### ISSUE TITLE
Null pointer exception in GeoFunctions::getEnvelope

### ISSUE THREAD

**Issue by highker** [prestodb/presto#10027]
```
java.lang.NullPointerException
	at com.facebook.presto.plugin.geospatial.GeoFunctions.getEnvelope(GeoFunctions.java:597)
	at com.facebook.presto.plugin.geospatial.GeoFunctions.stXMax(GeoFunctions.java:246)
	at com.facebook.presto.$gen.PageFilter_<HIDDEN>.filter(Unknown Source)
	at com.facebook.presto.$gen.PageFilter_<HIDDEN>.filter(Unknown Source)
	at com.facebook.presto.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:87)
	at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:86)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:286)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:234)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

cc: @mbasmanova @zhenxiao

**Comment by mbasmanova** [comment]
This is probably the same issue as #9814 - GeoFunctions::getEnvelope throws NPE for Geometry Collections.

Mehrdad Honarkhah is changing ST_XMin/XMax/YMin/YMax functions to use `deserializeEnvelope`. That change will fix this problem and remove GeoFunctions::getEnvelope as it will no longer be used.

**Comment by mbasmanova** [comment]
I reproduced this issue with the following query:

```
select ST_XMin(ST_GeometryFromText('GEOMETRYCOLLECTION (POINT (5 1), LINESTRING (3 4, 4 4))')) LIMIT 10000
```

CC: @mehrdad-honarkhah
