### ISSUE TITLE
Flaky TestStateCompiler.testComplexStateEstimatedSize

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#10109]
```
[ERROR]   TestStateCompiler.testComplexStateEstimatedSize:333 expected [1823245] but found [1823221]
```

**Comment by findepi** [comment]
```
# ./mvnw -pl presto-main test -Dtest=TestStateCompiler#testComplexStateEstimatedSize # (invocationCount = 1000)

...

[INFO] Running com.facebook.presto.operator.aggregation.TestStateCompiler
[ERROR] Tests run: 1000, Failures: 5, Errors: 0, Skipped: 0, Time elapsed: 25.96 s <<< FAILURE! - in com.facebook.presto.operator.aggregation.TestStateCompiler
[ERROR] testComplexStateEstimatedSize(com.facebook.presto.operator.aggregation.TestStateCompiler)  Time elapsed: 0.015 s  <<< FAILURE!
java.lang.AssertionError: expected [1048120] but found [1047935]
	at com.facebook.presto.operator.aggregation.TestStateCompiler.testComplexStateEstimatedSize(TestStateCompiler.java:332)

[ERROR] testComplexStateEstimatedSize(com.facebook.presto.operator.aggregation.TestStateCompiler)  Time elapsed: 0.017 s  <<< FAILURE!
java.lang.AssertionError: expected [1899048] but found [1898863]
	at com.facebook.presto.operator.aggregation.TestStateCompiler.testComplexStateEstimatedSize(TestStateCompiler.java:361)

[ERROR] testComplexStateEstimatedSize(com.facebook.presto.operator.aggregation.TestStateCompiler)  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: expected [1899048] but found [1898932]
	at com.facebook.presto.operator.aggregation.TestStateCompiler.testComplexStateEstimatedSize(TestStateCompiler.java:361)

[ERROR] testComplexStateEstimatedSize(com.facebook.presto.operator.aggregation.TestStateCompiler)  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: expected [1899048] but found [1898932]
	at com.facebook.presto.operator.aggregation.TestStateCompiler.testComplexStateEstimatedSize(TestStateCompiler.java:361)

[ERROR] testComplexStateEstimatedSize(com.facebook.presto.operator.aggregation.TestStateCompiler)  Time elapsed: 0.012 s  <<< FAILURE!
java.lang.AssertionError: expected [1899048] but found [1898932]
	at com.facebook.presto.operator.aggregation.TestStateCompiler.testComplexStateEstimatedSize(TestStateCompiler.java:361)
```
