### ISSUE TITLE
Get com.facebook.presto.operator.PageTransportTimeoutException on newly installed Presto cluster

### ISSUE THREAD

**Issue by deeptideshpande** [prestodb/presto#10107]
We recently installed 0.184 version of Presto cluster. We have 56 workers and a coordinator. Presto cluster is colocated with Hadoop cluster. Following is our configuration of the presto cluster:

**Coordinator config:**
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
query.max-memory=210GB
query.max-memory-per-node=4GB
discovery-server.enabled=true
discovery.uri=http://********:8080

**JVM Config**
-server
-Xmx16G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-DHADOOP_USER_NAME=hdfs

When we run queries on the small tables (10 GB), presto cluster performs very well. Query executes in a second.

But when I run simple select queries on tables of size 350 GB, the query fails with following error:

`com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://10.50.1.164:8080/v1/task/20180307_010630_00005_638dd.2.32/results/47/0 - 6 failures, time since last success 61.07s)
	at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:383)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1126)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
	at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:518)
	at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:512)
	at io.airlift.http.client.jetty.JettyHttpClient$JettyResponseFuture.failed(JettyHttpClient.java:884)
	at io.airlift.http.client.jetty.JettyHttpClient$BufferingResponseListener.onComplete(JettyHttpClient.java:1123)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:457)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:528)
	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:129)
	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:122)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:708)
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	... 7 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
	... 8 more`

We tried increasing the heap size for presto but that did not help. Is there any other configuration tuning we can try?

**Comment by zhaiyuyong** [comment]
Full gc，please provide table structure. ORC?PARQUET？
