### ISSUE TITLE
version-0.193 print error:

### ISSUE THREAD

**Issue by pengyf584** [prestodb/presto#10111]
`java.lang.NullPointerException: maxSize is null`
`Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes.`
config 148 node 
mem 256G CPU 64.
the sql:
`
SELECT format_datetime(date_trunc('minute',dt.timevalue),'yyyy-MM-dd HH:mm:ss.S') timevalue, config_cfg_base_subapptype_appunicode.appid appunicode_cfg_base_subapptype_appid, dt.city city, config_cfg_base_subapptype_appunicode.app_type_l1 appunicode_cfg_base_subapptype_app_type_l1, config_cfg_base_subapptype_appunicode.app_type_l2 appunicode_cfg_base_subapptype_app_type_l2, dt.appunicode appunicode, dt.rat rat, dt.cellid cellid, config_vt_cfg_cell_venue_cellid.Scene_Id2 cellid_vt_cfg_cell_venue_Scene_Id2, config_vt_cfg_cell_venue_cellid.Scene_Id3 cellid_vt_cfg_cell_venue_Scene_Id3, config_vt_cfg_cell_venue_cellid.venueid cellid_vt_cfg_cell_venue_venueid, config_vt_cfg_cell_venue_cellid.Scene_Id1 cellid_vt_cfg_cell_venue_Scene_Id1, config_vt_cfg_cell_venue_cellid.Scene_Id4 cellid_vt_cfg_cell_venue_Scene_Id4, config_vt_cfg_base_terminal_tac_modelid.FACT_ID modelid_vt_cfg_base_terminal_tac_FACT_ID, config_vt_cfg_base_terminal_tac_modelid.CAT_ONE modelid_vt_cfg_base_terminal_tac_CAT_ONE, config_vt_cfg_base_terminal_tac_modelid.CAT_TWO modelid_vt_cfg_base_terminal_tac_CAT_TWO, config_vt_cfg_base_terminal_tac_modelid.TERMINALNAME modelid_vt_cfg_base_terminal_tac_TERMINALNAME, dt.modelid modelid, dt.msisdn msisdn, dt.imsi imsi, dt.imei imei, dt.usergroup usergroup, dt.USER_DINNER USER_DINNER ,SUM(kpi_nbrServicePv) kpi_nbrServicePv FROM st_cl_user_ne_app_15MIN dt LEFT JOIN (SELECT DISTINCT config_cfg_base_subapptype_appunicode.appid, config_cfg_base_subapptype_appunicode.appunicode, config_cfg_base_subapptype_appunicode.app_type_l1, config_cfg_base_subapptype_appunicode.app_type_l2 FROM config.cfg_base_subapptype config_cfg_base_subapptype_appunicode ) config_cfg_base_subapptype_appunicode ON cast(dt.appunicode as varchar(50)) = cast(config_cfg_base_subapptype_appunicode.appunicode as varchar(50)) LEFT JOIN (SELECT DISTINCT config_vt_cfg_cell_venue_cellid.Scene_Id2, config_vt_cfg_cell_venue_cellid.cellid, config_vt_cfg_cell_venue_cellid.Scene_Id3, config_vt_cfg_cell_venue_cellid.venueid, config_vt_cfg_cell_venue_cellid.Scene_Id1, config_vt_cfg_cell_venue_cellid.Scene_Id4 FROM config.vt_cfg_cell_venue config_vt_cfg_cell_venue_cellid ) config_vt_cfg_cell_venue_cellid ON cast(dt.cellid as varchar(50)) = cast(config_vt_cfg_cell_venue_cellid.cellid as varchar(50)) LEFT JOIN (SELECT DISTINCT config_vt_cfg_base_terminal_tac_modelid.FACT_ID, config_vt_cfg_base_terminal_tac_modelid.MODEL_ID, config_vt_cfg_base_terminal_tac_modelid.CAT_ONE, config_vt_cfg_base_terminal_tac_modelid.CAT_TWO, config_vt_cfg_base_terminal_tac_modelid.TERMINALNAME FROM config.vt_cfg_base_terminal_tac config_vt_cfg_base_terminal_tac_modelid ) config_vt_cfg_base_terminal_tac_modelid ON cast(dt.modelid as varchar(50)) = cast(config_vt_cfg_base_terminal_tac_modelid.MODEL_ID as varchar(50)) WHERE Day = 20180304 AND Minute = '1300' GROUP BY format_datetime(date_trunc('minute',dt.timevalue),'yyyy-MM-dd HH:mm:ss.S'), config_cfg_base_subapptype_appunicode.appid, dt.city, config_cfg_base_subapptype_appunicode.app_type_l1, config_cfg_base_subapptype_appunicode.app_type_l2, dt.appunicode, dt.rat, dt.cellid, config_vt_cfg_cell_venue_cellid.Scene_Id2, config_vt_cfg_cell_venue_cellid.Scene_Id3, config_vt_cfg_cell_venue_cellid.venueid, config_vt_cfg_cell_venue_cellid.Scene_Id1, config_vt_cfg_cell_venue_cellid.Scene_Id4, config_vt_cfg_base_terminal_tac_modelid.FACT_ID, config_vt_cfg_base_terminal_tac_modelid.CAT_ONE, config_vt_cfg_base_terminal_tac_modelid.CAT_TWO, config_vt_cfg_base_terminal_tac_modelid.TERMINALNAME, dt.modelid, dt.msisdn, dt.imsi, dt.imei, dt.usergroup, dt.USER_DINNER
`

**Comment by findepi** [comment]
This is one error or two? Please share stacktrace for `java.lang.NullPointerException: maxSize is null` (run CLI with `--debug`)

**Comment by pengyf584** [comment]
@findepi this is one error， the presto-cli report：Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://132.xxx:8883/v1/task/20180307_062038_00004_cu6nn,)the http://132.xxx:8883/v1/task/20180307_062038_00004_cu6nn show the java.lang.NullPointerException: maxSize is null error. the sql run on impala is ok ,but run presto failed .the impala metadata will loss some time ,so i want use presto instead of impala .but it seem that the performance may ..

**Comment by pengyf584** [comment]
the cli stack trace: com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://132.225.168.58:8883/v1/task/20180307_072025_00001_95q24.2.72/results/28/0 - 6 failures, time since last success 60.87s)
	at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:390)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
	at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:523)
	at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:517)
	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:540)
	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:129)
	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:122)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:748)
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
	... 8 more

**Comment by pengyf584** [comment]
com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://132.xx.xx.xx:8883/v1/task/20180307_072025_00001_95q24.2.72/results/28/0 - 6 failures, time since last success 60.87s)
	at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:390)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
	at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
	at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:523)
	at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:517)
	at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
	at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:459)
	at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:540)
	at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:129)
	at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:122)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:748)
	at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
	... 8 more

**Comment by sopel39** [comment]
It could be that worker is doing full GC. Is this a particular query that is failing or this happens from time to time? Are you using G1, e.g: `-XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent`?

**Comment by pengyf584** [comment]
@sopel39  the jvm.config:
 -server
 -Xmx120G
 -Xms10G
 -XX:CMSFullGCsBeforeCompaction=4
 -XX:+UseG1GC
 -XX:G1HeapRegionSize=32M
 -XX:+UseGCOverheadLimit
 -XX:+ExplicitGCInvokesConcurrent
 -XX:+HeapDumpOnOutOfMemoryError
 -XX:+ExitOnOutOfMemoryError

**Comment by pengyf584** [comment]
i want use presto instead of impala, because the impala ofter loss metadata .but the performance may..,the sql run ok in impala ,but run in presto is failed

**Comment by sopel39** [comment]
I would suggest to dump GC log so that it can be investigated further along with a query that is being executed:
```
-Xloggc:/tmp/gc.log
-XX:+PrintGCDetails
-XX:+PrintGCDateStamps
-XX:+PrintClassHistogramBeforeFullGC
-XX:+PrintClassHistogramAfterFullGC
```

**Comment by sopel39** [comment]
We also internally don't set `Xms`, just `Xmx`. I'm also not sure about `-XX:CMSFullGCsBeforeCompaction=4`

**Comment by pengyf584** [comment]
@sopel39 i have delete the XX:CMSFullGCsBeforeCompaction ,but have the same error ,the presto-cli error as this (Query 20180307_091545_00000_bhzr9 failed: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://132.225.1xx:8883/v1/task/20180307_091545_00000_bhzr9.2.9/results/28/0 - 6 failures, time since last success 73.16s)),the url(http://132.225.1xx:8883/v1/task/20180307_091545_00000_bhzr9.2.9/results/28/0 ) say this :java.lang.NullPointerException: maxSize is null
at java.util.Objects.requireNonNull(Objects.java:228)
	at com.facebook.presto.execution.SqlTaskManager.getTaskResults(SqlTaskManager.java:330)
	at com.facebook.presto.server.TaskResource.getResults(TaskResource.java:247)
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:68)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:527)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sopel39** [comment]
Which presto version is it? What query is it?

**Comment by pengyf584** [comment]
@sopel39 0.193,the gc.log did not have the fullgc word

**Comment by chafidz0000000** [comment]
Is it possible to clean up and optimize your SQL? For example, avoiding transformation in JOIN clauses. Casting every cellid as varchar(50) first before stating them in join clauses, so
`left join(
		select
			...
		from
			config.cfg_base_subapptype config_cfg_base_subapptype_appunicode
	) config_cfg_base_subapptype_appunicode on
	cast(dt.appunicode as varchar(50)) = cast(config_cfg_base_subapptype_appunicode.appunicode as varchar(50))`
become simply as
`from(
	select
		cast(dt.appunicode as varchar(50)),
		...
	from st_cl_user_ne_app_15MIN
	where
		day = 20180304
		and minute = '1300') dt
left join(
		select
			distinct cast(config_cfg_base_subapptype_appunicode.appid as varchar(50)),
			...
		from
			config.cfg_base_subapptype config_cfg_base_subapptype_appunicode
	) config_cfg_base_subapptype_appunicode on
	dt.appunicode = config_cfg_base_subapptype_appunicode.appunicode`
I assume _day_ and _minute_ are from _st_cl_user_ne_app_15MIN_

Filtering data as early as possible, will help a lot, if I'm not mistaken
