### ISSUE TITLE
Cannot create schema on S3 

### ISSUE THREAD

**Issue by rfcarter** [prestodb/presto#10162]
I get the following error when I try to create a schema on S3.

presto> CREATE SCHEMA hive.web WITH (location = 's3://rfc-l0-test');
Query 20180314_213709_00002_fdxzi failed: Access Denied: Cannot create schema web

The version is Presto 0.196.

**Comment by nezihyigitbasi** [comment]
Can you start presto-cli with `--debug` and share the entire stack trace?

**Comment by rfcarter** [comment]
Query 20180315_181248_00001_wprvi failed: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
com.facebook.presto.spi.PrestoException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:322)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.createDatabase(BridgingHiveMetastore.java:121)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:381)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:381)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$createDatabase$2(SemiTransactionalHiveMetastore.java:271)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:744)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:1509)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:177)
	at com.facebook.presto.transaction.TransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(TransactionManager.java:577)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:14412)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:14380)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result.read(ThriftHiveMetastore.java:14314)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_database(ThriftHiveMetastore.java:625)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_database(ThriftHiveMetastore.java:612)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastoreClient.createDatabase(ThriftHiveMetastoreClient.java:96)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$createDatabase$10(ThriftHiveMetastore.java:313)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:137)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:311)
	... 16 more

presto>

**Comment by electrum** [comment]
@rfcarter I see you closed the issue. Did you figure out the problem?

Reading the stack trace, it appears this error comes from the metastore, which is probably trying to validate the location and fails because it doesn't have the Hadoop `S3AFileSystem` class.

**Comment by rfcarter** [comment]
Sorry, the close was a mistake.

**Comment by rfcarter** [comment]
How do I add Hadoop S3AFileSystem?

**Comment by rfcarter** [comment]
I have gotten past my original issue but now I get the following when trying to create a schema. I am not using AWS S3. I am using S3 compatible storage. 

presto> create schema hive.pdr with (location='s3a://rfc-l0-test');
Query 20180315_222435_00001_zzhsz failed: java.lang.IllegalArgumentException: Can not create a Path from an empty string
com.facebook.presto.spi.PrestoException: java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:322)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.createDatabase(BridgingHiveMetastore.java:121)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:381)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.createDatabase(CachingHiveMetastore.java:381)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$createDatabase$2(SemiTransactionalHiveMetastore.java:271)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:744)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:1509)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:177)
	at com.facebook.presto.transaction.TransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(TransactionManager.java:577)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.IllegalArgumentException: Can not create a Path from an empty string
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:14412)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result$create_database_resultStandardScheme.read(ThriftHiveMetastore.java:14380)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_database_result.read(ThriftHiveMetastore.java:14314)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_database(ThriftHiveMetastore.java:625)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_database(ThriftHiveMetastore.java:612)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastoreClient.createDatabase(ThriftHiveMetastoreClient.java:96)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$createDatabase$10(ThriftHiveMetastore.java:313)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:137)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.createDatabase(ThriftHiveMetastore.java:311)
	... 16 more

presto>

**Comment by rfcarter** [comment]
I fixed the problem above. I did not have a / at the end of the location.

**Comment by denkoRa** [comment]
@rfcarter  Do you recall how you solved the first problem here? I am facing the same issue.

**Comment by njalan** [comment]
@rfcarter May I know how did you fix the issue?
