### ISSUE TITLE
LDAP Password authenticator is not registered

### ISSUE THREAD

**Issue by jkairys** [prestodb/presto#10165]
I'm trying to configure an instance of 0.196 using LDAP authentication. I have followed the updated installation procedure at https://prestodb.io/docs/current/security/ldap.html, but I can't get the server to start, getting an error that suggests that the ldap password authenticator isn't registered. 

Do I need to download a plugin from somewhere?

Relevant log error message and configuration settings below.

```
2018-03-15T04:54:58.025Z	INFO	main	com.facebook.presto.security.AccessControlManager	-- Loading system access control --
2018-03-15T04:54:58.026Z	INFO	main	com.facebook.presto.security.AccessControlManager	-- Loaded system access control allow-all --
2018-03-15T04:54:58.028Z	INFO	main	com.facebook.presto.server.security.PasswordAuthenticatorManager	-- Loading password authenticator --
2018-03-15T04:54:58.028Z	ERROR	main	com.facebook.presto.server.PrestoServer	Password authenticator ldap is not registered
java.lang.IllegalStateException: Password authenticator ldap is not registered
	at com.google.common.base.Preconditions.checkState(Preconditions.java:518)
	at com.facebook.presto.server.security.PasswordAuthenticatorManager.loadPasswordAuthenticator(PasswordAuthenticatorManager.java:72)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:131)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

My config.properties includes:
```
http-server.authentication.type=PASSWORD
http-server.http.port=8080
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/etc/presto/keystore.jks
http-server.https.keystore.key=<KEYSTORE_KEY>
```
And my password-authenticator.properties file includes:
```
password-authenticator.name=ldap
ldap.url=ldaps://ldap.server.url
ldap.user-bind-pattern=${USER}@domain.name
```

Thanks in advance!

**Comment by findepi** [comment]
In your server `plugin` dir, do you have `/password-authenticators` sub-dir with `presto-password-authenticators-0.196.jar` (and bunch of other jars)?

**Comment by jkairys** [comment]
Yes I do, but your question prompted me to check where presto was looking for plugins. Turns out my `node.properties` configuration file was telling presto to look in the wrong place. After setting `plugin.dir=/opt/presto/plugin`, presto starts as expected. Thanks for the suggestion and apologies for the noob error!
