### ISSUE TITLE
NullPointerException in PartitionedLookupSourceFactory

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#10238]
```
java.lang.NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:236)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:220)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:291)
	at com.facebook.presto.operator.PartitionedLookupSourceFactory.supplyLookupSources(PartitionedLookupSourceFactory.java:260)
	at com.facebook.presto.operator.PartitionedLookupSourceFactory.lendPartitionLookupSource(PartitionedLookupSourceFactory.java:189)
	at com.facebook.presto.operator.HashBuilderOperator.finishInput(HashBuilderOperator.java:509)
	at com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:458)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:399)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by findepi** [comment]
I see this seems possible when 
- `PartitionedLookupSourceFactory.supplyLookupSources` and
- `PartitionedLookupSourceFactory.freePartitions`
coincide; or when `freePartitions()` is called before, but `HashBuilderOperator` continues to work somehow.

This seems to be possible when query is aborted and `PLSF` gets destroyed before `HBO` is stopped (might be just a matter of ordering).

@haozhun, i don't know the bucket-by-bucket code -- is it possible that when `SharedInternalLookupSourceFactoryManager` is used ("N probe, 1 lookup source"), `N` happens to actually be 0 and probe side is determined empty before build side is completed? If that could be possible then, `SharedInternalLookupSourceFactoryManager.referenceCount.listener` could trigger `PLSF` destruction before `HBO` is stopped.


@electrum do you happen to have usable repro query?

**Comment by findepi** [comment]
This is closed, but https://github.com/prestodb/presto/issues/10258 remains.
