### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException in geometry_to_bing_tiles

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#10276]
```
PrestoQueryError: java.lang.ArrayIndexOutOfBoundsException: 1590457587 
	at com.facebook.presto.spi.block.LongArrayBlockBuilder.writeLong(LongArrayBlockBuilder.java:63) 
	at com.facebook.presto.spi.type.AbstractLongType.writeLong(AbstractLongType.java:66) 
	at com.facebook.presto.plugin.geospatial.BingTileFunctions.writeTilesToBlockBuilder(BingTileFunctions.java:300) 
	at com.facebook.presto.plugin.geospatial.BingTileFunctions.geometryToBingTiles(BingTileFunctions.java:207) 
	at com.facebook.presto.$gen.PageProjectionWork_20180327_232031_05145_43rh8_2_2_1233773.lambda_1(Unknown Source) 
	at com.facebook.presto.operator.scalar.TryFunction.tryBlock(TryFunction.java:105) 
	at com.facebook.presto.$gen.PageProjectionWork_20180327_232031_05145_43rh8_2_2_1233773.evaluate(Unknown Source) 
	at com.facebook.presto.$gen.PageProjectionWork_20180327_232031_05145_43rh8_2_2_1233773.process(Unknown Source) 
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:275) 
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:180) 
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:127) 
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145) 
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140) 
	at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:49) 
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:110) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:295) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:234) 
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379) 
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278) 
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645) 
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272) 
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975) 
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162) 
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492) 
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
	at java.base/java.lang.Thread.run(Thread.java:844) 
```

**Comment by mbasmanova** [comment]
This error is trigged by BingTileFunctions#geometryToBingTiles failing to check geometry limits due to integer overflow in the following computation:

```
int tileCount = toIntExact((rightLowerTile.getX() - leftUpperTile.getX() + 1) * (rightLowerTile.getY() - leftUpperTile.getY() + 1));
```

@arhimondr Andrii, thank you for helping to find this out.
