### ISSUE TITLE
Query failed: Unable to load credentials from service endpoint

### ISSUE THREAD

**Issue by sbmaggarwal** [prestodb/presto#10298]
I am trying to connect to S3 Bucket from the hive catalog in PrestoDB from HDP VM by Teradata.

For this, I configured the `hive-site.xml` file and added my AWS Access Key and Secret Key in the `/etc/hive/conf/hive-site.xml` file like:

    <property>
      <name>hive.s3.aws-access-key</name>
      <value>something</value>
    </property>
    <property>
      <name>hive.s3.aws-secret-key</name>
      <value>some-other-thing</value>
    </property>

Now, my S3 Bucket URL path where `Parquet` files reside looks like:

    https://s3.console.aws.amazon.com/s3/buckets/sb.mycompany.com/someFolder/anotherFolder/?region=us-east-2&tab=overview

While Create an external table, I gave the location for S3 in the query as:

    CREATE TABLE hive.project.data (... schema ...)
    WITH ( format = 'PARQUET', 
      external_location = 's3://sb.mycompany.com/someFolder/anotherFolder/?region=us-east-2&tab=overview')

PrestoDB **isn't able to connect** to S3 Buckets and giving this error:

    Query 20180316_063813_11114_z22jg failed: Unable to load credentials from service endpoint

I even restarted my PrestDB server after I added the Keys. Next, I tried adding my properties to `/home/presto/.prestoadmin/catalog/hive.properties`:

    connector.name=hive-hadoop2
    hive.metastore.uri=thrift://localhost:9083
    hive.allow-drop-table=true
    hive.allow-rename-table=true
    hive.time-zone=UTC
    hive.metastore-cache-ttl=0s
    hive.s3.use-instance-credentials=false
    hive.s3.aws-access-key=something
    hive.s3.aws-secret-key=some-other-thing

Again restarted the PrestoDB server but still the same issue. 

I then modified the S3 Bucket location in query with bucket name only:

    external_location = 's3://sb.mycompany.com'

And with `s3a` scheme as well:

    external_location = 's3a://sb.mycompany.com'

But the same issue is still present. What am I doing wrong?

  [1]: https://prestodb.io/

**Comment by findepi** [comment]
> Next, I tried adding my properties to /home/presto/.prestoadmin/catalog/hive.properties:
> ...
> Again restarted the PrestoDB server but still the same issue.

Did you also run [`presto-admin configuration deploy`](https://prestodb.io/presto-admin/docs/current/presto-admin-commands.html#configuration-deploy), before restarting Presto?

**Comment by sbmaggarwal** [comment]
@findepi Just tried this. Still the same issue. Any other information I can provide to make things more clear?

**Comment by rentaow** [comment]
XML configuration files eg, hive-site.xml needs to be appended to ```hive.config.resources```  in your ```hive.properties``` file I think.

You should be able to set ```hive.s3.aws-access-key``` & ```hive.s3.aws-secret-key``` directly in ```hive.properties``` as well.

https://prestodb.io/docs/current/connector/hive.html#configuration

**Comment by nezihyigitbasi** [comment]
@sbmaggarwal Can you run the presto-cli with `--debug` and share the full stacktrace?

**Comment by sbmaggarwal** [comment]
@nezihyigitbasi Yes, I get this:

```
Query 20180316_112407_00005_aj9x6 failed: Unable to load credentials from service endpoint

=========   TECHNICAL DETAILS   =========
[ Error message ]
Unable to load credentials from service endpoint

[ Session information ]
ClientSession{server=http://localhost:8080, user=presto, clientInfo=null, catalog=null, schema=null, timeZone=Zulu, locale=en_US, properties={}, transactionId=null, debug=true, quiet=false}

[ Stack trace ]
com.amazonaws.AmazonClientException: Unable to load credentials from service endpoint
	at com.amazonaws.auth.EC2CredentialsFetcher.handleError(EC2CredentialsFetcher.java:180)
	at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:159)
	at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:104)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4016)
	at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:4478)
	at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:4452)
	at com.amazonaws.services.s3.AmazonS3Client.resolveServiceEndpoint(AmazonS3Client.java:4426)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1167)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1152)
	at com.facebook.presto.hive.PrestoS3FileSystem.lambda$getS3ObjectMetadata$2(PrestoS3FileSystem.java:552)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:138)
	at com.facebook.presto.hive.PrestoS3FileSystem.getS3ObjectMetadata(PrestoS3FileSystem.java:549)
	at com.facebook.presto.hive.PrestoS3FileSystem.getFileStatus(PrestoS3FileSystem.java:305)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1439)
	at com.facebook.presto.hive.HiveMetadata.getExternalPath(HiveMetadata.java:719)
	at com.facebook.presto.hive.HiveMetadata.createTable(HiveMetadata.java:690)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:218)
	at com.facebook.presto.metadata.MetadataManager.createTable(MetadataManager.java:505)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:148)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:57)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:111)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Network is unreachable
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:47)
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:106)
	at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:77)
	at com.amazonaws.auth.InstanceProfileCredentialsProvider$InstanceMetadataCredentialsEndpointProvider.getCredentialsEndpoint(InstanceProfileCredentialsProvider.java:117)
	at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:121)
	... 24 more
========= TECHNICAL DETAILS END =========
```
Should I try the `s3cmd` command to download a sample file? I can download the files using the access keys on the laptop through `s3cmd` but haven't tried the same on VM.

**Comment by electrum** [comment]
This looks like a network / firewall issue:
```
Caused by: java.net.ConnectException: Network is unreachable
```
Please verify you can connect to S3 from the same VM. Try using `s3cmd` or `curl`.

**Comment by sbmaggarwal** [comment]
@electrum That was the issue. In the Cloudera VM, there was an issue with networking and was reported earlier as well. I configured the network adapter and the issue was solved. Thanks a lot for the guidance.

**Comment by sbmaggarwal** [comment]
@electrum Actually, I reset the network adapter and I am still getting this error. Note that I can run this command when I am a root user:
    yum update

When I am a `presto` user, I get:
```
[presto@presto-demo ~]$ sudo yum install s3cmd
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.nbrc.ac.in
 * extras: mirror.nbrc.ac.in
 * updates: mirror.nbrc.ac.in
No package s3cmd available.
Error: Nothing to do
[presto@presto-demo ~]$
```
But as the `update` command updated al packages, I can assume that networking is running fine. Does this mean that only the presto user doesn't have the Internet access?

**Comment by electrum** [comment]
The “yum” command might be setup to use a proxy or have a special firewall rule. Try this:

curl -v https://s3.amazonaws.com/

Check if it works and look in the verbose output to see if it’s using a proxy.

**Comment by rabinnh** [comment]
Try adding a trailing '/' to the bucket location.

**Comment by sbmaggarwal** [comment]
This wasn't an issue with presto but the VM.
