### ISSUE TITLE
Regression in querying information schema

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#10397]
One of our internal connector integration test fails with the exception below. With commit 484c2bac122779e7ebedc4f615a5d0a2fa8d7f6c `InformationSchemaMetadata.getTableLayouts()` now creates instances of `QualifiedTablePrefix`, which will fail for names that contain uppercase characters. The failing test just runs `SHOW SCHEMAS` against our internal connector and we have many schemas with names that have uppercase characters. /cc @kokosing 

```
      java.lang.RuntimeException: schemaName is not lowercase: DataLineage
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:113)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:362)
	at com.facebook.presto.tests.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:109)
	at com.facebook.presto.tests.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:104)
	at com.facebook.presto.test.TestIntegrationSmokeTest.testShowSchemas(TestIntegrationSmokeTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: schemaName is not lowercase: DataLineage
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:437)
	at com.facebook.presto.metadata.MetadataUtil.checkLowerCase(MetadataUtil.java:82)
	at com.facebook.presto.metadata.MetadataUtil.checkSchemaName(MetadataUtil.java:62)
	at com.facebook.presto.metadata.QualifiedTablePrefix.<init>(QualifiedTablePrefix.java:45)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.lambda$calculatePrefixesWithSchemaName$2(InformationSchemaMetadata.java:259)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:64)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:64)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.calculatePrefixesWithSchemaName(InformationSchemaMetadata.java:260)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.getTableLayouts(InformationSchemaMetadata.java:222)
	at com.facebook.presto.metadata.MetadataManager.getLayouts(MetadataManager.java:343)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.planTableScan(PickTableLayout.java:196)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.access$200(PickTableLayout.java:60)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutWithoutPredicate.apply(PickTableLayout.java:179)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutWithoutPredicate.apply(PickTableLayout.java:148)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:141)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:104)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:193)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:95)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:140)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:129)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:310)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:295)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:251)
	... 3 more
```

**Comment by findepi** [comment]
@nezihyigitbasi @kokosing  since presto treats object names case insensitively (lowercasing everything), would it be enough to lowercase before constructing `QualifiedTablePrefix`?

is your internal connector a `base-jdbc`-based? this could be reproducible with mysql connector perhaps

**Comment by kokosing** [comment]
@nezihyigitbasi Potential fix is here: #10400
