### ISSUE TITLE
Unable to use multiple kerberos realms

### ISSUE THREAD

**Issue by jasper-eb** [prestodb/presto#10412]
Presto version: 0.197

I have two hive-hadoop2 catalogs, which use two different realms. The only catalog that works is the catalog who's realm is default. The catalog which is not in the default realm will return a `org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to principal/domain@REALM.COM` error (full stacktrace below). Once I swap the default realm, the same behvior will happen, but with the other catalog. 

I have confirmed that the principal properly maps to both sources, which is also evident through queries succeeding on the default realm catalog and running `hadoop org.apache.hadoop.security.HadoopKerberosName`. Could this be caused by presto not succeeding in creating the UGI from the non-default realm? Enabling `-Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true` shows the presto communicating to the correct KDC.

```
java.lang.IllegalArgumentException: Illegal principal name principal/domain@REALM.COM: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to principal/comain@REALM.COM
	at org.apache.hadoop.security.User.<init>(User.java:51)
	at org.apache.hadoop.security.UserGroupInformationShim.createUserGroupInformationForSubject(UserGroupInformationShim.java:45)
	at com.facebook.presto.hive.authentication.KerberosHadoopAuthentication.getUserGroupInformation(KerberosHadoopAuthentication.java:52)
	at com.facebook.presto.hive.authentication.CachingKerberosHadoopAuthentication.refreshUgi(CachingKerberosHadoopAuthentication.java:56)
	at com.facebook.presto.hive.authentication.CachingKerberosHadoopAuthentication.getUserGroupInformation(CachingKerberosHadoopAuthentication.java:48)
	at com.facebook.presto.hive.authentication.KerberosHiveMetastoreAuthentication.authenticate(KerberosHiveMetastoreAuthentication.java:75)
	at com.facebook.presto.hive.metastore.thrift.Transport.create(Transport.java:44)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreClientFactory.create(HiveMetastoreClientFactory.java:58)
	at com.facebook.presto.hive.metastore.thrift.StaticHiveCluster.createMetastoreClient(StaticHiveCluster.java:75)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$getTable$5(ThriftHiveMetastore.java:206)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:137)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getTable(ThriftHiveMetastore.java:205)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getTable(BridgingHiveMetastore.java:77)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:255)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:182)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:208)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getTable(CachingHiveMetastore.java:250)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:255)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:182)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:208)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getTable(CachingHiveMetastore.java:250)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getTable(SemiTransactionalHiveMetastore.java:135)
	at com.facebook.presto.hive.HiveMetadata.getViews(HiveMetadata.java:1096)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getViews(ClassLoaderSafeConnectorMetadata.java:328)
	at com.facebook.presto.metadata.MetadataManager.getView(MetadataManager.java:788)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:782)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:253)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:265)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1866)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:947)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:253)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:265)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:275)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:676)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:253)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:265)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:239)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:72)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:357)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:343)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to principal/domain@REALM.COM
	at org.apache.hadoop.security.authentication.util.KerberosName.getShortName(KerberosName.java:400)
	at org.apache.hadoop.security.User.<init>(User.java:48)
	... 67 more
```

**Comment by phd1994** [comment]
Hi,

This issue also seems to be there in the latest release. I have done some investigation on it. When the Kerberos User is in the same realm as the server, the DEFAULT rule successfully extracts shortName as a special case. In other cases, it fails to do the same. Even if the rules are present in hive.config.resources, they are not carried over to KerberosHadoopAuthentication. 

I would like to take this up and create a PR soon. @martint Could you please assign it to me?

**Comment by kokosing** [comment]
It looks like nobody is actively working on this, so please go ahead.

**Comment by SanjayJosh** [comment]
It looks like this feature, for multiple realms is still not supported. Isn't it so?

**Comment by sopel39** [comment]
I think it's fixed

**Comment by SanjayJosh** [comment]
I don't think so. It doesn't look like you can use two hive-hadoop catalogues that use two different realms yet. I still get the same error:

`[myuser@presto-server ~]$ presto-cli --catalog dev1s0
presto> show schemas;
Query 20180913_064131_00036_if4ji failed: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Illegal principal name myuser@HADOOP_MACHINE1.REALM.1COM: org.apache.hadoop.security.authentication.util.KerberosName$NoMatchingRule: No rules applied to myuser@HADOOP_MACHINE.REALM.1COM`

The `/etc/krb5.conf` that I have has the default realm for another catalog dev2s0 that goes through fine for the principal ` myuser@HADOOP_MACHINE2.REALM.2COM` ,which is the same value as that of the default realm in the conf.

At least from what I have observed, with 0.210, it doesn't seem to work.

**Comment by sopel39** [comment]
Do you have `hadoop.security.auth_to_local` configured in `core-site.xml`?

**Comment by SanjayJosh** [comment]
@sopel39 .  Yes I do have bunch of rules picked up from my hadoop cluster's core-site.xml.
Is there something specific I should be looking at?

**Comment by sopel39** [comment]
>  Yes I do have bunch of rules picked up from my hadoop cluster's core-site.xml.
Is there something specific I should be looking at?

At least one rule should match your `myuser@HADOOP_MACHINE1.REALM1.COM`.

**Comment by SanjayJosh** [comment]
Well now the new problem that arises is this : 

`Failed connecting to Hive metastore:  [meta_store_thrift_url:9083]`

**Comment by lai-aa** [comment]
I think it is known issue which is only one Kerberos realm can be supported per JVM, via https://bugs.openjdk.java.net/browse/JDK-8129742. not so sure about whether we have any special handling in Presto or not.
