### ISSUE TITLE
Mismatched Domain Types error when using predicate pushdown on a complex type (array) with Parquet 

### ISSUE THREAD

**Issue by piyushnarang** [prestodb/presto#10415]
Table we're trying to query has a complex type `products: array<struct<field1: int, field2: int>>`. 

The predicate we have in place is to check if products is not null:
```
select userid, campaignid, products from my_table where day='2018-04-16' and products IS NOT NULL limit 10;
```

When we have `set session hive.parquet_predicate_pushdown_enabled=true;`, we end up running into this error:

```
Query 20180416_161626_00054_mdwtu failed: Error opening Hive split hdfs://root/user/ads/perf_data/my_table/day=2018-04-16/hour=23/host_platform=EU/000004_0 (offset=0, length=33554432): Mismatched Domain types: array(row(field1(integer), field2(integer))) vs integer
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:380)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:160)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createRecordCursor(ParquetRecordCursorProvider.java:93)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:158)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:88)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:224)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Mismatched Domain types: array(row(field1(integer), field2(integer))) vs integer
	at com.facebook.presto.spi.predicate.Domain.checkCompatibility(Domain.java:229)
	at com.facebook.presto.spi.predicate.Domain.intersect(Domain.java:184)
	at com.facebook.presto.spi.predicate.TupleDomain.intersect(TupleDomain.java:197)
	at com.facebook.presto.spi.predicate.TupleDomain.overlaps(TupleDomain.java:300)
	at com.facebook.presto.hive.parquet.predicate.TupleDomainParquetPredicate.matches(TupleDomainParquetPredicate.java:94)
	at com.facebook.presto.hive.parquet.predicate.ParquetPredicateUtils.predicateMatches(ParquetPredicateUtils.java:109)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:350)
	... 17 more
```

Digging into this a bit it seems like the issue is due to [ParquetTypeUtils.getPathIndex](https://github.com/prestodb/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/parquet/ParquetTypeUtils.java#L73) returning the index of the last field in the struct (`field2`). This ultimately results in the mismatch down the line. 

From what I understand, Parquet doesn't have statistics in place for complex types (just for primitives) so I'm not sure if trying to apply the predicate for this field is the right thing to do. I'm wondering if the right approach would be to skip complex fields from the list of predicates passed to the TupleDomain?
Thoughts @zhenxiao / @nezihyigitbasi ?

**Comment by nezihyigitbasi** [comment]
>> I'm wondering if the right approach would be to skip complex fields from the list of predicates passed to the TupleDomain?

I think this sounds like a reasonable workaround. Can you create a pull request?

**Comment by piyushnarang** [comment]
Sure, I'll take a stab at it and tag you. Thanks.

**Comment by nezihyigitbasi** [comment]
Fixed by #10436.

**Comment by hustnn** [comment]
@nezihyigitbasi @piyushnarang 

Thanks for your effort. Can I know which version has included this patch?

**Comment by piyushnarang** [comment]
@hustnn - I believe it should be in release 0.200 onwards.
