### ISSUE TITLE
LEFT JOIN fails with "A fixed distribution is required for JOIN when spilling is enabled"

### ISSUE THREAD

**Issue by chadjefferies** [prestodb/presto#10428]
I've started experimenting with enabling spilling on a 3 node cluster. 

It seems when a query on the right side of a LEFT JOIN has a non-existent partition, the query consistently fails with `A fixed distribution is required for JOIN when spilling is enabled`. This query otherwise runs fine with spilling disabled.

On the Presto user forum, @findepi indicated this is caused by 
>The planner created a plan where spilling is not possible to do

Here is the full stack trace:
```
java.lang.IllegalStateException: A fixed distribution is required for JOIN when spilling is enabled
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.getJoinOperatorsCountForSpill(LocalExecutionPlanner.java:2008)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.createLookupJoin(LocalExecutionPlanner.java:1988)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.createLookupJoin(LocalExecutionPlanner.java:1821)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitJoin(LocalExecutionPlanner.java:1526)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitJoin(LocalExecutionPlanner.java:646)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:221)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1115)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1075)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:646)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:425)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:396)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:83)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:350)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:324)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:129)
	at sun.reflect.GeneratedMethodAccessor502.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:69)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:64)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:455)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748) 
```

Here are steps to reproduce the error:
```
CREATE TABLE customers (
  email varchar,
  companyid int
)
WITH (
  format = 'PARQUET',
  partitioned_by = ARRAY['companyid']
);

CREATE TABLE orders (
  email varchar,
  companyid int
)
WITH (
  format = 'PARQUET',
  partitioned_by = ARRAY['companyid']
);

INSERT INTO customers VALUES('abc@email.com', 1234);

SELECT *
FROM customers c
LEFT JOIN orders o ON c.companyid = o.companyid and c.email = o.email
WHERE c.companyid  = 1234;
```

Thanks for your time!

**Comment by sopel39** [comment]
Please attach a plan as you did in Google Groups. It seems that join side being partitioned on `companyid` allows to skip local round robin, but it is required for spill to work.

`com/facebook/presto/sql/planner/optimizations/AddLocalExchanges.java:457` probably needs to be investigated:
```
            if (isSpillEnabled(session)) {
                probe = planAndEnforce(
                        node.getLeft(),
                        fixedParallelism(),
                        parentPreferences.constrainTo(node.getLeft().getOutputSymbols()).withFixedParallelism());
            }
```

This should work since `StreamPropertyDerivations.Visitor#visitTableScan` returns `MULTIPLE` stream property...

**Comment by chadjefferies** [comment]
Sure thing.

```
explain SELECT *
FROM customers c
LEFT JOIN orders o ON c.companyid = o.companyid and c.email = o.email
WHERE c.companyid  = 1234
```

```
- Output[email, companyid, email, companyid] => [email:varchar, companyid:integer, email_0:varchar, companyid_1:integer]
        Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
        email := email_0
        companyid := companyid_1
    - RemoteExchange[GATHER] => email:varchar, companyid:integer, email_0:varchar, companyid_1:integer
            Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: ?}
        - LeftJoin[("companyid" = "companyid_1") AND ("email" = "email_0")][$hashvalue, $hashvalue_22] => [email:varchar, companyid:integer, email_0:varchar, companyid_1:integer]
                Distribution: REPLICATED
                Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
            - ScanProject[table = hive:scratch:customers, originalConstraint = (1234 = "companyid")] => [email:varchar, companyid:integer, $hashvalue:bigint]
                    Cost: {rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}/{rows: ? (?), cpu: ?, memory: 0.00, network: 0.00}
                    $hashvalue := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("companyid"), 0)), COALESCE("$operator$hash_code"("email"), 0))
                    LAYOUT: scratch.customers
                    companyid := HiveColumnHandle{name=companyid, hiveType=int, hiveColumnIndex=-1, columnType=PARTITION_KEY}
                        :: [[1234]]
                    email := HiveColumnHandle{name=email, hiveType=string, hiveColumnIndex=0, columnType=REGULAR}
            - LocalExchange[HASH][$hashvalue_22] ("companyid_1", "email_0") => email_0:varchar, companyid_1:integer, $hashvalue_22:bigint
                    Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}
                - RemoteExchange[REPLICATE] => email_0:varchar, companyid_1:integer, $hashvalue_23:bigint
                        Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}
                    - FilterProject[filterPredicate = (1234 = "companyid_1")] => [email_0:varchar, companyid_1:integer, $hashvalue_26:bigint]
                            Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}/{rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}
                            $hashvalue_26 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("companyid_1"), 0)), COALESCE("$operator$hash_code"("email_0"), 0))
                        - Project[] => [email_0:varchar, companyid_1:integer]
                                Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}
                            - LocalExchange[ROUND_ROBIN] () => email_0:varchar, companyid_1:integer, $hashvalue_24:bigint
                                    Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}
                                - Project[] => [email_0:varchar, companyid_1:integer, $hashvalue_25:bigint]
                                        Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}
                                        $hashvalue_25 := "combine_hash"("combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("companyid_1"), 0)), COALESCE("$operator$hash_code"("email_0"), 0))
                                    - Values => [email_0:varchar, companyid_1:integer]
                                            Cost: {rows: 0 (0B), cpu: 0.00, memory: 0.00, network: 0.00}

```

**Comment by findepi** [comment]
@chadjefferies 
on the user group you included also the following:
```
SHOW SESSION
...
spill_enabled | FALSE | FALSE | boolean | Experimental: Enable spilling
```

This means you do not have spill enabled, at least not on the coordinator.
However, the exception says spill is enabled... 

The only way I could repro the problem using DDLs you provided was by setting `experimental.spill-enabled = true` on workers, but not on the coordinator. Of course, this is not valid configuration. Workers and coordinator needs to have exact same configuration (for almost everything except `coordinator = {true,false}`).

As I said earlier:
> The exception means that we planner created a plan where spilling is not possible to do. Of course, this should not happen.

Planner (which is part of the coordinator) won't alter plan to make it spill-friendly if the coordinator is not aware of spill.

Can you please make sure that `experimental.spill-enabled` is set to the same value on *all* nodes?

**Comment by chadjefferies** [comment]
@findepi Thank you very much for your time with this issue. You are correct, I did have the coordinator misconfigured. Everything looks good now. Thanks again!
