### ISSUE TITLE
JDBC driver incompatible with Java 9.

### ISSUE THREAD

**Issue by mikebell90** [prestodb/presto#10435]
>Presto 0.196
>Consuming app compiled under Java 8 build 152

When run under Java 9:

2018-04-17T23:59:34.086Z ERROR <> [RewindRaptorData-13] c.o.presto.sql.PrestoSQLExecution - Connection attempt failed 
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/facebook/presto/jdbc/ConnectionProperty. Method lambda$getRequiredValue$0()Ljava/sql/SQLException; at index 43 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at com.facebook.presto.jdbc.ConnectionProperty.getRequiredValue(ConnectionProperty.java:41)
	at com.facebook.presto.jdbc.PrestoDriverUri.getUser(PrestoDriverUri.java:123)
	at com.facebook.presto.jdbc.PrestoConnection.<init>(PrestoConnection.java:97)
	at com.facebook.presto.jdbc.PrestoDriver.connect(PrestoDriver.java:91)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.opentable.presto.sql.PrestoSQLExecution.connection(PrestoSQLExecution.java:100)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at com.opentable.presto.sql.PrestoSQLExecution.connectionWithRetries(PrestoSQLExecution.java:92)
	at com.opentable.presto.kafka.RewindRaptorData.rewind(RewindRaptorData.java:113)
	at com.opentable.presto.kafka.RewindRaptorData.lambda$null$0(RewindRaptorData.java:81)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-04-17T23:59:34.086Z ERROR <> [RewindRaptorData-13] c.o.presto.sql.PrestoSQLExecution - Failed to create connection 
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/facebook/presto/jdbc/ConnectionProperty. Method lambda$getRequiredValue$0()Ljava/sql/SQLException; at index 43 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at com.facebook.presto.jdbc.ConnectionProperty.getRequiredValue(ConnectionProperty.java:41)
	at com.facebook.presto.jdbc.PrestoDriverUri.getUser(PrestoDriverUri.java:123)
	at com.facebook.presto.jdbc.PrestoConnection.<init>(PrestoConnection.java:97)
	at com.facebook.presto.jdbc.PrestoDriver.connect(PrestoDriver.java:91)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.opentable.presto.sql.PrestoSQLExecution.connection(PrestoSQLExecution.java:100)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at com.opentable.presto.sql.PrestoSQLExecution.connectionWithRetries(PrestoSQLExecution.java:92)
	at com.opentable.presto.kafka.RewindRaptorData.rewind(RewindRaptorData.java:113)2018-04-17T23:59:34.086Z ERROR <> [RewindRaptorData-13] c.o.presto.sql.PrestoSQLExecution - Connection attempt failed 
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/facebook/presto/jdbc/ConnectionProperty. Method lambda$getRequiredValue$0()Ljava/sql/SQLException; at index 43 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at com.facebook.presto.jdbc.ConnectionProperty.getRequiredValue(ConnectionProperty.java:41)
	at com.facebook.presto.jdbc.PrestoDriverUri.getUser(PrestoDriverUri.java:123)
	at com.facebook.presto.jdbc.PrestoConnection.<init>(PrestoConnection.java:97)
	at com.facebook.presto.jdbc.PrestoDriver.connect(PrestoDriver.java:91)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.opentable.presto.sql.PrestoSQLExecution.connection(PrestoSQLExecution.java:100)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at com.opentable.presto.sql.PrestoSQLExecution.connectionWithRetries(PrestoSQLExecution.java:92)
	at com.opentable.presto.kafka.RewindRaptorData.rewind(RewindRaptorData.java:113)
	at com.opentable.presto.kafka.RewindRaptorData.lambda$null$0(RewindRaptorData.java:81)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-04-17T23:59:34.086Z ERROR <> [RewindRaptorData-13] c.o.presto.sql.PrestoSQLExecution - Failed to create connection 
java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class com/facebook/presto/jdbc/ConnectionProperty. Method lambda$getRequiredValue$0()Ljava/sql/SQLException; at index 43 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at com.facebook.presto.jdbc.ConnectionProperty.getRequiredValue(ConnectionProperty.java:41)
	at com.facebook.presto.jdbc.PrestoDriverUri.getUser(PrestoDriverUri.java:123)
	at com.facebook.presto.jdbc.PrestoConnection.<init>(PrestoConnection.java:97)
	at com.facebook.presto.jdbc.PrestoDriver.connect(PrestoDriver.java:91)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:678)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at com.opentable.presto.sql.PrestoSQLExecution.connection(PrestoSQLExecution.java:100)
	at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
	at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:56)
	at com.opentable.presto.sql.PrestoSQLExecution.connectionWithRetries(PrestoSQLExecution.java:92)
	at com.opentable.presto.kafka.RewindRaptorData.rewind(RewindRaptorData.java:113)

Also tried recompiling (under Java 8) JDBC driver. No diff.

**Comment by mikebell90** [comment]
openjdk 9.0.4
OpenJDK Runtime Environment (build 9.0.4+12-Ubuntu-4ubuntu2)
Bionic Beaver Ubuntu

**Comment by electrum** [comment]
Thanks for the report. This is a really strange error. Let me dig into it.

**Comment by electrum** [comment]
Fix: https://github.com/prestodb/presto/pull/10437

**Comment by mikebell90** [comment]
Thanks I'll take a look. Yeah it makes sense the byteweaving in shade plugin could be a boog.

**Comment by mikebell90** [comment]
Thanks yes and confirmed this fixed it here

**Comment by arjenzhou** [comment]
same issue with Java11 (DataGrip boot version).
