### ISSUE TITLE
Problem with legacy row field access

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#10479]
The following query fails with the stack trace below:

```
WITH R AS ( 
    SELECT 1, MAX(x) T 
    FROM (VALUES ROW(ROW(3, 4))) S(x) 
    GROUP BY 1 
) 
SELECT T.field0 FROM R;
```

```
com.facebook.presto.sql.analyzer.SemanticException: Column ':input(0).field0' cannot be resolved
        at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:39)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:440)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:292)
        at com.facebook.presto.sql.tree.DereferenceExpression.accept(DereferenceExpression.java:54)
        at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:313)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:263)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1498)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1480)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithInputs(ExpressionAnalyzer.java:1468)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypesFromInput(ExpressionAnalyzer.java:1439)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1137)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1075)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:646)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:697)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:646)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:425)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:351)
        at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:83)
        at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:350)
        at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:324)
        at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:129)
        at jdk.internal.reflect.GeneratedMethodAccessor260.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
```

**Comment by haozhun** [comment]
This is caused by mismatched config on coordinator/worker. It happens when the legacy row field ordinal access flag is set only on coordinator.
