### ISSUE TITLE
Planning failure when column names are reused in ORDER BY query

### ISSUE THREAD

**Issue by martint** [prestodb/presto#10508]
```sql
SELECT
    k,
    SUM(a) a,
    SUM(b) a
FROM (VALUES (1, 2, 3)) t(k, a, b)
GROUP BY k
ORDER BY k
```

fails with 

```
Query 20180427_013334_04199_fv2gg failed: line 3:9: Column 'a' is ambiguous
com.facebook.presto.sql.analyzer.SemanticException: line 3:9: Column 'a' is ambiguous
	at com.facebook.presto.sql.analyzer.SemanticExceptions.ambiguousAttributeException(SemanticExceptions.java:44)
	at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:137)
	at com.facebook.presto.sql.analyzer.Scope.tryResolveField(Scope.java:130)
	at com.facebook.presto.sql.analyzer.Scope.tryResolveField(Scope.java:111)
	at com.facebook.presto.sql.planner.TranslationMap.getSymbol(TranslationMap.java:313)
	at com.facebook.presto.sql.planner.TranslationMap.access$700(TranslationMap.java:43)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteExpressionWithResolvedName(TranslationMap.java:253)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteIdentifier(TranslationMap.java:247)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteIdentifier(TranslationMap.java:222)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitIdentifier(ExpressionTreeRewriter.java:734)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitIdentifier(ExpressionTreeRewriter.java:70)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:70)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:50)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.access$300(ExpressionTreeRewriter.java:25)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:539)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:70)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.defaultRewrite(ExpressionTreeRewriter.java:67)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteExpression(TranslationMap.java:226)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteExpression(TranslationMap.java:222)
	at com.facebook.presto.sql.tree.ExpressionRewriter.rewriteFunctionCall(ExpressionRewriter.java:105)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:479)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:70)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewriteWith(ExpressionTreeRewriter.java:37)
	at com.facebook.presto.sql.planner.TranslationMap.translateNamesToSymbols(TranslationMap.java:221)
	at com.facebook.presto.sql.planner.TranslationMap.put(TranslationMap.java:158)
	at com.facebook.presto.sql.planner.QueryPlanner.lambda$planBuilderFor$1(QueryPlanner.java:278)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at com.google.common.collect.ImmutableMapEntrySet$RegularEntrySet.forEach(ImmutableMapEntrySet.java:72)
	at com.facebook.presto.sql.planner.QueryPlanner.planBuilderFor(QueryPlanner.java:278)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:172)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:594)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:97)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:253)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:125)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:587)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:97)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:382)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:180)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:161)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:134)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:129)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:310)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:295)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:251)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

The issue doesn't happen if the ORDER BY clause is removed or if the outputs of the SELECT clause don't reuse the names of the FROM table.

**Comment by sopel39** [comment]
fixed via #10511
