### ISSUE TITLE
`SHOW PARTITIONS` NPE

### ISSUE THREAD

**Issue by highker** [prestodb/presto#10520]
``` java
presto:<ns>> show partitions from <table>;

Query 20180429_181238_84290_5pj2y, FAILED, 2 nodes
Splits: 5 total, 0 done (0.00%)
CPU Time: 0.1s total,     0 rows/s,     0B/s, 41% active
Per Node: 0.2 parallelism,     0 rows/s,     0B/s
Parallelism: 0.4
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20180429_181238_84290_5pj2y failed: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:788)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:511)
	at com.facebook.presto.hive.HiveMetadata$1.lambda$null$1(HiveMetadata.java:342)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at com.facebook.presto.spi.InMemoryRecordSet$InMemoryRecordCursor.advanceNextPosition(InMemoryRecordSet.java:97)
	at com.facebook.presto.split.MappedRecordSet$MappedRecordCursor.advanceNextPosition(MappedRecordSet.java:89)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:93)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:392)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:281)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:687)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:275)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by findepi** [comment]
Do I guess correctly that the table has null in one of the partitioning columns?

**Comment by highker** [comment]
@findepi yes you are right cc: @losipiuk
