### ISSUE TITLE
Hive metastore glue connector fails when db,table, or partition is missing properties

### ISSUE THREAD

**Issue by sebastiw** [prestodb/presto#10573]
Hi,
I'm getting a stacktrace when the Glue database, table and/or partition are missing properties. i.e. properties = null.
```
2018-05-07T09:40:43.497Z        WARN    http-worker-137 com.facebook.presto.server.ThrowableMapper      Request failed for /v1/statement
java.lang.NullPointerException
        at java.util.HashMap.putMapEntries(HashMap.java:501)
        at java.util.LinkedHashMap.<init>(LinkedHashMap.java:384)
        at com.facebook.presto.hive.metastore.Table$Builder.setParameters(Table.java:240)
        at com.facebook.presto.hive.metastore.glue.converter.GlueToPrestoConverter.convertTable(GlueToPrestoConverter.java:71)
        at com.facebook.presto.hive.metastore.glue.GlueHiveMetastore.getTable(GlueHiveMetastore.java:202)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTable(CachingHiveMetastore.java:255)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:208)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.getTable(CachingHiveMetastore.java:250)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getTable(SemiTransactionalHiveMetastore.java:135)
        at com.facebook.presto.hive.HiveMetadata.getViews(HiveMetadata.java:1096)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getViews(ClassLoaderSafeConnectorMetadata.java:328)
        at com.facebook.presto.metadata.MetadataManager.getView(MetadataManager.java:788)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:782)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:253)
        at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:265)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1866)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:947)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:253)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:265)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:275)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:676)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:253)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:265)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:239)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:72)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:169)
        at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:643)
```
 
Could probably be solved with some replacements in presto-hive/src/main/java/com/facebook/presto/hive/metastore/glue/converter/GlueToPrestoConverter.java
```
-                .setParameters(glueDb.getParameters())
+                .setParameters(firstNonNull(glueDb.getParameters(), ImmutableMap.of()))
```

**Comment by sopel39** [comment]
CC: @rentaow

**Comment by rentaow** [comment]
Did you create your table using Glue API directly or using Glue Crawler? There may have been other "optional" fields such as parameters that have been set to null and can be null checked.

**Comment by sebastiw** [comment]
We tried Glue API and CREATE TABLE in Aurora. Haven't found any other problems yet.

**Comment by rentaow** [comment]
I'll try to see all the places we can add null checks when I get the chance

**Comment by findepi** [comment]
should have been fixed by https://github.com/prestodb/presto/pull/10726
