### ISSUE TITLE
Possible memory leaks on selecting certain columns

### ISSUE THREAD

**Issue by sj860908** [prestodb/presto#10571]
Hello, all
I have been using presto for 2 years, and really satisfied with it.
I mainly bring up the cluster using EMR and recently upgraded from 0.170 to 0.194 where I think found a bug. 

I have data on s3 that is partitioned by dates that I have it available on presto as external table using hive catalog. The table has about 8 columns all string types, and I am experiencing very weird OOM happening when I query a certain column from it.

> select problematic_column From db.tableA where other_column='abcde' and reqdate='2018-03-01' limit 1;

Above query will run for couple minutes and will fail with OOM. 
(Above query is expect to result 0 rows)
What makes me to think the weird part is 

> select some_other_column From db.tableA where other_column='abcde' and reqdate='2018-03-01' limit 1;

Will run fine with expected result. I checked if there was any problem with problematic column using spark, checking length, any outstanding row, etc. but the column looks alright.

> select problematic_column From b.tableA where reqdate='2018-03-01' limit 1;

Above query ran fine. so it has to do something with worker node has some kind of memory leaking when it has where caluse with condition that will have 0 rows of output. 

When query fails, it actually brings down the worker node with it. When I observed memory usage by presto on worker nodes, when query is running, it will indefinitely use memory until it reaches Xmx on jvm config and worker nodes gets restarted. 

My team has been blocked by this bug and could not use any newer versions of Presto with Disk Spilling avaialble. Any help regarding solving, debugging this bug would be very much appreciated.

Here are related configurations
```
[hadoop@ip-xxxxx conf]$ cat config.properties
coordinator=false
node-scheduler.include-coordinator=false
discovery.uri=http://ip-xxxxx.ec2.internal:8889
http-server.threads.max=500
discovery-server.enabled=true
sink.max-buffer-size=1GB
query.max-memory=60GB
query.max-memory-per-node=30GB
query.max-history=40
query.min-expire-age=30m
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
experimental.spiller-threads = 8
experimental.spiller-spill-path = /mnt/presto-spill
experimental.spill-enabled = true
```

```
[hadoop@ip-xxxxx conf]$ cat jvm.config
-verbose:class
-server
-Xmx103079215104
-Xmn512M
-XX:+UseConcMarkSweepGC
-XX:+ExplicitGCInvokesConcurrent
-XX:+CMSClassUnloadingEnabled
-XX:+AggressiveOpts
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=150M
-Xbootclasspath/p:
-Djava.library.path=/usr/lib/hadoop/lib/native/:/usr/lib/hadoop-lzo/lib/native/:/usr/lib/
```

```
[hadoop@ip-172-31-43-202 conf]$ cat catalog/hive.properties
hive.s3.max-backoff-time=10m
hive.max-partitions-per-writers=10000
hive.max-partitions-per-scan=100000000
hive.allow-drop-table=true
hive.s3.max-connections=1000
hive.s3.max-error-retries =50
hive.metastore-refresh-interval=1m
hive.s3.staging-directory=/mnt/tmp/
hive.s3.socket-timeout=2m
hive.s3.max-client-retries=50
hive.metastore-cache-ttl=20m
hive.metastore.uri=thrift://xxxxx.compute-1.amazonaws.com:9083
hive.s3.connect-timeout=2m
connector.name=hive-hadoop2
hive.metastore-timeout=1m
hive.s3-file-system-type=PRESTO
hive.table-statistics-enabled=false
```

I have coordinator only master node m4.xlarge and two worker nodes r4.4xlarge for above cluster.  I orginally had 12 worker nodes on production, but used less nodes to reporduce the bug.

**Comment by nezihyigitbasi** [comment]
Try getting a heap dump on out of memory (see `HeapDumpOnOutOfMemoryError` and related JVM args, you should start the Presto workers with these args and when one of the runs out of memory the JVM should produce a heap dump), the heap dump will tell where the problem is.

**Comment by sj860908** [comment]
thanks for the help @nezihyigitbasi 
As I reproduce the problem, even with the HeapDump related confs, I wasn't able to generate the heap dumps. Resulting me to think about this as Native Memory OOM. 
How would you debug a case where OOM was from Native Memory? 

This is what my jvm setting is, with no heapdump getting produced.
[hadoop@ip-172-31-38-124 ~]$ cat /etc/presto/conf/jvm.config
-verbose:class
-server
-Xmx103079215104
-Xmn512M
-XX:+UseG1GC
-XX:+UseGCOverheadLimit
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+AggressiveOpts
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=/home/hadoop/
-XX:OnOutOfMemoryError=kill -9 %p
-XX:NativeMemoryTracking=detail
-XX:ReservedCodeCacheSize=512M
-Xbootclasspath/p:
-Djava.library.path=/usr/lib/hadoop/lib/native/:/usr/lib/hadoop-lzo/lib/native/:/usr/lib/

btw, this is a stack trace I get from failed node's server.log

2018-05-08T18:40:43.074Z	ERROR	SplitRunner-17-83	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20180508_183745_00003_a356q.1.0-134 {path=s3://xxxxx/part-00142-f551061d-7de2-4d51-be2f-a2e1fb2b0af5.c000.snappy.parquet, start=201326592, length=67108864, fileSize=352498795, hosts=[localhost], database=xxxx, table=xxx, forceLocalScheduling=false, partitionName=reqdate=2018-03-01/suffix=e2} (start = 1.193094508753E7, wall = 167199 ms, cpu = 0 ms, wait = 2702 ms, calls = 1)
java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at parquet.hadoop.codec.SnappyDecompressor.setInput(SnappyDecompressor.java:102)
	at parquet.hadoop.codec.NonBlockedDecompressorStream.read(NonBlockedDecompressorStream.java:46)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at parquet.bytes.BytesInput$StreamBytesInput.toByteArray(BytesInput.java:204)
	at parquet.column.impl.ColumnReaderImpl.readPageV1(ColumnReaderImpl.java:557)
	at parquet.column.impl.ColumnReaderImpl.access$300(ColumnReaderImpl.java:57)
	at parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:516)
	at parquet.column.impl.ColumnReaderImpl$3.visit(ColumnReaderImpl.java:513)
	at parquet.column.page.DataPageV1.accept(DataPageV1.java:96)
	at parquet.column.impl.ColumnReaderImpl.readPage(ColumnReaderImpl.java:513)
	at parquet.column.impl.ColumnReaderImpl.checkRead(ColumnReaderImpl.java:505)
	at parquet.column.impl.ColumnReaderImpl.consume(ColumnReaderImpl.java:607)
	at parquet.column.impl.ColumnReaderImpl.<init>(ColumnReaderImpl.java:351)
	at parquet.column.impl.ColumnReadStoreImpl.newMemColumnReader(ColumnReadStoreImpl.java:66)
	at parquet.column.impl.ColumnReadStoreImpl.getColumnReader(ColumnReadStoreImpl.java:61)
	at parquet.io.RecordReaderImplementation.<init>(RecordReaderImplementation.java:270)
	at parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:134)
	at parquet.io.MessageColumnIO$1.visit(MessageColumnIO.java:99)
	at parquet.filter2.compat.FilterCompat$NoOpFilter.accept(FilterCompat.java:154)
	at parquet.io.MessageColumnIO.getRecordReader(MessageColumnIO.java:99)
	at parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:137)
	at parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:208)
	at parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:201)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.advanceNextPosition(ParquetHiveRecordCursor.java:215)
	at com.facebook.presto.hive.HiveCoercionRecordCursor.advanceNextPosition(HiveCoercionRecordCursor.java:91)
	at com.facebook.presto.hive.HiveRecordCursor.advanceNextPosition(HiveRecordCursor.java:173)
	at com.facebook.presto.$gen.CursorProcessor_20180508_183723_1.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processColumnSource(ScanFilterAndProjectOperator.java:245)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:237)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nezihyigitbasi** [comment]
`Unsafe.allocateMemory()` throws OOM when the operating system cannot allocate more memory (e.g., malloc returns null), so in this case you are *not* running out of heap memory, but rather system memory. The direct byte buffers created by Hadoop snappy codec will be recycled/freed on garbage collection (GC) and it's possible that GC didn't kick in a timely manner in this case and you ran out of system memory and ended up with an OOM.

I don't think I have a good workaround for this. One workaround is to scan less data, so that snappy codec allocates less native memory. Another workaround can be to run less worker threads per Presto worker, so the aggregate native memory allocation is capped.

**Comment by findepi** [comment]
> run less worker threads per Presto worker

This might do, but it also means "utilize your resources less". Might be needed for some data formats but counter-productive for others, on the same cluster. Would it be possible to monitor native memory allocation and have _something_ that helps in a more automated fashion?

**Comment by sj860908** [comment]
Thanks for your thoughts.

What is weird is exact same dataset works fine on version 0.170
I wonder if there was change on how Hadoop handles snappy codec or on garbage collecting principle. 

Also what is super weird is query would work fine with other columns but one column. 

btw, @nezihyigitbasi I know there is couple different ways user can specify how gc works, what is the recommend way?

**Comment by nezihyigitbasi** [comment]
@sj860908 It's possible that your dataset got larger as AFAIK there was no hadoop related change on Presto side. We recommend using G1 garbage collector (more recommendations here: https://prestodb.io/docs/current/installation/deployment.html). BTW I just noticed that you are using `ParquetHiveRecordCursor`, which is the old reader. Can you please try the new reader (config property: `hive.parquet-optimized-reader.enabled`, session property: `parquet_optimized_reader_enabled`). The new reader uses a different Snappy codec and it shouldn't have this issue.

@findepi you are right, it's not efficient and it's just a workaround. Monitoring native memory and taking action based on that will be a complex control logic. Let's see whether the new Parquet reader works for him.

**Comment by sj860908** [comment]
@nezihyigitbasi parquet optimized reader did fix my issue. Thank you so much.
Wonder why that reader isn't set as True by default tho.

Do you also suggest using hive.parquet-predicate-pushdown.enabled ?

**Comment by nezihyigitbasi** [comment]
Yes, setting `hive.parquet-predicate-pushdown.enabled` is recommended too. Both the new Parquet reader and the parquet predicate pushdown are enabled by default starting from some recent release.
