### ISSUE TITLE
Cannot request more data when base processor is finished

### ISSUE THREAD

**Issue by BlueStalker** [prestodb/presto#10587]
I am running a pretty large query (large in terms of size of the key in group by), which is like
```
select id, date, count(*) from table WHERE  date BETWEEN A AND  B group BY  1,  2 having   count(*) > 1)
```
the id, date combinations is really huge and I am enabling spill to disk, 
it is on release 0.199. and the query runs around half an hour, then got failed due to:
```
java.lang.IllegalStateException: Cannot request more data when base processor is finished
	at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
	at com.facebook.presto.operator.WorkProcessorUtils$4.process(WorkProcessorUtils.java:212)
	at com.facebook.presto.operator.WorkProcessorUtils$5.process(WorkProcessorUtils.java:241)
	at com.facebook.presto.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:480)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:392)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:281)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:687)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:275)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
What's happening here?

**Comment by sopel39** [comment]
fixed via https://github.com/prestodb/presto/pull/10593
