### ISSUE TITLE
HBase connector throw Exception after I update presto from 0.171 to 0.201.

### ISSUE THREAD

**Issue by Crossoverrr** [prestodb/presto#10618]
The code below can work in presto version 0.171:

arrayType.writeSlice(builder, Slices.utf8Slice(value));

but in version 0.201, it turn out to be wrong:

java.lang.UnsupportedOperationException: com.facebook.presto.spi.block.ArrayBlockBuilder
        at com.facebook.presto.spi.block.BlockBuilder.writeBytes(BlockBuilder.java:58)
        at com.facebook.presto.spi.type.ArrayType.writeSlice(ArrayType.java:177)
        at com.facebook.presto.spi.type.ArrayType.writeSlice(ArrayType.java:171)
        at com.analysys.presto.connector.hbase.CHBaseRecordCursor.getObject(CHBaseRecordCursor.java:399)
        at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:121)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Any ideas?

**Comment by Crossoverrr** [comment]
@martint 
Sorry to trouble you, bro.
I really need to resolve this problem, please help me!

**Comment by Crossoverrr** [comment]
That's a presto-connector developed by me, haha :)

**Comment by Crossoverrr** [comment]
Check it out bro!
https://github.com/analysys/presto-hbase-connector
