### ISSUE TITLE
ST_Contains, ST_Intersects, ST_Distance, etc. on geometry collections fail with NPE

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#10628]
All of the relationship tests functions fail with NPE when input is a geometry collection.

The following functions are affected: ST_Contains, ST_Crosses, ST_Disjoint, ST_Equals, ST_Intersects, ST_Overlaps, ST_Touches and ST_Within.

```
presto> select ST_Contains(ST_GeometryFromText('GEOMETRYCOLLECTION (POINT (1 2), LINESTRING (8 4, 5 7))'), ST_Point(1, 2));

java.lang.NullPointerException
	at com.esri.core.geometry.RelationalOperations.relate(RelationalOperations.java:44)
	at com.esri.core.geometry.OperatorContainsLocal.execute(OperatorContainsLocal.java:31)
	at com.esri.core.geometry.GeometryEngine.contains(GeometryEngine.java:479)
	at com.esri.core.geometry.ogc.OGCGeometry.contains(OGCGeometry.java:305)
	at com.facebook.presto.plugin.geospatial.GeoFunctions.stContains(GeoFunctions.java:743)
```

See https://github.com/Esri/geometry-api-java/issues/176 for the issue in the underlying library.

**Comment by mbasmanova** [comment]
Fixed by #11157
