### ISSUE TITLE
NO_NODES_AVAILABLE (65541) with select * from table query

### ISSUE THREAD

**Issue by ameybarve15** [prestodb/presto#10630]
Here is the stack trace:

```
java.sql.SQLException: Query failed (#20180517_063938_00009_a77fj): No nodes available to run query
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1799)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1787)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1756)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.facebook.presto.jdbc.internal.guava.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.facebook.presto.jdbc.internal.guava.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.facebook.presto.jdbc.LengthLimitedIterator.hasNext(LengthLimitedIterator.java:42)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:149)
	at org.apache.commons.dbcp2.DelegatingResultSet.next(DelegatingResultSet.java:191)
	at org.apache.commons.dbcp2.DelegatingResultSet.next(DelegatingResultSet.java:191)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.getResults(JDBCInterpreter.java:510)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.executeSql(JDBCInterpreter.java:694)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.interpret(JDBCInterpreter.java:763)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:101)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:502)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.execution.scheduler.SimpleNodeSelector.computeAssignments(SimpleNodeSelector.java:124)
	at com.facebook.presto.execution.scheduler.DynamicSplitPlacementPolicy.computeAssignments(DynamicSplitPlacementPolicy.java:41)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:234)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:456)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
```

Presto version 0.195. 
Any idea what is wrong and how can this be fixed?

**Comment by ameybarve15** [comment]
Thanks findepi,

We have one coordinator and one server running on google cloud machines repectively

`select * from system.runtime.nodes;
               node_id                |        http_uri         |   node_version   | coordinator | state  
--------------------------------------+-------------------------+------------------+-------------+--------
 3a04c620-ae33-4f79-b7cd-c8c5b849f538 | http://10.128.0.22:8285 | 0.195-1-g63a1adc | false       | active 
 60e29193-62f4-4f63-93cb-421cb3fea177 | http://10.128.0.15:8285 | 0.195-1-g63a1adc | true        | active 
(2 rows)

Query 20180517_083549_00013_a77fj, FINISHED, 2 nodes
Splits: 17 total, 17 done (100.00%)
0:00 [2 rows, 164B] [26 rows/s, 2.14KB/s]`

**Coordinator configuration:**

config.properties
query.max-memory=50GB
node-scheduler.include-coordinator=false
query.max-memory-per-node=1GB
http-server.http.port=8285
discovery.uri=http://instance-group-1-8138.c.ampool-141120.internal:8285
coordinator=true
discovery-server.enabled=true

node.properties
plugin.dir=/usr/lib/presto/lib/plugin
node.environment=production
plugin.config-dir=/etc/presto/catalog
node.id=60e29193-62f4-4f63-93cb-421cb3fea177
node.data-dir=/var/lib/presto

jvm.config
-server
-Xmx16G
-XX:+UseG1GC
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p

env.sh
JAVA8_HOME=/usr/jdk64/jdk1.8.0_112

**Server configuration:**
config.properties
query.max-memory=50GB
node-scheduler.include-coordinator=false
query.max-memory-per-node=1GB
http-server.http.port=8285
discovery.uri=http://instance-group-1-8138.c.ampool-141120.internal:8285
coordinator=false

node.properties
plugin.dir=/usr/lib/presto/lib/plugin
node.environment=production
plugin.config-dir=/etc/presto/catalog
node.id=3a04c620-ae33-4f79-b7cd-c8c5b849f538
node.data-dir=/var/lib/presto

jvm.config
-server
-Xmx16G
-XX:+UseG1GC
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p

env.sh
JAVA8_HOME=/usr/jdk64/jdk1.8.0_112

**Comment by ameybarve15** [comment]
Hi @findepi any suggestions to solve the problem?

**Comment by findepi** [comment]
@ameybarve15 i didn't mean to investigate your issue. I meant only that initially provided information was very very scarce.
Having said that -- there isn't anything obvious in your configuration. You may want to look into server.log (on all nodes) when your queries are failing to see whether there are any errors / timeouts logged.
