### ISSUE TITLE
NullPointerException in MysqlIO.clearInputStream being logged

### ISSUE THREAD

**Issue by github55hh** [prestodb/presto#10644]
Hi, Hello: When I executed the insert statement to MySQL, the Presto background reported the null pointer exception. I don't know what is the reason, the insert statement can be successful, but the background is wrong, always feel a problem, so want to ask, is it bug or my problem.

```
>2018-05-19T16:53:24.363+0800    ERROR   20180519_085324_00015_qc2ua.1.0-0-97    com.facebook.presto.operator.Driver     Error closing operator 0 for task 20180519_085324_00015_qc2ua.1.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:901)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6676)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
        at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:205)
        at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:194)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:543)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:402)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by electrum** [comment]
Thanks for reporting. This seems to be a bug in the MySQL JDBC driver. It happens on close, after the data has been read, so it doesn't actually harm anything (other than printing a log message). We could try updating the JDBC driver to see if they fixed the bug already.

What version of Presto are you using? We changed the close behavior for MySQL in 0.200, so I'm wondering if this happens in older versions, newer versions, or both.

**Comment by github55hh** [comment]
Thanks for your answer, I use the 0.201 version of presto. In the process of using, I found another problem. I used javajdbc to insert data into MySQL yesterday. The success of the insertion was false. But when I write data to hdfs, the success value of the insert success is true. So I would like to ask, is the BUG or your developers deliberately set such a return mode?

**Comment by electrum** [comment]
Can you show some sample code? Or explain exactly which JDBC methods you are using?

**Comment by github55hh** [comment]
@Test
    public void testInsert2Mysql() throws ClassNotFoundException, SQLException {
        Class.forName("com.facebook.presto.jdbc.PrestoDriver");
        Connection connection = DriverManager.getConnection("jdbc:presto://10.0.37.165:9401/mysql/test","root",null);
        Statement stmt = connection.createStatement();
        boolean execute = stmt.execute("insert into person (id,name) values(1,'zhengzhou'),(2,'langfang')");
        System.out.println("The result is："+execute);
        connection.close();
    }

The result I get is false, and its insert operation is successful.

**Comment by tooptoop4** [comment]
I am getting this in v0.220:
2019-06-17T13:57:33.645Z        ERROR   20190617_135733_00068_wehgw.1.0-0-101   com.facebook.presto.operator.Driver     Error closing operator 0 for task 20190617_135733_00068_wehgw.1.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:899)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6679)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
        at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:185)
        at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:174)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:546)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:406)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220____20190617_135337_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Svti** [comment]
me too , how to fix ?

**Comment by axzhcode** [comment]
+1

**Comment by findepi** [comment]
@github55hh @axzhcode @Svti @tooptoop4 FYI this has been fixed some time ago in prestosql.

**Comment by SunHao1234** [comment]
> FYI this has been fixed some time ago in prestosql.

When I use version 230, there is still a null pointer exception when connecting to MySQL

**Comment by SunHao1234** [comment]
> 
> 
> I am getting this in v0.220:
> 2019-06-17T13:57:33.645Z ERROR 20190617_135733_00068_wehgw.1.0-0-101 com.facebook.presto.operator.Driver Error closing operator 0 for task 20190617_135733_00068_wehgw.1.0
> java.lang.NullPointerException
> at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:899)
> at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
> at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6679)
> at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
> at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
> at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
> at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:185)
> at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:174)
> at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:546)
> at com.facebook.presto.operator.Driver.processInternal(Driver.java:406)
> at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
> at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
> at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
> at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
> at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
> at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
> at com.facebook.presto.$gen.Presto_0_220____20190617_135337_1.run(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)

****

> 
> 
> I am getting this in v0.220:
> 2019-06-17T13:57:33.645Z ERROR 20190617_135733_00068_wehgw.1.0-0-101 com.facebook.presto.operator.Driver Error closing operator 0 for task 20190617_135733_00068_wehgw.1.0
> java.lang.NullPointerException
> at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:899)
> at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
> at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6679)
> at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
> at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
> at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
> at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:185)
> at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:174)
> at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:546)
> at com.facebook.presto.operator.Driver.processInternal(Driver.java:406)
> at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
> at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
> at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
> at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
> at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
> at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
> at com.facebook.presto.$gen.Presto_0_220____20190617_135337_1.run(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)

Have you solved the problem?

**Comment by xzhongyu** [comment]
Me too. When I use version 230, there is a null pointer exception when connecting to MySQL

**Comment by xzhongyu** [comment]
ERROR	20200114_031948_00000_e7w4s.1.0.0-0-98	com.facebook.presto.operator.Driver	Error closing operator 0 for task 20200114_031948_00000_e7w4s.1.0.0
java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
	at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
	at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
	at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
	at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:81)
	at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:194)
	at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:183)
	at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:546)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:406)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_230_3b9af8c____20200114_031905_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rongrong** [comment]
@SunHao1234  can you post your 0.230 stack trace? Thanks!

**Comment by quietgopher** [comment]
I'm getting this too.  I'm doing a very basic select query (a column from a table).
presto image: apachepinot/pinot-presto:0.236.0 (built recently by Pinot team)
mysql image: mysql/mysql-server:5.6

2020-05-10T19:34:24.573Z	ERROR	20200510_193418_00003_k57wb.2.0.0-0-107	com.facebook.presto.operator.Driver	Error closing operator 0 for task 20200510_193418_00003_k57wb.2.0.0
java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
	at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
	at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
	at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.finish(ScanFilterAndProjectOperator.java:182)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.close(ScanFilterAndProjectOperator.java:166)
	at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:549)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:409)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_236_SNAPSHOT_dbf3a80____20200510_192846_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by 741454897** [comment]
I get this error in 0.281, help！

ERROR   20230602_124259_00174_8p37x.3.0.0-0-113 com.facebook.presto.operator.Driver     Error closing operator 0 for task 20230602_124259_00174_8p37x.3.0.0
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.available()" because "this.mysqlInput" is null
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.finish(ScanFilterAndProjectOperator.java:205)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.close(ScanFilterAndProjectOperator.java:189)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:609)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:462)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
        at com.facebook.presto.$gen.Presto_0_281_cfbc6eb____20230602_121919_1.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by maxpixelton** [comment]
I get this error in 0.281, help！
2023-05-09T15:06:42.252+0800    ERROR   20230509_070448_02216_g4kjm.1.0.0-0-42  com.facebook.presto.operator.Driver     Error closing operator 0 for task 20230509_070448_02216_g4kjm.1.0.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:83)
        at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:209)
        at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:198)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:609)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:462)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
        at com.facebook.presto.$gen.Presto_0_281_2415c18____20230509_063321_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by SendDreams** [comment]
I get this error in 0.289, help！
2024-12-25T16:35:27.549+0800    ERROR   20241225_083508_70657_bsgyq.6.0.0.0-0-62        com.facebook.presto.operator.Driver     Error closing operator 0 for task 20241225_083508_70657_bsgyq.6.0.0.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.finish(ScanFilterAndProjectOperator.java:205)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.close(ScanFilterAndProjectOperator.java:189)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:627)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:475)
        at com.facebook.presto.operator.Driver.lambda$processFor$10(Driver.java:324)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:750)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:317)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
        at com.facebook.presto.$gen.Presto_0_289_bd64355____20241017_040743_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
