### ISSUE TITLE
Invalid plan for complex order by expression involving lambda in grouping keys

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#10694]
**Query**:
```
SELECT 
 cardinality (filter(numbers, x -> x < 7))
FROM(
VALUES ARRAY[1,2,3]
) AS t (numbers)
GROUP BY
 cardinality (filter(numbers, x -> x < 7))
ORDER BY
 cardinality (filter(numbers, x -> x < 7))
```

**Error**:
`Query 20180523_224742_00013_nx3i2 failed: Invalid node. Expression dependencies ([expr_3]) not in source plan output ([cardinality$gid])`

It looks like the invalid project node is created here: https://github.com/prestodb/presto/blob/2501e88816ca9f66c6b65635573ac0f18f435b3c/presto-main/src/main/java/com/facebook/presto/sql/planner/QueryPlanner.java#L168-L171

CC: @findepi it looks like you wrote that code, so maybe you have some context.

**Comment by sopel39** [comment]
Invalid node is created at:
`com/facebook/presto/sql/planner/QueryPlanner.java:166`
The case is as follows:
1. After aggregation is planned then in `TranslationMap` there is mapping `"cardinality"("filter"("expr_3", (expr_0) -> ("expr_0" < 7)))" -> "cardinality$gid"`
2. We then try to map `cardinality (filter(numbers, x -> x < 7))` from projection and order by to a symbol in line `com/facebook/presto/sql/planner/QueryPlanner.java:166`
3. Because `TranslationMap#lambdaDeclarationToSymbolMap` contains different mapping for `x` identifiers in lambdas within projection and order by, only one `cardinality (filter(numbers, x -> x < 7))` is mapper property to `cardinality$gid`. The other get translated to `"cardinality"("filter"("expr_3", (expr) -> ("expr" < 7)))"` for which there isn't a mapping.
4. lambda argument mappings are created in `com.facebook.presto.sql.planner.LogicalPlanner#buildLambdaDeclarationToSymbolMap`. Maybe those mapping should be deterministic instead of creating new symbol for each `LambdaArgumentDeclaration`

**Comment by findepi** [comment]
My thought was to defer substitution of lambda formal parameters (`x`) to symbols after we translated the expressions (capturing duplicates).

**Comment by atris** [comment]
I would like to help with this. Please let me know

**Comment by rschlussel** [comment]
There is a similar issue for 
```
EXPLAIN 
SELECT 
  COUNT(*) 
FROM 
  (values ARRAY['a', 'b']) as t(col1) 
ORDER BY 
  IF(
    SUM(
      REDUCE(
        col1, 
        ROW(0), 
        ("l", "r") -> "l", 
        "x" -> 1
      )
    ) > 0, 
    COUNT(*), 
    SUM(
      REDUCE(
        col1, 
        ROW(0), 
        ("l", "r") -> "l", 
        "x" -> 1
      )
    )
  ) 
```

The query fails with "Query 20191227_170043_00012_nihq2 failed: line 19:9: Column 'col1' cannot be resolved" 
 
Stack trace:
```
com.facebook.presto.sql.analyzer.SemanticException: line 19:9: Column 'col1' cannot be resolved
	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:32)
	at com.facebook.presto.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:104)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:395)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:311)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:70)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:334)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:902)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:311)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:334)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:1037)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:311)
	at com.facebook.presto.sql.tree.Cast.accept(Cast.java:98)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:334)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:902)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:311)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:334)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.coerceToSingleType(ExpressionAnalyzer.java:1323)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIfExpression(ExpressionAnalyzer.java:531)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIfExpression(ExpressionAnalyzer.java:311)
	at com.facebook.presto.sql.tree.IfExpression.accept(IfExpression.java:70)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:334)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:277)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1523)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1505)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1492)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1479)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:127)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:66)
	at com.facebook.presto.spi.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitSort(InternalPlanVisitor.java:74)
	at com.facebook.presto.sql.planner.plan.SortNode.accept(SortNode.java:85)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:117)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:66)
	at com.facebook.presto.spi.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:117)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:66)
	at com.facebook.presto.spi.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:117)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:66)
	at com.facebook.presto.spi.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitOutput(InternalPlanVisitor.java:29)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:84)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:63)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validateIntermediatePlan$1(PlanSanityChecker.java:76)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validateIntermediatePlan(PlanSanityChecker.java:76)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:183)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:176)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:183)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:174)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:120)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:135)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:113)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:62)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:59)
	at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:53)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:751)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:365)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)
	at com.facebook.presto.$gen.Presto_null__testversion____20191227_162826_4.run(Unknown Source)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The issue is with the duplicate expressions in the if condition.  The lambdaDeclarationToVariableMap maps each lambda declaration based on identity (it uses NodeRef), but as far as object equality the two expressions are the same, which is what we use when creating variablesForExpressions() in the QueryPlanner.  As such, only one of the expressions gets properly mapped by the translation map and an invalid plan is created.

**Comment by rschlussel** [comment]
I put up a fix for the second issue.  The first issue is not actually related to order by, as the following query also fails:
```
SELECT cardinality (filter(numbers, x -> x < 7)) FROM( VALUES ARRAY[1,2,3] ) AS t (numbers) GROUP BY cardinality (filter(numbers, x -> x < 7));
```
The cause is that the output expressions are different from the grouping expressions when converted to symbols (again due to the lambda map issue), and aren't being added to the translation map.  The issue occurs when we try to create a projection using the outputs

**Comment by rschlussel** [comment]
this is a duplicate of https://github.com/prestodb/presto/issues/7140
