### ISSUE TITLE
Presto is having issues reading Avro files from HDFS using ‘avro.schema.literal’.

### ISSUE THREAD

**Issue by mdmuqeetali** [prestodb/presto#10736]
Getting below exception when trying to use Presto (0.200) to query Avro files stored on HDFS using Hive external table schema with supplied Avro schema using ‘avro.schema.literal’. The same query works fine over Hive directly.

java.lang.IllegalArgumentException: undefined
          at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
          at com.facebook.presto.hive.util.SerDeUtils.serializeStruct(SerDeUtils.java:252)
          at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:99)
          at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:82)
          at com.facebook.presto.hive.util.SerDeUtils.serializeStruct(SerDeUtils.java:264)
          at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:99)
          at com.facebook.presto.hive.util.SerDeUtils.serializeObject(SerDeUtils.java:82)
          at com.facebook.presto.hive.util.SerDeUtils.getBlockObject(SerDeUtils.java:77)
          at com.facebook.presto.hive.GenericHiveRecordCursor.parseObjectColumn(GenericHiveRecordCursor.java:443)
          at com.facebook.presto.hive.GenericHiveRecordCursor.parseColumn(GenericHiveRecordCursor.java:490)
          at com.facebook.presto.hive.GenericHiveRecordCursor.isNull(GenericHiveRecordCursor.java:454)
          at com.facebook.presto.hive.HiveRecordCursor.isNull(HiveRecordCursor.java:231)
          at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:101)
          at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
          at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
          at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
          at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
          at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
          at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
          at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
          at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at java.lang.Thread.run(Thread.java:748)

**Comment by mdmuqeetali** [comment]
Same error with latest Presto build 0.203..

**Comment by yangjun616** [comment]
we use 0.198, we can read the table create with avro.schema.literal .But when we alter the table properties add some fields ,we meet the same error
