### ISSUE TITLE
Overflow in optimized OrcWriter

### ISSUE THREAD

**Issue by dain** [prestodb/presto#10776]
Looks like a really large page can cause the writer to create a single stream buffer larger than 2 GiB, which should not be possible when the max stripe size in our installation is less than 100 MiB.  I believe the logic that splits pages should take split pages until the logical size (i.e., `getSizeInBytes`) is below some reasonable limit.
```
java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Math.java:1071)
	at com.facebook.presto.orc.OrcOutputBuffer.size(OrcOutputBuffer.java:150)
	at com.facebook.presto.orc.stream.LongOutputStreamV1.getBufferedBytes(LongOutputStreamV1.java:201)
	at com.facebook.presto.orc.writer.SliceDictionaryColumnWriter.getOutputDataStreams(SliceDictionaryColumnWriter.java:442)
	at com.facebook.presto.orc.writer.ListColumnWriter.getOutputDataStreams(ListColumnWriter.java:217)
	at com.facebook.presto.orc.OrcWriter.writeStripe(OrcWriter.java:332)
	at com.facebook.presto.orc.OrcWriter.writeChunk(OrcWriter.java:284)
	at com.facebook.presto.orc.OrcWriter.write(OrcWriter.java:239)
	at com.facebook.presto.hive.OrcFileWriter.appendRows(OrcFileWriter.java:132)
	at com.facebook.presto.hive.HiveWriter.append(HiveWriter.java:76)
	at com.facebook.presto.hive.HivePageSink.writePage(HivePageSink.java:308)
```

**Comment by wenleix** [comment]
I have looked that query, because of the writer scaling, there will be a `PartitionedOutputOperator` before `TableWriterOperator`, thus any page that is too large will not go through.

If the issue is not because some excessively large Page, I can only see two potential issues after looking at the code.

- We hit some corner cases that makes the flush heuristic not working as expected, so we are writing huge chunk.

https://github.com/prestodb/presto/blob/2a245384cb247d01153c897163a6b4b1f00422fc/presto-orc/src/main/java/com/facebook/presto/orc/OrcWriter.java#L285-L295

- The underlying `OrcOutputBuffer` doesn't get reset appropriately. But I checked the code and didn't see anything wrong there. Also this should result in data corruption issues in other cases.
