### ISSUE TITLE
Analyzer crash when casting row(json) to row(double)

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#10788]
This will cause analyzer to crash in `LocalCache.get`:
> select cast(row(json_extract(a, '$.key')) as row(a double)) from (values ('{"key":1.1}')) t(a);

java.lang.RuntimeException: Error fetching next at http://localhost:8080/v1/statement/20180608_013523_00013_bzhmx/1 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-type=[text/plain], date=[Fri, 08 Jun 2018 01:35:23 GMT], transfer-encoding=[chunked]}, hasValue=false} [Error: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.VerifyError: Inconsistent stackmap frames at branch target 96
Exception Details:
  Location:
    com/facebook/presto/$gen/RowCast$3144ABE73CE61986B64EF556437677C7_20180608_013523_23.castRow(Lcom/facebook/presto/spi/ConnectorSession;Lcom/facebook/presto/spi/block/Block;)Lcom/facebook/presto/spi/block/Block; @41: goto
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @41
    flags: { }
    locals: { 'com/facebook/presto/spi/ConnectorSession', 'com/facebook/presto/spi/block/Block', integer, 'com/facebook/presto/spi/block/BlockBuilder', 'com/facebook/presto/spi/block/BlockBuilder' }
    stack: { }
  Stackmap Frame:
    bci: @96
    flags: { }
    locals: { 'com/facebook/presto/spi/ConnectorSession', 'com/facebook/presto/spi/block/Block', integer, 'com/facebook/presto/spi/block/BlockBuilder', 'com/facebook/presto/spi/block/BlockBuilder' }
    stack: { 'com/facebook/presto/spi/type/Type' }
  Bytecode:
    0x0000000: 033d ba00 1500 0001 04b9 001b 0300 4e2d
    0x0000010: b900 2101 003a 042b 03b9 0027 0200 9900
    0x0000020: 0e19 04b9 002a 0100 57a7 0037 ba00 2f00
    0x0000030: 0019 04ba 0034 0000 2b03 b900 3803 001c
    0x0000040: 9900 0857 0ea7 0016 ba00 3e00 0059 c700
    0x0000050: 0a04 3d57 0ea7 0006 b600 44b9 0048 0300
    0x0000060: 2db9 004b 0100 57ba 004e 0000 2dc0 0023
    0x0000070: 03b9 0052 0300 c000 23b0
  Stackmap Table:
    append_frame(@44,Integer,Object[#29],Object[#29])
    full_frame(@72,{Object[#93],Object[#35],Integer,Object[#29],Object[#29]},{Object[#23],Object[#29],Object[#95]})
    full_frame(@88,{Object[#93],Object[#35],Integer,Object[#29],Object[#29]},{Object[#23],Object[#29],Object[#64]})
    full_frame(@91,{Object[#93],Object[#35],Integer,Object[#29],Object[#29]},{Object[#23],Object[#29],Double})
    same_locals_1_stack_item_frame(@96,Object[#23])

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:913)
	at com.facebook.presto.metadata.FunctionRegistry.getCoercion(FunctionRegistry.java:1063)
	at com.facebook.presto.metadata.FunctionRegistry.getCoercion(FunctionRegistry.java:1056)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:980)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:302)
	at com.facebook.presto.sql.tree.Cast.accept(Cast.java:98)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:323)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:268)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1550)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:2016)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:1828)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:948)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:269)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:279)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:675)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:269)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:243)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:73)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:65)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:169)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:660)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:582)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:439)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$3(SqlQueryManager.java:372)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by wenleix** [comment]
This is probably because of the bug that row to row cast not work with JSON type: https://github.com/prestodb/presto/issues/9113

**Comment by rongrong** [comment]
I think they are the same.
