### ISSUE TITLE
wired exception from presto

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#10824]
Hi when I fire a query in presto

select   anticutoff_callback_version2_orderid_daily_list.orderid,  anticutoff_callback_version2_orderid_daily_list.masterhotelid,  anticutoff_callback_version2_orderid_daily_list.hotelid,  anticutoff_callback_version2_orderid_daily_list.group,  anticutoff_callback_version2_orderid_daily_list.hotelname,  anticutoff_callback_version2_orderid_daily_list.guarantee,  anticutoff_callback_version2_orderid_daily_list.date_live,  anticutoff_callback_version2_orderid_daily_list.cancelreason,  anticutoff_callback_version2_orderid_daily_list.cityname,  anticutoff_callback_version2_orderid_daily_list.groupname,  anticutoff_callback_version2_orderid_daily_list.star,  anticutoff_callback_version2_orderid_daily_list.provincename,  anticutoff_callback_version2_orderid_daily_list.num_all, MAX(  anticutoff_callback_version2_orderid_daily_list.cjl )  as a, MAX(  anticutoff_callback_version2_orderid_daily_list.cutoff_ratio )  as b  from "dw_htlbizdb"."anticutoff_callback_version2_orderid_daily_list"  where  (  anticutoff_callback_version2_orderid_daily_list.d= '2018-06-13' )   group by  anticutoff_callback_version2_orderid_daily_list.orderid,  anticutoff_callback_version2_orderid_daily_list.masterhotelid,  anticutoff_callback_version2_orderid_daily_list.hotelid,  anticutoff_callback_version2_orderid_daily_list.group,  anticutoff_callback_version2_orderid_daily_list.hotelname,  anticutoff_callback_version2_orderid_daily_list.guarantee,  anticutoff_callback_version2_orderid_daily_list.date_live,  anticutoff_callback_version2_orderid_daily_list.cancelreason,  anticutoff_callback_version2_orderid_daily_list.cityname,  anticutoff_callback_version2_orderid_daily_list.groupname,  anticutoff_callback_version2_orderid_daily_list.star,  anticutoff_callback_version2_orderid_daily_list.provincename,  anticutoff_callback_version2_orderid_daily_list.num_all  order by  anticutoff_callback_version2_orderid_daily_list.masterhotelid asc LIMIT 2000

I got this exception 

com.facebook.presto.sql.parser.ParsingException: line 1:238: no viable alternative at input 'anticutoff_callback_version2_orderid_daily_list.group'
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:48)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:284)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:121)
	at com.facebook.presto.sql.parser.SqlBaseParser.selectItem(SqlBaseParser.java:4858)
	at com.facebook.presto.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:3919)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3676)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3481)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3332)
	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2761)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1414)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:236)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:113)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:77)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:406)
	at com.facebook.presto.server.protocol.Query.<init>(Query.java:183)
	at com.facebook.presto.server.protocol.Query.create(Query.java:159)
	at com.facebook.presto.server.protocol.StatementResource.createQuery(StatementResource.java:160)
	at sun.reflect.GeneratedMethodAccessor1113.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

when I remove anticutoff_callback_version2_orderid_daily_list.group from sql it works fine

is there any idea or suggestion?

**Comment by photogamerun** [comment]
it looks like 'group' is reserved work in presto, so I can not use group in select statements
is it corrected?

**Comment by findepi** [comment]
You can always "-quote the identifier: `anticutoff_callback_version2_orderid_daily_list."group"`
