### ISSUE TITLE
Parquet Map type raises indexoutofboundsexception

### ISSUE THREAD

**Issue by sj860908** [prestodb/presto#10844]
I had a query that access parquet files with data type being Map<String, Int>.
Query was running fine until I upgraded cluster from 0.170 to 0.194 with parquet reader optimizer turned on. 

Then when I ran the same query it gives me this stack trace.
```
com.facebook.presto.spi.PrestoException: Index (0) is greater than or equal to list size (0)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:219)
	at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:197)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:217)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:209)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:184)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:191)
	... 12 more
```

I'm using hive catalog on presto, and running the exact same query on hive and spark works fine.
Looking at the stack trace, I think it is freaking out on empty map element or something.

These are example data on that column.
```
{"c":1,"b":3,"a":1}
{}
{"a":1,"b":20}
{}
```

and hive column definition =   column_name map<string,int>

Any help would be appreciated.

**Comment by oaustegard** [comment]
Running `set session hive.parquet_optimized_reader_enabled = false;` might help.

**Comment by nezihyigitbasi** [comment]
@sj860908 is this still an issue for you?

**Comment by zhenxiao** [comment]
@sj860908 Presto203 should have fixed this issue, could you please take a try?
