### ISSUE TITLE
TextInputFormat error: Compression codec com.hadoop.compression.lzo.LzoCodec not found

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto#10862]
```
 sudo presto --debug --schema default --execute 'select count(*) from PrestoHiveSampleTable'
Query 20180614_222037_00005_wksty failed: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
com.facebook.presto.spi.PrestoException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
        at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:139)
        at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:117)
        at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:72)
        at com.facebook.presto.split.BufferingSplitSource.isFinished(BufferingSplitSource.java:86)
        at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:89)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:354)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
```

**Comment by kokosing** [comment]
Can you please provide more information? What version of Presto did you use? Can you post DDL of table that you used?

**Comment by nakhanha** [comment]
Presto version 0.174
What doeS DDL mean?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kokosing** [comment]
I mean `CREATE TABLE` that was used to create the table you use. You can use `SHOW CREATE TABLE` command in Hive and in Presto. 

Regarding DDL, please see https://en.wikipedia.org/wiki/Data_definition_language.

**Comment by nakhanha** [comment]
"DROP TABLE IF EXISTS PrestoHiveSampleTable; CREATE TABLE PrestoHiveSampleTable (ClientId string,QueryTime string,Market string,DevicePlatform string,DeviceMake string,DeviceModel string,State string,Country string,QueryDwellTime double,SessionId bigint,SessionPageViewOrder bigint) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; LOAD DATA LOCAL INPATH '/usr/lib/examples/hive/HiveSampleData.txt' OVERWRITE INTO TABLE PrestoHiveSampleTable;"

**Comment by kokosing** [comment]
Can you post whole stack trace that you are receiving.

PS. if you reply with email please remove the conversation history from the message as it is posted as github.

**Comment by nakhanha** [comment]
sudo presto --debug --schema default --execute 'select count(*) from PrestoHiveSampleTable'
Query 20180619_061445_00005_vf96m failed: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
com.facebook.presto.spi.PrestoException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
        at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:139)
        at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:117)
        at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:72)
        at com.facebook.presto.split.BufferingSplitSource.isFinished(BufferingSplitSource.java:86)
        at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:89)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:354)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to create input format org.apache.hadoop.mapred.TextInputFormat
        at com.facebook.presto.hive.HiveUtil.getInputFormat(HiveUtil.java:215)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:290)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:231)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:86)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:187)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
        at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$1(ResumableTasks.java:33)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        ... 3 more
Caused by: java.lang.RuntimeException: Error in configuring object
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:112)
        at org.apache.hadoop.util.ReflectionUtils.setConf(ReflectionUtils.java:78)
        at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:136)
        at com.facebook.presto.hive.HiveUtil.getInputFormat(HiveUtil.java:212)
        ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.ReflectionUtils.setJobConf(ReflectionUtils.java:109)
        ... 13 more
Caused by: java.lang.IllegalArgumentException: Compression codec com.hadoop.compression.lzo.LzoCodec not found.
        at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:139)
        at org.apache.hadoop.io.compress.CompressionCodecFactory.<init>(CompressionCodecFactory.java:180)
        at org.apache.hadoop.mapred.TextInputFormat.configure(TextInputFormat.java:45)
        ... 18 more
Caused by: java.lang.ClassNotFoundException: Class com.hadoop.compression.lzo.LzoCodec not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
        at org.apache.hadoop.io.compress.CompressionCodecFactory.getCodecClasses(CompressionCodecFactory.java:132)
        ... 20 more


Thanks

**Comment by kokosing** [comment]
What do you have in `hive.properties`?

**Comment by nakhanha** [comment]
connector.name=hive-hadoop2
hive.metastore.uri=thrift://hn0-nkhhad. net:9083,thrift://hn1-nkhhad.net:9083
hive.config.resources=/etc/hadoop/conf/hdfs-site.xml,/etc/hadoop/conf/core-site.xml

**Comment by kokosing** [comment]
Either in hive.config.resources=/etc/hadoop/conf/hdfs-site.xml or /etc/hadoop/conf/core-site.xml
you have `io.compression.codecs` configured to use lzo (`com.hadoop.compression.lzo.LzoCodec`) compression which seems to be not available in Presto.

Either change the configuration or define other (supported by Presto) compression for this table explicitly.

**Comment by nakhanha** [comment]
Yes my  /etc/hadoop/conf/core-site.xml has com.hadoop.compression.lzo.LzoCodec. I added 
hadoop-lzo-0.6.0.2.6.3.2-14.jar
hadoop-lzo-0.6.0.2.6.3.2-14-javadoc.jar
hadoop-lzo-0.6.0.2.6.3.2-14-sources.jar to hive presto-server-0.174/plugin/hive-hadoop2/ folder. I still see that Exception. Is there something I am missing ?

**Comment by heaventouch** [comment]
i met the same problem. have you solved it ?
