### ISSUE TITLE
ArrayIndexOutOfBounds error when struct is missing fields present in Hive table schema

### ISSUE THREAD

**Issue by shreyasjoshis** [prestodb/presto#10941]
## Summary

Lets say we have an ORC backed Hive table with a column like: `struct <a:string>` that evolves to add another field to become `struct <a:string, b:string>`. In this case the ORC files written with the old schema are no longer readable. Presto fails with the following error:

```java
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.facebook.presto.orc.reader.StructStreamReader.readBlock(StructStreamReader.java:100)
	at com.facebook.presto.orc.OrcRecordReader.readBlock(OrcRecordReader.java:370)
	at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:240)
	at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:216)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:256)
	at com.facebook.presto.spi.Page.assureLoaded(Page.java:230)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:265)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
````

Instead, Presto should set the fields missing from the struct (In this case `b`) to null. I will be submitting a PR for this change soon.

**Comment by shreyasjoshis** [comment]
Closing as this is fixed.

**Comment by nidhirawat** [comment]
Can anyone please tell me in which version of presto this issue was fixed
