### ISSUE TITLE
Presto 0.205 & Hive & Parquet & Timestamp/BIGINT field issue

### ISSUE THREAD

**Issue by us3r** [prestodb/presto#11066]
Hello 

I have noticed strange behaviour on presto. I have created a 3 different parquet files (attached you can find it):
1) parquet with defined endtime field as STRING
2) parquet with defined endtime field as BIGINT (INT64 in parquet)
3) parquet with defined endtime field as TIMESTAMP

After that I have created 3 tables in hive:

endtime as *string*:
```
CREATE EXTERNAL TABLE `npatestasstring`  (
 `endtime` string, 
  `name` string )
 PARTITIONED BY ( 
  `year` smallint, 
  `month` smallint, 
  `day` smallint, 
  `hour` smallint
)
STORED AS PARQUET 
LOCATION
  's3a://npatest/asstring';
```

endtime as *bigint*:
```
CREATE EXTERNAL TABLE `npatestasint`  (
 `endtime` bigint, 
  `name` string )
 PARTITIONED BY ( 
  `year` smallint, 
  `month` smallint, 
  `day` smallint, 
  `hour` smallint
)
STORED AS PARQUET 
LOCATION
  's3a://npatest/asint';
```

endtime as *timestamp*:
```
CREATE EXTERNAL TABLE `npatestastimestamp`  (
 `endtime` timestamp, 
  `name` string )
 PARTITIONED BY ( 
  `year` smallint, 
  `month` smallint, 
  `day` smallint, 
  `hour` smallint
)
STORED AS PARQUET 
LOCATION
  's3a://npatest/astimestamp';
```

Everything is ok with endtime defined as "string":
Hive:
![image](https://user-images.githubusercontent.com/848741/42840946-bd2e4ffc-8a08-11e8-9c89-293734fdd5b2.png)
Presto:
![image](https://user-images.githubusercontent.com/848741/42840988-e0c4d88c-8a08-11e8-956e-a3048770a8cc.png)

If I will try to point to the "bigint" definition:

Hive:
![image](https://user-images.githubusercontent.com/848741/42841029-07eb420c-8a09-11e8-9bf9-59382ae684d2.png)

Presto:
![image](https://user-images.githubusercontent.com/848741/42841057-1cd4b70c-8a09-11e8-9a3c-ddc725c54da0.png)

And this is error:
```
java.lang.UnsupportedOperationException: com.facebook.presto.spi.type.BigintType
	at com.facebook.presto.spi.type.AbstractType.writeSlice(AbstractType.java:135)
	at com.facebook.presto.hive.parquet.reader.ParquetBinaryColumnReader.readValue(ParquetBinaryColumnReader.java:55)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.lambda$readValues$1(ParquetPrimitiveColumnReader.java:184)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.processValues(ParquetPrimitiveColumnReader.java:204)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.readValues(ParquetPrimitiveColumnReader.java:183)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.readPrimitive(ParquetPrimitiveColumnReader.java:171)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:208)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:258)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readBlock(ParquetReader.java:241)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:243)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:221)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:262)
	at com.facebook.presto.spi.Page.assureLoaded(Page.java:244)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:245)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

If I try to use a table with timestamp:
hive:
![image](https://user-images.githubusercontent.com/848741/42841152-73e9dcc0-8a09-11e8-8cf3-2f81743c3651.png)

Presto:
![image](https://user-images.githubusercontent.com/848741/42841179-8c56dfe2-8a09-11e8-9bad-380007432e25.png)

And stack trace:
```
java.lang.UnsupportedOperationException: com.facebook.presto.spi.type.TimestampType
	at com.facebook.presto.spi.type.AbstractType.writeSlice(AbstractType.java:135)
	at com.facebook.presto.hive.parquet.reader.ParquetBinaryColumnReader.readValue(ParquetBinaryColumnReader.java:55)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.lambda$readValues$1(ParquetPrimitiveColumnReader.java:184)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.processValues(ParquetPrimitiveColumnReader.java:204)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.readValues(ParquetPrimitiveColumnReader.java:183)
	at com.facebook.presto.hive.parquet.reader.ParquetPrimitiveColumnReader.readPrimitive(ParquetPrimitiveColumnReader.java:171)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:208)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:258)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readBlock(ParquetReader.java:241)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:243)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:221)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:262)
	at com.facebook.presto.spi.Page.assureLoaded(Page.java:244)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:245)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Any clue what can be wrong?

[parquet.zip](https://github.com/prestodb/presto/files/2203130/parquet.zip)

EDIT 

After publishing this issue I have noticed sth strange....
![image](https://user-images.githubusercontent.com/848741/42841857-abb2cc82-8a0b-11e8-8d6d-fb396d905328.png)
![image](https://user-images.githubusercontent.com/848741/42841995-262888b2-8a0c-11e8-9716-eb90efd767cb.png)

Same table directly on hive:
![image](https://user-images.githubusercontent.com/848741/42841878-be15c316-8a0b-11e8-8311-682976e9a937.png)

**Comment by us3r** [comment]
@findepi .... pls send to me your address ... I owe you really good beer :))))

**Comment by rigogsilva** [comment]
Thanks!
