### ISSUE TITLE
worker NO_MORE_BUFFERS

### ISSUE THREAD

**Issue by imperio-wxm** [prestodb/presto#11109]
I have 62G * 7 workers for hive.

```java
query.max-memory-per-node=15GB
query.max-memory=115GB

-Xmx46G
```

The problem is a query often blocked on just one node（each time on a random one）, other nodes are faster. And in Task ID link I found `NO_MORE_BUFFERS` for outputBuffers. Hive data is not big, all table just 800M+ and result just 100M+.

What is the situation that may lead to this？

![image](https://user-images.githubusercontent.com/8111349/43085811-86614ec8-8ece-11e8-8567-b41bf1b29128.png)

![image](https://user-images.githubusercontent.com/8111349/43090992-8d21efda-8edb-11e8-8140-66412242aa67.png)

![image](https://user-images.githubusercontent.com/8111349/43086138-38c928f6-8ecf-11e8-9342-9852873eb9ad.png)

![image](https://user-images.githubusercontent.com/8111349/43086160-4848cfac-8ecf-11e8-93a5-8746f8f3d700.png)

logs

```java
602_19017_d2s3z.4.0/results/20180723_153602_19017_d2s3z.2.1/1 - requests failed for 60.03s)
2018-07-23T23:36:43.597+0800    ERROR   exchange-client-7       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://:8080/v1/task/20180723_153602_19017_d2s3z.1.2/results/20180723_153602_19017_d2s3z.0.0 failed java.util.concurrent.CancellationException: Task was cancelled.
2018-07-23T23:36:43.597+0800    ERROR   exchange-client-10      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://:8080/v1/task/20180723_153602_19017_d2s3z.1.5/results/20180723_153602_19017_d2s3z.0.0 failed java.util.concurrent.CancellationException: Task was cancelled.
2018-07-23T23:36:43.598+0800    ERROR   exchange-client-19      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://:8080/v1/task/20180723_153602_19017_d2s3z.1.1/results/20180723_153602_19017_d2s3z.0.0 failed java.util.concurrent.CancellationException: Task was cancelled.
2018-07-23T23:36:43.598+0800    ERROR   SplitRunner-705-57872   com.facebook.presto.operator.Driver     Error freeing memory for operator 1 for task 20180723_153602_19017_d2s3z.2.1
java.lang.IllegalArgumentException: tried to free more memory than is reserved
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.facebook.presto.operator.DriverContext.freeMemory(DriverContext.java:232)
        at com.facebook.presto.operator.OperatorContext.freeMemory(OperatorContext.java:283)
        at com.facebook.presto.operator.OperatorContext.setMemoryReservation(OperatorContext.java:332)
        at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:464)
        at com.facebook.presto.operator.Driver.access$400(Driver.java:60)
        at com.facebook.presto.operator.Driver$DriverLockResult.close(Driver.java:617)
        at com.facebook.presto.operator.Driver.close(Driver.java:151)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:637)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.destroy(TaskExecutor.java:500)
        at com.facebook.presto.execution.TaskExecutor.splitFinished(TaskExecutor.java:273)
        at com.facebook.presto.execution.TaskExecutor.access$2300(TaskExecutor.java:69)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:703)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

```java
2018-07-23T22:57:01.540+0800	ERROR	SplitRunner-792-60354	com.facebook.presto.execution.TaskExecutor	Error processing Split 20180723_145620_13994_d2s3z.4.2-0  (start = 1532357757235, wall = 64305 ms, cpu = 123 ms, calls = 20): PAGE_TRANSPORT_TIMEOUT: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://:8080/v1/task/20180723_145620_13994_d2s3z.5.0/results/20180723_145620_13994_d2s3z.4.2/1 - requests failed for 60.03s)
2018-07-23T22:57:01.555+0800	ERROR	exchange-client-4	com.facebook.presto.operator.HttpPageBufferClient	Request to delete http://:8080/v1/task/20180723_145620_13994_d2s3z.4.3/results/20180723_145620_13994_d2s3z.2.2 failed java.util.concurrent.CancellationException: Task was cancelled.
2018-07-23T22:57:01.555+0800	ERROR	exchange-client-6	com.facebook.presto.operator.HttpPageBufferClient	Request to delete http://:8080/v1/task/20180723_145620_13994_d2s3z.4.5/results/20180723_145620_13994_d2s3z.2.2 failed java.util.concurrent.CancellationException: Task was cancelled.
2018-07-23T22:57:01.555+0800	ERROR	exchange-client-12	com.facebook.presto.operator.HttpPageBufferClient	Request to delete http://:8080/v1/task/20180723_145620_13994_d2s3z.2.5/results/20180723_145620_13994_d2s3z.1.2 failed java.util.concurrent.CancellationException: Task was cancelled.
......
```

```java
2018-07-23T23:51:52.083+0800	ERROR	http-worker-125637	org.glassfish.jersey.server.ServerRuntime$Responder	An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:314)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:197)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:419)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:141)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:741)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:521)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:679)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:728)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:179)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:163)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:441)
	at io.airlift.http.server.TimingFilter$TimedServletOutputStream.write(TimingFilter.java:162)
	at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.write(ResponseWriter.java:325)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._flushBuffer(UTF8JsonGenerator.java:1853)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeCustomStringSegment2(UTF8JsonGenerator.java:1366)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegment(UTF8JsonGenerator.java:1239)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeStringSegments(UTF8JsonGenerator.java:1194)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._writeLongString(UTF8JsonGenerator.java:462)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeString(UTF8JsonGenerator.java:439)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:37)
	at com.fasterxml.jackson.databind.ser.std.StringSerializer.serialize(StringSerializer.java:21)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:491)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:412)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:27)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:505)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:100)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:21)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:183)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:505)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:100)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:21)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:183)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:505)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:100)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:21)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:183)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:505)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:505)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:602)
	at io.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:245)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
	... 47 more
Caused by: java.io.IOException: 断开的管道
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:177)
	... 107 more
```

```java
**2018-07-23T22:00:52.532+0800	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs
2018-07-23T22:18:33.071+0800	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs
2018-07-23T22:18:53.570+0800	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs
2018-07-23T22:48:13.923+0800	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs
2018-07-23T23:05:14.493+0800	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs
2018-07-23T23:31:35.087+0800	INFO	Code-Cache-GC-Trigger	com.facebook.presto.server.CodeCacheGcTrigger	Triggering GC to avoid Code Cache eviction bugs**
```

**Comment by nezihyigitbasi** [comment]
Which Presto version are you using? The stack traces look like they are pretty old versions of the code. 

I strongly recommend you to give one of the latest versions a try. The latest version is 0.207, but we fixed an important bug in that version, so you can try 0.206. Version 0.208 will be released shortly, you can also give it a try.

**Comment by imperio-wxm** [comment]
I update cluster version to 0.205.
Is it a more stable version?
