### ISSUE TITLE
Glue integration: CREATE TABLE fails with NPE ("parameters is null") in some cases

### ISSUE THREAD

**Issue by ilfrin** [prestodb/presto#11167]
With Presto 0.203 when a Glue database (schema) is created from AWS Glue, or created via Presto (CREATE SCHEMA) but later edited via AWS Web UI, eg. setting the "Location" property, then CREATE TABLE using that schema fails in Presto.

It's somewhat similar to https://github.com/prestodb/presto/issues/10573 but that has been fixed with https://github.com/prestodb/presto/pull/10726 fix which is present in 0.203. 

```
presto> create table glue.test.foo (a int);
Query 20180731_151404_00138_wx7wd failed: java.lang.NullPointerException: parameters is null
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: parameters is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:238)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getDatabase(CachingHiveMetastore.java:261)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getDatabase(SemiTransactionalHiveMetastore.java:126)
	at com.facebook.presto.hive.HiveWriteUtils.getDatabase(HiveWriteUtils.java:465)
	at com.facebook.presto.hive.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:445)
	at com.facebook.presto.hive.HiveLocationService.forNewTable(HiveLocationService.java:55)
	at com.facebook.presto.hive.HiveMetadata.createTable(HiveMetadata.java:628)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:227)
	at com.facebook.presto.metadata.MetadataManager.createTable(MetadataManager.java:547)
	at com.facebook.presto.execution.CreateTableTask.internalExecute(CreateTableTask.java:175)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:81)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:63)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:124)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: parameters is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.facebook.presto.hive.metastore.Database$Builder.setParameters(Database.java:152)
	at com.facebook.presto.hive.metastore.glue.converter.GlueToPrestoConverter.convertDatabase(GlueToPrestoConverter.java:56)
	at com.facebook.presto.hive.metastore.glue.GlueHiveMetastore.getDatabase(GlueHiveMetastore.java:168)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadDatabase(CachingHiveMetastore.java:266)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	... 20 more
```

**Comment by ilfrin** [comment]
cc @rentaow

**Comment by rentaow** [comment]
#10726 is in >= 0.204

**Comment by ilfrin** [comment]
hmmm right .. I missed that, thanks!

do you think this is the same issue judging from the stack trace?

**Comment by ilfrin** [comment]
I'll confirm that tomorrow

**Comment by ilfrin** [comment]
Yup that fixes it. Thanks.
