### ISSUE TITLE
Presto Worker Deadlock(hang) on logback when OOM

### ISSUE THREAD

**Issue by zhaiyuyong** [prestodb/presto#11160]
```java
com.facebook.presto.spi.PrestoTransportException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (getting info for task http://10.210.120.116:9090/v1/task/20180731_081712_00329_bgzx6.1.41 - 24 failures, failure duration 300.27s, total failed request time 240.04s)
at com.facebook.presto.server.remotetask.RequestErrorTracker.requestFailed(RequestErrorTracker.java:131)
at com.facebook.presto.server.remotetask.TaskInfoFetcher.failed(TaskInfoFetcher.java:236)
at com.facebook.presto.server.remotetask.SimpleHttpResponseHandler.onFailure(SimpleHttpResponseHandler.java:86)
at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:24)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:58)
at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:38)
at io.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:124)
at io.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:91)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:464)
at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:545)
at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:156)
at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:149)
at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:257)
at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:767)
at org.eclipse.jetty.client.TimeoutCompleteListener.onTimeoutExpired(TimeoutCompleteListener.java:52)
at org.eclipse.jetty.io.CyclicTimeout$Wakeup.run(CyclicTimeout.java:271)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 3 more
Caused by: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed
... 9 more
```

all http-worker-%s thread(200) wait on logback

```java
"http-worker-1968" #1968 prio=5 os_prio=0 tid=0x00007ee370001000 nid=0xd90f waiting on condition [0x00007edd56af2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007ee496f5e4d0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
	at ch.qos.logback.core.AsyncAppenderBase.putUninterruptibly(AsyncAppenderBase.java:181)
	at ch.qos.logback.core.AsyncAppenderBase.put(AsyncAppenderBase.java:172)
	at ch.qos.logback.core.AsyncAppenderBase.append(AsyncAppenderBase.java:161)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at io.airlift.http.server.DelimitedRequestLog.log(DelimitedRequestLog.java:126)
	at org.eclipse.jetty.server.RequestLogCollection.log(RequestLogCollection.java:44)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:694)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:498)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:755)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:673)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zhaiyuyong** [comment]
like https://jira.qos.ch/browse/LOGBACK-1358?attachmentViewMode=list

**Comment by findepi** [comment]
@zhaiyuyong do you say you experienced deadlock after OOM? 
Your Presto server should kill itself after an OOM. Please double check your JVM flags, specially that you have `-XX:+ExitOnOutOfMemoryError` there. 
See https://prestodb.io/docs/current/installation/deployment.html#jvm-config

**Comment by zhaiyuyong** [comment]
@findepi 
```java
# java.lang.OutOfMemoryError: Java heap space
# -XX:OnOutOfMemoryError="kill -9 %p"
#   Executing /bin/sh -c "kill -9 20572"...
os::fork_and_exec failed: Cannot allocate memory (12)

```
jvm config
```java
-server
-javaagent:/etc/zabbix/scripts/hadoop/jolokia-jvm-agent.jar=port=16867,host=0.0.0.0
-Xmx90G
-XX:+UseG1GC
-XX:G1HeapRegionSize=64M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
#-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:+AggressiveOpts
-XX:+UseNUMA
-XX:ReservedCodeCacheSize=512M
-XX:PermSize=1024M
-XX:MaxPermSize=1024M
-verbose:class
-XX:+PrintGCApplicationConcurrentTime
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintGCCause
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintReferenceGC
-XX:PrintFLSStatistics=2
-XX:+PrintAdaptiveSizePolicy
-XX:+PrintSafepointStatistics
-XX:PrintSafepointStatisticsCount=1
-Xloggc:/data/presto/data/var/log/presto-gc.log
```

**Comment by kokosing** [comment]
See that you are not using `-XX:+ExitOnOutOfMemoryError`, but `-XX:OnOutOfMemoryError=kill -9 %p`. From the log you sent it seems that JVM is unable to run kill process due the lack of memory.
