### ISSUE TITLE
Expectation for distributed sort in .206

### ISSUE THREAD

**Issue by rahul9269** [prestodb/presto#11186]
I was using the 206 build to test the distributed sort feature. I have 30 node clusters with query local memory limit set to 14GB. 
My expecation was that for a simple query with a single order by, I should be able to roughly sort 14 * 30 GB of data, is that correct ?

Sample Query on tpch 100 lineitem table:

SELECT l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_discount, l_returnflag, l_linestatus, l_shipdate, l_receiptdate, l_commitdate  from tpch100.lineitem_parq order by l_extendedprice

My queries are failing at the lowest stage , which has TableScanOperator -> TaskOutputOperator.  The TaskOutputOperator fails with the below exception.

com.facebook.presto.ExceededMemoryLimitException: Query exceeded local total memory limit of 14.10GB
	at com.facebook.presto.ExceededMemoryLimitException.exceededLocalTotalMemoryLimit(ExceededMemoryLimitException.java:44)
	at com.facebook.presto.memory.DefaultQueryContext.updateSystemMemory(DefaultQueryContext.java:172)
	at com.facebook.presto.memory.DefaultQueryContext$QueryMemoryReservationHandler.reserveMemory(DefaultQueryContext.java:310)
	at com.facebook.presto.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:35)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:36)
	at com.facebook.presto.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:63)
	at com.facebook.presto.execution.buffer.OutputBufferMemoryManager.updateMemoryUsage(OutputBufferMemoryManager.java:71)
	at com.facebook.presto.execution.buffer.ArbitraryOutputBuffer.enqueue(ArbitraryOutputBuffer.java:215)
	at com.facebook.presto.execution.buffer.LazyOutputBuffer.enqueue(LazyOutputBuffer.java:255)
	at com.facebook.presto.operator.TaskOutputOperator.addInput(TaskOutputOperator.java:149)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Task that failed had processed only 470MB of data. 

Can someone help me understand this scenario ?

**Comment by sopel39** [comment]
Hi @rahul9269 

1. Could you try running the query with config property: `pages-index.eager-compaction-enabled=true`?
2. Could you post `EXPLAIN` and JSON of the failing query?

This could be related to: https://github.com/prestodb/presto/pull/10634
