### ISSUE TITLE
TestTaskExecutor.testLevelMultipliers is flaky

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#11210]
https://gist.github.com/nezihyigitbasi/8a97e5d3f66bcb7ad425a23796566ab3

**Comment by findepi** [comment]
i just run into the same problem:
```
17:03:17 [ERROR] Tests run: 5525, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,464.932 s <<< FAILURE! - in TestSuite
17:03:17 [ERROR] testLevelMultipliers(com.facebook.presto.execution.executor.TestTaskExecutor)  Time elapsed: 0.084 s  <<< FAILURE!
17:03:17 java.lang.IllegalStateException: Attempted arrival of unregistered party for java.util.concurrent.Phaser@5ce07d4a[phase = 11947 parties = 1 arrived = 1]
17:03:17 	at java.util.concurrent.Phaser.arriveAndAwaitAdvance(Phaser.java:686)
17:03:17 	at com.facebook.presto.execution.executor.TestTaskExecutor.testLevelMultipliers(TestTaskExecutor.java:270)
```

I tried to repro locally with eg
```
@Test(invocationCount = 10000, threadPoolSize = 64) // i have 8 logical cores
public void testLevelMultipliers()
```
then the test didn't fail, but the following was logged several times
```
2018-12-14T02:28:14.354-0600 SEVERE Error processing Split test3.0.0      -2 testing-split (start = 867020.0, wall = 1429000 ms, cpu = 3 ms, wait = 1195000 ms, calls = 239)
java.lang.IllegalStateException: Attempted arrival of unregistered party for java.util.concurrent.Phaser@17df21b7[phase = 23805 parties = 1 arrived = 1]
	at java.util.concurrent.Phaser.arriveAndAwaitAdvance(Phaser.java:686)
	at com.facebook.presto.execution.executor.TestTaskExecutor$TestingJob.processFor(TestTaskExecutor.java:532)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_null____20181214_082813_3705.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
or (notice, this is different line)
```
2018-12-14T02:25:02.277-0600 SEVERE Error processing Split test3.0.0      -1 testing-split (start = 21020.0, wall = 45000 ms, cpu = 0 ms, wait = 39000 ms, calls = 9)
java.lang.IllegalStateException: Attempted arrival of unregistered party for java.util.concurrent.Phaser@1394168b[phase = 49 parties = 0 arrived = 0]
	at java.util.concurrent.Phaser.doArrive(Phaser.java:391)
	at java.util.concurrent.Phaser.arriveAndDeregister(Phaser.java:654)
	at com.facebook.presto.execution.executor.TestTaskExecutor$TestingJob.processFor(TestTaskExecutor.java:540)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_null____20181214_082502_1536.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

(stacktraces produced at 62f7c99df5d1ef45c2f96ffb05cbd2c707422815)


at first sight, this looks like some race. I hope that this is just a tests's race.

cc @raghavsethi

**Comment by raghavsethi** [comment]
I spent some time looking at this and can't wrap my head around it. I'm reasonably confident it's not causing issues since it has been running in production for months. I'll likely have time to look at it in the middle of January.

**Comment by rschlussel** [comment]
I saw this issue again today:

```
ERROR] Tests run: 6608, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4,099.217 s <<< FAILURE! - in TestSuite
[ERROR] testLevelMultipliers(com.facebook.presto.execution.executor.TestTaskExecutor)  Time elapsed: 0.032 s  <<< FAILURE!
java.lang.IllegalStateException: Attempted arrival of unregistered party for java.util.concurrent.Phaser@211f986e[phase = 17161 parties = 0 arrived = 0]
	at java.util.concurrent.Phaser.arriveAndAwaitAdvance(Phaser.java:686)
	at com.facebook.presto.execution.executor.TestTaskExecutor.testLevelMultipliers(TestTaskExecutor.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] com.facebook.presto.execution.executor.TestTaskExecutor.testLevelMultipliers(com.facebook.presto.execution.executor.TestTaskExecutor)
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
[INFO]   Run 3: PASS
[INFO]   Run 4: PASS
[INFO]   Run 5: PASS
[INFO]   Run 6: PASS
[INFO]   Run 7: PASS
[INFO]   Run 8: PASS
[INFO]   Run 9: PASS
[INFO]   Run 10: PASS
[INFO]   Run 11: PASS
[INFO]   Run 12: PASS
[ERROR]   Run 13: TestTaskExecutor.testLevelMultipliers:272 » IllegalState Attempted arrival of ...
[INFO]   Run 14: PASS
[INFO]   Run 15: PASS
[INFO]   Run 16: PASS
[INFO]   Run 17: PASS
[INFO]   Run 18: PASS
[INFO]   Run 19: PASS
[INFO]   Run 20: PASS
[INFO]   Run 21: PASS
[INFO]   Run 22: PASS
[INFO]   Run 23: PASS
[INFO]   Run 24: PASS
[INFO]   Run 25: PASS
[INFO]   Run 26: PASS
[INFO]   Run 27: PASS
[INFO]   Run 28: PASS
[INFO]   Run 29: PASS
[INFO]   Run 30: PASS
[INFO]   Run 31: PASS
[INFO]   Run 32: PASS
[INFO]   Run 33: PASS
[INFO]   Run 34: PASS
[INFO]   Run 35: PASS
[INFO]   Run 36: PASS
[INFO]   Run 37: PASS
[INFO]   Run 38: PASS
[INFO]   Run 39: PASS
[INFO]   Run 40: PASS
[INFO]   Run 41: PASS
[INFO]   Run 42: PASS
[INFO]   Run 43: PASS
[INFO]   Run 44: PASS
[INFO]   Run 45: PASS
[INFO]   Run 46: PASS
[INFO]   Run 47: PASS
[INFO]   Run 48: PASS
[INFO]   Run 49: PASS
[INFO]   Run 50: PASS
[INFO]   Run 51: PASS
[INFO]   Run 52: PASS
[INFO]   Run 53: PASS
[INFO]   Run 54: PASS
[INFO]   Run 55: PASS
[INFO]   Run 56: PASS
[INFO]   Run 57: PASS
[INFO]   Run 58: PASS
[INFO]   Run 59: PASS
[INFO]   Run 60: PASS
[INFO]   Run 61: PASS
[INFO]   Run 62: PASS
[INFO]   Run 63: PASS
[INFO]   Run 64: PASS
[INFO]   Run 65: PASS
[INFO]   Run 66: PASS
[INFO]   Run 67: PASS
[INFO]   Run 68: PASS
[INFO]   Run 69: PASS
[INFO]   Run 70: PASS
[INFO]   Run 71: PASS
[INFO]   Run 72: PASS
[INFO]   Run 73: PASS
[INFO]   Run 74: PASS
[INFO]   Run 75: PASS
[INFO]   Run 76: PASS
[INFO]   Run 77: PASS
[INFO]   Run 78: PASS
[INFO]   Run 79: PASS
[INFO]   Run 80: PASS
[INFO]   Run 81: PASS
[INFO]   Run 82: PASS
[INFO]   Run 83: PASS
[INFO]   Run 84: PASS
[INFO]   Run 85: PASS
[INFO]   Run 86: PASS
[INFO]   Run 87: PASS
[INFO]   Run 88: PASS
[INFO]   Run 89: PASS
[INFO]   Run 90: PASS
[INFO]   Run 91: PASS
[INFO]   Run 92: PASS
[INFO]   Run 93: PASS
[INFO]   Run 94: PASS
[INFO]   Run 95: PASS
[INFO]   Run 96: PASS
[INFO]   Run 97: PASS
[INFO]   Run 98: PASS
[INFO]   Run 99: PASS
[INFO]   Run 100: PASS
[INFO] 
[INFO] 
[ERROR] Tests run: 6509, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by rschlussel** [comment]
@arhimondr  it looks like you've touched some code on this test before. Do you have any ideas?

**Comment by arhimondr** [comment]
@rschlussel Not on top of mind mind. I didn't do any significant changes in this codebase.

**Comment by xieandrew** [comment]
Ran into this issue here: https://github.com/prestodb/presto/actions/runs/16155252511/job/45596153364?pr=25433

**Comment by hantangwangd** [comment]
After checking the code of `testLevelMultipliers` in detail, I think the following scenario could potentially trigger this `Phaser` exception:
 - t0: main thread construct the global phaser with parties=2, and then enqueue 6 drivers to the tasks in taskExecutor.
 - t1: main thread pass the check for while loop, which means no driver is finished.
 - t2: a certain driver completes the processing, and then executes `arriveAndDeregister` on the global phaser. Now the global phaser's parties is 1.
 - t3: main thread and another driver which is scheduled to executing may concurrently invoke `arriveAndAwaitAdvance()` on the global phaser.

When two threads concurrently invoke `arriveAndAwaitAdvance()` on a `Phaser` with parties=1, if both requests arrive before the `Phaser` advances to the next phase, it will throw the aforementioned exception. It is a little tricky to reproduce, I've constructed the following code to simulate the `Phaser` usage pattern in `testLevelMultipliers`, and additionally using a control phaser to synchronize the concurrent `arriveAndAwaitAdvance()` calls on the global phaser as much as possible:

```
public class PhaserErrorCatcher
{
    public static void main(String[] args) throws Exception
    {
        for (int r = 0; r < 100000; r++) {
            try {
                doSingleRound(r);
            }
            catch (Exception e) {
                System.err.println("Catch an exception at the " + r + "th round");
                throw e;
            }
        }
    }

    public static void doSingleRound(int idx) {
        Phaser controlPhaser = new Phaser(2);
        Phaser globalPhaser = new Phaser(2);

        // Deregister from globalPhaser when a certain driver[TestingJob] finishes processing
        globalPhaser.arriveAndDeregister();
        System.out.println("==>Current globalPhaser state: isTerminated=" + globalPhaser.isTerminated() +
                ", registered parties=" + globalPhaser.getRegisteredParties() +
                ", arrived parties=" + globalPhaser.getArrivedParties());

        // Simulate the behavior of the sole worker thread in the taskExecutor
        final int WORKER_THREAD_NUMBER = 1;
        for (int i = 0; i < WORKER_THREAD_NUMBER; i++) {
            new Thread(() -> {
                try {
                    controlPhaser.arriveAndAwaitAdvance();
                    globalPhaser.arriveAndAwaitAdvance();
                } catch (Exception e) {
                    System.err.println("Catch an exception at the " + idx + "th round");
                    throw new RuntimeException(e);
                }
            }).start();
        }

        // Simulate the behavior of the main thread
        controlPhaser.arriveAndAwaitAdvance();
        globalPhaser.arriveAndAwaitAdvance();
    }
}
```

According to this test scenario, I think do not call `arriveAndDeregister` on the global phaser upon `TestingJob` completion could prevent this potential issue without affecting the test execution. Further investigation and testing will be done to confirm this.

cc: @rschlussel @arhimondr @xieandrew

**Comment by hantangwangd** [comment]
Closing as completed by #25532
