### ISSUE TITLE
Presto cli broken for named row cast

### ISSUE THREAD

**Issue by rongrong** [prestodb/presto#11216]
presto:di> SELECT cast(row(1, 2) as row(a bigint, b bigint));
java.lang.RuntimeException: Error fetching next at https://[2401:db00:1010:b10e:face:0:f:0]:7778/v1/statement/20180807_213918_07607_qvpd8/2 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Tue, 07 Aug 2018 21:39:18 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20180807_213918_07607_qvpd8","infoUri":"https://[2401:db00:1010:b10e:face:0:f:0]:7778/ui/query.html?20180807_213918_07607_qvpd8","columns":[{"name":"_col0","type":"row(a bigint,b bigint)","typeSignature":{"rawType":"row","typeArguments":[{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["a","b"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"fieldName":{"name":"a","delimited":false},"typeSignature":"bigint"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"fieldName":{"name":"b","delimited":false},"typeSignature":"bigint"}}]}}],"data":[[[1,2]]],"stats":{"state":"FINISHED","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":10,"cpuTimeMillis":1,"wallTimeMillis":1,"queuedTimeMillis":47,"elapsedTimeMillis":75,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"FINISHED","done":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":10,"cpuTimeMillis":1,"wallTimeMillis":1,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":100.0}}
]
        at com.facebook.presto.client.StatementClientV1.requestFailedException(StatementClientV1.java:408)
        at com.facebook.presto.client.StatementClientV1.advance(StatementClientV1.java:356)
        at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:122)
        at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:132)
        at com.facebook.presto.cli.Query.renderOutput(Query.java:116)
        at com.facebook.presto.cli.Console.process(Console.java:310)
        at com.facebook.presto.cli.Console.runConsole(Console.java:254)
        at com.facebook.presto.cli.Console.run(Console.java:144)
        at com.facebook.presto.cli.Presto.main(Presto.java:31)
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.client.QueryResults from JSON response:
[{"id":"20180807_213918_07607_qvpd8","infoUri":"https://[2401:db00:1010:b10e:face:0:f:0]:7778/ui/query.html?20180807_213918_07607_qvpd8","columns":[{"name":"_col0","type":"row(a bigint,b bigint)","typeSignature":{"rawType":"row","typeArguments":[{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"bigint","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["a","b"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"fieldName":{"name":"a","delimited":false},"typeSignature":"bigint"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"fieldName":{"name":"b","delimited":false},"typeSignature":"bigint"}}]}}],"data":[[[1,2]]],"stats":{"state":"FINISHED","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":10,"cpuTimeMillis":1,"wallTimeMillis":1,"queuedTimeMillis":47,"elapsedTimeMillis":75,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"FINISHED","done":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":10,"cpuTimeMillis":1,"wallTimeMillis":1,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":100.0}}
]
        at com.facebook.presto.client.JsonResponse.<init>(JsonResponse.java:69)
        at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:143)
        at com.facebook.presto.client.StatementClientV1.advance(StatementClientV1.java:342)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class com.facebook.presto.client.QueryResults]
        at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
        at com.facebook.presto.client.JsonResponse.<init>(JsonResponse.java:66)
        ... 9 more
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "fieldName" (class com.facebook.presto.spi.type.NamedTypeSignature), not marked as ignorable (2 known properties: "name", "typeSignature"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.facebook.presto.client.QueryResults["columns"]->java.util.ArrayList[0]->com.facebook.presto.client.Column["typeSignature"]->com.facebook.presto.client.ClientTypeSignature["arguments"]->java.util.ArrayList[0]->com.facebook.presto.spi.type.NamedTypeSignature["fieldName"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:833)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1096)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1467)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1421)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:487)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3761)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2090)
        at com.facebook.presto.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:150)
        at com.facebook.presto.client.ClientTypeSignatureParameter$ClientTypeSignatureParameterDeserializer.deserialize(ClientTypeSignatureParameter.java:132)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:396)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
        at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
        ... 10 more

**Comment by martint** [comment]
This is probably related to 
https://github.com/prestodb/presto/issues/3693

**Comment by haozhun** [comment]
It's not related to #3693.

We broke client backward compatibility in 0.205. https://github.com/prestodb/presto/commit/8dce0bbc76f11d8eabd021884536e9a7d1e43459

**Comment by martint** [comment]
> We broke client backward compatibility in 0.205

So it's only an issue if you're running an older version of the CLI? Or does it also happen it the CLI version matches the server version?

**Comment by electrum** [comment]
The problem is we dropped the `name` field which the `NamedTypeSignature` required to be non-null. We need to do the following:

* Add the field for old clients
* Add parsing of the old field for new clients
