### ISSUE TITLE
Connecting to Netezza Database failing

### ISSUE THREAD

**Issue by Gaurang033** [prestodb/presto#11221]
hi Guys, 

I realize we don't have seperate driver for Netezza so can I connect to **Netezza** using **postgresSQL** driver? 
I tried it however it shows following error. 
```
2018-08-08T13:42:06.124-0400	ERROR	Query-20180808_174205_00000_qwr8d-165	org.postgresql.Driver	Connection error:
org.postgresql.util.PSQLException: A connection could not be made using the requested protocol null.
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:57)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at com.facebook.presto.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:59)
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:119)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.listSchemaNames(JdbcMetadata.java:72)
	at com.facebook.presto.metadata.MetadataManager.listSchemaNames(MetadataManager.java:290)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.calculatePrefixesWithSchemaName(InformationSchemaMetadata.java:257)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.getTableLayouts(InformationSchemaMetadata.java:222)
	at com.facebook.presto.metadata.MetadataManager.getLayouts(MetadataManager.java:350)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.planTableScan(PickTableLayout.java:203)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.access$200(PickTableLayout.java:61)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutWithoutPredicate.apply(PickTableLayout.java:186)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutWithoutPredicate.apply(PickTableLayout.java:153)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:165)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:138)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:103)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:185)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:105)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:185)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:105)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:94)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:140)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:129)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:341)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:326)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
following is my **netezza.properties** catalog file 

```
connector.name=postgresql
connection-url=jdbc:netezpostgresql://myhost:5480/mydb
connection-user=myuser
connection-password=mypassword
```

I found a netezza connector in forked repo, however not sure how to use it. is there anyway I can provide external connector in configuration file?

**Comment by pdanilew** [comment]
Hi, you are using postgresql JDBC drivers with Netteza.
You can create your own connector based on existing ones. It is not difficult, I wrote one for Teradata.

**Comment by electrum** [comment]
Try using the Redshift connector. It uses an older version of the PostgreSQL driver and might work. Otherwise, modify or fork the Redshift connector and change it to use the Netezza JDBC driver (nzjdbc) rather than the PostgreSQL one

**Comment by Gaurang033** [comment]
@electrum Thanks. I am able to successfully build the Netezza connector. However I have few questions.  In case if I want to create a pull request. 

- I was not able to find Netezza JDBC jar on maven.  so is that okay if I use System Jar. I mean can I check-in the nzjdbc.jar with code and use that in maven? 

- How to create the catalog file for Netezza? for pull-request is it okay if I don't. will it be accepted?
