### ISSUE TITLE
Race condition in OuterPositionTracker

### ISSUE THREAD

**Issue by dain** [prestodb/presto#11223]
This is a reoccurrence of #9766 and #9982.
```
com.google.common.base.VerifyException
	at com.google.common.base.Verify.verify(Verify.java:99)
	at com.facebook.presto.operator.PartitionedLookupSource$OuterPositionTracker.positionVisited(PartitionedLookupSource.java:330)
	at com.facebook.presto.operator.PartitionedLookupSource.appendTo(PartitionedLookupSource.java:179)
	at com.facebook.presto.operator.LookupJoinPageBuilder.appendRow(LookupJoinPageBuilder.java:78)
	at com.facebook.presto.operator.LookupJoinOperator.joinCurrentPosition(LookupJoinOperator.java:540)
	at com.facebook.presto.operator.LookupJoinOperator.processProbe(LookupJoinOperator.java:467)
	at com.facebook.presto.operator.LookupJoinOperator.lambda$processProbe$3(LookupJoinOperator.java:399)
	at com.facebook.presto.operator.PartitionedLookupSourceFactory$SpillAwareLookupSourceProvider.withLease(PartitionedLookupSourceFactory.java:432)
	at com.facebook.presto.operator.LookupJoinOperator.processProbe(LookupJoinOperator.java:396)
	at com.facebook.presto.operator.LookupJoinOperator.getOutput(LookupJoinOperator.java:311)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by mbasmanova** [comment]
@dain @findepi Dain, Piotr, we ran into this again in production. A query retried 20 times and failed every time. Do you have any theories about what might be causing this?

**Comment by mbasmanova** [comment]
CC: @haozhun

**Comment by haozhun** [comment]
This has been fixed. It's not a race condition.

https://github.com/prestodb/presto/pull/11636
https://github.com/prestodb/presto/pull/11794
