### ISSUE TITLE
presto 0.208 client.SliderClient - java.io.FileNotFoundException: Unknown export presto

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto#11256]
I am seeing following error. when i run
slider registry --name presto1 --getexp presto
2018-08-13 18:33:08,844 [main] INFO  impl.MetricsConfig - loaded properties from hadoop-metrics2-azure-file-system.properties
2018-08-13 18:33:08,848 [main] INFO  sink.WasbAzureIaasSink - Init starting.
2018-08-13 18:33:08,848 [main] INFO  sink.AzureIaasSink - Init starting. Initializing MdsLogger.
2018-08-13 18:33:08,861 [main] INFO  sink.AzureIaasSink - Init completed.
2018-08-13 18:33:08,861 [main] INFO  sink.WasbAzureIaasSink - Init completed.
2018-08-13 18:33:08,877 [main] INFO  impl.MetricsSinkAdapter - Sink azurefs2 started
2018-08-13 18:33:09,027 [main] INFO  impl.MetricsSystemImpl - Scheduled snapshot period at 60 second(s).
2018-08-13 18:33:09,027 [main] INFO  impl.MetricsSystemImpl - azure-file-system metrics system started
2018-08-13 18:33:09,525 [main] INFO  client.AHSProxy - Connecting to Application History server at headnodehost/10.0.0.18:10200
2018-08-13 18:33:09,697 [main] INFO  imps.CuratorFrameworkImpl - Starting
2018-08-13 18:33:09,770 [main-EventThread] INFO  state.ConnectionStateManager - State change: CONNECTED
2018-08-13 18:33:11,860 [main] INFO  client.SliderClient - java.io.FileNotFoundException: Unknown export presto
2018-08-13 18:33:11,864 [main] INFO  util.ExitUtil - Exiting with status 44
2018-08-13 18:33:11,926 [pool-1-thread-1] INFO  impl.MetricsSystemImpl - Stopping azure-file-system metrics system...
2018-08-13 18:33:11,926 [azurefs2] INFO  impl.MetricsSinkAdapter - azurefs2 thread interrupted.
2018-08-13 18:33:11,931 [pool-1-thread-1] INFO  impl.MetricsSystemImpl - azure-file-system metrics system stopped.
2018-08-13 18:33:11,931 [pool-1-thread-1] INFO  impl.MetricsSystemImpl - azure-file-system metrics system shutdown complete.

is there something I am missing ?

**Comment by kokosing** [comment]
Are you using presto-yarn (https://github.com/prestodb/presto-yarn)?

**Comment by nakhanha** [comment]
Yes I am, I was previously using presto 0.187 and it is working fine. seeing problems with 0.208

**Comment by nakhanha** [comment]
2018-08-13 22:23:15,085 [AMRM Callback Handler Thread] ERROR appmaster.SliderAppMaster - Role instance RoleInstance{role='WORKER', id='container_1534186717238_0005_01_000027', container=ContainerID=container_1534186717238_0005_01_000027 nodeID=wn1-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:30050 http=wn1-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:30060 priority=1073741826 resource=<memory:24576, vCores:1>, createTime=1534198973135, startTime=1534198973148, completionTime=0, released=false, roleId=2, host=wn1-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net, hostURL=http://wn1-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:30060, state=5, placement=null, exitCode=0, command='python ./infra/agent/slider-agent/agent/main.py --label container_1534186717238_0005_01_000027___WORKER --zk-quorum zk0-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:2181,zk1-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:2181,zk3-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:2181 --zk-reg-path /registry/users/root/services/org-apache-slider/presto1 > <LOG_DIR>/slider-agent.out 2>&1 ; ', diagnostics='', output=null, logLink=http://wn1-nkhia2.gfzh4zwlyuyevicwo5snq3uech.cx.internal.cloudapp.net:30060/node/containerlogs/container_1534186717238_0005_01_000027/root, environment=[LANGUAGE="en_US.UTF-8", HADOOP_USER_NAME="root", PYTHONPATH="./infra/agent/slider-agent/:./infra/agent/slider-agent/jinja2", AGENT_LOG_ROOT="<LOG_DIR>", SLIDER_PASSPHRASE="FoLIt4om9fprGV8HtDQRawzcsV2JxAPuU2fJU85S9ZumZPLzmP", LC_ALL="en_US.UTF-8", AGENT_WORK_ROOT="$PWD", LANG="en_US.UTF-8", MALLOC_ARENA_MAX="4"]} failed 



seeing this error in Yarn logs

**Comment by nakhanha** [comment]
node logs show
2018-08-13T20:29:10.179Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

**Comment by nakhanha** [comment]
2018-08-14T03:15:26.579Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.IllegalArgumentException: Max query memory per node (query.max-memory-per-node) cannot be greater than the max query total memory per node (query.max-total-memory-per-node).
    "site.global.presto_query_max_memory": "26GB",
    "site.global.presto_query_max_memory_per_node": "13GB",
    "site.global.presto_server_port": "9090",

**Comment by nakhanha** [comment]
i changed the memory to 5G and this error wasnt thrown.

However seeing this error

2018-08-14T06:11:54.427Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

sshuser@wn1-nkhiap:/var/lib/presto/etc$ cat queues.json
{
  "queues": {
    "global": {
      "maxConcurrent": 10,
      "maxQueued": 100
    }
  },
  "rules": [
    {
      "queues": [
        "global"
      ]
    }
  ]
}


sshuser@wn1-nkhiap:/var/lib/presto/etc$ cat queues.json
{
  "queues": {
    "global": {
      "maxConcurrent": 10,
      "maxQueued": 100
    }
  },
  "rules": [
    {
      "queues": [
        "global"
      ]
    }
  ]
}
is there soemthign I am missing ?

**Comment by aeoles** [comment]
I have encountered the same error, how do u fix that
