### ISSUE TITLE
Filter is executing after Project for queries including CROSS JOIN 

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#11265]
```sql
SELECT tt
FROM 
(
    SELECT x
    FROM (VALUES -100, -50, 50) as t(x)
) t
CROSS JOIN
(
    SELECT MAP(ARRAY[1, 2], ARRAY[y1, y2]) bounds
    FROM (VALUES (-85, 85)) as r(y1, y2)
) r
CROSS JOIN UNNEST (ARRAY[BING_TILE_AT(x, x, 16)]) AS p(tt)

WHERE 
    t.x BETWEEN r.bounds[1] and r.bounds[2]

```

Stacktrace:

```
Query 20180814_005430_10274_2s8tm failed: Latitude must be between -85.05112878 and 85.05112878
com.facebook.presto.spi.PrestoException: Latitude must be between -85.05112878 and 85.05112878
        at com.facebook.presto.plugin.geospatial.BingTileFunctions.checkCondition(BingTileFunctions.java:479)
        at com.facebook.presto.plugin.geospatial.BingTileFunctions.checkLatitude(BingTileFunctions.java:468)
        at com.facebook.presto.plugin.geospatial.BingTileFunctions.bingTileAt(BingTileFunctions.java:155)
        at com.facebook.presto.$gen.PageProjectionWork_20180814_005430_10274_2s8tm_0_15_448431.evaluate(Unknown Source)
        at com.facebook.presto.$gen.PageProjectionWork_20180814_005430_10274_2s8tm_0_15_448431.process(Unknown Source)
        at com.facebook.presto.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.process(DictionaryAwarePageProjection.java:175)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:278)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:182)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:129)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:49)
        at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:110)
        at com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:95)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:373)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

Query Plan:

```
---------------------------------------------------------------------------------------------------------------------------------------------------------
 Fragment 0 [SINGLE]
     Output layout: [field_13]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Output[tt] => [field_13:BingTile]
             tt := field_13
         - Unnest [replicate=, unnest=expr_14:array(BingTile)] => [field_13:BingTile]
!Note -->    - Filter[filterPredicate = ("field" BETWEEN "map"[1] AND "map"[2])] => [field:integer, map:map(integer, integer), expr_14:array(BingTile)]        
                     Cost: {rows: 3 (288B), cpu: 25840.00, memory: 12495.00, network: 0.00}
                 - Project[] => [field:integer, map:map(integer, integer), expr_14:array(BingTile)]
                         Cost: {rows: 3 (321B), cpu: 25519.00, memory: 12495.00, network: 0.00}
                         expr_14 := "array_constructor"("bing_tile_at"(CAST("field" AS double), CAST("field" AS double), 16))
                     - CrossJoin => [field:integer, map:map(integer, integer)]
                             Distribution: REPLICATED
                             Cost: {rows: 3 (168B), cpu: 25198.00, memory: 12495.00, network: 0.00}
                         - LocalExchange[ROUND_ROBIN] () => field:integer
                                 Cost: {rows: 3 (15B), cpu: 15.00, memory: 0.00, network: 0.00}
                             - Values => [field:integer]
                                     Cost: {rows: 3 (15B), cpu: 0.00, memory: 0.00, network: 0.00}
                                     (-100)
                                     (-50)
                                     (50)
                         - LocalExchange[SINGLE] () => map:map(integer, integer)
                                 Cost: {rows: 1 (51B), cpu: 61.00, memory: 0.00, network: 0.00}
                             - Project[] => [map:map(integer, integer)]
                                     Cost: {rows: 1 (51B), cpu: 61.00, memory: 0.00, network: 0.00}
                                     map := "map"("$literal$array(integer)"("from_base64"('CQAAAElOVF9BUlJBWQIAAAAAAQAAAAIAAAA=')), "array_constructor"("
                                 - LocalExchange[ROUND_ROBIN] () => field_4:integer, field_5:integer
                                         Cost: {rows: 1 (10B), cpu: 10.00, memory: 0.00, network: 0.00}
                                     - Values => [field_4:integer, field_5:integer]
                                             Cost: {rows: 1 (10B), cpu: 0.00, memory: 0.00, network: 0.00}
                                             (-85, 85)
```

Per report, this bug only happens after Presto 0.208

**Comment by martint** [comment]
That’s expected behavior. Logically, the filter executes after the from clause. You need to move the filters to a subquery before the correlated join is evaluated.

**Comment by rschlussel** [comment]
@martint it may be correct, but I don't think it was an intentional change and it's not consistent for all types of predicates.  For example, if you change `t.x BETWEEN r.bounds[1] AND r.bounds[2]` to  `t.x > r.bounds[1] AND t.x <r.bounds[2]`, the filter gets pushed below the project again.  I strongly suspect it's related to https://github.com/prestodb/presto/commit/6dcd67fdffbe291ca68f1c5fe8936a575cce86df.

**Comment by martint** [comment]
Yes, it's almost certainly related to that PR. The reason it may no be being pushed may be related to BETWEEN not being processed in the same way as simple comparison expressions.

This is an interesting case that highlights a much larger problem. In general, it's incorrect to push predicates through expressions that may fail on input. Doing so can cause queries that would fail if evaluated according to strict spec semantics to succeed.

**Comment by sopel39** [comment]
> This is an interesting case that highlights a much larger problem. In general, it's incorrect to push predicates through expressions that may fail on input. Doing so can cause queries that would fail if evaluated according to strict spec semantics to succeed.

It's rather hard to determine if projection might or not depending if filter is pushed down. This could be feature of the data as projection and filter symbols can be different.

**Comment by wenleix** [comment]
Interestingly, PostgreSQL push predicate into subquery .

The following query failed: 
```sql
SELECT 
    id, 
    1 / id AS div
FROM test_tbl

# ERROR:  division by zero

    SELECT id
    FROM test_tbl
    WHERE 1 / id = 0

# ERROR:  division by zero
```

But the following query succeed:
```sql

SELECT *
FROM (
    SELECT 
        id, 
        1 / id AS div
    FROM test_tbl
) AS foo
WHERE id != 0

# success

SELECT *
FROM (
    SELECT id
    FROM test_tbl
    WHERE 1 / id = 0
) AS foo
WHERE id != 0

# success
```

The test table is created via https://gist.github.com/wenleix/526c309f2aa671c6d015a61623bdb9cb

**Comment by wenleix** [comment]
Confirmed Oracle DB has the same predicate pushdown behavior. As shown in https://livesql.oracle.com/apex/livesql/s/g66lacpzjz8p5e3njr3gf9bv7.
