### ISSUE TITLE
presto server doesnt start with the error. 

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto#11270]
Hi all,

I have presto on an yarn cluster.

When i try to run slider registry  --name presto1 --getexp presto. 

i see this error
2018-08-13 18:33:11,860 [main] INFO client.SliderClient - java.io.FileNotFoundException: Unknown export presto
2018-08-13 18:33:11,864 [main] INFO util.ExitUtil - Exiting with status 44

In the server.log on my coordinator node.

18-08-14T15:47:37.543Z        WARN    main    Bootstrap       query.queue-config-file
2018-08-14T15:47:37.543Z        WARN    main    Bootstrap
2018-08-14T15:47:38.124Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Defunct property 'query.queue-config-file' (class [class com.facebook.presto.execution.QueryManagerConfig]) cannot be configured.

2) Configuration property 'query.queue-config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

this is my queues.json
sshuser@wn1-nkhiap:/var/lib/presto/etc$ cat queues.json
{
"queues": {
"global": {
"maxConcurrent": 10,
"maxQueued": 100
}
},
"rules": [
{
"queues": [
"global"
]
}
]
}

these are the config properties
sshuser@wn3-nkhiap:/var/lib/presto/data/etc$ cat config.properties
coordinator=false
http-server.http.port=9090
query.max-memory=26GB
query.max-memory-per-node=5GB
discovery.uri=http://wn0-nkhiap.rqmghcde2gkufogg2yw2g55yid.cx.internal.cloudapp.net:9090
sshuser@wn3-nkhiap:/var/lib/presto/data/etc$ cat jvm.config
-server
-Xmx23G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
sshuser@wn3-nkhiap:/var/lib/presto/data/etc$ free
total used free shared buff/cache available
Mem: 28789328 2665856 24443184 102416 1680288 25434564
Swap: 7340028 0 7340028
sshuser@wn3-nkhiap:/var/lib/presto/data/etc$ free -g
total used free shared buff/cache available
Mem: 27 2 23 0 1 24
Swap: 6 0 6
sshuser@wn3-nkhiap:/var/lib/presto/data/etc$

**Comment by dain** [comment]
The "query queues" system was replaced by "resource groups" system a long time ago.  You can read about configuring resource groups here: https://prestodb.io/docs/current/admin/resource-groups.html

**Comment by nakhanha** [comment]
thanks dain

**Comment by nakhanha** [comment]
@dain  which presto version was this replaced in ?

**Comment by dain** [comment]
I don't remember, but it will be mentioned in the release notes.

**Comment by nakhanha** [comment]
it was dropped in 0.198

https://prestodb.io/docs/current/release/release-0.198.html

@dain Thanks

**Comment by nakhanha** [comment]
it was dropped in 0.198

https://prestodb.io/docs/current/release/release-0.198.html

@dain Thanks
