### ISSUE TITLE
Error when select count(1) in release 0.204

### ISSUE THREAD

**Issue by sczhaoqi** [prestodb/presto#11276]
when i execute sql on hive catalog as follows
sql1:
```
select count(1) from (select sum(field1) from table limit 10) a;
```
sql2:
```
select count(*) from (select sum(field1) from table  limit 10) a;
```
execute the sql1:
```
 java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.facebook.presto.sql.planner.optimizations.HashGenerationOptimizer$Rewriter.visitDistinctLimit(HashGenerationOptimizer.java:212)
```
but the sql2' results is right

**Comment by sczhaoqi** [comment]
@findepi  The test results I just made are similar to the previous ones, but with different Error 

2018-12-17T14:55:08.674+0800	ERROR	remote-task-callback-28	com.facebook.presto.execution.StageStateMachine	Stage 20181217_065508_00028_ezngw.1 failed
java.lang.ArrayIndexOutOfBoundsException: 0
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at com.facebook.presto.operator.MultiChannelGroupByHash.addNewGroup(MultiChannelGroupByHash.java:310)
	at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:293)
	at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:270)
	at com.facebook.presto.operator.MultiChannelGroupByHash.access$200(MultiChannelGroupByHash.java:54)
	at com.facebook.presto.operator.MultiChannelGroupByHash$GetRunLengthEncodedGroupIdsWork.process(MultiChannelGroupByHash.java:824)
	at com.facebook.presto.operator.DistinctLimitOperator.processUnfinishedWork(DistinctLimitOperator.java:222)
	at com.facebook.presto.operator.DistinctLimitOperator.addInput(DistinctLimitOperator.java:167)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_213__0_204____20181217_064110_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sczhaoqi** [comment]
The test table like :
create table test1(
id String,
age int
)
insert into table1 values ('id1', 1);

**Comment by sczhaoqi** [comment]
we are using apache hadoop 2.7.4 and apache hive 2.1.1
