### ISSUE TITLE
Nginx on EMR cannot communicate with Presto Server

### ISSUE THREAD

**Issue by mnoumanshahzad** [prestodb/presto#11312]
Hi All,

Following is my current stack
Presto --> 0.203
Presto JDBC --> 0.203
EMR --> 5.16.0
Nginx --> 1.12.1

I am using Nginx as a reverse proxy and direct all incoming traffic (from a custom port) to the Presto Server on the EMR master node.

Following is my server block from the Nginx configuration
```
server {
    listen       52525 default_server;
    listen       [::]:52525 default_server;
    server_name  localhost;
    root         /usr/share/nginx/html;

    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;

    # Redirects base path to Presto Web UI
    location / {

      auth_basic $auth;
      auth_basic_user_file /etc/nginx/.htpasswd;

      proxy_set_header Accept-Encoding "";
      sub_filter_types *;
      sub_filter_once off;
      sub_filter 'http://localhost:8889/' 'https://presto.DNS_NAME_PLACEHOLDER/';
      proxy_pass http://localhost:8889/;
    }

    # Redirects to Ganglia Web UI
    location /ganglia {

      auth_basic $auth;
      auth_basic_user_file /etc/nginx/.htpasswd;

      proxy_pass http://localhost:80/ganglia;
    }
}
```
This is the error I see when trying to connect using Presto JDBC driver
```
java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:271)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:225)
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:75)
	at Sample.main(Sample.java:15)
Caused by: java.lang.RuntimeException: Error fetching next (attempts: 50, duration: 2.05m)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:329)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1734)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:118)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:246)
	... 3 more
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8889
	at com.facebook.presto.jdbc.internal.client.JsonResponse.execute(JsonResponse.java:148)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:352)
	... 6 more
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:8889
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:240)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.facebook.presto.jdbc.internal.client.OkHttpUtil.lambda$basicAuth$1(OkHttpUtil.java:91)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.facebook.presto.jdbc.internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:77)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.facebook.presto.jdbc.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at com.facebook.presto.jdbc.internal.okhttp3.RealCall.execute(RealCall.java:77)
	at com.facebook.presto.jdbc.internal.client.JsonResponse.execute(JsonResponse.java:130)
	... 7 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.platform.Platform.connectSocket(Platform.java:125)
	at com.facebook.presto.jdbc.internal.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
	... 31 more
```

The same configurations work on my previous stack just fine
Presto --> 0.194
Presto JDBC --> 0.194
EMR --> 5.15.0
Nginx --> 5.12.1

- Presto server process is running fine
- If I run my JDBC application from the EMR master node, it works fine
- I do see 200 OK status in the Nginx access logs for a GET and a POST request coming in from Presto JDBC driver
- Have tried replacing 'localhost' in the nginx configuration with '127.0.0.1' and with the master node's IP
- Tried to play around with the location block in the nginx configuration

I have tried multiple things but had no luck getting to the root cause. 
Kindly help
Thanks

**Comment by electrum** [comment]
Based on the JDBC stack trace, it seems the driver is trying to connect to `localhost:8889`. Shouldn't be trying to connect to the Nginx port `52525`?

Try running both of these:
```
presto --debug --execute 'select 123' --server localhost:8889
presto --debug --execute 'select 123' --server localhost:52525

**Comment by dain** [comment]
Please, reopen if that did not resolve your issue.

**Comment by mnoumanshahzad** [comment]
Thanks for you help...!

I tried some stuff out, and seems like my Nginx configuration was problematic.

The problem was the following line:
`      sub_filter 'http://localhost:8889/' 'https://presto.DNS_NAME_PLACEHOLDER/';
`

This line is swapping the string in the HTTP Response messages before sending it back to the client. (i.e. NextUri in the response message for the JDBC requests)

In the newer Presto versions, the NextUri starts with 'https' rather than 'http'.

To avoid it completely, i have replaced the following lines

sub_filter_types *;
sub_filter_once off;
sub_filter 'http://localhost:8889/' 'https://presto.DNS_NAME_PLACEHOLDER/';


with

`    proxy_set_header Host $host;
`
