### ISSUE TITLE
Presto Raptor plugin fails DELETE FROM query if table has column of Decimal type

### ISSUE THREAD

**Issue by OleksiiDuzhyi** [prestodb/presto#11339]
When running DELETE FROM query on presto-raptor plugin for a table with column of decimal type the following exception is thrown:

```
java.util.concurrent.CompletionException: com.facebook.presto.spi.PrestoException: Failed to rewrite shard file: /presto/data/var/data/storage/91/5e/915eb10e-752b-4d73-a2d0-d84485708df8.orc
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.presto.spi.PrestoException: Failed to rewrite shard file: /presto/data/var/data/storage/91/5e/915eb10e-752b-4d73-a2d0-d84485708df8.orc
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteFile(OrcStorageManager.java:437)
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteShard(OrcStorageManager.java:402)
	at com.facebook.presto.raptor.storage.OrcStorageManager.lambda$null$0(OrcStorageManager.java:308)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more
Caused by: java.io.IOException: Unhandled ORC object: org.apache.hadoop.hive.serde2.io.HiveDecimalWritable
	at com.facebook.presto.raptor.storage.OrcFileRewriter.uncompressedSize(OrcFileRewriter.java:180)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.uncompressedSize(OrcFileRewriter.java:146)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.rewrite(OrcFileRewriter.java:127)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.rewrite(OrcFileRewriter.java:93)
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteFile(OrcStorageManager.java:434)
	... 6 more
```

Previously discussed in #8888

**Comment by electrum** [comment]
Fixed in #11522
