### ISSUE TITLE
failed: Unhandled type for long:tinyint

### ISSUE THREAD

**Issue by seqid** [prestodb/presto#11335]
version:
don`t know how to find presto-server version.

presto client log:
```
presto> create table mongodb.test.xxx as select * from mysql.test.xxx order by xxx limit 10;
CREATE TABLE: 10 rows

Query 20180822_040229_00010_xdwqe, FINISHED, 9 nodes
Splits: 187 total, 187 done (100.00%)
0:16 [454K rows, 0B] [29.1K rows/s, 0B/s]

presto> select * from mongodb.test.xxx;

Query 20180822_040307_00011_xdwqe, FAILED, 2 nodes
Splits: 17 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20180822_040307_00011_xdwqe failed: Unhandled type for long:tinyint
```
presto server log:
```
2018-08-22T04:36:02.245Z	INFO	query-execution-84	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20180822_043601_00118_xdwqe :: Transaction:[9fdcb5a4-670c-49eb-9d9f-9a84e43e9c89] :: elapsed 1172ms :: planning 27ms :: scheduling 1145ms :: running 0ms :: finishing 1145ms :: begin 2018-08-22T04:36:01.065Z :: end 2018-08-22T04:36:02.237Z
2018-08-22T04:44:04.542Z	ERROR	remote-task-callback-296	com.facebook.presto.execution.StageStateMachine	Stage 20180822_044404_00119_xdwqe.1 failed
com.facebook.presto.spi.PrestoException: Unhandled type for long:tinyint
	at com.facebook.presto.mongodb.MongoPageSource.appendTo(MongoPageSource.java:169)
	at com.facebook.presto.mongodb.MongoPageSource.getNextPage(MongoPageSource.java:131)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:256)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:624)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2018-08-22T04:44:04.550Z	INFO	query-execution-93	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20180822_044404_00119_xdwqe :: Transaction:[18ce728c-1b55-4c77-9789-9b47fb491b5e] :: elapsed 35ms :: planning 17ms :: scheduling 8ms :: running 4ms :: finishing 6ms :: begin 2018-08-22T04:44:04.507Z :: end 2018-08-22T04:44:04.542Z
```

**Comment by ebyhr** [comment]
I couldn't reproduce this from your info. Would you share DDL of `mysql.test.xxx`?

**Comment by seqid** [comment]
please add column type tinyint or char(12), then you can get the same error.
