### ISSUE TITLE
java.lang.OutOfMemoryError: Requested array size exceeds VM limit when reading large Text files

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#11367]
When reading large text files, in fairly rare cases Presto hive is requesting allocation of byte[] of size 2,147,483,646 or 2,147,483,647. This exceeds the VM limit which is Integer.MAX_VALUE-2. However apache hadoop library uses Integer.MAX_VALUE as the limit and allows such allocation. This results in the OutOfMemoryError but it's not caught by Presto Hive. As a result of our JVM configuration, this results in JVM restarts and kills all queries running on the cluster. The call stack is:

	At org.apache.hadoop.io.Text.setCapacity(Text.java:179)
	At org.apache.hadoop.io.Text.append(Text.java:165)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:249)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)
	at org.apache.hadoop.mapreduce.lib.input.UncompressedSplitLineReader.readLine(UncompressedSplitLineReader.java:94)
	at org.apache.hadoop.mapred.LineRecordReader.<init>(LineRecordReader.java:136)
	at org.apache.hadoop.mapred.TextInputFormat.getRecordReader(TextInputFormat.java:67)
	at com.facebook.presto.hive.HiveUtil.createRecordReader(HiveUtil.java:204)

Reference:
https://plumbr.io/outofmemoryerror/requested-array-size-exceeds-vm-limit

**Comment by findepi** [comment]
Just curious, which Presto version is this? See:
```
At org.apache.hadoop.io.Text.setCapacity(Text.java:179)
At org.apache.hadoop.io.Text.append(Text.java:165)
at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:249)   <-- this, i guess, would be line 243 in current master
...
```

**Comment by yingsu00** [comment]
@findepi Hi this stack was from decompiled code of hadoop2. We're depending on  hadoop-apache2-2.7.4-3. And my presto version is up to date. Did you mean the current master of hadoop2 it has a different line number?

**Comment by wenleix** [comment]
Hadoop LineReader was monkey-patched in https://github.com/prestodb/presto-hadoop-apache2/pull/30
