### ISSUE TITLE
presto server installation failed: resource groups not used

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto#11377]
2018-08-28T21:39:45.492Z        WARN    main    Bootstrap       UNUSED PROPERTIES
2018-08-28T21:39:45.492Z        WARN    main    Bootstrap       resource-groups.config-file
2018-08-28T21:39:45.492Z        WARN    main    Bootstrap       resource-groups.configuration-manager
2018-08-28T21:39:45.492Z        WARN    main    Bootstrap
2018-08-28T21:39:46.135Z        ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Configuration property 'resource-groups.config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2) Configuration property 'resource-groups.configuration-manager' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'resource-groups.config-file' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2) Configuration property 'resource-groups.configuration-manager' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:234)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

sshuser@wn1-nkh207:/var/lib/presto/data/etc$ cat config.properties
coordinator=true
node-scheduler.include-coordinator=False
discovery-server.enabled=true
http-server.http.port=9090
query.max-memory=26GB
query.max-memory-per-node=5GB
discovery.uri=http://wn1-nkh207.tyzgimpt4ifexi5svc1bekkc5g.cx.internal.cloudapp.net:9090
resource-groups.configuration-manager=file
resource-groups.config-file=/var/lib/presto/etc/resource_groups.json
sshuser@wn1-nkh207:/var/lib/presto/data/etc$ cat resource_groups.json
{
  "rootGroups": [
    {
      "name": "global",
      "softMemoryLimit": "80%",
      "maxRunning": 100,
      "maxQueued": 100
    }
  ],
  "selectors": [
    {
      "user":
      "group":
    },
    {
      "source":
      "group":
    },
    {
      "group":
    }
  ]
}
sshuser@wn1-nkh207:/var/lib/presto/data/etc$

**Comment by oneonestar** [comment]
```
resource-groups.configuration-manager=file
resource-groups.config-file=/var/lib/presto/etc/resource_groups.json
```
This should be placed in the file `etc/resource-groups.properties`. See https://prestodb.io/docs/current/admin/resource-groups.html

**Comment by nakhanha** [comment]
@oneonestar Should it be only present on cordinator nodes ?

**Comment by oneonestar** [comment]
This will create a resource group, but it will not match any queries.
So the resource limit won't work.

**Comment by nezihyigitbasi** [comment]
You should have selector rules that specifies which queries (by user, source, type, etc.) go into which resource groups. Please see the resource group docs for detailed information: https://prestodb.io/docs/current/admin/resource-groups.html
