### ISSUE TITLE
Planning error when aliasing table colums

### ISSUE THREAD

**Issue by martint** [prestodb/presto#11385]
```sql
SELECT 1
FROM orders AS t (a, b, c, d, e, f, g, h, i)
```

fails with 

```
java.lang.IllegalArgumentException: Number of outputs (10) doesn't match number of fields in scopes tree (9)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:294)
	at com.facebook.presto.sql.planner.RelationPlan.<init>(RelationPlan.java:51)
	at com.facebook.presto.sql.planner.RelationPlanner.visitAliasedRelation(RelationPlanner.java:170)
	at com.facebook.presto.sql.planner.RelationPlanner.visitAliasedRelation(RelationPlanner.java:98)
	at com.facebook.presto.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:262)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:143)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:597)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:98)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:251)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:123)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:590)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:98)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:439)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:190)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:171)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:144)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:139)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:344)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:329)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:285)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by martint** [comment]
This seems to be due to a hidden "row_number" in the table.

**Comment by martint** [comment]
The underlying table has 10 columns (9 visible, 1 hidden), which results in 10 columns in the output mappings from the planned relation. The aliased relation has only 9 total columns. The check when processing `visitAliasedRelation` is trying to verify that the number of columns in the aliased relation's is the same as the underlying table, so it fails.
