### ISSUE TITLE
Environment name with dashes won't work

### ISSUE THREAD

**Issue by synhershko** [prestodb/presto#11403]
Specifying the following in `/etc/presto/node.properties` throws the error shown below on node start.

```
node.environment=bigdata-boutique
```

The error:

```
1) Error: Invalid configuration property node.environment: is malformed (for class io.airlift.node.NodeConfig.environment)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Invalid configuration property node.environment: is malformed (for class io.airlift.node.NodeConfig.environment)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:241)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

I think it's legitimate to expect dashes to work in environment names?

Would you accept a PR for fixing this?

**Comment by synhershko** [comment]
I found this answer by @electrum : https://stackoverflow.com/a/19921351

Underscores would work but still the error message is not clear.

**Comment by findepi** [comment]
> Underscores would work but still the error message is not clear.

You can get a better message by `@Pattern` annotating `NodeConfig.getEnvironment`. Will you make a PR?
