### ISSUE TITLE
changing log.properties to com.facebook.presto=DEBUG reveals stacktrace but everything working

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#11480]
2018-09-14T03:11:57.076Z        WARN    http-worker-172 org.eclipse.jetty.server.HttpChannel    /v1/query
java.lang.RuntimeException: Authentication error
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:71)
        at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:64)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:531)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
        at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: authenticator was not loaded
        at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
        at com.facebook.presto.server.security.PasswordAuthenticatorManager.getAuthenticator(PasswordAuthenticatorManager.java:83)
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:65)
        ... 38 more

maybe something before line https://github.com/prestosql/presto/blob/331/presto-main/src/main/java/io/prestosql/server/PrestoServer.java#L142 runs async in background OR this is something to do with worker nodes pinging the coordinator early in coord startup

**Comment by ddrinka** [comment]
@tooptoop4 I get lots of warnings about authentication errors while Presto is starting up, I guess before it has its key material fully loaded.  It's alarming to me as well to have stack traces flowing in the logs for this anticipated circumstance.

**Comment by hammadzz** [comment]
I am actually seeing this error on trying to connect to Presto via LDAPS. Any ideas of what could cause this? I did try restarting Presto but didn't help.

**Comment by morgans2** [comment]
I have been seeing the same issue and it does present intermittently. We are on version .210, in the process of upgrading to .214. This is actually causing issues in our prod environment where users will occasionally receive a denial, and everything works fine minutes later. Makes monitoring of the service impractical too.
