### ISSUE TITLE
NPE in convex_hull_agg

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11488]
convex_hull_agg fails with `NullPointerException` when input contains geometry collection.

```
java.lang.NullPointerException
	at com.esri.core.geometry.ogc.OGCConcreteGeometryCollection.convexHull(OGCConcreteGeometryCollection.java:447)
	at com.facebook.presto.plugin.geospatial.aggregation.ConvexHullAggregation.combine(ConvexHullAggregation.java:79)
	at com.facebook.presto.$gen.GeometryGeometryConvexHullAggGroupedAccumulator_20180914_201841_108030.addIntermediate(Unknown Source)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder$Aggregator.processPage(InMemoryHashAggregationBuilder.java:421)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$processPage$1(InMemoryHashAggregationBuilder.java:169)
```

CC: @yuyongyang800

**Comment by yuyongyang800** [comment]
I remembered this is an existing bug in the esri-geometry-api V2.2.0. When the input contains GeometryCollection objects, it throws NPE. The following line is where the change takes place:
https://github.com/Esri/geometry-api-java/blob/master/src/main/java/com/esri/core/geometry/ogc/OGCConcreteGeometryCollection.java#L447

I believe this bug is fixed in V2.2.1, which is already released from esri. Do we want to update the pom.xml in presto to leverage V2.2.1?

**Comment by mbasmanova** [comment]
@yuyongyang800 Let's upgrade ESRI and remove the type check from `ST_ConvexHull` function.  Yongyang, would you like to do that?

**Comment by mbasmanova** [comment]
Thanks, @yuyongyang800
