### ISSUE TITLE
presto is unable to fetch rows from an hive table stored as avro (with schema defined in avro.schema.url tblproperty)

### ISSUE THREAD

**Issue by alvespat** [prestodb/presto#11548]
Hello , 
i have the next table defined into hive ( kerberised hadoop cluster) :
 
```
CREATE TABLE `default.avrotable_test_url`(
	 `bu_id` int COMMENT '', 
	  `bu_name` string COMMENT '', 
	  `studio_id` int COMMENT '', 
	  `mcr_bu_code` string COMMENT '', 
	  `date_creation` bigint COMMENT '', 
	  `date_modification` bigint COMMENT '', 
	  `user` int COMMENT '', 
	  `archive` boolean COMMENT '', 
	  `company_code` string COMMENT '')
	ROW FORMAT SERDE 
	  'org.apache.hadoop.hive.serde2.avro.AvroSerDe' 
	STORED AS INPUTFORMAT 
	  'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat' 
	OUTPUTFORMAT 
	  'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'
	LOCATION
	  'hdfs://Dev-hdfs-haas-1/user/hive/warehouse/avrotable_test_url'
	TBLPROPERTIES (
	  'avro.schema.url'='hdfs://Dev-hdfs-haas-1/user/hive/warehouse/avrotable_test_url_schema.asvc')
```

When i execute a  select from this table thru prestocli i get next error  ( it works thru hue) : 
---------------------------------------------------------------------
```
resto> select * from "hive-dev".default.avrotable_test_url;

Query 20180921_112332_00022_kugyr, FAILED, 1 node
http://localhost:8080/query.html?20180921_112332_00022_kugyr
Splits: 17 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 57% active
Per Node: 1.6 parallelism,     0 rows/s,     0B/s
Parallelism: 1.6
Spilled: 0B
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20180921_112332_00022_kugyr failed: cannot find field bu_id from [0:error_error_error_error_error_error_error, 1:cannot_determine_schema, 2:check, 3:schema, 4:url, 5:and, 6:literal]

=========   TECHNICAL DETAILS   =========
[ Error message ]
cannot find field bu_id from [0:error_error_error_error_error_error_error, 1:cannot_determine_schema, 2:check, 3:schema, 4:url, 5:and, 6:literal]

[ Session information ]
ClientSession{server=http://localhost:8080, user=root, clientInfo=null, catalog=null, schema=null, timeZone=Etc/GMT, locale=en_US, properties={}, transactionId=null, debug=true, quiet=false}

[ Stack trace ]
java.lang.RuntimeException: cannot find field bu_id from [0:error_error_error_error_error_error_error, 1:cannot_determine_schema, 2:check, 3:schema, 4:url, 5:and, 6:literal]
        at org.apache.hadoop.hive.serde2.objectinspector.ObjectInspectorUtils.getStandardStructFieldRef(ObjectInspectorUtils.java:416)
        at org.apache.hadoop.hive.serde2.objectinspector.StandardStructObjectInspector.getStructFieldRef(StandardStructObjectInspector.java:147)
        at com.facebook.presto.hive.GenericHiveRecordCursor.<init>(GenericHiveRecordCursor.java:156)
        at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:63)
        at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:157)
        at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:87)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:253)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:416)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:310)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:586)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:734)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
========= TECHNICAL DETAILS END =========
```
----------------------------------------------------------------------
Currently the only workaround i found was to add the schema as litteral  ( avro.schema.litteral). 

But would like to know if did  a mistake somewhere (in my hadoop configuration files/ hive properties) ?

Reading  presto documentation , thus should work : 
"Presto supports querying and manipulating Hive tables with Avro storage format which has the schema set based on an Avro schema file/literal ".

presto VERSION is 0.167-T.0.2

any insights will be appreciate.

Thanks.
Pat

**Comment by findepi** [comment]
@alvespat apparently we currently support `avro.schema.url` being a local file (`file:///some/path`). 
I have hacked a fix, need to polish things up before making a PR.

**Comment by alvespat** [comment]
Thanks @findepi Findepi, 
Let me know  when you'll provide this PR.

**Comment by conrosebraugh** [comment]
I am having a similar issue with a schema file stored on S3. Will this PR cover schema files stored on S3?
