### ISSUE TITLE
Join query failed with IllegalArgumentException: Too large (846115165 expected elements with load factor 0.75)

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#11563]
```
java.lang.IllegalArgumentException: Too large (846115165 expected elements with load factor 0.75)
 at it.unimi.dsi.fastutil.HashCommon.arraySize(HashCommon.java:160)
 at com.facebook.presto.operator.PagesHash.<init>(PagesHash.java:63)
 at com.facebook.presto.operator.JoinHashSupplier.<init>(JoinHashSupplier.java:70)
 at com.facebook.presto.operator.PagesIndex.createLookupSourceSupplier(PagesIndex.java:512)
 at com.facebook.presto.operator.HashBuilderOperator.buildLookupSource(HashBuilderOperator.java:589)
 at com.facebook.presto.operator.HashBuilderOperator.finishInput(HashBuilderOperator.java:486)
 at com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:442)
```

CC: @raghavsethi

**Comment by dain** [comment]
This is an old issue.  The join hash only allows for < 2B elements after the fill factor is expanded.  This can be worked around by increasing the distributed or local parallelism, or we could try again to switch to a segmented array in the join hash... last time the perf hit was too large to justify the change.

**Comment by raghavsethi** [comment]
Ah in that case let's settle for improving the error message/categorization for now.

**Comment by mbasmanova** [comment]
@dain ,

> The join hash only allows for < 2B elements after the fill factor is expanded.

What is `fill factor` here? The error complains about 846M records, not 2B.

**Comment by weimy2018** [comment]
+1 
I run tpcds 10T on 8 worker nodes and 1 condinator with 128GiB memory and 16 cores by Trino-360 version ,meet it again.
Any effective solutions？
