### ISSUE TITLE
Presto writes on S3: File does not exist (Eventual Consistency?)

### ISSUE THREAD

**Issue by cvitello** [prestodb/presto#11587]
Affected Presto Versions: >0.198 (issue existence verified on .205 and .208)
OS: Amazon Linux 2 (2017.12) LTS Release Candidate
Worker Count: 20

Hello All,

We're encountering a sporadic issue with Presto writes against a managed Hive table stored on S3. The input file format for the table is Parquet. The issue is similar to this topic reported in the [presto-users group](https://groups.google.com/d/topic/presto-users/30HkNq0cHfA/discussion).

This is a sample stack trace when the issue occurs:

```
com.facebook.presto.spi.PrestoException: Error committing write to Hive
	at com.facebook.presto.hive.RecordFileWriter.commit(RecordFileWriter.java:183)
	at com.facebook.presto.hive.HiveWriter.commit(HiveWriter.java:86)
	at com.facebook.presto.hive.HivePageSink.doFinish(HivePageSink.java:184)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1726)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at com.facebook.presto.hive.authentication.DirectHdfsAuthentication.doAs(DirectHdfsAuthentication.java:38)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:80)
	at com.facebook.presto.hive.HivePageSink.finish(HivePageSink.java:175)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:65)
	at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:178)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:393)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: File does not exist: s3a://bucket/folder/partition/file
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.getFileStatus(PrestoS3FileSystem.java:316)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:428)
	at com.facebook.presto.hive.ParquetRecordWriterUtil$1.close(ParquetRecordWriterUtil.java:89)
	at com.facebook.presto.hive.RecordFileWriter.commit(RecordFileWriter.java:179)
	... 22 more
```

Looking at the JMX MBeans, the errors look to correspond to increments in the GetMetadataErrors (com.facebook.presto.hive.s3:type=PrestoS3FileSystem,name=hive) attribute.

Based off the user group topic and the stack trace, [RecordFileWriter](https://github.com/prestodb/presto/blob/aa6dbf04a6f016bbe30446fde04e7ef087ea532c/presto-hive/src/main/java/com/facebook/presto/hive/RecordFileWriter.java#L130) and [ParquetRecordWriterUtil](https://github.com/prestodb/presto/blob/2d43bd87607d6ebe704d334780d9c5d8514cc47e/presto-hive/src/main/java/com/facebook/presto/hive/ParquetRecordWriterUtil.java#L89) both make explicit calls to the abstracted file system. In the case of S3, I believe this request would fall under the HEAD/GET category which only has eventual consistency for read-after-write. Running the workload against a custom build with the two getFileStatus calls disabled has not caused these errors to reappear.

Beyond commenting those calls out or moving the tables to HDFS, do have any suggestions on how to workaround this issue? Thanks for your time!

**Comment by nezihyigitbasi** [comment]
> Running the workload against a custom build with the two getFileStatus calls disabled has not caused these errors to reappear.

How confident are you that without these calls the errors disappear? If you have high confidence then we are probably hitting the case documented in the S3 docs (as you suspect): `The caveat is that if you make a HEAD or GET request to the key name (to find if the object exists) before creating the object, Amazon S3 provides eventual consistency for read-after-write.` If that's the case, unfortunately, I cannot think of any other way than disabling those calls when S3 filesystem is used (which will have other side effects though).

**Comment by cvitello** [comment]
Thanks for the quick response, Nezih. I've only been running the workload against the custom build today so not definitively confident, but I plan to continue testing.

> which will have other side effects though

Could you elaborate on this? I'm guessing that at least the statistics would be affected.

**Comment by nezihyigitbasi** [comment]
The commit that added the `getFileStatus` call in `ParquetRecordWriterUtil` says that writer scaling depends on that: https://github.com/prestodb/presto/commit/2d43bd87607d6ebe704d334780d9c5d8514cc47e

**Comment by cvitello** [comment]
Thanks for the information. I'm going to close this out as the issue appears to be with our usage of the write functionality.

**Comment by nezihyigitbasi** [comment]
@cvitello can you please give more details if possible?

**Comment by cvitello** [comment]
After an additional day of testing with the two sections of code commented out, I still didn't run into the issue. However, since we didn't want to pursue that as a long term solution, we're moving forward with relocating the table to HDFS.

**Comment by Hammond95** [comment]
Hi @nezihyigitbasi we are facing the same issue, when performing some inserts that:
* require a big load of resources
* on tables in parquet format
* partitioned

```CREATE EXTERNAL TABLE DEFAULT.MONTHLY_ACTIVE_USERS(
  col_1 string, 
  col_2 string, 
  col_3 bigint, 
  col_4 bigint, 
  col_5 bigint, 
  col_6 bigint
PARTITIONED BY (pcol_1 string, pcol_2 bigint,  pcol_3 string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://location/on/s3/'```

Presto 0.206, release from AWS on EMR.

This problem just occurs randomly, after performing the insert a couple of times it just works without giving the error anymore.

Do you know if this has been fixed in a next release?

**Comment by nezihyigitbasi** [comment]
I don't think we have fixed this issue in one of the latest releases. If you or anyone wants to fix this issue, the HEAD/GET requests that are sent & cause eventual consistency may be in multiple places (e.g., in Parquet writer code path and in PrestoS3FileSystem as pointed out in https://github.com/prestosql/presto/issues/103).

**Comment by electrum** [comment]
I'm confused about how the Parquet HEAD request *after* the write is completed causes a problem. I thought the issue is doing the HEAD request to check for existence *before* the object exists. Is this because we are making a request before creation which then causes the one after creation to fail? In other words, if we skip the before creation check, the one after the write would not be a problem?

**Comment by nezihyigitbasi** [comment]
Isn't the HEAD/GET for Parquet before write? If not, it is not a problem, because this issue is due to sending HEAD/GET requests before creating the S3 object.

**Comment by Hammond95** [comment]
I've updated my comment above, maybe it is clearer now, and will not led to confusion.
