### ISSUE TITLE
presto not able to access jars in class path 

### ISSUE THREAD

**Issue by nakhanha** [prestodb/presto#11656]
I want to add ADL file system support to presto.

I have copied all the relavant jars to the path mentioned below.
root@wn1-nkhadl:/mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538879153772_0002/container_1538879153772_0002_01_000002/app/install/presto-server-0.208/lib# ls -latr adl*
-rw-r--r-- 1 yarn hadoop 37618 Oct 7 02:01 adls2-oauth2-token-provider.jar

yarn 12168 5.2 2.8 27231744 824088 ? Sl 02:44 3:57 java -cp /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538879153772_0002/container_1538879153772_0002_01_000002/app/install/presto-server-0.208/lib/* -server -Xmx23G -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -Dnode.data-dir=/var/lib/presto/data -Dnode.id=ed55b10e-c9da-11e8-bc16-000d3a913d9d -Dnode.environment=test -Dlog.levels-file=/var/lib/presto/etc/log.properties -Dplugin.config-dir=/var/lib/presto/etc/catalog -Dconfig=/var/lib/presto/etc/config.properties com.facebook.presto.server.PrestoServer

_0002_01_000002/app/install/presto-server-0.208/lib# jar tvf adls2-oauth2-token-provider.jar | grep HdiAdl
1303 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdl.class
9950 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdlFileSystem.class

when i submit the query
presto:default> create table txtn(txn1 INT);
Query 20181007_035559_00014_bg56u failed: Could not initialize class org.apache.hadoop.fs.adl.HdiAdlFileSystem

presto:default>

server.logs on cordinator show.
2018-10-07T02:50:27.202Z INFO query-scheduler-3 stderr java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.fs.adl.HdiAdlFileSystem

I have also added jars to hive-hadoop2 connector classpath. 

I still face the classdefnotfound error.
is there something i am missing. please guide.

**Comment by nakhanha** [comment]
@dain any inputs

**Comment by dain** [comment]
Connectors are only exposed to Java packages included in the SPI (e.g., Presto SPI, jackson, etc), and everything else is hidden.  This lets connectors use libraries that are incompatible with the Presto server.  Instead of adding the jars to the system class path, they need to be bundled with the connector.

As, I mentioned before, instead of trying to hack in support for the ADL filesystem, it will be easier to get this added to the standard Presto distribution.  I suggest you start by creating an issue for that.

**Comment by nakhanha** [comment]
Thanks for your reply @dain 
I tried adding to connector classpath as well.


yarn **14314** 9.1 2.7 27222468 802492 ? Sl 03:27 1:25 java -cp /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/container_1538967442733_0003_01_000003/app/install/presto-server-0.208/lib/* -server -Xmx23G -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError=kill -9 %p -Dcatalog.config-dir=/var/lib/presto/etc/catalog -Dnode.data-dir=/var/lib/presto/data -Dnode.id=266589cc-caaa-11e8-a432-000d3a3eac46 -Dnode.environment=test -Dlog.levels-file=/var/lib/presto/etc/log.properties -Dconfig=/var/lib/presto/etc/config.properties com.facebook.presto.server.PrestoServer

sshuser@wn1-nkhiap:~$ sudo lsof -p 14314 | grep 'jar' | grep 'adls2-oauth' presto-se 14314 yarn mem REG 8,17 37618 20448422 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/container_1538967442733_0003_01_000003/app/install/presto-server-0.208/plugin/**hive-hadoop2**/adls2-oauth2-token-provider.jar

and

sshuser@wn1-nkhiap:~$ sudo jar tvf /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1538967442733_0003/conta iner_1538967442733_0003_01_000003/app/install/presto-server-0.208/plugin/hive-hadoop2/adls2-oauth2-token-provider.jar | grep 'H diAdl'
1303 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdl.class
9950 Sat Sep 08 09:42:48 UTC 2018 org/apache/hadoop/fs/adl/HdiAdlFileSystem.class
sshuser@wn1-nkhiap:~$

**Comment by dain** [comment]
I'm not sure I followed that, but from the `lsof` command it looks like the Presto process did open the jar.  There are a bunch of things that could be going wrong here.  For example, the Presto Hive integration strips a bunch of APIs from Hive and repackages stuff to make the integration easier and more reliable.  We don't really recommend or support people "throwing jars" in the connector directories.  It could work for a small time, but in the long run you will run into compatibility issues (and possibly bad query results), which is why I suggest working to get a supported integration.

**Comment by nakhanha** [comment]
which team is responsible for this integration ?

**Comment by nakhanha** [comment]
I am totally confused as why though it opens up jars , server.log says Classnotfound.

**Comment by nakhanha** [comment]
Not Just ADL jars.

few other jars , which are also 
2018-10-08T20:36:10.919Z        ERROR   hive-hive-0     com.hadoop.compression.lzo.LzoCodec     Cannot load native-lzo without native-hadoop
2018-10-08T20:36:11.156Z        WARN    hive-hive-0     com.facebook.presto.hive.util.ResumableTasks    ResumableTask completed exceptionally
java.lang.NoSuchMethodError: org.apache.hadoop.conf.Configuration.reloadExistingConfigurations()V
        at org.apache.hadoop.fs.adl.AdlConfKeys.addDeprecatedKeys(AdlConfKeys.java:114)
        at org.apache.hadoop.fs.adl.AdlFileSystem.<clinit>(AdlFileSystem.java:91)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.hadoop.conf.Configuration.getClassByNameOrNull(Configuration.java:2134)
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2099)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2654)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:99)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:73)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:50)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:282)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:256)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:91)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:185)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
        at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
        at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

sshuser@wn3-nkhadl:/var/lib/presto/data/var/log$ sudo lsof -p 14484 | grep "jar" | grep "lzo"
presto-se 14484 yarn  mem       REG               8,17    71867 13632469 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1539028731470_0002/container_1539028731470_0002_01_000002/app/install/presto-server-0.208/plugin/hive-hadoop2/hadoop-lzo-0.6.0.2.6.5.3003-25.jar
presto-se 14484 yarn  mem       REG               8,17    49844 13632420 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1539028731470_0002/container_1539028731470_0002_01_000002/app/install/presto-server-0.208/plugin/hive-hadoop2/hadoop-lzo-0.6.0.2.6.5.3003-25-sources.jar
presto-se 14484 yarn  mem       REG               8,17   179470 13632477 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1539028731470_0002/container_1539028731470_0002_01_000002/app/install/presto-server-0.208/plugin/hive-hadoop2/hadoop-lzo-0.6.0.2.6.5.3003-25-javadoc.jar
presto-se 14484 yarn  495r      REG               8,17   179470 13632477 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1539028731470_0002/container_1539028731470_0002_01_000002/app/install/presto-server-0.208/plugin/hive-hadoop2/hadoop-lzo-0.6.0.2.6.5.3003-25-javadoc.jar
presto-se 14484 yarn  496r      REG               8,17    49844 13632420 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1539028731470_0002/container_1539028731470_0002_01_000002/app/install/presto-server-0.208/plugin/hive-hadoop2/hadoop-lzo-0.6.0.2.6.5.3003-25-sources.jar
presto-se 14484 yarn  497r      REG               8,17    71867 13632469 /mnt/resource/hadoop/yarn/local/usercache/root/appcache/application_1539028731470_0002/container_1539028731470_0002_01_000002/app/install/presto-server-0.208/plugin/hive-hadoop2/hadoop-lzo-0.6.0.2.6.5.3003-25.jar
sshuser@wn3-nkhadl:/var/lib/presto/data/var/log$

**Comment by dain** [comment]
> which team is responsible for this integration?

File the issue with the main Presto project.

> Not Just ADL jars.... few other jars , which are also

As I mentioned, Presto is not designed for this type of modification.  It may work, it may not.

**Comment by nakhanha** [comment]
@kokosing @dain  you think this would be helpful 

**site.global.plugin (optional)** (default - None): This allows you to add any additional jars you want to copy to plugin presto-server-<version>/plugin/<connector> directory in addition to what is already available there. It should be of the format {‘connector1’ : [‘jar1’, ‘jar2’..], ‘connector2’ : [‘jar3’, ‘jar4’..]..}. This will copy jar1, jar2 to Presto plugin directory at plugin/connector1 directory and jar3, jar4 at plugin/connector2 directory. Make sure you have the plugin jars you want to add to Presto available at presto-yarn-package/src/main/slider/package/plugins/ prior to building the presto-yarn app package and thus the app package built presto-yarn-package-<version>-<presto-version>.zip will have the jars under package/plugins directory.

**Comment by dain** [comment]
Presto is not designed to support this kind of class path hacking, and instead we want features built in and tested within Presto.  That way when people have problems with them we can provide support.
