### ISSUE TITLE
EMRFS Downloads Fail When Called in Quick Succession on a Worker Node

### ISSUE THREAD

**Issue by ddrinka** [prestodb/presto#11662]
I'm running Presto 0.206 on EMR 5.17.0, and it appears this is an EMRFS issue, not a Presto issue.  I have raised a support ticket with AWS.  Is it still appropriate to document it here?

I'm working with bucketed sorted tables which utilize sort files which, upon insert, are written to a temporary location adjacent to the table's output location.  My table is located in S3 so the temporary files are as well.

Uploading the sort files works fine.  However, when the time comes to pull them back down, there is an issue.  If the node doing the work is the master, the process succeeds.  If the node is a worker, the download process fails at the 49th file every execution.

I've adjusted the size of the sort files by changing the buffer size, but regardless of the size of the S3 key, the download breaks at file 49.

Here's the exception:
```
com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1270)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.call.GetObjectMetadataCall.perform(GetObjectMetadataCall.java:22)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.call.GetObjectMetadataCall.perform(GetObjectMetadataCall.java:8)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.executor.GlobalS3Executor.execute(GlobalS3Executor.java:91)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.AmazonS3LiteClient.invoke(AmazonS3LiteClient.java:184)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.AmazonS3LiteClient.getObjectMetadata(AmazonS3LiteClient.java:96)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.AbstractAmazonS3Lite.getObjectMetadata(AbstractAmazonS3Lite.java:38)
        at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.retrieveMetadata(Jets3tNativeFileSystemStore.java:214)
        at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem.getFileStatus(S3NativeFileSystem.java:755)
        at com.amazon.ws.emr.hadoop.fs.EmrFileSystem.getFileStatus(EmrFileSystem.java:536)
        at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:452)
        at com.facebook.presto.hive.SortingFileWriter.writeSorted(SortingFileWriter.java:185)
        at com.facebook.presto.hive.SortingFileWriter.commit(SortingFileWriter.java:127)
        at com.facebook.presto.hive.HiveWriter.commit(HiveWriter.java:86)
        at com.facebook.presto.hive.HivePageSink.doFinish(HivePageSink.java:184)
        at com.facebook.presto.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:360)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1820)
        at com.facebook.presto.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
        at com.facebook.presto.hive.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:39)
        at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:80)
        at com.facebook.presto.hive.HivePageSink.finish(HivePageSink.java:175)
        at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:65)
        at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:156)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:393)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:286)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
        at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.conn.$Proxy200.get(Unknown Source)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1238)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
        ... 43 more
```

**Comment by findepi** [comment]
@ddrinka thanks for reporting this. I don't know the answer, but hopefully someone will help you here.
The inconvenient part is that `com.amazon.ws.emr.hadoop.fs.EmrFileSystem` is not part of Presto code base. Did you try to get AWS support help first?

**Comment by ddrinka** [comment]
@findepi Thanks for your response.

I have a ticket open with AWS as well.  I'm attempting to replicate the configuration using s3a:// rather than EMRFS.  I'll update when I have the results of that.

**Comment by ddrinka** [comment]
It appears that even when the table location is defined as s3a://, EMRFS is still utilized for the sort files.

`2018-10-08T23:26:55.918Z        INFO    20181008_232352_00039_hbtat.1.0-16-472  com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem      Opening 's3a://bucket/tmp/presto-ec2-user/guid/date=2018-09-28/.tmp-sort.20181008_232352_00039_hbtat_bucket-00000.49' for reading`

**Comment by ddrinka** [comment]
I've set `hive.s3-file-system-type = PRESTO` which seems to start using Presto's S3 client.

However, diagnosing if the issue still occurs has been difficult as I can't seem to get debug logging turned on in EMR.  Setting `com.facebook.presto=DEBUG` in `log.properties` appears to do nothing.

Sorry I'm such a noob.  What I really want to see is `
com.facebook.presto.hive.s3.PrestoS3FileSystem` debug messages.  Can I get a little help getting that enabled?

**Comment by ddrinka** [comment]
From AWS Support, the exception shown here is thrown when the S3 connection pool is exhausted.  The root cause of the odd circumstances is that, out of the box, a default of 500 connections is configured on the master node, but the parameter is not set at all on the worker nodes.  It appears the value defaults to 50 if left unconfigured, which is why files 0-49 completed successfully.

Support recommended setting the following to avoid the issue:
```json
[
  {
    "Classification": "emrfs-site",
    "Properties": {
       "fs.s3.maxConnections": "3000"
    }
  }
]
```

**Comment by dain** [comment]
Can we change the defaults programmatically in Presto so no one needs to set this?

**Comment by mnoumanshahzad** [comment]
> Can we change the defaults programmatically in Presto so no one needs to set this?

This is an 'emrfs-site' configuration and not a direct Presto configuration. This can be set when deploying an EMR cluster by setting the configurations as follows

```
"Classification": "emrfs-site"
"Properties": {
      "fs.s3.maxConnections" : "3000"
}
```

**Comment by ddrinka** [comment]
AWS has this on their radar now.  I mentioned I thought it was a bug and they agreed.  Should make it into a future release.

**Comment by electrum** [comment]
I think we can set this in `EmrFsS3ConfigurationUpdater`, but no need if AWS is going to make it default. Let's close for now.
