### ISSUE TITLE
Spilling to disk fails when there are bad disks

### ISSUE THREAD

**Issue by thoralf-gutierrez** [prestodb/presto#11696]
Hello everybody,

We're using Presto 0.211 with spilling to disk enabled and noticed queries failing when one disk went bad, with the following error:
```
com.facebook.presto.spi.PrestoException: Failed to create spill file
	at com.facebook.presto.spiller.FileSingleStreamSpiller.<init>(FileSingleStreamSpiller.java:100)
	at com.facebook.presto.spiller.FileSingleStreamSpillerFactory.create(FileSingleStreamSpillerFactory.java:143)
	at com.facebook.presto.spiller.GenericSpiller.spill(GenericSpiller.java:63)
	at com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder.spillToDisk(SpillableHashAggregationBuilder.java:222)
	at com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder.startMemoryRevoke(SpillableHashAggregationBuilder.java:158)
	at com.facebook.presto.operator.HashAggregationOperator.startMemoryRevoke(HashAggregationOperator.java:413)
	at com.facebook.presto.operator.Driver.handleMemoryRevoke(Driver.java:478)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:351)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1053)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.FileSystemException: /volumes/data03/presto/spill/spill2914747411759358463.bin: Read-only file system
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at java.nio.file.TempFileHelper.create(TempFileHelper.java:138)
	at java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:161)
	at java.nio.file.Files.createTempFile(Files.java:852)
	at com.facebook.presto.spiller.FileSingleStreamSpiller.<init>(FileSingleStreamSpiller.java:97)
	... 16 more
```

(The bad disk was confirmed when inspecting `dmesg`)

Could we get the workers to avoid spilling to bad disks when it catches these types of errors? This is something I could help with if you think it makes sense.

**Comment by kokosing** [comment]
In general Presto is not fault-tolerant yet. I do not think that fixing this special case is needed while the more general problems related to fault tolerance are not yet touched.

**Comment by electrum** [comment]
@kokosing I'm not sure I agree. We already support multiple spill paths and handle out of disk space. This seems like a reasonable case to handle by blacklisting any disks that fail with `FileSystemException`. Though this might turn out to be more difficult in practice, since failures can manifest in many ways, so maybe it's better to ask the user to use a volume manager which is more suited to handling this transparently.
