### ISSUE TITLE
Java JDBC hang for a long time after query has already failed

### ISSUE THREAD

**Issue by VicoWu** [prestodb/presto#11711]
I am now using presto 0.212 , but I am not sure if this problem is only introduced in new version presto or a common problem:
I am using JDBC connecting to presto, then, these cases happened very often when my query failed because of worker node instability:

When I get the error at 08:00:
```
 java.sql.SQLException: Query failed (#20181013_134239_00010_k7ym8): Error fetching http://10.88.193.36:8087/v1/task/20181013_134239_00010_k7ym8.4.14/results/19/0: Expected response code to be 200, but was 500 Internal Server Error:
```
But in fact the query's failed time is 07:50, namely, this query has already failed for 10 minutes.
So, why this happened ?

I catch the java JDBC client stack trace during the  interval that the query has already failed in presto server side and but my JDBC client haven't get any response:

```
"pool-1-thread-1" #9 prio=5 os_prio=0 tid=0x00007fae24222000 nid=0x3865 waiting on condition [0x00007fadfe39b000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000718907890> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
        at com.facebook.presto.jdbc.internal.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:224)
        at com.facebook.presto.jdbc.internal.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:314)
        at com.facebook.presto.jdbc.internal.client.StatementClient.advance(StatementClient.java:240)
        at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1784)
        at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1764)
        at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
        at com.facebook.presto.jdbc.internal.guava.collect.Iterators$5.hasNext(Iterators.java:547)
        at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:162)
        at com.hulu.metrics.presto.comparator.SimulateProduction$LaunchQuery.runQuery(SimulateProduction.java:159)
        at com.hulu.metrics.presto.comparator.SimulateProduction$LaunchQuery.run(SimulateProduction.java:140)

```
you could see that the JDBC client is hanging in get the query result, but in fact the query has failed for several minutes!
Does anyone ever met this phenomenon and know the reason?

**Comment by dain** [comment]
My guess is the client can not talk to the server anymore.  If the client does not check in with the server periodically, the server will assume the client crashed and fail the query as abandoned.  I'm not sure what happens on the client side, but from the stack, it looks like the client is trying to establish a connection to the server, and is waiting.  It is possible that the timeouts are not set or really large on the client which would explain why it is taking 10 minutes.

**Comment by electrum** [comment]
The JDBC driver should handle timeouts appropriately, even if there is a network error between the coordinator and client. However, based on the stack trace, it appears the JDBC driver you are using is more than a year old. Can you try with the latest driver and post a new stack trace if the problem happens again?
