### ISSUE TITLE
hive connector encounter  an UnknownHostException issue 

### ISSUE THREAD

**Issue by wgzhao** [prestodb/presto#11750]
I have 24-nodes Presto Cluster, the version is 0.208.  The Hadoop enable Kerberos auth.
So, my hive connector properties like the following:

```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://hadoop3.fzzq.com:9083,thrift://hadoop4.fzzq.com:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.metastore.authentication.type=KERBEROS
hive.metastore.service.principal=hive/_HOST@FZZQ.COM
hive.metastore.client.principal=presto@FZZQ.COM
hive.metastore.client.keytab=/etc/presto/presto.keytab
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.presto.principal=presto@FZZQ.COM
hive.hdfs.presto.keytab=/etc/presto/presto.keytab
hive.allow-drop-table=true
hive.recursive-directories=true
hive.orc.bloom-filters.enabled=true
```
All FQDN hostnames are listed in `/etc/hosts` file, like here:

```
192.209.1xx.xxx	hadoop1.fzzq.com	hadoop1
192.209.1xx.xxx	hadoop2.fzzq.com	hadoop2
192.209.1xx.xxx	hadoop3.fzzq.com	hadoop3
192.209.1xx.xxx	hadoop4.fzzq.com	hadoop4
192.209.1xx.xxx	hadoop5.fzzq.com	hadoop5
192.209.1xx.xxx	hadoop6.fzzq.com	hadoop6
192.209.1xx.xxx	hadoop7.fzzq.com	hadoop7
192.209.1xx.xxx	hadoop8.fzzq.com	hadoop8
192.209.1xx.xxx	hadoop9.fzzq.com	hadoop9
192.209.1xx.xxx	hadoop10.fzzq.com	hadoop10
192.209.1xx.xxx	hadoop11.fzzq.com	hadoop11
192.209.1xx.xxx	hadoop12.fzzq.com	hadoop12
192.209.1xx.xxx	hadoop13.fzzq.com	hadoop13
192.209.1xx.xxx	hadoop14.fzzq.com	hadoop14
192.209.1xx.xxx	hadoop15.fzzq.com	hadoop15
192.209.1xx.xxx	hadoop16.fzzq.com	hadoop16
192.209.1xx.xxx	hadoop17.fzzq.com	hadoop17
192.209.1xx.xxx	hadoop18.fzzq.com	hadoop18
192.209.1xx.xxx	hadoop19.fzzq.com	hadoop19
192.209.1xx.xxx	hadoop20.fzzq.com	hadoop20
192.209.1xx.xxx	hadoop21.fzzq.com	hadoop21
192.209.1xx.xxx	hadoop22.fzzq.com	hadoop22
192.209.1xx.xxx	hadoop23.fzzq.com	hadoop23
192.209.1xx.xxx	hadoop24.fzzq.com	hadoop24
```
(I hidden real ip addresses for security)

Hadoop Cluster using Hortonworks HDP 2.5.0 version, and hive service has two hive-metastore servers (hadoop3.fzzq.com and hadoop4.fzzq.com)

sometimes, the presto coordinate server occurs the following  error:

```
2018-10-20T02:05:50.903+0800	ERROR	remote-task-callback-27229	com.facebook.presto.execution.StageStateMachine	Stage 20181019_180549_01742_gy7pj.1 failed
com.facebook.presto.spi.PrestoException: Failed connecting to Hive metastore: [hadoop3.fzzq.com:9083, hadoop4.fzzq.com:9083]
	at com.facebook.presto.hive.metastore.thrift.StaticHiveCluster.createMetastoreClient(StaticHiveCluster.java:86)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$getPartition$38(ThriftHiveMetastore.java:842)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:137)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getPartition(ThriftHiveMetastore.java:841)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getPartition(BridgingHiveMetastore.java:248)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadPartitionByName(CachingHiveMetastore.java:561)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.access$300(CachingHiveMetastore.java:71)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore$3.load(CachingHiveMetastore.java:177)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore$3.load(CachingHiveMetastore.java:173)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:214)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getPartition(CachingHiveMetastore.java:518)
	at com.facebook.presto.hive.metastore.HivePageSinkMetadataProvider.getPartition(HivePageSinkMetadataProvider.java:54)
	at com.facebook.presto.hive.HiveWriterFactory.createWriter(HiveWriterFactory.java:284)
	at com.facebook.presto.hive.HivePageSink.getWriterIndexes(HivePageSink.java:341)
	at com.facebook.presto.hive.HivePageSink.writePage(HivePageSink.java:266)
	at com.facebook.presto.hive.HivePageSink.doAppend(HivePageSink.java:261)
	at com.facebook.presto.hive.HivePageSink.lambda$appendPage$2(HivePageSink.java:247)
	at com.facebook.presto.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1726)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at com.facebook.presto.hive.authentication.DirectHdfsAuthentication.doAs(DirectHdfsAuthentication.java:38)
	at com.facebook.presto.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:85)
	at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:247)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:57)
	at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:219)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:282)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:973)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.thrift.transport.TTransportException: hadoop4.fzzq.com:9083: java.net.UnknownHostException: hadoop4.fzzq.com
	at com.facebook.presto.hive.metastore.thrift.Transport.rewriteException(Transport.java:91)
	at com.facebook.presto.hive.metastore.thrift.Transport.create(Transport.java:51)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreClientFactory.create(HiveMetastoreClientFactory.java:58)
	at com.facebook.presto.hive.metastore.thrift.StaticHiveCluster.createMetastoreClient(StaticHiveCluster.java:75)
	... 48 more
Caused by: java.net.UnknownHostException: hadoop4.fzzq.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:589)
	at com.facebook.presto.hive.metastore.thrift.Transport.createRaw(Transport.java:66)
	at com.facebook.presto.hive.metastore.thrift.Transport.create(Transport.java:43)
	... 50 more
```
I try to turn debug log level ,but can not find more useful info.

**Comment by findepi** [comment]
Hopefully you've fixed the problem by now. If not, I would look into the root cause:
```
UnknownHostException: hadoop4.fzzq.com
```

**Comment by wgzhao** [comment]
I have fixed the problem ,the root cause is  MIT KDC's overhead.
So, I increase the MIT KDC threads . It works.
