### ISSUE TITLE
can't start prestodb server over https with a custom password authenticator

### ISSUE THREAD

**Issue by dinal** [prestodb/presto#11806]
Hi,
I'm using presto 0.206 and trying to config it to run over https with a password authenticator that i wrote.

I get the following error -

```
2018-10-29T16:24:45.974+0200    INFO    main    com.facebook.presto.server.security.PasswordAuthenticatorManager    -- Loading password authenticator --
2018-10-29T16:24:45.976+0200    INFO    main    Bootstrap   PROPERTY  DEFAULT  RUNTIME  DESCRIPTION
2018-10-29T16:24:45.980+0200    INFO    main    com.facebook.presto.server.security.PasswordAuthenticatorManager    -- Loaded password authenticator v3io --
2018-10-29T16:24:45.989+0200    INFO    main    com.facebook.presto.server.PrestoServer ======== SERVER STARTED ========
2018-10-29T16:24:45.989+0200    ERROR   Announcer-0 io.airlift.discovery.client.Announcer   Cannot connect to discovery server for announce: Announcement failed for https://192.168.224.157:8889
2018-10-29T16:24:45.990+0200    ERROR   Announcer-0 io.airlift.discovery.client.Announcer   Service announcement failed after 9.44ms. Next request will happen within 0.00s
looks like my plugin ("v3io") is loaded successfully but something is wrong with the https config

```
config.properties -

coordinator=true
node-scheduler.include-coordinator=true
http-server.https.port=8889
query.max-memory=5GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=https://192.168.224.157:8889
node.internal-address=192.168.224.157
http-server.https.keystore.path=/opt/presto-server-0.206/keystore.jks
http-server.https.keystore.key=password
http-server.authentication.type=PASSWORD

**Comment by Praveen2112** [comment]
For enabling https server we should also add this configuration property 
`http-server.https.enabled=true`

**Comment by dinal** [comment]
@Praveen2112 
if i'm not setting discovery.uri to use https then cli won't allow using user+password (i want to authenticate the user in the password authenticator i added)

I get this error when starting cli with password flag - 
```
Exception in thread "main" java.lang.IllegalArgumentException: Authentication using username/password requires HTTPS to be enabled
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.facebook.presto.cli.QueryRunner.setupBasicAuth(QueryRunner.java:146)
	at com.facebook.presto.cli.QueryRunner.<init>(QueryRunner.java:79)
	at com.facebook.presto.cli.Console.run(Console.java:138)
	at com.facebook.presto.cli.Presto.main(Presto.java:31)
```

**Comment by Praveen2112** [comment]
@dinal 
You have to use https in the presto-server uri if you need user + password, you will be using https in the `discovery.uri` only if you require a secure internal connection. AFAIK for a normal custom password authenticator, coordinator should have both http port (for discovering the worker nodes) and https port (for password based authentication). So this config properties should ideally work for you

coordinator=true
node-scheduler.include-coordinator=true
http-server.https.port=8889
http-server.https.enabled=true
http-server.http.port=8080
query.max-memory=5GB
query.max-memory-per-node=1GB
discovery-server.enabled=true
discovery.uri=http://192.168.224.157:8080
node.internal-address=192.168.224.157
http-server.https.keystore.path=/opt/presto-server-0.206/keystore.jks
http-server.https.keystore.key=password

./presto --server https://192.168.224.157:8889 (and your other username and password)

**Comment by dinal** [comment]
that works! thanks!
my confusion was that i thought discovery.uri should be the same as the config passed to --server in cli

**Comment by bb786112** [comment]
Hi,

I am also working with the username & password and also enabled Https & created .jks file. But I am getting the below error.

Error running command: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: s
un.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target


Could you please tell me how to create the username & password for Presto

Thanks

**Comment by pdpark** [comment]
I'm getting the same error. Were you able to resolve?

**Comment by sohamjadiya1cz** [comment]
> Hi,
> 
> I am also working with the username & password and also enabled Https & created .jks file. But I am getting the below error.
> 
> Error running command: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: s
> un.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 
> Could you please tell me how to create the username & password for Presto
> 
> Thanks

Hello I am also facing same problem, can anyone help us with it?

**Comment by sinisdevan** [comment]
Hi I am also working with username and password. after authentication while querying presto db with "show catalogs;" I am getting below error "Error running command: java.net.ConnectException: Failed to connect to /127.0.0.1:8443". can anyone help me with the rot cause and solution
