### ISSUE TITLE
Not able to query hive tables from Presto

### ISSUE THREAD

**Issue by SivaSamrajS** [prestodb/presto#11877]
I have started the Presto server and thrift server is running on localhsot/127.0.0.1:9083. Presto Server is started succesfully. 

While querying the tables from presto-cli, getting the Readtimeout error. This is my hive.properties.

`2018-11-08T16:23:36.833+0530	INFO	query-execution-0	com.facebook.presto.event.QueryMonitor	TIMELINE: Query 20181108_105332_00000_tbfg4 :: Transaction:[6d19f6df-8706-43d3-ba5d-d2ac2d7fd011] :: elapsed 3472ms :: planning 1051ms :: scheduling 2127ms :: running 144ms :: finishing 150ms :: begin 2018-11-08T16:23:33.093+05:30 :: end 2018-11-08T16:23:36.565+05:30
2018-11-08T16:23:37.178+0530	DEBUG	query-execution-0	com.facebook.presto.execution.QueryStateMachine	Query 20181108_105337_00002_tbfg4 is PLANNING
2018-11-08T16:23:46.950+0530	DEBUG	Query-20181108_105336_00001_tbfg4-166	com.facebook.presto.hive.RetryDriver	Failed on executing getAllViews with attempt 1, will retry. Exception: 127.0.0.1:9083: java.net.SocketTimeoutException: Read timed out
2018-11-08T16:23:57.966+0530	DEBUG	Query-20181108_105336_00001_tbfg4-166	com.facebook.presto.hive.RetryDriver	Failed on executing getAllViews with attempt 2, will retry. Exception: 127.0.0.1:9083: java.net.SocketTimeoutException: Read timed out
2018-11-08T16:24:09.053+0530	DEBUG	query-execution-0	com.facebook.presto.execution.QueryStateMachine	Query 20181108_105337_00002_tbfg4 is FAILED
2018-11-08T16:24:09.053+0530	DEBUG	query-execution-2	com.facebook.presto.execution.QueryStateMachine	Query 20181108_105336_00001_tbfg4 is FAILED
2018-11-08T16:24:09.053+0530	DEBUG	Query-20181108_105336_00001_tbfg4-166	com.facebook.presto.execution.QueryStateMachine	Query 20181108_105336_00001_tbfg4 failed
com.facebook.presto.spi.PrestoException: 127.0.0.1:9083: java.net.SocketTimeoutException: Read timed out
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getAllViews(ThriftHiveMetastore.java:579)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getAllViews(BridgingHiveMetastore.java:128)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadAllViews(CachingHiveMetastore.java:369)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:214)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getAllViews(CachingHiveMetastore.java:364)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadAllViews(CachingHiveMetastore.java:369)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:214)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getAllViews(CachingHiveMetastore.java:364)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getAllViews(SemiTransactionalHiveMetastore.java:280)
	at com.facebook.presto.hive.HiveMetadata.listViews(HiveMetadata.java:1379)
	at com.facebook.presto.spi.connector.ConnectorMetadata.listViews(ConnectorMetadata.java:386)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.listViews(ClassLoaderSafeConnectorMetadata.java:345)
	at com.facebook.presto.metadata.MetadataManager.listViews(MetadataManager.java:753)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.lambda$calculatePrefixesWithTableName$7(InformationSchemaMetadata.java:288)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.calculatePrefixesWithTableName(InformationSchemaMetadata.java:291)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.getTableLayouts(InformationSchemaMetadata.java:225)
	at com.facebook.presto.metadata.MetadataManager.getLayouts(MetadataManager.java:357)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.listTableLayouts(PickTableLayout.java:291)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.planTableScan(PickTableLayout.java:230)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.access$200(PickTableLayout.java:79)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutForPredicate.apply(PickTableLayout.java:146)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutForPredicate.apply(PickTableLayout.java:110)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:166)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:139)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:104)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:95)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:163)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:152)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:397)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:382)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:326)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: 127.0.0.1:9083: java.net.SocketTimeoutException: Read timed out
	at com.facebook.presto.hive.metastore.thrift.Transport.rewriteException(Transport.java:91)
	at com.facebook.presto.hive.metastore.thrift.Transport.access$000(Transport.java:32)
	at com.facebook.presto.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:168)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:362)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:284)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:191)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_names_by_filter(ThriftHiveMetastore.java:1282)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_names_by_filter(ThriftHiveMetastore.java:1267)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastoreClient.getTableNamesByFilter(ThriftHiveMetastoreClient.java:92)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllViews$28(ThriftHiveMetastore.java:571)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:139)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getAllViews(ThriftHiveMetastore.java:568)
	... 65 more
	Suppressed: org.apache.thrift.transport.TTransportException: 127.0.0.1:9083: java.net.SocketTimeoutException: Read timed out
		... 79 more
	Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
		at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
		at com.facebook.presto.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:165)
		... 76 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
		at java.net.SocketInputStream.read(SocketInputStream.java:171)
		at java.net.SocketInputStream.read(SocketInputStream.java:141)
		at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
		... 78 more
	Suppressed: org.apache.thrift.transport.TTransportException: 127.0.0.1:9083: java.net.SocketTimeoutException: Read timed out
		... 79 more
	Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
		at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
		at com.facebook.presto.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:165)
		... 76 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.net.SocketInputStream.socketRead0(Native Method)
		at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
		at java.net.SocketInputStream.read(SocketInputStream.java:171)
		at java.net.SocketInputStream.read(SocketInputStream.java:141)
		at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
		at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
		at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
		at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
		... 78 more
Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketTimeoutException: Read timed out
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
	at com.facebook.presto.hive.metastore.thrift.Transport$TTransportWrapper.readAll(Transport.java:165)
	... 76 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
	... 78 more
`

my Hive.properties:

`connector.name=hive-hadoop2
  hive.metastore.uri = thrift://127.0.0.1:9083
  hive.config.resources=/opt/hadoop/etc/hadoop/core-site.xml,/opt/hadoop/etc/hadoop/hdfs-site.xml`

Tried increasing the timeout to 1m, still getting the same issue. 

Hive Metastore log `2018-11-08T16:23:48,016 WARN [pool-8-thread-30] org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.metastore.local does not exist
2018-11-08T16:23:48,017 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
2018-11-08T16:23:49,044 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:50,023 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:51,051 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:52,031 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:53,060 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:54,039 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:55,066 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:56,046 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:57,073 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:57,076 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: Cleaning up thread local RawStore...
2018-11-08T16:23:57,077 INFO [pool-8-thread-27] org.apache.hadoop.hive.metastore.HiveMetaStore - 27: Done cleaning up thread local RawStore
2018-11-08T16:23:58,052 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:59,041 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:23:59,118 WARN [pool-8-thread-31] org.apache.hadoop.hive.conf.HiveConf - HiveConf of name hive.metastore.local does not exist
2018-11-08T16:23:59,119 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
2018-11-08T16:24:00,057 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:01,134 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:02,065 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:03,141 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:04,071 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:05,146 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:06,077 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:07,150 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:08,083 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:08,086 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: Cleaning up thread local RawStore...
2018-11-08T16:24:08,086 INFO [pool-8-thread-30] org.apache.hadoop.hive.metastore.HiveMetaStore - 30: Done cleaning up thread local RawStore
2018-11-08T16:24:09,155 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:11,160 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:13,168 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:15,177 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:17,184 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:19,191 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: source:127.0.0.1 get_table_names_by_filter: db = default, filter = hive_filter_field_params__presto_view = "true"
2018-11-08T16:24:19,194 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: Cleaning up thread local RawStore...
2018-11-08T16:24:19,195 INFO [pool-8-thread-31] org.apache.hadoop.hive.metastore.HiveMetaStore - 31: Done cleaning up thread local RawStore`

Can you please help on this?

**Comment by pashalogin** [comment]
It seems like partitions missing for your table. Is this internal table or external table? Try running msck repair on table before running query.

**Comment by findepi** [comment]
@SivaSamrajS , did @pashalogin comment help you?
please provide an answer if you still need assistance
