### ISSUE TITLE
ctas is not working for empty or null string column 

### ISSUE THREAD

**Issue by sivankumar86** [prestodb/presto#11905]
I want to create a table with empty string or null value but, it is failing with below error

Query 20181113_001815_00003_rt676 failed: Varchar length 0 out of allowed range [1, 65535]

create table empty_table_6 as SELECT * FROM (
     VALUES
         (1, '')        
 ) AS t (id, name);

**Comment by mbasmanova** [comment]
@sivankumar86 Which connector are you using?

**Comment by sivankumar86** [comment]
@mbasmanova Thank you for taking a look. it is hive connector in EMR 5.18.0

**Comment by findepi** [comment]
@sivankumar86 please provide Presto version, include full error stacktrace (run cli with `--debug`) and contents of `hive.properties`

**Comment by sivankumar86** [comment]
Presto version

Presto 0.212

hive.properties
==========

hive.metastore-cache-ttl=20m
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.non-managed-table-writes-enabled = true
hive.s3-file-system-type = EMRFS
hive.hdfs.impersonation.enabled = true
hive.metastore.uri = thrift://ip-172-31-20-209.ec2.internal:9083


stacktrace:

presto:default> create table empty_table_6 as SELECT * FROM (
             -> VALUES
             -> (1, '')
             -> ) AS t (id, name);
Query 20181119_041042_00002_cugfy failed: Varchar length 0 out of allowed range [1, 65535]
java.lang.RuntimeException: Varchar length 0 out of allowed range [1, 65535]
	at org.apache.hadoop.hive.serde2.typeinfo.BaseCharUtils.validateVarcharParameter(BaseCharUtils.java:32)
	at org.apache.hadoop.hive.serde2.typeinfo.VarcharTypeInfo.<init>(VarcharTypeInfo.java:33)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoFactory.createPrimitiveTypeInfo(TypeInfoFactory.java:151)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoFactory.getPrimitiveTypeInfo(TypeInfoFactory.java:109)
	at org.apache.hadoop.hive.serde2.typeinfo.TypeInfoFactory.getVarcharTypeInfo(TypeInfoFactory.java:170)
	at com.facebook.presto.hive.HiveTypeTranslator.translate(HiveTypeTranslator.java:93)
	at com.facebook.presto.hive.HiveType.toHiveType(HiveType.java:209)
	at com.facebook.presto.hive.HiveMetadata.getColumnHandles(HiveMetadata.java:1805)
	at com.facebook.presto.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:928)
	at com.facebook.presto.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:201)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:281)
	at com.facebook.presto.metadata.MetadataManager.beginCreateTable(MetadataManager.java:652)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:161)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:124)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
	at com.facebook.presto.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:106)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:22)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:150)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:139)

**Comment by kokosing** [comment]
What hive version do you use?

**Comment by sivankumar86** [comment]
hive 2.3.3

**Comment by kokosing** [comment]
CDH or HDP?

**Comment by findepi** [comment]
I guess this has nothing to do with CTAS. Rather, than we ask Hive to create column of `varchar(0)` type. @sivankumar86 can you try
```
CREATE TABLE t (c varchar(0)); -- i expect this to fail
```
and
```
create table empty_table_6 as  SELECT id, CAST(name AS varchar(4)) FROM (VALUES (1, '')) AS t (id, name); -- i expect this to succeed
```

**Comment by sivankumar86** [comment]
@findepi  Thank you, you are correct, it worked after casting with varchar(4).
