### ISSUE TITLE
Reading ORC files fails

### ISSUE THREAD

**Issue by arhimondr** [prestodb/presto#11928]
```
java.lang.IllegalArgumentException: min and max cannot both be null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.facebook.presto.orc.metadata.statistics.StringStatisticsBuilder.addStringStatistics(StringStatisticsBuilder.java:93)
	at com.facebook.presto.orc.metadata.statistics.StringStatisticsBuilder.mergeStringStatistics(StringStatisticsBuilder.java:157)
	at com.facebook.presto.orc.metadata.statistics.ColumnStatistics.mergeColumnStatistics(ColumnStatistics.java:272)
	at com.facebook.presto.orc.StripeReader.getRowGroupStatistics(StripeReader.java:469)
	at com.facebook.presto.orc.StripeReader.selectRowGroups(StripeReader.java:443)
	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:158)
	at com.facebook.presto.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:510)
	at com.facebook.presto.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:452)
	at com.facebook.presto.orc.OrcRecordReader.nextBatch(OrcRecordReader.java:381)
	at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:135)
	... 14 more
```

**Comment by arhimondr** [comment]
This commit https://github.com/prestodb/presto/commit/87f7e51c99963787f71027e749cf1e10815180fb#diff-2699d3c3c091813ca823fc2a9e2b2ee6R469 uses `ColumnStatistics.mergeColumnStatistics` to merge row group stats. Before, the `ColumnStatistics.mergeColumnStatistics` was used only when writing ORC files. ORC file writer in Presto doesn't set type specific statistics, such as `StringStatistics` or `IntegerStatistics`, etc. when both `min` and `max` are null. So the `StringStatistics` with both `min` and `max` null are not allowed in the merging code. However other ORC implementation are free to set `StringStatistics` even if both `min` and `max` are null

**Comment by arhimondr** [comment]
CC: @haozhun , @wenleix , @dain , @kevinwilfong

**Comment by nezihyigitbasi** [comment]
Closing as #11929 is already merged.
