### ISSUE TITLE
Integer overflow when turning dictionary into direct in ORC writer

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#11930]
```
java.lang.ArithmeticException: integer overflow 
 at java.base/java.lang.Math.toIntExact(Math.java:1071) 
 at com.facebook.presto.orc.ChunkedSliceOutput.size(ChunkedSliceOutput.java:104) 
 at com.facebook.presto.orc.OrcOutputBuffer.estimateOutputDataSize(OrcOutputBuffer.java:117) 
 at com.facebook.presto.orc.stream.ByteArrayOutputStream.getBufferedBytes(ByteArrayOutputStream.java:92) 
 at com.facebook.presto.orc.writer.SliceDirectColumnWriter.getBufferedBytes(SliceDirectColumnWriter.java:208) 
 at com.facebook.presto.orc.writer.SliceDictionaryColumnWriter.tryConvertToDirect(SliceDictionaryColumnWriter.java:213) 
 at com.facebook.presto.orc.DictionaryCompressionOptimizer$DictionaryColumnManager.tryConvertToDirect(DictionaryCompressionOptimizer.java:357) 
 at com.facebook.presto.orc.DictionaryCompressionOptimizer.tryConvertToDirect(DictionaryCompressionOptimizer.java:201) 
 at com.facebook.presto.orc.DictionaryCompressionOptimizer.optimize(DictionaryCompressionOptimizer.java:147)

**Comment by wenleix** [comment]
I suspect it's because one single row group can be too large after converting to direct encoded. I need to investigate the issue with production data. 

As a separate question, Given we have seen similar stacktraces in the past, @dain does it make sense to make the following two methods return long instead of integer:
```
SliceOutput::size()
SliceOutput::writerIndex()
```

since it's legit to have `ChunkedSliceOutput`'s size exceed integer.

**Comment by dain** [comment]
@wenleix, it seems reasonable to change `size()` to return `long`, but it is a backwards incompatible change.  @martint and @electrum, do you think it is worth it to make this change now, or should we introduce a new method for this?

**Comment by martint** [comment]
It's a little strange for SliceOutput::size() to return long, since SliceOutput is designed to write to a Slice, which only supports int lengths and offsets.
