### ISSUE TITLE
Presto worker experiences high System CPU 62.08% presto-server [kernel.kallsyms] [k] _spin_lock before recreating a new FileSystem

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#11949]
recentlly
I am suffering the high cpu issue in presto worker,  when I use top -p $PID -H  command i found the high cpu thread alway pending on this method .$gen.PageFilter_88896.filter always

may be there have connection between hdfs and presto I guess for this issue, because once our enginnering switch active namenode node from one to other, some of my presto worker will suffering this high cpu issue when split come and it always hang on this method gen.PageFilter_88896.filter, 

what I found is 
(1) in presto FileSystem we only use one instance per UGI because we always reused the cache.
(2) the lazyblock only call the hdfs api when gen.PageFilter_88896.filter is trigger. because it's lazyblock
so I guess the problem may be happen on the distributedFileSystem that presto provided
so far I don't have any conclusion about this issue
is there any one meeting this problem before and can give me some idea. 
Now i have to change the reused the cache to disable in presto hdfs-site.xml, but that will decrease the query performance

"20181120_031009_06443_w8gin.2.14-7-87400" #87400 prio=5 os_prio=0 tid=0x00007f9394001000 nid=0x7e8 runnable [0x00007f91bb0fb000]
   java.lang.Thread.State: RUNNABLE
        at com.facebook.presto.$gen.PageFilter_88896.filter(Unknown Source)
        at com.facebook.presto.$gen.PageFilter_88896.filter(Unknown Source)
        at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:86)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:286)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:234)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:369)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:266)
        at com.facebook.presto.operator.Driver$$Lambda$793/1099733161.get(Unknown Source)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:646)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:260)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecut

**Comment by photogamerun** [comment]
![image](https://user-images.githubusercontent.com/16651123/48757063-6ff0ab00-ecd6-11e8-9fa1-5c3954e8f167.png)

the cpu usage are so crazy, in this cluster 24 machines, only 3 machines has this bug, it really impact all the machine in this cluster and cause cpu high in all the machines

**Comment by photogamerun** [comment]
java 8 

I don't think it has some relation with filter, because a when I switch to other user with the same query cpu is not high

we use kerberos model
from my observed, I found PrestoFileSystemCache cache the UGI and fsSystem, when namenode switch from active to standy but the UGI still point to old fsSystem, looks like kerberos side cause the cput high, because later when the keberos ticket expired the privateCredentials change a new fsSystem create the problem solved automatically,

so I my side I change the TICKET_RENEW_WINDOW  to lower value to reduce the impact time and finally it resolved

final class KerberosTicketUtils
{
    private static final float TICKET_RENEW_WINDOW = 0.80f;

    private KerberosTicketUtils()
    {
    }

**Comment by photogamerun** [comment]
My workaround does't resolve the issue absolutely it still exist, but it only impact small time period.
it only related to how our company used presto, we only use presto on work time, switch the namenode is always do manually by our engineer at night so,  in previous the expired day is 24 hour, so it will impact next work day, now I change the value to 0.01 so it only impact  15 minutes.

**Comment by photogamerun** [comment]
when I perf report I found there is a spin_lock which ocupy most of cpu in presto server
62.08%  presto-server  [kernel.kallsyms]   [k] _spin_lock
   5.49%  presto-server  [kernel.kallsyms]   [k] ktime_get
   1.89%  presto-server  [kernel.kallsyms]   [k] ktime_get_update_offsets
   1.61%  presto-server  [kernel.kallsyms]   [k] _spin_lock_irqsave
   0.78%  presto-server  [kernel.kallsyms]   [k] system_call_after_swapgs
   0.68%  presto-server  [kernel.kallsyms]   [k] sysret_check
   0.65%  presto-server  libzip.so           [.] inflate_fast
   0.63%  presto-server  [kernel.kallsyms]   [k] futex_wait_setup
   0.52%  presto-server  libc-2.18.so        [.] vfprintf
   0.47%  presto-server  [kernel.kallsyms]   [k] rcu_process_gp_end
   0.45%  presto-server  [kernel.kallsyms]   [k] apic_timer_interrupt
   0.44%  presto-server  [kernel.kallsyms]   [k] futex_wake
   0.39%  presto-server  libc-2.18.so        [.] _int_malloc
   0.29%  presto-server  [kernel.kallsyms]   [k] update_cpu_load
   0.27%  presto-server  libc-2.18.so        [.] malloc
   0.27%  presto-server  [kernel.kallsyms]   [k] native_write_msr_safe
   0.26%  presto-server  [kernel.kallsyms]   [k] read_tsc

is  there any one help?

**Comment by photogamerun** [comment]
![image](https://user-images.githubusercontent.com/16651123/49427749-24162980-f7df-11e8-87cb-e064745e4153.png)

we found system cpu is very high

**Comment by nezihyigitbasi** [comment]
You should look at the entire stack to see who calls `_spin_lock`.

**Comment by photogamerun** [comment]
![image](https://user-images.githubusercontent.com/16651123/49629364-2a491780-fa24-11e8-9181-5e1d7b3cc437.png)

that the perf record, no idea how to found who call spin lock in java

**Comment by photogamerun** [comment]
![image](https://user-images.githubusercontent.com/16651123/49630518-7e0a2f80-fa29-11e8-9032-428492b123e0.png)

this is flame graph the red line has no any clue

**Comment by photogamerun** [comment]
"20181207_143217_10572_wdc8r.2.9-14-101319" #101319 prio=5 os_prio=0 tid=0x00007f00fc012800 nid=0x16586 runnable [0x00007efe54fd2000]
   java.lang.Thread.State: RUNNABLE
        at com.facebook.presto.$gen.PageFilter_91633.filter(Unknown Source)
        at com.facebook.presto.$gen.PageFilter_91633.filter(Unknown Source)
        at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:86)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:286)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:234)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:369)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:266)
        at com.facebook.presto.operator.Driver$$Lambda$753/1592787671.get(Unknown Source)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:646)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:260)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I am this function cause cpu high

**Comment by dain** [comment]
Jstack is not a great took for this kind of problem, since it only tells you where the JVM paused for "safe points", instead perf is a much better tool.  The flame graph above says that you are spending like 95 percent of the CPU in some unknown libc call.  I'd try to get a linux expert to look at the system to find out what is really happening.

**Comment by photogamerun** [comment]
high cpu happen on this sql
select   tmp_passengerall_lp.gender, SUM(  tmp_passengerall_lp.quantity )  as a, SUM(  tmp_passengerall_lp.ordercnt )  as b, AVG(  tmp_passengerall_lp.decide )  as c, (SUM(tmp_passengerall_lp.amount)/ SUM(tmp_passengerall_lp.quantity)) as d, SUM(  tmp_passengerall_lp.amount )  as e  from "tmp_mobdb"."tmp_passengerall_lp"  where  ( ( tmp_passengerall_lp.gender  is not null  ) )  and  ( ( tmp_passengerall_lp.effectdate  >= '2017-01-01' and  tmp_passengerall_lp.effectdate <=  '2017-11-30') )   group by  tmp_passengerall_lp.gender   LIMIT 2000 

when I run this sql presto work fine
select   tmp_passengerall_lp.gender, SUM(  tmp_passengerall_lp.quantity )  as a, SUM(  tmp_passengerall_lp.ordercnt )  as b, AVG(  tmp_passengerall_lp.decide )  as c, (SUM(tmp_passengerall_lp.amount)/ SUM(tmp_passengerall_lp.quantity)) as d, SUM(  tmp_passengerall_lp.amount )  as e  from "tmp_mobdb"."tmp_passengerall_lp" where ( ( tmp_passengerall_lp.gender  is not null  ) ) and tmp_passengerall_lp.effectdate  >= '2017-01-01' group by  tmp_passengerall_lp.gender   LIMIT 2000 


the different is first sql has  ( ( tmp_passengerall_lp.effectdate  >= '2017-01-01' and  tmp_passengerall_lp.effectdate <=  '2017-11-30') ) 
second one has  tmp_passengerall_lp.effectdate  >= '2017-01-01'

it look like the filter logic in presto cause the High cpu when pass the page position, there must be some position mistake when doing filter in presto

**Comment by photogamerun** [comment]
so far I have to do some config change 

so far I have to change compiler.expression-cache-size=10
 to reduce the dynamic byte code cache size and increase refresh frequency.  because once the dynamic byte code refresh presto work fine, it's so strange!!!!

**Comment by llysjtu** [comment]
@photogamerun Is your problem fixed yet? Our cluster meets almost the same problem.
