### ISSUE TITLE
Error while authentication with ldap

### ISSUE THREAD

**Issue by vikash32** [prestodb/presto#12032]
Hi,

When i am trying to connect presto using CLI with LDAP authentication. It always giving me server error. 

i am  using below cli command 
`./presto --server https://<prestoserver.com>:8443 --keystore-path presto_ldap/presto.jks --keystore-password apassword --catalog hive --schema default --user vikash --password`
 
then on cli it is giving me ERROR

```
Error running command: Error starting query at https://<prestoserver.com>:8443/v1/statement returned an invalid response: JsonResponse{statusCode=500, statusMessage=Server Error, headers={cache-control=[must-revalidate,no-cache,no-store], connection=[close], content-length=[14191], content-type=[text/html;charset=iso-8859-1]}, hasValue=false} [Error: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v1/statement. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.RuntimeException: Authentication error
	at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:71)
	at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
```
And on presto server it is throwing error as given below.

`2018-12-07T15:37:14.258+0530	WARN	http-worker-137	org.eclipse.jetty.server.HttpChannel	/v1/statement
java.lang.RuntimeException: Authentication error
	at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:71)
	at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:690)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
`
`
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Authentication error
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.password.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:90)
	at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:65)
	... 39 more
Caused by: java.lang.RuntimeException: Authentication error
	at com.facebook.presto.password.LdapAuthenticator.authenticate(LdapAuthenticator.java:120)
	at com.facebook.presto.password.LdapAuthenticator.authenticate(LdapAuthenticator.java:100)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	... 45 more
`

without https i.e on port 8080 it is working fine. but it is throwing error on port 8443 as given above.
Please let me know if more information required.

**Comment by dain** [comment]
The root cause in that stack is:
```
Caused by: java.lang.RuntimeException: Authentication error
  at com.facebook.presto.password.LdapAuthenticator.authenticate(LdapAuthenticator.java:120)
  at com.facebook.presto.password.LdapAuthenticator.authenticate(LdapAuthenticator.java:100)
  at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
  at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
  at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
  at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
  at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046) ... 45 more
```
Which I think is here in TRUNK: https://github.com/prestodb/presto/blob/master/presto-password-authenticators/src/main/java/com/facebook/presto/password/LdapAuthenticator.java#L120

Immediately before that error is thrown, the server logs the original exception with the message `Authentication error for user`.  If you see that in your logs, you should be able to find the root cause (which is likely some sort of communication error to the LDAP server itself).  If it is not there, then I would guess you are running and older version which didn't log the original error message.

**Comment by findepi** [comment]
> Immediately before that error is thrown, the server logs the original exception with the message Authentication error for user. If you see that in your logs ...

@vikash32 note that you need to enable DEBUG log level first.

**Comment by vikash32** [comment]
Hi @findepi @dain ,

i am running 0.214v of presto-server and client.
I have enabled DEBUG in log.properties
```
com.facebook.presto.server.security=DEBUG
com.facebook.presto=DEBUG
```
Now i am getting `LDAP: error code 34 - invalid DN` error on presto server.   I have configured password -authenticator.properties like below. 
```
password-authenticator.name=ldap
ldap.url=ldaps://<ldap_server>:636
ldap.user-bind-pattern=${USER},OU=Employees,DC=xyz,DC=com
ldap.user-base-dn=DC=xyz,DC=com
```
Also i have checked my ldap server. it is returning value fine with the user.
ldapsearch -x cn=vikash -b dc=xyz,dc=com
```
dn: uid=vikash,ou=Employees,dc=xyz,dc=com
objectClass: top
objectClass: account
objectClass: posixAccount
objectClass: shadowAccount
cn: vikash
uid: vikash
uidNumber: 1032
gidNumber: 1032
homeDirectory: /home/vikash
loginShell: /bin/bash
gecos: Vikash
shadowLastChange: 17058
shadowMin: 0
shadowMax: 99999
shadowWarning: 7
userPassword:: e1NTSEF9Zjd4S0JtYU1vOTBvb1sda2xiMVZWcUFTNitaSlJkREc=
``` 


Complete  error stacktrace of presto server
```
2018-12-10T18:02:11.049+0530	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========



2018-12-10T18:05:55.502+0530    DEBUG   http-worker-139	com.facebook.presto.password.LdapAuthenticator	Authentication error for user [vikash]
javax.naming.InvalidNameException: [LDAP: error code 34 - invalid DN]
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3095)
	at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2886)
	at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2800)
	at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
	at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
	at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
	at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.init(InitialContext.java:244)
	at javax.naming.InitialContext.<init>(InitialContext.java:216)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at com.facebook.presto.password.jndi.JndiUtils.createDirContext(JndiUtils.java:30)
	at com.facebook.presto.password.LdapAuthenticator.authenticate(LdapAuthenticator.java:108)
	at com.facebook.presto.password.LdapAuthenticator.authenticate(LdapAuthenticator.java:100)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.password.LdapAuthenticator.createAuthenticatedPrincipal(LdapAuthenticator.java:90)
	at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:65)
	at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:690)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by vikash32** [comment]
Hi @dain @findepi ,

Fixed it , it is because of configuration in the `password-authenticator.properties`.
As per documentation [https://prestodb.io/docs/current/security/ldap.html](url) it says config should be like below.
```
password-authenticator.name=ldap
ldap.url=ldaps://ldap-server:636
ldap.user-bind-pattern=<Refer below for usage>
```
where `ldap.user-bind-pattern=${USER}@corp.example.com` 
BUT
I have changes this one a little and now config it like below and it worked.
```
password-authenticator.name=ldap
ldap.url=ldaps://ldap_server.xyz.com:636
ldap.user-bind-pattern=uid=${USER},ou=Employees,dc=xyz,dc=com
ldap.user-base-dn=DC=timesgroup,DC=com
```
and getting 
```
2018-12-11T16:39:15.559+0530	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========
2018-12-11T16:39:26.556+0530	DEBUG	http-worker-139	com.facebook.presto.password.LdapAuthenticator	Authentication successful for user [vikash]
2018-12-11T16:39:27.354+0530	DEBUG	query-execution-0	com.facebook.presto.execution.QueryStateMachine	Query 20181211_110926_00000_skfjs is WAITING_FOR_RESOURCES
```
But is it possible to disable unsecure port, here in this case 8080 so that coordinator node will not get connected by presto-client.

**Comment by vikash32** [comment]
Hi @dain @findepi ,

Fixed it , it is because of configuration in the `password-authenticator.properties`.
As per documentation [https://prestodb.io/docs/current/security/ldap.html](url) it says config should be like below.
```
password-authenticator.name=ldap
ldap.url=ldaps://ldap-server:636
ldap.user-bind-pattern=<Refer below for usage>
```
where `ldap.user-bind-pattern=${USER}@corp.example.com` 
BUT
I have changes this one a little config it like below and it worked.
```
password-authenticator.name=ldap
ldap.url=ldaps://ldap_server.xyz.com:636
ldap.user-bind-pattern=uid=${USER},ou=Employees,dc=xyz,dc=com
ldap.user-base-dn=DC=xyz,DC=com
```
and getting 
```
2018-12-11T16:39:15.559+0530	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========
2018-12-11T16:39:26.556+0530	DEBUG	http-worker-139	com.facebook.presto.password.LdapAuthenticator	Authentication successful for user [vikash]
2018-12-11T16:39:27.354+0530	DEBUG	query-execution-0	com.facebook.presto.execution.QueryStateMachine	Query 20181211_110926_00000_skfjs is WAITING_FOR_RESOURCES
```
Now is it possible to disable unsecure port 8080 so that presto-client will not able to connect on these port and only secure port able to connect coordinator node.

**Comment by findepi** [comment]
> Now is it possible to disable unsecure port 8080 so that presto-client will not able to connect on these port and through secure port to connect coordinator node.

```
http-server.http.enabled=false
```

in `config.properties`

**Comment by vikash32** [comment]
Hi @findepi 

I tried with this config `http-server.http.enabled=false`, but after disabling port 8080 discovery uri is not accessible because embedded discovery service running on port 8080. 

However i am successfully manage to disable the unsecure port 8080 with `Secure Internal Communication` configuration and kerberos but not with LDAP.
 
i think presto does not support `LDAP` with `Secure Internal Communication` . But it do with Kerberos.
