### ISSUE TITLE
Verifier incorrectly handles tear-down failures

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12043]
The following logic appears to prefer tear-down failures over setup and run failures. It needs to be reversed. Also, teardown logic doesn't handle the case of setup failure resulting in "Can't drop tmp table" errors.

```
queryResult = tearDownResult.getState() == State.SUCCESS ? queryResult : tearDownResult;
```

```
Test state FAILED_TO_TEARDOWN, Control state SUCCESS
java.sql.SQLException: Query failed (#20181205_151007_11271_a8s27): The following metastore delete operations failed: drop table local_atn1sodium.tmp_verifier_9e8b12601503454abfce2a1f4c4d1bbe
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1840)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1750)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:119)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:249)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:227)
	at jdk.internal.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.common.util.concurrent.SimpleTimeLimiter$1$1.call(SimpleTimeLimiter.java:95)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:238)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:135)
	at com.google.common.util.concurrent.SimpleTimeLimiter.access$100(SimpleTimeLimiter.java:48)
	at com.google.common.util.concurrent.SimpleTimeLimiter$1.invoke(SimpleTimeLimiter.java:101)
	at com.sun.proxy.$Proxy72.execute(Unknown Source)
	at com.facebook.presto.verifier.Validator.executeQuery(Validator.java:430)
	at com.facebook.presto.verifier.Validator.lambda$executeQueryTest$1(Validator.java:315)
	at com.facebook.presto.verifier.Validator.tearDown(Validator.java:240)
	at com.facebook.presto.verifier.Validator.executeQueryTest(Validator.java:315)
	at com.facebook.presto.verifier.Validator.validate(Validator.java:219)
	at com.facebook.presto.verifier.Validator.valid(Validator.java:191)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.facebook.presto.spi.PrestoException: The following metastore delete operations failed: drop table local_atn1sodium.tmp_verifier_9e8b12601503454abfce2a1f4c4d1bbe
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeIrreversibleMetastoreOperations(SemiTransactionalHiveMetastore.java:1381)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$2300(SemiTransactionalHiveMetastore.java:957)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:935)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:807)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:1949)
	at com.facebook.presto.hive.PrismMetadata.commit(PrismMetadata.java:687)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:188)
	at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:593)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
	Suppressed: com.facebook.presto.spi.TableNotFoundException: Table 'local_atn1sodium.tmp_verifier_9e8b12601503454abfce2a1f4c4d1bbe' not found
		at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.dropTable(ThriftHiveMetastore.java:704)
		at com.facebook.presto.hive.metastore.thrift.PrismHiveMetastore.dropTable(PrismHiveMetastore.java:142)
		at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.dropTable(BridgingHiveMetastore.java:167)
		at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:427)
		at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:427)
		at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.lambda$prepareDropTable$0(SemiTransactionalHiveMetastore.java:983)
		at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$IrreversibleMetastoreOperation.run(SemiTransactionalHiveMetastore.java:2216)
		at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeIrreversibleMetastoreOperations(SemiTransactionalHiveMetastore.java:1360)
		... 15 more
```

**Comment by mbasmanova** [comment]
CC: @zein @ggreg @nezihyigitbasi

**Comment by nezihyigitbasi** [comment]
> The following logic appears to prefer tear-down failures over setup and run failures. 

Breaking the existing logic down:

- If setup fails (we don't run the query), then if teardown succeeds we use the setup result, else we use teardown result. So, tear down failure is preferred over the setup failure. Do you have concerns about this?

- If setup succeeds (we run the query), then if teardown succeeds we use the query result (which is fine), else we use the teardown result. Are you saying that for the teardown failure case here we shouldn't use the teardown result, but still use the query result? 

> Also, teardown logic doesn't handle the case of setup failure resulting in "Can't drop tmp table" errors.

Can you please elaborate? As far as I can see from the code the `SqlException`s are handled fine in `Validator::executeQuery`. The `tearDown` call is also retried a configurable number of times (default is 1). The stack trace and the error you paste is the error message set in the `VerifierQueryEvent` by looking at the exceptions in the query results. In this case the query failed, because tear down failed with that message.

**Comment by mbasmanova** [comment]
@nezihyigitbasi The error message says "delete operations failed: drop table tmp_verifier_xxx: Table not found". How could this happen? The only explanation I can think of is that setup failed to create tmp_verifier_xxx table. E.g. setup failed, then teardown failed. In this case, knowing why setup failed is more important, but that error information is missing.

I also thinkg that tear down needs to be more robust and succeed if it can't delete a table that doesn't exist.
