### ISSUE TITLE
"future should be done" assertion in HashBuilderOperator

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#12040]
Some queries are failing with this stack trace:

```
Caused by: com.google.common.base.VerifyException: future should be done
	at com.google.common.base.Verify.verify(Verify.java:123)
	at com.facebook.presto.memory.DefaultQueryContext.tryUpdateUserMemory(DefaultQueryContext.java:199)
	at com.facebook.presto.memory.DefaultQueryContext$QueryMemoryReservationHandler.tryReserveMemory(DefaultQueryContext.java:314)
	at com.facebook.presto.memory.context.RootAggregatedMemoryContext.tryUpdateBytes(RootAggregatedMemoryContext.java:49)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.tryUpdateBytes(ChildAggregatedMemoryContext.java:46)
	at com.facebook.presto.memory.context.SimpleLocalMemoryContext.trySetBytes(SimpleLocalMemoryContext.java:77)
	at com.facebook.presto.operator.OperatorContext$InternalLocalMemoryContext.trySetBytes(OperatorContext.java:599)
	at com.facebook.presto.operator.HashBuilderOperator.updateIndex(HashBuilderOperator.java:344)
	at com.facebook.presto.operator.HashBuilderOperator.addInput(HashBuilderOperator.java:333)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_214_84_gad05dcb____20181206_001801_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by nezihyigitbasi** [comment]
This should happen when:
- `delta <=0` so that we execute that `verify` call in `tryUpdateUserMemory`.
- `delta >= 0` so that we return a future (on L136) other than `NOT_BLOCKED` in `updateUserMemory` method.

Together this means `delta = 0`, and for the future to be not done the general pool must be full. I will think about a fix for this.
