### ISSUE TITLE
Error in retrieval of decimal(m, n) columns via JDBC

### ISSUE THREAD

**Issue by MichaelChirico** [prestodb/presto#12197]
Pushing upstream from issues dealing with retrieving these columns to R:

https://github.com/s-u/RJDBC/issues/68

https://github.com/r-dbi/DBI/issues/247

I'm not sure, but this may be a duplicate of https://github.com/prestodb/presto/issues/11467 (certainly related)

**Comment by findepi** [comment]
@MichaelChirico i know nothing about RJDBC or r-dbi. Can you phrase the issue in a way that I have a chance to understand it?

**Comment by dernst** [comment]
RJDBC tries to call `getDouble` on the `ResultSet` for a column of type `DECIMAL` which causes an exception stating that `String` is not numeric.

According to https://docs.oracle.com/javase/1.5.0/docs/guide/jdbc/getstart/mapping.html :
> The method recommended for retrieving DECIMAL and NUMERIC values is ResultSet.getBigDecimal. JDBC also allows access to these SQL types as simple Strings or arrays of char. Thus, Java programmers can use getString to receive a DECIMAL or NUMERIC result. However, this makes the common case where DECIMAL or NUMERIC are used for currency values rather awkward, since it means that application writers have to perform math on strings. It is also possible to retrieve these SQL types as any of the Java numeric types. 

I would assume that it should be possible to extract values from a `DECIMAL`  as Java's `BigDecimal`, `String` or `double` (and other numeric types).

**Comment by dernst** [comment]
Here's a short Java program which demonstrates the problem.
```
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;

public class PrestoTest {
    public static void main(String[] args) throws SQLException {
        String url = "jdbc:presto://192.168.0.10:8080/memory/";
        Connection conn = DriverManager.getConnection(url, "test", null);

        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery("SELECT cast(42.1 as decimal(17,7))");
        rs.next();

        /* rs.getDouble throws an exception:
         *
         * Exception in thread "main" java.sql.SQLException: Value is not a number: java.lang.String
         *  at com.facebook.presto.jdbc.PrestoResultSet.toNumber(PrestoResultSet.java:1729)
         *  at com.facebook.presto.jdbc.PrestoResultSet.getDouble(PrestoResultSet.java:229)
         *  at PrestoTest.main(PrestoTest.java:22)
         *
        */
        double x = rs.getDouble(1);
        System.out.println("got: " + x);
    }
}
```

I suppose the issue is if presto should be able to return decimal columns as double or not.

**Comment by yanqingfu** [comment]
any solution for this, I encountered the same issue: 
Error in .jcall(rp, "I", "fetch", stride, block) : 
  java.sql.SQLException: Value is not a number: java.lang.String

access to a Presto database, one column datatype is decimal(38,12)

driver downloaded from https://prestodb.io/docs/current/installation/jdbc.html
drv <-  JDBC("io.prestosql.jdbc.PrestoDriver",classPath="Documents/presto-jdbc-0.240.jar")

using RJDBC to connect to the database in RStudio

**Comment by yanqingfu** [comment]
I have another oracle database , and when using driver = JDBC("oracle.jdbc.OracleDriver",classPath="/Users/670951/Desktop/ojdbc6.jar") to do select *, no such java error

which means the problem might in PrestoDriver

**Comment by MichaelChirico** [comment]
ultimately I switched to using the REST API for retrieving Presto queries
instead of JDBC, FWIW.

**Comment by MichaelChirico** [comment]
I'm afraid I'm no longer at that company. but it was basically a matter of
using the presto REST API as documented via httr. talk with your
engineering/dbops folks about where the endpoint is / what port is
listening.

**Comment by yanqingfu** [comment]
@MichaelChirico thanks, finally figure it out with RPresto

library(DBI)
library(RPresto)
con <- dbConnect(
  RPresto::Presto(),
  host = "<hostname> with http://",
  port = portnumber,
  user = 'username',
  catalog = 'name1',
  schema = 'name2'
)
dbGetQuery(con, 'SELECT column FROM name1.name2.table LIMIT 10')

**Comment by findepi** [comment]
> drv <- JDBC("io.prestosql.jdbc.PrestoDriver"...

@yanqingfu you are using PrestoSQL driver
PrestoSQL releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)

**Comment by yanqingfu** [comment]
@findepi  thanks for the info
