### ISSUE TITLE
Planner NPE with OUT JOIN and TRY

### ISSUE THREAD

**Issue by highker** [prestodb/presto#12237]
Reproduce with
```sql
SELECT
    *
FROM (
    (
        SELECT
            *
        FROM (
            VALUES (1, 4),
                (2, 5),
                (3, 6)
        ) AS a(x, y)
    ) a
    LEFT OUTER JOIN (
            SELECT
                *
            FROM (
                VALUES (1, 4),
                    (2, 5),
                    (3, 6)
            ) AS b(x, y)
        ) b
        ON a.x = b.x
)
WHERE
    TRY(GREAT_CIRCLE_DISTANCE(a.x, a.y, b.x, b.y)) < 10
```

Stacktrace:
```
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:882)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:788)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitBindExpression(ExpressionInterpreter.java:954)
	at com.facebook.presto.sql.tree.BindExpression.accept(BindExpression.java:85)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:901)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:731)
	at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:71)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:261)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.nullInputEvaluator(PredicatePushDown.java:954)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.canConvertOuterToInner(PredicatePushDown.java:908)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.tryNormalizeToOuterToInnerJoin(PredicatePushDown.java:895)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:359)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:128)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:287)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitFilter(PredicatePushDown.java:339)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitFilter(PredicatePushDown.java:128)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:165)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:128)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown.optimize(PredicatePushDown.java:122)
	at com.facebook.presto.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:51)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:163)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:152)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:416)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:401)
	at com.facebook.presto.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:345)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:519)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:506)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1347)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:39)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
	at io.airlift.concurrent.MoreFutures.addSuccessCallback(MoreFutures.java:512)
	at io.airlift.concurrent.MoreFutures.addSuccessCallback(MoreFutures.java:519)
	at com.facebook.presto.execution.SqlQueryExecution.waitForMinimumWorkers(SqlQueryExecution.java:330)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:323)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by highker** [comment]
dup #10848; close
