### ISSUE TITLE
Query failed with "because noMoreSplits has already been set for"

### ISSUE THREAD

**Issue by javainthinking** [prestodb/presto#12246]
Query pattern like below failed with message "because noMoreSplits has already been set for":
select * from 
(select * from nation union select * from nation)
limit 100;

based on version 0.165

Stack:
java.lang.IllegalStateException: noMoreSplits has already been set for 23
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at com.facebook.presto.server.remotetask.HttpRemoteTask.addSplits(HttpRemoteTask.java:424)
	at com.facebook.presto.execution.SqlStageExecution.addExchangeLocations(SqlStageExecution.java:269)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler$StageLinkage.processScheduleResults(SqlQueryScheduler.java:870)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.lambda$schedule$14(SqlQueryScheduler.java:688)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:687)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nezihyigitbasi** [comment]
0.165 is a pretty old version, and it's very likely that this issue has been fixed. Can you please try the latest Presto version (0.215)?
