### ISSUE TITLE
not able to bring up the presto

### ISSUE THREAD

**Issue by ManasaDornala** [prestodb/presto#12253]
Hi Team,

We are using presto and it is throwing an error once we launch it.

ERROR	main	com.facebook.presto.server.PrestoServer	Method [public com.facebook.presto.spi.block.Block com.facebook.presto.ml.MLFeaturesFunctions.features(double,double,double,double,double,double,double,double)] is an instance method. It must be in a class annotated with @ScalarFunction, and the class is required to have a public constructor.

java.lang.IllegalArgumentException: Method [public com.facebook.presto.spi.block.Block com.facebook.presto.ml.MLFeaturesFunctions.features(double,double,double,double,double,double,double,double)] is an instance method. It must be in a class annotated with @ScalarFunction, and the class is required to have a public constructor.

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)

	at com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser.getConstructor(ParametricScalarImplementation.java:646)

	at com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser.<init>(ParametricScalarImplementation.java:513)

	at com.facebook.presto.operator.scalar.annotations.ParametricScalarImplementation$Parser.parseImplementation(ParametricScalarImplementation.java:710)

	at com.facebook.presto.operator.scalar.annotations.ScalarFromAnnotationsParser.parseParametricScalar(ScalarFromAnnotationsParser.java:106)

	at com.facebook.presto.operator.scalar.annotations.ScalarFromAnnotationsParser.parseFunctionDefinitions(ScalarFromAnnotationsParser.java:60)

	at com.facebook.presto.metadata.FunctionExtractor.extractFunctions(FunctionExtractor.java:57)

	at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:200)

	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:172)

	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:156)

	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:137)

	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:117)

	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

**Comment by findepi** [comment]
Hi @ManasaDornala 

apparently you're using `presto-ml` from some older Presto version with newer Presto version.
(in particular, your `presto-ml` misses this change: https://github.com/prestodb/presto/commit/45c18adc96d9d1a866fff7c39e4e818c7b663463#diff-194415b939d187c0b66a1d9d5c14baca)

please use consistent plugin versions though out your deployment.

**Comment by ManasaDornala** [comment]
Hi @findepi , Thank you.
Right now the vesrion - presto-server-0.208-e.0.3.tar.gz has only few plugins.
Do we need to gather all the plugins from each version from my old version and keep the latest ones
or do we have them anywhere.

**Comment by findepi** [comment]
@ManasaDornala 
if you're using -e release, please upgrade to 213e.
You need to download fresh installation package (perhaps rpm). *Do not* copy plugins from older version.
