### ISSUE TITLE
Sometimes Presto cancels my whole query because just one of my rows is malformed

### ISSUE THREAD

**Issue by danb-lotsofnumbers** [prestodb/presto#12289]
I have a table with millions of rows in it.  A very small percentage of the rows are malformed.
I would like to run queries against my table.  I don't care what happens to the malformed rows.  I want to get results for the rows which are not malformed.

When I do this using Presto, sometimes my query gets cancelled.  I get an error message that helpfully tells me that one of my rows was malformed and therefore it cancelled my whole query.

I don't want this to happen.  I want my query to run.

You might argue that I can work around this bug by wrapping every computation in TRY() so that it will return null instead of cancel.  I've recently discovered there's a broad class of errors which will ignore my TRY() and cancel my query anyway.

I do not want my query to be cancelled.  Not ever.  Not for any reason (other than a failure to parse the query itself).  I want my query to run.

Here's one example where this happens:

Exception: com.esri.core.geometry.GeometryException: This operation should not be performed on an empty geometry. 
	at com.esri.core.geometry.Point.getX(Point.java:186) 
	at com.facebook.presto.plugin.geospatial.GeoFunctions.computePolygonCentroid(GeoFunctions.java:1338) 
	at com.facebook.presto.plugin.geospatial.GeoFunctions.computeMultiPolygonCentroid(GeoFunctions.java:1387) 
	at com.facebook.presto.plugin.geospatial.GeoFunctions.stCentroid(GeoFunctions.java:346) 
	at com.facebook.presto.$gen.PageProjectionWork_20190131_203944_59719_8bmx4_8_13_300718.lambda_0(Unknown Source) 
	at com.facebook.presto.operator.scalar.TryFunction.trySlice(TryFunction.java:92) 
	at com.facebook.presto.$gen.PageProjectionWork_20190131_203944_59719_8bmx4_8_13_300718.evaluate(Unknown Source) 
	at com.facebook.presto.$gen.PageProjectionWork_20190131_203944_59719_8bmx4_8_13_300718.process(Unknown Source) 
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:295) 
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:183) 
	at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315) 
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79) 
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65) 
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141) 
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136) 
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:111) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:296) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:231) 
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379) 
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283) 
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675) 
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276) 
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077) 
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162) 
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483) 
	at com.facebook.presto.$gen.Presto_0_216____20190130_011429_1.run(Unknown Source) 
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) 
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
	at java.base/java.lang.Thread.run(Thread.java:844)

Here is a different one:

Exception: java.nio.BufferUnderflowException 
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:628) 
	at java.base/java.nio.ByteBufferAsIntBufferB.get(ByteBufferAsIntBufferB.java:120) 
	at com.facebook.presto.facebook.FacebookGeoFunctions.fbFromEntGeoPolygon(FacebookGeoFunctions.java:200) 
	at com.facebook.presto.$gen.PageProjectionWork_20190131_220202_64999_xwygd_8_13_304764.lambda_0(Unknown Source) 
	at com.facebook.presto.operator.scalar.TryFunction.trySlice(TryFunction.java:92) 
	at com.facebook.presto.$gen.PageProjectionWork_20190131_220202_64999_xwygd_8_13_304764.evaluate(Unknown Source) 
	at com.facebook.presto.$gen.PageProjectionWork_20190131_220202_64999_xwygd_8_13_304764.process(Unknown Source) 
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:295) 
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:183) 
	at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315) 
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79) 
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65) 
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141) 
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136) 
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:111) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:296) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:231) 
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379) 
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283) 
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675) 
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276) 
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077) 
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162) 
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483) 
	at com.facebook.presto.$gen.Presto_0_216____20190130_011455_1.run(Unknown Source) 
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) 
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
	at java.base/java.lang.Thread.run(Thread.java:844) 

Both of these errors cancelled my query even though I wrapped everything in TRY().

But this issue is not about ST_Centroid or about fb_from_ent_geo_polygon.  This issue is about the more general flaw in Presto that _sometimes it cancels my query_.

How can I make Presto not cancel my query?

**Comment by dain** [comment]
> at com.facebook.presto.facebook.FacebookGeoFunctions.fbFromEntGeoPolygon(FacebookGeoFunctions.java:200)

I don't see this function in the Presto codebase, but assuming it is a scalar function, you can wrap it in [`try`](https://prestosql.io/docs/current/functions/conditional.html#try) call, which will return `null` instead of failing.  For example:
```sql
SELECT try(fb_from_ent_geo_polygon('invalid polygon');
```

**Comment by electrum** [comment]
> I've recently discovered there's a broad class of errors which will ignore my TRY() 

Functions should throw `INVALID_FUNCTION_ARGUMENT` for invalid input, which will allow `try()` to handle them. Both of the functions you listed do not properly handle invalid input (by converting them into an appropriate Presto exception).

Presto aborts the query on an unknown error because in general, a database should return correct answers above all else. For years we've talked about adding a best-effort mode that could continue on certain types of errors, though it's never been a high priority and it's not clear exactly how it would work (what errors would be allowed and such).

**Comment by danb-lotsofnumbers** [comment]
@electrum, thanks for reading my post!

It sounds like Presto has some assumptions about the way functions will be written, but either:
 * the assumptions are not being communicated to people writing the functions
 * the people writing the functions have trouble predicting what sorts of exceptions might be thrown by invalid inputs
It seems like this is leading to a bad user experience.  I wonder if there's a way to fix it?

One idea might be to add a function which would be like TRY() but would actually catch all exceptions, the way that we expect TRY() would.  I'm not sure what such a function would be called -- perhaps TRY_ALL().

**Comment by findepi** [comment]
> the people writing the functions have trouble predicting what sorts of exceptions might be thrown by invalid inputs

that's correct.  Consider the case where your query does not have `TRY` -- is it then OK to fail the query with eg NullPointerException when function input is invalid?
We need to fix these functions, but unfortunately, we cannot fix them in a generic way.
