### ISSUE TITLE
Hive Connector doesn't support reading temp table created inside transaction

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#12311]
To reproduce (write mode is `STAGE_AND_MOVE_TO_TARGET_DIRECTORY`):
```sql

START TRANSACTION;

CREATE TABLE hive.tpch_bucketed.tmp_orders_bucketed
WITH (bucketed_by = ARRAY['custkey'], bucket_count = 11)
AS
SELECT * 
FROM  hive.tpch.orders;


SELECT count(*) FROM hive.tpch_bucketed.tmp_orders_bucketed;

```

Failed with:
```
Query 20190207_015020_00028_dna6g failed: Partition location does not exist: file:/var/folders/cs/tktg4_9j59g6m202z1sfr65xl7_b9w/T/PrestoTest1215964744893499018/hive_data/tpch_bucketed/tmp_orders_bucketed
com.facebook.presto.spi.PrestoException: Partition location does not exist: file:/var/folders/cs/tktg4_9j59g6m202z1sfr65xl7_b9w/T/PrestoTest1215964744893499018/hive_data/tpch_bucketed/tmp_orders_bucketed
	at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.processException(HiveFileIterator.java:163)
	at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:133)
	at com.facebook.presto.hive.util.HiveFileIterator$FileStatusIterator.<init>(HiveFileIterator.java:118)
	at com.facebook.presto.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:107)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:100)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:37)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.addAll(Iterators.java:357)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.getBucketedSplits(BackgroundHiveSplitLoader.java:421)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:369)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:258)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:93)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:187)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The issue is directory rename is happening at the commit time.

We have special handle for new added partition in ongoing transaction, but not new added table: 
https://github.com/prestodb/presto/blob/c7576b8f604019bd74c0a4899581c792dd6d6547/presto-hive/src/main/java/com/facebook/presto/hive/metastore/SemiTransactionalHiveMetastore.java#L2066-L2079

**Comment by wenleix** [comment]
cc @arhimondr

**Comment by wenleix** [comment]
Previous fix get reverted by https://github.com/prestodb/presto/pull/12394
