### ISSUE TITLE
failed: Equi criteria are empty, so INNER join should not have PARTITIONED distribution type

### ISSUE THREAD

**Issue by ziyege** [prestodb/presto#12354]
Execute join query in presto-cli across different data sources and see this error.

select * from epet.epet_mall.jz_warehouse_list inner join warehouse.epet_warehouse.jz_kingdee_adjust on epet.epet_mall.jz_warehouse_list.wid=warehouse.epet_warehouse.jz_kingdee_adjust.wid where epet.epet_mall.jz_warehouse_list.wid=1 limit 10;

2019-02-19T16:15:10.779+0800	DEBUG	Query-20190219_081506_00017_m793j-405	com.facebook.presto.execution.QueryStateMachineQuery 20190219_081506_00017_m793j failed
java.lang.IllegalArgumentException: Equi criteria are empty, so INNER join should not have PARTITIONED distribution type
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:437)
	at com.facebook.presto.sql.planner.plan.JoinNode.<init>(JoinNode.java:112)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:529)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:287)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:166)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitLimit(PlanVisitor.java:54)
	at com.facebook.presto.sql.planner.plan.LimitNode.accept(LimitNode.java:87)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitExchange(PredicatePushDown.java:189)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitExchange(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:243)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:166)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitLimit(PlanVisitor.java:54)
	at com.facebook.presto.sql.planner.plan.LimitNode.accept(LimitNode.java:87)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:166)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:129)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown.optimize(PredicatePushDown.java:123)
	at com.facebook.presto.sql.planner.optimizations.StatsRecordingPlanOptimizer.optimize(StatsRecordingPlanOptimizer.java:51)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:163)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:152)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:418)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:403)
	at com.facebook.presto.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:347)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:519)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:506)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1347)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:39)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
	at io.airlift.concurrent.MoreFutures.addSuccessCallback(MoreFutures.java:512)
	at io.airlift.concurrent.MoreFutures.addSuccessCallback(MoreFutures.java:519)
	at com.facebook.presto.execution.SqlQueryExecution.waitForMinimumWorkers(SqlQueryExecution.java:332)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:325)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rschlussel** [comment]
1. What version of Presto are you running?  What configuration/session properties do you have set?
2. Do you have an example that we can reproduce (e.g. with the tpch or tpcds connector).  I tried to reproduce with the following query using the tpch query runner on tpch.sf1., but I didn't encounter your error (see below) 
```
presto:sf1> select * from nation join region on nation.regionkey = region.regionkey where nation.regionkey=1 limit 10;
 nationkey |     name      | regionkey |                                                    comment                                                     | regionkey |  name   |             comment             
-----------+---------------+-----------+----------------------------------------------------------------------------------------------------------------+-----------+---------+---------------------------------
         1 | ARGENTINA     |         1 | al foxes promise slyly according to the regular accounts. bold requests alon                                   |         1 | AMERICA | hs use ironic, even requests. s 
         2 | BRAZIL        |         1 | y alongside of the pending deposits. carefully special packages are about the ironic forges. slyly special     |         1 | AMERICA | hs use ironic, even requests. s 
         3 | CANADA        |         1 | eas hang ironic, silent packages. slyly regular packages are furiously over the tithes. fluffily bold          |         1 | AMERICA | hs use ironic, even requests. s 
        17 | PERU          |         1 | platelets. blithely pending dependencies use fluffily across the even pinto beans. carefully silent accoun     |         1 | AMERICA | hs use ironic, even requests. s 
        24 | UNITED STATES |         1 | y final packages. slow foxes cajole quickly. quickly silent platelets breach ironic accounts. unusual pinto be |         1 | AMERICA | hs use ironic, even requests. s 
(5 rows)
```

**Comment by wenleix** [comment]
@ziyege  This is English-language-only Github community :)

**Comment by qqibrow** [comment]
This could be reproduced by:
```
-- in hive:
CREATE TABLE tmp.t1 ( eid smallint, name String)
create table tmp.t2 (eid bigint, name String)
```
in presto:
```
explain SELECT c.name 
FROM tmp.t1 f JOIN tmp.t2 c 
ON f.eid = c.eid WHERE f.eid = 1
failed: Equi criteria are empty, so INNER join should not have PARTITIONED distribution type
```
if you do:
```
explain SELECT c.name 
FROM tmp.t1 f JOIN tmp.t2 c 
ON f.eid = c.eid WHERE f.eid = smallint '1'
```
it will succeed. 

Commit 48fe4a6938675f1d876df938c3b0f7f53ef92a98 introduced the side effect.  I find the code path is complicated to debug. Any idea on how to fix it elegantly? 
@rschlussel @wenleix

**Comment by rschlussel** [comment]
Thanks for the reproduction.  It looks like this is caused by predicate push down removing equijoin criteria after the distribution type has already been set.  The fix is pretty simple, but I still need to figure out how to write an automated test for it because our integration test tables don't have tinyint types.

**Comment by qqibrow** [comment]
thanks for the quick fix. Testing is important actually. I don't know why below query cannot reproduce:
```
select a 
from (VALUES bigint '1', bigint '2', bigint '3') t(a)
 join (VALUES smallint '0', smallint '1') p(b)
 on b = a and b = 1
```

**Comment by rschlussel** [comment]
The values version doesn't reproduce because the query only fails when new information from the TableLayout allows more predicates to be pushed down.  Values statements have all their information up front.
