### ISSUE TITLE
CreateEmptyPartition procedure might fail due to ExceptionInInitializerError in some rare case

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#12415]
We suspect it might because we don't use a `ClassloaderSafeMetadata`

Stacktrace

```
2019-02-26T10:06:14.133-0800    DEBUG   query-scheduler-6       com.facebook.presto.execution.QueryStateMachine Query 20190226_180613_00112_43887 failed
com.facebook.presto.spi.PrestoException: PROCEDURE_CALL_FAILED
        at com.facebook.presto.execution.CallTask.execute(CallTask.java:167)
        at com.facebook.presto.execution.CallTask.execute(CallTask.java:60)
        at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:168)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ExceptionInInitializerError
        at com.facebook.presto.hive.HdfsConfigurationUpdater.configureCompression(HdfsConfigurationUpdater.java:153)
        at com.facebook.presto.hive.HdfsConfigurationUpdater.updateConfiguration(HdfsConfigurationUpdater.java:145)
        at com.facebook.presto.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:40)
        at com.facebook.presto.hive.HiveHdfsConfiguration$1.initialValue(HiveHdfsConfiguration.java:34)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:170)
        at com.facebook.presto.hive.HiveHdfsConfiguration.getConfiguration(HiveHdfsConfiguration.java:57)
        at com.facebook.presto.hive.WarmStorageHdfsConfiguration.getConfiguration(WarmStorageHdfsConfiguration.java:48)
        at com.facebook.presto.hive.HdfsEnvironment.getConfiguration(HdfsEnvironment.java:58)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
        at com.facebook.presto.hive.HiveWriteUtils.pathExists(HiveWriteUtils.java:506)
        at com.facebook.presto.hive.*****LocationService.forExistingTable(*****LocationService.java:69)
        at com.facebook.presto.hive.HiveMetadata.beginInsert(HiveMetadata.java:1270)
        at com.facebook.presto.hive.*****Metadata.beginInsert(*****Metadata.java:361)
        at com.facebook.presto.hive.CreateEmptyPartitionProcedure.createEmptyPartition(CreateEmptyPartitionProcedure.java:89)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:707)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
        at com.facebook.presto.execution.CallTask.execute(CallTask.java:160)
        ... 5 more
Caused by: java.lang.RuntimeException: Illegal Hadoop Version: Unknown (expected A.B.* format)
        at org.apache.hadoop.hive.shims.ShimLoader.getMajorVersion(ShimLoader.java:164)
        at org.apache.hadoop.hive.shims.ShimLoader.loadShims(ShimLoader.java:139)
        at org.apache.hadoop.hive.shims.ShimLoader.getHadoopShims(ShimLoader.java:100)
        at org.apache.hadoop.hive.conf.HiveConf$ConfVars.<clinit>(HiveConf.java:371)
        ... 23 more
```

**Comment by wenleix** [comment]
The similar issue was reported in https://github.com/prestosql/presto/issues/412 as well.
