### ISSUE TITLE
Presto 0.215 data type errors when reading Parquet Data

### ISSUE THREAD

**Issue by mnoumanshahzad** [prestodb/presto#12418]
Hi,

I am using Presto 0.215 and querying Parquet data in AWS S3.
I was previously running Presto 0.206 and did not get these errors.

I am getting the following errors at times, but so far could not understand why I get them.

`java.lang.UnsupportedOperationException: com.facebook.presto.spi.type.TimestampType
	at com.facebook.presto.spi.type.AbstractType.writeSlice(AbstractType.java:135)
	at com.facebook.presto.parquet.reader.BinaryColumnReader.readValue(BinaryColumnReader.java:55)
	at com.facebook.presto.parquet.reader.PrimitiveColumnReader.lambda$readValues$1(PrimitiveColumnReader.java:184)
	at com.facebook.presto.parquet.reader.PrimitiveColumnReader.processValues(PrimitiveColumnReader.java:204)
	at com.facebook.presto.parquet.reader.PrimitiveColumnReader.readValues(PrimitiveColumnReader.java:183)
	at com.facebook.presto.parquet.reader.PrimitiveColumnReader.readPrimitive(PrimitiveColumnReader.java:171)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:209)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:259)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:242)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:246)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:224)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:276)
	at com.facebook.presto.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:267)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.lambda$recordProcessedInput$2(ScanFilterAndProjectOperator.java:308)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:276)
	at com.facebook.presto.spi.block.LazyBlock.getLoadedBlock(LazyBlock.java:267)
	at com.facebook.presto.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.<init>(DictionaryAwarePageProjection.java:97)
	at com.facebook.presto.operator.project.DictionaryAwarePageProjection.project(DictionaryAwarePageProjection.java:75)
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:294)
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:199)
	at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:146)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:49)
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:110)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:293)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:228)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_215____20190301_070204_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

I also get the same error for `IntegerType` as well.

Kindly help

**Comment by zhenxiao** [comment]
looks like a type mismatch, how is ur parquet file being generated? which version of parquet you are using?

**Comment by tooptoop4** [comment]
getting same issue with uber hoodie files
