### ISSUE TITLE
Include Thrift service identity in error message

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#12473]
Currently if Presto failed to connect to a Thrift connector, the stack trace doesn't include any information which Thrift server it is, and what caused the connection error. It will help the user to understand what's going on by including such information in the error message.

A current sample stack trace is like:
```
com.facebook.presto.spi.PrestoException: Error communicating with remote Thrift server
	at com.facebook.presto.connector.thrift.util.ThriftExceptions.toPrestoException(ThriftExceptions.java:43)
	at com.facebook.presto.connector.thrift.util.ThriftExceptions.lambda$catchingThriftException$0(ThriftExceptions.java:50)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:176)
	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:163)
...
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.airlift.drift.protocol.TTransportException: Max retry time (1.00m) exceeded
	at io.airlift.drift.client.DriftMethodInvocation.fail(DriftMethodInvocation.java:325)
	... 53 more
	Suppressed: io.airlift.drift.client.RetriesFailedException: Max retry time (1.00m) exceeded (invocationAttempts: 0, duration: 1.36m, failedConnections: 0, overloadedRejects: 11)
		at io.airlift.drift.client.DriftMethodInvocation.fail(DriftMethodInvocation.java:331)
		... 53 more
```

**Comment by yingsu00** [comment]
@hellium01 @rongrong

**Comment by eladitzhakian** [comment]
Can we reopen this? I'm having difficulties connecting to a working thrift server and the logs don't help. @rongrong
