### ISSUE TITLE
Need to have Custom Split in HiveUtil.createRecorder

### ISSUE THREAD

**Issue by arnaboss** [prestodb/presto#12509]
I am using my custom Input Format which is called at the HiveUtils.createRecorder passing a FileSplit object at https://github.com/prestodb/presto/blob/0cd02a9835f55fa59cca6b7aebfcb5d651214b85/presto-hive/src/main/java/com/facebook/presto/hive/HiveUtil.java#L207

This calls the getRecorder at the custom Input Format and it fails to cast FileSplit to the custom Split. 

Is there any way to pass a custom split at the HiveUtil.createRecorder?

Hi I am still getting this error as below

```
java.lang.ClassCastException: org.apache.hadoop.mapred.FileSplit cannot be cast to amazon.conexio.hive.EDXManifestHiveInputFormat$EDXManifestHiveSplit
	at amazon.conexio.hive.EDXManifestHiveInputFormat.getRecordReader(EDXManifestHiveInputFormat.java:79)
	at com.facebook.presto.hive.HiveUtil.createRecordReader(HiveUtil.java:220)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$0(GenericHiveRecordCursorProvider.java:72)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1824)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at com.facebook.presto.hive.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:39)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:80)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:71)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:187)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:95)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_215____20190318_190434_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is the Input format getRecorder

```
    public RecordReader<BytesWritable, BytesWritable> getRecordReader(final InputSplit split, final JobConf job, final Reporter reporter) throws IOException {
        LOG.info("Getting record reader");

        EDXManifestHiveSplit hiveSplit = (EDXManifestHiveSplit) split;

        JobConf confWithTableProperties = HiveJobConfUtil.copyTablePropertiesToJobConf(job);

        return myFormat.getRecordReader(hiveSplit.mySplit, confWithTableProperties, reporter);
    }
```

and the custom Split as

```
    public static final class EDXManifestHiveSplit extends FileSplit {
        private EDXManifestSplit mySplit;

        public EDXManifestHiveSplit() {
            this(null, null);
        }

        public EDXManifestHiveSplit(final EDXManifestSplit split, final Path tablePath) {
            super(tablePath, 0, 0, (String[]) null);
            mySplit = split;
        }

        /** {@inheritDoc} */
        @Override
        public void write(final DataOutput out) throws IOException {
            super.write(out);
            mySplit.write(out);
        }

        /** {@inheritDoc} */
        @Override
        public void readFields(final DataInput in) throws IOException {
            super.readFields(in);
            mySplit = new EDXManifestSplit();
            mySplit.readFields(in);
        }

        @Override
        public int hashCode() {
            return new HashCodeBuilder(17, 31). // two randomly chosen prime numbers
                    // if deriving: appendSuper(super.hashCode()).
                            append(mySplit).
                            toHashCode();
        }

        @Override
        public boolean equals(Object obj) {
            if (!(obj instanceof EDXManifestHiveSplit))
                return false;
            if (obj == this)
                return true;

            EDXManifestHiveSplit rhs = (EDXManifestHiveSplit) obj;
            return new EqualsBuilder().
                    // if deriving: appendSuper(super.equals(obj)).
                            append(mySplit, rhs.mySplit).
                            isEquals();
        }

        @Override
        public String toString() {
            return "EDXManifestHiveSplit{" +
                    "mySplit=" + mySplit +
                    '}';
        }
    }
```

**Comment by nezihyigitbasi** [comment]
Looks like you are getting help in our mailing list, so closing this one: https://groups.google.com/forum/#!topic/presto-users/oObR8FES_zI
