### ISSUE TITLE
Unknown connector $system@hive

### ISSUE THREAD

**Issue by Xiangakun** [prestodb/presto#12613]
when executing below sql:  select * from hive.default."test_insert_partitioned_table$partitions";  with presto cli of version 0.215, it occurred the error "Query 20190408_082738_00053_eak43 failed: Unknown connector $system@hive", does anyone meet the same error before? It seems I miss some configuration when using the newer version 0.215, but I am not sure what's it and how to fix it. Hope receive your kindly help. 
Note: I tried with presto jdbc and met the same error.

**Comment by Xiangakun** [comment]
Anybody can help with this?

**Comment by tdcmeehan** [comment]
* Does this happen only when querying the $partitions metadata, or any hive table?
* You mention presto jdbc.  Is it the same error when trying to query $partitions metadata on JDBC, or any table on a jdbc connector?
* Can you post the stacktrace?
* You mention a newer version, 0.215.  What version did you upgrade from?

**Comment by Xiangakun** [comment]
Thanks for your reply, followings are my answers.

1. The error only happens when querying the $partitions metadata, it works fine when executes below sql:
select * from hive.default.test_insert_partitioned_table; 

2. It's the same error as cli, and happens only when querying $partitions metadata.

3. Following is the stacktrace:
2019-04-10T19:07:14.253+0800	ERROR	query-execution-195774	com.facebook.presto.execution.QueryStateMachine	Query 20190410_110713_00016_eak43 failed
com.facebook.presto.spi.PrestoException: Unknown connector $system@hive
	at com.facebook.presto.metadata.SessionPropertyManager.getConnectorSessionPropertyMetadata(SessionPropertyManager.java:119)
	at com.facebook.presto.metadata.SessionPropertyManager.decodeCatalogPropertyValue(SessionPropertyManager.java:180)
	at com.facebook.presto.FullConnectorSession.getProperty(FullConnectorSession.java:129)
	at com.facebook.presto.hive.HiveSessionProperties.isForcePartitionValue(HiveSessionProperties.java:460)
	at com.facebook.presto.hive.HivePartitionManager.getPartitions(HivePartitionManager.java:124)
	at com.facebook.presto.hive.HiveMetadata$1.lambda$cursor$2(HiveMetadata.java:361)
	at com.facebook.presto.spi.InMemoryRecordSet.cursor(InMemoryRecordSet.java:60)
	at com.facebook.presto.hive.HiveMetadata$1.cursor(HiveMetadata.java:369)
	at com.facebook.presto.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:124)
	at com.facebook.presto.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
	at com.facebook.presto.spi.RecordPageSource.<init>(RecordPageSource.java:37)
	at com.facebook.presto.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:103)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_215_40_ge09b7c8____20190327_063903_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

4. I upgraded it from version 0.188, as you know, the grammar "table$partitions" was introduced since version 0.199, and the prior grammar "SHOW PARTITIONS" would never be used in version 0.215.

**Comment by tdcmeehan** [comment]
Seems like this is caused by a local code change?  I don't see any `HiveSessionProperties#isForcePartitionValue` in version 0.215:

https://github.com/prestodb/presto/blob/0.215/presto-hive/src/main/java/com/facebook/presto/hive/HiveSessionProperties.java

**Comment by Xiangakun** [comment]
Yes, it's my local code change, I will look into it myself firstly, thanks for your kindly help very much~

**Comment by IElgohary** [comment]
@Xiangakun any updates on this? I' getting the same error but with delta when I query `information_schema.columns`
