### ISSUE TITLE
Nested Fields in Elasticsearch

### ISSUE THREAD

**Issue by jwfcps** [prestodb/presto#12642]
I'm getting an error with nested fields using the elasticsearch connector:

```
java.lang.UnsupportedOperationException
        at com.facebook.presto.spi.block.SingleRowBlockWriter.build(SingleRowBlockWriter.java:207)
        at com.facebook.presto.elasticsearch.ElasticsearchUtils.serializePrimitive(ElasticsearchUtils.java:108)
        at com.facebook.presto.elasticsearch.ElasticsearchUtils.serializeObject(ElasticsearchUtils.java:49)
        at com.facebook.presto.elasticsearch.ElasticsearchUtils.serializeStruct(ElasticsearchUtils.java:74)
        at com.facebook.presto.elasticsearch.ElasticsearchUtils.serializeObject(ElasticsearchUtils.java:44)
        at com.facebook.presto.elasticsearch.ElasticsearchRecordCursor.getObject(ElasticsearchRecordCursor.java:165)
        at com.facebook.presto.$gen.CursorProcessor_20190410_200458_2.project_0(Unknown Source)
        at com.facebook.presto.$gen.CursorProcessor_20190410_200458_2.process(Unknown Source)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processColumnSource(ScanFilterAndProjectOperator.java:242)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:234)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_218____20190410_200445_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Here is my table schema:

```
{
    "tableName": "winlogbeat_m",
    "schemaName": "elk",
    "host": "elkcoord01",
    "port": 9300,
    "clusterName": "ELK",
    "index": "winlogbeat-6.4.0-2019.04.09",
    "indexExactMatch": false,
    "type": "doc",
    "columns": [
        {
            "jsonType":  "varchar",
            "name":  "@timestamp",
            "jsonPath":  "@timestamp",
            "type":  "varchar"
        },
        {
            "jsonType":  "varchar",
            "name":  "event_id",
            "jsonPath":  "event_id",
            "type":  "varchar"
        },
        {
            "jsonType":  "object",
            "name":  "beat",
            "jsonPath":  "beat",
            "type":  "ROW(hostname varchar)"
        }
    ]
}
```

It seems that it was working at some point:
https://github.com/prestodb/presto/pull/12057#issuecomment-457953279

A slack conversation with @zhenxiao confirmed there is an issue.

**Comment by jwfcps** [comment]
This fixes my issue, but if ElasticsearchRecordCursor ever calls it with an actual primitive the null return will probably cause an exception.  Though I'm not sure why you'd have an object type just contain a single serialized primitive.

```
--- a/presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/ElasticsearchUtils.java
+++ b/presto-elasticsearch/src/main/java/com/facebook/presto/elasticsearch/ElasticsearchUtils.java
@@ -46,7 +46,8 @@ public final class ElasticsearchUtils
         if (MAP.equals(type.getTypeSignature().getBase()) || ARRAY.equals(type.getTypeSignature().getBase())) {
             throw new IllegalArgumentException("Type not supported: " + type.getDisplayName());
         }
-        return serializePrimitive(type, builder, object);
+        serializePrimitive(type, builder, object);
+        return null;
     }
 
     private static Block serializeStruct(Type type, BlockBuilder builder, Object object)
@@ -78,13 +79,13 @@ public final class ElasticsearchUtils
         return (Block) type.getObject(builder, 0);
     }
 
-    private static Block serializePrimitive(Type type, BlockBuilder builder, Object object)
+    private static void serializePrimitive(Type type, BlockBuilder builder, Object object)
     {
         requireNonNull(builder, "builder is null");
 
         if (object == null) {
             builder.appendNull();
-            return builder.build();
+            return;
         }
 
         if (type.equals(BOOLEAN)) {
@@ -105,6 +106,6 @@ public final class ElasticsearchUtils
         else {
             throw new IllegalArgumentException("Unknown primitive type: " + type.getDisplayName());
         }
-        return builder.build();
+        return;
     }
 }
```

**Comment by wenleix** [comment]
cc @zhenxiao

**Comment by wenleix** [comment]
Thanks @jwfcps  for reporting the issue. I talked with @zhenxiao (one of the main community maintainer for Elasticsearch) , and he will take a look once he is back from vacation. Feel free to ping us if you didn't hear back in two weeks.

**Comment by zhenxiao** [comment]
@jwfcps could you please submit a PR? I am happy to review. We could follow the discussion there. It would be nice to add testcases for nested fields for Elasticsearch Connector.
