### ISSUE TITLE
Remote page is too large

### ISSUE THREAD

**Issue by pgoggijr** [prestodb/presto#12717]
Running Presto v.206 on EMR v5.17

Getting the following exception when querying data with a limit of 200:
```
com.facebook.presto.operator.PageTooLargeException: Remote page is too large
	at com.facebook.presto.operator.HttpPageBufferClient.rewriteException(HttpPageBufferClient.java:534)
	at com.facebook.presto.operator.HttpPageBufferClient.access$1800(HttpPageBufferClient.java:88)
	at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:403)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The tasks complete successfully on all nodes but one. looking at the logs on that node I see:

```
2019-04-23T19:56:56.735Z        INFO    page-buffer-client-callback-35  stderr  Exception in thread "page-buffer-client-callback-35"
2019-04-23T19:56:56.735Z        INFO    page-buffer-client-callback-35  stderr  com.facebook.presto.operator.PageTooLargeException: Remote page is too large
2019-04-23T19:56:56.735Z        ERROR   SplitRunner-254-1260314 com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-4  (start = 1.0863463535823208E10, wall = 1669 ms, cpu = 1 ms, wait = 1 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.735Z        ERROR   SplitRunner-187-738643  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-3  (start = 1.086346353579229E10, wall = 1670 ms, cpu = 3 ms, wait = 0 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.735Z        ERROR   SplitRunner-235-973197  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-7  (start = 1.086346353591828E10, wall = 1670 ms, cpu = 1 ms, wait = 1 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.735Z        INFO    page-buffer-client-callback-35  stderr          at com.facebook.presto.operator.HttpPageBufferClient.rewriteException(HttpPageBufferClient.java:534)
2019-04-23T19:56:56.736Z        INFO    page-buffer-client-callback-35  stderr          at com.facebook.presto.operator.HttpPageBufferClient.access$1800(HttpPageBufferClient.java:88)
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-212-700269  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-8  (start = 1.086346353596868E10, wall = 1670 ms, cpu = 1 ms, wait = 4 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-233-949929  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-9  (start = 1.086346353600873E10, wall = 1670 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-250-1141927 com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-10  (start = 1.0863463536031605E10, wall = 1670 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-237-973119  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-11  (start = 1.086346353612612E10, wall = 1669 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        INFO    page-buffer-client-callback-35  stderr          at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:403)
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-193-802642  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-6  (start = 1.0863463535892685E10, wall = 1670 ms, cpu = 1 ms, wait = 1 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        INFO    page-buffer-client-callback-35  stderr          at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-243-1043093 com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-1  (start = 1.0863463535723215E10, wall = 1670 ms, cpu = 3 ms, wait = 0 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        INFO    page-buffer-client-callback-35  stderr          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-04-23T19:56:56.736Z        INFO    page-buffer-client-callback-35  stderr          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-241-1034656 com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-5  (start = 1.0863463535862726E10, wall = 1670 ms, cpu = 1 ms, wait = 1 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-215-839266  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-12  (start = 1.0863463536176275E10, wall = 1670 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        INFO    page-buffer-client-callback-35  stderr          at java.lang.Thread.run(Thread.java:748)
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-254-1260314 com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-13  (start = 1.0863463536269361E10, wall = 1670 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-237-973119  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-14  (start = 1.0863463536317068E10, wall = 1670 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-223-736063  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-2  (start = 1.0863463535750906E10, wall = 1670 ms, cpu = 2 ms, wait = 0 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-156-708674  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-0  (start = 1.086346353570312E10, wall = 1670 ms, cpu = 5 ms, wait = 0 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.736Z        ERROR   SplitRunner-212-700269  com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20190423_195654_48233_ngupz.0.0-15  (start = 1.086346353635036E10, wall = 1670 ms, cpu = 1 ms, wait = 5 ms, calls = 7): PAGE_TOO_LARGE: Remote page is too large
2019-04-23T19:56:56.737Z        INFO    page-buffer-client-callback-30  stderr  Exception in thread "page-buffer-client-callback-30"
2019-04-23T19:56:56.737Z        INFO    page-buffer-client-callback-30  stderr  com.facebook.presto.operator.PageTooLargeException: Remote page is too large
2019-04-23T19:56:56.737Z        INFO    page-buffer-client-callback-30  stderr          at com.facebook.presto.operator.HttpPageBufferClient.rewriteException(HttpPageBufferClient.java:534)
2019-04-23T19:56:56.737Z        INFO    page-buffer-client-callback-30  stderr          at com.facebook.presto.operator.HttpPageBufferClient.access$1800(HttpPageBufferClient.java:88)
2019-04-23T19:56:56.737Z        INFO    page-buffer-client-callback-30  stderr          at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:403)
2019-04-23T19:56:56.738Z        INFO    page-buffer-client-callback-30  stderr          at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1341)
2019-04-23T19:56:56.738Z        INFO    page-buffer-client-callback-30  stderr          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-04-23T19:56:56.738Z        INFO    page-buffer-client-callback-30  stderr          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-04-23T19:56:56.738Z        INFO    page-buffer-client-callback-30  stderr          at java.lang.Thread.run(Thread.java:748)
```

The query is not doing any joins, it's simply applying filtering logic and a limit 200 (there would be ~8000 records without a limit) on a single table backed by orc files in HDFS.

I also _do not_ encounter this error when I exclude the LIMIT clause of my query, which seems curious.

Are there any known configuration changes that can help with this behavior?

**Comment by wenleix** [comment]
Usually it means there is single row too large (thinking about huge array / map or even varchar ) :)

**Comment by pgoggijr** [comment]
@wenleix thanks for the response.  Might be on the right track because there _are_ a few arrays in this schema.  I have tracked it down to a single array column that I believe might be the culprit, but that leaves me with another question:

Why would removing the LIMIT clause allow the query to succeed if that were the case?

**Comment by wenleix** [comment]
@pgoggijr : The query might finish before these huge arrays encountered :)

**Comment by pgoggijr** [comment]
@wenleix I only encounter the issue when I DO include LIMIT. When there is no LIMIT clause, and I materialize all rows that match the filter, I do not encounter the error. So the row must be encountered in this case

**Comment by yingsu00** [comment]
@pgoggijr By adding LIMIT a new limit phase would be added to the plan, maybe that's the reason you only see it with LIMIT. Also, is it possible to add a repro to this issue with synthesized data?

**Comment by pgoggijr** [comment]
@yingsu00 
I'm still trying to reproduce with synthesized data, no luck yet.

I also found that if I add an ORDER BY, I can keep the LIMIT.  Doesn't matter what column I order by or which direction

**Comment by wenleix** [comment]
@pgoggijr : Ah. Sorry, I misread your previous comments. 

A use case that reproduce the issue definitely helps us to look into the issue. But sounds like it's not easy to reproduce it with a toy dataset. 

Can you share the plan with and without limit? (and has the issue vs. not having the issue). 

We are discussing how to solve the root cause, cc @highker, @arhimondr . In the meanwhile, one workaround will be to filter out rows with huge arrays?

**Comment by xingnailu** [comment]
same error~  presto version is 0.203. Has the later version been fixed? @wenleix
