### ISSUE TITLE
Failing runtime assertion: "Driver should never block"

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#12826]
```
java.lang.IllegalStateException: Driver should never block
	at com.google.common.base.Preconditions.checkState(Preconditions.java:504)
	at com.facebook.presto.operator.index.IndexLoader$IndexSnapshotLoader.load(IndexLoader.java:337)
	at com.facebook.presto.operator.index.IndexLoader.getIndexedDataForKeys(IndexLoader.java:180)
	at com.facebook.presto.operator.index.IndexLoader.getIndexedDataForKeys(IndexLoader.java:158)
	at com.facebook.presto.operator.index.IndexLookupSource.getJoinPosition(IndexLookupSource.java:83)
	at com.facebook.presto.operator.index.IndexLookupSource.getJoinPosition(IndexLookupSource.java:74)
	at com.facebook.presto.operator.JoinProbe.getCurrentJoinPosition(JoinProbe.java:87)
	at com.facebook.presto.operator.LookupJoinOperator.advanceProbePosition(LookupJoinOperator.java:565)
	at com.facebook.presto.operator.LookupJoinOperator.processProbe(LookupJoinOperator.java:478)
	at com.facebook.presto.operator.LookupJoinOperator.lambda$processProbe$3(LookupJoinOperator.java:399)
	at com.facebook.presto.operator.StaticLookupSourceProvider.withLease(StaticLookupSourceProvider.java:34)
	at com.facebook.presto.operator.LookupJoinOperator.processProbe(LookupJoinOperator.java:396)
	at com.facebook.presto.operator.LookupJoinOperator.getOutput(LookupJoinOperator.java:311)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_219____20190514_204259_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by rschlussel** [comment]
@nezihyigitbasi do you have more info about when this error occurs.  Is it deterministic/is there a query to reproduce it?

**Comment by nezihyigitbasi** [comment]
Will provide you more info, but I don't have a simple query to repro.

**Comment by rschlussel** [comment]
This looks like a race condition with index joins.

**Comment by rschlussel** [comment]
@hellium01 explained that this was because index joins were written before yield was implemented.  when the server for the index join is slow, this can happen.

**Comment by rschlussel** [comment]
@hellium01 and I discussed.  The problem is that the IndexLoader doesn't expect the index lookup to block.  The driver depends on the index scan, which runs for a 1s quanta.  if it doesn't complete in that time (e.g. the index server is slow), the task is considered blocked. 

The easiest solution would be to wait for the output of the index loader for up to some timeout amount of time.
