### ISSUE TITLE
"inputFormat should not be accessed from a null StorageFormat" is categorized as "HIVE_UNKNOWN_ERROR"

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#12887]
Stacktrace:

```
java.util.concurrent.CompletionException: com.facebook.presto.spi.PrestoException: inputFormat should not be accessed from a null StorageFormat
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1004)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2307)
	at com.facebook.presto.hive.PrismSplitManager$PrismSplitSource.getNextBatch(PrismSplitManager.java:74)
	at com.facebook.presto.split.ConnectorAwareSplitSource.getNextBatch(ConnectorAwareSplitSource.java:64)
	at com.facebook.presto.split.BufferingSplitSource$GetNextBatch.fetchSplits(BufferingSplitSource.java:119)
	at com.facebook.presto.split.BufferingSplitSource$GetNextBatch.lambda$fetchSplits$1(BufferingSplitSource.java:126)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:211)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:111)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:868)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:691)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:160)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:868)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:691)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:48)
	at io.airlift.concurrent.MoreFutures.lambda$toListenableFuture$11(MoreFutures.java:490)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.airlift.concurrent.MoreFutures$2.onSuccess(MoreFutures.java:462)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1347)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:868)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:691)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:160)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:868)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:691)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:160)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:868)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:691)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.setResult(AbstractTransformFuture.java:245)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:160)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.facebook.presto.spi.PrestoException: inputFormat should not be accessed from a null StorageFormat
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:194)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	... 4 more
Caused by: java.lang.IllegalStateException: inputFormat should not be accessed from a null StorageFormat
	at com.facebook.presto.hive.metastore.StorageFormat.getInputFormat(StorageFormat.java:54)
	at com.facebook.presto.hive.metastore.MetastoreUtil.getHiveSchema(MetastoreUtil.java:103)
	at com.facebook.presto.hive.metastore.MetastoreUtil.getHiveSchema(MetastoreUtil.java:79)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.getPartitionSchema(BackgroundHiveSplitLoader.java:535)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:277)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:258)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:93)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:187)
	... 7 more
```

**Comment by wenleix** [comment]
This is fixed by https://github.com/prestodb/presto/pull/12973 as a by-product.
