### ISSUE TITLE
Elasticsearch connector: schemaName not optional

### ISSUE THREAD

**Issue by fastcatch** [prestodb/presto#12898]
(split from #12880)
In *table definition* files the **`schemaName` is not optional** - though supposedly it should be as per the documentation and also as per standard logic.  If `schemaName`  is not defined in the table definition presto fails to start with `[...] java.lang.IllegalArgumentException: schemaName is null or empty [...]`. 

Details:

Relevant files:
`etc/catalog/elasticsearch.properties` (especially note: `elasticsearch.default-schema-name`)
```
connector.name=elasticsearch
elasticsearch.default-schema-name=default
elasticsearch.table-description-directory=etc/elasticsearch/
elasticsearch.scroll-size=1000
elasticsearch.scroll-timeout=1m
elasticsearch.request-timeout=2s
elasticsearch.max-request-retries=5
elasticsearch.max-request-retry-time=10s
elasticsearch.max-hits=100000000
```

With `etc/elasticsearch/sample_ok.json` being
```
{
    "tableName": "prestodebug",
    "schemaName": "default",
    "host": "127.0.0.1",
    "port": 9300,
    "clusterName": "docker-cluster",
    "index": "prestodebug",
    "indexExactMatch": true,
    "type": "_doc",
    "columns": [
        {
            "name":"col1",
            "type": "varchar",
            "jsonPath": "col1",
            "jsonType": "varchar",
            "ordinaryPosition":"0"
        }
    ]
}
```
presto starts fine.   (NB: Real host IP is masked for security.)

However, removing the `"schemaName": "default"` attribute (which should be redundant in that its default is defined in the properties file) results in presto starting with a huge exception (literally some 1500 lines, only the last portion is copied here):
```
[...]
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.prestosql.elasticsearch.ElasticsearchTableDescription`, problem: schemaName is null or empty
 at [Source: (byte[])"

{
    "tableName": "prestodebug",
    "host": "127.0.0.1",
    "port": 9300,
    "clusterName": "docker-cluster",
    "index": "prestodebug",
    "indexExactMatch": true,
    "type": "_doc",
    "columns": [
        {
            "name":"col1",
            "type": "varchar",
            "jsonPath": "col1",
            "jsonType": "varchar",
            "ordinaryPosition":"0"
        }
    ]
}
"; line: 20, column: 1]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3121)
        at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:193)
        ... 30 more
Caused by: java.lang.IllegalArgumentException: schemaName is null or empty
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at io.prestosql.elasticsearch.ElasticsearchTableDescription.<init>(ElasticsearchTableDescription.java:52)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
        ... 39 more

5 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
        at io.prestosql.elasticsearch.ElasticsearchConnectorFactory.create(ElasticsearchConnectorFactory.java:67)
        ... 8 more
```

**Comment by wenleix** [comment]
cc @zhenxiao

**Comment by zhenxiao** [comment]
nice catch, will take a look
