### ISSUE TITLE
IN subquery does not add implicit coercions

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#1292]
This query should return work but throws an error due to the missing implicit coercion:

```
select 1.0 in (values (1),(2), (3));
```

**Comment by yuananf** [comment]
I can take this.
Should it fail with an error ```type mismatch for In value and valuelist```, or should it success and add coercion?

**Comment by kokosing** [comment]
Currently above query returns different error:
```
presto> select 1.0 in (values (1),(2), (3));

Query 20151028_130949_00011_n3vd7, FAILED, 1 node
Splits: 4 total, 0 done (0,00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20151028_130949_00011_n3vd7 failed: $operator$EQUAL(double,bigint):boolean not found
```

This error is raised during the planning: 
```
com.facebook.presto.spi.PrestoException: $operator$EQUAL(double,bigint):boolean not found
	at com.facebook.presto.util.Failures.checkCondition(Failures.java:75)
	at com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:596)
	at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:128)
	at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:68)
	at com.facebook.presto.sql.relational.CallExpression.accept(CallExpression.java:88)
	at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.lambda$visitCall$285(ExpressionOptimizer.java:124)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:125)
	at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:68)
	at com.facebook.presto.sql.relational.CallExpression.accept(CallExpression.java:88)
	at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer.optimize(ExpressionOptimizer.java:65)
	at com.facebook.presto.sql.relational.SqlToRowExpressionTranslator.translate(SqlToRowExpressionTranslator.java:124)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.toRowExpression(LocalExecutionPlanner.java:983)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:890)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:823)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:410)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
...
```
@cberner @dain So it looks like as it is already fixed and can be closed if I not missed anything.

**Comment by kokosing** [comment]
@sopel39 I am assigning this one to you, as it looks like you were working on something really close to it recently. So probably you already solved this.

**Comment by losipiuk** [comment]
@sopel39 Is that still relevant. Please close if this is no longer an issue.
