### ISSUE TITLE
information_schema.schemata table not found

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#12944]
this query gives error in presto 0.220:
`select * from hive.information_schema.table_privileges limit 1`

stack trace:

```
com.facebook.presto.spi.PrestoException: information_schema.schemata table not found
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.listTablePrivileges(ThriftHiveMetastore.java:1279)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.listTablePrivileges(BridgingHiveMetastore.java:349)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTablePrivileges(CachingHiveMetastore.java:733)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:190)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:219)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.listTablePrivileges(CachingHiveMetastore.java:728)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTablePrivileges(CachingHiveMetastore.java:733)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.lambda$new$0(CachingHiveMetastore.java:190)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:219)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.listTablePrivileges(CachingHiveMetastore.java:728)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.listTablePrivileges(SemiTransactionalHiveMetastore.java:838)
	at com.facebook.presto.hive.HiveMetadata.buildGrants(HiveMetadata.java:2183)
	at com.facebook.presto.hive.HiveMetadata.listTablePrivileges(HiveMetadata.java:2173)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.listTablePrivileges(ClassLoaderSafeConnectorMetadata.java:574)
	at com.facebook.presto.metadata.MetadataManager.listTablePrivileges(MetadataManager.java:1120)
	at com.facebook.presto.metadata.MetadataListing.listTablePrivileges(MetadataListing.java:79)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildTablePrivileges(InformationSchemaPageSourceProvider.java:196)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:128)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:110)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:80)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_220____20190611_125634_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result$get_table_resultStandardScheme.read(ThriftHiveMetastore.java:35066)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result$get_table_resultStandardScheme.read(ThriftHiveMetastore.java:35034)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result.read(ThriftHiveMetastore.java:34965)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table(ThriftHiveMetastore.java:1218)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table(ThriftHiveMetastore.java:1204)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastoreClient.getTable(ThriftHiveMetastoreClient.java:148)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$listTablePrivileges$51(ThriftHiveMetastore.java:1251)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:139)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.listTablePrivileges(ThriftHiveMetastore.java:1249)
	... 52 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
	Suppressed: org.apache.hadoop.hive.metastore.api.NoSuchObjectException: information_schema.schemata table not found
		... 63 more
```

**Comment by mbasmanova** [comment]
This issues reproduces with the following test in `TestHiveIntegrationSmokeTest`:

```
    @Test
    public void test()
    {
        assertQuerySucceeds(getQueryRunner().getDefaultSession(), "select * from hive.information_schema.table_privileges limit 1");
    }

com.facebook.presto.spi.TableNotFoundException: Table 'information_schema.schemata' not found
	at com.facebook.presto.hive.metastore.file.FileHiveMetastore.lambda$getRequiredTable$5(FileHiveMetastore.java:329)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.presto.hive.metastore.file.FileHiveMetastore.getRequiredTable(FileHiveMetastore.java:329)
	at com.facebook.presto.hive.metastore.file.FileHiveMetastore.listTablePrivileges(FileHiveMetastore.java:948)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadTablePrivileges(CachingHiveMetastore.java:733)
```

@arhimondr @highker @wenleix Anyone knows what might be wrong?

**Comment by mbasmanova** [comment]
@rschlussel Rebecca, do you happen to know why this might be failing?

**Comment by ebyhr** [comment]
I think this is caused by case sensitivity. The schemata is stored as uppercase on hive metastore.
