### ISSUE TITLE
Aggregate over unpartitioned source is not yet supported by materialized exchange 

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#13003]
```
presto:tpch> set session exchange_materialization_strategy='ALL';
SET SESSION
presto:tpch> select orderkey, max(totalprice) from orders group by 1;
Query 20190624_194310_00018_btfzz failed: precomputed hashes are not supported in materializing exchanges
java.lang.IllegalArgumentException: precomputed hashes are not supported in materializing exchanges
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.createRemoteMaterializedExchange(PlanFragmenter.java:510)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:468)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:307)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:282)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:464)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:307)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:282)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitAggregation(InternalPlanVisitor.java:29)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:201)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.buildSubPlan(PlanFragmenter.java:738)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.createRemoteStreamingExchange(PlanFragmenter.java:490)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:466)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:307)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:282)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
```

Related to https://github.com/prestodb/presto/issues/12387

**Comment by arhimondr** [comment]
Most likely it was due to misconfiguration.

This PR tries to address ambiguous error messages you have faced: https://github.com/prestodb/presto/pull/13085
