### ISSUE TITLE
GENERIC_INTERNAL_ERROR: String index out of range when using multibyte string in date_format's format

### ISSUE THREAD

**Issue by shigemk2** [prestodb/presto#13022]
I had an error when executing this query.

```sql
SELECT DATE_FORMAT(now() AT TIME ZONE 'Asia/Tokyo', '%Y年%m月%d日')
```

I know the solution is not using multibyte string in date_format's format, but I want to know the reason.

https://github.com/prestodb/presto/blob/28ec8f43fec01a6cd7bdec2d48852bf133ad2896/presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java#L667-L685

**Comment by ebyhr** [comment]
The root cause is here.
https://github.com/prestodb/presto/blob/28ec8f43fec01a6cd7bdec2d48852bf133ad2896/presto-main/src/main/java/com/facebook/presto/operator/scalar/DateTimeFunctions.java#L1173-L1180

**Comment by ebyhr** [comment]
> I know the solution is not using multibyte string in date_format's format, but I want to know the reason.

The reason is L1179 uses byte length as the exit condition, but L1180 uses chartAt. Thus, the for loop tries to access missing index.

When you face the issue in Presto, the stacktrace will be helpful. You can get it from Web UI or CLI's --debug option. In this case, we can get below stacktrace.
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 9
        at java.lang.String.charAt(String.java:658)
        at com.facebook.presto.operator.scalar.DateTimeFunctions.createDateTimeFormatter(DateTimeFunctions.java:1180)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
        at io.airlift.concurrent.ThreadLocalCache.get(ThreadLocalCache.java:45)
        at com.facebook.presto.operator.scalar.DateTimeFunctions.dateFormat(DateTimeFunctions.java:680)
        at com.facebook.presto.operator.scalar.DateTimeFunctions.dateFormatWithTimeZone(DateTimeFunctions.java:675)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649)
        at com.facebook.presto.sql.InterpretedFunctionInvoker.invoke(InterpretedFunctionInvoker.java:99)
        at com.facebook.presto.sql.InterpretedFunctionInvoker.invoke(InterpretedFunctionInvoker.java:51)
        at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:891)
        at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:267)
        at com.facebook.presto.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:56)
        at com.facebook.presto.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:80)
        at com.facebook.presto.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0(ExpressionRewriteRuleSet.java:129)
        at com.facebook.presto.sql.planner.plan.AssignmentUtils.lambda$rewrite$1(AssignmentUtils.java:84)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.planner.plan.AssignmentUtils.rewrite(AssignmentUtils.java:85)
        at com.facebook.presto.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:129)
        at com.facebook.presto.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.apply(ExpressionRewriteRuleSet.java:110)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:166)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:139)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:104)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:186)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:95)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:183)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:172)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:425)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:410)
        at com.facebook.presto.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:354)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by shigemk2** [comment]
Thank you for your comment.

I think this is Presto's bug.

Is this worth to fix this bug?

**Comment by ebyhr** [comment]
Yes, it's Presto's bug (not library's). Sent PR to fix this issue. https://github.com/prestodb/presto/pull/13031
