### ISSUE TITLE
response 500 error

### ISSUE THREAD

**Issue by axzhcode** [prestodb/presto#13060]
exception: 
```
uncategorized SQLException; SQL state [null]; error code [0]; Error executing query; nested exception is java.sql.SQLException: Error executing query
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:73)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy121.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:222)
	at com.zmlearn.bigdata.framework.core.jdbc.presto.PrestoMapper.selectList(PrestoMapper.java:122)
	at com.zmlearn.bigdata.framework.core.jdbc.presto.PrestoMapper.selectCount(PrestoMapper.java:59)
	at com.zmlearn.bigdata.framework.core.jdbc.presto.PrestoMapper$$FastClassBySpringCGLIB$$c536bfad.invoke(<generated>)
Caused by: java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:279)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228)
	at com.facebook.presto.jdbc.PrestoPreparedStatement.<init>(PrestoPreparedStatement.java:80)
	at com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:128)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:312)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:87)
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
Caused by: java.lang.RuntimeException: Error fetching next at http://ip:port/v1/statement/20190704_121456_03990_zuq3g/1 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Server Error, headers={connection=[close]}, hasValue=false} [Error: ]
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:458)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.advance(StatementClientV1.java:397)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1742)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:119)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:250)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228)
	at com.facebook.presto.jdbc.PrestoPreparedStatement.<init>(PrestoPreparedStatement.java:80)
	at com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:128)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:312)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
```

like https://github.com/prestosql/presto/issues/628
but prestodb restart error: 
```
Configuration property 'http-server.max-response-header-size' was not used
```

**Comment by rongrong** [comment]
We haven't upgraded airlift library to the version that adds support for `http-server.max-response-header-size` yet so this config is currently not available. We will upgrade it to include this in next release. In the meanwhile, you can change the version of airlift to 0.181 in pom.xml to enable this.

**Comment by axzhcode** [comment]
@rongrong ok

**Comment by axzhcode** [comment]
@rongrong Does it have other solutions?
