### ISSUE TITLE
Presto0.221 occours jdbc error

### ISSUE THREAD

**Issue by daren990** [prestodb/presto#13080]
`2019-07-11T08:08:15.642+0800    ERROR   20190711_000814_00000_9xezp.1.0-0-109   com.facebook.presto.operator.Driver
Error closing operator 0 for task 20190711_000814_00000_9xezp.1.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:899)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6679)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
        at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:185)
        at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:174)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:546)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:406)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_null__testversion____20190711_000756_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

2019-07-11T08:08:16.039+0800    INFO    query-execution-2       com.facebook.presto.event.QueryMonitor  TIMELINE: Query 20190711_000814_00000_9xezp :: Transaction:[537ab344-7631-4135-81e6-54e51fbff935] :: elapsed 1280ms :: planning 260ms :: scheduling 686ms :: running 197ms :: finishing 137ms :: begin 2019-07-11T08:08:14.616+08:00 :: end 2019-07-11T08:08:15.896+08:00`

**Presto Server console shows errors as above;
I 'v got the right result but at the same time ,the server console shows errors;

DB: MYSQL 5.6   Presto Version: 0.221

The client code as below:**
` Connection connection = DriverManager.getConnection("jdbc:presto://127.0.0.1:8080", "root", null);`
        `connection.setCatalog("mysql");`
       ` Statement stmt = connection.createStatement();`
        `ResultSet rs = stmt.executeQuery("select * from mysql.ea.hold");`
       ` while (rs.next()) {`
            `System.out.println(rs.getString(1)`
                 `   +"-"+rs.getString(2)`
                   ` +"-"+rs.getString(3)`
                   ` +"-"+rs.getString(4)`
                   ` +"-"+rs.getString(5)`
                   ` +"-"+rs.getString(6)`
                   ` +"-"+rs.getString(7)`
                    `+"-"+rs.getString(8)`
                    `+"-"+rs.getString(9));`
       ` }`
     ` rs.close();`
        `connection.close();`

**Comment by daren990** [comment]
I'v found the cause,I fixed it,
the reason is  "try-with-resources" cluase,we should close the resources by order instead of using " try-with-resources" cluase to close it;
I found the source code is 

`try (Connection connection = this.connection;`
`               Statement statement = this.statement;`
`               ResultSet resultSet = this.resultSet) {`

**Comment by CCColby** [comment]
> I'v found the cause,I fixed it, the reason is "try-with-resources" cluase,we should close the resources by order and check if it is already closed or not instead of using " try-with-resources" cluase to close it; I found the source code is
> 
> `try (Connection connection = this.connection;` ` Statement statement = this.statement;` ` ResultSet resultSet = this.resultSet) {`

I also meet this problem, how to fixs it? thanks!
