### ISSUE TITLE
presto jdbc execute long sql got error "Request Header Fields Too Large"

### ISSUE THREAD

**Issue by dandanmaowu** [prestodb/presto#13097]
i have a sql is not too long, only 300 lines, 7000 words,  when this sql execute using JDBC , got an error...

`        Class.forName("com.facebook.presto.jdbc.PrestoDriver");

        String url = "jdbc:presto://master:9000/hive/default";
        Connection con = DriverManager.getConnection(url, "admin", "");

        String sql = IOUtils.toString(new FileInputStream("test.sql"), Charset.forName("utf8"));
        System.out.println("sql length:" + sql.length());

        PreparedStatement pre = con.prepareStatement(sql);

        ResultSet rs = pre.executeQuery();

        int count = rs.getMetaData().getColumnCount();
        while (rs.next()) {
            for (int i = 1; i <= count; i++) {
                System.out.print(rs.getString(i));
                if (i < count) {
                    System.out.print("\t");
                }
            }
            System.out.println();
        }

        con.close();`

`Exception in thread "main" java.sql.SQLException: Error executing query
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:279)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:228)
	at com.facebook.presto.jdbc.PrestoPreparedStatement.executeQuery(PrestoPreparedStatement.java:95)
	at com.test.jdbc.TestPresto.main(TestPresto.java:309)
Caused by: java.lang.RuntimeException: Error starting query at http://xx.xx.xx.xx:9000/v1/statement returned an invalid response: JsonResponse{statusCode=431, statusMessage=Request Header Fields Too Large, headers={connection=[close], content-length=[74], content-type=[text/html;charset=iso-8859-1]}, hasValue=false} [Error: <h1>Bad Message 431</h1><pre>reason: Request Header Fields Too Large</pre>]
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:458)
	at com.facebook.presto.jdbc.internal.client.StatementClientV1.<init>(StatementClientV1.java:135)
	at com.facebook.presto.jdbc.internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
	at com.facebook.presto.jdbc.QueryExecutor.startQuery(QueryExecutor.java:46)
	at com.facebook.presto.jdbc.PrestoConnection.startQuery(PrestoConnection.java:701)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:240)
	... 3 more`

**reason: Request Header Fields Too Large**

I thought increasing this parameter would solve the problem
`http-server.max-request-header-size=32MB`
but it didn't work...

What's interesting is that when I use the command line to execute, the sql works fine
`./presto --server master:9000 --catalog hive --schema default`

How to solve this problem?????

**Comment by dandanmaowu** [comment]
@tdcmeehan

**Comment by tooptoop4** [comment]
@dandanmaowu did u solve?

**Comment by wwyzxb** [comment]
Add the params 'http-server.max-request-header-size=5MB' in config.properties on coordinator  solved my problem!

**Comment by Abdillah** [comment]
This should be added to the documentation somewhere.
