### ISSUE TITLE
Flaky Test TestHiveRecoverableGroupedExecution

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#13108]
```
[ERROR] testCreateBucketedTable(com.facebook.presto.hive.TestHiveRecoverableGroupedExecution)  Time elapsed: 60.04 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.hive.TestHiveRecoverableGroupedExecution.testCreateBucketedTable() didn't finish within the time-out 60000
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:131)
	at com.facebook.presto.client.StatementClientV1.advance(StatementClientV1.java:383)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:92)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:391)
	at com.facebook.presto.hive.TestHiveRecoverableGroupedExecution.testRecoverableGroupedExecution(TestHiveRecoverableGroupedExecution.java:194)
	at com.facebook.presto.hive.TestHiveRecoverableGroupedExecution.testCreateBucketedTable(TestHiveRecoverableGroupedExecution.java:103)
```

**Comment by shixuan-fan** [comment]
Thanks for reporting. I'll try to reproduce locally and see how we could improve the test.

**Comment by rschlussel** [comment]
disabled for now in #13145

**Comment by shixuan-fan** [comment]
Cross posting this comment for stacktraces that might be useful for deflaking effort.

**Comment by rschlussel** [comment]
this was fixed a while back and the test is no longer disabled.
