### ISSUE TITLE
UnknownHostException with hive-hadoop2

### ISSUE THREAD

**Issue by Ethan-Ma** [prestodb/presto#13114]
Hi team,
I set up a single machine , it works well. 
But when adding one worker, it will get an error exception: java.net.UnknownHostException: nameservice2.
#I replace the uri with * for secrecy

the following is the run log:
2019-07-23T15:44:36.395+0800	ERROR	SplitRunner-73-122	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20190723_074430_00001_7vs9q.6.0-0 {path=hdfs://nameservice2/***************************************} (start = 4.314105898196037E9, wall = 163 ms, cpu = 0 ms, wait = 538 ms, calls = 1)
java.lang.IllegalArgumentException: java.net.UnknownHostException: nameservice2
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:320)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:119)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:89)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:62)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:65)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:187)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:95)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:221)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_221____20190723_074230_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: nameservice2 

my hive.properties like following:
▽
connector.name=hive-hadoop2
hive.metastore.uri=thrift://********    #I replace the uri with * for secrecy
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml,/etc/hadoop/conf/mapred-site.xml
hive.allow-add-column=true
hive.allow-drop-column=true
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.allow-rename-column=true
hive.parquet.use-column-names=true

Can anyone help me？
thanks！

**Comment by shixuan-fan** [comment]
My very initial investigation to the stacktrace suggests that the ip address for the address is null, which leads to the error.

**Comment by shixuan-fan** [comment]
What does your node.properties look like?

**Comment by Ethan-Ma** [comment]
> What does your node.properties look like on coordinator and worker?

my node.properties on coordinator and worker, as follows:
node.environment=production
node.id=6c0599b4-e701-4f44-976f-ca93648b28c0
node.data-dir=/software/servers/presto/data

The address you mentioned is the _discovery.uri_ in config.properties or somewhere else?
