### ISSUE TITLE
Multiplying bigint column by a double decimal value causes IllegalArgumentException (cast error)

### ISSUE THREAD

**Issue by owenlynch** [prestodb/presto#13150]
Hi,
I am testing with presto V 0.221.
We have many queries that multiply values by say "100.0" that used to automatically cast to double - these were working fine in presto versions up to 0.179.

Now testing our application against v0.221 and we running in to trouble for several query types.

Perhaps there is a property setting that allows this cast to happen automatically?

for example, given the table:

```
> desc test_table;
            Column            |  Type   |     Extra     | Comment 
------------------------------+---------+---------------+---------
 timeid                       | varchar |               |         
 var1                | bigint  |               |         
 var2                | double  |               |         
```

The following works on Hive and older versions of presto:

```
select 100.0*var1 from test_table;
```

now however it yields an error:
 `Query 20190730_151531_01326_msrmq failed: java.lang.IllegalArgumentException`

Issue may be in `FunctionManager`

Full stack trace from logs:

```
2019-07-30T16:15:32.299+0100    ERROR   remote-task-callback-2309       com.facebook.presto.execution.StageStateMachine Stage 20190730_151531_01326_msrmq.1 failed
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2052)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3943)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3967)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4952)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4958)
        at com.facebook.presto.metadata.StaticFunctionNamespace.getScalarFunctionImplementation(StaticFunctionNamespace.java:1031)
        at com.facebook.presto.metadata.StaticFunctionNamespace.getScalarFunctionImplementation(StaticFunctionNamespace.java:1022)
        at com.facebook.presto.metadata.FunctionManager.getScalarFunctionImplementation(FunctionManager.java:100)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:106)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:75)
        at com.facebook.presto.spi.relation.CallExpression.accept(CallExpression.java:107)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer.optimize(ExpressionOptimizer.java:72)
        at com.facebook.presto.sql.relational.SqlToRowExpressionTranslator.translate(SqlToRowExpressionTranslator.java:170)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.toRowExpression(LocalExecutionPlanner.java:1287)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitScanFilterAndProject$4(LocalExecutionPlanner.java:1243)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor$$Lambda$1140.00000000F42149B0.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1244)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1170)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:704)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:78)
        at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:31)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:468)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:380)
        at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:87)
        at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:394)
        at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:366)
        at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:131)
        at sun.reflect.GeneratedMethodAccessor491.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$523.00000000B22C1520.invoke(Unknown Source)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at com.facebook.presto.server.security.AuthenticationFilter.doFilter(AuthenticationFilter.java:69)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:813)
Caused by: java.lang.IllegalArgumentException
        at java.lang.invoke.MethodHandles.insertArguments(MethodHandles.java:2314)
        at com.facebook.presto.metadata.PolymorphicScalarFunction.applyExtraParameters(PolymorphicScalarFunction.java:209)
        at com.facebook.presto.metadata.PolymorphicScalarFunction.getScalarFunctionImplementationChoice(PolymorphicScalarFunction.java:133)
        at com.facebook.presto.metadata.PolymorphicScalarFunction.specialize(PolymorphicScalarFunction.java:100)
        at com.facebook.presto.metadata.StaticFunctionNamespace.lambda$new$0(StaticFunctionNamespace.java:401)
        at com.facebook.presto.metadata.StaticFunctionNamespace$$Lambda$208.00000000B13CBD00.apply(Unknown Source)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2273)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2156)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2046)
        ... 96 more

```

**Comment by owenlynch** [comment]
Hello,
 Any feedback or update for this issue?

I have upgraded my sever to the latest release (0.224) and the issue is still there.
I can work around this by adding a cast in any query that multiplies an int by a float/double.
i.e.:
`select 100.0*cast(var1 as double) from test_table;`

But we already have many pre written queries for calculating percentages that have multiplication and division logic like this and changing all queries to work around this bug is not optimal.
This kind of operation works in hive, impala and presto versions up to around 0.180.

Any feedback appreciated!

**Comment by owenlynch** [comment]
As commented in #13256 starting the server with 
`-Dparse-decimal-literals-as-double=true` 
works around this issue.

**Comment by aweisberg** [comment]
@owenlynch Could this be better documented? What places did you look at for information on this?

Seems like the change brings us closer to the standard, but the [documentation for fixed precision is still wrong](https://github.com/prestodb/presto/blob/master/presto-docs/src/main/sphinx/language/types.rst#decimal). I'll update those docs, but if you can think of other places that would have helped please let me know.

**Comment by owenlynch** [comment]
> Could this be better documented? What places did you look at for information on this?
yes I think so. I looked in the Online documentation but never spotted it was default and that that setting is needed. I now retrospectively see that setting is documented here: https://prestodb.github.io/docs/current/language/types.html#fixed-precision
I think I probably searched for 'double' not 'decimal'

> Seems like the change brings us closer to the standard,
In both Hive and Impala no cast is necessary and they automatically cast to decimal by default.

> I know the docs are orthogonal to the issue of multiplication not working when it should automatically perform a cast instead of generating an error.
I agree - it should do it be default or display a more meaningful error if possible.

**Comment by aweisberg** [comment]
I just tried to reproduce this on master (basically 0.225 that is coming up) and it works. Can you check if it reproduces for you with 0.225 once it is released?

**Comment by owenlynch** [comment]
Good news,
I'll try it on 0.225 when it is released.

**Comment by tooptoop4** [comment]
bump @owenlynch

**Comment by owenlynch** [comment]
@aweisberg  @tooptoop4 

I installed presto 0.225 and the issue still persists:
```
presto> select 1.0*2;
Query 20190905_145937_00000_qhxih failed: java.lang.IllegalArgumentException
```
As before, once I add the etc/jvm.config argument again `-Dparse-decimal-literals-as-double=true` it works ok.

SO for now that workaround/solution is ok for me.
