### ISSUE TITLE
presto-tests build sometimes hangs and times out in travis

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#13168]
the presto-tests build in travis frequently seems to get stuck and time out after an hour and 20 minutes.

Example: https://api.travis-ci.org/v3/job/565758893/log.txt
Right now we don't have great insight into what the tests are stuck doing.  

Two theories
1. it's getting stuck shutting down a test, e.g. deleting directories after closing the TestingPrestoServer (https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/testing/TestingPrestoServer.java#L348).  this is based on the fact that the last log line printed is "Life cycle stopped.", which makes it seem like even though it stopped the server, it hasn't started the next thing yet, so the test somehow doesn't end. 
2. There's some test getting stuck before it logs anything

Maybe cherry-picking the commits from https://github.com/prestosql/presto/pull/840 could help give us more information.

**Comment by rschlussel** [comment]
After running stackfold on the thread dumps from two different failed builds, these are the threads that are doing work (same in both builds).  All the rest are parked/waiting.

```
http-client-discovery-* (6 threads)
http-client-dynamic-* (2 threads)
http-client-exchange-* (4 threads)
http-client-failure-detector-* (2 threads)
http-client-memoryManager-* (2 threads)
http-client-node-manager-* (4 threads)
http-client-scheduler-* (2 threads)
http-client-workerInfo-* (2 threads)
http-worker-* (3 threads)
    at sun.nio.ch.SelectorImpl.select
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
    at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.select(ManagedSelector.java:423)
    at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:360)
    at ...

binary-spiller-* (8 threads)
page-buffer-client-callback-* (50 threads)
pool-2-thread-1
task-notification-* (10 threads)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run

surefire-forkedjvm-command-thread
    at java.io.FileInputStream.readBytes(Native Method)
    at java.io.FileInputStream.read(FileInputStream.java:255)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
    at java.io.DataInputStream.readInt(DataInputStream.java:387)
    at org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
    at org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:391)
    at java.lang.Thread.run(Thread.java:748)

http-worker-2878-acceptor-0@1a685f39-http@31e1a3df{HTTP/1.1,[http/1.1, h2c]}{127.0.0.1:36514}
http-worker-3022-acceptor-0@4cfdd95e-http@37d4ace3{HTTP/1.1,[http/1.1, h2c]}{127.0.0.1:43641}
http-worker-2925-acceptor-0@5f54f7b4-http@18ea3229{HTTP/1.1,[http/1.1, h2c]}{127.0.0.1:37784}
    at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
    at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
    at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
    at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:385)
    at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:648)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
    at java.lang.Thread.run(Thread.java:748)

pool-2-thread-2
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at okio.Okio$2.read(Okio.java:139)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
    at ...
```

The running tests are always from TestDistributedSpillQueries, e.g. 
```
com.facebook.presto.tests.TestDistributedSpilledQueries::testCorrelatedNonAggregationScalarSubqueries running for 52.63m
com.facebook.presto.tests.TestDistributedSpilledQueries running for 55.23m.
```
and
```
com.facebook.presto.tests.TestDistributedSpilledQueries running for 52.90m
com.facebook.presto.tests.TestDistributedSpilledQueries::testLimitWithJoin running for 35.99m
```



Example build: https://api.travis-ci.org/v3/job/572988507/log.txt

**Comment by rschlussel** [comment]
Closing in favor of #15542
