### ISSUE TITLE
Access Denied: Cannot invoke function regexp_like

### ISSUE THREAD

**Issue by dggs123** [prestodb/presto#13177]
Hi, Not sure why, but all the users getting an access denied error while running the below query, other than who created it.
Query: `select * from "sales_view"`
Error:  
```
io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot invoke function regexp_like
	at io.prestosql.spi.security.AccessDeniedException.denyInvokeFunction(AccessDeniedException.java:341)
	at io.prestosql.security.DenyAllAccessControl.checkCanInvokeFunction(DenyAllAccessControl.java:298)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:900)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:312)
	at io.prestosql.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:335)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.coerceType(ExpressionAnalyzer.java:1285)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitIfExpression(ExpressionAnalyzer.java:528)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.visitIfExpression(ExpressionAnalyzer.java:312)
	at io.prestosql.sql.tree.IfExpression.accept(IfExpression.java:70)
	at io.prestosql.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:335)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:278)
	at io.prestosql.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1596)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:2063)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:1874)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1102)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:266)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:280)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:290)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:757)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:266)
	at io.prestosql.sql.tree.Query.accept(Query.java:94)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:280)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:258)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:253)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeView(StatementAnalyzer.java:2023)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:895)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:266)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:280)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1916)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1098)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:266)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:280)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:290)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:757)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:266)
	at io.prestosql.sql.tree.Query.accept(Query.java:94)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:280)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:258)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:76)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:68)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:207)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:754)
	at io.prestosql.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:361)
	at io.prestosql.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:303)
	at io.prestosql.$gen.Presto_302_e_2_aws_3____20190729_150729_1.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Here's how I created the view:

```create view "sales_view" as select *, if(regexp_like("customer", '0000+'), substr("customer", -6), "customer") as "rs_code", "sales_qty_kg" - COALESCE("sales_return_qty_kg", 0) as "net_sales_qty_kg", "sales_qty_cases" - COALESCE("sales_return_qty_cases", 0) as "net_sales_qty_cases", "sales_qty_pcs" - COALESCE("sales_return_qty_pcs", 0) as "net_sales_qty_pcs", "total_sales_value" - COALESCE("sales_return_total_sales", 0) as "net_sales_value" from "sales_tables"```

**Comment by findepi** [comment]
HI @dggs123, thanks for using Starburst Presto based on Presto 302.
If you have support subscription (https://www.starburstdata.com/presto-enterprise/), please contact Starburst support.
If you don't have the subscription, then 3xx releases are maintained at https://github.com/prestosql/presto
