### ISSUE TITLE
NullPointerException in ST_Buffer

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13194]
The following query fails with NPE in ST_Buffer:

```
> select st_buffer(st_buffer(st_point(177.50102959662, 64.726807421691), 0.0000000001), 0.00005)

java.lang.NullPointerException: input is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at com.facebook.presto.geospatial.serde.GeometrySerde.serialize(GeometrySerde.java:60)
        at com.facebook.presto.plugin.geospatial.GeoFunctions.stBuffer(GeoFunctions.java:367)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:707)
```

CC: @jagill

**Comment by jagill** [comment]
A simpler query that produces the same problem is
```
select st_buffer(st_geometryfromtext('POLYGON ((
    177.0 64.0,
    177.0000000001 64.0,
    177.0000000001 64.0000000001,
    177.0 64.0000000001,
    177.0 64.0
))'), 0.01)
```

but the following query (with one less 0) produces correct output:

```
select st_buffer(ST_geometryfromtext('POLYGON ((
    177.0 64.0,
    177.000000001 64.0,
    177.000000001 64.000000001,
    177.0 64.000000001,
    177.0 64.0
))'), 0.01)
```

I suspect that a polygon that small is causing some numerical issues.

**Comment by jagill** [comment]
In the processes of buffering the small polygon, there is a simplification step, which collapses nearby points.  This removes all the points from the Polygon, which eventually returns a null.

I've filed an issue with Esri: https://github.com/Esri/geometry-api-java/issues/241
