### ISSUE TITLE
Is there a way to run Presto on JVM 11?

### ISSUE THREAD

**Issue by l1x** [prestodb/presto#13216]
I am getting an error when launching on JVM 11.

```
java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

```
2019-08-13T11:19:30.855+0200    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector,
see the following errors:

1) Error injecting constructor, java.io.IOException: Can not attach to current VM
  at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:41)
  at io.airlift.jmx.JmxModule.configure(JmxModule.java:55)
  while locating io.airlift.jmx.JmxAgent9
  while locating io.airlift.jmx.JmxAgent
    for the 1st parameter of io.airlift.jmx.JmxModule$JmxAnnouncementProvider.setJmxAgent(JmxModule.java:68)
  while locating io.airlift.jmx.JmxModule$JmxAnnouncementProvider
  while locating io.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.internal.Element
(setName=,uniqueId=361, type=MULTIBINDER, keyType=)
  while locating java.util.Set<io.airlift.discovery.client.ServiceAnnouncement>
    for the 2nd parameter of io.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:63)
```

**Comment by tooptoop4** [comment]
what presto version? @l1x

**Comment by l1x** [comment]
@tooptoop4 0.224

**Comment by armsword** [comment]
The solution was to add the flag -Djdk.attach.allowAttachSelf=true to ${presto-home}/etc/jvm.config

**Comment by l1x** [comment]
Thanks, I will try.
