### ISSUE TITLE
Flaky TestHivePushdownFilterQueries

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#13253]
testFilterFunctions and testArrays failed  with the following stacktrace in a recent build: https://api.travis-ci.org/v3/job/572454390/log.txt

```
[ERROR] testFilterFunctions(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 12.497 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM lineitem_ex WHERE keys[1] % 5 = 0 AND nested_keys[1][2] > 100
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:138)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:337)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:235)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testFilterFunctions(TestHivePushdownFilterQueries.java:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to read ORC file: file:/tmp/PrestoTest3034274899939071963/hive_data/tpch/lineitem_ex/20190815_205249_00016_kkt5v_c501edb6-9447-4d8a-8374-2f5c02842425
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:391)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 18 more
Caused by: com.facebook.presto.spi.PrestoException: Failed to read ORC file: file:/tmp/PrestoTest3034274899939071963/hive_data/tpch/lineitem_ex/20190815_205249_00016_kkt5v_c501edb6-9447-4d8a-8374-2f5c02842425
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:94)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:250)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_225_SNAPSHOT_4222738__testversion____20190815_205238_14609.run(Unknown Source)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.facebook.presto.orc.reader.ListFilter.populateElementFilters(ListFilter.java:213)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:369)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:226)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:373)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:226)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:263)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:78)
	... 12 more

[ERROR] testArrays(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 2.158 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM lineitem_ex WHERE nested_keys[3] IS NOT NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:138)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:337)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:235)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testArrays(TestHivePushdownFilterQueries.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to read ORC file: file:/tmp/PrestoTest3034274899939071963/hive_data/tpch/lineitem_ex/20190815_205249_00016_kkt5v_c501edb6-9447-4d8a-8374-2f5c02842425
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:391)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 18 more
Caused by: com.facebook.presto.spi.PrestoException: Failed to read ORC file: file:/tmp/PrestoTest3034274899939071963/hive_data/tpch/lineitem_ex/20190815_205249_00016_kkt5v_c501edb6-9447-4d8a-8374-2f5c02842425
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:94)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:250)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_225_SNAPSHOT_4222738__testversion____20190815_205237_14608.run(Unknown Source)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.facebook.presto.orc.reader.ListFilter.populateElementFilters(ListFilter.java:213)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:369)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:226)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:373)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:226)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:263)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:78)
	... 12 more
```

@mbasmanova based on the stack trace it looks related to https://github.com/prestodb/presto/pull/13099.  Can you take a look?

**Comment by mbasmanova** [comment]
@rschlussel Thanks for reporting. I'll take a look. CC: @prestodb/aria

**Comment by mbasmanova** [comment]
Some more flakiness:

```
ERROR] Tests run: 1449, Failures: 1, Errors: 0, Skipped: 57, Time elapsed: 2,528.97 s <<< FAILURE! - in TestSuite
[ERROR] testArrays(com.facebook.presto.hive.TestHivePushdownFilterQueries)  Time elapsed: 36.627 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM lineitem_ex WHERE nested_keys[3] IS NULL
	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:150)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:138)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertQueryUsingH2Cte(TestHivePushdownFilterQueries.java:366)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.assertFilterProject(TestHivePushdownFilterQueries.java:264)
	at com.facebook.presto.hive.TestHivePushdownFilterQueries.testArrays(TestHivePushdownFilterQueries.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to read ORC file: file:/tmp/PrestoTest8169961107556799537/hive_data/tpch/lineitem_ex/20190820_080456_00016_qsgeg_149acf7a-5e90-4542-883f-0e6d386167c9
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:115)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:391)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:147)
	... 18 more
Caused by: com.facebook.presto.spi.PrestoException: Failed to read ORC file: file:/tmp/PrestoTest8169961107556799537/hive_data/tpch/lineitem_ex/20190820_080456_00016_qsgeg_149acf7a-5e90-4542-883f-0e6d386167c9
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:94)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:250)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_225_SNAPSHOT_2ec6bb0__testversion____20190820_080442_14390.run(Unknown Source)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.populateOutputPositionsWithFilter(ListSelectiveStreamReader.java:428)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:382)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:227)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:263)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:78)
	... 12 more
```

**Comment by mbasmanova** [comment]
#13335 extends OrcTester to allow testing filters on subfields. This capability will allow reproducing this issue.

**Comment by mbasmanova** [comment]
I'm still seeing occasional failures:

```
SELECT * FROM lineitem_ex WHERE keys[1] % 5 = 0 AND nested_keys[1][2] > 100

SELECT * FROM lineitem_ex WHERE nested_keys[3] IS NOT NULL

Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.facebook.presto.orc.reader.ListFilter.populateElementFilters(ListFilter.java:213)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:382)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:231)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.readNotAllNulls(ListSelectiveStreamReader.java:389)
	at com.facebook.presto.orc.reader.ListSelectiveStreamReader.read(ListSelectiveStreamReader.java:231)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:263)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:78)
	... 12 more
```

**Comment by oerling** [comment]
Maybe the thing to do would be to have a catch block that would copy out the files for interactive reproduction.  The split of the test data across files is not deterministic, right?

**Comment by mbasmanova** [comment]
Haven't seen this recently.
