### ISSUE TITLE
Unsupported type: array(bigint) in TupleDomainFilterUtils

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#13295]
Comparing array column with literal array triggers an error in TupleDomainFilterUtils:

```
CREATE TABLE lineitem_ex AS
SELECT orderkey, ARRAY[orderkey, partkey, suppkey] AS keys FROM lineitem;

SELECT orderkey FROM lineitem_ex WHERE keys = ARRAY[1, 2, 3];
```

```
Caused by: java.lang.UnsupportedOperationException: Unsupported type: array(bigint)
	at com.facebook.presto.orc.TupleDomainFilterUtils.createRangeFilter(TupleDomainFilterUtils.java:173)
	at com.facebook.presto.orc.TupleDomainFilterUtils.toFilter(TupleDomainFilterUtils.java:76)
	at com.google.common.collect.Maps$9.transformEntry(Maps.java:1955)
	at com.google.common.collect.Maps$12.getValue(Maps.java:1996)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.toTupleDomainFilters(OrcSelectivePageSourceFactory.java:319)
	at com.facebook.presto.hive.orc.OrcSelectivePageSourceFactory.createOrcPageSource(OrcSelectivePageSourceFactory.java:249)
	... 17 more
```

CC: @prestodb/aria

**Comment by oerling** [comment]
Yes, the fix is not to extract comparisons between columns and constants where the column is not a scalar.  Scalars inside a nesting where each enclosing level is supported are fine. Since the only supporting complex type at present is list, we should make sure list[1] = 1 gets extracted but struct.field = 1 does not.

 

By this time comparisons will be between compatible types so checking the type of the scalar is just as good.
