### ISSUE TITLE
UnsupportedOperationException: com.facebook.presto.spi.block.IntArrayBlockBuilder

### ISSUE THREAD

**Issue by toninis** [prestodb/presto#13346]
Hello all,

I get this error when I try to aggregate some DOUBLE types with Integers . 
Is this normal behaviour ? 

I am querying Hive backend with Presto 0.215 . 

```
java.lang.UnsupportedOperationException: com.facebook.presto.spi.block.IntArrayBlockBuilder 
at com.facebook.presto.spi.block.BlockBuilder.writeLong(BlockBuilder.java:50) 	 
at com.facebook.presto.spi.type.AbstractLongType.writeLong(AbstractLongType.java:67) 	
at com.facebook.presto.operator.aggregation.state.NullableLongStateSerializer.serialize(NullableLongStateSerializer.java:39) 	
at com.facebook.presto.operator.aggregation.state.NullableLongStateSerializer.serialize(NullableLongStateSerializer.java:23) 	
at com.facebook.presto.$gen.IntegerIntegerMaxGroupedAccumulator_20190906_070657_33372.evaluateIntermediate(Unknown Source) 	
at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder$Aggregator.evaluate(InMemoryHashAggregationBuilder.java:444) 	
at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$buildResult$3(InMemoryHashAggregationBuilder.java:302) 	
at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315) 	
at com.facebook.presto.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:480) 	
at com.facebook.presto.operator.Driver.processInternal(Driver.java:379) 	
at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283) 	
at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675) 	
at com.facebook.presto.operator.Driver.processFor(Driver.java:276) 	
at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065) 	
at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162) 	
at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483) 	at com.facebook.presto.$gen.Presto_0_215____20190807_152739_1.run(Unknown Source) 	
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	
at java.lang.Thread.run(Thread.java:748)
--
```

**Comment by tooptoop4** [comment]
Send sample SQL sir

**Comment by tooptoop4** [comment]
And ddl
