### ISSUE TITLE
OrcWriter may close column writers twice if rollback

### ISSUE THREAD

**Issue by highker** [prestodb/presto#13400]
During rollback, do not close the writer if the it has already been closed.
Need to re-exam `outputPageSink`'s behavior in `compactSorted` method.

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:488)
        at com.facebook.presto.orc.writer.SliceDictionaryColumnWriter.getBufferedBytes(SliceDictionaryColumnWriter.java:518)
        at com.facebook.presto.orc.DictionaryCompressionOptimizer$DictionaryColumnManager.getBufferedBytes(DictionaryCompressionOptimizer.java:443)
        at com.facebook.presto.orc.DictionaryCompressionOptimizer$DictionaryColumnManager.getCompressionRatio(DictionaryCompressionOptimizer.java:438)
        at com.facebook.presto.orc.DictionaryCompressionOptimizer.convertLowCompressionStreams(DictionaryCompressionOptimizer.java:184)
        at com.facebook.presto.orc.DictionaryCompressionOptimizer.finalOptimize(DictionaryCompressionOptimizer.java:107)
        at com.facebook.presto.orc.OrcWriter.bufferStripeData(OrcWriter.java:368)
        at com.facebook.presto.orc.OrcWriter.flushStripe(OrcWriter.java:332)
        at com.facebook.presto.orc.OrcWriter.close(OrcWriter.java:444)
        at com.facebook.presto.raptor.storage.OrcFileWriter.close(OrcFileWriter.java:149)
        at com.facebook.presto.raptor.storage.OrcStorageManager$OrcStoragePageSink.rollback(OrcStorageManager.java:679)
        at com.facebook.presto.raptor.storage.organization.ShardCompactor.compactSorted(ShardCompactor.java:161)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.performCompaction(OrganizationJob.java:108)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.runJob(OrganizationJob.java:83)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.runJob(OrganizationJob.java:71)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.run(OrganizationJob.java:59)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        ... 3 more
```

**Comment by golammott** [comment]
@highker First time contributor here attempting to tackle this one, I walked through the code and here are a few callouts:

- After the low level ColumnWriters get marked as closed in the OrcWriter, IOExceptions can still be thrown (resulting in the outputPageSink.rollback()). 
- This lead to inconsistent state where the low level ColumnWriters are marked as closed, but the OrcStorageManager's writer is still marked as open. Which is why OrcStorageManager.rollback attempts to close the writers again.
- This appears to solved in prestosql by switching to using OrcRecordWriter from hive instead of the built in OrcWriter. Hive's OrcRecordWriter makes a stronger guarantee that these low level writers are either closed or the exception is thrown. 

I think we can either backport this change from prestosql or update the native OrcWriter to make a stronger guarantee of closing the writers or throwing the exception.

**Comment by highker** [comment]
@golammott, your understand is correct. Feel free to send out a PR to address the issue.
`OrcRecordWriter` is a legacy slow writer that should be avoid. We deliberately moved away from it (#12594).

**Comment by golammott** [comment]
Thanks @highker, addressed this issue in #13429. 

Let me know if this approach works and I can add some unit tests. Was also thinking of causing the IOExceptions to propagate back to the `OrcStorageManager.appendPages()` and marking the writer as closed there.

**Comment by highker** [comment]
Paste the original exception causing the rollback for reference
```
com.facebook.presto.spi.PrestoException: java.io.IOException: com.facebook.presto....
        at com.facebook.presto.raptor.storage.OrcFileWriter.appendPages(OrcFileWriter.java:114)
        at com.facebook.presto.raptor.storage.OrcStorageManager$OrcStoragePageSink.appendPages(OrcStorageManager.java:610)
        at com.facebook.presto.raptor.storage.organization.ShardCompactor.compactSorted(ShardCompactor.java:145)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.performCompaction(OrganizationJob.java:108)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.runJob(OrganizationJob.java:83)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.runJob(OrganizationJob.java:71)
        at com.facebook.presto.raptor.storage.organization.OrganizationJob.run(OrganizationJob.java:59)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.UncheckedIOException: java.io.IOException: com.facebook.presto....
        at io.airlift.slice.OutputStreamSliceOutput.writeToOutputStream(OutputStreamSliceOutput.java:362)
        at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:185)
        at io.airlift.slice.OutputStreamSliceOutput.writeBytes(OutputStreamSliceOutput.java:176)
        at com.facebook.presto.orc.OrcOutputBuffer.writeDataTo(OrcOutputBuffer.java:124)
        at com.facebook.presto.orc.stream.StreamDataOutput.writeData(StreamDataOutput.java:67)
        at com.facebook.presto.orc.OutputStreamOrcDataSink.lambda$write$0(OutputStreamOrcDataSink.java:53)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.facebook.presto.orc.OutputStreamOrcDataSink.write(OutputStreamOrcDataSink.java:53)
        at com.facebook.presto.orc.OrcWriter.flushStripe(OrcWriter.java:339)
        at com.facebook.presto.orc.OrcWriter.writeChunk(OrcWriter.java:304)
        at com.facebook.presto.orc.OrcWriter.write(OrcWriter.java:262)
        at com.facebook.presto.raptor.storage.OrcFileWriter.appendPages(OrcFileWriter.java:111)
        ... 10 more
Caused by: java.io.IOException: com.facebook.presto....

**Comment by highker** [comment]
@golammott, thanks for writing the unit test! I will think about how to address the issue tonight. Meanwhile, if you have a good proposal, feel free to put it down in the comment.

**Comment by highker** [comment]
@golammott, maybe just add a try/finally block to the following code. It's unfortunate we have decoupled reset and close so far away.
```java
// write all data
orcDataSink.write(outputData);

// open next stripe
columnWriters.forEach(ColumnWriter::reset);
dictionaryCompressionOptimizer.reset();
rowGroupRowCount = 0;
stripeRowCount = 0;
bufferedBytes = toIntExact(columnWriters.stream().mapToLong(ColumnWriter::getBufferedBytes).sum());

**Comment by highker** [comment]
@golammott, will you still be available to work on this ticket?

**Comment by golammott** [comment]
@highker Sorry for the delay, looking at this now.
