### ISSUE TITLE
presto-cli can not use [no jansi64-0.225-9e57310 in java.library.path]

### ISSUE THREAD

**Issue by wwwwwwchun** [prestodb/presto#13408]
the presto version is 0.225,
when i exec the presto-cli,the cli return err:
[root@idc_db_5_30 presto-server]# ./bin/presto --server 172.18.0.2:8080
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no jansi64-0.225-9e57310 in java.library.path, no jansi-0.225-9e57310 in java.library.path, no jansi in java.library.path, /tmp/libjansi-64-0-4261962157137269829.225-9e57310: /tmp/libjansi-64-0-4261962157137269829.225-9e57310: failed to map segment from shared object: Operation not permitted]
        at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
        at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:42)
        at org.fusesource.jansi.AnsiConsole.wrapOutputStream(AnsiConsole.java:48)
        at org.fusesource.jansi.AnsiConsole.<clinit>(AnsiConsole.java:38)
        at com.facebook.presto.cli.Console.run(Console.java:92)
        at com.facebook.presto.cli.Presto.main(Presto.java:31)

how can i reslove this problem?
thanks

**Comment by shanmugaapriyan** [comment]
I'm also getting the same error while running it in my CENTOS. But its working fine in my MAC

**Comment by shanmugaapriyan** [comment]
Its not an issue. This occurs only if the presto-cli couldn't able to access its java temp folder.  

Running the same as sudo user with all the permissions or create a new temp folder and run the cli

> java -Djava.io.tmpdir=<user-path>/presto-server-0.225/temp -jar presto-cli

**Comment by mawu2** [comment]
It might because your /tmp is mounted as noexec, you can execute `mount -o remount,exec /tmp` to resolve this temporarily.

**Comment by wwwwwwchun** [comment]
this problem has been solved,i umount /tmp,the program is ok

**Comment by pratyakshsharma** [comment]
For me the output of java -version was giving java version "17.0.2". Switching it to jdk-1.8 helped, since my maven is also configured with jdk-1.8 only

**Comment by jianwu** [comment]
Go the same problem. None of above suggestion works
