### ISSUE TITLE
ExceededMemoryLimitException on query with many aggregate functions

### ISSUE THREAD

**Issue by felixgao** [prestodb/presto#13437]
I am running a 23 node cluster on EMR each worker node have 64GB physical memory.  My config looks like
```
sink.max-buffer-size=1GB
query.max-memory=900GB
query.max-memory-per-node=25GB
query.max-total-memory-per-node=32GB
query.max-history=40
query.min-expire-age=30m
query.initial-hash-partitions=20 
optimizer.optimize-metadata-queries=true
experimental.spiller-spill-path=/mnt/tmp/
experimental.spill-enabled=true
experimental.max-spill-per-node=100GB
experimental.query-max-spill-per-node=100GB
```
If I execute the query as 
```
    select count(*) 
    from invoice_table
    where company_id is not Null and 
          invoice_id is not Null and 
          invoice_amount is not Null 
    group by invoice_id, company_id 
    having approx_distinct(paid_date) <= 1 


Query 20190923_191356_00012_3caur, RUNNING, 23 nodes
Splits: 4,522 total, 3,338 done (73.82%)
55:41 [2.15B rows, 36.1GB] [645K rows/s, 11.1MB/s]
```
the query seems to finish with resource utilization like
![image](https://user-images.githubusercontent.com/1153820/65459401-ad492c00-de04-11e9-8bff-e9606aa6a950.png)

However, if I start to add more aggregation functions to the query like
```
select company_id, 
      invoice_id, 
    sum(invoice_amount) as invoice_amount, 
    sum(payment_amount) as payment_amount, 
    min(invoice_create_date) as invoice_create_date, 
    min(invoice_due_date) as invoice_due_date, 
    min(paid_date) as paid_date, 
    approx_distinct(paid_date) as number_of_times_paid 
    from invoice_table
    where company_id is not Null and 
          invoice_id is not Null and 
          invoice_amount is not Null 
    group by invoice_id, company_id 
    having approx_distinct(paid_date) <= 1 
    limit 200;
```
this will results exceeded local memory limit error.
```
com.facebook.presto.ExceededMemoryLimitException: Query exceeded per-node user memory limit of 24.85GB
	at com.facebook.presto.ExceededMemoryLimitException.exceededLocalUserMemoryLimit(ExceededMemoryLimitException.java:39)
	at com.facebook.presto.memory.DefaultQueryContext.updateUserMemory(DefaultQueryContext.java:134)
	at com.facebook.presto.memory.DefaultQueryContext$QueryMemoryReservationHandler.reserveMemory(DefaultQueryContext.java:312)
	at com.facebook.presto.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:37)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at com.facebook.presto.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
	at com.facebook.presto.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:66)
	at com.facebook.presto.operator.OperatorContext$InternalLocalMemoryContext.setBytes(OperatorContext.java:590)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.updateMemory(InMemoryHashAggregationBuilder.java:348)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.updateMemoryWithYieldInfo(InMemoryHashAggregationBuilder.java:337)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.updateMemory(InMemoryHashAggregationBuilder.java:181)
	at com.facebook.presto.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:411)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1065)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_215____20190923_181100_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
![image](https://user-images.githubusercontent.com/1153820/65459526-fb5e2f80-de04-11e9-977a-944d16029285.png)

I am Presto CLI 0.215

I have tried to tune the task_parallel to different numbers 8,16,32 all resulted in the same error. 

The underlying data is parquet file stored in S3.

**Comment by shixuan-fan** [comment]
Would you mind sharing the distributed query plan by `EXPLAIN (TYPE DISTRIBUTED) <query>`?

**Comment by felixgao** [comment]
certainly. here is the the query plan for the multiple aggregated values

```
 Fragment 0 [SINGLE]
     Output layout: [company_id, invoice_id, sum, sum_10, min, min_11, min_12, max, approx_distinct_13]
     Output partitioning: SINGLE []
     Grouped Execution: false
     - Output[company_id, invoice_id, invoice_amount, payment_amount, invoice_create_date, invoice_due_date, paid_date, is_fully_paid, number_of_times_paid] => [company_id:bigint, invoice_id:bi
             invoice_amount := sum
             payment_amount := sum_10
             invoice_create_date := min
             invoice_due_date := min_11
             paid_date := min_12
             is_fully_paid := max
             number_of_times_paid := approx_distinct_13
         - Limit[200] => [invoice_id:bigint, company_id:bigint, sum:decimal(38,8), sum_10:decimal(38,8), min:timestamp, min_11:timestamp, min_12:timestamp, max:boolean, approx_distinct_13:bigin
             - LocalExchange[SINGLE] () => invoice_id:bigint, company_id:bigint, sum:decimal(38,8), sum_10:decimal(38,8), min:timestamp, min_11:timestamp, min_12:timestamp, max:boolean, approx_
                 - RemoteSource[1] => [invoice_id:bigint, company_id:bigint, sum:decimal(38,8), sum_10:decimal(38,8), min:timestamp, min_11:timestamp, min_12:timestamp, max:boolean, approx_dist

 Fragment 1 [HASH]
     Output layout: [invoice_id, company_id, sum, sum_10, min, min_11, min_12, max, approx_distinct_13]
     Output partitioning: SINGLE []
     Grouped Execution: false
     - LimitPartial[200] => [invoice_id:bigint, company_id:bigint, sum_10:decimal(38,8), min:timestamp, min_12:timestamp, max:boolean, min_11:timestamp, approx_distinct_13:bigint, sum:decimal(3
         - Filter[filterPredicate = ("approx_distinct_13" <= BIGINT '1')] => [invoice_id:bigint, company_id:bigint, sum_10:decimal(38,8), min:timestamp, min_12:timestamp, max:boolean, min_11:ti
             - Project[] => [invoice_id:bigint, company_id:bigint, sum_10:decimal(38,8), min:timestamp, min_12:timestamp, max:boolean, min_11:timestamp, approx_distinct_13:bigint, sum:decimal(3
                 - Aggregate(FINAL)[invoice_id, company_id][$hashvalue] => [invoice_id:bigint, company_id:bigint, $hashvalue:bigint, sum_10:decimal(38,8), min:timestamp, min_12:timestamp, max:b
                         sum_10 := "sum"("sum_50")
                         min := "min"("min_51")
                         min_12 := "min"("min_53")
                         max := "max"("max_54")
                         min_11 := "min"("min_52")
                         approx_distinct_13 := "approx_distinct"("approx_distinct_55")
                         sum := "sum"("sum_49")
                     - LocalExchange[HASH][$hashvalue] ("invoice_id", "company_id") => invoice_id:bigint, company_id:bigint, min_53:bigint, min_52:bigint, min_51:bigint, max_54:boolean, approx_
                         - RemoteSource[2] => [invoice_id:bigint, company_id:bigint, min_53:bigint, min_52:bigint, min_51:bigint, max_54:boolean, approx_distinct_55:HyperLogLog, sum_49:varbinar

 Fragment 2 [SOURCE]
     Output layout: [invoice_id, company_id, min_53, min_52, min_51, max_54, approx_distinct_55, sum_49, sum_50, $hashvalue_57]
     Output partitioning: HASH [invoice_id, company_id][$hashvalue_57]
     Grouped Execution: false
     - Aggregate(PARTIAL)[invoice_id, company_id][$hashvalue_57] => [invoice_id:bigint, company_id:bigint, $hashvalue_57:bigint, min_53:bigint, min_52:bigint, min_51:bigint, max_54:boolean, app
             min_53 := "min"("paid_date")
             min_52 := "min"("invoice_due_date")
             min_51 := "min"("invoice_create_date")
             max_54 := "max"("is_fully_paid")
             approx_distinct_55 := "approx_distinct"("paid_date")
             sum_49 := "sum"("invoice_amount")
             sum_50 := "sum"("payment_amount")
         - ScanFilterProject[table = hive:<MASKED>:invoice_table, grouped = false, filterPredicate = ((((NOT ("company_id" IS NULL)) AND ("country" = CAST('United States' AS varchar))) AND
                 $hashvalue_57 := "combine_hash"("combine_hash"(bigint '0', COALESCE("$operator$hash_code"("invoice_id"), 0)), COALESCE("$operator$hash_code"("company_id"), 0))
                 LAYOUT: <MASKED>:invoice_table
                 country := country:string:10:REGULAR
                 invoice_create_date := invoice_create_date:timestamp:4:REGULAR
                 company_id := company_id:bigint:0:REGULAR
                 payment_amount := payment_amount:decimal(38,8):24:REGULAR
                 invoice_id := invoice_id:bigint:1:REGULAR
                 is_fully_paid := is_fully_paid:boolean:8:REGULAR
                 product_name := product_name:string:58:REGULAR
                 invoice_amount := invoice_amount:decimal(38,8):47:REGULAR
                 paid_date := paid_date:timestamp:23:REGULAR
                 invoice_due_date := invoice_due_date:timestamp:56:REGULAR

```

**Comment by shixuan-fan** [comment]
Most of the time when we see local memory limit error, it is due to data skew. Could you check the cardinality of "company_id, invoice_id" combination to see if there are skew? 

Note that since your total memory is larger than node count * local memory, so it is guaranteed to first hit local memory limit before hitting total memory limit, thus the skew guess might not be correct.

**Comment by felixgao** [comment]
I did a count distinct on 'company_id, invoice_id' there are 1,445,965,788 records out of 2.1B rows.
