### ISSUE TITLE
presto doesn't start anymore : AttachNotSupportedException

### ISSUE THREAD

**Issue by thomasLeclaire** [prestodb/presto#13506]
Hello! 
I changed nothing but my presto installation doesn't start anymore now. 
It's running into a GKE cluster which auto update, therefore could be the rootcause, but didn't find more details which could explain. 

When process is starting (same for worker or coordinator) : I get this exception and nothing more..

`ERROR	main	com.facebook.presto.server.PrestoServer	com/sun/tools/attach/AttachNotSupportedException`

`java.lang.NoClassDefFoundError: com/sun/tools/attach/AttachNotSupportedException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.base/java.lang.Class.getDeclaredConstructors(Unknown Source)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:115)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:706)
	at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:53)
	at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:36)
	at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:49)
	at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:35)
	at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:27)
	at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:99)
	at com.google.inject.internal.AbstractProcessor.process(AbstractProcessor.java:54)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:128)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AttachNotSupportedException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more`

thx for any help!

PS : same error with presto 0.222 or 0.226, java 8 or java 11

**Comment by ajaygeorge** [comment]
Hi @thomasLeclaire , From the error stack it looks like the JAVA_HOME might be pointing to a jre instead of a jdk .
Can you please double check that.

**Comment by thomasLeclaire** [comment]
hello! 
yes it sounds like it was jre but it was perfectly running like this for months. I can't explain what suddenly happened last week. 

I moved to an explicit JDK11, and still the same issue, but after the addition of this option in jvm config it is now working well. 
 `   -Djdk.attach.allowAttachSelf=true`

regards,
Thomas
