### ISSUE TITLE
NPE in SliceDictionarySelectiveStreamReader

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#13515]
```
Caused by: java.lang.NullPointerException
	at com.facebook.presto.orc.reader.SliceDictionarySelectiveReader.skip(SliceDictionarySelectiveReader.java:346)
	at com.facebook.presto.orc.reader.SliceDictionarySelectiveReader.read(SliceDictionarySelectiveReader.java:167)
	at com.facebook.presto.orc.reader.SliceSelectiveStreamReader.read(SliceSelectiveStreamReader.java:116)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:346)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:84)
	... 13 more
```

**Comment by bhhari** [comment]
#13518
