### ISSUE TITLE
NullPointer in SliceDirectSelectiveStreamReader

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#13510]
```
> Caused by: java.lang.NullPointerException
> 	at com.facebook.presto.orc.reader.SliceDirectSelectiveStreamReader.skip(SliceDirectSelectiveStreamReader.java:310)
> 	at com.facebook.presto.orc.reader.SliceDirectSelectiveStreamReader.read(SliceDirectSelectiveStreamReader.java:135)
> 	at com.facebook.presto.orc.reader.SliceSelectiveStreamReader.read(SliceSelectiveStreamReader.java:116)
> 	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:346)
> 	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:84)
> 	... 12 more
```

**Comment by bhhari** [comment]
#13513
