### ISSUE TITLE
NPE in LongDictionarySelectiveStreamReader

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#13514]
```
Caused by: java.lang.NullPointerException
	at com.facebook.presto.orc.reader.LongDictionarySelectiveStreamReader.skip(LongDictionarySelectiveStreamReader.java:197)
	at com.facebook.presto.orc.reader.LongDictionarySelectiveStreamReader.read(LongDictionarySelectiveStreamReader.java:122)
	at com.facebook.presto.orc.reader.LongSelectiveStreamReader.read(LongSelectiveStreamReader.java:116)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:346)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:84)
	... 13 more
```

**Comment by bhhari** [comment]
#13516
