### ISSUE TITLE
Handle pushdown of filter that always fail

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#13529]

**Comment by bhhari** [comment]
```
Caused by: java.lang.IllegalArgumentException: Cannot pushdown filter that is always false
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.facebook.presto.metadata.MetadataManager.pushdownFilter(MetadataManager.java:438)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.pushPredicateIntoTableScan(PickTableLayout.java:298)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutForPredicate.apply(PickTableLayout.java:156)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutForPredicate.apply(PickTableLayout.java:120)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:166)
```

**Comment by mbasmanova** [comment]
This appears to be a duplicate of #13534
