### ISSUE TITLE
Generic Internal Error: LambdaForm cannot be cast to LambdaFormEditor$Transform

### ISSUE THREAD

**Issue by caithagoras** [prestodb/presto#13542]
```
com.facebook.presto.spi.PrestoException: java.base/java.lang.invoke.LambdaForm cannot be cast to java.base/[Ljava.lang.invoke.LambdaFormEditor$Transform;
	at com.facebook.presto.spi.block.SingleMapBlock.handleThrowable(SingleMapBlock.java:418)
	at com.facebook.presto.spi.block.SingleMapBlock.seekKey(SingleMapBlock.java:174)
	at com.facebook.presto.operator.scalar.MapZipWithFunction.mapZipWith(MapZipWithFunction.java:138)
	at com.facebook.presto.$gen.PageProjectionWork_20191011_223026_46103_fdqrw_4_13_1561476.lambda_1(Unknown Source)
	at com.facebook.presto.operator.scalar.ArrayReduceFunction.reduce(ArrayReduceFunction.java:114)
	at com.facebook.presto.$gen.PageProjectionWork_20191011_223026_46103_fdqrw_4_13_1561476.evaluate(Unknown Source)
	at com.facebook.presto.$gen.PageProjectionWork_20191011_223026_46103_fdqrw_4_13_1561476.process(Unknown Source)
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:295)
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:183)
	at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315)
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79)
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:111)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:300)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:235)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_225_9e57310____20190927_011447_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassCastException: java.base/java.lang.invoke.LambdaForm cannot be cast to java.base/[Ljava.lang.invoke.LambdaFormEditor$Transform;
	at java.base/java.lang.invoke.LambdaFormEditor.getInCache(LambdaFormEditor.java:266)
	at java.base/java.lang.invoke.LambdaFormEditor.filterArgumentForm(LambdaFormEditor.java:629)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:291)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:255)
	at java.base/java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:422)
	at java.base/java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:859)
	at java.base/java.lang.invoke.MethodHandle.asType(MethodHandle.java:844)
	at java.base/java.lang.invoke.Invokers.checkGenericType(Invokers.java:495)
	at com.facebook.presto.spi.block.SingleMapBlock.seekKey(SingleMapBlock.java:171)
	... 26 more
```

**Comment by caithagoras** [comment]
Query Id: 20191011_223026_46103_fdqrw
