### ISSUE TITLE
VerifyException when running ANALYZE

### ISSUE THREAD

**Issue by tooptoop4** [prestodb/presto#13580]
analyze  hive.a.b

ui log:
com.google.common.base.VerifyException: All computed statistics must be used
	at com.google.common.base.Verify.verify(Verify.java:123)
	at com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)
	at com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)
	at com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

coordinator:
2019-10-21T12:40:27.944Z        ERROR   SplitRunner-0-107       com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20191021_123951_01173_kqqrg.0.0-16  (start = 1.1528994884693E7, wall = 36062 ms, cpu = 0 ms, wait = 0 ms, calls = 3)
com.google.common.base.VerifyException: All computed statistics must be used
        at com.google.common.base.Verify.verify(Verify.java:123)
        at com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)
        at com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)
        at com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2019-10-21T12:40:27.945Z        ERROR   remote-task-callback-128        com.facebook.presto.execution.StageStateMachine Stage 20191021_123951_01173_kqqrg.0 failed
com.google.common.base.VerifyException: All computed statistics must be used
        at com.google.common.base.Verify.verify(Verify.java:123)
        at com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)
        at com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)
        at com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

        
        worker:
        Z :: end 2019-10-21T12:40:17.544Z
2019-10-21T12:40:27.944Z        ERROR   SplitRunner-0-107       com.facebook.presto.execution.executor.TaskExecutor     Error processing Split 20191021_123951_01173_kqqrg.0.0-16  (start = 1.1528994884693E7, wall = 36062 ms, cpu = 0 ms, wait = 0 ms, calls = 3)
com.google.common.base.VerifyException: All computed statistics must be used
        at com.google.common.base.Verify.verify(Verify.java:123)
        at com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)
        at com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)
        at com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2019-10-21T12:40:27.945Z        ERROR   remote-task-callback-128        com.facebook.presto.execution.StageStateMachine Stage 20191021_123951_01173_kqqrg.0 failed
com.google.common.base.VerifyException: All computed statistics must be used
        at com.google.common.base.Verify.verify(Verify.java:123)
        at com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)
        at com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)
        at com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

 json plan:       
                "failures" : [ {
          "type" : "com.google.common.base.VerifyException",
          "message" : "All computed statistics must be used",
          "suppressed" : [ ],
          "stack" : [ "com.google.common.base.Verify.verify(Verify.java:123)", "com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)", "com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)", "com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)", "com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)", "com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)", "com.facebook.presto.operator.Driver.processInternal(Driver.java:379)", "com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)", "com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)", "com.facebook.presto.operator.Driver.processFor(Driver.java:276)", "com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)", "com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)", "com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)", "com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)", "java.lang.Thread.run(Thread.java:748)" ],
          "errorCode" : {
            "code" : 65536,
            "name" : "GENERIC_INTERNAL_ERROR",
            "type" : "INTERNAL_ERROR"
          }
        }, {
          "type" : "com.google.common.base.VerifyException",
          "message" : "All computed statistics must be used",
          "suppressed" : [ ],
          "stack" : [ "com.google.common.base.Verify.verify(Verify.java:123)", "com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)", "com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)", "com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)", "com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)", "com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)", "com.facebook.presto.operator.Driver.processInternal(Driver.java:379)", "com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)", "com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)", "com.facebook.presto.operator.Driver.processFor(Driver.java:276)", "com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)", "com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)", "com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)", "com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)", "java.lang.Thread.run(Thread.java:748)" ],
          "errorCode" : {
            "code" : 65536,
            "name" : "GENERIC_INTERNAL_ERROR",
            "type" : "INTERNAL_ERROR"
          }
        } ],
        "queuedPartitionedDrivers" : 0,
        "runningPartitionedDrivers" : 0,
        "outputBufferOverutilized" : false,
        "physicalWrittenDataSize" : "0B",
        "memoryReservation" : "0B",
        "systemMemoryReservation" : "0B",
        "fullGcCount" : 0,
        "fullGcTime" : "0.00ns"
      },
      "lastHeartbeat" : "2019-10-21T12:40:27.905Z",
      "outputBuffers" : {
        "type" : "PARTITIONED",
        "state" : "FAILED",
        "canAddBuffers" : false,
        "canAddPages" : false,
        "totalBufferedBytes" : 0,
        "totalBufferedPages" : 0,
        "totalRowsSent" : 0,
        "totalPagesSent" : 0,
        "buffers" : [ ]
      },
      "noMoreSplits" : [ "99" ],
      
      
    "failureCause" : {
      "type" : "com.google.common.base.VerifyException",
      "message" : "All computed statistics must be used",
      "suppressed" : [ ],
      "stack" : [ "com.google.common.base.Verify.verify(Verify.java:123)", "com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)", "com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)", "com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)", "com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)", "com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)", "com.facebook.presto.operator.Driver.processInternal(Driver.java:379)", "com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)", "com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)", "com.facebook.presto.operator.Driver.processFor(Driver.java:276)", "com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)", "com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)", "com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)", "com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)", "java.lang.Thread.run(Thread.java:748)" ],
      "errorCode" : {
        "code" : 65536,
        "name" : "GENERIC_INTERNAL_ERROR",
        "type" : "INTERNAL_ERROR"
      }
    }
  },
  "failureInfo" : {
    "type" : "com.google.common.base.VerifyException",
    "message" : "All computed statistics must be used",
    "suppressed" : [ ],
    "stack" : [ "com.google.common.base.Verify.verify(Verify.java:123)", "com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1075)", "com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:166)", "com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:736)", "com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$31(LocalExecutionPlanner.java:2261)", "com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)", "com.facebook.presto.operator.Driver.processInternal(Driver.java:379)", "com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)", "com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)", "com.facebook.presto.operator.Driver.processFor(Driver.java:276)", "com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)", "com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)", "com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)", "com.facebook.presto.$gen.Presto_0_220_dirty__0_220____20191021_094234_1.run(Unknown Source)", "java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)", "java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)", "java.lang.Thread.run(Thread.java:748)" ],
    "errorCode" : {
      "code" : 65536,
      "name" : "GENERIC_INTERNAL_ERROR",
      "type" : "INTERNAL_ERROR"
    }
  },
  "errorCode" : {
    "code" : 65536,
    "name" : "GENERIC_INTERNAL_ERROR",
    "type" : "INTERNAL_ERROR"
    
    
    one of many partitionids (s3 based hive connector):
    "datestr=20190928/journal_date=2019-08-12 00%3A00%3A00/books_name=xx yy aa bb cc dd/books_id=123"
    
    17463346 rows in the table, 70 normal columns and 4 partitioned columns (varchar,timestamp,varchar(30),bigint), parquet format, presto v0.220, total of 582 partitions
    
    If i were a gambler i would guess timestamp data type for partition column is problematic when s3 encodes values. UPDATE: confirmed this theory, by copying the parquet files under a folder of type string (and make hive table partitioned on that string data type column instead of timestamp data type column) then it worked. ie copied journal_date=2019-09-01 00%3A00%3A00/ to journal_date=20190901/

**Comment by tooptoop4** [comment]
@jessesleeping do you know if analyze was tested when one of partition columns is timestamp data type?
