### ISSUE TITLE
Time zone not supported: Asia/Qostanay

### ISSUE THREAD

**Issue by davidrabinowitz** [prestodb/presto#13628]
When trying to compile the latest version I get the following error in presto-main:

```
[ERROR] test(com.facebook.presto.util.TestTimeZoneUtils)  Time elapsed: 0.02 s  <<< FAILURE!
com.facebook.presto.spi.type.TimeZoneNotSupportedException: Time zone not supported: Asia/Qostanay
	at com.facebook.presto.spi.type.TimeZoneKey.getTimeZoneKey(TimeZoneKey.java:131)
	at com.facebook.presto.util.TestTimeZoneUtils.test(TestTimeZoneUtils.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Looking at presto-spi/src/main/resources/com/facebook/presto/spi/type/zone-index.properties I see that Asia/Qostanay is missing.

How can I add it?

**Comment by shixuan-fan** [comment]
This timezone is introduced in tzdata2018h according to https://www.oracle.com/technetwork/java/javase/tzdata-versions-138805.html. I'm not entirely sure  how it works though. 

@rongrong Do you have some idea?

**Comment by davidrabinowitz** [comment]
The problem is that this time zone is missing from presto-spi/src/main/resources/com/facebook/presto/spi/type/zone-index.properties. The presto-spi/src/test/java/com/facebook/presto/spi/type/TestTimeZoneKey.java test should be fixed as well - fixing the hash at line https://github.com/prestodb/presto/blob/8ac4b8466a7db96d9941e27cecf7aaf64c85bfaf/presto-spi/src/test/java/com/facebook/presto/spi/type/TestTimeZoneKey.java#L216.

I would have submitted a PR, but I don't have the CLA yet.

**Comment by JK-Rubi** [comment]
Running into the same error.  Can we look into getting this addressed?
