### ISSUE TITLE
presto ：Error fetching results

### ISSUE THREAD

**Issue by LiClass** [prestodb/presto#13642]
Caused by: java.sql.SQLException: Error fetching results
at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:155)
at com.alibaba.druid.pool.DruidPooledResultSet.next(DruidPooledResultSet.java:69)
at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:92)
at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:60)
at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:466)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
... 51 more
Caused by: com.facebook.presto.jdbc.internal.guava.base.VerifyException
at com.facebook.presto.jdbc.internal.guava.base.Verify.verify(Verify.java:99)
at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1815)
at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1759)

server version:0.213
cli jdbc version:0.213

There are multiple identical requests，But there is 10% query failure,and Is completely random

**Comment by LiClass** [comment]
#presto.version=presto-main:0.203
coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=9090
query.max-memory=500GB
discovery-server.enabled=true
discovery.uri=http://xxxxx:9090
exchange.http-client.request-timeout=50s
exchange.http-client.idle-timeout=2m
exchange.http-client.max-connections=1000
exchange.http-client.max-connections-per-server=1000
query.max-memory-per-node=5GB
scheduler.http-client.max-connections=1000
scheduler.http-client.max-connections-per-server=1000
event.http-client.max-connections-per-server=100
discovery.http-client.max-connections-per-server=100
query.max-run-time=600s
task.concurrency=1
deprecated.legacy-map-subscript=true
##deprecated.legacy-round-n-bigint=true
deprecated.legacy-map-subscript=true

**Comment by LiClass** [comment]
catalog is hive,coordinator=1,works=49

CPU: | 64 
-- | --
memory: | 128 GB

**Comment by ameyamahajan** [comment]
How did this resolve? By changing the `discover.uri` to different port help?

**Comment by Audi0s1ave** [comment]
Were you able to get the reason behind - Error fetching results? Or was it totally random?
