### ISSUE TITLE
unable to start prestodb with ES connector.

### ISSUE THREAD

**Issue by kant111** [prestodb/presto#13679]
I followed the doc on setting up the prestodb with ES connector. I am unable to start. I get the following error

```
2019-11-09T17:25:03.746-0800	ERROR	main	com.facebook.presto.server.PrestoServer	com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'elasticsearch.default-schema' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'elasticsearch.default-schema' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
	at com.facebook.presto.elasticsearch.ElasticsearchConnectorFactory.create(ElasticsearchConnectorFactory.java:72)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:358)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:217)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:209)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:195)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:132)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'elasticsearch.default-schema' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:233)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:240)
	at com.facebook.presto.elasticsearch.ElasticsearchConnectorFactory.create(ElasticsearchConnectorFactory.java:67)
	... 8 more


2019-11-09T17:25:03.747-0800	INFO	Thread-88	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
```

Here are my configs

`presto-server-0.228/etc/elasticsearch/es.json`

```
{
    "tableName": "es",
    "schemaName": "default",
    "host": "localhost",
    "port": 9200,
    "clusterName": "elasticsearch",
    "index": "twitter",
    "type": "user"
}
```
and 

`presto-server-0.228/etc/catalog/elasticsearch.properties`

```
connector.name=elasticsearch
elasticsearch.default-schema=default
elasticsearch.table-description-directory=etc/elasticsearch/
elasticsearch.scroll-size=1000
elasticsearch.scroll-timeout=2s
elasticsearch.request-timeout=2s
elasticsearch.max-request-retries=5
elasticsearch.max-request-retry-time=10s
```

What is the default-schema? what does it mean in elasticsearch terms?

Also `"type"` field in the table definitions should be optional since ES >= 6.0 there are no types. I am using ES 6.4.3. Any ideas on what the fix is?

**Comment by kant111** [comment]
Looks to me there are bunch of issues going on here.

1) If I remove `elasticsearch.default-schema=default` from `elasticsearch.properties` and add  `"schemaName": "default"` in `presto-server-0.228/etc/elasticsearch/es.json` although documentation says its optional it works. otherwise, it fails.
2) the columns list in `es.json` looks like it must be specified although documentation says it is optional.
3) The ES port must `ES transport port` 9300 not the ES HTTP port. The transport port for the ES will be deprecated soon.
4) The prestodb documentation says it is recommended to use ES >= 6.0  but in 6.0 there are no types only indices however the presto db documentation says it is required.

**Comment by kant111** [comment]
upgraded to presto-324. that fixed all my issues.

**Comment by hqisog** [comment]
> upgraded to presto-324. that fixed all my issues.

can you give me  you operate documentation ?

**Comment by findepi** [comment]
> > upgraded to presto-324. that fixed all my issues.
> 
> can you give me you operate documentation ?

@hqisog Presto 3xx releases, @kant111 mentioned here, are maintained at https://github.com/prestosql/presto.
You can download the release build from https://prestosql.io/download.html and you can find documentation at https://prestosql.io/docs/current/
Ask on the Presto Community Slack (https://prestosql.io/slack.html) if you want to learn more.

**Comment by hqisog** [comment]
@findepi  i want use presto-elasticsearch ,but has erros;

Schema 'my_schema' does not exist

Here are my configs


userdemo.json

{
  "tableName": "userdemo",
  "schemaName": "my_schema",
  "host": "**.*.*.***",
  "port": 9300,
  "clusterName": "leno",
  "index": "userdemo",
  "type": "doc",
  "columns": [
      {
          "name": "key",
          "type": "varchar",
          "jsonPath": "key",
          "jsonType": "varchar",
          "ordinalPosition": "0"
      }
  ]
}

./presto --server localhost:8080 --catalog elasticsearch --schema my_schema

when i'm  run ：   select *　from elasticsearch.my_schema.userdemo ;

there find this error,
Schema 'my_schema' does not exist

why ？

**Comment by rongrong** [comment]
cc @zhenxiao

**Comment by zhenxiao** [comment]
@hqisog could you please share which version you are using, and full error stack?

**Comment by hqisog** [comment]
@zhenxiao  　presto download from   https://repo1.maven.org/maven2/com/facebook/presto/presto-server/0.228/presto-server-0.228.tar.gz  　

i coulden't find any error from  server.log or launcher.log or http-request.log,
but when i query sql like  select * from leno.stu2,  Errors found are as follows.

[leno@wh-8-148 presto-server-0.231.1]$ bin/presto-cli --server 10.1.8.148:8080 --catalog elasticsearch --debug
presto> select * from leno.stu2;
Query 20200214_005558_00000_fwe5x failed: line 1:15: Schema leno does not exist
com.facebook.presto.sql.analyzer.SemanticException: line 1:15: Schema leno does not exist
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:982)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:268)
        at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:282)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1919)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1091)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:268)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:282)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:292)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:806)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:268)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:282)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:260)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
        at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:751)
        at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
        at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:304)
        at com.facebook.presto.$gen.Presto_0_231_1_fc5b682____20200213_135205_1.run(Unknown Source)
        at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
select * from leno.stu2

**Comment by zhenxiao** [comment]
Hi @hqisog 

could you please try:
userdemo.json -> my_schema.userdemo.json

**Comment by hqisog** [comment]
> Hi @hqisog
> 
> could you please try:
> userdemo.json -> my_schema.userdemo.json

I already tried that,same error.

**Comment by zhenxiao** [comment]
could you please share elasticsearch.properties
and run a
show schemas from elasticsearch;
share the result?

**Comment by hqisog** [comment]
can you give me a document about this operation？ I follow official document, it’s doesn't work.&nbsp;



---Original---

**Comment by zhenxiao** [comment]
wired. Follow the official document should work:
https://prestodb.io/docs/current/connector/elasticsearch.html
