### ISSUE TITLE
Cast conversion

### ISSUE THREAD

**Issue by gsarode39** [prestodb/presto#13694]
Does presto support array<array<string>>

I am constantly getting this error: 

`class org.apache.parquet.io.PrimitiveColumnIO cannot be cast to class org.apache.parquet.io.GroupColumnIO (org.apache.parquet.io.PrimitiveColumnIO and org.apache.parquet.io.GroupColumnIO are in unnamed module of loader io.prestosql.server.PluginClassLoader`

This error does not specify which column the error is thrown at, but my suspicion is on the column with the data structure that I mentioned above.

**Comment by rongrong** [comment]
Presto supports array of array in general. The error seems to be from Parquet. @zhenxiao do you have some insights?

**Comment by zhenxiao** [comment]
Yep, this is from Parquet stack. Presto should be able to support array<array> for Parquet.
could you please share ur table definition, including the schema? And ur query? A full stack trace would also be helpful.
BTW, seems you are using prestosql. which might have some difference from prestodb. anyway, stacktrace from prestosql is also helpful.

**Comment by findepi** [comment]
> seems you are using prestosql

@gsarode39 
Presto SQL releases are maintained at https://github.com/prestosql/presto. You should report an issue at https://github.com/prestosql/presto/issues/
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/community.html)

**Comment by kishoreduraisam** [comment]
@findepi @zhenxiao  Is this an open issue or is it related to the way table is defined? I am running into the same issue for the past few days and havent been able to figure this out. Here is how some of my columns are defined
product_prodcontainerid ARRAY<VARCHAR>,
product_type ARRAY<VARCHAR>,
product_quantity BIGINT,
product_id ARRAY<VARCHAR>,
product_name ARRAY<VARCHAR>,

and here is the full stacktrace 
Query 20200602_084111_00044_7p4v4 failed: class org.apache.parquet.io.GroupColumnIO cannot be cast to class org.apache.parquet.io.PrimitiveColumnIO (org.apache.parquet.io.GroupColumnIO and org.apache.parquet.io.PrimitiveColumnIO are in unnamed module of loader io.prestosql.server.PluginClassLoader @5da799)
java.lang.ClassCastException: class org.apache.parquet.io.GroupColumnIO cannot be cast to class org.apache.parquet.io.PrimitiveColumnIO (org.apache.parquet.io.GroupColumnIO and org.apache.parquet.io.PrimitiveColumnIO are in unnamed module of loader io.prestosql.server.PluginClassLoader @5da799)
        at io.prestosql.plugin.hive.parquet.ParquetColumnIOConverter.constructField(ParquetColumnIOConverter.java:92)
        at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.lambda$createPageSource$6(ParquetPageSourceFactory.java:264)
        at java.base/java.util.Optional.flatMap(Optional.java:294)
        at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:262)
        at io.prestosql.plugin.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:132)
        at io.prestosql.plugin.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:174)
        at io.prestosql.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:105)
        at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:57)
        at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
        at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_333____20200528_152651_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834

Any help is much appreciated.

**Comment by findepi** [comment]
@kishoreduraisam Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)

**Comment by VijethKashyapTR** [comment]
> Does presto support array<array>
> 
> I am constantly getting this error:
> 
> `class org.apache.parquet.io.PrimitiveColumnIO cannot be cast to class org.apache.parquet.io.GroupColumnIO (org.apache.parquet.io.PrimitiveColumnIO and org.apache.parquet.io.GroupColumnIO are in unnamed module of loader io.prestosql.server.PluginClassLoader`
> 
> This error does not specify which column the error is thrown at, but my suspicion is on the column with the data structure that I mentioned above.

Did you find any workaround for this? It's 2023 and we are still seeing this

**Comment by pwrstar** [comment]
I'm having similar issue, any updates on this issue?
