### ISSUE TITLE
I am getting this in v0.220:

### ISSUE THREAD

**Issue by SunHao1234** [prestodb/presto#13701]
I am getting this in v0.220:
2019-06-17T13:57:33.645Z        ERROR   20190617_135733_00068_wehgw.1.0-0-101   com.facebook.presto.operator.Driver     Error closing operator 0 for task 20190617_135733_00068_wehgw.1.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:899)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6679)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:74)
        at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:185)
        at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:174)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:546)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:406)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at com.facebook.presto.$gen.Presto_0_220____20190617_135337_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

_Originally posted by @tooptoop4 in https://github.com/prestodb/presto/issues/10644#issuecomment-502694944_

**Comment by yingsu00** [comment]
@SunHao1234 Do you still have the same error in latest build 0.229? How to reproduce the error?
