### ISSUE TITLE
Oracle catalog license error

### ISSUE THREAD

**Issue by minhnguyenvan95** [prestodb/presto#13885]
presto version presto:302-e.7

my catalog properties
```
connector.name=oracle
connection-url=jdbc:oracle:thin:@x:1521/tcbsweb
connection-user=x
connection-password=x
```

presto server error log
```
resto-acb_1_4e5da9e79fd7 | 2019-12-20T08:51:58.208Z	INFO	main	Bootstrap	PROPERTY                  DEFAULT  RUNTIME  DESCRIPTION
presto-acb_1_4e5da9e79fd7 | 2019-12-20T08:51:58.208Z	INFO	main	Bootstrap	memory.max-data-per-node  128MB    128MB
presto-acb_1_4e5da9e79fd7 | 2019-12-20T08:51:58.208Z	INFO	main	Bootstrap	memory.splits-per-node    8        8
presto-acb_1_4e5da9e79fd7 | 2019-12-20T08:51:58.354Z	INFO	main	io.prestosql.metadata.StaticCatalogStore	-- Added catalog memory using connector memory --
presto-acb_1_4e5da9e79fd7 | 2019-12-20T08:51:58.354Z	INFO	main	io.prestosql.metadata.StaticCatalogStore	-- Loading catalog /etc/presto/catalog/acbo-oracle.properties --
presto-acb_1_4e5da9e79fd7 | 2019-12-20T08:51:58.355Z	ERROR	main	io.prestosql.server.PrestoServer	Couldn't find a valid license, please make sure the license file path is correct
presto-acb_1_4e5da9e79fd7 | io.prestosql.spi.license.LicenseManager$PrestoLicenseException: Couldn't find a valid license, please make sure the license file path is correct
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.license.goto.checkAllFeatures(PrestoLicenseManager.java:62)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.spi.license.LicenseManager.checkFeature(LicenseManager.java:39)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.plugin.jdbc.LicenceCheckingConnectorFactory.create(LicenceCheckingConnectorFactory.java:52)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:326)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:199)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:191)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:177)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.server.PrestoServer.run(PrestoServer.java:139)
presto-acb_1_4e5da9e79fd7 | 	at io.prestosql.server.PrestoServer.main(PrestoServer.java:77)
presto-acb_1_4e5da9e79fd7 | 

```

**Comment by findepi** [comment]
In general, Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)

I see you're using Starburst. For license questions should contact Starburst directly @ https://www.starburstdata.com/contact/
