### ISSUE TITLE
Error when connecting to Cassandra

### ISSUE THREAD

**Issue by alvaropalmeirao** [prestodb/presto#13994]
Hello,
 I have a cassandra cluster running on port 9042 (SSL) and 9142 (non-SSL). I've configured the PrestoDB catalog to connect via PrestoDB:
```
connector.name=cassandra
cassandra.contact-points=10.x.x.x
cassandra.username=cassandra
cassandra.password=xxx
cassandra.native-protocol-port=9142
```
And when i am connecting to my cluster via presto-cli i'm getting this error:
```
presto-cli --catalog cassandra --schema xxx --debug
presto:xxx> select * from test;
Query 20200122_132804_00009_cv7qv failed: initialArraySize cannot be negative but was: -2147483648
java.lang.IllegalArgumentException: initialArraySize cannot be negative but was: -2147483648
	at com.datastax.driver.$internal.com.google.common.collect.CollectPreconditions.checkNonnegative(CollectPreconditions.java:39)
	at com.datastax.driver.$internal.com.google.common.collect.Lists.newArrayListWithCapacity(Lists.java:174)
	at com.datastax.driver.core.HostConnectionPool.initAsync(HostConnectionPool.java:113)
	at com.datastax.driver.core.SessionManager.replacePool(SessionManager.java:323)
	at com.datastax.driver.core.SessionManager.maybeAddPool(SessionManager.java:359)
	at com.datastax.driver.core.SessionManager.createPools(SessionManager.java:119)
	at com.datastax.driver.core.SessionManager.initAsync(SessionManager.java:89)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:332)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
	at com.datastax.driver.core.DelegatingCluster.connect(DelegatingCluster.java:71)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:164)
	at com.facebook.presto.cassandra.NativeCassandraSession.executeWithSession(NativeCassandraSession.java:536)
	at com.facebook.presto.cassandra.NativeCassandraSession.getKeyspaceByCaseInsensitiveName(NativeCassandraSession.java:257)
	at com.facebook.presto.cassandra.NativeCassandraSession.getTable(NativeCassandraSession.java:190)
	at com.facebook.presto.cassandra.CassandraMetadata.getTableHandle(CassandraMetadata.java:104)
	at com.facebook.presto.cassandra.CassandraMetadata.getTableHandle(CassandraMetadata.java:66)
	at com.facebook.presto.metadata.MetadataManager.getTableHandle(MetadataManager.java:326)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:916)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1852)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1031)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:281)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:746)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:271)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:249)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:79)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:71)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:744)
	at com.facebook.presto.execution.SqlQueryManager.createQueryInternal(SqlQueryManager.java:366)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$4(SqlQueryManager.java:305)
	at com.facebook.presto.$gen.Presto_0_224_b3a49f7____20200122_132523_1.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The table exists in my schema and the user has permissions to access it.

**Comment by navinko** [comment]
Hi @alvaropalmeirao , Did you get the Root cause and what was the issue for the below error.

initialArraySize cannot be negative but was: -2147483648
