### ISSUE TITLE
hive connection failure

### ISSUE THREAD

**Issue by vekselman** [prestodb/presto#14028]
Hello everyone,
Presto server failing to start with hive catalog.
hive.properties:
`connector.name=hive-hadoop2
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.security=read-olny
hive.metastore.uri=thrift://XXX:9083
hive.metastore.authentication.type=KERBEROS
hive.metastore.username=presto
hive.metastore.client.keytab=/etc/security/keytabs/presto.keytab
hive.metastore.client.principal=presto@EXAMPLE.COM
hive.metastore.service.principal=hive/_HOST@EXAMPLE.COM
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.presto.principal=presto@EXAMPLE.COM
hive.hdfs.presto.keytab=/etc/security/keytabs/presto.keytab
`

`2020-01-29T14:06:55.627+0200    ERROR   main    com.facebook.presto.server.PrestoServer Guice configuration errors:

1) Explicit bindings are required and com.facebook.presto.spi.connector.ConnectorAccessControl is not explicitly bound.
  while locating com.facebook.presto.spi.connector.ConnectorAccessControl

1 error
com.google.inject.ConfigurationException: Guice configuration errors:

1) Explicit bindings are required and com.facebook.presto.spi.connector.ConnectorAccessControl is not explicitly bound.
  while locating com.facebook.presto.spi.connector.ConnectorAccessControl

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:144)
        at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:364)
        at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:222)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:214)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:200)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:132)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:74)
`

**Comment by powerLambda** [comment]
@vekselman how do you resolve this issue? I'm facing similar exception stack, thanks.

**Comment by maxmithun** [comment]
@vekselman I'm facing similar exception . your update here will be appreciated.
