### ISSUE TITLE
Testcase Failures when trying to upgrade to hive-apache 3.0.0

### ISSUE THREAD

**Issue by zhenxiao** [prestodb/presto#14052]
[ERROR] testDoubleSequence(com.facebook.presto.orc.TestOrcReader)  Time elapsed: 0.124 s  <<< FAILURE!
java.lang.AssertionError: match not found for middle section
	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.orc.TestingOrcPredicate$BasicOrcPredicate.matchMiddleSection(TestingOrcPredicate.java:226)
	at com.facebook.presto.orc.TestingOrcPredicate$BasicOrcPredicate.matches(TestingOrcPredicate.java:195)
	at com.facebook.presto.orc.TestingOrcPredicate$MultiOrcPredicate.lambda$matches$0(TestingOrcPredicate.java:155)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at com.facebook.presto.orc.TestingOrcPredicate$MultiOrcPredicate.matches(TestingOrcPredicate.java:155)
	at com.facebook.presto.orc.StripeReader.selectRowGroups(StripeReader.java:445)
	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:168)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextStripe(AbstractOrcRecordReader.java:504)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextRowGroup(AbstractOrcRecordReader.java:399)
	at com.facebook.presto.orc.AbstractOrcRecordReader.prepareNextBatch(AbstractOrcRecordReader.java:454)
	at com.facebook.presto.orc.OrcBatchRecordReader.nextBatch(OrcBatchRecordReader.java:109)
	at com.facebook.presto.orc.OrcTester.assertFileContentsPresto(OrcTester.java:886)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:624)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:594)
	at com.facebook.presto.orc.OrcTester.testRoundTripTypes(OrcTester.java:510)
	at com.facebook.presto.orc.OrcTester.testRoundTripTypes(OrcTester.java:498)
	at com.facebook.presto.orc.OrcTester.testRoundTrip(OrcTester.java:340)
	at com.facebook.presto.orc.OrcTester.testRoundTrip(OrcTester.java:325)
	at com.facebook.presto.orc.AbstractTestOrcReader.testDoubleSequence(AbstractTestOrcReader.java:325)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] testDwrfInvalidCheckpointsForRowGroupDictionary(com.facebook.presto.orc.TestOrcReader)  Time elapsed: 0.213 s  <<< FAILURE!
java.lang.AssertionError: match not found for middle section
	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.orc.TestingOrcPredicate$BasicOrcPredicate.matchMiddleSection(TestingOrcPredicate.java:226)
	at com.facebook.presto.orc.TestingOrcPredicate$BasicOrcPredicate.matches(TestingOrcPredicate.java:195)
	at com.facebook.presto.orc.TestingOrcPredicate$MultiOrcPredicate.lambda$matches$0(TestingOrcPredicate.java:155)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at com.facebook.presto.orc.TestingOrcPredicate$MultiOrcPredicate.matches(TestingOrcPredicate.java:155)
	at com.facebook.presto.orc.StripeReader.selectRowGroups(StripeReader.java:445)
	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:168)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextStripe(AbstractOrcRecordReader.java:504)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextRowGroup(AbstractOrcRecordReader.java:399)
	at com.facebook.presto.orc.AbstractOrcRecordReader.prepareNextBatch(AbstractOrcRecordReader.java:454)
	at com.facebook.presto.orc.OrcBatchRecordReader.nextBatch(OrcBatchRecordReader.java:109)
	at com.facebook.presto.orc.OrcTester.assertFileContentsPresto(OrcTester.java:886)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:624)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:600)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:582)
	at com.facebook.presto.orc.AbstractTestOrcReader.testDwrfInvalidCheckpointsForRowGroupDictionary(AbstractTestOrcReader.java:475)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] testDwrfInvalidCheckpointsForStripeDictionary(com.facebook.presto.orc.TestOrcReader)  Time elapsed: 1.218 s  <<< FAILURE!
java.lang.AssertionError: match not found for middle section
	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.orc.TestingOrcPredicate$BasicOrcPredicate.matchMiddleSection(TestingOrcPredicate.java:226)
	at com.facebook.presto.orc.TestingOrcPredicate$BasicOrcPredicate.matches(TestingOrcPredicate.java:195)
	at com.facebook.presto.orc.TestingOrcPredicate$MultiOrcPredicate.lambda$matches$0(TestingOrcPredicate.java:155)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at com.facebook.presto.orc.TestingOrcPredicate$MultiOrcPredicate.matches(TestingOrcPredicate.java:155)
	at com.facebook.presto.orc.StripeReader.selectRowGroups(StripeReader.java:445)
	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:168)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextStripe(AbstractOrcRecordReader.java:504)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextRowGroup(AbstractOrcRecordReader.java:399)
	at com.facebook.presto.orc.AbstractOrcRecordReader.prepareNextBatch(AbstractOrcRecordReader.java:454)
	at com.facebook.presto.orc.OrcBatchRecordReader.nextBatch(OrcBatchRecordReader.java:109)
	at com.facebook.presto.orc.OrcTester.assertFileContentsPresto(OrcTester.java:886)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:624)
	at com.facebook.presto.orc.OrcTester.assertRoundTrip(OrcTester.java:594)
	at com.facebook.presto.orc.OrcTester.testRoundTripTypes(OrcTester.java:510)
	at com.facebook.presto.orc.OrcTester.testRoundTripTypes(OrcTester.java:498)
	at com.facebook.presto.orc.OrcTester.testRoundTrip(OrcTester.java:340)
	at com.facebook.presto.orc.OrcTester.testRoundTrip(OrcTester.java:325)
	at com.facebook.presto.orc.AbstractTestOrcReader.testDwrfInvalidCheckpointsForStripeDictionary(AbstractTestOrcReader.java:488)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

@mbasmanova

**Comment by zhenxiao** [comment]
the upgrade effort:
https://github.com/prestodb/presto/pull/14044

**Comment by zhenxiao** [comment]
@aweisberg

**Comment by mbasmanova** [comment]
CC: @prestodb/aria

**Comment by bhhari** [comment]
The issue is happening because of the bloom filter that is written is not passing the predicate. For example, it fails to find some values (0.4) which results in failing the predicate. As a workaround
commenting the following lin OrcTester.java L 2033 
`orderTableProperties.setProperty("orc.bloom.filter.write.version", "original");` works.
 I'm going to verify what changed in the BloomFilter read/write with this upgrade and update the issue.
cc : @mbasmanova  @zhenxiao

**Comment by zhenxiao** [comment]
thank you, @bhhari
