### ISSUE TITLE
Fix reading Map<int,int> column with negative keys

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#14232]
Currently the SubfieldTokenizer throws parse exception when we try to access a map with negative key.

`Select map_col[-1] from map_table`
```
Caused by: com.facebook.presto.spi.PrestoException: Invalid subfield path: 'map_col[‸-1]'
	at com.facebook.presto.spi.SubfieldTokenizer.invalidSubfieldPath(SubfieldTokenizer.java:262)
	at com.facebook.presto.spi.SubfieldTokenizer.matchUnquotedSubscript(SubfieldTokenizer.java:167)
	at com.facebook.presto.spi.SubfieldTokenizer.computeNext(SubfieldTokenizer.java:109)
	at com.facebook.presto.spi.SubfieldTokenizer.tryToComputeNext(SubfieldTokenizer.java:69)
	at com.facebook.presto.spi.SubfieldTokenizer.hasNext(SubfieldTokenizer.java:63)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at com.facebook.presto.spi.Subfield.<init>(Subfield.java:225)
```
cc: @mbasmanova

**Comment by mbasmanova** [comment]
CC: @prestodb/aria
