### ISSUE TITLE
how can I use druid connector

### ISSUE THREAD

**Issue by Doslin** [prestodb/presto#14231]

**Comment by beepupa** [comment]
connector.name=druid

druid.broker-url=http://ip:port
druid.coordinator-url=http://ip:port
druid.schema-name=druid

**Comment by manoveg** [comment]
Hi,
I recently experimented with using druid connector and get following error message:
`INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog properties etc/catalog/druid.properties --
2020-03-30T23:57:06.298Z	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog druid --
2020-03-30T23:57:06.298Z	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector druid
java.lang.IllegalArgumentException: No factory for connector druid
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:216)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:199)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:135)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:77)
`

I use druid Version: 0.17.0 and PRESTO_VERSION=0.233.1

**Comment by skyahead** [comment]
you want to create a directory called 'presto-druid' under plugin/, inside 'presto-druid' put the all the jars in presto-druid-version.zip. The latest zip file is here: https://repo1.maven.org/maven2/com/facebook/presto/presto-druid/0.233.1/presto-druid-0.233.1.zip

**Comment by mysticaltech** [comment]
Thank you @skyahead!
