### ISSUE TITLE
broker Druid query should return Json Array

### ISSUE THREAD

**Issue by beepupa** [prestodb/presto#14251]
当我使用Druid连接器的时候。执行 select * from test limit 10，报错。请问我该怎么解决？
presto:druid> select * from test limit 10;

Query 20200316_075245_00017_54mhe, FAILED, 1 node
Splits: 17 total, 0 done (0.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200316_075245_00017_54mhe failed: broker Druid query should return Json Array

**Comment by pigxuyu** [comment]
you need show more detail，like exception

**Comment by hey-jude** [comment]
I saw same error.
Here is stack trace.

```
2020-04-16T15:59:54.247+0900    ERROR   remote-task-callback-558        com.facebook.presto.execution.StageExecutionStateMachine        Stage execution 20200416_065949_00030_n86zw.1.0 failed
java.lang.IllegalArgumentException: broker Druid query should return Json Array
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
        at com.facebook.presto.druid.DruidBrokerPageSource.getNextPage(DruidBrokerPageSource.java:120)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
        at com.facebook.presto.$gen.Presto_0_233_1_2d75403____20200414_101626_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
