### ISSUE TITLE
Explain (Type IO) fails when Aria is enabled

### ISSUE THREAD

**Issue by bhhari** [prestodb/presto#14287]
```
com.facebook.presto.spi.PrestoException: Unsupported data type in EXPLAIN (TYPE IO): double
	at com.facebook.presto.sql.planner.planPrinter.IOPlanPrinter$IOPlanVisitor.getVarcharValue(IOPlanPrinter.java:549)
	at com.facebook.presto.sql.planner.planPrinter.IOPlanPrinter$IOPlanVisitor.formatMarker(IOPlanPrinter.java:535)
	at com.facebook.presto.sql.planner.planPrinter.IOPlanPrinter$IOPlanVisitor.lambda$null$1(IOPlanPrinter.java:515)
```

**Comment by mbasmanova** [comment]
CC: @prestodb/aria
