### ISSUE TITLE
PruneUnreferencedOutputs filter no output column, druid source still read the column cause exception

### ISSUE THREAD

**Issue by pigxuyu** [prestodb/presto#14369]
sql:
select b.name from druid.druid.url_insight a join mysql.ifly_cpcc_ad_basic.t_other_plat b on cast(a.plat_id as int) = b.id where __time >= '2020-04-08 00:00' and __time < '2020-04-08 00:01' limit 10;

PruneUnreferencedOutputs filter the column of __time, druid DruidBrokerPageSource still parse json to search the column of  __time

@zhenxiao

**Comment by pigxuyu** [comment]
#14368

**Comment by zhenxiao** [comment]
seems __time should be part of druid query, right? druid connector needs to keep the time range.

**Comment by pigxuyu** [comment]
> seems __time should be part of druid query, right? druid connector needs to keep the time range.

@zhenxiao 
Sorry, I didn't give you enough information.

druid table:
![image](https://user-images.githubusercontent.com/14072245/79034802-780efa80-7beb-11ea-8d19-b837cc77cae5.png)

mysql table:
![image](https://user-images.githubusercontent.com/14072245/79034862-c3c1a400-7beb-11ea-8596-a806523fe2b6.png)


exception:
`com.facebook.presto.spi.PrestoException: Cannot cast '2020-04-08T00:00:00.000+08:00' to INT
	at com.facebook.presto.type.VarcharOperators.castToInteger(VarcharOperators.java:198)
	at com.facebook.presto.$gen.PageProjectionWork_20200411_035900_13.evaluate(Unknown Source)
	at com.facebook.presto.$gen.PageProjectionWork_20200411_035900_13.process(Unknown Source)
	at com.facebook.presto.operator.project.DictionaryAwarePageProjection$DictionaryAwarePageProjectionWork.process(DictionaryAwarePageProjection.java:175)
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:296)
	at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:184)
	at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315)
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79)
	at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:111)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:290)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:237)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:381)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:677)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_null__testversion____20200411_033746_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`

dql:
SELECT __time, plat_id FROM url_insight WHERE ((__time >= '2020-04-08 00:00:00.000') AND (__time < '2020-04-08 00:01:00.000'))
