### ISSUE TITLE
Not able to start presto server

### ISSUE THREAD

**Issue by luckyskg** [prestodb/presto#14378]
I am trying to setup a presto server with minio s3 gateway

Getting the below error
```
2020-04-12T18:32:08.413+0530	INFO	main	com.facebook.presto.server.PluginManager	Registering connector tpch
2020-04-12T18:32:08.414+0530	INFO	main	com.facebook.presto.server.PluginManager	-- Finished loading plugin /Users/sandeep/projects/data/plugin/tpch --
2020-04-12T18:32:08.421+0530	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog properties etc/catalog/minio.properties --
2020-04-12T18:32:08.421+0530	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog minio --
2020-04-12T18:32:09.216+0530	ERROR	main	com.facebook.presto.server.PrestoServer	java.lang.NoSuchFieldException: modifiers
java.lang.AssertionError: java.lang.NoSuchFieldException: modifiers
	at com.facebook.presto.hadoop.HadoopFileSystemCache.setFinalStatic(HadoopFileSystemCache.java:50)
	at com.facebook.presto.hadoop.HadoopFileSystemCache.initialize(HadoopFileSystemCache.java:31)
	at com.facebook.presto.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:37)
	at com.facebook.presto.hive.HdfsEnvironment$$FastClassByGuice$$a9f55374.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:245)
	at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:132)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:364)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:222)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:214)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:200)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:135)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:77)
Caused by: java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
	at com.facebook.presto.hadoop.HadoopFileSystemCache.setFinalStatic(HadoopFileSystemCache.java:41)
	... 47 more
```

*config.properties* :
```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8081
query.max-memory=5GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery-server.enabled=true
discovery.uri=http://localhost:8081
```

*catalog properties*
```
connector.name=hive-hadoop2
hive.metastore=file
hive.metastore.catalog.dir=s3://xxxxminio/
hive.allow-drop-table=true
hive.s3.aws-access-key=xxxxxxxxxxxxxxxx
hive.s3.aws-secret-key=xxxxxxxxxxxxxxxxxxxxxxxx
hive.s3.endpoint=http://127.0.0.1:9000
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
hive.s3select-pushdown.enabled=true
```

*node.properties*:
```
node.environment=dev
node.id=7513730d-c663-4340-ae5d-6e74440683d3
node.data-dir=/Users/sandeep/projects/data
```

*java version*:
```
openjdk 13.0.2 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Please let me know the fix for this issue. I am new to to Java. Just trying to setup presto server with minio connector and use it as my ML datastore

**Comment by mbasmanova** [comment]
Which version of Presto are you on?

CC: @jainxrohit

**Comment by rschlussel** [comment]
Not enough information, so closing this issue.
