### ISSUE TITLE
JSON Format reader does not fetch compression from source system

### ISSUE THREAD

**Issue by jainxrohit** [prestodb/presto#14401]
While adding the support for ZSTD write(https://github.com/prestodb/presto/pull/14396), we removed compression usage for zero row file creation.
However with this change, JSON format sources started failing, as it seems JSON reader can not fetch encoding information from the source system, hence it uses it from the configuration. 
So when we change the encoding configuration at run time, reading JSON format files fails, as it uses the wrong encoding to read.

How to reproduce:
1. Remove the JSON Format check from the HiveZeroRowFileCreator.generateZeroRowFile
2. Use None compression encoding for JSON format.
3. Create Table CREATE TABLE hive.tpch.partition6_json( orderkey bigint, linenumber integer ) WITH ( format = 'JSON', partitioned_by = ARRAY['linenumber'], bucketed_by=ARRAY['orderkey'], bucket_count=4);
4. insert into tpch.partition6_json values(1,1);
5. Select * from partition6_json;
The above steps should fail the select query and throw following stack trace:

```
com.facebook.presto.spi.PrestoException: Unexpected end of input stream
	at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:227)
	at com.facebook.presto.hive.HiveRecordCursor.advanceNextPosition(HiveRecordCursor.java:175)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:100)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:381)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:677)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_null__testversion____20200416_041640_2.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Unexpected end of input stream
	at org.apache.hadoop.io.compress.DecompressorStream.decompress(DecompressorStream.java:145)
	at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)
	at java.io.InputStream.read(InputStream.java:101)
	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:200)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:238)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:193)
	at org.apache.hadoop.mapred.LineRecordReader.skipUtfByteOrderMark(LineRecordReader.java:208)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:246)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:48)
	at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:209)
```

**Comment by jainxrohit** [comment]
cc: @mbasmanova @bhhari

**Comment by mbasmanova** [comment]
CC: @prestodb/aria @jbroll @sujay-jain
