### ISSUE TITLE
using presto to query druid could not return successfully

### ISSUE THREAD

**Issue by gaohaoning** [prestodb/presto#14413]
I have configured presto to use druid catalog:

------------------------------------------------------
connector.name=druid
druid.coordinator-url=http://XXXX:8081
druid.broker-url=http://XXXX:8082
druid.schema-name=druid
------------------------------------------------------

**and when I started the presto-cli it seems to be alright, but whatever I run queries, the results are as follow:**

root@aws-dc-presto01:~/presto-cli-0.233.1# ./presto --server XXXX:8080 --catalog druid --schema druid

presto:druid> select * from XXXX limit 100;
**Query 20200420_110030_00003_5wef4 failed: unsupported type: OTHER**

presto:druid> describe XXXX;

**Query 20200420_113803_00002_cjdy7, FAILED, 1 node
Splits: 19 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]**

**Query 20200420_113803_00002_cjdy7 failed: unsupported type: OTHER**

**The query can be ran on druid successfully, but when querying through presto, something went wrong as above.**
Meanwhile, the server-side outputs are as follows:

2020-04-20T11:38:04.010Z    ERROR   SplitRunner-3-103   com.facebook.presto.execution.executor.TaskExecutor Error processing Split 20200420_113803_00002_cjdy7.2.0.0-0 InformationSchemaSplit{tableHandle=druid:information_schema:columns, prefixes=[druid.druid.etl_umooc], addresses=[10.1.26.78:8080]} (start = 9.65779990532344E8, wall = 13 ms, cpu = 0 ms, wait = 18 ms, calls = 1)
java.lang.IllegalArgumentException: unsupported type: OTHER
    at com.facebook.presto.druid.DruidMetadata.getType(DruidMetadata.java:167)
    at com.facebook.presto.druid.DruidMetadata.toColumnMetadata(DruidMetadata.java:173)
    at com.facebook.presto.druid.DruidMetadata.lambda$getTableMetadata$2(DruidMetadata.java:96)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.druid.DruidMetadata.getTableMetadata(DruidMetadata.java:97)
    at com.facebook.presto.druid.DruidMetadata.listTableColumns(DruidMetadata.java:124)
    at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:590)
    at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:153)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:122)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:116)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
    at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
    at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
    at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:227)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
    at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
    at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
    at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
    at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
    at com.facebook.presto.$gen.Presto_0_233_1_2d75403____20200420_113454_1.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

2020-04-20T11:38:04.021Z    ERROR   remote-task-callback-3  com.facebook.presto.execution.StageExecutionStateMachine    Stage execution 20200420_113803_00002_cjdy7.2.0 failed
java.lang.IllegalArgumentException: unsupported type: OTHER
    at com.facebook.presto.druid.DruidMetadata.getType(DruidMetadata.java:167)
    at com.facebook.presto.druid.DruidMetadata.toColumnMetadata(DruidMetadata.java:173)
    at com.facebook.presto.druid.DruidMetadata.lambda$getTableMetadata$2(DruidMetadata.java:96)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.druid.DruidMetadata.getTableMetadata(DruidMetadata.java:97)
    at com.facebook.presto.druid.DruidMetadata.listTableColumns(DruidMetadata.java:124)
    at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:590)
    at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:153)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:122)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:116)
    at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
    at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
    at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
    at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:227)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
    at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
    at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
    at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
    at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
    at com.facebook.presto.$gen.Presto_0_233_1_2d75403____20200420_113454_1.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)

2020-04-20T11:38:04.066Z    INFO    query-execution-1   com.facebook.presto.event.QueryMonitor  TIMELINE: Query 20200420_113803_00002_cjdy7 :: Transaction:[c3d04f60-7bb8-41d4-94bf-d247ce1cb139] :: elapsed 263ms :: planning 123ms :: scheduling 118ms :: running 12ms :: finishing 10ms :: begin 2020-04-20T11:38:03.758Z :: end 2020-04-20T11:38:04.021Z

**Comment by gaohaoning** [comment]
> I have configured presto to use druid catalog:
> 
> ## connector.name=druid
> druid.coordinator-url=http://XXXX:8081
> druid.broker-url=http://XXXX:8082
> druid.schema-name=druid
> **and when I started the presto-cli it seems to be alright, but whatever I run queries, the results are as follow:**
> 
> root@aws-dc-presto01:~/presto-cli-0.233.1# ./presto --server XXXX:8080 --catalog druid --schema druid
> 
> presto:druid> select * from XXXX limit 100;
> **Query 20200420_110030_00003_5wef4 failed: unsupported type: OTHER**
> 
> presto:druid> describe XXXX;
> 
> **Query 20200420_113803_00002_cjdy7, FAILED, 1 node Splits: 19 total, 0 done (0.00%) 0:00 [0 rows, 0B] [0 rows/s, 0B/s]**
> 
> **Query 20200420_113803_00002_cjdy7 failed: unsupported type: OTHER**
> 
> **The query can be ran on druid successfully, but when querying through presto, something went wrong as above.**
> Meanwhile, the server-side outputs are as follows:
> 
> 2020-04-20T11:38:04.010Z ERROR SplitRunner-3-103 com.facebook.presto.execution.executor.TaskExecutor Error processing Split 20200420_113803_00002_cjdy7.2.0.0-0 InformationSchemaSplit{tableHandle=druid:information_schema:columns, prefixes=[druid.druid.etl_umooc], addresses=[10.1.26.78:8080]} (start = 9.65779990532344E8, wall = 13 ms, cpu = 0 ms, wait = 18 ms, calls = 1)
> java.lang.IllegalArgumentException: unsupported type: OTHER
> at com.facebook.presto.druid.DruidMetadata.getType(DruidMetadata.java:167)
> at com.facebook.presto.druid.DruidMetadata.toColumnMetadata(DruidMetadata.java:173)
> at com.facebook.presto.druid.DruidMetadata.lambda$getTableMetadata$2(DruidMetadata.java:96)
> at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> at com.facebook.presto.druid.DruidMetadata.getTableMetadata(DruidMetadata.java:97)
> at com.facebook.presto.druid.DruidMetadata.listTableColumns(DruidMetadata.java:124)
> at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:590)
> at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:153)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:122)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:116)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
> at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
> at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
> at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:227)
> at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
> at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
> at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
> at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
> at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
> at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
> at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
> at com.facebook.presto.$gen.Presto_0_233_1_2d75403____20200420_113454_1.run(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 
> 2020-04-20T11:38:04.021Z ERROR remote-task-callback-3 com.facebook.presto.execution.StageExecutionStateMachine Stage execution 20200420_113803_00002_cjdy7.2.0 failed
> java.lang.IllegalArgumentException: unsupported type: OTHER
> at com.facebook.presto.druid.DruidMetadata.getType(DruidMetadata.java:167)
> at com.facebook.presto.druid.DruidMetadata.toColumnMetadata(DruidMetadata.java:173)
> at com.facebook.presto.druid.DruidMetadata.lambda$getTableMetadata$2(DruidMetadata.java:96)
> at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
> at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
> at com.facebook.presto.druid.DruidMetadata.getTableMetadata(DruidMetadata.java:97)
> at com.facebook.presto.druid.DruidMetadata.listTableColumns(DruidMetadata.java:124)
> at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:590)
> at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:153)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:122)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:116)
> at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
> at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
> at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
> at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:227)
> at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
> at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
> at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
> at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
> at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
> at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
> at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
> at com.facebook.presto.$gen.Presto_0_233_1_2d75403____20200420_113454_1.run(Unknown Source)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 
> 2020-04-20T11:38:04.066Z INFO query-execution-1 com.facebook.presto.event.QueryMonitor TIMELINE: Query 20200420_113803_00002_cjdy7 :: Transaction:[c3d04f60-7bb8-41d4-94bf-d247ce1cb139] :: elapsed 263ms :: planning 123ms :: scheduling 118ms :: running 12ms :: finishing 10ms :: begin 2020-04-20T11:38:03.758Z :: end 2020-04-20T11:38:04.021Z

My Server:

**root@:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic**

**Comment by gaohaoning** [comment]
@zhenxiao Can you plesase help me on this?

**Comment by zhenxiao** [comment]
sure. @gaohaoning we found a similar problem
@beinan is working on it.

**Comment by gaohaoning** [comment]
please let me know when the problem is solved. I will be very grateful.
@zhenxiao @beinan

**Comment by zhenxiao** [comment]
hi @gaohaoning I think @beinan get the problem fixed. Could you please try the latest branch?

**Comment by gaohaoning** [comment]
@zhenxiao OK, I will try the latest version and reply to you ASAP, Thx~
