### ISSUE TITLE
druid query out of memory

### ISSUE THREAD

**Issue by mqiang** [prestodb/presto#14440]
@zhenxiao I meet a new issue, if a druid table is very large, when i exec 'select * from table', it will be out of memory when convert http response to String.

detail exception:
java.lang.OutOfMemoryError: input is too large to fit in a byte array
	at com.google.common.io.ByteStreams.toByteArrayInternal(ByteStreams.java:195)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:221)
	at com.facebook.airlift.http.client.StringResponseHandler.handle(StringResponseHandler.java:66)
	at com.facebook.airlift.http.client.StringResponseHandler.handle(StringResponseHandler.java:34)
	at com.facebook.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:529)
	at com.facebook.presto.druid.DruidClient.getData(DruidClient.java:124)
	at com.facebook.presto.druid.DruidBrokerPageSource.getNextPage(DruidBrokerPageSource.java:116)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:251)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:381)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:677)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_null__testversion____20200426_020023_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhenxiao** [comment]
this is with pushdown, right? @mqiang 
is not pushdown "select *" working fine?

**Comment by mqiang** [comment]
> this is with pushdown, right? @mqiang
> is not pushdown "select *" working fine?

I think that's two issues.
1. 'select *' is still not pushdown.
2.In my test case, I changed pushdown variable to true. If a druid table is not big, there is no problem; but if this table is very big, it will be out of memory when handling http response stream to string .
I find it not read response stream by page, so oom. I try to solve this issues, please help to review it. https://github.com/prestodb/presto/pull/14445
