### ISSUE TITLE
`ANALYZE TABLE` fails on tables with structs

### ISSUE THREAD

**Issue by otakart** [prestodb/presto#14494]
Starting with version 0.225 `ANALYZE TABLE` command on Hive connector fails for tables with struct columns.
Fails also on current v0.235.

> java.lang.IllegalArgumentException: unsupported type: struct<cause:string,is_enabled:boolean,created_at:date,disable_date:date,processed_last:date,processed_since:date>
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:210)
	at com.facebook.presto.hive.metastore.thrift.ThriftMetastoreUtil.createMetastoreColumnStatistics(ThriftMetastoreUtil.java:792)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$updateTableStatistics$18(ThriftHiveMetastore.java:412)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.updateTableStatistics(ThriftHiveMetastore.java:413)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.updateTableStatistics(BridgingHiveMetastore.java:112)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.updateTableStatistics(CachingHiveMetastore.java:338)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.updateTableStatistics(CachingHiveMetastore.java:338)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$setTableStatistics$6(SemiTransactionalHiveMetastore.java:322)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:905)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:2518)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:211)
	at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:601)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rschlussel** [comment]
Seems possibly related to https://github.com/prestodb/presto/commit/09d128027221f9afecdefca52ea4489d16571890  @mbasmanova

**Comment by otakart** [comment]
@rschlussel Thank you for checking this. I just tried to compile v0.225 with https://github.com/prestodb/presto/commit/09d128027221f9afecdefca52ea4489d16571890 reverted and `analyze table` works fine.

**Comment by mbasmanova** [comment]
CC: @prestodb/aria

**Comment by mbasmanova** [comment]
CC: @sujay-jain @jbroll
