### ISSUE TITLE
using presto to query druid could not return successfully(still have problem)

### ISSUE THREAD

**Issue by gaohaoning** [prestodb/presto#14584]
after I updated my version to presto-server-0.235.1, the problem in #14413 still exists.
---------------------------------------------------------------------------------------------------------
Same problem still exists.

When I use presto to query druid datasource without rollup configuration, everything seems OK;
When I use presto to query druid datasource with rollup configuration, the following ERROR came out:

---------------------------------------------------------------------------------------------------------
(on the client side)

presto:druid> describe etl_ucampus;

Query 20200527_062018_00004_sy2jr, FAILED, 1 node
Splits: 19 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200527_062018_00004_sy2jr failed: unsupported type: OTHER
---------------------------------------------------------------------------------------------------------
(on the server side)

2020-05-27T14:20:18.340+0800        ERROR        SplitRunner-6-108        com.facebook.presto.execution.executor.TaskExecutor        Error processing Split 20200527_062018_00004_sy2jr.2.0.0-0 InformationSchemaSplit{tableHandle=druid:information_schema:columns, prefixes=[druid.druid.etl_ucampus], addresses=[10.1.26.78:8080]} (start = 4.143514321002068E9, wall = 12 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.IllegalArgumentException: unsupported type: OTHER
        at com.facebook.presto.druid.DruidMetadata.getType(DruidMetadata.java:160)
        at com.facebook.presto.druid.DruidMetadata.toColumnMetadata(DruidMetadata.java:166)
        at com.facebook.presto.druid.DruidMetadata.lambda$getTableMetadata$2(DruidMetadata.java:96)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.druid.DruidMetadata.getTableMetadata(DruidMetadata.java:97)
        at com.facebook.presto.druid.DruidMetadata.listTableColumns(DruidMetadata.java:124)
        at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:581)
        at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:94)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:153)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:122)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:116)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
        at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:227)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
        at com.facebook.presto.$gen.Presto_0_235_1_7265eb8____20200527_061937_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020-05-27T14:20:18.350+0800        ERROR        remote-task-callback-3        com.facebook.presto.execution.StageExecutionStateMachine        Stage execution 20200527_062018_00004_sy2jr.2.0 failed
java.lang.IllegalArgumentException: unsupported type: OTHER
        at com.facebook.presto.druid.DruidMetadata.getType(DruidMetadata.java:160)
        at com.facebook.presto.druid.DruidMetadata.toColumnMetadata(DruidMetadata.java:166)
        at com.facebook.presto.druid.DruidMetadata.lambda$getTableMetadata$2(DruidMetadata.java:96)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.druid.DruidMetadata.getTableMetadata(DruidMetadata.java:97)
        at com.facebook.presto.druid.DruidMetadata.listTableColumns(DruidMetadata.java:124)
        at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:581)
        at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:94)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:153)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:122)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:116)
        at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:86)
        at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:227)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
        at com.facebook.presto.$gen.Presto_0_235_1_7265eb8____20200527_061937_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

2020-05-27T14:20:18.392+0800        INFO        dispatcher-query-2        com.facebook.presto.event.QueryMonitor        TIMELINE: Query 20200527_062018_00004_sy2jr :: Transaction:[44e0bdaa-103e-4b84-8b03-fd5b44f03fbd] :: elapsed 197ms :: planning 100ms :: scheduling 77ms :: running 14ms :: finishing 6ms :: begin 2020-05-27T14:20:18.153+08:00 :: end 2020-05-27T14:20:18.350+08:00
---------------------------------------------------------------------------------------------------------

**Comment by gaohaoning** [comment]
@zhenxiao
@beinan
could you please help about this problem ?

**Comment by zhenxiao** [comment]
@gaohaoning did you try the latest version 236? I think @beinan fixed the issue. @beinan could you please help?

**Comment by gaohaoning** [comment]
version 235.1 still have the same problem , I just tried version 236, 236 is OK, Thx very much !!!
@zhenxiao @beinan

**Comment by zhenxiao** [comment]
get it. nice it is resolved
