### ISSUE TITLE
Query 20200616_200514_00006_yhuc2 failed: The connection attempt failed.

### ISSUE THREAD

**Issue by shreehari-verna** [prestodb/presto#14658]
I have installed presto on my Mac OS Catalina. 
After starting the presto server in the bin directory, 
`sudo ./launcher start` 

When I try to connect to the PostgreSQL or MySql I am unable to connect. 
I get a "Query 20200616_200514_00006_yhuc2 failed: The connection attempt failed." Error

I have correctly configured the catalog directory with postgresql.properties as,

connector.name=postgresql
connection-url=jdbc:postgresql://example.net:5432/database
connection-user=root
connection-password=secret
 
found at [https://prestodb.io/docs/current/connector/postgresql.html](url)

Can anyone please tell me what could be wrong?

**Comment by mbasmanova** [comment]
Is `example.net:5432` actually correct? Perhaps, launch CLI with --debug flag, re-run the query and share the stack trace here.

**Comment by rschlussel** [comment]
Haven't heard back, so closing the issue.

**Comment by gadhesaimohan** [comment]
Getting same issue

**Comment by gadhesaimohan** [comment]
Executed presto CLI with:-  **./presto --server 192.168.10.218:8080 --catalog postgresql --debug**

Query 20220315_041100_00005_92b3t failed: The connection attempt failed.
 com.facebook.presto.spi.PrestoException: The connection attempt failed.                                                                                                                             
        at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:155)                                                                                                   
        at com.facebook.presto.plugin.jdbc.JdbcClient.schemaExists(JdbcClient.java:38)                                                                                                              
        at com.facebook.presto.plugin.jdbc.JdbcMetadata.schemaExists(JdbcMetadata.java:69)                                                                                                          
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.schemaExists(ClassLoaderSafeConnectorMetadata.java:204)                                                   
        at com.facebook.presto.metadata.MetadataManager.lambda$schemaExists$0(MetadataManager.java:291)                                                                                             
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)                                                                                                                            
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)              
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)    
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)         
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)               
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                  
        at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)               
        at com.facebook.presto.metadata.MetadataManager.schemaExists(MetadataManager.java:291)    
        at com.facebook.presto.execution.CreateSchemaTask.execute(CreateSchemaTask.java:63)      
        at com.facebook.presto.execution.CreateSchemaTask.execute(CreateSchemaTask.java:39)   
        at com.facebook.presto.execution.DDLDefinitionExecution.executeTask(DDLDefinitionExecution.java:58)
        at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:203)
        at com.facebook.presto.$gen.Presto_0_271_ab814d9____20220315_035021_1.run(Unknown Source)
        at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:266)    
        at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:197)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)        
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)        
        at java.lang.Thread.run(Thread.java:748)                                                  
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.                      
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:292)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)        
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)                         
        at org.postgresql.Driver.makeConnection(Driver.java:454)                                  
        at org.postgresql.Driver.connect(Driver.java:256)                                         
        at com.facebook.presto.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:82)
        at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:149) 
        ... 26 more                              
Caused by: java.net.SocketTimeoutException: connect timed out                                     
        at java.net.PlainSocketImpl.socketConnect(Native Method)                                  
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)           
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
