### ISSUE TITLE
OOM on hive metastore after upgrade from 0.225 to 0.236

### ISSUE THREAD

**Issue by tarigancana** [prestodb/presto#14749]
I just update the presto to 0.236 found issue that our Hive Metastore cpu is goes to 100% and also make the Out of Memory
```
2020-06-28T06:36:40,948 ERROR [pool-7-thread-193] metastore.RetryingHMSHandler: Retrying HMSHandler after 2000 ms (attempt 1 of 10) with error: javax.jdo.JDOException: Exception thrown when executing query : SELECT "A0"."PART_NAME" FROM "
PARTITIONS" "A0" LEFT OUTER JOIN "TBLS" "B0" ON "A0"."TBL_ID" = "B0"."TBL_ID" LEFT OUTER JOIN "DBS" "C0" ON "B0"."DB_ID" = "C0"."DB_ID" WHERE "C0"."NAME" = ? AND "B0"."TBL_NAME" = ? AND "A0"."PART_NAME" LIKE 'event=%/ts=%' ESCAPE E'\\'
        at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:677)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:391)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:255)
        at org.apache.hadoop.hive.metastore.ObjectStore.getPartitionPsQueryResults(ObjectStore.java:2565)
        at org.apache.hadoop.hive.metastore.ObjectStore.listPartitionNamesPs(ObjectStore.java:2612)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:101)
        at com.sun.proxy.$Proxy23.listPartitionNamesPs(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_partition_names_ps(HiveMetaStore.java:4517)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:148)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:107)
        at com.sun.proxy.$Proxy24.get_partition_names_ps(Unknown Source)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12389)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12373)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:103)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
NestedThrowablesStackTrace:
org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1969)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:161)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:174)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeQuery(ParamLoggingPreparedStatement.java:375)
        at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:552)
        at org.datanucleus.store.rdbms.query.JDOQLQuery.performExecute(JDOQLQuery.java:617)
        at org.datanucleus.store.query.Query.executeQuery(Query.java:1855)
        at org.datanucleus.store.query.Query.executeWithArray(Query.java:1744)
        at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:368)
        at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:255)
        at org.apache.hadoop.hive.metastore.ObjectStore.getPartitionPsQueryResults(ObjectStore.java:2565)
        at org.apache.hadoop.hive.metastore.ObjectStore.listPartitionNamesPs(ObjectStore.java:2612)
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RawStoreProxy.invoke(RawStoreProxy.java:101)
        at com.sun.proxy.$Proxy23.listPartitionNamesPs(Unknown Source)
        at org.apache.hadoop.hive.metastore.HiveMetaStore$HMSHandler.get_partition_names_ps(HiveMetaStore.java:4517)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invokeInternal(RetryingHMSHandler.java:148)
        at org.apache.hadoop.hive.metastore.RetryingHMSHandler.invoke(RetryingHMSHandler.java:107)
        at com.sun.proxy.$Proxy24.get_partition_names_ps(Unknown Source)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12389)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Processor$get_partition_names_ps.getResult(ThriftHiveMetastore.java:12373)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39)
        at org.apache.hadoop.hive.metastore.TUGIBasedProcessor.process(TUGIBasedProcessor.java:103)
        at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
```

I also try update to 0.237 and the problem still happen. any suggestion?

![Screen Shot 2020-06-28 at 13 43 04](https://user-images.githubusercontent.com/11748229/85940218-56e5bc80-b945-11ea-9e75-a50e14c5ed0c.png)

**Comment by mbasmanova** [comment]
CC: @vkorukanti

**Comment by mbasmanova** [comment]
CC: @zhenxiao

**Comment by vkorukanti** [comment]
AFAIK, we haven't made any changes in Parquet that could cause the increase in HMS calls. @tarigancana Can you check the HMS log to see what calls are coming from Presto?

**Comment by tarigancana** [comment]
This is the log before oom

```
2020-06-28T06:29:29,695  INFO [pool-7-thread-192] metastore.HiveMetaStore: 192: source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,695  INFO [pool-7-thread-192] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,697  INFO [pool-7-thread-191] metastore.HiveMetaStore: 191: source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,697  INFO [pool-7-thread-191] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,698  INFO [pool-7-thread-160] metastore.HiveMetaStore: 160: source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,698  INFO [pool-7-thread-160] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,703  INFO [pool-7-thread-169] metastore.HiveMetaStore: 169: source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:29,703  INFO [pool-7-thread-169] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:33,519  WARN [pool-7-thread-180] conf.HiveConf: HiveConf of name hive.hwi.war.file does not exist
2020-06-28T06:29:33,520  INFO [pool-7-thread-180] metastore.HiveMetaStore: 180: Opening raw store with implementation class:org.apache.hadoop.hive.metastore.ObjectStore
2020-06-28T06:29:37,455  INFO [pool-7-thread-157] metastore.HiveMetaStore: 157: source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:29:37,456  INFO [pool-7-thread-157] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:31:45,134 ERROR [main] metastore.HiveMetaStore: java.lang.OutOfMemoryError: GC overhead limit exceeded

2020-06-28T06:31:45,134 ERROR [main] metastore.HiveMetaStore: Metastore Thrift Server threw an exception...
java.lang.OutOfMemoryError: GC overhead limit exceeded
2020-06-28T06:31:45,134 ERROR [pool-7-thread-169] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: GC overhead limit exceeded

2020-06-28T06:31:52,996  INFO [pool-7-thread-155] metastore.HiveMetaStore: 155: source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:31:52,997  INFO [pool-7-thread-155] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=plenty tbl=events
2020-06-28T06:32:40,976 ERROR [pool-7-thread-157] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: GC overhead limit exceeded

2020-06-28T06:32:40,976 ERROR [pool-7-thread-164] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: GC overhead limit exceeded

2020-06-28T06:32:45,132  INFO [pool-7-thread-154] metastore.HiveMetaStore: 154: source:10.251.17.6 get_table : db=nightshift tbl=vidio_transaction_all
2020-06-28T06:32:45,132 ERROR [pool-7-thread-155] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: GC overhead limit exceeded

2020-06-28T06:32:45,132  INFO [pool-7-thread-154] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=nightshift tbl=vidio_transaction_all
2020-06-28T06:32:57,825  INFO [pool-7-thread-156] metastore.HiveMetaStore: 156: source:10.251.17.6 get_table : db=nightshift tbl=vidio_transaction_all
2020-06-28T06:32:57,825  INFO [pool-7-thread-156] HiveMetaStore.audit: ugi=hive ip=10.251.17.6 cmd=source:10.251.17.6 get_table : db=nightshift tbl=vidio_transaction_all
2020-06-28T06:32:57,829 ERROR [pool-7-thread-192] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: GC overhead limit exceeded

2020-06-28T06:32:57,835 ERROR [pool-7-thread-191] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: Java heap space

2020-06-28T06:33:44,869 ERROR [pool-7-thread-156] metastore.RetryingHMSHandler: java.lang.OutOfMemoryError: GC overhead limit exceeded
``````

**Comment by douglasawh** [comment]
@tarigancana what was the resolution to this? Thanks!
