### ISSUE TITLE
LBM: Unsupported type: date when collecting stats for temporary tables

### ISSUE THREAD

**Issue by viczhang861** [prestodb/presto#14777]
Triggered when large batch mode is on and stats are collected for temporary table.
Stacktrace:
`java.lang.IllegalArgumentException: Unsupported type: date
	at com.facebook.presto.hive.PrismStatistics.getSupportedColumnStatistics(PrismStatistics.java:96)
	at com.facebook.presto.prism.metastore.thrift.PrismHiveMetastore.getSupportedColumnStatistics(PrismHiveMetastore.java:325)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getSupportedColumnStatistics(BridgingHiveMetastore.java:96)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getSupportedColumnStatistics(CachingHiveMetastore.java:270)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getSupportedColumnStatistics(CachingHiveMetastore.java:270)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getSupportedColumnStatistics(SemiTransactionalHiveMetastore.java:180)
	at com.facebook.presto.hive.HiveMetadata.lambda$createTemporaryTable$23(HiveMetadata.java:971)
	at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$1(CollectCollectors.java:61)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.hive.HiveMetadata.createTemporaryTable(HiveMetadata.java:971)
	at com.facebook.presto.hive.PrismMetadata.createTemporaryTable(PrismMetadata.java:611)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.createTemporaryTable(ClassLoaderSafeConnectorMetadata.java:351)
	at com.facebook.presto.metadata.MetadataManager.createTemporaryTable(MetadataManager.java:650)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.createRemoteMaterializedExchange(PlanFragmenter.java:562)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:500)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:338)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:305)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:496)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:338)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:305)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
	at com.facebook.presto.spi.plan.PlanVisitor.visitAggregation(PlanVisitor.java:25)
	at com.facebook.presto.spi.plan.AggregationNode.accept(AggregationNode.java:199)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
	at com.facebook.presto.spi.plan.PlanVisitor.visitProject(PlanVisitor.java:30)
	at com.facebook.presto.spi.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.buildSubPlan(PlanFragmenter.java:830)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.createRemoteStreamingExchange(PlanFragmenter.java:522)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:498)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:338)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:305)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitSort(InternalPlanVisitor.java:74)
	at com.facebook.presto.sql.planner.plan.SortNode.accept(SortNode.java:85)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:496)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:338)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:305)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.buildSubPlan(PlanFragmenter.java:830)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.createRemoteStreamingExchange(PlanFragmenter.java:522)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:498)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:338)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:305)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4727)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitOutput(PlanFragmenter.java:430)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitOutput(PlanFragmenter.java:338)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:84)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:34)
	at com.facebook.presto.sql.planner.PlanFragmenter.createSubPlans(PlanFragmenter.java:182)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:387)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:360)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:310)
	at com.facebook.presto.$gen.Presto_0_239_SNAPSHOT_6d983fb____20200702_194954_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:231)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)`

**Comment by mbasmanova** [comment]
@viczhang861 Vic, is the fix is to disable stats collection for temporary tables?

**Comment by viczhang861** [comment]
@mbasmanova This is fixed by https://github.com/prestodb/presto/pull/14799,  stats collection is disabled by default for temporary table. However, one code path didn't check for that. The fix is to use a default set of column statistics types (data_size and number_of_non_null) for all column types rather than throwing an error.
