### ISSUE TITLE
Unexpected parameter --password for cli

### ISSUE THREAD

**Issue by xanderblinov** [prestodb/presto#14790]
At issue https://github.com/prestodb/presto/issues/8361 @electrum advised to use `--password` for presto-sli authentication. Unfortunately I got error: 

```
presto --password
Exception in thread "main" io.airlift.command.ParseArgumentsUnexpectedException: Found unexpected parameters: [--password]
	at io.airlift.command.SingleCommand.validate(SingleCommand.java:97)
	at io.airlift.command.SingleCommand.parse(SingleCommand.java:65)
	at io.airlift.command.SingleCommand.parse(SingleCommand.java:56)
	at com.facebook.presto.cli.Presto.main(Presto.java:25)
```
I used jar from https://prestodb.io/docs/current/installation/cli.html 
 
See --help output below: there is no --password option
```
presto --help
NAME
        presto - Presto interactive console

SYNOPSIS
        presto [--catalog <catalog>] [--debug] [--execute <execute>]
                [(-f <file> | --file <file>)] [(-h | --help)]
                [--output-format <output-format>] [--schema <schema>]
                [--server <server>] [--session <session>...]
                [--socks-proxy <socks-proxy>] [--source <source>] [--user <user>]

OPTIONS
        --catalog <catalog>
            Default catalog

        --debug
            Enable debug information

        --execute <execute>
            Execute specified statements and exit

        -f <file>, --file <file>
            Execute statements from file and exit

        -h, --help
            Display help information

        --output-format <output-format>
            Output format for batch mode (default: CSV)

        --schema <schema>
            Default schema

        --server <server>
            Presto server location (default: localhost:8080)

        --session <session>
            Session property (property can be used multiple times; format is
            key=value)

        --socks-proxy <socks-proxy>
            SOCKS proxy to use for server connections

        --source <source>
            Name of source making query

        --user <user>
            Username
```

**Comment by xanderblinov** [comment]
Used some wrong executable. Downloads it again and works fine
