### ISSUE TITLE
Flaky testTransactionMetadataCleanup

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#14835]
Seeing travis failure for TestTransactionManagerIntegeration.testTransactionMetadataCleanup() 

Example Failure:
```
[ERROR] Tests run: 734, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 759.463 s <<< FAILURE! - in TestSuite
[ERROR] testTransactionMetadataCleanup(com.facebook.presto.tests.TestTransactionManagerIntegration)  Time elapsed: 3.803 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.facebook.presto.tests.TestTransactionManagerIntegration.testTransactionMetadataCleanup(TestTransactionManagerIntegration.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-07-01T16:03:01.713-0500 INFO Life cycle stopping...
2020-07-01T16:03:01.717-0500 INFO Life cycle stopped.
2020-07-01T16:03:01.718-0500 INFO Life cycle stopping...
2020-07-01T16:03:01.718-0500 INFO Life cycle stopping...
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestTransactionManagerIntegration.testTransactionMetadataCleanup:40 expected [true] but found [false]
```

**Comment by viczhang861** [comment]
log from  https://api.travis-ci.org/v3/job/712292389/log.txt

`2020-07-27T13:08:23.334-0500 INFO Started o.e.j.s.ServletContextHandler@46aee3f0{/,null,AVAILABLE,@http}
2020-07-27T13:08:23.335-0500 INFO Started http@68d1f1f8{HTTP/1.1,[http/1.1, h2c]}{127.0.0.1:40078}
2020-07-27T13:08:23.335-0500 INFO Started @814269ms
2020-07-27T13:08:23.527-0500 INFO Life cycle starting...
2020-07-27T13:08:23.527-0500 INFO Life cycle startup complete. System ready.
2020-07-27T13:08:23.541-0500 INFO Created coordinator TestingPrestoServer in 1.02s: http://127.0.0.1:40078
2020-07-27T13:08:23.550-0500 INFO Announced servers in 6.70ms
2020-07-27T13:08:23.554-0500 INFO Added functions in 4.06ms
2020-07-27T13:08:23.555-0500 INFO Registering connector tpch
2020-07-27T13:08:23.555-0500 INFO Registering connector tpch
2020-07-27T13:08:23.555-0500 INFO Registering connector tpch
2020-07-27T13:08:23.555-0500 INFO Registering connector tpch
2020-07-27T13:08:23.555-0500 INFO Installed plugin TpchPlugin in 970.88us
2020-07-27T13:08:23.558-0500 INFO Created catalog tpch (tpch) in 2.52ms
2020-07-27T13:08:23.561-0500 INFO Announced catalog tpch (tpch) in 2.68ms
2020-07-27T13:08:23.589-0500 WARNING Error fetching node state from http://127.0.0.1:45164/v1/info/state: Server refused connection: http://127.0.0.1:45164/v1/info/state
2020-07-27T13:08:23.986-0500 INFO TIMELINE: Query 20200727_180823_00000_mz72u :: Transaction:[e191a9e0-45bc-42f7-bcd6-e2d9ebe1de30] :: elapsed 371ms :: planning 26ms :: scheduling 242ms :: running 80ms :: finishing 23ms :: begin 2020-07-27T13:08:23.582-05:00 :: end 2020-07-27T13:08:23.953-05:00
2020-07-27T13:08:24.088-0500 INFO TIMELINE: Query 20200727_180823_00001_mz72u :: Transaction:[3ae075a6-fa83-40ea-8acb-03e7645b112d] :: elapsed 115ms :: planning 13ms :: scheduling 27ms :: running 64ms :: finishing 11ms :: begin 2020-07-27T13:08:23.966-05:00 :: end 2020-07-27T13:08:24.081-05:00
2020-07-27T13:08:24.135-0500 INFO TIMELINE: Query 20200727_180824_00002_mz72u :: Transaction:[cd2d5f11-2ebe-4004-9723-a31d89daf540] :: elapsed 0ms :: planning 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2020-07-27T13:08:24.133-05:00 :: end 2020-07-27T13:08:24.133-05:00
2020-07-27T13:08:24.149-0500 INFO TIMELINE: Query 20200727_180824_00003_mz72u :: Transaction:[44261000-ddc0-4cfa-a1c0-2c650005717f] :: elapsed 0ms :: planning 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2020-07-27T13:08:24.148-05:00 :: end 2020-07-27T13:08:24.148-05:00
2020-07-27T13:08:24.169-0500 INFO Life cycle stopping...
2020-07-27T13:08:24.170-0500 INFO TIMELINE: Query 20200727_180824_00004_mz72u :: Transaction:[f41b038c-91d4-4c4c-ad78-03ab89cbec92] :: elapsed 0ms :: planning 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2020-07-27T13:08:24.166-05:00 :: end 2020-07-27T13:08:24.166-05:00
2020-07-27T13:08:24.200-0500 INFO Stopped http@68d1f1f8{HTTP/1.1,[http/1.1, h2c]}{127.0.0.1:40078}
2020-07-27T13:08:24.201-0500 INFO Stopped o.e.j.s.ServletContextHandler@46aee3f0{/,null,UNAVAILABLE,@http}`
