### ISSUE TITLE
Presto not able to read timestamp value ''0000-00-00 00:00:00' on MySql.

### ISSUE THREAD

**Issue by SonuSingh200190** [prestodb/presto#14875]
error logs:

java.sql.SQLException: Query failed (#20200722_172805_00036_kvi6s): Value '2018-01-01 00:00:0019218123060209.99108.948.948.940000-00-00 00:00:000000-00-00 00:00:000000-00-00 00:00:009.999.998.94' can not be represented as java.sql.Timestamp
        at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1840)
        at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1820)
        at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1759)
        at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
        at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
        at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
        at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1311)
        at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1327)
        at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:144)

**Comment by mbasmanova** [comment]
CC: @jamesgpearce
