### ISSUE TITLE
Unexpected 'ARRAY comparison not supported for arrays with null elements' error when using array column in a subquery

### ISSUE THREAD

**Issue by wfaria** [prestodb/presto#14916]
Consider the following subquery that we have on our AWS EMR Cluster (EMR version 5.29, Presto 0.227):
```
...
inter_treatment_filtered_messages AS
(
    WITH aux_table AS
    (
        SELECT communication_type, message_parts,
            row_number() OVER(
                PARTITION BY
                    fmboa.message_contact
                ORDER BY
                    fmboa.treatment_rank, fmboa.treatment_name)
            AS rnk
        FROM filtered_messages_based_on_aggr AS fmboa
    )
    SELECT *
    FROM aux_table
    WHERE rnk = 1
)
SELECT *
FROM inter_treatment_filtered_messages
```

The column `message_parts` type is ARRAY<STRING>. When we run the query that contains this subquery, it fails with the following stacktrace:
```
com.facebook.presto.spi.PrestoException: ARRAY comparison not supported for arrays with null elements
	at com.facebook.presto.spi.type.TypeUtils.checkElementNotNull(TypeUtils.java:103)
	at com.facebook.presto.spi.type.ArrayType.equalTo(ArrayType.java:74)
	at com.facebook.presto.$gen.PagesHashStrategy_20200729_133612_28879.rowEqualsRow(Unknown Source)
	at com.facebook.presto.operator.StreamingAggregationOperator.findNextGroupStart(StreamingAggregationOperator.java:258)
	at com.facebook.presto.operator.StreamingAggregationOperator.processInput(StreamingAggregationOperator.java:203)
	at com.facebook.presto.operator.StreamingAggregationOperator.addInput(StreamingAggregationOperator.java:161)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at com.facebook.presto.$gen.Presto_0_227____20200722_202716_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

If I remove that column `message_parts` from the subquery, everything works fine. Note that that column doesn't appear in any predicate on the SQL (except at the last Select to display the results). I tried to reproduce this exception creating a small table with an empty array but the same error didn't happen, so I think that it may only happen when dealing with millions of rows (moreover since I don't compare entire rows on my query).

Could someone please take a look on this? This error message is pretty unhelpful because there is no line on the exception and it seems to be caused by an engine internal error.

Thanks!

**Comment by mbasmanova** [comment]
@wfaria Would you share query plan (the output of EXPLAIN (type distributed) <query>) and schema of filtered_messages_based_on_aggr (the output of SHOW CREATE TABLE filtered_messages_based_on_aggr) ?

**Comment by wfaria** [comment]
Hello, I think that I was able to escape from this "bug" by breaking my queries into multiple subqueries instead of using nested queries (mainly based on NON EXISTS statements). However, I wasn't able to discover the exact way to trigger this problem.

[Here is the Query Plan](https://pastebin.com/D0vKzP7d) from the affected query but I believe that it is pretty huge to be read, sorry for that...

I can't do that SHOW CREATE TABLE because **filtered_messages_based_on_aggr** is a subquery alias, it is part of a huge query. The subquery is defined by:

```
**(... other subqueries here...)**
filtered_messages_based_on_aggr AS
(
    SELECT *
    FROM messages_with_rules AS mwr
    WHERE NOT EXISTS
        (
            -- Removing all over-impacted contacts without the flag to ignore this filter.
            SELECT *
            FROM over_impacted_contacts AS oic
            WHERE mwr.message_contact = oic.message_contact AND
                mwr.communication_type = oic.communication_type AND
                NOT
                (
                    mwr.message_merged_parameters IS NOT NULL AND
                    ELEMENT_AT(mwr.message_merged_parameters, 'ignore_over_impact_filter') IS NOT NULL AND
                    mwr.message_merged_parameters['ignore_over_impact_filter'] = 'True'
                )
        )
        AND
        NOT EXISTS
        (
            -- Removing all contacts according to campaign-specific rules.
            SELECT *
            FROM hive.dbm_local.message_aggr_per_user AS mcapu
            WHERE
                mwr.message_contact = mcapu.message_contact AND
                mwr.communication_type = mcapu.communication_type AND
                (
                    (
                        mwr.message_limit_per_user > 0 AND
                        mwr.treatment_name = mcapu.treatment_name AND
                        mwr.message_limit_per_user <= mcapu.treatment_msgs
                    )
                    OR
                    (
                        (
                            mwr.treatment_name = mcapu.treatment_name OR
                            (mwr.equivalent_campaigns IS NOT NULL 
                            AND ARRAY_POSITION(mwr.equivalent_campaigns, mcapu.treatment_name) > 0)
                        )
                        AND
                        DATE_ADD('day', mwr.same_campaign_day_interval , mcapu.max_date) >=
                            CAST('{{year}}-{{month}}-{{day}}' AS DATE)
                    )
                )
        )
),
**(... the query which I pasted on the first comment is placed here ...)**
```

**Comment by rongrong** [comment]
@wfaria can you reformat the plan with proper indentation etc, the paste is very hard to read. Also from the query you gave that produced `filtered_messages_based_on_aggr` , I can't tell where `message_parts` is from and how it's constructed.

**Comment by wfaria** [comment]
My bad, now [here is the plan with a better indentation](https://pastebin.com/SVd4vaMY).

The original query is 300 lines long and I am worried with company compliance rules. This way I would like to not paste the entire query in a public forum. Moreover, I can't send the data to let you test the query there. `message_parts` is another subquery above that subquery, it have multiple `String` and `Bigint` columns, come `ARRAY<STRING>` columns and a single `MAP<ARRAY<STRING>>` column.
