### ISSUE TITLE
[Presto-Druid] "Can not create a Path from a null string" when reading Druid segment on s3

### ISSUE THREAD

**Issue by jinyangli34** [prestodb/presto#14921]
```
presto:default> select time from druid_canary_hourly_test;

Query 20200729_174306_00013_rxief, FAILED, 1 node
http://i-0854c7e41e1b76259.inst.aws.airbnb.com:6093/ui/query.html?20200729_174306_00013_rxief
Splits: 8 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 0B
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20200729_174306_00013_rxief failed: Can not create a Path from a null string
java.lang.IllegalArgumentException: Can not create a Path from a null string
	at org.apache.hadoop.fs.Path.checkPathArg(Path.java:122)
	at org.apache.hadoop.fs.Path.<init>(Path.java:134)
	at com.facebook.presto.druid.DruidPageSourceProvider.createPageSource(DruidPageSourceProvider.java:81)
	at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:58)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:382)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:284)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:672)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:277)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_238_1_$_git_commit_id_abbrev_____20200729_075129_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

`time` here is a varchar dimension column in Druid datasource.

**Comment by Huper7777** [comment]
Yes
