### ISSUE TITLE
Flaky test TestQueryResource.testGetQueryInfos

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#14940]
ERROR] Tests run: 6312, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4,171.897 s <<< FAILURE! - in TestSuite
[ERROR] testGetQueryInfos(com.facebook.presto.server.TestQueryResource)  Time elapsed: 4.219 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.facebook.presto.server.TestQueryResource.assertStateCounts(TestQueryResource.java:177)
	at com.facebook.presto.server.TestQueryResource.testGetQueryInfos(TestQueryResource.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by rschlussel** [comment]
@tdcmeehan it looks like you touched this test recently.  can you take a look?
