### ISSUE TITLE
Cannot add mongodb dependency in presto-main

### ISSUE THREAD

**Issue by HuangDCat** [prestodb/presto#15007]
I want to read the connector information from mongodb and add it to presto. I modified the related code in presto-main and added related dependencies in pom.xml. In IDEA, I can start normally and read the data in mongo. I replaced the jar package generated by maven package into the lib of presto-server, and it failed to start normally after executing ./launcher start. The error message output in the log is as follows:

**ERROR	main	com.facebook.presto.server.PrestoServer	com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/mongodb/client/MongoCollection
com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/mongodb/client/MongoCollection
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:51)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:48)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:581)
	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:176)
	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:122)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:245)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:132)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:78)**

The new dependencies in pom.xml are as follows:

    <dependency>
        <groupId>org.mongodb</groupId>
        <artifactId>mongo-java-driver</artifactId>
        <version>3.6.0</version>
        <exclusions>
            <exclusion>
                <groupId>io.netty</groupId>
                <artifactId>*</artifactId>
            </exclusion>
        </exclusions>
    </dependency>

I don't understand why and looking forward to your answers, thank you.

**Comment by mbasmanova** [comment]
presto-main shouldn't depend on any connectors. It might be easier for us to help if you could share a work-in-progress PR.
