### ISSUE TITLE
Ranger presto plugin issuse || Not able to retrive scheams from presto-server || Access denied failure || Authentication failure

### ISSUE THREAD

**Issue by AvianshKumar** [prestodb/presto#15026]
Hi Team,
While trying to enabled ranger presto plugin we are getting two errors.

Before that, I am able to run Ranger admin and ranger presto plugin successfully.

**Ranger admin version:-3.0.0
Ranger Presto plugin version:- 3.0.0.
Presto-server version:- 331.**

Explanation of errors:-
1:- Getting  Authentication Failed error when I am starting my presto after enabling ranger admin and ranger-presto successfully.

PFB the error logs:-

**2020-08-14T11:16:33.254Z        WARN    PolicyRefresher(serviceName=prestodev)-150      org.apache.ranger.admin.client.RangerAdminRESTClient    Error getting Roles. secureMode=false, user=root (auth:SIMPLE), response={**"httpStatusCode":401,"statusCode":401,"msgDesc":"Authentication Failed"**}, serviceName=prestodev**

2:-After presto up and running with the above error then When we try to get schemas of catalog then we are getting **Access denied issue.**

PFB error logs:-

2020-08-14T11:17:01.484Z        DEBUG   Query-20200814_111700_00000_zd8fv-162   io.prestosql.security.AccessControl     Invocation of checkCanShowSchemas(context=io.prestosql.security.SecurityContext@9c9ac10e, catalogName='hive') took 20.63ms and failed with io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot show schemas: hive
2020-08-14T11:17:01.493Z        DEBUG   dispatcher-query-3      io.prestosql.execution.QueryStateMachine        Query 20200814_111700_00000_zd8fv is FAILED
2020-08-14T11:17:01.492Z        DEBUG   dispatcher-query-1      io.prestosql.execution.QueryStateMachine        Query 20200814_111700_00000_zd8fv failed
io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot show schemas: hive
        at io.prestosql.spi.security.AccessDeniedException.denyShowSchemas(AccessDeniedException.java:136)
        at org.apache.ranger.authorization.presto.authorizer.RangerSystemAccessControl.checkCanShowSchemas(RangerSystemAccessControl.java:319)
        at

**Comment by findepi** [comment]
@AvianshKumar  Presto 3xx releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
