### ISSUE TITLE
Storage connection error when reading Hive Metadata is incorrectly considered as "HIVE_BAD_DATA"

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#15021]
Regression due to https://github.com/prestodb/presto/pull/14498

See discussions in https://github.com/prestodb/presto/pull/14498/files#r468313121

Example stacktrace:
```
Caused by: com.facebook.presto.orc.OrcCorruptionException: Malformed ORC file. Invalid stripe row index [......]
	at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.propagate(ExceptionWrappingMetadataReader.java:115)
	at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.readRowIndexes(ExceptionWrappingMetadataReader.java:97)
	at com.facebook.presto.orc.StripeReader.readColumnIndexes(StripeReader.java:493)
	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:184)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextStripe(AbstractOrcRecordReader.java:656)
	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextRowGroup(AbstractOrcRecordReader.java:541)
	at com.facebook.presto.orc.AbstractOrcRecordReader.prepareNextBatch(AbstractOrcRecordReader.java:596)
	at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:617)
	at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:86)
	... 13 more
Caused by: java.io.IOException: com.facebook.presto.spi.PrestoException: Error reading from ...... at position ......
	at com.facebook.presto.orc.OrcCorruptionException.<init>(OrcCorruptionException.java:36)
	... 22 more
Caused by: com.facebook.presto.spi.PrestoException: Error reading from ...... at position ......
	at com.facebook.presto.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:77)
	at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:105)
	at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:96)
	at com.facebook.presto.orc.AbstractOrcDataSource$LazyBufferLoader.load(AbstractOrcDataSource.java:237)
	at com.facebook.presto.orc.AbstractOrcDataSource$LazyBufferLoader.loadNestedDiskRangeBuffer(AbstractOrcDataSource.java:223)
	at com.facebook.presto.orc.AbstractOrcDataSource$LazyMergedSliceLoader.get(AbstractOrcDataSource.java:261)
	at com.facebook.presto.orc.AbstractOrcDataSource$LazyMergedSliceLoader.get(AbstractOrcDataSource.java:246)
	at com.facebook.presto.orc.LazySliceInput.getDelegate(LazySliceInput.java:52)
	at com.facebook.presto.orc.LazySliceInput.readUnsignedByte(LazySliceInput.java:126)
	at com.facebook.presto.orc.stream.OrcInputStream.advance(OrcInputStream.java:456)
	at com.facebook.presto.orc.stream.OrcInputStream.read(OrcInputStream.java:152)
	at com.facebook.presto.orc.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2715)
	at com.facebook.presto.orc.protobuf.CodedInputStream$StreamDecoder.isAtEnd(CodedInputStream.java:2654)
	at com.facebook.presto.orc.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2004)
	at com.facebook.presto.orc.proto.DwrfProto$RowIndex.<init>(DwrfProto.java:6016)
	at com.facebook.presto.orc.proto.DwrfProto$RowIndex.<init>(DwrfProto.java:5988)
	at com.facebook.presto.orc.proto.DwrfProto$RowIndex$1.parsePartialFrom(DwrfProto.java:6681)
	at com.facebook.presto.orc.proto.DwrfProto$RowIndex$1.parsePartialFrom(DwrfProto.java:6676)
	at com.facebook.presto.orc.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
	at com.facebook.presto.orc.protobuf.AbstractParser.parseFrom(AbstractParser.java:96)
	at com.facebook.presto.orc.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.facebook.presto.orc.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
	at com.facebook.presto.orc.proto.DwrfProto$RowIndex.parseFrom(DwrfProto.java:6214)
	at com.facebook.presto.orc.metadata.DwrfMetadataReader.readRowIndexes(DwrfMetadataReader.java:256)
	at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.readRowIndexes(ExceptionWrappingMetadataReader.java:94)
	... 20 more

```

**Comment by mbasmanova** [comment]
CC: @sujay-jain @bhhari
