### ISSUE TITLE
Oracle Connector

### ISSUE THREAD

**Issue by olinadib** [prestodb/presto#15051]
I have installed presto 0.149 , I was trying to create oracle adapter as below :

connector.name=oracle
connection-url=jdbc:oracle:thin:@10.12.1.200:1521/orcl
connection-user=system
connection-password=welcome1

I am getting the below error when running the presto server noting that connector name is correct:

2020-08-18T10:44:57.754+0300    ERROR   main    com.facebook.presto.server.PrestoServer No factory for connector oracle
java.lang.IllegalArgumentException: No factory for connector oracle
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:147)
        at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:99)
        at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:77)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:63)

**Comment by palashgoel7** [comment]
Hi,
1. Please mask all secrets when you post an issue. 
2. Oracle connector was added in v0.241: https://github.com/prestodb/presto/pull/15014
