### ISSUE TITLE
presto on druid error

### ISSUE THREAD

**Issue by jiemar** [prestodb/presto#15203]
i integrate druid connector to prestodb 0.227

it shows error like below, what's wrong?
presto:druid> select * from app_auto_xun_qh;
Query 20200922_012536_00001_47a6n failed: No value present

presto:druid> select * from app_auto_xun_qh limit 1;
Query 20200922_012547_00002_47a6n failed: Druid query generator cannot handle partial limit

**Comment by jiemar** [comment]
presto:druid> select * from app_auto_xun_qh;
Query 20200922_014901_00008_47a6n failed: No value present
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at com.facebook.presto.druid.DruidSplitManager.getSplits(DruidSplitManager.java:56)
        at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:87)
        at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:51)
        at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:140)
        at com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
        at com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStreamingLinkedStages(SqlQueryScheduler.java:420)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStreamingLinkedStages(SqlQueryScheduler.java:521)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:329)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.<init>(SqlQueryScheduler.java:210)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createSqlQueryScheduler(SqlQueryScheduler.java:157)
        at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:497)
        at com.facebook.presto.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:365)
