### ISSUE TITLE
Flaky test TestQueryManager.testFailQueryPrerun

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#15215]
Example failure log from travis

```
[ERROR] Tests run: 1036, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,008.992 s <<< FAILURE! - in TestSuite
[ERROR] testFailQueryPrerun(com.facebook.presto.tests.TestQueryManager)  Time elapsed: 0.126 s  <<< FAILURE!
java.lang.AssertionError: unexpected query state: RUNNING
	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.tests.TestQueryManager.testFailQueryPrerun(TestQueryManager.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-23T12:50:10.334-0500	INFO	Thread-4884	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.335-0500	INFO	Thread-4885	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.338-0500	INFO	Thread-4889	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.340-0500	INFO	Thread-4883	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.341-0500	INFO	Thread-4882	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
2020-09-23T12:50:10.341-0500	INFO	Thread-4890	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestQueryManager.testFailQueryPrerun:118 unexpected query state: RUNNING
[INFO] 
[ERROR] Tests run: 1036, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by rschlussel** [comment]
@jeremy-degroot it looks like you wrote this test in https://github.com/prestodb/presto/pull/14716.  Can you work on improving it to be less flaky?

cc: @viczhang861  and @tdcmeehan since you guys reviewed the PR and may have context.

**Comment by tdcmeehan** [comment]
This was probably made to be flaky by #14833.  I can pick it up.

**Comment by jeremy-degroot** [comment]
@tdcmeehan I'm happy to pick this up since I originally wrote it

**Comment by tdcmeehan** [comment]
@jeremy-degroot thanks for offering to pick this up.  I had already submitted a PR (#15217) because I am fairly confident the root cause of the flakiness is the PR I introduced above (#14833).

**Comment by jeremy-degroot** [comment]
@tdcmeehan Yeah, I saw that after I commented. Just reviewed it 👍
