### ISSUE TITLE
Presto server wouldn't start when there is Error parsing schema

### ISSUE THREAD

**Issue by tedyu** [prestodb/presto#15241]
I configured Presto server to connect to Cassandra backend (using https://repo1.maven.org/maven2/io/prestosql/presto-server/309/presto-server-309.tar.gz).

The server didn't start, due to:
```
2020-09-28T23:18:52.519Z        ERROR   Query-20200928_231805_00001_suw5n-158   com.datastax.driver.core.SchemaParser   Error parsing schema for table k.test_jsonb: Cluster.getMetadata().getKeyspace("k").getTable("test_jsonb") will be missing or incomplete
com.datastax.driver.core.exceptions.UnresolvedUserTypeException: Cannot resolve user type k.jsonb
        at com.datastax.driver.core.DataTypeCqlNameParser.parse(DataTypeCqlNameParser.java:147)
        at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:188)
        at com.datastax.driver.core.SchemaParser.buildTables(SchemaParser.java:179)
        at com.datastax.driver.core.SchemaParser.buildKeyspaces(SchemaParser.java:131)
        at com.datastax.driver.core.SchemaParser.refresh(SchemaParser.java:64)
        at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:337)
        at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:277)
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:201)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1483)
        at com.datastax.driver.core.Cluster.init(Cluster.java:159)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
        at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
        at com.datastax.driver.core.Cluster.connect(Cluster.java:247)
        at com.datastax.driver.core.DelegatingCluster.connect(DelegatingCluster.java:71)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
        at io.prestosql.plugin.cassandra.NativeCassandraSession.executeWithSession(NativeCassandraSession.java:553)
        at io.prestosql.plugin.cassandra.NativeCassandraSession.getKeyspaceByCaseInsensitiveName(NativeCassandraSession.java:258)
        at io.prestosql.plugin.cassandra.NativeCassandraSession.getCaseSensitiveTableNames(NativeCassandraSession.java:175)
        at io.prestosql.plugin.cassandra.CassandraMetadata.listTables(CassandraMetadata.java:140)
        at io.prestosql.metadata.MetadataManager.listTables(MetadataManager.java:549)
        at io.prestosql.connector.informationschema.InformationSchemaMetadata.lambda$calculatePrefixesWithTableName$7(InformationSchemaMetadata.java:305)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at io.prestosql.connector.informationschema.InformationSchemaMetadata.calculatePrefixesWithTableName(InformationSchemaMetadata.java:309)
        at io.prestosql.connector.informationschema.InformationSchemaMetadata.getTableLayouts(InformationSchemaMetadata.java:243)
        at io.prestosql.metadata.MetadataManager.getLayout(MetadataManager.java:404)
        at io.prestosql.sql.planner.iterative.rule.PushPredicateIntoTableScan.pushFilterIntoTableScan(PushPredicateIntoTableScan.java:212)
        at io.prestosql.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:107)
        at io.prestosql.sql.planner.iterative.rule.PushPredicateIntoTableScan.apply(PushPredicateIntoTableScan.java:71)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:165)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:140)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:105)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:190)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:107)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:190)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:107)
        at io.prestosql.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:96)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:170)
        at io.prestosql.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:159)
        at io.prestosql.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:423)
        at io.prestosql.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:408)
        at io.prestosql.execution.SqlQueryExecution.startExecution(SqlQueryExecution.java:352)
        at io.prestosql.$gen.Presto_309____20200928_231647_1.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
It seems Presto should bypass the schema which it cannot analyze.

**Comment by tedyu** [comment]
Transferring to https://github.com/prestosql/presto/issues/5346
