### ISSUE TITLE
DROP TABLE not deleting data in S3

### ISSUE THREAD

**Issue by jmesney** [prestodb/presto#15308]
If user creates a table and populates it with 1 or more rows, and then drops the table, the table's file and folder structure remains in S3.  The table definition is correctly removed from the metastore however. This means any attempt to create a table of the same name will fail with a "Target directory for table x already exists' because the folder is still present in S3.  This happens consistently. 

Desired behaviour: Since this is a "managed" table and not an external table the metastore should also delete the folder from S3 to complete the DROP TABLE.  

To workaround: Find the folder for table x in AWS S3 mgmt console, and manually delete it. 

Steps to reproduce: 
```
presto:default> create table table1(start_date date);
CREATE TABLE
presto:default> insert into table1 values date('2020-10-13');
INSERT: 1 row
Query 20201013_130841_00133_yjuzs, FINISHED, 3 nodes
Splits: 36 total, 36 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 9% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak User Memory: 0B
Peak Total Memory: 122B
Peak Task Total Memory: 122B
0:01 [0 rows, 0B] [0 rows/s, 0B/s]
presto:default> drop table table1;
DROP TABLE
*presto:default> create table table1(start_date date);
Query 20201013_130905_00135_yjuzs failed: Target directory for table 'default.table1' already exists: s3a://xxxxxxxxx/table1
*com.facebook.presto.spi.PrestoException: Target directory for table 'default.table1' already exists: s3a://xxxxxxxxx/table1
	at com.facebook.presto.hive.HiveLocationService.forNewTable(HiveLocationService.java:65)
	at com.facebook.presto.hive.HiveMetadata.createTable(HiveMetadata.java:816)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.createTable(ClassLoaderSafeConnectorMetadata.java:343)
	at com.facebook.presto.metadata.MetadataManager.createTable(MetadataManager.java:641)
	at com.facebook.presto.execution.CreateTableTask.internalExecute(CreateTableTask.java:195)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:82)
	at com.facebook.presto.execution.CreateTableTask.execute(CreateTableTask.java:64)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:175)
	at com.facebook.presto.$gen.Presto_0_237_2_2020_9_22_433f0c7874_27bfcd5____20201013_090433_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:231)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$4(LocalDispatchQuery.java:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
presto:default>
```

**Comment by ashishtadose** [comment]
I could reproduce it in my local env, looks like ThriftHiveMetastore leaving couldn't delete data files while deleting S3 backed hive managed tables.

WIll debug some more to identify the fix.

**Comment by bmitchinson** [comment]
> This is because in s3 it creates "0" byte object at the s3 path, if you create just the table definition.
> 
> But, if you create a table along with data, drop table works fine. `create table table1 AS (SELECT date('2020-10-13') as "start_date") ` And then `drop table table1` will work fine.

Spent at least 2 work days trying to figure out why dropping from presto wouldn't delete from S3 (using minio as a replacement), and it turns out it was cause the table was empty. Thank you for this.

**Comment by shubhamg931** [comment]
@ameyamahajan thanks it works, but it is still not clear as to why data ingested via the `insert into table values ()` statement is not getting deleted. What difference does `create table as` statements make here since similar data is being generated in both cases?
Also, I tried ingesting data into the same table using the `insert into table select x from table2` statement and deletion for this table worked as well
