### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ravasan** [prestodb/presto#15363]
Running `./mvnw clean install` gives:

```
...
[INFO] ------------------------------------------------------------------------
[INFO] Building presto-root 0.244-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.0.0:clean (default-clean) @ presto-root ---
[INFO] Deleting /Users/prajwal/work/presto-cf/presto/target
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (default) @ presto-root ---
[INFO] 
[INFO] --- dependency-scope-maven-plugin:0.8:check (default) @ presto-root ---
[INFO] No test dependency scope issues found
[INFO] 
[INFO] --- license-maven-plugin:2.3:check (default) @ presto-root ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (checkstyle) @ presto-root ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ presto-root ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] argLine set to empty
[INFO] 
[INFO] --- git-commit-id-plugin:2.1.13:revision (default) @ presto-root ---
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:analyze-only (default) @ presto-root ---
[INFO] Skipping pom project
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:analyze-duplicate (default) @ presto-root ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:analyze-dep-mgt (default) @ presto-root ---
[INFO] Found Resolved Dependency/DependencyManagement mismatches:
[INFO] 	Ignoring Direct Dependencies.
[INFO] 	None
[INFO] 
[INFO] --- duplicate-finder-maven-plugin:1.2.1:check (default) @ presto-root ---
[INFO] Ignoring POM project!
[INFO] 
[INFO] --- modernizer-maven-plugin:1.7.1:modernizer (modernizer) @ presto-root ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:report (report) @ presto-root ---
[INFO] Skipping JaCoCo execution because property jacoco.skip is set.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:test-jar (attach-tests) @ presto-root ---
[INFO] Skipping packaging of the test-jar
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ presto-root ---
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-sources) @ presto-root ---
[INFO] 
[INFO] >>> spotbugs-maven-plugin:3.1.10:check (default) > :spotbugs @ presto-root >>>
[INFO] 
[INFO] --- spotbugs-maven-plugin:3.1.10:spotbugs (spotbugs) @ presto-root ---
[WARNING] Error injecting: org.codehaus.mojo.spotbugs.SpotBugsMojo
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
  at org.codehaus.mojo.spotbugs.SpotBugsMojo.<init>(Unknown Source)
  while locating org.codehaus.mojo.spotbugs.SpotBugsMojo

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
	at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:65)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:63)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at org.eclipse.sisu.inject.Guice4$1.get(Guice4.java:162)
	at org.eclipse.sisu.inject.LazyBeanEntry.getValue(LazyBeanEntry.java:81)
	at org.eclipse.sisu.plexus.LazyPlexusBean.getValue(LazyPlexusBean.java:51)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:519)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:353)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:198)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
	at org.codehaus.mojo.spotbugs.SpotBugsMojo.$getStaticMetaClass(SpotBugsMojo.groovy)
	at org.codehaus.mojo.spotbugs.SpotBugsMojo.<init>(SpotBugsMojo.groovy)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:86)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:133)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	... 36 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] presto-root ........................................ FAILURE [  4.756 s]
[INFO] presto-common ...................................... SKIPPED
[INFO] presto-spi ......................................... SKIPPED
[INFO] presto-plugin-toolkit .............................. SKIPPED
[INFO] presto-client ...................................... SKIPPED
[INFO] presto-parser ...................................... SKIPPED
[INFO] presto-array ....................................... SKIPPED
[INFO] presto-geospatial-toolkit .......................... SKIPPED
[INFO] presto-bytecode .................................... SKIPPED
[INFO] presto-matching .................................... SKIPPED
[INFO] presto-memory-context .............................. SKIPPED
[INFO] presto-expressions ................................. SKIPPED
[INFO] presto-tpch ........................................ SKIPPED
[INFO] presto-thrift-api .................................. SKIPPED
[INFO] presto-function-namespace-managers ................. SKIPPED
[INFO] presto-main ........................................ SKIPPED
[INFO] presto-resource-group-managers ..................... SKIPPED
[INFO] presto-thrift-testing-udf-server ................... SKIPPED
[INFO] presto-tests ....................................... SKIPPED
[INFO] presto-atop ........................................ SKIPPED
[INFO] presto-hive-common ................................. SKIPPED
[INFO] presto-cache ....................................... SKIPPED
[INFO] presto-jmx ......................................... SKIPPED
[INFO] presto-record-decoder .............................. SKIPPED
[INFO] presto-kafka ....................................... SKIPPED
[INFO] presto-redis ....................................... SKIPPED
[INFO] presto-accumulo .................................... SKIPPED
[INFO] presto-cassandra ................................... SKIPPED
[INFO] presto-blackhole ................................... SKIPPED
[INFO] presto-memory ...................................... SKIPPED
[INFO] presto-orc ......................................... SKIPPED
[INFO] presto-benchmark ................................... SKIPPED
[INFO] presto-parquet ..................................... SKIPPED
[INFO] presto-rcfile ...................................... SKIPPED
[INFO] presto-hive-metastore .............................. SKIPPED
[INFO] presto-hive ........................................ SKIPPED
[INFO] presto-hive-hadoop2 ................................ SKIPPED
[INFO] presto-i18n-functions .............................. SKIPPED
[INFO] presto-teradata-functions .......................... SKIPPED
[INFO] presto-example-http ................................ SKIPPED
[INFO] presto-local-file .................................. SKIPPED
[INFO] presto-tpcds ....................................... SKIPPED
[INFO] presto-raptor ...................................... SKIPPED
[INFO] presto-base-jdbc ................................... SKIPPED
[INFO] presto-testing-docker .............................. SKIPPED
[INFO] presto-mysql ....................................... SKIPPED
[INFO] presto-oracle ...................................... SKIPPED
[INFO] presto-postgresql .................................. SKIPPED
[INFO] presto-redshift .................................... SKIPPED
[INFO] presto-sqlserver ................................... SKIPPED
[INFO] presto-mongodb ..................................... SKIPPED
[INFO] presto-ml .......................................... SKIPPED
[INFO] presto-geospatial .................................. SKIPPED
[INFO] presto-jdbc ........................................ SKIPPED
[INFO] presto-cli ......................................... SKIPPED
[INFO] presto-product-tests ............................... SKIPPED
[INFO] presto-pinot-toolkit ............................... SKIPPED
[INFO] presto-pinot ....................................... SKIPPED
[INFO] presto-benchmark-driver ............................ SKIPPED
[INFO] presto-password-authenticators ..................... SKIPPED
[INFO] presto-session-property-managers ................... SKIPPED
[INFO] presto-kudu ........................................ SKIPPED
[INFO] presto-thrift-testing-server ....................... SKIPPED
[INFO] presto-thrift-connector ............................ SKIPPED
[INFO] presto-elasticsearch ............................... SKIPPED
[INFO] presto-druid ....................................... SKIPPED
[INFO] presto-server ...................................... SKIPPED
[INFO] presto-server-rpm .................................. SKIPPED
[INFO] presto-docs ........................................ SKIPPED
[INFO] presto-spark-common ................................ SKIPPED
[INFO] presto-verifier .................................... SKIPPED
[INFO] presto-testing-server-launcher ..................... SKIPPED
[INFO] presto-benchto-benchmarks .......................... SKIPPED
[INFO] presto-proxy ....................................... SKIPPED
[INFO] presto-benchmark-runner ............................ SKIPPED
[INFO] presto-spark-classloader-interface ................. SKIPPED
[INFO] presto-spark-base .................................. SKIPPED
[INFO] presto-spark ....................................... SKIPPED
[INFO] presto-spark-package ............................... SKIPPED
[INFO] presto-spark-launcher .............................. SKIPPED
[INFO] presto-spark-testing ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.217 s
[INFO] Finished at: 2020-10-27T14:42:43+05:30
[INFO] Final Memory: 83M/300M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.10:spotbugs (spotbugs) on project presto-root: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.10:spotbugs failed: Unable to load the mojo 'spotbugs' in the plugin 'com.github.spotbugs:spotbugs-maven-plugin:3.1.10'. A required class is missing: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.spotbugs:spotbugs-maven-plugin:3.1.10
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
...
```
Says it is a spotbugs plugin problem.

**Comment by highker** [comment]
Use java 8 with maven 3.5+ to compile
