### ISSUE TITLE
Failing when using the Function Namespace Managers 

### ISSUE THREAD

**Issue by lyzGithub** [prestodb/presto#15382]
Failing when using the Function Namespace Managers.
`2020-10-31T11:18:50.900+0800    ERROR   main    com.facebook.presto.server.PrestoServer No factory for function namespace manager mysql
java.lang.IllegalStateException: No factory for function namespace manager mysql
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
        at com.facebook.presto.metadata.FunctionManager.loadFunctionNamespaceManager(FunctionManager.java:166)
        at com.facebook.presto.metadata.StaticFunctionNamespaceStore.loadFunctionNamespaceManager(StaticFunctionNamespaceStore.java:72)
        at com.facebook.presto.metadata.StaticFunctionNamespaceStore.loadFunctionNamespaceManagers(StaticFunctionNamespaceStore.java:57)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:149)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:77)`

 The configuration file is:
`root@mdw:/opt/prestodb# cat etc/function-namespace/example.properties 
function-namespace-manager.name=mysql
database-url=jdbc:mysql://localhost:3306/
function-namespaces-table-name=example_function_namespaces
functions-table-name=example_sql_functions`

**Comment by beinan** [comment]
Looks like the plugin/function-namespace-managers has not been loaded.  How did you start presto?

**Comment by lyzGithub** [comment]
> Looks like the plugin/function-namespace-managers has not been loaded. How did you start presto?

Thanks for reply. Presto ran in a single node. I used the presto-server-0.242.1.tar.gz package downloaded from prestodb.io and also built package on the branch release-0.242. And I have found that there is no `plugin/function-namespace-managers` dir  in the installation package. So Is the feature [Function Namespace Managers](https://prestodb.io/docs/current/admin/function-namespace-managers.html) not ready for now?

**Comment by lyzGithub** [comment]
Or is there any wrong action I made when I wrote the configuration file or start the presto? And do anyone have a more detailed configuration guide to set up the Function Namespace Managers ?

**Comment by beinan** [comment]
If you build and start presto locally, you can append the function-namespace-managers plugin into the plugin.bundles in the config.properties.

`plugin.bundles=\

  ../presto-function-namespace-managers/pom.xml,\
`

The function namespace managers is ready to use, I just happened to use it a few weeks ago.  The key point is making presto server load the plugin, otherwise we would see a failure of 'No factory for function namespace manager mysql' as you reported.

**Comment by lyzGithub** [comment]
> If you build and start presto locally, you can append the function-namespace-managers plugin into the plugin.bundles in the config.properties.
> 
> `plugin.bundles=\
> 
> ../presto-function-namespace-managers/pom.xml,
> `
> 
> The function namespace managers is ready to use, I just happened to use it a few weeks ago. The key point is making presto server load the plugin, otherwise we would see a failure of 'No factory for function namespace manager mysql' as you reported.

SO I get the newest code from the master branch and run the presto in the IDE and config an function namespace example file according to the office docs:
![image](https://user-images.githubusercontent.com/9393130/100823990-47d4de80-3490-11eb-8506-8c9e848ab688.png)
The the plugin.bundles  have been added to the config.properties by default. And I got another error:
![image](https://user-images.githubusercontent.com/9393130/100824176-a0a47700-3490-11eb-9e0a-ae0c0d6c461b.png)
What can caused this problem?

**Comment by ingomueller-net** [comment]
Does #15501 address this issue?

**Comment by ingomueller-net** [comment]
I think that this is a documentation issue. #15642 formulates it that way. With version 0.246, I managed to make UDFs work and the issue mentions a number of things I had to find out because they were not documented.

**Comment by dborkar** [comment]
@rongrong this is coming up more. Can you take a look?
