### ISSUE TITLE
Insert query to partitioned table fails when there are 1000 partitions even though the number of records are very less.

### ISSUE THREAD

**Issue by pradeepagrawal8184** [prestodb/presto#15409]
Problem Statement: Insertion to partition table is failing in limited memory environment even with a small dataset. For large no. of partitions (1000 partitions) lot of memory (more than 4GB) is required even for small datasets of few MB.
If a table has partition on columns where partition columns contains around 1000 distinct values then insert operation to partitioned column fails with error message “exceeded per-node total memory limit”(refer below image). 

`io.prestosql.ExceededMemoryLimitException: Query exceeded per-node total memory limit of 7GB [Allocated: 6.30GB, Delta: 1005.39MB, Top Consumers: {TableWriterOperator=6.30GB}]
        at io.prestosql.ExceededMemoryLimitException.exceededLocalTotalMemoryLimit(ExceededMemoryLimitException.java:46)
        at io.prestosql.memory.QueryContext.enforceTotalMemoryLimit(QueryContext.java:330)
        at io.prestosql.memory.QueryContext.updateSystemMemory(QueryContext.java:174)
        at io.prestosql.memory.QueryContext$QueryMemoryReservationHandler.reserveMemory(QueryContext.java:303)
        at io.prestosql.memory.context.RootAggregatedMemoryContext.updateBytes(RootAggregatedMemoryContext.java:37)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.ChildAggregatedMemoryContext.updateBytes(ChildAggregatedMemoryContext.java:38)
        at io.prestosql.memory.context.SimpleLocalMemoryContext.setBytes(SimpleLocalMemoryContext.java:66)
        at io.prestosql.operator.OperatorContext$InternalLocalMemoryContext.setBytes(OperatorContext.java:662)
        at io.prestosql.operator.TableWriterOperator.updateMemoryUsage(TableWriterOperator.java:380)
        at io.prestosql.operator.TableWriterOperator.addInput(TableWriterOperator.java:267)
        at io.prestosql.operator.Driver.processInternal(Driver.java:384)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1087)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_____20201028_124129_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

Note: Default max supported partition is 100. add properties in hive.config file and set hive.max-partitions-per-writers=1000

Ref : 
https://github.com/prestosql/presto/blob/master/presto-main/src/main/java/io/prestosql/operator/TableWriterOperator.java#L257  (calls HivePageSink.appendPage())
https://github.com/prestosql/presto/blob/master/presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSink.java#L300
https://github.com/prestosql/presto/blob/master/presto-orc/src/main/java/io/prestosql/orc/OrcWriter.java#L289

If more information required please let me know.

**Comment by findepi** [comment]
@pradeepagrawal8184  PrestoSQL releases are maintained at https://github.com/prestosql/presto.
Also, there is the `#troubleshooting` channel on Presto Community Slack (https://prestosql.io/slack.html)
