### ISSUE TITLE
error while running hive queries 'alter table concatenate'

### ISSUE THREAD

**Issue by zshit** [prestodb/presto#15411]
first I create table in presto 
`CREATE TABLE  hive.db.ods_test (
tid bigint,
msg varchar,
pt varchar
) with(partitioned_by = array['pt']);`
then insert rows to different orcfiles
`insert into hive.db.ods_test values(1,'empty msg' ,'202011');`
` insert into hive.db.ods_test values(2,null,'202011');`

 I try to merge orcfiles but error happens while running hive queries 'alter table hive.ods_test partition (pt='202011') ' 

`2020-11-04T17:37:06,060 ERROR [LocalJobRunner Map Task Executor #0] OrcFileMergeOperator: Closing operator..Exception: java.lang.IllegalArgumentException: Incompatible merging of string column statistics
        at org.apache.orc.impl.ColumnStatisticsImpl$StringStatisticsImpl.merge(ColumnStatisticsImpl.java:602)
        at org.apache.orc.impl.writer.TreeWriterBase.updateFileStatistics(TreeWriterBase.java:345)
        at org.apache.orc.impl.writer.StructTreeWriter.updateFileStatistics(StructTreeWriter.java:127)
        at org.apache.orc.impl.WriterImpl.appendStripe(WriterImpl.java:648)
        at org.apache.hadoop.hive.ql.exec.OrcFileMergeOperator.processKeyValuePairs(OrcFileMergeOperator.java:160)
        at org.apache.hadoop.hive.ql.exec.OrcFileMergeOperator.process(OrcFileMergeOperator.java:74)
        at org.apache.hadoop.hive.ql.io.merge.MergeFileMapper.map(MergeFileMapper.java:100)
        at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
        at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)`

while runnig `insert into hive.db.ods_test values(2,null,'202011') ` 
StringStatisticsBuilder create ColumnStatistics object with a **null** stringStatistics attribute.
code in presto :
```java
public ColumnStatistics buildColumnStatistics()
    {
        Optional<StringStatistics> stringStatistics = buildStringStatistics();
        stringStatistics.ifPresent(s -> verify(nonNullValueCount > 0));
        return new ColumnStatistics(
                nonNullValueCount,
                stringStatistics.map(s -> STRING_VALUE_BYTES_OVERHEAD + sum / nonNullValueCount).orElse(0L),
                null,
                null,
                null,
                stringStatistics.orElse(null),
                null,
                null,
                null,
                null);
    }
```

code in apache-orc throw IllegalArgumentException
```java
 public void merge(ColumnStatisticsImpl other) {
      if (other instanceof StringStatisticsImpl) {
       ...
      } else {
        if (isStatsExists() && minimum != null) {
          throw new IllegalArgumentException("Incompatible merging of string column statistics");
        }
      }
```

**Comment by ljluestc** [comment]
```
public ColumnStatistics buildColumnStatistics() {
    Optional<StringStatistics> stringStatistics = buildStringStatistics();
    stringStatistics.ifPresent(s -> verify(nonNullValueCount > 0));
    
    // Check for empty 'minimum' value
    Slice minimumValue = stringStatistics.map(StringStatistics::getMinimum).orElse(null);
    Slice maximumValue = stringStatistics.map(StringStatistics::getMaximum).orElse(null);
    
    if (minimumValue != null && maximumValue != null && minimumValue.compareTo(maximumValue) > 0) {
        // Handle empty 'minimum' value
        minimumValue = maximumValue;
    }

    return new ColumnStatistics(
            nonNullValueCount,
            stringStatistics.map(s -> STRING_VALUE_BYTES_OVERHEAD + sum / nonNullValueCount).orElse(0L),
            minimumValue,
            null,
            null,
            stringStatistics.orElse(null),
            null,
            null,
            null,
            null);
}
```
