### ISSUE TITLE
TestBlockBuilder and TestBlockEncodingBuffer crashing

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#15543]
I've seen crashes in these tests a few times. 

Example error logs:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project presto-main: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/prestodb/presto/presto-main/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/prestodb/presto/presto-main && /usr/lib/jvm/java-8-oracle/jre/bin/java -Dfile.encoding=UTF-8 -Xmx4g -Xms4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/travis/build/prestodb/presto/presto-main/target/surefire/surefirebooter5947601471425078169.jar /home/travis/build/prestodb/presto/presto-main/target/surefire 2020-12-17T16-39-52_477-jvmRun1 surefire7554938500306809614tmp surefire_01437631571422695189tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] com.facebook.presto.block.TestBlockBuilder
[ERROR] com.facebook.presto.operator.repartition.TestBlockEncodingBuffers
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/travis/build/prestodb/presto/presto-main && /usr/lib/jvm/java-8-oracle/jre/bin/java -Dfile.encoding=UTF-8 -Xmx4g -Xms4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/travis/build/prestodb/presto/presto-main/target/surefire/surefirebooter5947601471425078169.jar /home/travis/build/prestodb/presto/presto-main/target/surefire 2020-12-17T16-39-52_477-jvmRun1 surefire7554938500306809614tmp surefire_01437631571422695189tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 3
[ERROR] Crashed tests:
[ERROR] com.facebook.presto.block.TestBlockBuilder
[ERROR] com.facebook.presto.operator.repartition.TestBlockEncodingBuffers
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
[ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[ERROR] 	at java.lang.Thread.run(Thread.java:748)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by mbasmanova** [comment]
I'm disabling slow parts of this test in https://github.com/prestodb/presto/pull/15643

**Comment by mbasmanova** [comment]
CC: @bhhari @jbroll @sujay-jain @rongrong

**Comment by rschlussel** [comment]
@mbasmanova I'm still seeing this issue

```
2021-03-04T22:05:49.6562281Z [ERROR] Error occurred in starting fork, check output in log
2021-03-04T22:05:49.6562893Z [ERROR] Process Exit Code: 3
2021-03-04T22:05:49.6563361Z [ERROR] Crashed tests:
2021-03-04T22:05:49.6564269Z [ERROR] com.facebook.presto.block.TestBlockBuilder
2021-03-04T22:05:49.6566190Z [ERROR] com.facebook.presto.operator.repartition.TestBlockEncodingBuffers
2021-03-04T22:05:49.6568952Z [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
2021-03-04T22:05:49.6573756Z [ERROR] Command was /bin/sh -c cd /home/runner/work/presto/presto/presto-main && /opt/hostedtoolcache/jdk/8.0.282/x64/jre/bin/java -Dfile.encoding=UTF-8 -Xmx4g -Xms4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -jar /home/runner/work/presto/presto/presto-main/target/surefire/surefirebooter956568151874963175.jar /home/runner/work/presto/presto/presto-main/target/surefire 2021-03-04T22-00-56_226-jvmRun1 surefire6907275898387873456tmp surefire_05640529451610831842tmp
2021-03-04T22:05:49.6576618Z [ERROR] Error occurred in starting fork, check output in log
2021-03-04T22:05:49.6577270Z [ERROR] Process Exit Code: 3
2021-03-04T22:05:49.6577733Z [ERROR] Crashed tests:
2021-03-04T22:05:49.6578635Z [ERROR] com.facebook.presto.block.TestBlockBuilder
2021-03-04T22:05:49.6580559Z [ERROR] com.facebook.presto.operator.repartition.TestBlockEncodingBuffers
2021-03-04T22:05:49.6583141Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
2021-03-04T22:05:49.6585705Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
2021-03-04T22:05:49.6588244Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
2021-03-04T22:05:49.6590936Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
2021-03-04T22:05:49.6593842Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
2021-03-04T22:05:49.6597758Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1022)
2021-03-04T22:05:49.6601287Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:868)
2021-03-04T22:05:49.6603762Z [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2021-03-04T22:05:49.6606070Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
2021-03-04T22:05:49.6608036Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
2021-03-04T22:05:49.6610007Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
2021-03-04T22:05:49.6612495Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2021-03-04T22:05:49.6615722Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)
2021-03-04T22:05:49.6619099Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)
2021-03-04T22:05:49.6621364Z [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-03-04T22:05:49.6622509Z [ERROR] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2021-03-04T22:05:49.6623675Z [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-03-04T22:05:49.6625136Z [ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2021-03-04T22:05:49.6626788Z [ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2021-03-04T22:05:49.6627881Z [ERROR] 	at java.lang.Thread.run(Thread.java:748)
2021-03-04T22:05:49.6628533Z [ERROR] -> [Help 1]
2021-03-04T22:05:49.6628876Z [ERROR] 
```
