### ISSUE TITLE
No nodes available to run query 

### ISSUE THREAD

**Issue by xuhang1458** [prestodb/presto#15566]
My custom IotDB connection plug-in performs a SELECT * ·· An exception appears

com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.execution.scheduler.nodeSelection.SimpleNodeSelector.computeAssignments(SimpleNodeSelector.java:155)
	at com.facebook.presto.execution.scheduler.DynamicSplitPlacementPolicy.computeAssignments(DynamicSplitPlacementPolicy.java:42)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:273)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler$1.schedule(SourcePartitionedScheduler.java:147)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.schedule(LegacySqlQueryScheduler.java:423)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I don't have that problem querying other catalogs, right? Please help me

**Comment by SonuSingh200190** [comment]
Please let me know how many workers and coordinator nodes do you have?

I have faced the same issue before and reason could be the following:
1. worker node doesn't have a particular catalog.properties, please add that catalog and restart presto-server on the worker node.
2. if the coordinator node has that catalog.properties then please add below key and value in config.properties
**node-scheduler.include-coordinator=true**
and please restart presto-server on the coordinator node. 
your issue will be solved.
