### ISSUE TITLE
Presto 0.246 returns a division by zero stacktrace

### ISSUE THREAD

**Issue by elukey** [prestodb/presto#15685]
Hi everybody,

I have upgraded Prestodb from 0.226 to 0.246, and adjusted some config parameters to adapt to the new version. My testing environment is very simple, one query coordinator and one worker node. When I try to execute a query that uses the Hive catalog, I always see the following returned:

```
java.lang.ArithmeticException: / by zero
	at com.facebook.presto.sql.planner.NodePartitioningManager.createArbitraryBucketToNode(NodePartitioningManager.java:256)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getBucketNodeMap(NodePartitioningManager.java:189)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:335)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:343)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:233)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:164)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:474)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:347)
	at com.facebook.presto.$gen.Presto_0_246_b4fb470____20210205_091342_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:254)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$5(LocalDispatchQuery.java:114)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The code that yields the exception seems to be doing a division indeed, but I have no idea why by zero since the worker node is correctly recognized by the coordinator (I checked in the IU as well). Can you give me more info about why this error happens?

**Comment by elukey** [comment]
If I add the `hive.node-selection-strategy` config to something like `SOFT_AFFINITY` then the division by zero is not thrown anymore, but the query gets stuck in PLANNING. In my settings the Presto worker is not co-located with HDFS data.

**Comment by elukey** [comment]
```
    private static List<InternalNode> createArbitraryBucketToNode(List<InternalNode> nodes, int bucketCount)
    {
        List<InternalNode> shuffledNodes = new ArrayList<>(nodes);
        Collections.shuffle(shuffledNodes);

        ImmutableList.Builder<InternalNode> distribution = ImmutableList.builderWithExpectedSize(bucketCount);
        for (int i = 0; i < bucketCount; i++) {
            distribution.add(shuffledNodes.get(i % shuffledNodes.size()));  <================
        }
        return distribution.build();
    }
```

**Comment by elukey** [comment]
Any idea/suggestion? :)

**Comment by elukey** [comment]
The above stacktrace is returned when I try to query a Hive table with 256 buckets, that works fine with 0.226 thought.

I tried another one without bucketing, but now I get:

```
com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.execution.scheduler.nodeSelection.SimpleNodeSelector.computeAssignments(SimpleNodeSelector.java:155)
	at com.facebook.presto.execution.scheduler.DynamicSplitPlacementPolicy.computeAssignments(DynamicSplitPlacementPolicy.java:42)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:273)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler$1.schedule(SourcePartitionedScheduler.java:147)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.schedule(LegacySqlQueryScheduler.java:423)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Even if I see an active worker in the Presto UI...

**Comment by rschlussel** [comment]
Does this only happen with bucketed tables?

**Comment by elukey** [comment]
> Does this only happen with bucketed tables?

Hi! Thanks for following up! The division by zero exception yes, it seems happening with a hive bucketed table, but not with a table without buckets. The last stacktrace (no nodes available) happens with the table without buckets.

**Comment by rschlussel** [comment]
Okay, so at least that's consistent.  Can you share your configuration? also, does the node show up if you do `SELECT * FROM system.runtime.nodes`?

**Comment by rschlussel** [comment]
Basically it sounds like the original error should be improved to instead throw a no nodes available error, but the actual issue, is the scheduler isn't finding any nodes where it can run your hive query.

**Comment by elukey** [comment]
Sure!

```
presto:runtime> SELECT * FROM nodes;
            node_id             |                  http_uri                   | node_version  | coordinator | state  
--------------------------------+---------------------------------------------+---------------+-------------+--------
 an-test-coord1001-eqiad-wmnet  | https://an-test-coord1001.eqiad.wmnet:8281  | 0.246-b4fb470 | true        | active 
 an-test-presto1001-eqiad-wmnet | https://an-test-presto1001.eqiad.wmnet:8281 | 0.246-b4fb470 | false       | active 
(2 rows)

Query 20210208_205209_00038_brdzt, FINISHED, 2 nodes
Splits: 17 total, 17 done (100.00%)
0:00 [2 rows, 184B] [12 rows/s, 1.12KB/s]
```

* Query coordinator config.properties
```
coordinator=true
discovery-server.enabled=true
discovery.uri=https://an-test-coord1001.eqiad.wmnet:8281
http-server.authentication.type=KERBEROS
http-server.http.enabled=true
http-server.http.port=8280
http-server.https.enabled=true
http-server.https.keystore.key=redacted
http-server.https.keystore.path=/etc/presto/ssl/server.p12
http-server.https.port=8281
http.authentication.krb5.config=/etc/krb5.conf
http.server.authentication.krb5.keytab=/etc/security/keytabs/presto/presto.keytab
http.server.authentication.krb5.service-name=presto
internal-communication.https.keystore.key=redacted
internal-communication.https.keystore.path=/etc/presto/ssl/server.p12
internal-communication.https.required=true
internal-communication.https.trust-store-password=redacted
internal-communication.https.trust-store-path=/etc/ssl/certs/java/cacerts
internal-communication.kerberos.enabled=true
jmx.rmiregistry.port=8279
node-scheduler.include-coordinator=false
node-scheduler.network-topology=legacy
query.max-memory=2GB
query.max-memory-per-node=2GB
query.max-total-memory-per-node=2GB
```
Worker config.properties
```
coordinator=false
discovery.uri=https://an-test-coord1001.eqiad.wmnet:8281
http-server.authentication.type=KERBEROS
http-server.http.enabled=false
http-server.http.port=8280
http-server.https.enabled=true
http-server.https.keystore.key=redacted
http-server.https.keystore.path=/etc/presto/ssl/server.p12
http-server.https.port=8281
http.authentication.krb5.config=/etc/krb5.conf
http.server.authentication.krb5.keytab=/etc/security/keytabs/presto/presto.keytab
http.server.authentication.krb5.service-name=presto
internal-communication.https.keystore.key=redacted
internal-communication.https.keystore.path=/etc/presto/ssl/server.p12
internal-communication.https.required=true
internal-communication.https.trust-store-password=redacted
internal-communication.https.trust-store-path=/etc/ssl/certs/java/cacerts
internal-communication.kerberos.enabled=true
jmx.rmiregistry.port=8279
node-scheduler.include-coordinator=false
node-scheduler.network-topology=legacy
query.max-memory=2GB
query.max-memory-per-node=2GB
query.max-total-memory-per-node=2GB
```

Query coordinator / Worker hive catalog properties
```
connector.name=hive-hadoop2
hive.compression-codec=SNAPPY
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
hive.hdfs.authentication.type=KERBEROS
hive.hdfs.impersonation.enabled=true
hive.hdfs.presto.keytab=/etc/security/keytabs/presto/presto.keytab
hive.hdfs.presto.principal=presto/an-test-coord1001.eqiad.wmnet@WIKIMEDIA
hive.hdfs.wire-encryption.enabled=true
hive.metastore.authentication.type=KERBEROS
hive.metastore.client.keytab=/etc/security/keytabs/presto/presto.keytab
hive.metastore.client.principal=presto/an-test-coord1001.eqiad.wmnet@WIKIMEDIA
hive.metastore.service.principal=hive/analytics-test-hive.eqiad.wmnet@WIKIMEDIA
hive.metastore.uri=thrift://analytics-test-hive.eqiad.wmnet:9083
hive.metastore.username=presto
hive.non-managed-table-creates-enabled=true
hive.non-managed-table-writes-enabled=true
hive.security=read-only
hive.storage-format=PARQUET
```
```

**Comment by rschlussel** [comment]
I suspect what's happening is that the worker doesn't know about the hive catalog.  Can you double check that the file is there and in the right directory and try restarting the worker (you always need to restart after config changes, since Presto won't pick them up automatically)?  Another thing to try would be to try adding another connector (e.g. add the tpch connector https://prestodb.io/docs/current/connector/tpch.html) and see if you can query that.

**Comment by elukey** [comment]
@rschlussel the catalog config file properties had a typo in its filename, you were absolutely right, everything works now :)
