### ISSUE TITLE
error when connect to elasticSearch: missing authentication credentials for REST request 

### ISSUE THREAD

**Issue by zhouxinghua** [prestodb/presto#15693]
2021-02-08T14:07:49.490+0800	ERROR	NodeRefresher	com.facebook.presto.elasticsearch.client.ElasticsearchClient	Error refreshing nodes
com.facebook.presto.spi.PrestoException: method [GET], host [http://172.16.30.3:9204], URI [/_nodes/http], status line [HTTP/1.1 401 Unauthorized]
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/_nodes/http]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/_nodes/http]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}
	at com.facebook.presto.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:664)
	at com.facebook.presto.elasticsearch.client.ElasticsearchClient.fetchNodes(ElasticsearchClient.java:354)
	at com.facebook.presto.elasticsearch.client.ElasticsearchClient.refreshNodes(ElasticsearchClient.java:163)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
---------------------------------------------------------------------------------------------
as indicated above, my presto-server version is 0.246 and elasticsearch version is 7.9,  exception has occured when I try to connected elasticsearch , So How should I add the username and password of elasticsearch to etc/catalog/elasticsearch.properties ?

**Comment by agrawalreetika** [comment]
@zhouxinghua Could you please provide your catalog details? And are you getting the above error while querying from your configured catalog?

**Comment by zhouxinghua** [comment]
> @zhouxinghua Could you please provide your catalog details? And are you getting the above error while querying from your configured catalog?

this error happened when I start my presto server and try connect to elasticSearch,  catalog is here:
--------------------------------------------------------
connector.name=elasticsearch
elasticsearch.host=xxx
elasticsearch.port=9200
elasticsearch.default-schema-name=xxx
-----------------------------------------------------------
