### ISSUE TITLE
[Alluxio catalog] Loading alluxio catalog error

### ISSUE THREAD

**Issue by jasondavindev** [prestodb/presto#15734]
Since 19th day I'm getting an error when running the prestodb container connected to alluxio. When the loading steps starts, I get the error below:

```
2021-02-22T18:10:09.218Z	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Loading catalog alluxio --
2021-02-22T18:10:09.558Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize()J
  at com.facebook.presto.hive.metastore.alluxio.AlluxioMetastoreModule.provideCatalogMasterClient(AlluxioMetastoreModule.java:58) (via modules: com.facebook.presto.hive.metastore.HiveMetastoreModule -> com.facebook.airlift.configuration.ConditionalModule -> com.facebook.presto.hive.metastore.alluxio.AlluxioMetastoreModule)
  while locating alluxio.client.table.TableMasterClient
    for the 1st parameter of com.facebook.presto.hive.metastore.alluxio.AlluxioHiveMetastore.<init>(AlluxioHiveMetastore.java:74)
  while locating com.facebook.presto.hive.metastore.alluxio.AlluxioHiveMetastore
  at com.facebook.presto.hive.metastore.alluxio.AlluxioMetastoreModule.setup(AlluxioMetastoreModule.java:50) (via modules: com.facebook.presto.hive.metastore.HiveMetastoreModule -> com.facebook.airlift.configuration.ConditionalModule -> com.facebook.presto.hive.metastore.alluxio.AlluxioMetastoreModule)
  while locating com.facebook.presto.hive.metastore.ExtendedHiveMetastore
    for the 3rd parameter of com.facebook.presto.hive.HiveMetadataFactory.<init>(HiveMetadataFactory.java:93)
  at com.facebook.presto.hive.HiveClientModule.configure(HiveClientModule.java:143)
  while locating com.facebook.presto.hive.HiveMetadataFactory
  at com.facebook.presto.hive.HiveClientModule.configure(HiveClientModule.java:144)
  while locating java.util.function.Supplier<com.facebook.presto.hive.TransactionalMetadata>
Caused by: java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize()J
	at sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize(Native Method)
	at alluxio.conf.PropertyKey.lambda$static$8(PropertyKey.java:2647)
	at alluxio.DefaultSupplier.get(DefaultSupplier.java:34)
	at alluxio.conf.PropertyKey.getDefaultValue(PropertyKey.java:6093)
	at alluxio.conf.InstancedConfiguration.validate(InstancedConfiguration.java:397)
	at alluxio.util.ConfigurationUtils.reloadProperties(ConfigurationUtils.java:456)
	at alluxio.util.ConfigurationUtils.defaults(ConfigurationUtils.java:404)
	at com.facebook.presto.hive.metastore.alluxio.AlluxioMetastoreModule.provideCatalogMasterClient(AlluxioMetastoreModule.java:58)
	at com.facebook.presto.hive.metastore.alluxio.AlluxioMetastoreModule$$FastClassByGuice$$23fb71ca.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:136)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:379)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:231)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:223)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:209)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:138)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:79)
....
and repeat 8 times to java.lang.UnsatisfiedLinkError: sun.management.OperatingSystemImpl.getTotalPhysicalMemorySize()J
...
...
...
```

At first I was thinking that my new presto plugin for event listener was causing the error, but I revert all the changes, clearing the plugin code & dependencies and rebuild the presto docker image, and then the error persists.
When I remove the alluxio catalog properties file the prestodb server starts. For now, I'm using the old docker image to the prestodb to work.

Presto Version: 0.245.1
Alluxio Version: 2.4.1-2
OS Version: Ubuntu 20
Docker Version: 20.10.3

**Comment by jasondavindev** [comment]
I solved this problem upgrading openjdk to version 11 (Docker image `openjdk:11-jdk-slim`) and fix JMX configurations to start up the presto.
References links:
https://github.com/Alluxio/alluxio/issues/12882
https://github.com/Alluxio/alluxio/pull/12884
