### ISSUE TITLE
Cassandra product tests not passing

### ISSUE THREAD

**Issue by aweisberg** [prestodb/presto#15749]
I am guessing this is a Tempto issue with us passing the wrong type to the cassandra driver for the column https://stackoverflow.com/questions/41480481/codec-not-found-for-requested-operation-date-java-util-date
Could also be a mistake in the test definition
https://travis-ci.com/github/prestodb/presto/builds/218243799
```
2021-02-25 20:22:55 SEVERE: cannot initialize test suite
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [date <-> java.lang.Float]
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:806)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:649)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:631)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:556)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:80)
	at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:204)
	at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:134)
	at io.prestodb.tempto.internal.fulfillment.table.cassandra.CassandraBatchLoader.load(CassandraBatchLoader.java:78)
	at io.prestodb.tempto.internal.fulfillment.table.cassandra.CassandraTableManager.insertData(CassandraTableManager.java:103)
	at io.prestodb.tempto.internal.fulfillment.table.cassandra.CassandraTableManager.createImmutable(CassandraTableManager.java:87)
	at io.prestodb.tempto.internal.fulfillment.table.cassandra.CassandraTableManager.createImmutable(CassandraTableManager.java:45)
	at io.prestodb.tempto.fulfillment.table.TableManager.createImmutable(TableManager.java:45)
	at io.prestodb.tempto.internal.fulfillment.table.ImmutableTablesFulfiller.createTable(ImmutableTablesFulfiller.java:46)
	at io.prestodb.tempto.internal.fulfillment.table.ImmutableTablesFulfiller.createTable(ImmutableTablesFulfiller.java:28)
	at io.prestodb.tempto.internal.fulfillment.table.TableRequirementFulfiller.createTable(TableRequirementFulfiller.java:76)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.prestodb.tempto.internal.fulfillment.table.TableRequirementFulfiller.fulfill(TableRequirementFulfiller.java:60)
	at io.prestodb.tempto.internal.initialization.TestInitializationListener.lambda$doFulfillment$0(TestInitializationListener.java:326)
	at io.prestodb.tempto.context.TestContextDsl.runWithTestContext(TestContextDsl.java:51)
	at io.prestodb.tempto.internal.initialization.TestInitializationListener.doFulfillment(TestInitializationListener.java:324)
	at io.prestodb.tempto.internal.initialization.TestInitializationListener.onStart(TestInitializationListener.java:189)
	at org.testng.TestRunner.fireEvent(TestRunner.java:1210)
	at org.testng.TestRunner.beforeRun(TestRunner.java:629)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at io.prestodb.tempto.runner.TemptoRunner.run(TemptoRunner.java:94)
	at io.prestodb.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:67)
	at io.prestodb.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:55)
	at com.facebook.presto.tests.TemptoProductTestRunner.main(TemptoProductTestRunner.java:27)
```

**Comment by v-jizhang** [comment]
I'll take a look.

**Comment by v-jizhang** [comment]
It's a mistake in the test definition in DataTypesTableDefinition.java
There is a discrepancy between table creation and the data.
I'll fix it.
