### ISSUE TITLE
Run Presto-0.247 in IDEA throws "No suitable driver found for jdbc:mysql" in function namespace manager

### ISSUE THREAD

**Issue by lzwang2** [prestodb/presto#15747]
I downloaded Tag 0.247.
Cmd "./mvnw clean install -DskipTests" succeed.
Then I imported the project into IntelliJ IDEA, and everything seems to be fine.
I created  a run configuration according to the docs, as below:

_Main Class: com.facebook.presto.server.PrestoServer
VM Options: -ea -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent -Xmx2G -Dconfig=etc/config.properties -Dlog.levels-file=etc/log.properties
Working directory: $MODULE_DIR$
Use classpath of module: presto-main_

I started to run PrestoServer, and it failed with exception below.

```
2021-02-25T15:29:36.970+0800	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error notifying ProvisionListener com.facebook.airlift.bootstrap.LifeCycleModule$$Lambda$2262/699104460 of com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager.
 Reason: com.facebook.airlift.bootstrap.LifeCycleStartException: Exception in PostConstruct method com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager::initialize()
  at com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManagerModule.configure(MySqlFunctionNamespaceManagerModule.java:43)
  while locating com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error notifying ProvisionListener com.facebook.airlift.bootstrap.LifeCycleModule$$Lambda$2262/699104460 of com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager.
 Reason: com.facebook.airlift.bootstrap.LifeCycleStartException: Exception in PostConstruct method com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager::initialize()
  at com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManagerModule.configure(MySqlFunctionNamespaceManagerModule.java:43)
  while locating com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManagerFactory.create(MySqlFunctionNamespaceManagerFactory.java:59)
	at com.facebook.presto.metadata.FunctionAndTypeManager.loadFunctionNamespaceManager(FunctionAndTypeManager.java:165)
	at com.facebook.presto.metadata.StaticFunctionNamespaceStore.loadFunctionNamespaceManager(StaticFunctionNamespaceStore.java:81)
	at com.facebook.presto.metadata.StaticFunctionNamespaceStore.loadFunctionNamespaceManagers(StaticFunctionNamespaceStore.java:63)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:152)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:79)
Caused by: com.facebook.airlift.bootstrap.LifeCycleStartException: Exception in PostConstruct method com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager::initialize()
	at com.facebook.airlift.bootstrap.LifeCycleManager.startInstance(LifeCycleManager.java:245)
	at com.facebook.airlift.bootstrap.LifeCycleManager.addInstance(LifeCycleManager.java:211)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:62)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	... 9 more
Caused by: org.jdbi.v3.core.ConnectionException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:300)
	at org.jdbi.v3.core.LazyHandleSupplier.initHandle(LazyHandleSupplier.java:58)
	at org.jdbi.v3.core.LazyHandleSupplier.getHandle(LazyHandleSupplier.java:46)
	at org.jdbi.v3.sqlobject.statement.internal.CustomizingStatementHandler.invoke(CustomizingStatementHandler.java:148)
	at org.jdbi.v3.sqlobject.statement.internal.SqlUpdateHandler.invoke(SqlUpdateHandler.java:30)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$null$13(SqlObjectFactory.java:163)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
	at org.jdbi.v3.core.LazyHandleSupplier.lambda$invokeInContext$1(LazyHandleSupplier.java:72)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
	at org.jdbi.v3.core.LazyHandleSupplier.invokeInContext(LazyHandleSupplier.java:71)
	at org.jdbi.v3.sqlobject.SqlObjectFactory.lambda$createInvocationHandler$14(SqlObjectFactory.java:162)
	at org.jdbi.v3.core.OnDemandExtensions.invoke(OnDemandExtensions.java:76)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$0(OnDemandExtensions.java:63)
	at org.jdbi.v3.core.internal.JdbiThreadLocals.invokeInContext(JdbiThreadLocals.java:27)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$null$1(OnDemandExtensions.java:62)
	at org.jdbi.v3.core.Jdbi.withExtension(Jdbi.java:439)
	at org.jdbi.v3.core.OnDemandExtensions.lambda$create$2(OnDemandExtensions.java:61)
	at com.sun.proxy.$Proxy224.createFunctionNamespacesTableIfNotExists(Unknown Source)
	at com.facebook.presto.functionNamespace.mysql.MySqlFunctionNamespaceManager.initialize(MySqlFunctionNamespaceManager.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.airlift.bootstrap.LifeCycleManager.startInstance(LifeCycleManager.java:240)
	... 20 more
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.facebook.presto.functionNamespace.mysql.MySqlConnectionModule.lambda$setup$0(MySqlConnectionModule.java:41)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:285)
	... 43 more

```

But there is a mysql-connector-java in External Libraires of the project.
![image](https://user-images.githubusercontent.com/29887006/109120852-7279bf00-7781-11eb-9078-c8945c12431b.png)

Any suggestions?

**Comment by lzwang2** [comment]
Below is my solution.

1. add "mysql-connector-java" dependency to presto-main pom.xml
```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
</dependency>
```
2. add "com.mysql.jdbc.Driver" to _SPI_PACKAGES_ in _com.facebook.presto.server.PluginManager_
```
private static final ImmutableList<String> SPI_PACKAGES = ImmutableList.<String>builder()
            .add("com.facebook.presto.spi.")
            .add("com.fasterxml.jackson.annotation.")
            .add("com.fasterxml.jackson.module.afterburner.")
            .add("io.airlift.slice.")
            .add("io.airlift.units.")
            .add("org.openjdk.jol.")
            .add("com.facebook.presto.common")
            .add("com.facebook.drift.annotations.")
            .add("com.facebook.drift.TException")
            .add("com.facebook.drift.TApplicationException")
            .add("com.mysql.jdbc.Driver")
            .build();
```

3. complement jdbc url in function-namespace/example.properties in presto-main
```
function-namespace-manager.name=mysql
database-url=jdbc:mysql://localhost:3306/test?user=root&password=root
function-namespaces-table-name=example_function_namespaces
functions-table-name=example_sql_functions
```

----
Below is the cause of the error.

It's related to classloader.

When `java.sql.DriverManager` is first visited, it will use SPI to load related drivers and store them in `registeredDrivers`.
This SPI loading is implemented by a piece of static code in `java.sql.DriverManager` as below.
```
static {
    loadInitialDrivers();
    println("JDBC DriverManager initialized");
}
```
And following the execution of the code, you will find that the driver class is loaded by `Thread.currentThread().getContextClassLoader()`.(We call this classloader the *initial classloader* here.)

When we try to get a connection using `java.sql.DriverManager.getConnection()`, it will do a check using `isDriverAllowed()`.
It will check if the driver class loaded by the user specified classloader equals to the driver class in the `registeredDrivers` which are loaded by the initial classloader.
If not ,it will return false.

Obviously, if the initial classloader is not the same with the user specified classloader, we will fail to get a connection.

In my situation, DriverManager is first visited when loading mysql catalog.
The call chain is as follows.
1. Set the current thread classloader to ` classloader` in `JdbcConnectorFactory`,i.e. the PluginClassLoader of mysql.
2. use `JdbcConnectorFactory` to create the connector
3. install `MySqlClientModule`, and DriverManager will be used in `new Driver()` in `MySqlClientModule.ensureCatalogIsEmpty()`.

The key point here is the first step. Before DriverManager is visited, the current thread classloader is set to the PluginClassLoader of mysql.
Thus, drivers registered in DriverManager through SPI can only be accessed by mysql plugin.

The solution at the beginning forces all the plugins using AppClassLoader to load mysql drivers. 
Thus, different plugins can share registered drivers in DriverManager.

**Comment by aweisberg** [comment]
Thank you for figuring this out! I will open a PR with your fix.

**Comment by lzwang2** [comment]
Sorry to reply late.

The error doesn't show up in master now.


I'm still trying to figure out the reason.
I'm also reviewing the comment I replyed before, perhaps there are some details that are not that exact.
I will provide more information if I make some progress.




At 2021-10-08 02:30:29, "Rongrong Zhong" ***@***.***> wrote:

The issue should've been fixed in later versions. Let us know if you still see errors in latest version of Presto and we will look into it. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
