### ISSUE TITLE
druid connector querying simple druid setup gives NPEs

### ISSUE THREAD

**Issue by benkrug** [prestodb/presto#15862]
I have a druid 0.20.0 quickstart installation (on a laptop), and installed presto.  I'll attach my presto configuration files.  If I start a client and try to query druid, every attempt errors out with "internal error", and the presto log has an error like the following:

```
2021-03-22T17:45:39.555-0700    DEBUG   Query-20210323_004539_00012_4ykdk-331   com.facebook.presto.execution.QueryStateMachine Query 20210323_004539_00012_4ykdk failed
java.lang.NullPointerException
        at com.google.common.base.CharMatcher.matchesAllOf(CharMatcher.java:507)
        at com.facebook.airlift.http.client.HttpUriBuilder.percentDecode(HttpUriBuilder.java:283)
        at com.facebook.airlift.http.client.HttpUriBuilder.<init>(HttpUriBuilder.java:58)
        at com.facebook.airlift.http.client.HttpUriBuilder.uriBuilderFrom(HttpUriBuilder.java:71)
        at com.facebook.presto.druid.DruidClient.prepareMetadataQuery(DruidClient.java:158)
        at com.facebook.presto.druid.DruidClient.getTables(DruidClient.java:105)
        at com.facebook.presto.druid.DruidMetadata.listTables(DruidMetadata.java:109)
        at com.facebook.presto.metadata.MetadataManager.listTables(MetadataManager.java:570)
        at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.lambda$calculatePrefixesWithTableName$7(InformationSchemaMetadata.java:304)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.calculatePrefixesWithTableName(InformationSchemaMetadata.java:308)
        at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.getTableLayouts(InformationSchemaMetadata.java:242)
        at com.facebook.presto.metadata.MetadataManager.getLayout(MetadataManager.java:397)
        at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.pushPredicateIntoTableScan(PickTableLayout.java:305)
        at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout.pushPredicateIntoTableScan(PickTableLayout.java:250)
        at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutForPredicate.apply(PickTableLayout.java:137)
        at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutForPredicate.apply(PickTableLayout.java:102)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:168)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:141)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:106)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:188)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:188)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:188)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:108)
        at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:95)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:188)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:177)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:406)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:392)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:342)
        at com.facebook.presto.$gen.Presto_0_248_0b0ce2f____20210323_003719_1.run(Unknown Source)
        at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:254)
        at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$5(LocalDispatchQuery.java:114)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
I confirmed that I can query druid directly over http using port 8082, as configured for druid, but nothing works through presto.  It's a very simple setup.  Am I doing something wrong in my configuration?

[config.files.gz](https://github.com/prestodb/presto/files/6186120/config.files.gz)
[logs.tar.gz](https://github.com/prestodb/presto/files/6186121/logs.tar.gz)

**Comment by benkrug** [comment]
This was resolved by replacing localhost:8081, localhost:8082 in druid catalog config, with http://127.0.0.1:8081, http://127.0.0.1:8082.  (Thanks Asif Kazi on Presto Slack!)

**Comment by 1ambda** [comment]
Was able to solve the same issue. Thanks! @benkrug
