### ISSUE TITLE
java.lang.NoClassDefFoundError: org/spark_project/guava/base/Preconditions with Presto 0.252-SNASPHOT

### ISSUE THREAD

**Issue by rguillome** [prestodb/presto#15971]
While executing a query with the last Presto-spark, i add this exception : 
```
21/04/19 20:26:45 INFO DAGScheduler: ShuffleMapStage 1 (ZippedPartitionsBaseRDD at PrestoSparkTaskRdd.java:92) failed in 19.591 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 6, ip-10-97-145-190.eu-west-3.compute.internal, executor 1): java.lang.NoClassDefFoundError: org/spark_project/guava/base/Preconditions
	at com.facebook.presto.spark.classloader_interface.PrestoSparkMutableRow.getSize(PrestoSparkMutableRow.java:131)
	at com.facebook.presto.spark.execution.PrestoSparkTaskExecutorFactory$PrestoSparkTaskExecutor.doComputeNext(PrestoSparkTaskExecutorFactory.java:686)
	at com.facebook.presto.spark.execution.PrestoSparkTaskExecutorFactory$PrestoSparkTaskExecutor.computeNext(PrestoSparkTaskExecutorFactory.java:663)
	at com.facebook.presto.spark.execution.PrestoSparkTaskExecutorFactory$PrestoSparkTaskExecutor.hasNext(PrestoSparkTaskExecutorFactory.java:641)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:133)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

After analysing, I think `spark-core.jar` should be included in the `presto-spark-package`.

I will propose a PR to fix this

**Comment by viczhang861** [comment]
Fixed by https://github.com/prestodb/presto/pull/16186
