### ISSUE TITLE
Alluxio cache RejectedExecutionException

### ISSUE THREAD

**Issue by highker** [prestodb/presto#15972]
High get and put errors
<img width="1624" alt="Screen Shot 2021-04-20 at 11 47 13 AM" src="https://user-images.githubusercontent.com/2192913/115449039-35550a80-a1cf-11eb-973b-199371309987.png">

Companied with high IOPS
<img width="1613" alt="Screen Shot 2021-04-20 at 11 48 42 AM" src="https://user-images.githubusercontent.com/2192913/115449084-400f9f80-a1cf-11eb-9ad0-872534395ebd.png">

get error stack trace
```
2021-04-20T11:41:24.214-0700    ERROR   20210420_183317_13961_36e3s.3.0.276-30-28526    alluxio.client.file.cache.LocalCacheManager     Failed to get existing page PageId{FileId=bca1447c5c90c8fd73cf8
abcbc41d378, PageIndex=246}: {}
java.io.IOException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@d45be6b[Not completed, task = alluxio.client.file.cache.TimeBoundPageStore$$Lambda$5005/0x00
007faf35537558@a3d61df] rejected from java.util.concurrent.ThreadPoolExecutor@5e063a9d[Running, pool size = 64, active threads = 63, queued tasks = 0, completed tasks = 34202996]
        at alluxio.client.file.cache.TimeBoundPageStore.get(TimeBoundPageStore.java:94)
        at alluxio.client.file.cache.LocalCacheManager.getPage(LocalCacheManager.java:610)
        at alluxio.client.file.cache.LocalCacheManager.get(LocalCacheManager.java:450)
        at alluxio.client.file.cache.NoExceptionCacheManager.get(NoExceptionCacheManager.java:75)
        at alluxio.client.file.cache.LocalCacheFileInStream.positionedRead(LocalCacheFileInStream.java:208)
        at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:139)
        at alluxio.hadoop.HdfsFileInputStream.readFully(HdfsFileInputStream.java:156)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
        at com.facebook.presto.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:64)
        at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:105)
        at com.facebook.presto.orc.AbstractOrcDataSource$ChunkedSliceLoader.load(AbstractOrcDataSource.java:292)
        at com.facebook.presto.orc.AbstractOrcDataSource$ChunkedSliceLoader.load(AbstractOrcDataSource.java:266)
        at io.airlift.slice.ChunkedSliceInput$InternalLoader.load(ChunkedSliceInput.java:383)
        at io.airlift.slice.ChunkedSliceInput.ensureAvailable(ChunkedSliceInput.java:111)
        at io.airlift.slice.ChunkedSliceInput.read(ChunkedSliceInput.java:126)
        at io.airlift.slice.ChunkedSliceInput.readByte(ChunkedSliceInput.java:135)
        at io.airlift.slice.ChunkedSliceInput.readUnsignedByte(ChunkedSliceInput.java:145)
        at com.facebook.presto.orc.LazySliceInput.readUnsignedByte(LazySliceInput.java:126)
        at com.facebook.presto.orc.stream.OrcInputStream.advance(OrcInputStream.java:466)
        at com.facebook.presto.orc.stream.OrcInputStream.seekToCheckpoint(OrcInputStream.java:237)
        at com.facebook.presto.orc.stream.LongInputStreamDwrf.seekToCheckpoint(LongInputStreamDwrf.java:49)
        at com.facebook.presto.orc.stream.LongInputStreamDwrf.seekToCheckpoint(LongInputStreamDwrf.java:22)
        at com.facebook.presto.orc.stream.CheckpointInputStreamSource.openStream(CheckpointInputStreamSource.java:57)
        at com.facebook.presto.orc.reader.LongDirectSelectiveStreamReader.openRowGroup(LongDirectSelectiveStreamReader.java:308)
        at com.facebook.presto.orc.reader.LongDirectSelectiveStreamReader.read(LongDirectSelectiveStreamReader.java:95)
        at com.facebook.presto.orc.reader.LongSelectiveStreamReader.read(LongSelectiveStreamReader.java:116)
        at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:672)
        at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:86)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:276)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:241)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:418)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:294)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
        at com.facebook.presto.$gen.Presto_0_250_$_git_commit_id_abbrev_____20210419_070440_1.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@d45be6b[Not completed, task = alluxio.client.file.cache.TimeBoundPageStore$$Lambda$5005/0x00007faf3553
7558@a3d61df] rejected from java.util.concurrent.ThreadPoolExecutor@5e063a9d[Running, pool size = 64, active threads = 63, queued tasks = 0, completed tasks = 34202996]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at alluxio.shaded.client.com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:152)
        at alluxio.client.file.cache.TimeBoundPageStore.get(TimeBoundPageStore.java:85)
        ... 40 more
```

put error stack trace
```
2021-04-20T11:41:24.210-0700    ERROR   20210420_183552_13993_36e3s.2.0.276-25-212      alluxio.client.file.cache.LocalCacheManager     Failed to add page PageId{FileId=f76eea3380a91b100c21dd23934db1
04, PageIndex=0}: {}
java.io.IOException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6c7e16b0[Not completed, task = alluxio.client.file.cache.TimeBoundPageStore$$Lambda$5244/0x0
0007faf365b24a8@368ecdaa] rejected from java.util.concurrent.ThreadPoolExecutor@5e063a9d[Running, pool size = 64, active threads = 64, queued tasks = 0, completed tasks = 34202989]
        at alluxio.client.file.cache.TimeBoundPageStore.put(TimeBoundPageStore.java:72)
        at alluxio.client.file.cache.LocalCacheManager.putAttempt(LocalCacheManager.java:348)
        at alluxio.client.file.cache.LocalCacheManager.putInternal(LocalCacheManager.java:292)
        at alluxio.client.file.cache.LocalCacheManager.put(LocalCacheManager.java:254)
        at alluxio.client.file.cache.NoExceptionCacheManager.put(NoExceptionCacheManager.java:52)
        at alluxio.client.file.cache.LocalCacheFileInStream.positionedRead(LocalCacheFileInStream.java:222)
        at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:139)
        at alluxio.hadoop.HdfsFileInputStream.readFully(HdfsFileInputStream.java:156)
        at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
        at com.facebook.presto.hive.orc.HdfsOrcDataSource.readInternal(HdfsOrcDataSource.java:64)
        at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:105)
        at com.facebook.presto.orc.AbstractOrcDataSource.readFully(AbstractOrcDataSource.java:96)
        at com.facebook.presto.orc.AbstractOrcDataSource$LazyBufferLoader.load(AbstractOrcDataSource.java:237)
        at com.facebook.presto.orc.AbstractOrcDataSource$LazyBufferLoader.loadNestedDiskRangeBuffer(AbstractOrcDataSource.java:223)
        at com.facebook.presto.orc.AbstractOrcDataSource$LazyMergedSliceLoader.get(AbstractOrcDataSource.java:261)
        at com.facebook.presto.orc.AbstractOrcDataSource$LazyMergedSliceLoader.get(AbstractOrcDataSource.java:246)
        at com.facebook.presto.orc.LazySliceInput.getDelegate(LazySliceInput.java:52)
        at com.facebook.presto.orc.LazySliceInput.readUnsignedByte(LazySliceInput.java:126)
        at com.facebook.presto.orc.stream.OrcInputStream.advance(OrcInputStream.java:466)
        at com.facebook.presto.orc.stream.OrcInputStream.read(OrcInputStream.java:160)
        at com.facebook.presto.orc.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2715)
        at com.facebook.presto.orc.protobuf.CodedInputStream$StreamDecoder.isAtEnd(CodedInputStream.java:2654)
        at com.facebook.presto.orc.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2004)
        at com.facebook.presto.orc.proto.DwrfProto$RowIndex.<init>(DwrfProto.java:6016)
        at com.facebook.presto.orc.proto.DwrfProto$RowIndex.<init>(DwrfProto.java:5988)
        at com.facebook.presto.orc.proto.DwrfProto$RowIndex$1.parsePartialFrom(DwrfProto.java:6681)
        at com.facebook.presto.orc.proto.DwrfProto$RowIndex$1.parsePartialFrom(DwrfProto.java:6676)
        at com.facebook.presto.orc.protobuf.AbstractParser.parseFrom(AbstractParser.java:91)
        at com.facebook.presto.orc.protobuf.AbstractParser.parseFrom(AbstractParser.java:96)
        at com.facebook.presto.orc.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
        at com.facebook.presto.orc.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
        at com.facebook.presto.orc.proto.DwrfProto$RowIndex.parseFrom(DwrfProto.java:6214)
        at com.facebook.presto.orc.metadata.DwrfMetadataReader.readRowIndexes(DwrfMetadataReader.java:381)
        at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.readRowIndexes(ExceptionWrappingMetadataReader.java:104)
        at com.facebook.presto.orc.StripeReader.readColumnIndexes(StripeReader.java:521)
        at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:190)
        at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextStripe(AbstractOrcRecordReader.java:658)
        at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextRowGroup(AbstractOrcRecordReader.java:542)
        at com.facebook.presto.orc.AbstractOrcRecordReader.prepareNextBatch(AbstractOrcRecordReader.java:597)
        at com.facebook.presto.orc.OrcSelectiveRecordReader.getNextPage(OrcSelectiveRecordReader.java:625)
        at com.facebook.presto.hive.orc.OrcSelectivePageSource.getNextPage(OrcSelectivePageSource.java:86)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:276)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:241)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:418)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:294)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
        at com.facebook.presto.$gen.Presto_0_250_$_git_commit_id_abbrev_____20210419_070440_1.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@6c7e16b0[Not completed, task = alluxio.client.file.cache.TimeBoundPageStore$$Lambda$5244/0x00007faf365
b24a8@368ecdaa] rejected from java.util.concurrent.ThreadPoolExecutor@5e063a9d[Running, pool size = 64, active threads = 64, queued tasks = 0, completed tasks = 34202989]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at alluxio.shaded.client.com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:152)
        at alluxio.client.file.cache.TimeBoundPageStore.put(TimeBoundPageStore.java:63)
        ... 53 more
```

Enough space on disk
```
/dev/md1p1              930G  909G   22G  98% /mnt/flash
```

**Comment by apc999** [comment]
after investigation, this issue is related writing data to a full disk, where the cache "thinks" the disk is not full due to underestimating the file system overhead

This issue will be addressed by
https://github.com/Alluxio/alluxio/pull/13126
where we

1. add a metrics to monitor and report when no space left on device happens
1. force evicting items in a retry in this case
1. add a new flag `alluxio.user.client.cache.store.overhead` (this will have a different name in Presto) to allow users to specify the space overhead when writing data to certain disks
