### ISSUE TITLE
EmptySplit cannot be cast to HiveSplit

### ISSUE THREAD

**Issue by jainxrohit** [prestodb/presto#15982]
ava.lang.ClassCastException: class com.facebook.presto.split.EmptySplit cannot be cast to class com.facebook.presto.hive.HiveSplit (com.facebook.presto.split.EmptySplit is in unnamed module of loader 'app'; com.facebook.presto.hive.HiveSplit is in unnamed module of loader com.facebook.presto.server.PluginClassLoader @1dc9e4d2)
	at com.facebook.presto.hive.HiveTableLayoutHandle.getIdentifier(HiveTableLayoutHandle.java:252)
	at com.facebook.presto.sql.planner.CanonicalPlanFragment$RuntimeInformationRewriter.lambda$visitCanonicalTableScan$0(CanonicalPlanFragment.java:104)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.facebook.presto.sql.planner.CanonicalPlanFragment$RuntimeInformationRewriter.visitCanonicalTableScan(CanonicalPlanFragment.java:104)
	at com.facebook.presto.sql.planner.CanonicalPlanFragment$RuntimeInformationRewriter.visitCanonicalTableScan(CanonicalPlanFragment.java:90)
	at com.facebook.presto.sql.planner.CanonicalTableScanNode.accept(CanonicalTableScanNode.java:97)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4747)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4755)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
	at com.facebook.presto.spi.plan.PlanVisitor.visitAggregation(PlanVisitor.java:25)
	at com.facebook.presto.spi.plan.AggregationNode.accept(AggregationNode.java:199)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:29)
	at com.facebook.presto.sql.planner.CanonicalPlanFragment.updateRuntimeInformation(CanonicalPlanFragment.java:87)
	at com.facebook.presto.execution.FragmentResultCacheContext.updateRuntimeInformation(FragmentResultCacheContext.java:130)
	at com.facebook.presto.operator.Driver.lambda$processNewSources$7(Driver.java:263)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.facebook.presto.operator.Driver.processNewSources(Driver.java:263)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:727)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:706)
	at com.facebook.presto.operator.Driver.updateSource(Driver.java:227)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:951)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1071)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_252_SNAPSHOT_$_git_commit_id_abbrev___0_252_20210416_204430_71____20210419_215834_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by elharo** [comment]
fixed by #15991
