### ISSUE TITLE
After setting hive.force-local-scheduling the program runs  abnormal

### ISSUE THREAD

**Issue by wmtbnbo** [prestodb/presto#16008]
when i set hive.force-local-scheduling=true in `/catalog/hive.prperties` the program start exception
**version**:
```
Hadoop : 3.0.0+cdh6.2.1
Hive : 2.1.1+cdh6.2.1
Allxio : alluxio-2.3.0
presto : 2.3.0
```
**Exception info:**
```
2021-04-27T09:34:14.206+0800	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Configuration property 'hive.force-local-scheduling' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'hive.force-local-scheduling' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:136)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:379)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:231)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:223)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:209)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:138)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:79)


2021-04-27T09:34:14.208+0800	INFO	Thread-47	com.facebook.airlift.bootstrap.LifeCycleManager	Life cycle stopping...
```
I'm not sure if it's a version compatibility exception,Is there anyone who can help me answer my doubts? thanks.

**Comment by v-jizhang** [comment]
I've reproduced it. Pretty sure it's a bug.

**Comment by imjalpreet** [comment]
@wmtbnbo Can you let us know which version of Presto are you using? You mentioned 2.3.0 I think that's a typo. 

Also, the configuration property **hive.force-local-scheduling** was removed in Presto 0.233 (https://prestodb.io/docs/current/release/release-0.233.html#hive-changes). As mentioned in the release note, you can set **hive.node-selection-strategy=HARD_AFFINITY** to get the same functionality.

**Comment by wmtbnbo** [comment]
> @wmtbnbo Can you let us know which version of Presto are you using? You mentioned 2.3.0 I think that's a typo.
> 
> Also, the configuration property **hive.force-local-scheduling** was removed in Presto 0.233 (https://prestodb.io/docs/current/release/release-0.233.html#hive-changes). As mentioned in the release note, you can set **hive.node-selection-strategy=HARD_AFFINITY** to get the same functionality.

I'm sorry to leave the wrong version number. I'm sure the real version is Presto 0.235，Thank you for your reply, I will test again
 about **hive.node-selection-strategy=HARD_AFFINITY**

**Comment by wmtbnbo** [comment]
I'm sure it's caused by the version,The correct setting is hive.node-selection-strategy=HARD_AFFINITY
