### ISSUE TITLE
select * from a Hudi Mor table failed: "Can not read value at 0 in block -1 in file "

### ISSUE THREAD

**Issue by qfrtrt** [prestodb/presto#16092]
version: 0.252
SQL: `select * from schema_as__job_status_rt order by updated_at desc;`
Error: 
```
Query 20210513_110531_00005_bbfiq failed: Can not read value at 0 in block -1 in file hdfs://ns1/hudi/schema_as.job_status.mor/605759be-0f9e-4445-8471-29b96263194b-0_0-3-3_20210513114938.parquet
org.apache.parquet.io.ParquetDecodingException: Can not read value at 0 in block -1 in file hdfs://ns1/hudi/schema_as.job_status.mor/605759be-0f9e-4445-8471-29b96263194b-0_0-3-3_20210513114938.parquet
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:251)
	at org.apache.parquet.hadoop.ParquetRecordReader.nextKeyValue(ParquetRecordReader.java:207)
	at org.apache.hadoop.hive.ql.io.parquet.read.ParquetRecordReaderWrapper.<init>(ParquetRecordReaderWrapper.java:98)
	at org.apache.hadoop.hive.ql.io.parquet.read.ParquetRecordReaderWrapper.<init>(ParquetRecordReaderWrapper.java:60)
	at org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat.getRecordReader(MapredParquetInputFormat.java:92)
	at org.apache.hudi.hadoop.HoodieParquetInputFormat.getRecordReader(HoodieParquetInputFormat.java:297)
	at org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat.getRecordReader(HoodieParquetRealtimeInputFormat.java:253)
	at com.facebook.presto.hive.HiveUtil.createRecordReader(HiveUtil.java:257)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$0(GenericHiveRecordCursorProvider.java:74)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:73)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:456)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:184)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:418)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:294)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_252_$_git_commit_id_abbrev_____20210513_110522_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: readDirect unsupported in RemoteBlockReader
	at org.apache.hadoop.hdfs.RemoteBlockReader.read(RemoteBlockReader.java:492)
	at org.apache.hadoop.hdfs.DFSInputStream$ByteBufferStrategy.doRead(DFSInputStream.java:789)
	at org.apache.hadoop.hdfs.DFSInputStream.readBuffer(DFSInputStream.java:823)
	at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:883)
	at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:938)
	at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:143)
	at org.apache.parquet.hadoop.util.H2SeekableInputStream$H2Reader.read(H2SeekableInputStream.java:81)
	at org.apache.parquet.hadoop.util.H2SeekableInputStream.readFully(H2SeekableInputStream.java:90)
	at org.apache.parquet.hadoop.util.H2SeekableInputStream.readFully(H2SeekableInputStream.java:75)
	at org.apache.parquet.hadoop.ParquetFileReader$ConsecutiveChunkList.readAll(ParquetFileReader.java:1174)
	at org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:805)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:127)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:222)
	... 27 more
```

**Comment by rohanpednekar** [comment]
@bhasudha Do you think you can help here? Thanks!

**Comment by qfrtrt** [comment]
Solve this problem by adding a property in "hdfs.xml":
```
  <property>
    <name>dfs.client.use.legacy.blockreader</name>
    <value>false</value>
  </property>
```

**Comment by ClareGuoBin** [comment]
I met the same problem, could you tell me what is your hadoop version? I have changed the configuration as you said, but it still does't make sense @qfrtrt

**Comment by qfrtrt** [comment]
My version is "Hadoop 2.7.3.2.6.5.0-292". Hoping This Helps

**Comment by ClareGuoBin** [comment]
Thanks, my version is 3.0.0-cdh6.3.2, i try other ways. @qfrtrt

**Comment by xsy-coder** [comment]
> 
what is hdfs.xml directory? Link to hive.config.resources?

**Comment by Mr-heb** [comment]
hi , I've also met the same problem , my version is 3.0.0-cdh6.3.2 too, Is it resolved or not @ClareGuoBin
