### ISSUE TITLE
Flaky test TestQueues.testQueuedQueryInteraction

### ISSUE THREAD

**Issue by viczhang861** [prestodb/presto#16126]
Failed test
https://github.com/prestodb/presto/pull/16121/checks?check_run_id=2623286824

org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.TestQueues.testQueuedQueryInteraction() didn't finish within the time-out 240000

**Comment by rschlussel** [comment]
@swapsmagic I'm seeing this issue again: https://github.com/prestodb/presto/actions/runs/3567753776/jobs/5995821172
```
Error:  com.facebook.presto.execution.TestQueues.testQueuedQueryInteraction  Time elapsed: 60.009 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.TestQueues.testQueuedQueryInteraction() didn't finish within the time-out 60000
	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:347)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
