### ISSUE TITLE
Failed to read footer of file in TestIcebergDistributed

### ISSUE THREAD

**Issue by viczhang861** [prestodb/presto#16206]
Possible flaky test https://github.com/prestodb/presto/pull/16187/checks?check_run_id=2740454770, it may be transient transportation error. Mark it in this issue for reference.

Error:  Tests run: 439, Failures: 1, Errors: 0, Skipped: 438, Time elapsed: 31.496 s <<< FAILURE! - in com.facebook.presto.iceberg.TestIcebergDistributed
Error:  init(com.facebook.presto.iceberg.TestIcebergDistributed)  Time elapsed: 29.845 s  <<< FAILURE!
java.lang.RuntimeException: Failed to read footer of file: com.facebook.presto.iceberg.HdfsInputFile@5112ab6
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:551)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:519)
	at com.facebook.presto.tests.QueryAssertions.copyTable(QueryAssertions.java:365)
	at com.facebook.presto.tests.QueryAssertions.copyTable(QueryAssertions.java:357)
	at com.facebook.presto.tests.QueryAssertions.copyTpchTables(QueryAssertions.java:349)
	at com.facebook.presto.tests.QueryAssertions.copyTpchTables(QueryAssertions.java:335)
	at com.facebook.presto.iceberg.IcebergQueryRunner.createIcebergQueryRunner(IcebergQueryRunner.java:83)
	at com.facebook.presto.iceberg.IcebergQueryRunner.createIcebergQueryRunner(IcebergQueryRunner.java:44)
	at com.facebook.presto.iceberg.TestIcebergDistributed.createQueryRunner(TestIcebergDistributed.java:34)
	at com.facebook.presto.tests.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.iceberg.exceptions.RuntimeIOException: Failed to read footer of file: com.facebook.presto.iceberg.HdfsInputFile@5112ab6
	at org.apache.iceberg.parquet.ParquetUtil.fileMetrics(ParquetUtil.java:76)
	at com.facebook.presto.iceberg.IcebergParquetFileWriter.lambda$getMetrics$0(IcebergParquetFileWriter.java:72)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.iceberg.IcebergParquetFileWriter.getMetrics(IcebergParquetFileWriter.java:72)
	at com.facebook.presto.iceberg.IcebergPageSink.finish(IcebergPageSink.java:161)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:74)
	at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:275)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:441)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:294)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
	at com.facebook.presto.$gen.Presto_0_255_SNAPSHOT_6c83431__testversion____20210603_202135_1.run(Unknown Source)
	... 3 more
Caused by: java.io.IOException: can not read class org.apache.parquet.format.FileMetaData: java.io.IOException: Stream is closed!
	at org.apache.parquet.format.Util.read(Util.java:225)
	at org.apache.parquet.format.Util.readFileMetaData(Util.java:86)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$2.visit(ParquetMetadataConverter.java:866)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$2.visit(ParquetMetadataConverter.java:863)
	at org.apache.parquet.format.converter.ParquetMetadataConverter$NoFilter.accept(ParquetMetadataConverter.java:746)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:863)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:532)
	at org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:689)
	at org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:583)
	at org.apache.iceberg.parquet.ParquetUtil.fileMetrics(ParquetUtil.java:73)
	... 18 more
Caused by: shaded.parquet.org.apache.thrift.transport.TTransportException: java.io.IOException: Stream is closed!
	at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
	at shaded.parquet.org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:637)
	at shaded.parquet.org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:543)
	at org.apache.parquet.format.InterningProtocol.readFieldBegin(InterningProtocol.java:155)
	at org.apache.parquet.format.ColumnMetaData$ColumnMetaDataStandardScheme.read(ColumnMetaData.java:1630)
	at org.apache.parquet.format.ColumnMetaData$ColumnMetaDataStandardScheme.read(ColumnMetaData.java:1623)
	at org.apache.parquet.format.ColumnMetaData.read(ColumnMetaData.java:1464)
	at org.apache.parquet.format.ColumnChunk$ColumnChunkStandardScheme.read(ColumnChunk.java:1101)
	at org.apache.parquet.format.ColumnChunk$ColumnChunkStandardScheme.read(ColumnChunk.java:1070)
	at org.apache.parquet.format.ColumnChunk.read(ColumnChunk.java:954)
	at org.apache.parquet.format.RowGroup$RowGroupStandardScheme.read(RowGroup.java:932)
	at org.apache.parquet.format.RowGroup$RowGroupStandardScheme.read(RowGroup.java:911)
	at org.apache.parquet.format.RowGroup.read(RowGroup.java:818)
	at org.apache.parquet.format.FileMetaData$FileMetaDataStandardScheme.read(FileMetaData.java:1298)
	at org.apache.parquet.format.FileMetaData$FileMetaDataStandardScheme.read(FileMetaData.java:1242)
	at org.apache.parquet.format.FileMetaData.read(FileMetaData.java:1116)
	at org.apache.parquet.format.Util.read(Util.java:222)
	... 27 more
Caused by: java.io.IOException: Stream is closed!
	at org.apache.hadoop.fs.BufferedFSInputStream.getPos(BufferedFSInputStream.java:56)
	at org.apache.hadoop.fs.FSDataInputStream.getPos(FSDataInputStream.java:72)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.readChunk(ChecksumFileSystem.java:254)
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:276)
	at org.apache.hadoop.fs.FSInputChecker.fill(FSInputChecker.java:214)
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:232)
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:196)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at org.apache.parquet.io.DelegatingSeekableInputStream.read(DelegatingSeekableInputStream.java:66)
	at shaded.parquet.org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
	... 44 more

**Comment by ChunxuTang** [comment]
Hi @viczhang861, thanks for pointing it out!
I found that I couldn't reproduce this issue in my local environment. Do you have any suggestions to fix the issue?

@beinan @zhenxiao As we're working on improving code test coverage by adding more tests (e.g. https://github.com/prestodb/presto/pull/16219), do you have any ideas of how to resolve this issue?

**Comment by viczhang861** [comment]
@ChunxuTang I think this is transient transportation error. I created this issue for the purpose of tracking in case it happens again.

**Comment by ChunxuTang** [comment]
@viczhang861 Thanks for your clarification! If the issue takes place repeatedly in the future, feel free to let us know if there's anything we can help with ~
