### ISSUE TITLE
Run Presto-0.254  in IDEA throws "com.google.inject.CreationException: Unable to create injector, see the following errors:" 

### ISSUE THREAD

**Issue by longzhixin** [prestodb/presto#16447]
`system info` :  `Linux robot-VirtualBox 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
`jdk` : 
``` 
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
````

`maven`: 
```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

`presto` : 0.254, 0.257, master .....

`idea` :  2021.1.3
`parameters`:
```
-ea -XX:+UseG1GC -XX:G1HeapRegionSize=32M -XX:+UseGCOverheadLimit -XX:+ExplicitGCInvokesConcurrent -Xmx2G -Dconfig=etc/config.properties -Dlog.levels-file=etc/log.properties
```
at the same time. I switch the jdk11, I running success one trino project.

ERROR INFO
```
21-07-20T17:35:29.026+0800	INFO	main	Bootstrap	use-legacy-scheduler                                                  true                                                                       true                                                                       Use the version of the scheduler before refactorings for section retries
2021-07-20T17:35:29.026+0800	INFO	main	Bootstrap	optimizer.use-mark-distinct                                           true                                                                       true
2021-07-20T17:35:29.026+0800	INFO	main	Bootstrap	warn-on-no-table-layout-filter
2021-07-20T17:35:29.026+0800	INFO	main	Bootstrap	writer-min-size                                                       32MB                                                                       32MB                                                                       Target minimum size of writer output when scaling writers
2021-07-20T17:35:29.325+0800	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Explicit bindings are required and com.facebook.presto.common.block.BlockEncodingSerde is not explicitly bound.
  while locating com.facebook.presto.common.block.BlockEncodingSerde
    for the 2nd parameter of com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)
  at com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)

2) Explicit bindings are required and com.facebook.presto.execution.QueryManager is not explicitly bound.
  while locating com.facebook.presto.execution.QueryManager
    for the 5th parameter of com.facebook.presto.server.GracefulShutdownHandler.<init>(GracefulShutdownHandler.java:68)
  at com.facebook.presto.server.GracefulShutdownModule.setup(GracefulShutdownModule.java:27)

3) Explicit bindings are required and com.facebook.presto.execution.TaskManager is not explicitly bound.
  while locating com.facebook.presto.execution.TaskManager
    for the 1st parameter of com.facebook.presto.server.GracefulShutdownHandler.<init>(GracefulShutdownHandler.java:68)
  at com.facebook.presto.server.GracefulShutdownModule.setup(GracefulShutdownModule.java:27)

4) Explicit bindings are required and com.facebook.presto.execution.TaskManagerConfig is not explicitly bound.
  while locating com.facebook.presto.execution.TaskManagerConfig
    for the 2nd parameter of com.facebook.presto.server.ServerMainModule.createAsyncHttpResponseExecutor(ServerMainModule.java:674)
  at com.facebook.presto.server.ServerMainModule.createAsyncHttpResponseExecutor(ServerMainModule.java:674)

5) Explicit bindings are required and com.facebook.presto.execution.TaskManagerConfig is not explicitly bound.
  while locating com.facebook.presto.execution.TaskManagerConfig
    for the 1st parameter of com.facebook.presto.server.ServerMainModule.createAsyncHttpTimeoutExecutor(ServerMainModule.java:682)
  at com.facebook.presto.server.ServerMainModule.createAsyncHttpTimeoutExecutor(ServerMainModule.java:682)

6) Explicit bindings are required and com.facebook.presto.metadata.InternalNodeManager is not explicitly bound.
  while locating com.facebook.presto.metadata.InternalNodeManager
    for the 1st parameter of com.facebook.presto.storage.TempStorageManager.<init>(TempStorageManager.java:64)
  at com.facebook.presto.storage.TempStorageModule.configure(TempStorageModule.java:27)

7) Explicit bindings are required and com.facebook.presto.operator.ExchangeClientConfig is not explicitly bound.
  while locating com.facebook.presto.operator.ExchangeClientConfig
    for the 1st parameter of com.facebook.presto.server.ServerMainModule.createExchangeExecutor(ServerMainModule.java:658)
  at com.facebook.presto.server.ServerMainModule.createExchangeExecutor(ServerMainModule.java:658)

8) Explicit bindings are required and com.facebook.presto.operator.FileFragmentResultCacheConfig is not explicitly bound.
  while locating com.facebook.presto.operator.FileFragmentResultCacheConfig
    for the 1st parameter of com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)
  at com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)

9) Explicit bindings are required and com.facebook.presto.operator.FragmentCacheStats is not explicitly bound.
  while locating com.facebook.presto.operator.FragmentCacheStats
    for the 3rd parameter of com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)
  at com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)

10) Explicit bindings are required and com.facebook.presto.transaction.TransactionManager is not explicitly bound.
  while locating com.facebook.presto.transaction.TransactionManager
    for the 1st parameter of com.facebook.presto.security.AccessControlManager.<init>(AccessControlManager.java:82)
  at com.facebook.presto.security.AccessControlModule.configure(AccessControlModule.java:28)

11) Error: Invalid configuration property presto.version: presto.version must be provided when it cannot be automatically determined (for class com.facebook.presto.server.ServerConfig.prestoVersion)

12) Error: Invalid configuration property node.environment: may not be null (for class com.facebook.airlift.node.NodeConfig.environment)

12 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and com.facebook.presto.common.block.BlockEncodingSerde is not explicitly bound.
  while locating com.facebook.presto.common.block.BlockEncodingSerde
    for the 2nd parameter of com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)
  at com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)

2) Explicit bindings are required and com.facebook.presto.execution.QueryManager is not explicitly bound.
  while locating com.facebook.presto.execution.QueryManager
    for the 5th parameter of com.facebook.presto.server.GracefulShutdownHandler.<init>(GracefulShutdownHandler.java:68)
  at com.facebook.presto.server.GracefulShutdownModule.setup(GracefulShutdownModule.java:27)

3) Explicit bindings are required and com.facebook.presto.execution.TaskManager is not explicitly bound.
  while locating com.facebook.presto.execution.TaskManager
    for the 1st parameter of com.facebook.presto.server.GracefulShutdownHandler.<init>(GracefulShutdownHandler.java:68)
  at com.facebook.presto.server.GracefulShutdownModule.setup(GracefulShutdownModule.java:27)

4) Explicit bindings are required and com.facebook.presto.execution.TaskManagerConfig is not explicitly bound.
  while locating com.facebook.presto.execution.TaskManagerConfig
    for the 2nd parameter of com.facebook.presto.server.ServerMainModule.createAsyncHttpResponseExecutor(ServerMainModule.java:674)
  at com.facebook.presto.server.ServerMainModule.createAsyncHttpResponseExecutor(ServerMainModule.java:674)

5) Explicit bindings are required and com.facebook.presto.execution.TaskManagerConfig is not explicitly bound.
  while locating com.facebook.presto.execution.TaskManagerConfig
    for the 1st parameter of com.facebook.presto.server.ServerMainModule.createAsyncHttpTimeoutExecutor(ServerMainModule.java:682)
  at com.facebook.presto.server.ServerMainModule.createAsyncHttpTimeoutExecutor(ServerMainModule.java:682)

6) Explicit bindings are required and com.facebook.presto.metadata.InternalNodeManager is not explicitly bound.
  while locating com.facebook.presto.metadata.InternalNodeManager
    for the 1st parameter of com.facebook.presto.storage.TempStorageManager.<init>(TempStorageManager.java:64)
  at com.facebook.presto.storage.TempStorageModule.configure(TempStorageModule.java:27)

7) Explicit bindings are required and com.facebook.presto.operator.ExchangeClientConfig is not explicitly bound.
  while locating com.facebook.presto.operator.ExchangeClientConfig
    for the 1st parameter of com.facebook.presto.server.ServerMainModule.createExchangeExecutor(ServerMainModule.java:658)
  at com.facebook.presto.server.ServerMainModule.createExchangeExecutor(ServerMainModule.java:658)

8) Explicit bindings are required and com.facebook.presto.operator.FileFragmentResultCacheConfig is not explicitly bound.
  while locating com.facebook.presto.operator.FileFragmentResultCacheConfig
    for the 1st parameter of com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)
  at com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)

9) Explicit bindings are required and com.facebook.presto.operator.FragmentCacheStats is not explicitly bound.
  while locating com.facebook.presto.operator.FragmentCacheStats
    for the 3rd parameter of com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)
  at com.facebook.presto.server.ServerMainModule.createFragmentResultCacheManager(ServerMainModule.java:689)

10) Explicit bindings are required and com.facebook.presto.transaction.TransactionManager is not explicitly bound.
  while locating com.facebook.presto.transaction.TransactionManager
    for the 1st parameter of com.facebook.presto.security.AccessControlManager.<init>(AccessControlManager.java:82)
  at com.facebook.presto.security.AccessControlModule.configure(AccessControlModule.java:28)

11) Error: Invalid configuration property presto.version: presto.version must be provided when it cannot be automatically determined (for class com.facebook.presto.server.ServerConfig.prestoVersion)

12) Error: Invalid configuration property node.environment: may not be null (for class com.facebook.airlift.node.NodeConfig.environment)

12 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:137)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:81)
````

**Comment by abcwt112** [comment]
一模一样,请问大哥这个问题解决了吗?

**Comment by ellison840611** [comment]
Because when you configure the run/debug configurations, the configuration information that should be filled in the VM Options is incorrectly filled in the Program arguments.
