### ISSUE TITLE
Runaway split not resolving after the query finished/failed

### ISSUE THREAD

**Issue by chliang71** [prestodb/presto#16574]
Hi community,

In our production workload, we frequently saw runaway split still not resolving on worker nodes even after the queries have finished/failed. All such splits have the below stack trace. We are suspecting somewhere in this code path it get stuck swallowed query finish/fail signal. Would be good to have some insights from the community.

Thanks!

```
at com.facebook.presto.$gen.PagesHashStrategy_20210805_063244_412476.positionEqualsPositionIgnoreNulls(Unknown Source)
	at com.facebook.presto.operator.PagesHash.positionEqualsPositionIgnoreNulls(PagesHash.java:224)
	at com.facebook.presto.operator.PagesHash.<init>(PagesHash.java:107)
	at com.facebook.presto.operator.JoinHashSupplier.<init>(JoinHashSupplier.java:74)
	at jdk.internal.reflect.GeneratedConstructorAccessor96136.newInstance(Unknown Source)
	at java.base@11.0.4/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@11.0.4/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at app//com.facebook.presto.sql.gen.JoinCompiler$LookupSourceSupplierFactory.createLookupSourceSupplier(JoinCompiler.java:928)
	at app//com.facebook.presto.operator.PagesIndex.createLookupSourceSupplier(PagesIndex.java:490)
	at app//com.facebook.presto.operator.HashBuilderOperator.buildLookupSource(HashBuilderOperator.java:597)
	at app//com.facebook.presto.operator.HashBuilderOperator.finishInput(HashBuilderOperator.java:494)
	at app//com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:450)
	at app//com.facebook.presto.operator.Driver.processInternal(Driver.java:441)
	at app//com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:301)
	at app//com.facebook.presto.operator.Driver$$Lambda$3283/0x00007f5c295e0cb0.get(Unknown Source)
	at app//com.facebook.presto.operator.Driver.tryWithLock(Driver.java:722)
	at app//com.facebook.presto.operator.Driver.processFor(Driver.java:294)
	at app//com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at app//com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at app//com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_247_83b85b7____20210802_022936_1.run(Unknown Source)
	at java.base@11.0.4/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.4/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.4/java.lang.Thread.run(Thread.java:834)
```

**Comment by chliang71** [comment]
Hi @aweisberg I found your [fix](https://github.com/prestodb/presto/commit/8e8a546fcd4367fadda181e3eb334891215bba93) seem to address a very similar issue.  Thanks for posting it! I wonder do you have insights on why this could happen, i.e. why the interrupt mechanism wasn't enough? I'm digging into this, even some quick pointers to the code would help a lot. Thanks in advance.

**Comment by aweisberg** [comment]
Interruption only works if the code isn't stuck in a loop that fails to check for interrupts. In this case it is stuck in some generated code. I haven't seen that exact stack before but I have seen instances of generated code causing problems where they are stuck waiting to get compiled by the JVM. 

It might be a bug in the output of [JoinCompiler](https://github.com/prestodb/presto/blob/bf8b8a3c433dd5c35fadf451e3d52781e34daeed/presto-main/src/main/java/com/facebook/presto/sql/gen/JoinCompiler.java#L723).

**Comment by aweisberg** [comment]
If you provide a reproducer for this it would be a hugely helpful. Like if you can modify an existing unit test to trigger the runaway split.
