### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hudi.common.util.HoodieAvroUtils

### ISSUE THREAD

**Issue by huanchuanjian** [prestodb/presto#16632]
Hi, I want to use presto to query the real-time data of the hudi MOR table,  but have some problems

1. Presto version: 0.246

2. Hudi table is created with the following sql

```sql
CREATE TABLE `tmp.sensor_reading`(
  `uuid` string,
  `id` string,
  `ts` bigint,
  `temperature` double)
PARTITIONED BY (
  `ds` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat';
```

3. query sql

```sql
select * from tmp.sensor_reading where ds='20210808' limit 10;
```

4. error messages

```
2021-08-20T10:25:18.478+0800	ERROR	SplitRunner-6-113	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20210820_022513_00032_isq7y.1.0.0-1 {path=hdfs://ns1/user/hive/warehouse/tmp.db/sensor_reading/ds=20210808/fc29e5b9-5119-440b-ac1a-9e0e955a0c3e_1-5-0_20210819133601.parquet, start=0, length=959928, fileSize=959928, hosts=[], database=tmp, table=sensor_reading, nodeSelectionStrategy=NO_PREFERENCE, partitionName=ds=20210808, s3SelectPushdownEnabled=false, cacheQuotaRequirement=CacheQuotaRequirement{cacheQuotaScope=GLOBAL, quota=Optional.empty}} (start = 3.818715647407013E10, wall = 1690 ms, cpu = 0 ms, wait = 15 ms, calls = 1)
java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.<init>(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;Lorg/codehaus/jackson/JsonNode;)V
	at org.apache.hudi.common.util.HoodieAvroUtils.initRecordKeySchema(HoodieAvroUtils.java:147)
	at org.apache.hudi.common.util.HoodieAvroUtils.<clinit>(HoodieAvroUtils.java:66)
	at org.apache.hudi.hadoop.realtime.AbstractRealtimeRecordReader.addPartitionFields(AbstractRealtimeRecordReader.java:323)
	at org.apache.hudi.hadoop.realtime.AbstractRealtimeRecordReader.init(AbstractRealtimeRecordReader.java:346)
	at org.apache.hudi.hadoop.realtime.AbstractRealtimeRecordReader.<init>(AbstractRealtimeRecordReader.java:108)
	at org.apache.hudi.hadoop.realtime.RealtimeCompactedRecordReader.<init>(RealtimeCompactedRecordReader.java:50)
	at org.apache.hudi.hadoop.realtime.HoodieRealtimeRecordReader.constructRecordReader(HoodieRealtimeRecordReader.java:69)
	at org.apache.hudi.hadoop.realtime.HoodieRealtimeRecordReader.<init>(HoodieRealtimeRecordReader.java:47)
	at org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat.getRecordReader(HoodieParquetRealtimeInputFormat.java:253)
	at com.facebook.presto.hive.HiveUtil.createRecordReader(HiveUtil.java:254)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$0(GenericHiveRecordCursorProvider.java:74)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:73)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:449)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:177)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:417)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:300)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:721)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:293)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_246_dfb27e9__0_246____20210820_022457_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2021-08-20T10:25:18.478+0800	ERROR	SplitRunner-1-108	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20210820_022513_00032_isq7y.1.0.0-2 {path=hdfs://ns1/user/hive/warehouse/tmp.db/sensor_reading/ds=20210808/ad68d6ed-d9b0-4977-a50f-55e007aa0833_0-5-0_20210819133601.parquet, start=0, length=957310, fileSize=957310, hosts=[], database=tmp, table=sensor_reading, nodeSelectionStrategy=NO_PREFERENCE, partitionName=ds=20210808, s3SelectPushdownEnabled=false, cacheQuotaRequirement=CacheQuotaRequirement{cacheQuotaScope=GLOBAL, quota=Optional.empty}} (start = 3.818715647691907E10, wall = 1688 ms, cpu = 0 ms, wait = 18 ms, calls = 1)
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hudi.common.util.HoodieAvroUtils
	at org.apache.hudi.hadoop.realtime.AbstractRealtimeRecordReader.addPartitionFields(AbstractRealtimeRecordReader.java:323)
	at org.apache.hudi.hadoop.realtime.AbstractRealtimeRecordReader.init(AbstractRealtimeRecordReader.java:346)
	at org.apache.hudi.hadoop.realtime.AbstractRealtimeRecordReader.<init>(AbstractRealtimeRecordReader.java:108)
	at org.apache.hudi.hadoop.realtime.RealtimeCompactedRecordReader.<init>(RealtimeCompactedRecordReader.java:50)
	at org.apache.hudi.hadoop.realtime.HoodieRealtimeRecordReader.constructRecordReader(HoodieRealtimeRecordReader.java:69)
	at org.apache.hudi.hadoop.realtime.HoodieRealtimeRecordReader.<init>(HoodieRealtimeRecordReader.java:47)
	at org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat.getRecordReader(HoodieParquetRealtimeInputFormat.java:253)
	at com.facebook.presto.hive.HiveUtil.createRecordReader(HiveUtil.java:254)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.lambda$createRecordCursor$0(GenericHiveRecordCursorProvider.java:74)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.hive.GenericHiveRecordCursorProvider.createRecordCursor(GenericHiveRecordCursorProvider.java:73)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:449)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:177)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:417)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:300)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:721)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:293)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:545)
	at com.facebook.presto.$gen.Presto_0_246_dfb27e9__0_246____20210820_022457_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Has anyone encountered this problem？

**Comment by huanchuanjian** [comment]
We have solved this problem, we use spark to write hudi, it is worth noting that `HIVE_SYNC_ENABLED_OPT_KEY` option needs to be turned on, so that the commit timestamp will be synchronized.

eg.

```sql
CREATE EXTERNAL TABLE `tmp.my_hudi_table_ro`(
  `_hoodie_commit_time` string,
  `_hoodie_commit_seqno` string,
  `_hoodie_record_key` string,
  `_hoodie_partition_path` string,
  `_hoodie_file_name` string,
  `id` string,
  `ts` string)
PARTITIONED BY (
  `ds` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hudi.hadoop.HoodieParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://ns1/user/hive2/warehouse/tmp.db/my_hudi_table'
TBLPROPERTIES (
  'last_commit_time_sync'='20210922163914',
  'transient_lastDdlTime'='1632276943')
  

CREATE EXTERNAL TABLE `tmp.my_hudi_table_rt`(
  `_hoodie_commit_time` string,
  `_hoodie_commit_seqno` string,
  `_hoodie_record_key` string,
  `_hoodie_partition_path` string,
  `_hoodie_file_name` string,
  `id` string,
  `ts` string)
PARTITIONED BY (
  `ds` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hudi.hadoop.realtime.HoodieParquetRealtimeInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  'hdfs://ns1/user/hive2/warehouse/tmp.db/my_hudi_table'
TBLPROPERTIES (
  'last_commit_time_sync'='20210922163914',
  'transient_lastDdlTime'='1632276944')
```

`last_commit_time_sync`  this table property will be saved in the presto split
