### ISSUE TITLE
unable to integrate ranger with presto

### ISSUE THREAD

**Issue by Dakadivya** [prestodb/presto#16655]
2021-08-25T18:42:18.965Z	WARN	main	com.facebook.presto.server.PluginManager	No service providers of type com.facebook.presto.spi.Plugin

2021-08-26T06:10:20.088Z	ERROR	main	com.facebook.presto.server.PrestoServer	Access control ranger is not registered
java.lang.IllegalStateException: Access control ranger is not registered
	at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
	at com.facebook.presto.security.AccessControlManager.setSystemAccessControl(AccessControlManager.java:136)
	at com.facebook.presto.security.AccessControlManager.loadSystemAccessControl(AccessControlManager.java:118)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:152)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:77)

**Comment by drummerglen** [comment]
Same problem on version 0.276.1
`2022-09-18T23:10:37.102+0800    INFO    main    com.facebook.presto.security.AccessControlManager       -- Loading system access control --
2022-09-18T23:10:37.103+0800    ERROR   main    com.facebook.presto.server.PrestoServer Access control ranger is not registered
java.lang.IllegalStateException: Access control ranger is not registered
        at com.google.common.base.Preconditions.checkState(Preconditions.java:588)
        at com.facebook.presto.security.AccessControlManager.setSystemAccessControl(AccessControlManager.java:150)
        at com.facebook.presto.security.AccessControlManager.loadSystemAccessControl(AccessControlManager.java:136)
        at com.facebook.presto.security.AccessControlManager.loadSystemAccessControl(AccessControlManager.java:123)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:169)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)`

**Comment by pratyakshsharma** [comment]
@agrawalreetika Can you please help here.

**Comment by agrawalreetika** [comment]
You can use Ranger-Based Authorization for Hive connector by using the required configuration in your hive catalog configuration - https://prestodb.io/docs/current/connector/hive-security.html#hive-ranger-based-authorization
This is supported in presto-0.275 or later.
