### ISSUE TITLE
ARRAY_CONCAT seems to be stateful and not thread-safe

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#16728]
It seems to be all kind of bad. Sometimes I get:

presto:infrastructure> select sum(cardinality(s)) from (SELECT REDUCE_AGG(x, cast(array[] as array<bigint>), (x,y)->x||sequence(1, y), (x,y)->x||y) s FROM (SELECT x FROM (SELECT 1) CROSS JOIN UNNEST(SEQUENCE(1, 1000)) T(x)) group by random(100) );

Query 20210910_183113_54865_wx7hd failed: com.facebook.presto.common.block.LongArrayBlockBuilder

java.lang.UnsupportedOperationException: com.facebook.presto.common.block.LongArrayBlockBuilder
	at com.facebook.presto.common.block.BlockBuilder.appendStructure(BlockBuilder.java:95)
	at com.facebook.presto.common.type.ArrayType.writeObject(ArrayType.java:195)
	at com.facebook.presto.operator.aggregation.state.BlockState.write(BlockState.java:36)
	at com.facebook.presto.$gen.BigintBigintReduceAggGroupedAccumulator_20210910_183114_43520.evaluateFinal(Unknown Source)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder$Aggregator.evaluate(InMemoryHashAggregationBuilder.java:451)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$buildResult$3(InMemoryHashAggregationBuilder.java:302)

And some other times I get:

presto:infrastructure> select sum(cardinality(s)) from (SELECT REDUCE_AGG(x, cast(array[] as array<bigint>), (x,y)->x||sequence(1, y), (x,y)->x||y) s FROM (SELECT x FROM (SELECT 1) CROSS JOIN UNNEST(SEQUENCE(1, 7000)) T(x)) group by random(100) );

Query 20210910_183557_00071_ue9rt, FAILED, 1 node
Splits: 10 total, 4 done (40.00%)
0:02 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20210910_183557_00071_ue9rt failed: Invalid position 86989 and length 19596 in block with 106583 positions

Seems to happen only when used from lambdas in reduce_agg. Couldn't repro any other way.

**Comment by kaikalur** [comment]
Turns out ARRAY_CONCAT is using Block.getRegion and the REDUCE_AGG state is simply holding on to it. But getRegion can be a view so block is being modified when it's being held onto by the agg state.

I think we should simplify ARRAY_CONCAT and simply return a new block and get rid of the state object.

**Comment by kaikalur** [comment]
Similar issue with MAP_CONCAT as well:

presto:infrastructure> select sum(cardinality(s)) from (SELECT REDUCE_AGG(x, cast(map() as map<bigint, bigint>), (x,y) -> map_concat(x, map(sequence(1, y), repeat(1, cast(y as int)))), (x,y)->map_concat(x,y)) s FROM (SELECT x FROM (SELECT 1) CROSS JOIN UNNEST(SEQUENCE(1, 7000)) T(x)) group by random(100) );

Query 20210910_223512_48768_8qq3h failed: Expected current entry to be closed but was opened
