### ISSUE TITLE
HIVE_UNKNOWN_ERROR (16777221)

### ISSUE THREAD

**Issue by xueyibing** [prestodb/presto#16931]
prestodb VERSION
0.264-11C3FEA

hive version:
CDH 6.0.1, Parce
```
om.facebook.presto.spi.PrestoException: HIVE_UNKNOWN_ERROR
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:128)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: undefined
	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
	at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:73)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
	at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
	at com.facebook.presto.hive.StoragePartitionLoader.loadPartition(StoragePartitionLoader.java:168)
	at com.facebook.presto.hive.DelegatingPartitionLoader.loadPartition(DelegatingPartitionLoader.java:78)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:192)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:40)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:121)
	... 7 more
```

**Comment by agrawalreetika** [comment]
@xueyibing When are you getting this exception?

**Comment by beinan** [comment]
@xueyibing looks like the implementation of the FileSystem is not an instance of ExtendedFileSystem,  have you guys hacked presto somehow? or could you share your catalog/hive.properties to us?  Thanks!

**Comment by DawnWLBD** [comment]
@xueyibing 是hdfs-site.xml里的配置造成的。修改为：
<property>
      <name>fs.hdfs.impl.disable.cache</name>
      <value>false</value>
  </property>

**Comment by pratyakshsharma** [comment]
@xueyibing Just checking in to see if you are still facing any issues?
