### ISSUE TITLE
 There is a mismatch between the table and partition schemas.

### ISSUE THREAD

**Issue by luoshuibing** [prestodb/presto#16937]
The following error occurs in presto query because the hive table structure changes. Can you tell me how to resolve this error, or does Presto not support this operation?
        ```
 com.facebook.presto.spi.PrestoException: There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'resp_dur_w' in table 'dmrt_bc.dmrtbc_cts_online_sessn_rounds_test_i_w' is declared as type 'decimal(18,12)', but partition 'dt=2021-10-31' declared column 'resp_dur_w' as type 'decimal(38,12)'.
	at com.facebook.presto.hive.HiveSplitManager.lambda$getPartitionMetadata$2(HiveSplitManager.java:315)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:788)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1340)
	at com.facebook.presto.hive.ConcurrentLazyQueue.poll(ConcurrentLazyQueue.java:37)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:254)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:93)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:187)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:47)
	at com.facebook.presto.hive.util.ResumableTasks.access$000(ResumableTasks.java:20)
	at com.facebook.presto.hive.util.ResumableTasks$1.run(ResumableTasks.java:35)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by beinan** [comment]
@luoshuibing have you changed the type of column "resp_dur_w" recently?

**Comment by luoshuibing** [comment]
> @luoshuibing have you changed the type of column "resp_dur_w" recently?

yes,I modified the table data structure on the Hive client, but an error occurred in presto. So Presto doesn't support this kind of transformation of data structures, right?

**Comment by beinan** [comment]
@luoshuibing  looks like so, though I didn't look into the code.  you changed the column type from decimal(38,12) to decimal(18,12), did you?
