### ISSUE TITLE
Failed to initialize Hadoop FileSystem for iceberg connector: No FileSystem for scheme: hdfs

### ISSUE THREAD

**Issue by liupan664021** [prestodb/presto#16958]
I meet a special cornal case of iceberg connector, and it can be reproduced by following steps:
1. configurate iceberg connector and start the presto cluster
2. execute the following SQL to query the snapshots of a test table before quering any other SQL by iceberg connector
  ```SQL 
    select * from "test_table$snapshots"
  ```
3. then we get the following error:
 `com.facebook.presto.spi.PrestoException: cannot create caching file system
        at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:81)
        at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration$CachingJobConf.createFileSystem(HiveCachingHdfsConfiguration.java:105)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:59)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
        at com.facebook.presto.iceberg.HdfsInputFile.<init>(HdfsInputFile.java:42)
        at com.facebook.presto.iceberg.HdfsFileIO.newInputFile(HdfsFileIO.java:44)
        at com.facebook.presto.iceberg.HiveTableOperations.lambda$refreshFromMetadataLocation$6(HiveTableOperations.java:346)
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:405)
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214)
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198)
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190)
        at com.facebook.presto.iceberg.HiveTableOperations.refreshFromMetadataLocation(HiveTableOperations.java:345)
        at com.facebook.presto.iceberg.HiveTableOperations.refresh(HiveTableOperations.java:189)
        at com.facebook.presto.iceberg.HiveTableOperations.current(HiveTableOperations.java:165)
        at org.apache.iceberg.BaseTable.snapshots(BaseTable.java:119)
        at com.facebook.presto.iceberg.SnapshotsTable.buildPages(SnapshotsTable.java:86)
        at com.facebook.presto.iceberg.SnapshotsTable.pageSource(SnapshotsTable.java:79)
        at com.facebook.presto.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:106)
        at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:249)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:424)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:728)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:300)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
        at com.facebook.presto.$gen.Presto_0_266_SNAPSHOT_3532c04____20211109_073117_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:144)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:89)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:62)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:69)
        ... 36 more`

4. after the query failed after retring several times, the iceberg connector is 'broken' and can not handle other queries anymore

This bug is caused by the Hadoop filesystem is not initialized in the correct classloader safe context.

When analyzing the visiting of system table of iceberg connector, we can foucus on the following code:
```java
// IcebergMetadata.java
private Optional<SystemTable> getRawSystemTable(ConnectorSession session, SchemaTableName tableName)
    {
        IcebergTableName name = IcebergTableName.from(tableName.getTableName());

        MetastoreContext metastoreContext = new MetastoreContext(session.getIdentity(), session.getQueryId(), session.getClientInfo(), session.getSource(), Optional.empty());
        Optional<Table> hiveTable = metastore.getTable(metastoreContext, tableName.getSchemaName(), name.getTableName());
        if (!hiveTable.isPresent() || !isIcebergTable(hiveTable.get())) {
            return Optional.empty();
        }

        org.apache.iceberg.Table table = getIcebergTable(metastore, hdfsEnvironment, session, new SchemaTableName(tableName.getSchemaName(), name.getTableName()));

        SchemaTableName systemTableName = new SchemaTableName(tableName.getSchemaName(), name.getTableNameWithType());
        switch (name.getTableType()) {
            case DATA:
                break;
            case HISTORY:
                if (name.getSnapshotId().isPresent()) {
                    throw new PrestoException(NOT_SUPPORTED, "Snapshot ID not supported for history table: " + systemTableName);
                }
                return Optional.of(new HistoryTable(systemTableName, table));
            case SNAPSHOTS:
                if (name.getSnapshotId().isPresent()) {
                    throw new PrestoException(NOT_SUPPORTED, "Snapshot ID not supported for snapshots table: " + systemTableName);
                }
                return Optional.of(new SnapshotsTable(systemTableName, typeManager, table));
            case PARTITIONS:
                return Optional.of(new PartitionTable(systemTableName, typeManager, table, getSnapshotId(table, name.getSnapshotId())));
            case MANIFESTS:
                return Optional.of(new ManifestsTable(systemTableName, table, getSnapshotId(table, name.getSnapshotId())));
            case FILES:
                return Optional.of(new FilesTable(systemTableName, table, getSnapshotId(table, name.getSnapshotId()), typeManager));
        }
        return Optional.empty();
    }
```
If the system table type is `PARTITIONS`, `MANIFESTS` or `FILES`, from `getSnapshotId` here is the call chain:
```
getSnapshotId() -> Table#currentSnapshot() -> HiveTableOperations#current() -> HiveTableOperations#refresh() -> HiveTableOperations#refreshFromMetadataLocation()-> HdfsFileIO#newInputFile() -> ... -> initializing the Hadoop FileSystem ...
```
These steps is in the classloader safe context.
But the `HISTORY` and `SNAPSHOTS` miss those steps and the Hadoop FileSystem is not initialized in the plan stage.

Since it's the system table, the TableScan Stage is executed in coordinator. When building pages, the hadoop filesystem is initialized in the non classloader safe context. Of course it will failed, and after the wrong context initializing, the connector has no filesystem for 'hdfs' to handle other queries which is 'broken'. Now we can only restart the presto cluster to recorver the iceberg connector.

I'll soon give a pr to fix it.

**Comment by beinan** [comment]
Thank you @liupan664021 ! We will take a look at your PR soon.

**Comment by pratyakshsharma** [comment]
Closing as the PR was merged long back.
