### ISSUE TITLE
mysql jdbc  close  error  ???

### ISSUE THREAD

**Issue by kldcxy-1** [prestodb/presto#16952]
2021-11-06T16:43:16.130+0800    INFO    20211106_084322_00036_gc7ms.1.0.0-0-44  stderr  Sat Nov 06 16:43:16 CST 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2021-11-06T16:43:16.269+0800    ERROR   20211106_084322_00036_gc7ms.1.0.0-0-44  com.facebook.presto.operator.Driver     Error closing operator 0 for task 20211106_084322_00036_gc7ms.1.0.0
java.lang.NullPointerException
        at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
        at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
        at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
        at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
        at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:83)
        at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:195)
        at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:184)
        at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:605)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:458)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:728)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:300)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
        at com.facebook.presto.$gen.Presto_0_265_SNAPSHOT_b52db2c____20211106_082818_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Guazhen** [comment]
You need to add a suffix in mysql, useSSL= false&allowpublickeyretrieval=true&servertimezone = UTC

**Comment by kldcxy-1** [comment]
This error was not resolved

ERROR 20211106_084322_00036_gc7ms.1.0.0-0-44 com.facebook.presto.operator.Driver Error closing operator 0 for task 20211106_084322_00036_gc7ms.1.0.0
java.lang.NullPointerException
at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
at com.facebook.presto.spi.RecordPageSource.close(RecordPageSource.java:83)
at com.facebook.presto.operator.TableScanOperator.finish(TableScanOperator.java:195)
at com.facebook.presto.operator.TableScanOperator.close(TableScanOperator.java:184)
at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:605)
at com.facebook.presto.operator.Driver.processInternal(Driver.java:458)
at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:728)
at com.facebook.presto.operator.Driver.processFor(Driver.java:300)
at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
at com.facebook.presto.$gen.Presto_0_265_SNAPSHOT_b52db2c____20211106_082818_1.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by CCColby** [comment]
I alse meet this problem, how to fix it? thanks @kldcxy-1 
com.facebook.presto.operator.Driver Error closing operator 0 for task

**Comment by CCColby** [comment]
> I alse meet this problem, how to fix it? thanks @kldcxy-1 com.facebook.presto.operator.Driver Error closing operator 0 for task

i solved this problem,, upgrade JDBC

**Comment by kldcxy-1** [comment]
@CCColby  How did you upgrade JDBC? can you share the code?

**Comment by CCColby** [comment]
> @CCColby How did you upgrade JDBC? can you share the code?

I changed pom.xml, mysql-connector-java version to 8.0.22。
when you build, youcan find the error code,  fixed it , good lukcy

**Comment by kldcxy-1** [comment]
![image](https://user-images.githubusercontent.com/61725031/146339604-22a38b1a-a671-44cb-bbaa-ac0613ab2aa6.png)
Do you modify it manually like this? @CCColby

**Comment by kldcxy-1** [comment]
<dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.22</version>
        </dependency>

Do you modify it manually like this?  @CCColby  Have you tested other versions?

**Comment by CCColby** [comment]
> ```
>     <dependency>
>         <groupId>mysql</groupId>
>         <artifactId>mysql-connector-java</artifactId>
>         <version>8.0.22</version>
>     </dependency>
> ```
> 
> Do you modify it manually like this? @CCColby Have you tested other versions?

yes, i have not.  not only modify this xml。some code also need to solved. when you build ,you can find the problem

**Comment by kldcxy-1** [comment]
@CCColby  ok ， thank you.
