### ISSUE TITLE
Failed to Parse a Query - Formatted query does not parse

### ISSUE THREAD

**Issue by rubenssoto** [prestodb/presto#16987]
Hello,

I can't create a VIEW because presto give me the following error:

```
com.facebook.presto.spi.PrestoException: Formatted query does not parse: Query{queryBody=QuerySpecification{select=Select{distinct=false, selectItems=[*]}, from=Optional[Table{raw_courier_api.order}], where=null, groupBy=Optional.empty, having=null, orderBy=Optional.empty, offset=null, limit=null}, orderBy=Optional.empty}
	at com.facebook.presto.sql.SqlFormatterUtil.getFormattedSql(SqlFormatterUtil.java:44)
	at com.facebook.presto.execution.CreateViewTask.execute(CreateViewTask.java:86)
	at com.facebook.presto.execution.CreateViewTask.execute(CreateViewTask.java:49)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:213)
	at com.facebook.presto.$gen.Presto_0_266_SNAPSHOT_3e887dd____20211112_202323_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:266)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

The biggest problem is not the view creation, our data exploration tool is metabase and there is an option in metabase to put variables in queries, so the tool writes the querys like the following:

PREPARE statement10 FROM

select id from
    schema_name."order"
    where created_date > cast(? as timestamp)

and I have the same error.

I think the problem is related to the word order.

Anybody could help me? This is our most used table.

Thank you

**Comment by rohanpednekar** [comment]
I have reopened https://github.com/prestodb/presto/pull/12223 which got raised after https://github.com/prestodb/presto/issues/10739

Thanks for reporting @rubenssoto
