### ISSUE TITLE
limit error    what's the reason ?

### ISSUE THREAD

**Issue by kldcxy-1** [prestodb/presto#16982]
SELECT id FROM mysql.hly_message.baseinfo_msg_temp OFFSET 2 LIMIT 3

Exception in thread "main" java.sql.SQLException: Query failed (#20211112_091154_00006_exy8c): not yet implemented: com.facebook.presto.sql.planner.plan.OffsetNode
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1751)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:121)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:272)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)
	at com.facebook.presto.jdbc.PrestoStatement.executeQuery(PrestoStatement.java:79)
	at com.hly.presto.jdbc.utils.PrestoJdbcDemo.main(PrestoJdbcDemo.java:36)

**Comment by sixtree92** [comment]
Release 0.257 version add support for the the OFFSET clause in SQL query expressions. This feature can be enabled by setting the session property offset_clause_enabled or configuration property offset-clause-enabled to true.

session setting： set session offset_clause_enabled = true;
etc/config.properties:  offset-clause-enabled=true

https://prestodb.io/docs/current/release/release-0.257.html?highlight=offset%20clause%20enabled

**Comment by pratyakshsharma** [comment]
Closing this due to no follow up from user.
