### ISSUE TITLE
Raptorx: Are there plans to support iceberg connector?

### ISSUE THREAD

**Issue by weimy2018** [prestodb/presto#17025]
Will this feature have the same performance improvement when it is migrated to iceberg connector?

**Comment by beinan** [comment]
Thank you for your interest in raptorx.  We just merged a PR for the alluxio local cache support in iceberg connector, feel free to give it a shot, thanks!  https://github.com/prestodb/presto/pull/16942

**Comment by weimy2018** [comment]
Met this error . 
java.lang.UnsupportedOperationException: **s3a is not supported as the external filesystem.**
        at alluxio.hadoop.LocalCacheFileSystem.initialize(LocalCacheFileSystem.java:91)
        at com.facebook.presto.cache.alluxio.AlluxioCachingFileSystem.initialize(AlluxioCachingFileSystem.java:72)
        at com.facebook.presto.cache.CacheFactory.createCachingFileSystem(CacheFactory.java:54)
        at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration.lambda$getConfiguration$0(HiveCachingHdfsConfiguration.java:71)
        at com.facebook.presto.hive.cache.HiveCachingHdfsConfiguration$CachingJobConf.createFileSystem(HiveCachingHdfsConfiguration.java:105)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:59)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.facebook.presto.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
