### ISSUE TITLE
Type error while inlining sql udf

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#17102]
While testing a new release, we noticed the following type error with SQL UDF when we use inline_sql_functions=true

java.lang.IllegalArgumentException: type of variable 'xau_at_y' is expected to be bigint, but the actual type is integer
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:458)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.verifyTypeSignature(TypeValidator.java:217)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:133)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:66)
	at com.facebook.presto.spi.plan.ProjectNode.accept(ProjectNode.java:93)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitExchange(InternalPlanVisitor.java:135)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:305)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitOutput(InternalPlanVisitor.java:30)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:84)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:33)
	at com.facebook.presto.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:63)
	at com.facebook.presto.sql.planner.sanity.PlanChecker.lambda$validateFinalPlan$0(PlanChecker.java:83)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at com.facebook.presto.sql.planner.sanity.PlanChecker.validateFinalPlan(PlanChecker.java:83)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:199)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:181)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:208)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:189)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:128)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:135)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:113)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:62)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:59)
	at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:54)
	at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:86)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:189)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:796)
	at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:123)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kaikalur** [comment]
@rongrong  FYI

**Comment by kaikalur** [comment]
CREATE FUNCTION foo (
   str varchar,
   x bigint,
   y bigint
)
RETURNS bigint
COMMENT ''
LANGUAGE SQL
DETERMINISTIC
RETURNS NULL ON NULL INPUT
RETURN (CASE WHEN (y < 0) THEN null WHEN (x <= 0) THEN null WHEN ((length(str) - y) <= 0) THEN null WHEN (y < x) THEN 1 WHEN (strpos(substr(str, ((y - x) + 2), x), '1') > 0) THEN 1 ELSE 0 END)
;

with base AS (Select foo(x,7,7) x, y from T)
select y, 1.0 * sum(x)/count(x), count(x) from base group by 1

**Comment by kaikalur** [comment]
Looks like it works fine now!
