### ISSUE TITLE
Getting "java.lang.IllegalStateException: No service providers of type io.trino.spi.Plugin" error with starburst-enterprise-364-e.4.tar.gz and trino-jdbc-364-e.4.jar

### ISSUE THREAD

**Issue by suryaanand** [prestodb/presto#17142]
Hi Team,

I am using starburst-enterprise-364-e.4.tar.gz and trino-jdbc-364-e.4.jar and while staring the server I am getting below error.

`2021-12-23T21:11:35.325+0530	ERROR	main	io.trino.server.Server	No service providers of type io.trino.spi.Plugin
java.lang.IllegalStateException: No service providers of type io.trino.spi.Plugin
	at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:144)
	at io.trino.server.PluginManager.loadPlugin(PluginManager.java:134)
	at io.trino.server.ServerPluginsProvider.lambda$loadPlugins$1(ServerPluginsProvider.java:57)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at java.base/java.util.concurrent.ExecutorCompletionService.submit(ExecutorCompletionService.java:184)
	at io.trino.util.Executors.executeUntilFailure(Executors.java:41)
	at io.trino.server.ServerPluginsProvider.loadPlugins(ServerPluginsProvider.java:52)
	at io.trino.server.PluginManager.loadPlugins(PluginManager.java:115)
	at io.trino.server.Server.doStart(Server.java:123)
	at io.trino.server.Server.lambda$start$0(Server.java:78)
	at io.trino.$gen.Trino_364_e_4____20211223_154115_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:78)
	at com.starburstdata.presto.StarburstTrinoServer.main(StarburstTrinoServer.java:40)`

I have already installed trino opensource trino-server-364.tar.gz and trino-cli-364-executable.jar which is working fine for me. If I replace plugin folder from opensource trino server folder to starburst-enterprise-364-e.4 then its working fine. Could you please assist me on the same. Please let me know if any other information are required from my end.

Thank you

**Comment by ebyhr** [comment]
The right repository is https://github.com/trinodb/trino. Could you join our community Slack?

**Comment by suryaanand** [comment]
I have already on trino slack and as per I know I have already posted this issue on slack but didn't received any reply. You want to me share this issue on slack again? please suggest.

**Comment by ebyhr** [comment]
Yes, please share the link and also I would recommend closing this issue anyway.
