### ISSUE TITLE
debug start error  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Yanwenjingcn** [prestodb/presto#17144]
2021-12-30T14:17:35.510+0800	DEBUG	main	com.facebook.presto.server.PluginManager	    /Users/x/projects/IdeaProjects/presto/presto-function-namespace-managers/target/classes
2021-12-30T14:17:35.526+0800	INFO	main	com.facebook.presto.server.PluginManager	Installing com.facebook.presto.functionNamespace.FunctionNamespaceManagerPlugin
2021-12-30T14:17:35.536+0800	INFO	main	com.facebook.presto.server.PluginManager	Registering function namespace manager mysql
2021-12-30T14:17:35.537+0800	INFO	main	com.facebook.presto.server.PluginManager	-- Finished loading plugin ../presto-function-namespace-managers/pom.xml --
2021-12-30T14:17:35.537+0800	INFO	main	com.facebook.presto.server.PluginManager	-- Loading plugin ../presto-druid/pom.xml --
2021-12-30T14:17:35.537+0800	DEBUG	main	com.facebook.presto.server.PluginManager	/Users/x/projects/IdeaProjects/presto/presto-main/../presto-druid/pom.xml
2021-12-30T14:17:42.334+0800	ERROR	main	com.facebook.presto.server.PrestoServer	null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:788)
	at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:750)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:416)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:835)
	at io.airlift.resolver.ArtifactResolver.resolvePom(ArtifactResolver.java:175)
	at com.facebook.presto.server.PluginManager.buildClassLoaderFromPom(PluginManager.java:309)
	at com.facebook.presto.server.PluginManager.buildClassLoader(PluginManager.java:297)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:188)
	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:176)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:145)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)

i didn't change any code and config, just git clone project and run

**Comment by agrawalreetika** [comment]
@Yanwenjingcn I tried presto build from the master with default configs and started presto server. It's running fine for me.
I see for you Error is while loading the druid plugin. If you are not using the druid plugin, then can you try
 1. commenting/removing below line from config.properties
`  ../presto-druid/pom.xml,\`
2. Remove druid.properties

Then try to build and restart your server.

**Comment by pratyakshsharma** [comment]
@wengieeee are you still facing issues? Can we close this?
