### ISSUE TITLE
PresoDb google bigquery select error- ' line 1:15: Table  does not exist'

### ISSUE THREAD

**Issue by SEZ9** [prestodb/presto#17257]
hi, community， I use presto DB to query google Bigquery, I found that the following error will be prompted under some datasets 
We are expecting a reply，thanks .
![image](https://user-images.githubusercontent.com/20342912/152482264-f77ffb07-e797-476b-be17-aa9438ed7867.png)
our bigquery table and dataset like this. 
![image](https://user-images.githubusercontent.com/20342912/152482312-5787591a-c1b5-4cd3-94de-d0bf65c400aa.png)
these are full error stack
Query 20220204_041212_00004_rrijn failed: line 1:15: Table bigquery.ods.ods_hotelapi_hotel_img_tbl does not exist
com.facebook.presto.sql.analyzer.SemanticException: line 1:15: Table bigquery.ods.ods_hotelapi_hotel_img_tbl does not exist
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1252)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:316)
        at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2432)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1491)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:316)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:340)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1080)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:316)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:330)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:308)
        at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:89)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:189)
        at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:97)
        at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:796)
        at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:126)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by SEZ9** [comment]
I try to use Trino query, there is no similar problem ....

**Comment by agrawalreetika** [comment]
Hi @SEZ9, 
Which prestodb version are you trying it on?
I see a similar issue bug fix is done as a part of https://github.com/prestodb/presto/pull/16258 which was merged in prestodb-0.257

**Comment by SEZ9** [comment]
this issue happend in Both of AWS Emr release version Presto 0.261 and opensource [0.269]
