### ISSUE TITLE
HiveExternalQueryRunner failing with NoClassDefFoundError

### ISSUE THREAD

**Issue by kgpai** [prestodb/presto#17398]
A recent commit (https://github.com/prestodb/presto/commit/de18be1cf17968d16c5b6b4980bc22077ab96fdb) seems to have broken HiveExternalQueryRunner which is used for e2e testing in Velox/Presto_cpp and thus has broken builds . 

ERROR: 
 java.lang.NoClassDefFoundError: com/facebook/presto/tpcds/TpcdsPlugin
	at com.facebook.presto.hive.HiveQueryRunner.createQueryRunner(HiveQueryRunner.java:153)
	at com.facebook.presto.hive.HiveExternalWorkerQueryRunner.createNativeQueryRunner(HiveExternalWorkerQueryRunner.java:116)
	at com.facebook.presto.nativeworker.TestHiveTpchQueries.createNativeQueryRunner(TestHiveTpchQueries.java:44)
	at com.facebook.presto.nativeworker.TestHiveTpchQueriesUsingThrift.createQueryRunner(TestHiveTpchQueriesUsingThrift.java:25)
	at com.facebook.presto.tests.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.facebook.presto.tpcds.TpcdsPlugin
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by kgpai** [comment]
CC: @fgwang7w @mbasmanova @amitkdutta @mayankgarg1990

**Comment by fgwang7w** [comment]
@kgpai I'm setting up presto_cpp locally now and will take a look and respond on the issue. you mean that the build is broken, is it broken in velox or presto_cpp?

**Comment by fgwang7w** [comment]
fixed via https://github.com/prestodb/presto/pull/17400
