### ISSUE TITLE
Migrate from ESRI to Geotools for Geometry package

### ISSUE THREAD

**Issue by rohanpednekar** [prestodb/presto#17422]
Currently, Presto geo functions are based on the [ESRI package](https://github.com/Esri/geometry-api-java). The repository is dead and doesn't get any updates. The more common library is [Geotools](https://github.com/geotools/geotools) which is actively maintained and committed to.

For example, ESRI has an open PR for almost a year to support EWKB format geo from Postgres. The PR is completed and just pending merge: https://github.com/Esri/geometry-api-java/pull/271. This could have directly solved some of the issues while trying to select multipolygon geometry type from table:

```
Caused by: com.esri.core.geometry.GeometryException: invalid shape type
	at com.esri.core.geometry.OperatorImportFromWkbLocal.importFromWkb(OperatorImportFromWkbLocal.java:366)
	at com.esri.core.geometry.OperatorImportFromWkbLocal.executeOGC(OperatorImportFromWkbLocal.java:183)
	at com.esri.core.geometry.ogc.OGCGeometry.fromBinary(OGCGeometry.java:597)
	at com.facebook.presto.plugin.postgresql.PostgreSqlClient.getGeomFromBinary(PostgreSqlClient.java:223)
	at com.facebook.presto.plugin.postgresql.PostgreSqlClient.lambda$geometryColumnMapping$1(PostgreSqlClient.java:210)
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.getSlice(JdbcRecordCursor.java:173)
```

Please let me know what you guys think?

**Comment by davidraleigh** [comment]
@stolstov what do you think? maybe we merge the ewkb?

**Comment by stolstov** [comment]
The ESRI library is being maintained, but there is no new development planned so far. If any new bug found in existing functionality will be fixed.
