### ISSUE TITLE
Support Hive metastore impersonation for no-auth

### ISSUE THREAD

**Issue by zhangbutao** [prestodb/presto#17573]
If hive authentication(KERBEROS) is not enabled, hive metastore impersonation will fail. We should make impersonation work when no-auth.

**Comment by zhangbutao** [comment]
**hive.properties**
` cat etc/catalog/hive.properties
connector.name=hive-hadoop2
hive.metastore.uri=thrift://localhost:9083
hive.config.resources=core-site.xml,hadoop/hdfs-site.xml

hive.hdfs.impersonation.enabled=true
hive.metastore-impersonation-enabled=true
hive.metastore.authentication.type=NONE
`

**Error log:**
`presto> show schemas;
Query 20220402_053041_00000_h88zr failed: java.lang.NullPointerException
com.facebook.presto.spi.PrestoException: java.lang.NullPointerException
        at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:197)
        at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:88)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:342)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:303)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:337)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:342)
        at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:165)
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:188)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
`
