### ISSUE TITLE
No factory for connector [iceberg]

### ISSUE THREAD

**Issue by rjena5300** [prestodb/presto#17648]
Hello,
I am setting up iceberg catalog in presto 317, but getting below error while starting the presto server.

Below is my iceberg.properties catalog file contents

```
connector.name=iceberg
hive.metastore.uri=thrift://xxxxxxxxxxx:xxxxxx
iceberg.catalog.type=hive
```

```
!!! 2022-04-14 17:17:09,179 ERROR  - 2022-04-14T17:14:24.978Z INFO main io.prestosql.metadata.StaticCatalogStore -- Loading catalog etc/catalog/iceberg.properties --

!!! 2022-04-14 17:17:09,180 ERROR  - 2022-04-14T17:14:24.979Z ERROR main io.prestosql.server.PrestoServer No factory for connector [iceberg]. Available factories: [example-http, tpcds, memory, blackhole, kinesis, redis, phoenix, system, jmx, postgresql, elasticsearch, redshift, sqlserver, cassandra, localfile, kafka, tpch, atop, hive-hadoop2, mysql, bigquery, mongodb, presto-thrift]

!!! 2022-04-14 17:17:09,180 ERROR  - at com.google.common.base.Preconditions.checkArgument(Preconditions.java:440)
!!! 2022-04-14 17:17:09,180 ERROR  - at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:175)
!!! 2022-04-14 17:17:09,180 ERROR  - at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
!!! 2022-04-14 17:17:09,180 ERROR  - at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
!!! 2022-04-14 17:17:09,180 ERROR  - at io.prestosql.server.PrestoServer.run(PrestoServer.java:158)
!!! 2022-04-14 17:17:09,180 ERROR  - at io.prestosql.server.PrestoServer.main(PrestoServer.java:89)
```

Any steps I am missing to add iceberg connector ?

**Comment by ChunxuTang** [comment]
Hi @rjena5300, looks like you're using PrestoSQL but not PrestoDB? Could you try a release from this list (https://github.com/prestodb/presto/tags)?
