### ISSUE TITLE
Exception when using optimized_repartitioning

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#17730]
One of our user queries fails with:

```
java.lang.UnsupportedOperationException: accumulateSerializedRowSizes is not supported for fixed width types
	at com.facebook.presto.operator.repartition.LongArrayBlockEncodingBuffer.accumulateSerializedRowSizes(LongArrayBlockEncodingBuffer.java:52)
	at com.facebook.presto.operator.repartition.OptimizedPartitionedOutputOperator$PartitionBuffer.populateSerializedRowSizes(OptimizedPartitionedOutputOperator.java:741)
	at com.facebook.presto.operator.repartition.OptimizedPartitionedOutputOperator$PartitionBuffer.appendData(OptimizedPartitionedOutputOperator.java:688)
	at com.facebook.presto.operator.repartition.OptimizedPartitionedOutputOperator$PartitionBuffer.access$200(OptimizedPartitionedOutputOperator.java:619)
	at com.facebook.presto.operator.repartition.OptimizedPartitionedOutputOperator$PagePartitioner.partitionPage(OptimizedPartitionedOutputOperator.java:548)
	at com.facebook.presto.operator.repartition.OptimizedPartitionedOutputOperator.addInput(OptimizedPartitionedOutputOperator.java:177)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:434)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
```

But works when we turn off optimized_repartitioning

**Comment by kaikalur** [comment]
Hi @yingsu00 I was wondering if you can take a look. Unfortunately I haven't tried a smaller repro. If you can get enough context from the stack trace, please look into it. Otherwise, I will try and create a test case. Thanks!
