### ISSUE TITLE
i got this exception ResourceGroupManagerError while executing refreshAndStartQueries

### ISSUE THREAD

**Issue by mjzfrank** [prestodb/presto#17749]
I want test the feature of resource manager, this exception came out. do u have guide of resource manager?
i didn't find the guide in `https://prestodb.io/docs/current/overview.html`
`presto 272.1`
`jdk 1.8.0_191`
```
ERROR	ResourceGroupManager	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Error while executing refreshAndStartQueries
com.facebook.drift.client.UncheckedTTransportException: No hosts available
	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:126)
	at com.sun.proxy.$Proxy128.getResourceGroupInfo(Unknown Source)
	at com.facebook.presto.resourcemanager.ResourceManagerResourceGroupService.getResourceGroupInfos(ResourceManagerResourceGroupService.java:85)
	at com.facebook.presto.resourcemanager.ResourceManagerResourceGroupService.lambda$new$0(ResourceManagerResourceGroupService.java:70)
	at com.facebook.presto.resourcemanager.ResourceManagerResourceGroupService.getResourceGroupInfo(ResourceManagerResourceGroupService.java:79)
	at com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager.refreshResourceGroupRuntimeInfo(InternalResourceGroupManager.java:239)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.drift.protocol.TTransportException: No hosts available
	at com.facebook.drift.client.DriftMethodInvocation.fail(DriftMethodInvocation.java:331)
	at com.facebook.drift.client.DriftMethodInvocation.nextAttempt(DriftMethodInvocation.java:161)
	at com.facebook.drift.client.DriftMethodInvocation.createDriftMethodInvocation(DriftMethodInvocation.java:115)
	at com.facebook.drift.client.DriftMethodHandler.invoke(DriftMethodHandler.java:97)
	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:94)
	... 12 more
	Suppressed: com.facebook.drift.client.RetriesFailedException: No hosts available (invocationAttempts: 0, duration: 38.14us, failedConnections: 0, overloadedRejects: 0, attemptedAddresses: [])
		at com.facebook.drift.client.DriftMethodInvocation.fail(DriftMethodInvocation.java:337)
		... 16 more

```

**coordinator config.properties**

```
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=7005
discovery.uri=http://example:7005
discovery-server.enabled=true
query.max-memory=12GB
query.max-memory-per-node=4GB
query.max-total-memory-per-node=7GB
memory.heap-headroom-per-node=6GB
query.low-memory-killer.policy=total-reservation-on-blocked-nodes
experimental.reserved-pool-enabled=false
optimizer.optimize-hash-generation=true
resource-manager-enabled=true
```

**resource manager config.properties**
```
resource-manager=true
resource-manager-enabled=true
coordinator=false
node-scheduler.include-coordinator=false
http-server.http.port=7005
query.max-memory=12GB
query.max-memory-per-node=4GB
query.max-total-memory-per-node=7GB
memory.heap-headroom-per-node=6GB
discovery-server.enabled=true
discovery.uri=http://example:7005
```

**works config.properties**
```
coordinator=false
node-scheduler.include-coordinator=true
http-server.http.port=7005
discovery.uri=http://example:7005
query.max-memory=12GB
query.max-memory-per-node=4GB
query.max-total-memory-per-node=7GB
memory.heap-headroom-per-node=6GB
query.low-memory-killer.policy=total-reservation-on-blocked-nodes
experimental.reserved-pool-enabled=false
optimizer.optimize-hash-generation=true
resource-manager-enabled=true
```

**Comment by mjzfrank** [comment]
i found that the resource manager require this property
```
Error injecting constructor, java.lang.NullPointerException: trustCertificatesFile is null
```
```thrift.server.ssl.trust-certificate```
can't disable this ?

**Comment by rohanpednekar** [comment]
Could you please try 0.272 and not 0.272.1? There where some issue with 0.272.1 release.

**Comment by mjzfrank** [comment]
got it

**Comment by rohanpednekar** [comment]
@tdcmeehan @swapsmagic Do you guys think if someone can look into this NPE issue, we have one more user reporting a similar error while trying [disggregated-coordinator](https://prestodb.io/blog/2022/04/15/disggregated-coordinator at https://prestodb.slack.com/archives/C07JH9WMQ/p1652277867267079

**Comment by mjzfrank** [comment]
@rohanpednekar 
https://prestodb.slack.com/archives/C07JH9WMQ/p1652277867267079
sorry , i don't have a account to check this

**Comment by cliandy** [comment]
@mjzfrank @rohanpednekar @tdcmeehan @swapsmagic 

We've run into the same issue shown in the slack thread:
```
Error injecting constructor, java.lang.NullPointerException: trustCertificatesFile is null
  at com.facebook.drift.server.DriftServer.<init>(DriftServer.java:43)
```

What do we need to do with these configs to support SSL?
`thrift.server.ssl.trust-certificate`
`thrift.server.ssl.key`

Happy to add this to documentation if we can get something that works on this front. Thanks.

**Comment by rohanpednekar** [comment]
@swapsmagic just recommended to try with `thrift.server.ssl.enabled=false ` on another thread.

@cliandy and @mjzfrank Can you please try and let us know the feedback.

**Comment by cliandy** [comment]
@rohanpednekar We've tried that and still ran into issues with query execution.

**Comment by cliandy** [comment]
Behavior of nodes seems similar to what is mentioned here: https://github.com/prestodb/presto/issues/15453#issuecomment-1133595663

**Comment by fivesheep** [comment]
if you are running this in k8s with statefulset for the resource manager, try to use  dns name instead instead of the default ip seemed to be able to fix the issue. 
```
    node.internal-address-source=FQDN
    node.internal-address=$POD_DNS_WITH_HEADLESSS_SVC
```

**Comment by dnskr** [comment]
I see this exception during coordinator startup, but it resolves after some time.

**Launched Resource Manager, Coordinator and 2 Workers at the same time.**
There are 567 error messages within 1 minute and then the issue resolved:
```
2023-05-04T21:33:30.728Z	INFO	main	com.facebook.airlift.log.Logging	Logging to stderr
2023-05-04T21:33:30.730Z	INFO	main	Bootstrap	Loading configuration
2023-05-04T21:33:31.164Z	INFO	main	Bootstrap	Initializing logging
2023-05-04T21:33:42.119Z	INFO	main	com.facebook.airlift.jmx.JmxAgent	JMX agent started and listening on test-coordinator-65c8dc94d-fc996:36113
2023-05-04T21:33:42.781Z	ERROR	Discovery-0	com.facebook.airlift.discovery.client.CachingServiceSelector	Cannot connect to discovery server for refresh (presto/general): Lookup of presto failed for http://test-discovery:8080/v1/service/presto/general
2023-05-04T21:33:45.958Z	ERROR	ResourceGroupManager	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Error while executing refreshAndStartQueries
com.facebook.drift.client.UncheckedTTransportException: No hosts available
	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:126)

...

2023-05-04T21:34:43.115Z	ERROR	ResourceGroupManager	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Error while executing refreshAndStartQueries
com.facebook.drift.client.UncheckedTTransportException: No hosts available
	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:126)
```

**Added one more Coordinator.**
There are 95 error messages within 9 seconds and then the issue resolved:
```
2023-05-04T21:58:19.281Z	INFO	main	com.facebook.airlift.log.Logging	Logging to stderr
2023-05-04T21:58:19.283Z	INFO	main	Bootstrap	Loading configuration
2023-05-04T21:58:19.433Z	INFO	main	Bootstrap	Initializing logging
2023-05-04T21:58:22.479Z	INFO	main	com.facebook.airlift.jmx.JmxAgent	JMX agent started and listening on test-coordinator-65c8dc94d-bx7cn:33113
2023-05-04T21:58:23.567Z	ERROR	ResourceGroupManager	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Error while executing refreshAndStartQueries
com.facebook.drift.client.UncheckedTTransportException: No hosts available
	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:126)
	at com.sun.proxy.$Proxy131.getResourceGroupInfo(Unknown Source)

...

2023-05-04T21:58:32.857Z	ERROR	ResourceGroupManager	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Error while executing refreshAndStartQueries
com.facebook.drift.client.UncheckedTTransportException: No hosts available
	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:126)
	at com.sun.proxy.$Proxy131.getResourceGroupInfo(Unknown Source)
```

Probably the issue can be partially mitigated (not solved) by adding an initial delay to:
https://github.com/prestodb/presto/blob/cfa39cd8bfb121b203a7581fb54f0da5b36ce9b1/presto-main/src/main/java/com/facebook/presto/execution/resourceGroups/InternalResourceGroupManager.java#L136

`PeriodicTaskExecutor` has necessary constructor:
https://github.com/prestodb/presto/blob/cb6eadc03c47666108947b1b357613a093cb09e3/presto-main/src/main/java/com/facebook/presto/util/PeriodicTaskExecutor.java#L45-L48

What do you think @tdcmeehan?

**Comment by dnskr** [comment]
> if you are running this in k8s with statefulset for the resource manager, try to use dns name instead instead of the default ip seemed to be able to fix the issue.
> 
> ```
>     node.internal-address-source=FQDN
>     node.internal-address=$POD_DNS_WITH_HEADLESSS_SVC
> ```

@fivesheep Could you please elaborate what is `$POD_DNS_WITH_HEADLESSS_SVC`? Am I right that it should be set for resource manager pods only?

**Comment by tdcmeehan** [comment]
Sorry for responding to this late, I didn't come across it.  This usually happens at startup and is effectively noise in the logs.

Noise in the logs is not ideal however, and we can fix it.  I can think of a few ways:

1) As @dnskr suggested, we can simply pause for a bit.  This is not ideal though, because it might be difficult to understand how long to pause for and might be environment dependent.
2) We can differentiate between "startup" and "running" in the `PeriodicTaskExecutor`.  When it starts up, it can be configured to attempt for a configurable time period (say, 1 minute).  It can return a listener which returns after the first successful attempt, which can then be used by the resource manager to block new queries until that future is completed.

There are probably additions to the documentation which are required to make this more clear, any suggestions are welcome.
