### ISSUE TITLE
Pinot Presto number format error on max() function

### ISSUE THREAD

**Issue by dongxiaoman** [prestodb/presto#17755]
If we have a `TIMESTAMP` field in Pinot Table, and run `select max(timestamp_column) from my_table`, Pinot throws the below error:

```
java.lang.IllegalArgumentException: Invalid timestamp: '1.672528152E13'
	at org.apache.pinot.spi.utils.TimestampUtils.toMillisSinceEpoch(TimestampUtils.java:63)
	at com.facebook.presto.pinot.PinotBrokerPageSourceBase.parseTimestamp(PinotBrokerPageSourceBase.java:196)
	at com.facebook.presto.pinot.PinotBrokerPageSourceBase.setValue(PinotBrokerPageSourceBase.java:174)
	at com.facebook.presto.pinot.PinotBrokerPageSourceBase.setValue(PinotBrokerPageSourceBase.java:137)
	at com.facebook.presto.pinot.PinotBrokerPageSourceBase.setRows(PinotBrokerPageSourceBase.java:267)
	at com.facebook.presto.pinot.PinotBrokerPageSourceSql.populateFromQueryResults(PinotBrokerPageSourceSql.java:122)
```

This is because in Pinot right now max() returns double.

**Comment by dongxiaoman** [comment]
cc @xiangfu0
