### ISSUE TITLE
"java.lang.NullPointerException" when query from mysql  

### ISSUE THREAD

**Issue by mjzfrank** [prestodb/presto#17750]
```
presto-server-0.272.1
java version "1.8.0_191"
mysql-connector-java-5.1.48.jar
```

** then i repacle the ```/presto/plugin/mysql```  mysql-connector-java-5.1.48.jar to mysql-connector-java-8.0.27.jar , still got this exception ** 

2022-05-11T14:10:17.777+0800	ERROR	20220511_061017_00005_bh6fr.1.0.0-0-130	com.facebook.presto.operator.Driver    Error closing operator 0 for task 20220511_061017_00005_bh6fr.1.0.0
java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:892)
	at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:171)
	at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6644)
	at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:841)
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.finish(ScanFilterAndProjectOperator.java:193)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.close(ScanFilterAndProjectOperator.java:177)
	at com.facebook.presto.operator.Driver.closeAndDestroyOperators(Driver.java:605)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:458)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:728)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:300)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
	at com.facebook.presto.$gen.Presto_0_272_1_eb8be21____20220511_054824_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rohanpednekar** [comment]
fyi @imjalpreet and @pratyakshsharma

**Comment by pratyakshsharma** [comment]
I guess this is a known issue, which needs to be debugged. @mjzfrank Do you mind raising a jira for this if not done already?

**Comment by mjzfrank** [comment]
@rohanpednekar 
thx, i'll try 0.272 to test
