### ISSUE TITLE
Unable to create injector

### ISSUE THREAD

**Issue by faycal-merouane** [prestodb/presto#17772]
Hello , while trying to launch presto server I'm facing the following issue : 

`1) Configuration property 'connection-password' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2) Configuration property 'connection-user' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'connection-password' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2) Configuration property 'connection-user' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
        at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:138)
        at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:379)
        at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:231)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:223)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:209)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:141)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:81)
`
Thanks four your help.

**Comment by agrawalreetika** [comment]
@faycal-merouane Could you provide the details about the presto version and the catalog properties you are using when you are getting the above error?

**Comment by faycal-merouane** [comment]
hello @agrawalreetika, thx for your reply.
I'm using presto server 0.255 with the following configuration : 

etc/catalog/hive.properties : 

> connector.name=hive-hadoop2
hive.metastore.uri=thrift://hive-server-ip
connection-user=username
connection-password=password

I appreciate your help.

**Comment by agrawalreetika** [comment]
Hi @faycal-merouane, These are not the correct config for configuring the hive catalog in Presto.
These are the minimum configs, you can use in your catalog -

> connector.name=hive-hadoop2
hive.metastore.uri=thrift://example.net:9083

For getting details about other config properties, please refer to this - https://prestodb.io/docs/current/connector/hive.html

**Comment by rohanpednekar** [comment]
@faycal-merouane pls let us know if this issue is good to close or if you still need any help with this issue.

**Comment by pratyakshsharma** [comment]
@faycal-merouane gentle ping!
