### ISSUE TITLE
Presto get 'BoundedExecutor state corrupted due to underlying executor failure' error

### ISSUE THREAD

**Issue by mjzfrank** [prestodb/presto#17810]
`presto-0.277`,
`LOG ERROR` 
```
java.lang.IllegalStateException: BoundedExecutor is in a failed state
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.facebook.airlift.concurrent.BoundedExecutor.execute(BoundedExecutor.java:55)
	at com.google.common.util.concurrent.MoreExecutors$5.execute(MoreExecutors.java:987)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1029)
	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:675)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:105)
	at com.google.common.util.concurrent.AbstractTransformFuture.create(AbstractTransformFuture.java:47)
	at com.google.common.util.concurrent.Futures.transform(Futures.java:495)
	at com.facebook.presto.server.protocol.Query.waitForResults(Query.java:326)
	at com.facebook.presto.server.protocol.QueuedStatementResource$Query.toResponse(QueuedStatementResource.java:500)
	at com.facebook.presto.server.protocol.QueuedStatementResource.lambda$getStatus$2(QueuedStatementResource.java:256)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:205)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:194)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:110)
	at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:992)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

ERROR CODE
```
package io.airlift.concurrent;

import io.airlift.log.Logger;

import javax.annotation.concurrent.ThreadSafe;

import java.util.Queue;
import java.util.concurrent.ConcurrentLinkedQueue;
import java.util.concurrent.Executor;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;

import static com.google.common.base.Preconditions.checkArgument;
import static java.util.Objects.requireNonNull;

/**
 * Guarantees that no more than maxThreads will be used to execute tasks submitted
 * through {@link #execute(Runnable) execute()}.
 * <p>
 * There are a few interesting properties:
 * <ul>
 * <li>Multiple BoundedExecutors over a single coreExecutor will have fair sharing
 * of the coreExecutor threads proportional to their relative maxThread counts, but
 * can use less if not as active.</li>
 * <li>Tasks submitted to a BoundedExecutor is guaranteed to have those tasks
 * handed to threads in that order.</li>
 * <li>Will not encounter starvation</li>
 * </ul>
 */
@ThreadSafe
public class BoundedExecutor
        implements Executor
{
    private static final Logger log = Logger.get(BoundedExecutor.class);

    private final Queue<Runnable> queue = new ConcurrentLinkedQueue<>();
    private final AtomicInteger queueSize = new AtomicInteger(0);
    private final AtomicBoolean failed = new AtomicBoolean();

    private final Executor coreExecutor;
    private final int maxThreads;

    public BoundedExecutor(Executor coreExecutor, int maxThreads)
    {
        requireNonNull(coreExecutor, "coreExecutor is null");
        checkArgument(maxThreads > 0, "maxThreads must be greater than zero");
        this.coreExecutor = coreExecutor;
        this.maxThreads = maxThreads;
    }

    @Override
    public void execute(Runnable task)
    {
        if (failed.get()) {
            throw new RejectedExecutionException("BoundedExecutor is in a failed state");
        }

        queue.add(task);

        int size = queueSize.incrementAndGet();
        if (size <= maxThreads) {
            // If able to grab a permit, then we are short exactly one draining thread
            try {
                coreExecutor.execute(this::drainQueue);
            }
            catch (Throwable e) {
                failed.set(true);
                log.error("BoundedExecutor state corrupted due to underlying executor failure");
                throw e;
            }
        }
    }

    private void drainQueue()
    {
        // INVARIANT: queue has at least one task available when this method is called
        do {
            try {
                queue.poll().run();
            }
            catch (Throwable e) {
                log.error(e, "Task failed");
            }
        }
        while (queueSize.getAndDecrement() > maxThreads);
    }
}
```
--------------
`question`

can't this field ```AtomicBoolean failed ```  return to normal? once it's set true , always throw this exception

**Comment by mjzfrank** [comment]
@rohanpednekar
