### ISSUE TITLE
Crash in lambda resolution

### ISSUE THREAD

**Issue by kaikalur** [prestodb/presto#17923]
Following query crashes in lambda resolution apparently for array_sum. Turning off inline_sql_functions make the bug go away.

Caused by: java.lang.IllegalStateException: lambda expressions map does not contain this lambda definition
	at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at com.facebook.presto.sql.gen.RowExpressionCompiler$Visitor.visitLambda(RowExpressionCompiler.java:268)
	at com.facebook.presto.sql.gen.RowExpressionCompiler$Visitor.visitLambda(RowExpressionCompiler.java:108)
	at com.facebook.presto.spi.relation.LambdaDefinitionExpression.accept(LambdaDefinitionExpression.java:117)

```
WITH tmp AS (
    SELECT
        1 AS id,
        MAP(ARRAY['a', 'b'], ARRAY[3.0, 4.0]) AS hist

    UNION ALL

    SELECT
        2 AS id,
        MAP(ARRAY['b', 'c'], ARRAY[4.0, 5.0]) AS hist
)
SELECT
    ARRAY_SUM(
        MAP_VALUES(
            (MAP_NORMALIZE(hist)
        )
    ))
FROM tmp
```

**Comment by rongrong** [comment]
This seems to work for me:
```
presto:tiny> set session inline_sql_functions = true;
SET SESSION
presto:tiny> WITH tmp AS ( SELECT 1 AS id, MAP(ARRAY['a', 'b'], ARRAY[3.0, 4.0]) AS hist UNION ALL SELECT 2 AS id, MAP(ARRAY['b', 'c'], ARRAY[4.0, 5.0]) AS hist ) SELECT ARRAY_SUM( MAP_VALUES( (MAP_NORMALIZE(hist) ) )) FROM tmp;
 _col0
-------
   1.0
   1.0
(2 rows)

Query 20220628_185959_00005_9b69u, FINISHED, 1 node
http://localhost:8080/ui/query.html?20220628_185959_00005_9b69u
Splits: 14 total, 14 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 20% active
Per Node: 0.1 parallelism,     0 rows/s,     0B/s
Parallelism: 0.1
Peak User Memory: 0B
Peak Total Memory: 352B
Peak Task Total Memory: 352B
S0-driverCountPerTask: sum=14 count=1 min=14 max=14
S0-taskBlockedTimeNanos: sum=49ms count=1 min=49ms max=49ms
S0-taskElapsedTimeNanos: sum=55ms count=1 min=55ms max=55ms
S0-taskQueuedTimeNanos: sum=17ms count=1 min=17ms max=17ms
S0-taskScheduledTimeNanos: sum=53ms count=1 min=53ms max=53ms
fragmentPlanTimeNanos: sum=1ms count=1 min=1ms max=1ms
logicalPlannerTimeNanos: sum=65ms count=1 min=65ms max=65ms
178ms [0 rows, 0B] [0 rows/s, 0B/s]
```
