### ISSUE TITLE
Launching presto-server with Java 18 got an exception like "java.lang.IllegalAccessException: static final field has no write access"

### ISSUE THREAD

**Issue by hongbi1x** [prestodb/presto#17952]
When I launch presto-server v0.273.2 with OpenJDK 18, and got an exception: 
```
Error in custom provider, com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported class file major version 62
```

So I recompile presto by OpenJDK 18 and launch presto-server again. It still got an exception below. And the exception maybe caused by writing value to the finally field CACHE of Hadoop FileSystem by reflection.

Are there any bugs when using OpenJDK 18 to launch presto-server?

```
2022-06-28T13:58:19.538+0800	ERROR	main	com.facebook.presto.server.PrestoServer	java.lang.IllegalAccessException: static final field has no write access: org.apache.hadoop.fs.FileSystem.CACHE/org.apache.hadoop.fs.FileSystem$Cache/putStatic, from class java.lang.Object (module java.base)
java.lang.InternalError: java.lang.IllegalAccessException: static final field has no write access: org.apache.hadoop.fs.FileSystem.CACHE/org.apache.hadoop.fs.FileSystem$Cache/putStatic, from class java.lang.Object (module java.base)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:167)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:176)
	at java.base/java.lang.reflect.Field.acquireOverrideFieldAccessor(Field.java:1184)
	at java.base/java.lang.reflect.Field.getOverrideFieldAccessor(Field.java:1153)
	at java.base/java.lang.reflect.Field.set(Field.java:820)
	at org.apache.hadoop.fs.HadoopExtendedFileSystemCache.setFinalStatic(HadoopExtendedFileSystemCache.java:43)
	at org.apache.hadoop.fs.HadoopExtendedFileSystemCache.initialize(HadoopExtendedFileSystemCache.java:29)
	at com.facebook.presto.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:35)
	at com.facebook.presto.hive.HdfsEnvironment$$FastClassByGuice$$a9f55374.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
	at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:138)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:379)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:231)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:223)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:209)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:150)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)
Caused by: java.lang.IllegalAccessException: static final field has no write access: org.apache.hadoop.fs.FileSystem.CACHE/org.apache.hadoop.fs.FileSystem$Cache/putStatic, from class java.lang.Object (module java.base)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:955)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectField(MethodHandles.java:3494)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflectSetter(MethodHandles.java:3485)
	at java.base/java.lang.invoke.MethodHandleImpl$1.unreflectField(MethodHandleImpl.java:1637)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(MethodHandleAccessorFactory.java:145)
	... 52 more
```

**Comment by lucagiac81** [comment]
We observed the same issue, and we found it's related to [JEP 416](https://openjdk.org/jeps/416). As mentioned in the JEP, it's possible to use the old implementation with -Djdk.reflect.useDirectMethodHandle=false. Following that suggestion, we were able to launch Presto with JDK 18.

**Comment by pratyakshsharma** [comment]
@hongbi1x Were you able to solve your issue using the suggestion above?
