### ISSUE TITLE
[BUG] When MOR table has log file

### ISSUE THREAD

**Issue by choucmei** [prestodb/presto#17973]
# ERROR STACK
```
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: Query failed (#20220704_095340_00000_avry9): No value present in Option
	at com.facebook.presto.jdbc.TestPrestoDriverT.main(TestPrestoDriverT.java:89)
Caused by: java.sql.SQLException: Query failed (#20220704_095340_00000_avry9): No value present in Option
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1821)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1760)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.google.common.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1311)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1327)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:146)
	at com.facebook.presto.jdbc.TestPrestoDriverT.getHudi(TestPrestoDriverT.java:96)
	at com.facebook.presto.jdbc.TestPrestoDriverT.main(TestPrestoDriverT.java:87)
Caused by: java.util.NoSuchElementException: No value present in Option
	at org.apache.hudi.common.util.Option.get(Option.java:89)
	at com.facebook.presto.hudi.HudiSplitManager.createHudiSplit(HudiSplitManager.java:149)
	at com.facebook.presto.hudi.HudiSplitManager.lambda$getSplits$1(HudiSplitManager.java:125)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.facebook.presto.hudi.HudiSplitManager.getSplits(HudiSplitManager.java:126)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:41)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:89)
	at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:52)
	at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:156)
	at com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
	at com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:281)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:353)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:242)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:171)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:537)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:386)
	at com.facebook.presto.$gen.Presto_null__testversion____20220704_095201_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:266)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by pratyakshsharma** [comment]
Closing this since the PR is already merged.
