### ISSUE TITLE
Presto query Hudi returned Exception: The column of table is declared as type string, but the Parquet file declares the column as type INT64

### ISSUE THREAD

**Issue by Archie-selfless** [prestodb/presto#18249]
### Overview
I tried to verify the process using Kafka Connector ingesting data from Oracle with Debezium, and put the data into Hudi table with spark. Everything seems right but when I attempt query Hudi data by Presto, I got a Exception as follow:
```java
java.sql.SQLException: Query failed (#20220829_023856_00009_2usdj): The column u_no of table default.hudi_table1 is declared as type string, but the Parquet file (cosn://bigdata-1252394470/hudi/cdc/mysql/mytable1/id=1/6e993b81-f1de-4688-8b1e-a963769f42a7-0_1-57-2436_20220826165303859.parquet) declares the column as type INT64 
  at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841) 
  at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1821) 
  at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1760) 
  at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141) 
  at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136) 
  at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42) 
  at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1311) 
  at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1327) 
  at com.facebook.presto.jdbc.LengthLimitedIterator.hasNext(LengthLimitedIterator.java:42) 
  at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:146) in RemoteResultSetImpl.getObjects(RemoteResultSetImpl.java:1342) 
Caused by: com.facebook.presto.jdbc.internal.client.FailureInfo$FailureException: com.facebook.presto.spi.PrestoException: The column u_no of table default.hudi_table1 is declared as type string, but the Parquet file (cosn://bigdata-1252394470/hudi/cdc/mysql/mytable1/id=1/6e993b81-f1de-4688-8b1e-a963769f42a7-0_1-57-2436_20220826165303859.parquet) declares the column as type INT64 
  at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.getParquetType(ParquetPageSourceFactory.java:450) 
  at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.getColumnType(ParquetPageSourceFactory.java:551) 
  at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.lambda$createParquetPageSource$3(ParquetPageSourceFactory.java:266) 
  at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) 
  at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) 
  at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) 
  at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) 
  at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479) at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:270) 
  at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:196) 
  at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:452) 
  at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:187) 
  at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63) 
  at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80) at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:261) 
  at com.facebook.presto.operator.Driver.processInternal(Driver.java:426) at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309) 
  at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730) 
  at com.facebook.presto.operator.Driver.processFor(Driver.java:302) at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079) 
  at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:166) at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599) 
  at com.facebook.presto.$gen.Presto_0_275_f3f1035____20220828_164959_1.run(Unknown Source) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
```

As Presto Server loged above, I inspected the Parquet file in my Tencent COS. However the type of the column `u_no` is **string** rather than **INT64** (although its value shows like a integer, e.g. '1001','1002'...), it confused me a day, so I came here for help.

> Since Presto seems to have misconverted to INT64 when reading Hudi timestamp fields in the past, I guess some of the parsing process in the current version may be defective. 😄 

### Version

- Hudi - 0.12.0
- Presto - 0.275
- Spark - 3.2.2(scala2.12.5)

**Comment by Archie-selfless** [comment]
Resolved! Exception encountered because I set the `hoodie.datasource.write.recordkey.field` and `hoodie.datasource.write.partitionpath.field` with the same key.

**Comment by Archie-selfless** [comment]
Resolved! Exception encountered because I set the `hoodie.datasource.write.recordkey.field` and `hoodie.datasource.write.partitionpath.field` with the same key.
