### ISSUE TITLE
IndexOutOfBoundsException while querying Hudi MOR table

### ISSUE THREAD

**Issue by Sarfaraz-214** [prestodb/presto#18306]
We saw an issue while querying over MOR Hudi table via new Presto-Hudi connector. My table is hive-style partitioned.

**Query** : `select * from hudi.hudi_local_db.core_job_mor where last_updated=date('2022-04-21') limit 5;`

**Error** : `java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at com.facebook.presto.hudi.HudiRecordCursors.getHudiBaseFile(HudiRecordCursors.java:165)
	at com.facebook.presto.hudi.HudiRecordCursors.createRealtimeRecordCursor(HudiRecordCursors.java:73)
	at com.facebook.presto.hudi.HudiPageSourceProvider.createPageSource(HudiPageSourceProvider.java:127)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:261)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:426)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:302)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:166)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
	at com.facebook.presto.$gen.Presto_0_275_f3f1035____20220907_123910_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

Screenshot of data and server debug logs are attached.

[presto-hudi-log.txt](https://github.com/prestodb/presto/files/9508665/presto-hudi-log.txt)

<img width="722" alt="Screenshot 2022-09-07 at 8 40 40 PM" src="https://user-images.githubusercontent.com/113046370/188950122-46865268-0257-410d-b9ee-450623a3d105.png">

**Comment by Sarfaraz-214** [comment]
@codope Please check!

**Comment by codope** [comment]
@Sarfaraz-214 I think this should be resolved by #18222 
I just queried a Hudi MOR table with log files using presto-hudi master and it succeeded.

**Comment by Sarfaraz-214** [comment]
Thanks @codope 
@7c00 Will this fix be available in the next 0.277 version?

**Comment by codope** [comment]
yes it should be taken into the next release. i'll keep an eye.

**Comment by Sarfaraz-214** [comment]
@codope @7c00 I tried to execute the above with the 0.277 version. The reported issue is resolved, but however I am now facing issue mentioned here - #18302
