### ISSUE TITLE
Invalid partition value for Hudi table

### ISSUE THREAD

**Issue by Sarfaraz-214** [prestodb/presto#18302]
We saw an issue while querying over Hudi table via new Presto-Hudi connector. My table is hive-style partitioned and this happens for both COW and MOR tables.

**Query** : `select * from hudi.hudi_local_db.core_job_cow where last_updated=date('2022-04-21') limit 5;`

**Error** : `Query 20220907_150634_00003_4vg5x failed: Invalid partition value '2022-04-21' for date partition key: last_updated
com.facebook.presto.spi.PrestoException: Invalid partition value '2022-04-21' for date partition key: last_updated
        at com.facebook.presto.hudi.HudiPageSource.deserializePartitionValue(HudiPageSource.java:242)
        at com.facebook.presto.hudi.HudiPageSource.<init>(HudiPageSource.java:88)
        at com.facebook.presto.hudi.HudiPageSourceProvider.createPageSource(HudiPageSourceProvider.java:148)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:248)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:426)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:302)`
        
  Screenshot of data is attached.
<img width="722" alt="Screenshot 2022-09-07 at 8 40 40 PM" src="https://user-images.githubusercontent.com/113046370/188922845-7edb8e99-4997-4210-90d3-343cbc976da8.png">

**Comment by codope** [comment]
@7c00 Can you please take a look? It seems like the code expects a long value for date type fields. But here we see string in date format. 
https://github.com/prestodb/presto/blob/master/presto-hudi/src/main/java/com/facebook/presto/hudi/HudiPageSource.java#L222

**Comment by 7c00** [comment]
It's a bug. Let me fix that.

**Comment by Sarfaraz-214** [comment]
@7c00 Will this fix be available in the next 0.277 version?
