### ISSUE TITLE
TestHiveQueriesUsingThrift.testCreateTableAsSelect failed to rename tmp folder

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#18437]
https://github.com/prestodb/presto/pull/18420 fixes the "tmp table already exists" error (https://github.com/prestodb/presto/issues/18382) But the test still fails because of the tmp directory was not removed.

Error message: 
Unable to rename from file:/tmp/presto-hive/558f62ee-e3e2-48bf-b198-f698bf0780ce to file:/tmp/hive_data/tpch/tmp: target directory already exists

```
Error:  Tests run: 36, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 173.277 s <<< FAILURE! - in com.facebook.presto.nativeworker.TestHiveQueriesUsingThrift
Error:  com.facebook.presto.nativeworker.TestHiveQueriesUsingThrift.testCreateTableAsSelect  Time elapsed: 0.472 s  <<< FAILURE!
java.lang.RuntimeException: Unable to rename from file:/tmp/presto-hive/558f62ee-e3e2-48bf-b198-f698bf0780ce to file:/tmp/hive_data/tpch/tmp: target directory already exists
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:726)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:694)
	at com.facebook.presto.nativeworker.TestHiveQueries.testCreateTableAsSelect(TestHiveQueries.java:578)
	at com.facebook.presto.nativeworker.TestHiveQueriesUsingThrift.testCreateTableAsSelect(TestHiveQueriesUsingThrift.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.facebook.presto.spi.PrestoException: Unable to rename from file:/tmp/presto-hive/558f62ee-e3e2-48bf-b198-f698bf0780ce to file:/tmp/hive_data/tpch/tmp: target directory already exists
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.renameDirectory(SemiTransactionalHiveMetastore.java:2176)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.access$2700(SemiTransactionalHiveMetastore.java:114)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.prepareAddTable(SemiTransactionalHiveMetastore.java:1306)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$300(SemiTransactionalHiveMetastore.java:1244)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1124)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1060)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:3810)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:232)
	at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:719)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	... 3 more
```

**Comment by yingsu00** [comment]
cc @majetideepak

**Comment by majetideepak** [comment]
@yingsu00 thanks for reporting this. I will take a look.

**Comment by mbasmanova** [comment]
CC: @spershin @mshang816 @amitkdutta @tanjialiang

**Comment by majetideepak** [comment]
thanks @amitkdutta
