### ISSUE TITLE
NoClassDefFoundError: Could not initialize class com.facebook.presto.hive.s3.PrestoS3StorageClass

### ISSUE THREAD

**Issue by marvel-007** [prestodb/presto#18476]
The presto iceberg connector can normally read and write data when connecting to s3 using the hive catalog, but it can be started when the hadoop catalog is changed, but the query is reported as ClassNotFoundException: Class org.apache.hadoop.fs.s3a S3AFileSystem is not found. 
Then transfer the hadoop-aws and aws-java-sdk bundle under Hadoop-3.2.1 to plugin/iceberg, and start the message: NoClassDefFoundError: Could not initialize class com.facebook. presto. hive. s3. PrestoS3StorageClass. What is the problem? Missing bags? 

Detailed exception log：
2022-10-12T10:39:32.193+0800    INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Added catalog jmx using connector jmx --
2022-10-12T10:39:32.194+0800    INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Loading catalog properties etc/catalog/hive.properties --
2022-10-12T10:39:32.194+0800    INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Loading catalog hive --
2022-10-12T10:39:33.392+0800    WARN    main    org.apache.hadoop.util.NativeCodeLoader Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2022-10-12T10:39:33.494+0800    INFO    main    org.apache.hadoop.io.compress.bzip2.Bzip2Factory        Successfully loaded & initialized native-bzip2 library system-native
2022-10-12T10:39:33.497+0800    INFO    main    org.apache.hadoop.io.compress.zlib.ZlibFactory  Successfully loaded & initialized native-zlib library
2022-10-12T10:39:34.505+0800    INFO    main    com.facebook.airlift.bootstrap.LifeCycleManager Life cycle starting...
2022-10-12T10:39:34.506+0800    INFO    main    com.facebook.airlift.bootstrap.LifeCycleManager Life cycle startup complete. System ready.
2022-10-12T10:39:34.517+0800    INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Added catalog hive using connector hive-hadoop2 --
2022-10-12T10:39:34.517+0800    INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Loading catalog properties etc/catalog/iceberg.properties --
2022-10-12T10:39:34.517+0800    INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Loading catalog iceberg --
2022-10-12T10:39:35.338+0800    ERROR   main    com.facebook.presto.server.PrestoServer Guice configuration errors:

1) Error: Error creating instance of configuration class [com.facebook.presto.hive.s3.HiveS3Config]

1 error
com.google.inject.ConfigurationException: Guice configuration errors:

1) Error: Error creating instance of configuration class [com.facebook.presto.hive.s3.HiveS3Config]

1 error
        at com.facebook.airlift.configuration.Problems.getException(Problems.java:127)
        at com.facebook.airlift.configuration.Problems.exceptionFor(Problems.java:141)
        at com.facebook.airlift.configuration.ConfigurationFactory.newInstance(ConfigurationFactory.java:439)
        at com.facebook.airlift.configuration.ConfigurationFactory.getDefaultConfig(ConfigurationFactory.java:284)
        at com.facebook.airlift.configuration.ConfigurationInspector$ConfigRecord.<init>(ConfigurationInspector.java:85)
        at com.facebook.airlift.configuration.ConfigurationInspector$ConfigRecord.<init>(ConfigurationInspector.java:66)
        at com.facebook.airlift.configuration.ConfigurationInspector.inspect(ConfigurationInspector.java:38)
        at com.facebook.airlift.bootstrap.Bootstrap.makePrinterForConfiguration(Bootstrap.java:289)
        at com.facebook.airlift.bootstrap.Bootstrap.logConfiguration(Bootstrap.java:266)
        at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:222)
        at com.facebook.presto.iceberg.InternalIcebergConnectorFactory.createConnector(InternalIcebergConnectorFactory.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.facebook.presto.iceberg.IcebergConnectorFactory.create(IcebergConnectorFactory.java:49)
        at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:388)
        at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:235)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:227)
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:213)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
        at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:150)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.facebook.presto.hive.s3.PrestoS3StorageClass
        at com.facebook.presto.hive.s3.HiveS3Config.<init>(HiveS3Config.java:38)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.facebook.airlift.configuration.ConfigurationFactory.newInstance(ConfigurationFactory.java:433)
        ... 23 more

**Comment by rohanpednekar** [comment]
@marvel-007 What you mean by, when you say this - can you pls provide a bit more info about your use case. 

> but it can be started when the hadoop catalog is changed, but the query is reported as

@majetideepak  @imjalpreet Do you guys think you can help here?

**Comment by marvel-007** [comment]
> @marvel-007 What you mean by, when you say this - can you pls provide a bit more info about your use case.
> 
> > but it can be started when the hadoop catalog is changed, but the query is reported as
> 
> @majetideepak @imjalpreet Do you guys think you can help here?

My usage scenario is to used flink write the iceberg data to the s3 minio storage through the hadoop catalog, and then I want to query the iceberg data through presto's iceberg connector using hadoop catalog as well. I configure it according to the access document, and the above error occurs
