### ISSUE TITLE
High CPU usage during writing operations.

### ISSUE THREAD

**Issue by GonCuesMa** [prestodb/presto#18505]
Hi

I am suffering high CPU usage on all worker nodes when running INSERTs or CREATEs operations. The problem is that this causes service outages that make some queries fail, and sometimes, the UI is unresponsive.

![Screenshot-20221017134524-1181x780](https://user-images.githubusercontent.com/61585305/196237749-002d520c-c4b3-47f2-8620-78f0fecebb9f.png)

This issue usually happens when I execute concurrently pipelines that run those INSERTs/CREATEs. Here are the WARNING/ERROR logs that typically appear when this occurs.

```
2022-10-16T07:14:38.263Z	WARN	ContinuousTaskStatusFetcher-20221016_060516_01318_yvdg7.1.0.4-142088	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221016_060516_01318_yvdg7.1.0.4: http://172.17.85.60:8889/v1/task/20221016_060516_01318_yvdg7.1.0.4
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.17.85.60:8889/v1/task/20221016_060516_01318_yvdg7.1.0.4/status
	at com.facebook.presto.server.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:57)
	at com.facebook.presto.server.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

...

2022-10-16T07:14:56.143Z	ERROR	Announcer-1	com.facebook.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 17.86s

...

2022-10-16T07:14:56.144Z	WARN	ContinuousTaskStatusFetcher-20221016_071420_01460_yvdg7.1.0.4-142012	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221016_071420_01460_yvdg7.1.0.4: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.17.85.43:8889/v1/task/20221016_071420_01460_yvdg7.1.0.4

...

2022-10-16T07:16:38.474Z	WARN	TaskInfoFetcher-20221016_060516_01318_yvdg7.1.0.1-142150	com.facebook.presto.server.RequestErrorTracker	Error getting info for task 20221016_060516_01318_yvdg7.1.0.1: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.17.85.54:8889/v1/task/20221016_060516_01318_yvdg7.1.0.1
```

CPU utilization:

![image](https://user-images.githubusercontent.com/61585305/196238980-1f4c569e-01e5-4ad8-848a-6c724f11c2ac.png)

Since it only happens in writing operations, I suppose it is related to writer threads, but I could not find the key. I have been playing around with properties like `task.max-worker-threads` or `task.max-partial-aggregation-memory`, but I could not find the key.

Could you please help me to find a way to control the CPU usage on worker nodes?

Thanks a lot.

PD: The catalog is Hive (S3)
PD2: The target tables are partitioned and bucketed.

**Comment by GonCuesMa** [comment]
Hi @rohanpednekar @prabha-cloud, thanks for your reply.

More info about the issue:


The Presto server becomes temporarily unresponsive when we see the following logs on the coordinator node:
```
2022-10-16T07:14:38.263Z	WARN	ContinuousTaskStatusFetcher-20221016_060516_01318_yvdg7.1.0.4-142088	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221016_060516_01318_yvdg7.1.0.4: http://172.17.85.60:8889/v1/task/20221016_060516_01318_yvdg7.1.0.4
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.17.85.60:8889/v1/task/20221016_060516_01318_yvdg7.1.0.4/status
	at com.facebook.presto.server.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:57)
	at com.facebook.presto.server.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:30)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```


That occurs when there are INSERT/CREATE operations over partitioned and bucketed tables.

For example, if we execute the following statement at 2022-10-25T13:54:01.608Z:
```
CREATE TABLE hive.test_schema.test_table_D with
             (
                          format = 'ORC',
                          bucketed_by = array ['user_id'],
                          bucket_count = 60
             )
               AS
SELECT   d.day AS date_dt,
         d.user_id,
         min(d.start_dt) AS first_ts,
         max(d.end_dt)   AS last_ts
FROM     (
                SELECT day,
                       user_id,
                       start_dt,
                       end_dt
                FROM   hive.prod.test
                WHERE  day BETWEEN date '2022-05-06' AND    date '2022-09-10' - INTERVAL '1' day ) AS d
JOIN     hive.test_schema.test_table_C                                          AS u
ON       d.user_id = u.user_id
GROUP BY d.day,
         d.user_id;
```

The server starts having intermittent communication problems after approximately 20 seconds (2022-10-25T13:54:19.718Z)
```
2022-10-25T13:54:19.718Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.1.0.2-240	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.1.0.2: http://172.19.24.84:8889/v1/task/20221025_135401_00008_qy64p.1.0.2
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.19.24.84:8889/v1/task/20221025_135401_00008_qy64p.1.0.2/status
2022-10-25T13:54:19.912Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.1.0.1-230	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.1.0.1: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.1.0.1
2022-10-25T13:54:20.145Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.2.0.1-246	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.2.0.1: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.2.0.1
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.2.0.1/status
2022-10-25T13:54:26.082Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.1.0.2-253	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.1.0.2: http://172.19.24.84:8889/v1/task/20221025_135401_00008_qy64p.1.0.2
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.19.24.84:8889/v1/task/20221025_135401_00008_qy64p.1.0.2/status
2022-10-25T13:54:26.123Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.2.0.0-247	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.2.0.0: http://172.19.24.84:8889/v1/task/20221025_135401_00008_qy64p.2.0.0
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.19.24.84:8889/v1/task/20221025_135401_00008_qy64p.2.0.0/status
2022-10-25T13:54:26.385Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.1.0.1-230	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.1.0.1: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.1.0.1
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.1.0.1/status
2022-10-25T13:54:26.386Z	WARN	ContinuousTaskStatusFetcher-20221025_135401_00008_qy64p.2.0.1-230	com.facebook.presto.server.RequestErrorTracker	Error getting task status 20221025_135401_00008_qy64p.2.0.1: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.2.0.1
com.facebook.presto.server.ServiceUnavailableException: Server returned SERVICE_UNAVAILABLE: http://172.19.24.85:8889/v1/task/20221025_135401_00008_qy64p.2.0.1/status
2022-10-25T13:55:16.832Z	INFO	Task-20221025_135401_00008_qy64p.0.0.0-261	SplitCompletedLog	20221025_135401_00008_qy64p:::20221025_135401_00008_qy64p.0:::0
```

I can limit CPU usage on worker nodes by lowering the `task.max-worker-threads` and `task.min-drivers` config properties, but these communication errors still happen.

Here are the config files:

**MASTERs**

_jvm.config_
```
-verbose:class
-server
-Xmx36G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+AggressiveOpts
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=150M
-Xbootclasspath/p:
-Djava.library.path=/usr/lib/hadoop/lib/native/:/usr/lib/hadoop-lzo/lib/native/:/usr/lib/
-XX:+PrintAdaptiveSizePolicy
-XX:+PrintJNIGCStalls
-XX:+PrintReferenceGC
-XX:+PrintGCCause
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintGCApplicationConcurrentTime
-XX:+PrintGCApplicationStoppedTime
-Xloggc:/var/log/presto/garbage-collection.log
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=4
-XX:GCLogFileSize=4M
-Dcom.sun.management.jmxremote.host=localhost
-Djava.rmi.server.hostname=localhost
```

_config.properties_
```
coordinator=true
node-scheduler.include-coordinator=false
discovery.uri=http://ip.region.compute.internal:8889
http-server.threads.max=500
discovery-server.enabled=true
sink.max-buffer-size=1GB
query.max-memory=300GB
query.max-memory-per-node=28GB
query.max-total-memory-per-node=28GB
query.max-history=40
query.min-expire-age=30m
query.client.timeout=30m
query.stage-count-warning-threshold=100
query.max-stage-count=150
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
graceful-shutdown-timeout = 0s
jmx.rmiregistry.port = 9080
jmx.rmiserver.port = 9081
node-manager.http-client.max-content-length = 64MB
http-server.https.enabled = true
experimental.reserved-pool-enabled = false
query.low-memory-killer.policy = total-reservation-on-blocked-nodes
http-server.https.keystore.path = /var/lib/presto/xxxxxx.jks
http-server.https.port = 8888
http-server.authentication.type = PASSWORD
http-server.https.keystore.key = xxxxxxx
exchange.http-client.max-content-length = 64MB
memory.heap-headroom-per-node=8GB
```

**SLAVEs**

_jvm.config_
```
verbose:class
-server
-Xmx100G
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+AggressiveOpts
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=150M
-Xbootclasspath/p:
-Djava.library.path=/usr/lib/hadoop/lib/native/:/usr/lib/hadoop-lzo/lib/native/:/usr/lib/
-XX:+PrintAdaptiveSizePolicy
-XX:+PrintJNIGCStalls
-XX:+PrintReferenceGC
-XX:+PrintGCCause
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintGCApplicationConcurrentTime
-XX:+PrintGCApplicationStoppedTime
-Xloggc:/var/log/presto/garbage-collection.log
-XX:+UseGCLogFileRotation
-XX:NumberOfGCLogFiles=4
-XX:GCLogFileSize=4M
-Dcom.sun.management.jmxremote.host=localhost
-Djava.rmi.server.hostname=localhost
-XX:MaxMetaspaceSize=250M
```

_config.properties_
```
coordinator=false
node-scheduler.include-coordinator=false
discovery.uri=http://ip-172-17-65-116.eu-west-1.compute.internal:8889
http-server.threads.max=500
sink.max-buffer-size=1GB
query.max-memory=300GB
query.max-memory-per-node=50GB
query.max-total-memory-per-node=50GB
query.max-history=40
query.min-expire-age=30m
query.client.timeout=30m
query.stage-count-warning-threshold=100
query.max-stage-count=150
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
graceful-shutdown-timeout = 0s
jmx.rmiregistry.port = 9080
jmx.rmiserver.port = 9081
node-manager.http-client.max-content-length = 64MB
http-server.https.enabled = true
experimental.reserved-pool-enabled = false
query.low-memory-killer.policy = total-reservation-on-blocked-nodes
http-server.https.keystore.path = /var/lib/presto/xxxxxxx.jks
http-server.https.port = 8888
http-server.authentication.type = PASSWORD
http-server.https.keystore.key = xxxxxxxx
exchange.http-client.max-content-length = 64MB
memory.heap-headroom-per-node=30GB
```

Hardware specs:
- **MASTERs**: 8 vCore, 64 GiB memory, 300 SSD GB storage
- **SLAVEs**: 48 vCore, 185 GiB memory, 768 GiB EBS storage

Thanks again.

**Comment by GonCuesMa** [comment]
We resolved the issue by upgrading the JDK version from 8 to 11.
