### ISSUE TITLE
Error on rescaling

### ISSUE THREAD

**Issue by damiencarol** [prestodb/presto#1853]
1) Enable experimental syntax
2) Create rescaled table

    2014-10-23T12:25:10.148+0200     WARN   http-worker-112 com.facebook.presto.server.ThrowableMapper      Request failed for /v1/task/20141023_102509_00002_jxenx.1.0
    java.lang.IllegalArgumentException: Fragment is partitioned, but no partitioned driver found
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-18.0.jar:na]
            at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:173) ~[presto-main-0.80-SNAPSHOT.jar:0.80-SNAPSHOT]
            at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:109) ~[presto-main-0.80-SNAPSHOT.jar:0.80-SNAPSHOT]
            at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:96) ~[presto-main-0.80-SNAPSHOT.jar:0.80-SNAPSHOT]
            at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:219) ~[presto-main-0.80-SNAPSHOT.jar:0.80-SNAPSHOT]
            at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:223) ~[presto-main-0.80-SNAPSHOT.jar:0.80-SNAPSHOT]
            at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:104) ~[presto-main-0.80-SNAPSHOT.jar:0.80-SNAPSHOT]

Not sure if it's new since Guava was upgraded.

**Comment by cberner** [comment]
Seems to work now. Please re-open, if you're still seeing this!

**Comment by damiencarol** [comment]
ok
