### ISSUE TITLE
Hudi/Hive Connector Error: 'No FileSystem for scheme: s3' in diffrent versions

### ISSUE THREAD

**Issue by Archie-selfless** [prestodb/presto#18542]
# Precondition
I use Presto-0.275 with Hudi/Hive Connector based on S3 protocol and everyting goes well, but the Error: `No FileSystem for scheme: s3` occured when I switched to the release-0.277.

# Exploration
I noticed the PR: #18441 has committed to fix the Hive Connector. So will this next release version fix the problem about Hudi Connector as well?

# Expectation
Querying Hudi MOR-table by Hudi/Hive Connector and both support S3 protocol.

# Error Note
Querying Hudi MOR-table via Hive metastore in two version server and the result:
- In **Presto-0.275**, Hudi Connector(_ro/_rt) ✅ , Hive Connctor(_ro/_rt) ✅ 
- In **Presto-0.278-SNAPSHOT**(after #18441 fixed code), Hudi Connector(_ro) ✅ , others ❌ 

```
org.apache.hudi.exception.HoodieIOException: Failed to get instance of org.apache.hadoop.fs.FileSystem
	at org.apache.hudi.common.fs.FSUtils.getFs(FSUtils.java:109)
	at org.apache.hudi.common.table.HoodieTableMetaClient.getFs(HoodieTableMetaClient.java:294)
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:127)
	at org.apache.hudi.common.table.HoodieTableMetaClient.newMetaClient(HoodieTableMetaClient.java:641)
	at org.apache.hudi.common.table.HoodieTableMetaClient.access$000(HoodieTableMetaClient.java:80)
	at org.apache.hudi.common.table.HoodieTableMetaClient$Builder.build(HoodieTableMetaClient.java:710)
	at com.facebook.presto.hudi.HudiSplitManager.getSplits(HudiSplitManager.java:111)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:41)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:89)
	at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:52)
	at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:156)
	at com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
	at com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:281)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:353)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:242)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:171)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:557)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:405)
	at com.facebook.presto.$gen.Presto_0_278_SNAPSHOT_3e1cacd____20221021_041253_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:286)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: No FileSystem for scheme: s3
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:144)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:103)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:62)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.hudi.common.fs.FSUtils.getFs(FSUtils.java:107)
	... 27 more
```

**Comment by pratyakshsharma** [comment]
@Archie-selfless 

Please check https://github.com/prestodb/presto/pull/18354. PR is raised for fixing your issue already. I will be reviewing it later this week.

**Comment by Archie-selfless** [comment]
@pratyakshsharma OK, I have solved the core production problem by using the code in PR #18354 and looking forward code merge.

**Comment by pratyakshsharma** [comment]
Glad that you were unblocked.
