### ISSUE TITLE
An error is reported when connecting to the hive metastore，java.net.SocketException: Bad file descriptor (Write failed)

### ISSUE THREAD

**Issue by 8dukongjian** [prestodb/presto#18551]
I use mac OS, start the hive metastore on mac OS, execute "SHOW TABLES FROM hive.default;" and report an error

`java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
	at org.apache.thrift.transport.TSocket.close(TSocket.java:235)
	at com.facebook.presto.hive.metastore.thrift.Transport$TTransportWrapper.close(Transport.java:146)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastoreClient.close(ThriftHiveMetastoreClient.java:82)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getMetastoreClientThenCall(ThriftHiveMetastore.java:1139)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.lambda$getAllDatabases$5(ThriftHiveMetastore.java:289)
	at com.facebook.presto.hive.metastore.thrift.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:48)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:139)
	at com.facebook.presto.hive.metastore.thrift.ThriftHiveMetastore.getAllDatabases(ThriftHiveMetastore.java:288)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getAllDatabases(BridgingHiveMetastore.java:91)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadAllDatabases(CachingHiveMetastore.java:364)`

**Comment by prestored** [comment]
Can you confirm if you are able to Hive metastore outside Presto. For example using DBeaver/Sql workbench and run queries?

**Comment by 8dukongjian** [comment]
> Can you confirm if you are able to Hive metastore outside Presto. For example using DBeaver/Sql workbench and run queries?

Yes, I can successfully connect to the hive-metastore service using the Hive-metastore API(org.apache.hive). 
In addition, I found that I can occasionally connect to the local Hive metastore service through presto, but in most cases, the above error will be reported.

**Comment by 8dukongjian** [comment]
This is a screenshot of one of my sql execution, very few cases can query successfully, the vast majority will fail.

![image](https://user-images.githubusercontent.com/31331967/198181456-c0f986d4-ffa6-4a2e-b136-8d061e1611d8.png)

**Comment by pratyakshsharma** [comment]
@8dukongjian Are you still facing this issue? If so, can you confirm the presto version you are using and if you are using an M1 mac?
