### ISSUE TITLE
TPC-DS presto sqls issues on Athena.

### ISSUE THREAD

**Issue by MisterWJC** [prestodb/presto#18628]
There are issues and solutions when testing on Athena(version2 and 3):
[Src code](https://github.com/prestodb/presto/tree/master/presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds)

```
q05:
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 33:* Cannot check if varchar is BETWEEN date and date
	at aws.example.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:161)
	at aws.example.athena.StartQueryExample.main(StartQueryExample.java:91)

Solution: Need to cast varchar to date.

q16.sql
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 10:17: Cannot check if varchar is BETWEEN date and date
	at aws.example.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:161)
	at aws.example.athena.StartQueryExample.main(StartQueryExample.java:91)

q21:
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 18:21: Cannot check if varchar is BETWEEN date and date
	at aws.example.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:161)
	at aws.example.athena.StartQueryExample.main(StartQueryExample.java:91)
Solution: Need to cast varchar to date.

q32:
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 8:18: Cannot check if varchar is BETWEEN date and date
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)

q30:
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 28:3: Column 'c_last_review_date_sk' cannot be resolved
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
    
Solution: c_last_review_date_sk change to c_last_review_date

q58:
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 19:29: '=' cannot be applied to varchar, date
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
Solution: Need to cast varchar to date.

q72.sql:
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 23:40: '+' cannot be applied to varchar, interval day to second
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
Solution: Need to cast varchar to date.

q77.sql
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 12:21: Cannot check if varchar is BETWEEN date and date
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
Solution: Need to cast varchar to date.

q83.sql
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 19:30: IN value and list items must be the same type: varchar
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
Solution: Need to cast varchar to date.

q92.sql
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 8:18: Cannot check if varchar is BETWEEN date and date
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
Solution: Need to cast varchar to date.

q94.sql
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 10:17: Cannot check if varchar is BETWEEN date and date
	at aws.adevinta.tpcds.athena.AthenaQueryDriver.waitForQueryToComplete(AthenaQueryDriver.java:172)
	at aws.adevinta.tpcds.athena.AthenaQueryDriver.execute_Athena_Query(AthenaQueryDriver.java:72)
	at aws.adevinta.tpcds.athena.AthenaQueryDriver.main(AthenaQueryDriver.java:35)
Solution: Need to cast varchar to date.

q95.sql 
java.lang.RuntimeException: The Amazon Athena query failed to run with error message: SYNTAX_ERROR: line 10:17: Cannot check if varchar is BETWEEN date and date
	at aws.adevinta.tpcds.athena.StartQueryExample.waitForQueryToComplete(StartQueryExample.java:157)
	at aws.adevinta.tpcds.athena.StartQueryExample.main(StartQueryExample.java:79)
Solution: Need to cast varchar to date.
```

**Comment by rohanpednekar** [comment]
@pettyjamesm Hope all is well. Do you think you can help here? Thanks!

**Comment by pettyjamesm** [comment]
@MisterWJC - can you indicate how you created the schemas you're trying to run the TPCDS queries against? These errors seem to be related to a partition columns being declared as `VARCHAR` and attempting to query them as if the tables were partitioned on `date`. For example, in query 94.sql the offending operation is: 
```
WHERE ("d_date" BETWEEN CAST('1999-2-01' AS DATE) AND (CAST('1999-2-01' AS DATE) + INTERVAL  '60' DAY))
```
which reports an error:
```
Cannot check if varchar is BETWEEN date and date
```
meaning d_date is declared as varchar in the table schema.

**Comment by MisterWJC** [comment]
@pettyjamesm Thank you for the reminder! I was using the official version of ddl to create the schemas, which led to this issue, which has been solved by manually modifying the corresponding queries.
