### ISSUE TITLE
Getting Error reading from alluxio://<host>:19998/<path_to_parquet_file> at position xxxxxxx

### ISSUE THREAD

**Issue by harsh9898** [prestodb/presto#18998]
Presto version : 0.268
Presto JDBC version: 0.268
Presto coordinator: 1, workers: 4
Data Source: Alluxio
File format: parquet
Tools used for query in presto: DBeaver, presto CLI

When I am trying run the query with DBeaver, it's giving the following error :
**_com.facebook.presto.spi.PrestoException: Error reading from alluxio://<host>:19998/<path_to_parquet_file> at position xxxxxxx_**

Important Notes:

- The data size for parquet files is large. 
- Getting this error only for the directories where the data size is large ( 2 GB per one parquet file and about 200 similar-sized parquet files under the directory)
- This error is a random error when it's trying to read all parquet files stored under Alluxio. It's failing on some of the files randomly on a daily basis

Please help me with this as it's a critical error for me, I tried a lot of configurations and solutions but I am still not able to figure out why it's failing

If someone figured out to resolve this then Please help with this one. Let me know if more information is needed.

**Comment by harsh9898** [comment]
Below is the full error stack trace:

**com.facebook.presto.spi.PrestoException: Error reading from alluxio://<host_name>:19998/<path_to_parquet_file> at position
<xxxxxxxxxxxx>**
at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:66)
at com.facebook.presto.parquet.AbstractParquetDataSource.readFully(AbstractParquetDataSource.java:60)
at com.facebook.presto.parquet.AbstractParquetDataSource.readFully(AbstractParquetDataSource.java:51)
at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:247)
at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:330)
at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:313)
at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:193)
at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:171)
at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:298)
at com.facebook.presto.common.block.LazyBlock.getLoadedBlock(LazyBlock.java:289)
at com.facebook.presto.operator.ScanFilterAndProjectOperator$RecordingLazyBlockLoader.load(ScanFilterAndProjectOperator.java:320)
at com.facebook.presto.operator.ScanFilterAndProjectOperator$RecordingLazyBlockLoader.load(ScanFilterAndProjectOperator.java:306)
at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:298)
at com.facebook.presto.common.block.LazyBlock.getLoadedBlock(LazyBlock.java:289)
at com.facebook.presto.operator.project.InputPageProjection.project(InputPageProjection.java:69)
at com.facebook.presto.operator.project.PageProjectionWithOutputs.project(PageProjectionWithOutputs.java:56)
at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.processBatch(PageProcessor.java:327)
at com.facebook.presto.operator.project.PageProcessor$ProjectSelectedPositions.process(PageProcessor.java:201)
at com.facebook.presto.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:315)
at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:79)
at com.facebook.presto.operator.WorkProcessorUtils$YieldingIterator.computeNext(WorkProcessorUtils.java:65)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
at com.facebook.presto.operator.project.MergingPageOutput.getOutput(MergingPageOutput.java:128)
at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:301)
at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:245)
at com.facebook.presto.operator.Driver.processInternal(Driver.java:424)
at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:728)
at com.facebook.presto.operator.Driver.processFor(Driver.java:300)
at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
at com.facebook.presto.$gen.Presto_0_268_03318e7____20230201_140638_1.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalStateException: No data is read before EOF
at alluxio.shaded.client.com.google.common.base.Preconditions.checkState(Preconditions.java:508)
at alluxio.client.file.AlluxioFileInStream.positionedReadInternal(AlluxioFileInStream.java:269)
at alluxio.client.file.AlluxioFileInStream.positionedRead(AlluxioFileInStream.java:237)
at alluxio.hadoop.HdfsFileInputStream.read(HdfsFileInputStream.java:154)
at alluxio.hadoop.HdfsFileInputStream.readFully(HdfsFileInputStream.java:171)
at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:58)
... 36 more

**Comment by tdcmeehan** [comment]
CC: @beinan
