### ISSUE TITLE
hudi table error using hudi Connector select s3 table(Same table, hive connector can be selected)

### ISSUE THREAD

**Issue by zhangzhaohuazai** [prestodb/presto#19059]
I am just testing presto 0.279 with a Hudi connector for s3 table and getting this exception:
```
presto:users_cdc3> select count(*) from mysql_cdc_sync_hive_03_ro;
Query 20230215_045038_00001_9ceff failed: Could not check if s3a://flinkcdc/mysqlcdc_sync_hudi03 is a valid table
org.apache.hudi.exception.HoodieIOException: Could not check if s3a://flinkcdc/mysqlcdc_sync_hudi03 is a valid table
	at org.apache.hudi.exception.TableNotFoundException.checkTableValidity(TableNotFoundException.java:59)
	at org.apache.hudi.common.table.HoodieTableMetaClient.<init>(HoodieTableMetaClient.java:128)
	at org.apache.hudi.common.table.HoodieTableMetaClient.newMetaClient(HoodieTableMetaClient.java:641)
	at org.apache.hudi.common.table.HoodieTableMetaClient.access$000(HoodieTableMetaClient.java:80)
	at org.apache.hudi.common.table.HoodieTableMetaClient$Builder.build(HoodieTableMetaClient.java:710)
	at com.facebook.presto.hudi.HudiSplitManager.getSplits(HudiSplitManager.java:111)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:41)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:89)
	at com.facebook.presto.split.CloseableSplitSourceProvider.getSplits(CloseableSplitSourceProvider.java:52)
	at com.facebook.presto.sql.planner.SplitSourceFactory$Visitor.lambda$visitTableScan$0(SplitSourceFactory.java:157)
	at com.facebook.presto.sql.planner.LazySplitSource.getDelegate(LazySplitSource.java:96)
	at com.facebook.presto.sql.planner.LazySplitSource.getConnectorId(LazySplitSource.java:48)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:281)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:243)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:221)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:167)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:354)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:243)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:172)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:593)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:441)
	at com.facebook.presto.$gen.Presto_0_279_686ef1d____20230215_044938_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:306)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.facebook.presto.hive.s3.PrestoS3FileSystem.UnrecoverableS3OperationException: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: FG2078KZ2KG4P7PJ; S3 Extended Request ID: fl/owCcU90+V/zzqtpjiRuQXf0I2Z/OCwEWReqa1EZXTN5hKQYcj0gMR5wIdf3tccO7P3VADV94=), S3 Extended Request ID: fl/owCcU90+V/zzqtpjiRuQXf0I2Z/OCwEWReqa1EZXTN5hKQYcj0gMR5wIdf3tccO7P3VADV94= (Path: s3a://flinkcdc/mysqlcdc_sync_hudi03/.hoodie)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.lambda$getS3ObjectMetadata$5(PrestoS3FileSystem.java:683)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:139)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.getS3ObjectMetadata(PrestoS3FileSystem.java:670)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.getS3ObjectMetadata(PrestoS3FileSystem.java:654)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.getFileStatus(PrestoS3FileSystem.java:359)
	at org.apache.hadoop.fs.HadoopExtendedFileSystem.getFileStatus(HadoopExtendedFileSystem.java:388)
	at org.apache.hudi.common.fs.HoodieWrapperFileSystem.lambda$getFileStatus$17(HoodieWrapperFileSystem.java:402)
	at org.apache.hudi.common.fs.HoodieWrapperFileSystem.executeFuncWithTimeMetrics(HoodieWrapperFileSystem.java:106)
	at org.apache.hudi.common.fs.HoodieWrapperFileSystem.getFileStatus(HoodieWrapperFileSystem.java:396)
	at org.apache.hudi.exception.TableNotFoundException.checkTableValidity(TableNotFoundException.java:51)
	... 26 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: FG2078KZ2KG4P7PJ; S3 Extended Request ID: fl/owCcU90+V/zzqtpjiRuQXf0I2Z/OCwEWReqa1EZXTN5hKQYcj0gMR5wIdf3tccO7P3VADV94=)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1381)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1335)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1309)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem.lambda$getS3ObjectMetadata$5(PrestoS3FileSystem.java:673)
	... 35 more
```

**Comment by zhangzhaohuazai** [comment]
When I try Hive connector,for the same table, hive connector can be selected correctly.
My Version:hudi:0.12.1;hive:3.12;hadoop:3.2.4;flink:1.14.5
My hudi.properties:
```
connector.name=hudi
hive.metastore.uri=thrift://xx.xx.xx.xx:9083
```

**Comment by pratyakshsharma** [comment]
Hi @zhangzhaohuazai can you please share your hive connector catalog properties file as well?

**Comment by imjalpreet** [comment]
@zhangzhaohuazai You need to configure AWS access keys or IAM role in the Hudi catalog file as well in the same way you must have configured for the hive connector.

**Comment by tdcmeehan** [comment]
Please reopen if this is still an issue.  Thanks!
