### ISSUE TITLE
If we enable parquet dereference pushdown, the query will fail in some scenarios

### ISSUE THREAD

**Issue by 397090770** [prestodb/presto#19198]
I have a table with the following structure
```
 CREATE TABLE hive.default.ad_test (
    id integer,
    action_info row(process_time bigint, request_type varchar, request_count integer)
 )
 WITH (
    format = 'PARQUET'
 )
```
The data in the table are as follows:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/5170878/225563234-000b6b46-acc1-423a-8daf-6d661534d865.png">
If I hadn't enabled parquet dereference pushdown, the following query would have worked:
```
select action_info.process_time from ad_test;
```
<img width="633" alt="image" src="https://user-images.githubusercontent.com/5170878/225563500-f19e8f89-1ad2-4811-a266-34041e695b49.png">

When I enabled parquet dereference pushdown, the query reported an error:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/5170878/225563709-096d6613-0297-4b85-8179-4f399cc13933.png">

The coordinator reported the following exception
```
2023-03-16T16:49:47.442+0800	WARN	dispatcher-query-15	com.facebook.presto.server.ThrowableMapper	Request failed for /v1/statement/queued/20230316_084946_00009_uuz9z/2
com.fasterxml.jackson.databind.JsonMappingException: position is not valid: 0 (through reference chain: com.facebook.presto.client.QueryResults["data"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:729)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1433)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:921)
	at com.facebook.airlift.jaxrs.JsonMapper.writeTo(JsonMapper.java:177)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:266)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:251)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:109)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:85)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:163)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1135)
	at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:662)
	at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:395)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:385)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:884)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:916)
	at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:872)
	at com.facebook.airlift.http.server.AsyncResponseHandler$1.onSuccess(AsyncResponseHandler.java:102)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1058)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: position is not valid: 0
	at com.facebook.presto.common.block.RunLengthEncodedBlock.checkReadablePosition(RunLengthEncodedBlock.java:344)
	at com.facebook.presto.common.block.RunLengthEncodedBlock.isNull(RunLengthEncodedBlock.java:314)
	at com.facebook.presto.common.type.BigintType.getObjectValue(BigintType.java:34)
	at com.facebook.presto.server.protocol.RowIterable$RowIterator.computeNext(RowIterable.java:77)
	at com.facebook.presto.server.protocol.RowIterable$RowIterator.computeNext(RowIterable.java:50)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1323)
	at com.google.common.collect.Iterators$1.hasNext(Iterators.java:136)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serializeContents(IterableSerializer.java:83)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:74)
	at com.fasterxml.jackson.databind.ser.std.IterableSerializer.serialize(IterableSerializer.java:12)
	at com.fasterxml.jackson.databind.ser.std.StdDelegatingSerializer.serialize(StdDelegatingSerializer.java:168)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:721)
	... 31 more
```
I checked the cause of the exception and found that it was caused when action_info was NULL.

**Comment by jaystarshot** [comment]
I think we should mark this for depreciation since presto c++ doesn't support this but only supports the pushdown subfields optimizer
