### ISSUE TITLE
When we enable internal communication TLS and custom AUTH  together presto is failing

### ISSUE THREAD

**Issue by skairali** [prestodb/presto#19235]
0.279   is the presto version

config as follows
```
coordinator=true
discovery-server.enabled=true
discovery.uri=https://<<COORDINATOR HOSTNAME>>:8480
**http-server.authentication.type=PASSWORD**
http-server.http.enabled=false
**http-server.https.enabled=true**
http-server.https.keystore.key=KEYSTOREPASSWORD
http-server.https.keystore.path=/opt/presto/presto-keystore.jks
http-server.https.port=8480
internal-communication.https.keystore.key=KEYSTOREPASSWORD
internal-communication.https.keystore.path=/opt/presto/presto-keystore.jks
internal-communication.https.required=true
node-scheduler.include-coordinator=false
query.max-concurrent-queries=15
query.max-memory=8GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
task.concurrency=16
```

Points to be noted

1. When its HTTP internal communication and  AUTH working fine.
2. without AUTH, https is working fine for internal communication

Coordinator traces

```
2023-03-16T17:45:03.047Z	ERROR	Announcer-0	com.facebook.airlift.discovery.client.Announcer	Service announcement failed after 4.02ms. Next request will happen within 1000.00ms
2023-03-16T17:45:03.828Z	DEBUG	Discovery-2	com.facebook.airlift.discovery.client.CachingServiceSelector	Cannot connect to discovery server for refresh (collector/general)
com.facebook.airlift.discovery.client.DiscoveryException: Lookup of collector failed with status code 401
	at com.facebook.airlift.discovery.client.HttpDiscoveryLookupClient$1.handle(HttpDiscoveryLookupClient.java:140)
	at com.facebook.airlift.discovery.client.HttpDiscoveryLookupClient$1.handle(HttpDiscoveryLookupClient.java:128)
	at com.facebook.airlift.http.client.jetty.JettyResponseFuture.processResponse(JettyResponseFuture.java:101)
	at com.facebook.airlift.http.client.jetty.JettyResponseFuture.completed(JettyResponseFuture.java:78)
	at com.facebook.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:90)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
	at org.eclipse.jetty.client.ResponseNotifier.forwardSuccessComplete(ResponseNotifier.java:222)
	at org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener.forwardSuccessComplete(AuthenticationProtocolHandler.java:264)
	at org.eclipse.jetty.client.AuthenticationProtocolHandler$AuthenticationListener.onComplete(AuthenticationProtocolHandler.java:185)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:470)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:416)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:316)
	at org.eclipse.jetty.http.HttpParser.handleContentMessage(HttpParser.java:599)
	at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1669)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1517)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:172)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:135)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
```

Worker config

```
coordinator=false

discovery.uri=https://coordinator:8480/

http-server.authentication.type=PASSWORD

http-server.http.enabled=false
http-server.https.enabled=true

http-server.https.keystore.key=PASSORD
http-server.https.keystore.path=/opt/presto/presto-keystore.jks

http-server.https.port=8480
internal-communication.https.required=true
internal-communication.https.keystore.key=PASSORD
internal-communication.https.keystore.path=/opt/presto/presto-keystore.jks

query.max-concurrent-queries=15
query.max-memory=8GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
task.concurrency=16
```

Tried all the combinations based on https://prestodb.io/docs/current/security/internal-communication.html#internal-ssl-tls-configuration

Unable to get Presto co ordinator up and running

**Comment by imjalpreet** [comment]
I have been able to reproduce this in my local environment with the below minimal configs. The coordinator and workers are not able to communicate with the discovery server if Password Auth is enabled along with secure internal communication which results in 401 Unauthorised errors. We are looking into the root cause(and a fix) and will update you here when we have more information.

Coordinator config
```
coordinator=true
node-scheduler.include-coordinator=false
query.max-memory=50GB
query.max-memory-per-node=1GB
query.max-total-memory-per-node=2GB
discovery-server.enabled=true
discovery.uri=https://localhost:8443
presto.version=testversion
http-server.http.enabled=false
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/Users/imjalpreet/IdeaProjects/presto/presto-main/etc/keystore.jks
http-server.https.keystore.key=password
internal-communication.https.required=true
internal-communication.https.keystore.path=/Users/imjalpreet/IdeaProjects/presto/presto-main/etc/keystore.jks
internal-communication.https.keystore.key=password
http-server.authentication.type=PASSWORD
```

Worker config
```
presto.version=testversion
coordinator=false
node-scheduler.include-coordinator=false
node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
node.environment=production
node.internal-address=localhost
discovery.uri=https://localhost:8443
http-server.http.enabled=false
http-server.https.enabled=true
http-server.https.port=8444
http-server.https.keystore.path=/path/to/keystore.jks
http-server.https.keystore.key=password
internal-communication.https.required=true
internal-communication.https.keystore.path=/path/to/keystore.jks
internal-communication.https.keystore.key=password
```

**Comment by imjalpreet** [comment]
@skairali On further investigation, the current implementation of secure internal communication does not support any kind of password authentication(Basic File Based or LDAP). For now, you'll need to keep discovery and other internal communication on HTTP. 

We will be looking into changing that since internal communication shouldn't use the external security mechanism (LDAP/Basic Auth is for users running queries, not machine-to-machine). Currently, internal communication is supported with Kerberos, but really should have been implemented in a different way.

**Comment by skairali** [comment]
@imjalpreet   Could please use this issue to update the progress... Keep to know the progress and support you in testing as well

**Comment by yzhang1991** [comment]
Hi @skairali, we have some hot customer escalations this week so the team is kind of busy at the moment. We will prioritize this in another week. Thanks!
