### ISSUE TITLE
I configured allow-truncate table, but an error was reported during startup

### ISSUE THREAD

**Issue by 2370131441** [prestodb/presto#19299]
Configuration property 'allow-truncate-table' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'allow-truncate-table' was not used
  at com.facebook.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:244)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:143)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)

**Comment by agrawalreetika** [comment]
Hi @2370131441, 
There is no explicit configuration for truncating the table in Presto which is why you are getting this error.
Please remove it from your config and retry.
Which hive security option option are you using?

**Comment by 2370131441** [comment]
> Hi @2370131441, There is no explicit configuration for truncating the table in Presto which is why you are getting this error. Please remove it from your config and retry. Which hive security option option are you using?

I want to truncate the table in presto. What configuration should I add to the configuration file?

**Comment by agrawalreetika** [comment]
I was able to reproduce the issue. I will raise a PR to fix this. Thanks for reporting
