### ISSUE TITLE
select queries failed，MultiChannelGroupByHash::channelBuilders is empty

### ISSUE THREAD

**Issue by z-bb** [prestodb/presto#19321]
sql:
```
presto:default> SELECT
             ->   null
             -> FROM
             ->   (
             ->     SELECT
             ->       count(1)
             ->     FROM
             ->       (
             ->         SELECT
             ->           year
             ->         FROM
             ->           bigdata_admin.hive_audit
             ->         WHERE
             ->           year = '2023'
             ->         GROUP BY
             ->           year
             ->       ) AS aaa
             ->     limit
             ->       10
             ->   ) tmp;

Query 20230404_072044_00076_c2qf5, FAILED, 1 node
Splits: 65 total, 7 done (10.77%)
240ms [0 rows, 0B] [0 rows/s, 0B/s]
```
log:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
        at com.facebook.presto.operator.MultiChannelGroupByHash.addNewGroup(MultiChannelGroupByHash.java:329)
        at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:312)
        at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:289)
        at com.facebook.presto.operator.MultiChannelGroupByHash.access$200(MultiChannelGroupByHash.java:54)
        at com.facebook.presto.operator.MultiChannelGroupByHash$GetRunLengthEncodedGroupIdsWork.process(MultiChannelGroupByHash.java:843)
        at com.facebook.presto.operator.DistinctLimitOperator.processUnfinishedWork(DistinctLimitOperator.java:215)
        at com.facebook.presto.operator.DistinctLimitOperator.addInput(DistinctLimitOperator.java:172)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:434)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:307)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:728)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:300)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
        at com.facebook.presto.$gen.Presto_0_272_010_c59f4bc__0_272____20230403_013059_1.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

explain:
![clipboard_image_1680592953743](https://user-images.githubusercontent.com/35120306/229719577-eef4918f-c9c1-41a4-9b9b-f194498d69a9.png)

**Comment by z-bb** [comment]
@rongrong help
