### ISSUE TITLE
[Presto-on-Spark Native] Join query fails with Multiple entries with same key: orderkey=9 and orderkey=0

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#19399]
A join query that returns duplicate column names fails:

```
SELECT * FROM orders o, lineitem l WHERE o.orderkey = l.orderkey;

Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: orderkey=9 and orderkey=0
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayoutFromOutputVariables(LocalExecutionPlanner.java:886)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$CustomPlanTranslator.makeLayout(LocalExecutionPlanner.java:875)
	at com.facebook.presto.spark.execution.operator.NativeExecutionOperator$NativeExecutionOperatorTranslator.translate(NativeExecutionOperator.java:408)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitPlan(LocalExecutionPlanner.java:3123)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitPlan(LocalExecutionPlanner.java:900)
```

The "duplicate" column is "orderkey" present in both lineitem and orders.

CC: @rschlussel @miaoever @shrinidhijoshi

**Comment by mbasmanova** [comment]
The plan for this query includes an OutputNode that has "duplicate" entries in OutputNode::getOutputVariables()

```
    Output layout: [orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment, orderkey, partkey, suppkey, linenumber, quantity, extendedprice, discount, tax, returnflag, linestatus, shipdate, commitdate, receiptdate, shipinstruct, shipmode, comment_1, is_open, is_returned, tax_as_real, discount_as_real, linenumber_as_smallint, linenumber_as_tinyint]
    Output partitioning: SINGLE []
    Stage Execution Strategy: UNGROUPED_EXECUTION
    - Output[orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment, orderkey, partkey, suppkey, linenumber, quantity, extendedprice, discount, tax, returnflag, linestatus, shipdate, commitdate, receiptdate, shipinstruct, shipmode, comment, is_open, is_returned, tax_as_real, discount_as_real, linenumber_as_smallint, linenumber_as_tinyint] => [orderkey:bigint, custkey:bigint, orderstatus:varchar(1), totalprice:double, orderdate:varchar, orderpriority:varchar(15), clerk:varchar(15), shippriority:integer, comment:varchar(79), orderkey:bigint, partkey:bigint, suppkey:bigint, linenumber:integer, quantity:double, extendedprice:double, discount:double, tax:double, returnflag:varchar(1), linestatus:varchar(1), shipdate:varchar, commitdate:varchar, receiptdate:varchar, shipinstruct:varchar(25), shipmode:varchar(10), comment_1:varchar(44), is_open:boolean, is_returned:boolean, tax_as_real:real, discount_as_real:real, linenumber_as_smallint:smallint, linenumber_as_tinyint:tinyint]
            Estimates: {rows: 1 (341B), cpu: 4180.66, memory: 139.90, network: 927.00}
            comment := comment_1 (1:1)
        - InnerJoin[("orderkey_0" = "orderkey")] => [partkey:bigint, suppkey:bigint, linenumber:integer, quantity:double, extendedprice:double, discount:double, tax:double, returnflag:varchar(1), linestatus:varchar(1), shipdate:varchar, commitdate:varchar, receiptdate:varchar, shipinstruct:varchar(25), shipmode:varchar(10), comment_1:varchar(44), is_open:boolean, is_returned:boolean, tax_as_real:real, discount_as_real:real, linenumber_as_smallint:smallint, linenumber_as_tinyint:tinyint, orderkey:bigint, custkey:bigint, orderstatus:varchar(1), totalprice:double, orderdate:varchar, orderpriority:varchar(15), clerk:varchar(15), shippriority:integer, comment:varchar(79)]
                Distribution: PARTITIONED
            - RemoteSource[1] => [orderkey_0:bigint, partkey:bigint, suppkey:bigint, linenumber:integer, quantity:double, extendedprice:double, discount:double, tax:double, returnflag:varchar(1), linestatus:varchar(1), shipdate:varchar, commitdate:varchar, receiptdate:varchar, shipinstruct:varchar(25), shipmode:varchar(10), comment_1:varchar(44), is_open:boolean, is_returned:boolean, tax_as_real:real, discount_as_real:real, linenumber_as_smallint:smallint, linenumber_as_tinyint:tinyint]
            - LocalExchange[HASH] (orderkey) => [orderkey:bigint, custkey:bigint, orderstatus:varchar(1), totalprice:double, orderdate:varchar, orderpriority:varchar(15), clerk:varchar(15), shippriority:integer, comment:varchar(79)]
                - RemoteSource[2] => [orderkey:bigint, custkey:bigint, orderstatus:varchar(1), totalprice:double, orderdate:varchar, orderpriority:varchar(15), clerk:varchar(15), shippriority:integer, comment:varchar(79)]
```

When planning all-Java query, we do not translate OutputNode to an operator, but rather use custom logic in com.facebook.presto.sql.planner.LocalExecutionPlanner#createOutputPartitioning which allows for producing duplicate columns.

```
        @Override
        public PhysicalOperation visitOutput(OutputNode node, LocalExecutionPlanContext context)
        {
            return node.getSource().accept(this, context);
        }
```

**Comment by mbasmanova** [comment]
One solution might be to remove duplicate output columns when wrapping OutputNode in NativeExecutionNode.
