### ISSUE TITLE
Error: External table location can not be inside the system metadata directory

### ISSUE THREAD

**Issue by r-priyam** [prestodb/presto#19584]
In my `/opt/presto-server/etc/catalog/s3.properties`, I have these values (and running from local PC):
```
connector.name=hive-hadoop2
hive.metastore=file
hive.metastore.catalog.dir=s3://priyam/
hive.metastore.user=cox
hive.compression-codec=LZ4
hive.recursive-directories=true
hive.non-managed-table-writes-enabled=true
hive.max-partitions-per-writers=1000
hive.allow-drop-table=true
hive.s3.path-style-access=true
hive.s3select-pushdown.enabled=true
hive.s3.use-instance-credentials=false
```

When I run - `CREATE SCHEMA abc;`: It successfully creates schema. But then when I run -
`CREATE TABLE abc.xyz (id BIGINT) WITH ( external_location = 's3://priyam/test/', format = 'PARQUET' );`
It throws this -
```
Query 20230506_200613_00033_3s5bt failed: External table location can not be inside the system metadata directory
com.facebook.presto.spi.PrestoException: External table location can not be inside the system metadata directory
        at com.facebook.presto.hive.metastore.file.FileHiveMetastore.createTable(FileHiveMetastore.java:265)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.createTable(CachingHiveMetastore.java:553)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.createTable(CachingHiveMetastore.java:553)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$CreateTableOperation.run(SemiTransactionalHiveMetastore.java:2761)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeAddTableOperations(SemiTransactionalHiveMetastore.java:1626)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$1000(SemiTransactionalHiveMetastore.java:1282)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1217)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1098)
        at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:3823)
        at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:232)
        at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:720)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```
`test` directory exists in the bucket but it's failing. Can someone please help?

**Comment by r-priyam** [comment]
It was `hive.metastore.catalog` path conflict, but when I pointed it to this - `hive.metastore.catalog.dir=s3://priyam/catalog/` now I am getting `Query 20230506_203701_00002_d8upa failed: URI scheme is not "file"` while running the same CREATE TABLE command

**Comment by tdcmeehan** [comment]
@r-priyam can you share the whole stack trace?

**Comment by r-priyam** [comment]
Hi @tdcmeehan, Thank you for getting back. Sure, please find it below:

```
java.lang.IllegalArgumentException: URI scheme is not "file"
        at java.base/java.io.File.<init>(File.java:423)
        at com.facebook.presto.hive.metastore.file.FileHiveMetastore.createTable(FileHiveMetastore.java:277)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.createTable(CachingHiveMetastore.java:553)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.createTable(CachingHiveMetastore.java:553)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$CreateTableOperation.run(SemiTransactionalHiveMetastore.java:2761)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeAddTableOperations(SemiTransactionalHiveMetastore.java:1626)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore$Committer.access$1000(SemiTransactionalHiveMetastore.java:1282)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1217)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1098)
        at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:3823)
        at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:232)
        at com.facebook.presto.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(InMemoryTransactionManager.java:720)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
        at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by nmahadevuni** [comment]
Currently, FileHiveMetastore needs external location for tables to be on local file storage. It fails at
`File location = new File(new Path(table.getStorage().getLocation()).toUri());`
This needs a fix.
