### ISSUE TITLE
As long as you use presto to write the string in the table, querying in Spark SQL will result in an error

### ISSUE THREAD

**Issue by shiwl** [prestodb/presto#19705]
presto version : 0.278
environment : presto on iceberg - hdfs
description : 
As long as you use presto to write the string in the table, querying in Spark SQL will result in an error:
Caused by: java.lang.ClassCastException: [B cannot be cast to org.apache.spark.unsafe.types.UTF8String
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String(rows.scala:46)
	at org.apache.spark.sql.catalyst.expressions.BaseGenericInternalRow.getUTF8String$(rows.scala:46)
	at org.apache.spark.sql.catalyst.expressions.GenericInternalRow.getUTF8String(rows.scala:195)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:349)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I couldn't find any way to set the encoding format for writing characters in presto,
please help me

**Comment by imjalpreet** [comment]
@shiwl This issue has been fixed by #19542 
It should be available in the next release 0.282. You can try to cherry-pick and try in your build and let us know if you are still facing any issue.

**Comment by shiwl** [comment]
> @shiwl This issue has been fixed by #19542 It should be available in the next release 0.282. You can try to cherry-pick and try in your build and let us know if you are still facing any issue.

Thank you very much. When will the 0.282 version be updated

**Comment by shiwl** [comment]
Thank you very much. When will the 0.282 version be updated

**Comment by shiwl** [comment]
@imjalpreet Thank you very much. When will the 0.282 version be updated
