### ISSUE TITLE
[Native] Support and add e2e tests for analyze stats

### ISSUE THREAD

**Issue by majetideepak** [prestodb/presto#19922]
We implemented the Presto function in Velox https://github.com/facebookincubator/velox/issues/874
We need to test support and add e2e tests.

**Comment by karteekmurthys** [comment]
Added a PR https://github.com/prestodb/presto/pull/20028

**Comment by karteekmurthys** [comment]
There seems to be an aggregate function missing required by analyze command:
```
Caused by: java.lang.RuntimeException:  Aggregate function not registered: presto.default.$internal$max_data_size_for_stats
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:733)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:701)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:175)
	... 19 more
```
When I test basic table with a single integer column, analyze works fine on native cluster but if the table has a varchar column, analyze command fails. Looks like I need to create a table with multiple column types like Dates, Varchars, Ints, floats and decimals.
```
presto:kart> insert into t1 values(1),(2),(3),(4);
INSERT: 4 rows
presto:kart> analyze t1;
ANALYZE: 4 rows


presto:kart> insert into t2 values('a'),('b');
INSERT: 2 rows

Query 20230630_042753_00018_2h47r, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
[Latency: client-side: 0:01, server-side: 0:01] [0 rows, 0B] [0 rows/s, 0B/s]

presto:kart> analyze t2;
Query 20230630_042758_00019_2h47r failed:  Aggregate function not registered: presto.default.$internal$max_data_size_for_stats
```
Missing Aggregate functions in velox required for Analyze sql command:
1. max_data_size_for_stats --> this is defined but not working. Need to triage. Opened an issue https://github.com/facebookincubator/velox/issues/5484
2. sum_data_size_for_stats. Opened issue here https://github.com/facebookincubator/velox/issues/5485

<img width="679" alt="Screenshot 2023-06-30 at 12 01 44 PM" src="https://github.com/prestodb/presto/assets/6971561/b8260421-9692-4a75-ba40-d5f113dc9807">
