### ISSUE TITLE
Query Iceberg Hadoop Catalog 

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#19920]
I am trying to use `hadoop` catalog via presto-iceberg connector, and using below catalog configuration -

```
connector.name=iceberg
iceberg.catalog.type=hadoop
iceberg.catalog.warehouse=hdfs://example.com:8020/warehouse
```

But I am hitting below error while Presto server start -
```
2023-06-21T18:35:34.740+0530	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error: Invalid configuration property hive.metastore.uri: may not be null (for class com.facebook.presto.hive.metastore.thrift.StaticMetastoreConfig.metastoreUris)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Invalid configuration property hive.metastore.uri: may not be null (for class com.facebook.presto.hive.metastore.thrift.StaticMetastoreConfig.metastoreUris)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
	at com.facebook.presto.iceberg.InternalIcebergConnectorFactory.createConnector(InternalIcebergConnectorFactory.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.facebook.presto.iceberg.IcebergConnectorFactory.create(IcebergConnectorFactory.java:49)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:388)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:235)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:227)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:213)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:123)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:98)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:80)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:151)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:86)
```

Presto server is not starting without metastore uri in the catalog configuration.

As per my understanding, the Hadoop catalog doesn't necessarily rely on metastore for metadata https://github.com/prestodb/presto/blob/master/presto-iceberg/src/main/java/com/facebook/presto/iceberg/IcebergMetadataFactory.java#L58 

Shouldn't this configuration check be avoided when using the Hadoop catalog in Iceberg Connector?

**Comment by agrawalreetika** [comment]
To use the Hadoop catalog with the Iceberg table, it requires the ``hive.metastore.uri`` property, even though it doesn't rely on metastore for metadata when using Hadoop Catalog. As a workaround, you can provide a placeholder for `hive.metastore.uri`` property (**Ex -** hive.metastore.uri=thrift://localhost:9083) in the Iceberg catalog to use Hadoop Catalog until this is fixed.

**Comment by tdcmeehan** [comment]
@agrawalreetika can you create an issue on making the `hive.metastore.uri` field optional if one uses the Hadoop catalog?

**Comment by agrawalreetika** [comment]
Sure here - https://github.com/prestodb/presto/issues/20579

**Comment by agrawalreetika** [comment]
This is resolved as part of https://github.com/prestodb/presto/pull/20912
