### ISSUE TITLE
MergeJoinNode does not have a Graphviz visitor

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#19943]
Seeing these stacktraces when running e2e native tests:

https://app.circleci.com/pipelines/github/prestodb/presto/4065/workflows/242dd6cb-d620-4ee3-ae6e-21992e91d8e2/jobs/7904

```
2023-06-22T07:23:17.632-0600	WARN	dispatcher-query-3	com.facebook.presto.event.QueryMonitor	Error creating graphviz plan for query 20230622_132317_00026_6r4ym: java.lang.UnsupportedOperationException: Node com.facebook.presto.sql.planner.plan.MergeJoinNode does not have a Graphviz visitor
java.lang.UnsupportedOperationException: Node com.facebook.presto.sql.planner.plan.MergeJoinNode does not have a Graphviz visitor
	at com.facebook.presto.util.GraphvizPrinter$NodePrinter.visitPlan(GraphvizPrinter.java:267)
	at com.facebook.presto.util.GraphvizPrinter$NodePrinter.visitPlan(GraphvizPrinter.java:245)
	at com.facebook.presto.sql.planner.plan.InternalPlanVisitor.visitMergeJoin(InternalPlanVisitor.java:67)
	at com.facebook.presto.sql.planner.plan.MergeJoinNode.accept(MergeJoinNode.java:157)
	at com.facebook.presto.sql.planner.plan.InternalPlanNode.accept(InternalPlanNode.java:36)
	at com.facebook.presto.util.GraphvizPrinter$NodePrinter.visitAggregation(GraphvizPrinter.java:408)
	at com.facebook.presto.util.GraphvizPrinter$NodePrinter.visitAggregation(GraphvizPrinter.java:245)
	at com.facebook.presto.spi.plan.AggregationNode.accept(AggregationNode.java:233)
	at com.facebook.presto.util.GraphvizPrinter.printFragmentNodes(GraphvizPrinter.java:239)
	at com.facebook.presto.util.GraphvizPrinter.printDistributedFromFragments(GraphvizPrinter.java:202)
	at com.facebook.presto.sql.planner.planPrinter.PlanPrinter.graphvizDistributedPlan(PlanPrinter.java:457)
	at com.facebook.presto.event.QueryMonitor.createGraphvizQueryPlan(QueryMonitor.java:432)
	at com.facebook.presto.event.QueryMonitor.createQueryMetadata(QueryMonitor.java:283)
	at com.facebook.presto.event.QueryMonitor.queryCompletedEvent(QueryMonitor.java:240)
	at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$5(SqlQueryManager.java:294)
	at com.facebook.presto.execution.QueryStateMachine.lambda$addQueryInfoStateChangeListener$18(QueryStateMachine.java:964)
	at com.facebook.presto.execution.StateMachine.fireStateChangedListener(StateMachine.java:229)
	at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

```

CC: @majetideepak @rschlussel

**Comment by mbasmanova** [comment]
CC: @amitkdutta @vermapratyush
