### ISSUE TITLE
[native] Decimal not getting wrapped in java type

### ISSUE THREAD

**Issue by vermapratyush** [prestodb/presto#19999]
For native workload, decimal values are not getting wrapped in a java type. Following tests fail with the exception:
Test:
```
TestPrestoSparkExpressionCompiler.smokedTest
TestPrestoSparkExpressionCompiler.testSimpleCase
TestPrestoSparkExpressionCompiler.testUnaryOperators
TestPrestoSparkExpressionCompiler.testBinaryOperatorsDecimalBigint
TestPrestoSparkExpressionCompiler.testBinaryOperatorsDecimalInteger
TestPrestoSparkExpressionCompiler.testBinaryOperatorsDecimalDouble
```

```
Caused by: java.lang.IllegalArgumentException: Object '9.0' does not match type long
	at com.facebook.presto.common.Utils.nativeValueToBlock(Utils.java:33)
	at com.facebook.presto.operator.scalar.FunctionAssertions.interpret(FunctionAssertions.java:947)
	at com.facebook.presto.operator.scalar.FunctionAssertions.executeProjectionWithAll(FunctionAssertions.java:637)
	at com.facebook.presto.operator.scalar.FunctionAssertions.selectUniqueValue(FunctionAssertions.java:335)
	at com.facebook.presto.operator.scalar.FunctionAssertions.selectSingleValue(FunctionAssertions.java:330)
	at com.facebook.presto.operator.scalar.FunctionAssertions.assertFunction(FunctionAssertions.java:258)
	at com.facebook.presto.sql.gen.TestExpressionCompiler$AssertExecuteTask.run(TestExpressionCompiler.java:1950)
	... 31 more
```

**Comment by majetideepak** [comment]
@karteekmurthys Do you want to take a look at this issue?
