### ISSUE TITLE
CTAS to iceberg catalog (format = 'PARQUET') fails with "Size is greater than maximum int value"

### ISSUE THREAD

**Issue by skairali** [prestodb/presto#20240]
CTAS query create table "iceberg_cataloge"."schema"."sf100_lineitem" with (format = 'PARQUET') as select * from "tpch"."sf100"."lineitem" to create a table in iceberg catalog using lineitem table in tpch.sf100. The test was carried out in pre-prod cluster with 1 coordinator and 6 worker nodes.(each node i3.4xlarge). CTAS fails with following error.

java.lang.IllegalArgumentException: Size is greater than maximum int value
	at io.airlift.slice.Preconditions.checkArgument(Preconditions.java:32)
	at io.airlift.slice.OutputStreamSliceOutput.checkedCast(OutputStreamSliceOutput.java:369)
	at io.airlift.slice.OutputStreamSliceOutput.size(OutputStreamSliceOutput.java:103)
	at com.facebook.presto.parquet.writer.ParquetWriter.getWrittenBytes(ParquetWriter.java:114)
	at com.facebook.presto.hive.parquet.ParquetFileWriter.getWrittenBytes(ParquetFileWriter.java:89)
	at com.facebook.presto.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:260)
	at com.facebook.presto.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:211)
	at com.facebook.presto.iceberg.IcebergPageSink.lambda$appendPage$0(IcebergPageSink.java:149)
	at com.facebook.presto.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:86)
	at com.facebook.presto.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:149)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:66)
	at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:341)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:436)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:302)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
	at com.facebook.presto.$gen.Presto_0_279____20230629_143206_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by skairali** [comment]
Here is the PR to fix this issue

https://github.com/prestodb/presto/pull/20241

**Comment by skairali** [comment]
Looks like there is a recent PR that may address the same issue. https://github.com/prestodb/presto/pull/20045

**Comment by czentgr** [comment]
@skairali You mentioned another PR that addresses the issue. This PR was merged last week. Does this issue still apply or can it be closed?

**Comment by yingsu00** [comment]
Fixed via https://github.com/prestodb/presto/pull/20045
