### ISSUE TITLE
[Native] Spark e2e tests for Analyze failure

### ISSUE THREAD

**Issue by karteekmurthys** [prestodb/presto#20294]
This PR:https://github.com/prestodb/presto/pull/20055 adds Analyze e2e tests for presto. The same test fails with following exception for Spark:

Query
```
assertUpdate("ANALYZE region", 5);
```

Stacktrace:
```
2023-07-12T14:07:35.552-0500	ERROR	SplitRunner-11-39	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20230712_190728_00000_382pb.0.0.0.0-4  (start = 3.22559990190625E8, wall = 166 ms, cpu = 24 ms, wait = 15 ms, calls = 2)
java.lang.NullPointerException
	at com.facebook.presto.hive.HiveMetadata.createPartitionStatistics(HiveMetadata.java:2202)
	at com.facebook.presto.hive.HiveMetadata.finishStatisticsCollection(HiveMetadata.java:1512)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishStatisticsCollection(ClassLoaderSafeConnectorMetadata.java:196)
	at com.facebook.presto.metadata.MetadataManager.finishStatisticsCollection(MetadataManager.java:757)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.lambda$visitStatisticsWriterNode$46(LocalExecutionPlanner.java:2785)
	at com.facebook.presto.operator.StatisticsWriterOperator.getOutput(StatisticsWriterOperator.java:133)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:428)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
	at com.facebook.presto.spark.execution.task.PrestoSparkTaskExecution$DriverSplitRunner.processFor(PrestoSparkTaskExecution.java:480)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
	at com.facebook.presto.$gen.Presto_null__testversion____20230712_190659_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2023-07-12T14:07:35.849-0500	INFO	main	com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution	Total serialized task info size: 11.46kB
2023-07-12T14:10:40.159-0500	ERROR	Announcer-1	com.facebook.airlift.discovery.client.Announcer	Expected service announcement after 8000.00ms, but announcement was delayed 3.08m
2023-07-12T14:10:40.197-0500	WARN	dispatcher-event-loop-2	org.apache.spark.HeartbeatReceiver	Removing executor driver with no recent heartbeats: 188531 ms exceeds timeout 120000 ms
2023-07-12T14:10:40.210-0500	ERROR	dispatcher-event-loop-2	org.apache.spark.scheduler.TaskSchedulerImpl	Lost executor driver on localhost: Executor heartbeat timed out after 188531 ms
2023-07-12T14:10:40.221-0500	INFO	dag-scheduler-event-loop	org.apache.spark.scheduler.DAGScheduler	Executor lost: driver (epoch 1)
2023-07-12T14:10:40.222-0500	INFO	dispatcher-event-loop-9	org.apache.spark.storage.BlockManagerMasterEndpoint	Trying to remove executor driver from BlockManagerMaster.
2023-07-12T14:10:40.222-0500	INFO	driver-heartbeater	org.apache.spark.executor.Executor	Told to re-register on heartbeat
2023-07-12T14:10:40.225-0500	WARN	kill-executor-thread	org.apache.spark.SparkContext	Killing executors is only supported in coarse-grained mode
2023-07-12T14:10:40.225-0500	INFO	driver-heartbeater	org.apache.spark.storage.BlockManager	BlockManager BlockManagerId(driver, localhost, 55507) re-registering with master
2023-07-12T14:10:40.225-0500	INFO	driver-heartbeater	org.apache.spark.storage.BlockManagerMaster	Registering BlockManager BlockManagerId(driver, localhost, 55507)
2023-07-12T14:10:40.226-0500	INFO	dispatcher-event-loop-9	org.apache.spark.storage.BlockManagerMasterEndpoint	Removing block manager BlockManagerId(driver, localhost, 55507)
2023-07-12T14:10:40.227-0500	INFO	dispatcher-event-loop-9	org.apache.spark.storage.BlockManagerMasterEndpoint	Registering block manager localhost:55507 with 4.1 GB RAM, BlockManagerId(driver, localhost, 55507)
2023-07-12T14:10:40.227-0500	INFO	driver-heartbeater	org.apache.spark.storage.BlockManagerMaster	Registered BlockManager BlockManagerId(driver, localhost, 55507)

java.lang.NullPointerException
	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:61)
	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:392)
	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:517)
	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:500)
	at com.facebook.presto.tests.QueryAssertions.assertUpdate(QueryAssertions.java:71)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:235)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertUpdate(AbstractTestQueryFramework.java:230)
	at com.facebook.presto.nativeworker.AbstractTestNativeGeneralQueries.testAnalyzeStats(AbstractTestNativeGeneralQueries.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```

**Comment by mbasmanova** [comment]
@karteekmurthys Would you debug this issue? Where is NPE coming from? 

CC: @vermapratyush

**Comment by mbasmanova** [comment]
CC: @kewang1024

**Comment by mbasmanova** [comment]
@karteekmurthys Karteek, what did you find?

**Comment by majetideepak** [comment]
Closing since there has been no update on this.
