### ISSUE TITLE
[BUG] preso server can't start, seeing "java.io.UncheckedIOException"

### ISSUE THREAD

**Issue by leipanhz** [prestodb/presto#20449]
## Your Environment

* Presto version used: 0.278.1
* Storage (HDFS/S3/GCS..): S3
* Data source and connector used: file connector
* Deployment (Cloud or On-prem): cloud
* [Pastebin](https://pastebin.com/) link to the complete debug logs: https://pastebin.com/NMmzsBZY

## Expected Behavior

presto server starts

## Current Behavior
not starting with errors in the server.log

## Steps to Reproduce

1. Issue is seen after deploying 0.278.1 to the cluster, no other steps are performed
2.
3.
4.

## Screenshots (if appropriate)
2023-07-31T17:00:49.007-0700    INFO    main    com.facebook.airlift.jmx.JmxAgent       JMX agent started and listening on presto-1.fyre.ibm.com:36181
2023-07-31T17:00:49.116-0700    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  at com.facebook.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79)
  while locating com.facebook.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.internal.Element(setName=,uniqueId=397, type=MULTIBINDER, keyType=)
  while locating java.util.Set<com.facebook.airlift.discovery.client.ServiceAnnouncement>
    for the 2nd parameter of com.facebook.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
  at com.facebook.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:64)
  while locating com.facebook.airlift.discovery.client.Announcer
    for the 2nd parameter of com.facebook.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
  at com.facebook.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:122)
  while locating com.facebook.airlift.discovery.client.MergingServiceSelectorFactory
  at com.facebook.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:73)
  while locating com.facebook.airlift.discovery.client.ServiceSelectorFactory
    for the 1st parameter of com.facebook.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:50)
  at com.facebook.airlift.event.client.HttpEventModule.configure(HttpEventModule.java:43)
Caused by: java.lang.NullPointerException
        at com.facebook.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.get(DiscoveryBinder.java:128)
        at com.facebook.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.get(DiscoveryBinder.java:108)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:66)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:198)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:151)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory$1.call(InternalProviderInstanceBindingImpl.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:115)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:112)
        at com.facebook.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:82)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
        at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:176)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:143)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)

2) Error in custom provider, java.lang.NullPointerException
  at com.facebook.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79)
...
Caused by: java.io.UncheckedIOException (same stack trace as error #3)
5) Error injecting constructor, java.io.UncheckedIOException: Failed to bind to /0.0.0.0:8080
  at com.facebook.airlift.http.server.HttpServerInfo.<init>(HttpServerInfo.java:48)
  at com.facebook.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:73)
  while locating com.facebook.airlift.http.server.HttpServerInfo
    for the 1st parameter of com.facebook.airlift.http.server.LocalAnnouncementHttpServerInfo.<init>(LocalAnnouncementHttpServerInfo.java:31)
  while locating com.facebook.airlift.http.server.LocalAnnouncementHttpServerInfo
  at com.facebook.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:86)
  while locating com.facebook.airlift.discovery.client.AnnouncementHttpServerInfo
    for the 1st parameter of com.facebook.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.setAnnouncementHttpServerInfo(DiscoveryBinder.java:122)
  at com.facebook.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79) (via modules: com.facebook.presto.server.ServerMainModule -> com.facebook.presto.server.CoordinatorModule)
Caused by: java.io.UncheckedIOException (same stack trace as error #3)
6) Error injecting constructor, java.io.UncheckedIOException: Failed to bind to /0.0.0.0:8080
  at com.facebook.airlift.http.server.HttpServerInfo.<init>(HttpServerInfo.java:48)
  at com.facebook.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:73)
  while locating com.facebook.airlift.http.server.HttpServerInfo
    for the 1st parameter of com.facebook.airlift.http.server.LocalAnnouncementHttpServerInfo.<init>(LocalAnnouncementHttpServerInfo.java:31)
  while locating com.facebook.airlift.http.server.LocalAnnouncementHttpServerInfo
  at com.facebook.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:86)
  while locating com.facebook.airlift.discovery.client.AnnouncementHttpServerInfo
    for the 1st parameter of com.facebook.airlift.discovery.client.DiscoveryBinder$HttpAnnouncementProvider.setAnnouncementHttpServerInfo(DiscoveryBinder.java:122)
  at com.facebook.airlift.discovery.client.DiscoveryBinder.bindServiceAnnouncement(DiscoveryBinder.java:79)
Caused by: java.io.UncheckedIOException (same stack trace as error #3)
6 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:178)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.facebook.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:251)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:143)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:85)

**Comment by imjalpreet** [comment]
@leipanhz Can you please share your cluster configs?

**Comment by leipanhz** [comment]
yes, it worked after I reinstall
