### ISSUE TITLE
Flaky Test: TestMergeOperator.testMergeDifferentTypes

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#20541]
Error:  Tests run: 7533, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2,017.904 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.operator.TestMergeOperator.testMergeDifferentTypes  Time elapsed: 1.392 s  <<< FAILURE!
java.lang.AssertionError: Operator is expected to be unblocked within 1.00s
	at org.testng.Assert.fail(Assert.java:110)
	at com.facebook.presto.operator.OperatorAssertion.assertOperatorIsUnblocked(OperatorAssertion.java:332)
	at com.facebook.presto.operator.OperatorAssertion.assertOperatorIsUnblocked(OperatorAssertion.java:326)
	at com.facebook.presto.operator.TestMergeOperator.testMergeDifferentTypes(TestMergeOperator.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Example failing run: https://github.com/prestodb/presto/actions/runs/5813532124/job/15761327746?pr=20540

**Comment by hantangwangd** [comment]
I couldn't reproduce the flakiness at all after over 10000 continuous runs, even after I rollback to the version where PR #20540 is located. So I suspect this issue is related to CI running environment, as a one-second timeout is not so reliable when GC occurs. So should we change `UNBLOCKED_DEFAULT_TIMEOUT` to a longer time, such as 5 seconds? @rschlussel @tdcmeehan @elharo

**Comment by rschlussel** [comment]
Seems reasonable to me and hopefully that should help. Anything checking that something happens within a given amount of time is going to be inherently flaky.  Also tagging @arhimond if he has thoughts since it looks like he wrote the test.

**Comment by elharo** [comment]
Sure.
