### ISSUE TITLE
Partition Column transform support in Iceberg Connector

### ISSUE THREAD

**Issue by agrawalreetika** [prestodb/presto#20570]
Beyond selecting a particular column to partition by, you can select a “transform” and partition the table by the transformed value of the column. 
Available in Iceberg include: 
Day, Month, Year, Hour, Bucket, Truncate

Presto Iceberg Connector currently already supports Bucket & Truncate transform with partition column in Iceberg Table. This feature request is to add transform support for `Day, Month, Year, Hour`

Example -
From Presto Iceberg Connector,
```
    CREATE TABLE players (
        id int,
        name varchar,
        team varchar,
        ts timestamp
    )
    WITH (
        format = 'ORC',
        partitioning = ARRAY['year(ts)']
    );
```

``` 
      INSERT INTO  players 
           VALUES (1, 'player1', 'team1', TIMESTAMP '2023-08-12 03:04:05.321');
```

Presto throws below while `INSERT`:
```
Query 20230815_100629_00014_pf686 failed: Unsupported partition transform: 1000: ts_year: year(4)
java.lang.UnsupportedOperationException: Unsupported partition transform: 1000: ts_year: year(4)
	at com.facebook.presto.iceberg.PartitionTransforms.getColumnTransform(PartitionTransforms.java:117)
	at com.facebook.presto.iceberg.IcebergPageSink.lambda$toPartitionColumns$4(IcebergPageSink.java:381)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4719)
	at java.util.Collections$2.forEachRemaining(Collections.java:4727)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.facebook.presto.iceberg.IcebergPageSink.toPartitionColumns(IcebergPageSink.java:384)
	at com.facebook.presto.iceberg.IcebergPageSink.<init>(IcebergPageSink.java:125)
	at com.facebook.presto.iceberg.IcebergPageSinkProvider.createPageSink(IcebergPageSinkProvider.java:94)
	at com.facebook.presto.iceberg.IcebergPageSinkProvider.createPageSink(IcebergPageSinkProvider.java:73)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSinkProvider.createPageSink(ClassLoaderSafeConnectorPageSinkProvider.java:51)
	at com.facebook.presto.split.PageSinkManager.createPageSink(PageSinkManager.java:62)
	at com.facebook.presto.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:166)
	at com.facebook.presto.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:139)
	at com.facebook.presto.operator.DriverFactory.createDriver(DriverFactory.java:129)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:945)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1073)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
	at com.facebook.presto.$gen.Presto_null__testversion____20230815_080657_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by fgwang7w** [comment]
`date` type is not supported as part of partition key in iceberg connector

```

presto:iceberg_tpch_sf100> create table t1 ( c1 int, c2 varchar, c3 date) with (partitioning=ARRAY['year(c3)','bucket(c1,8)']);
CREATE TABLE
presto:iceberg_tpch_sf100> insert into t1 select 1, 'testing', date '1992-01-01';

Query 20230921_022447_00010_p474t, FAILED, 7 nodes
Splits: 103 total, 0 done (0.00%)
[Latency: client-side: 0:01, server-side: 494ms] [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230921_022447_00010_p474t failed: Unsupported partition transform: 1000: c3_year: year(3)

```

**Comment by gupteaj** [comment]
PR https://github.com/prestodb/presto/pull/21303
