### ISSUE TITLE
[Flaky Test] TestLargeRowGroup.testMemoryUsedIsNotAFunctionOfDataPageCount

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#20612]
This test has failed in some PRs with no changes to the `presto-parquet` module.

CI Run: https://github.com/ZacBlanco/prestodb/actions/runs/5894173141/job/16064675505?pr=14#step:7:16337

```
Error:  Tests run: 86, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 49.233 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.parquet.reader.TestLargeRowGroup.testMemoryUsedIsNotAFunctionOfDataPageCount  Time elapsed: 5.466 s  <<< FAILURE!
java.lang.AssertionError: [10000] pages :: parquetReaderDeepSize :: actual [31511240], expected < [21810380] expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertTrue(Assert.java:56)
	at com.facebook.presto.parquet.reader.TestLargeRowGroup.testMemoryUsedIsNotAFunctionOfDataPageCount(TestLargeRowGroup.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestLargeRowGroup.testMemoryUsedIsNotAFunctionOfDataPageCount:132 [10000] pages :: parquetReaderDeepSize :: actual [31511240], expected < [21810380] expected [true] but found [false]
[INFO] 
Error:  Tests run: 86, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by rschlussel** [comment]
I've seen this failure again https://github.com/prestodb/presto/actions/runs/10207426860/job/28242167839?pr=23360

**Comment by rschlussel** [comment]
@aaneja can you look at this flaky test failure?
