### ISSUE TITLE
Flaky test TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEmptyList in redis-hbo-provider

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#20620]
Example failing job: https://github.com/prestodb/presto/actions/runs/5931136397/job/16082358906?pr=20616
Stacktrace: 
```
Error:  Tests run: 22, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 213.599 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.statistic.TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEmptyList  Time elapsed: 0.212 s  <<< FAILURE!
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:232)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:209)
	at com.facebook.presto.statistic.HistoricalStatisticsSerde.encodeValue(HistoricalStatisticsSerde.java:59)
	at com.facebook.presto.statistic.TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEmptyList(TestHistoricalStatisticsSerde.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:232)
	at com.facebook.drift.codec.internal.compiler.ThriftCodecByteCodeGenerator.declareCodecFields(ThriftCodecByteCodeGenerator.java:239)
	at com.facebook.drift.codec.internal.compiler.ThriftCodecByteCodeGenerator.<init>(ThriftCodecByteCodeGenerator.java:165)
	at com.facebook.drift.codec.internal.compiler.CompilerThriftCodecFactory.generateThriftTypeCodec(CompilerThriftCodecFactory.java:61)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:143)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:127)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:232)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:209)
	at com.facebook.presto.statistic.HistoricalStatisticsSerde.encodeValue(HistoricalStatisticsSerde.java:59)
	at com.facebook.presto.statistic.TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEntryList(TestHistoricalStatisticsSerde.java:61)
	... 15 more
Caused by: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
	at com.facebook.drift.codec.metadata.RecursiveThriftTypeReference.get(RecursiveThriftTypeReference.java:62)
	at com.facebook.drift.codec.ThriftCodecManager.getElementCodec(ThriftCodecManager.java:195)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:149)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:127)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 35 more

Error:  com.facebook.presto.statistic.TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEntryList  Time elapsed: 0.002 s  <<< FAILURE!
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:232)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:209)
	at com.facebook.presto.statistic.HistoricalStatisticsSerde.encodeValue(HistoricalStatisticsSerde.java:59)
	at com.facebook.presto.statistic.TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEntryList(TestHistoricalStatisticsSerde.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.facebook.drift.codec.ThriftCodecManager.getCodec(ThriftCodecManager.java:232)
	at com.facebook.drift.codec.internal.compiler.ThriftCodecByteCodeGenerator.declareCodecFields(ThriftCodecByteCodeGenerator.java:239)
	at com.facebook.drift.codec.internal.compiler.ThriftCodecByteCodeGenerator.<init>(ThriftCodecByteCodeGenerator.java:165)
	at com.facebook.drift.codec.internal.compiler.CompilerThriftCodecFactory.generateThriftTypeCodec(CompilerThriftCodecFactory.java:61)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:143)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:127)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 22 more
Caused by: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
	at com.facebook.drift.codec.metadata.RecursiveThriftTypeReference.get(RecursiveThriftTypeReference.java:62)
	at com.facebook.drift.codec.ThriftCodecManager.getElementCodec(ThriftCodecManager.java:195)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:149)
	at com.facebook.drift.codec.ThriftCodecManager$1.load(ThriftCodecManager.java:127)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 35 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEmptyList:72 » UncheckedExecution com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
Error:    TestHistoricalStatisticsSerde.TestHistoricalPlanStatisticsEntryList:61 » UncheckedExecution com.google.common.util.concurrent.UncheckedExecutionException: java.lang.UnsupportedOperationException: Attempted to resolve a recursive reference to type 'com.facebook.presto.spi.statistics.HistoricalPlanStatisticsEntry' before the referenced type was cached (most likely a recursive type support bug)
[INFO] 
Error:  Tests run: 22, Failures: 2, Errors: 0, Skipped: 0
```

@jaystarshot

**Comment by rschlussel** [comment]
Also, i see all the test methods in this class start with capital T. so just wanted to add a formatting note that method names should be lower camel case.

**Comment by jaystarshot** [comment]
I suspect https://github.com/prestodb/presto/pull/20623 might fix it, but not sure since could not repro

**Comment by rschlussel** [comment]
Closing since #20623 was merged
