### ISSUE TITLE
Exclude new time zones from TestTimeZoneUtils

### ISSUE THREAD

**Issue by Akanksha-kedia** [prestodb/presto#20636]
mvn -T124 test

Java Version :
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

[ERROR] com.facebook.presto.util.TestTimeZoneUtils.testNamedZones  Time elapsed: 0.092 s  <<< FAILURE!
java.time.zone.ZoneRulesException: Unknown time-zone ID: Europe/Kyiv

**Comment by agrawalreetika** [comment]
Hi @Akanksha-kedia,
Could you please provide the steps to produce this test failure?
And which version of Presto are you on?

**Comment by Akanksha-kedia** [comment]
Java Version :
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b10, mixed mode)

Steps :
1. cd presto-main
2. mvn test -Dtest="TestTimeZoneUtils"

Presto [358 tags](https://github.com/prestodb/presto/tags) master


Error : [ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.448 s <<< FAILURE! - in com.facebook.presto.util.TestTimeZoneUtils
[ERROR] com.facebook.presto.util.TestTimeZoneUtils.testNamedZones  Time elapsed: 1.293 s  <<< FAILURE!
java.time.zone.ZoneRulesException: Unknown time-zone ID: Europe/Kyiv
	at java.time.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:272)
	at java.time.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:227)
	at java.time.ZoneRegion.ofId(ZoneRegion.java:120)
	at java.time.ZoneId.of(ZoneId.java:411)
	at java.time.ZoneId.of(ZoneId.java:359)
	at com.facebook.presto.util.TestTimeZoneUtils.assertTimeZone(TestTimeZoneUtils.java:98)
	at com.facebook.presto.util.TestTimeZoneUtils.testNamedZones(TestTimeZoneUtils.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestTimeZoneUtils.testNamedZones:81->assertTimeZone:98 » ZoneRules Unknown time-zone ID: Europe/Kyiv
[INFO]
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
[INFO]

**Comment by Akanksha-kedia** [comment]
Yes, it is there for me #19758
<https://github.com/prestodb/presto/pull/19758> presto version
0.284-SNAPSHOT

**Comment by Akanksha-kedia** [comment]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.826 s - in com.facebook.presto.util.TestTimeZoneUtils
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 min
[INFO] Finished at: 2023-08-23T16:41:58+05:30
[INFO] ------------------------------------------------------------------------

**Comment by Akanksha-kedia** [comment]
@tdcmeehan Please help to close this.Thanks
