### ISSUE TITLE
Set up Password File Authentication failed

### ISSUE THREAD

**Issue by yongbeima** [prestodb/presto#20675]
Friends,

I install presto on my remote server and I want to connect it using password on my local computer with jdbc.

**1)Set up presto environment**
$ docker pull ahanaio/prestodb-sandbox
$ docker run -p 8080:8080 -p 8443:8443 --name presto ahanaio/prestodb-sandbox
$ docker ps --all
CONTAINER ID        IMAGE                 COMMAND            CREATED             STATUS              PORTS               NAMES
a5a44e77a794        docker.io/ah...  "/opt/entrypoint.s..."   ...        ....        0.0.0.0:8080->8080/tcp, 0.0.0.0:8443->8443/tcp gracious_aryabhata
$ docker exec -it a5 /bin/bash

**2)Java Keystore File for TLS**
following this page: https://prestodb.io/docs/current/security/tls.html
bash-4.2# cd /opt/presto-server/etc/
bash-4.2# keytool -genkeypair -alias **a5a44e77a794** -keyalg RSA -keystore keystore.jks

**3)Password File Authentication**
following this page: https://prestodb.io/docs/current/security/password-file.html
bash-4.2# touch password.db
bash-4.2# yum install httpd-tools
bash-4.2# htpasswd -B -C 10 password.db test
bash-4.2# cat password.db 
test:$2y$10$ZliIvDCQI3tcBhqwBVd2A.3ihpawbBG6ZLzEUli5lgnabao330RaK
===add and edit password-authenticator.properties===
bash-4.2# cat password-authenticator.properties
password-authenticator.name=file
file.password-file=/opt/presto-server/etc/password.db

**4)Server Config Properties**
following this page: https://prestodb.io/docs/current/security/ldap.html
===edit config.properties===
bash-4.2# cat config.properties
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery-server.enabled=true
discovery.uri=http://localhost:8080
http-server.authentication.type=PASSWORD
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/opt/presto-server/etc/keystore.jks
http-server.https.keystore.key=thisistest

**5) Exit and restart the presto container**
bash-4.2# exit
$ docker restart a5a
$ docker logs a5a44e77a794 --tail 500
....
2023-08-26T01:09:57.668Z        INFO    main    org.eclipse.jetty.server.handler.ContextHandler Started o.e.j.s.ServletContextHandler@4822d7a1{/,null,AVAILABLE,@http}
2023-08-26T01:09:57.675Z        INFO    main    org.eclipse.jetty.server.AbstractConnector      Started http@4e9d1119{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8080}
2023-08-26T01:09:57.786Z        INFO    main    org.eclipse.jetty.util.ssl.SslContextFactory    x509=X509@7b50e70a(a5a44e77a794,h=[],w=[]) for SslContextFactory@1acd952e[provider=null,keyStore=file:///opt/presto-server/etc/keystore.jks,trustStore=null]
**2023-08-26T01:09:57.821Z        WARN    main    org.eclipse.jetty.util.ssl.SslContextFactory.config     No Client EndPointIdentificationAlgorithm configured for SslContextFactory@1acd952e[provider=null,keyStore=file:///opt/presto-server/etc/keystore.jks,trustStore=null]**
2023-08-26T01:09:57.840Z        INFO    main    org.eclipse.jetty.server.AbstractConnector      Started https@2ac00dc9{SSL,[ssl, http/1.1]}{0.0.0.0:8443}
2023-08-26T01:09:57.840Z        INFO    main    org.eclipse.jetty.server.Server Started @11002ms
2023-08-26T01:09:57.876Z        WARN    query-management-2      com.facebook.presto.memory.RemoteNodeMemory     Memory info update request to http://x.x.x.x:8080/v1/memory has not returned in 34184313.02s
.....

Now on my local computer I can still connect my presto with no password,
I can open http://x.x.x.x:8080 but cannot open https://x.x.x.x:8443 on my local computer.
there must be something wrong?

Thanks

**Comment by kiersten-stokes** [comment]
Hi @yongbeima! Thanks for supplying such detailed info! I just ran through your reproduction steps and, even though I get the same warning that you've bolded in your server logs, I can access the UI via port 8443. When you say you can't open `https://<localhost>:8443` do you mean that you get a 401 response or that you're prompted for a username/password and the authentication is failing?

**Comment by yongbeima** [comment]
> Hi @yongbeima! Thanks for supplying such detailed info! I just ran through your reproduction steps and, even though I get the same warning that you've bolded in your server logs, I can access the UI via port 8443. When you say you can't open `https://<localhost>:8443` do you mean that you get a 401 response or that you're prompted for a username/password and the authentication is failing?

when I open https://x.x.x.x:8443,I got this error:

The page is not working 
x.x.x.x No data was sent.
ERR_EMPTY_RESPONSE

Thanks

**Comment by yongbeima** [comment]
The tcp connection to 8443 port is working,

on my remote server:
$ lsof -i:8443
COMMAND     PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
docker-pr 19548 root    4u  IPv6 624315098      0t0  TCP *:pcsync-https (LISTEN)

on my local computer:
PS C:\Users\ybma> Test-NetConnection x.x.x.x -p 8443
ComputerName     : x.x.x.x
RemoteAddress    : x.x.x.x
RemotePort       : 8443
InterfaceAlias   : WLAN
SourceAddress    : x.x.x.x
TcpTestSucceeded : True

It seems just no response from my presto.

**Comment by yongbeima** [comment]
I listened to port 8443 on my server and found that no tcp data was received. 

$ /usr/sbin/tcpdump -s 0 -X 'tcp dst port 8443'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

Finally I found that the problem was caused by some configuration problems on my local computer.

Thanks

**Comment by yongbeima** [comment]
Now the problem is that I can still connect to 8080 although I have added password-authenticator...

**Comment by yongbeima** [comment]
Even if I comment out these lines of configuration, I can still access through 8080.

bash-4.2# cat config.properties
coordinator=true
node-scheduler.include-coordinator=true
**#http-server.http.port=8080
#discovery-server.enabled=true
#discovery.uri=http://localhost:8080**
query.max-memory=8GB
query.max-memory-per-node=2GB


here is some error log:

2023-08-30T09:21:59.706Z        INFO    main    com.facebook.presto.metadata.StaticCatalogStore -- Loading catalog jmx --
2023-08-30T09:21:59.892Z        WARN    http-worker-127 org.eclipse.jetty.server.HttpChannel    /v1/queryState
java.lang.RuntimeException: Authentication error
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:73)
        at com.facebook.airlift.http.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.facebook.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.facebook.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: authenticator was not loaded
        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.facebook.presto.server.security.PasswordAuthenticatorManager.getAuthenticator(PasswordAuthenticatorManager.java:83)
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:67)
        ... 39 more
2023-08-30T09:21:59.915Z        WARN    http-worker-140 org.eclipse.jetty.server.HttpChannel    /v1/info
java.lang.RuntimeException: Authentication error
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:73)
        at com.facebook.airlift.http.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.facebook.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.facebook.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: authenticator was not loaded
        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.facebook.presto.server.security.PasswordAuthenticatorManager.getAuthenticator(PasswordAuthenticatorManager.java:83)
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:67)
        ... 39 more
2023-08-30T09:21:59.933Z        WARN    http-worker-141 org.eclipse.jetty.server.HttpChannel    /v1/cluster
java.lang.RuntimeException: Authentication error
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:73)
        at com.facebook.airlift.http.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:80)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.facebook.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at com.facebook.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:51)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:411)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:305)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:159)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: authenticator was not loaded
        at com.google.common.base.Preconditions.checkState(Preconditions.java:507)
        at com.facebook.presto.server.security.PasswordAuthenticatorManager.getAuthenticator(PasswordAuthenticatorManager.java:83)
        at com.facebook.presto.server.security.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:67)
        ... 39 more
2023-08-30T09:22:00.066Z        INFO    main    Bootstrap       PROPERTY         DEFAULT  RUNTIME  DESCRIPTION
2023-08-30T09:22:00.066Z        INFO    main    Bootstrap       jmx.dump-period  10.00s   10.00s
2023-08-30T09:22:00.066Z        INFO    main    Bootstrap       jmx.dump-tables  []       []

**Comment by kiersten-stokes** [comment]
You'll still need to specify discovery configuration properties (`discovery-server.enabled` and `discovery.uri`) as that is how Presto finds all the available cluster nodes. By leaving `discovery.uri` as-is (e.g., `discovery.uri=http://localhost:8080/`), you can still access the unsecured dashboard because the nodes are still communicating via http rather than https. In order to completely disable the unsecured dashboard, I think you'll want to set up secure internal communication as well, which just requires a few additional changes to `config.properties`. Try out the steps [here](https://prestodb.io/docs/current/security/internal-communication.html#internal-ssl-tls-configuration)
