### ISSUE TITLE
Missing bindings for `SnapshotQueryConsumer` and `SnapshotQuerySupplier` in `VerifierModule`

### ISSUE THREAD

**Issue by vermapratyush** [prestodb/presto#20828]
Missing bindings for `SnapshotQueryConsumer` and `SnapshotQuerySupplier` in `VerifierModule`.

Verifier bootstrap fails with
```
Bootstrap Uncaught exception in thread main
com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Explicit bindings are required and com.facebook.presto.verifier.source.SnapshotQueryConsumer is not explicitly bound.
  while locating com.facebook.presto.verifier.source.SnapshotQueryConsumer
    for the 2nd parameter of com.facebook.presto.verifier.framework.VerificationManager.<init>(VerificationManager.java:133)
 at com.facebook.presto.verifier.framework.VerifierModule.setup(VerifierModule.java:130)
2) Explicit bindings are required and com.facebook.presto.verifier.source.SnapshotQuerySupplier is not explicitly bound.
  while locating com.facebook.presto.verifier.source.SnapshotQuerySupplier
    for the 3rd parameter of com.facebook.presto.verifier.framework.VerificationManager.<init>(VerificationManager.java:133)
 at com.facebook.presto.verifier.framework.VerifierModule.setup(VerifierModule.java:130)
```

_Originally posted by @vermapratyush in https://github.com/prestodb/presto/issues/19253#issuecomment-1714203681_

**Comment by vermapratyush** [comment]
cc @mbasmanova @stevechuck @erichwang @ajaygeorge

**Comment by stevechuck** [comment]
cc @ericyuliu
