### ISSUE TITLE
Unstable pipeline due to "Error committing write to Hive"

### ISSUE THREAD

**Issue by czentgr** [prestodb/presto#20830]
Various tests in the `product-tests-basic-environment` fail due to  "Error committing write to Hive"

```
2023-09-11T19:04:17.6966308Z 2023-09-12 00:49:17 INFO: FAILURE     /    sql_tests.testcases.insert.insert_select_star_union_all (Groups: insert) took 2.6 seconds
2023-09-11T19:04:17.7053439Z 2023-09-12 00:49:17 SEVERE: Failure cause:
2023-09-11T19:04:17.7057622Z io.prestodb.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20230911_190417_01242_y28b5): Error committing write to Hive
2023-09-11T19:04:17.7062796Z 	at io.prestodb.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:115)
2023-09-11T19:04:17.7063570Z 	at io.prestodb.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:83)
2023-09-11T19:04:17.7069158Z 	at io.prestodb.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:118)
2023-09-11T19:04:17.7070407Z 	at io.prestodb.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:101)
2023-09-11T19:04:17.7075777Z 	at io.prestodb.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:124)
2023-09-11T19:04:17.7076650Z 	at io.prestodb.tempto.insert.insert_select_star_union_all(Unknown Source)
2023-09-11T19:04:17.7077152Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-09-11T19:04:17.7081822Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-09-11T19:04:17.7082499Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-11T19:04:17.7088155Z 	at java.lang.reflect.Method.invoke(Method.java:498)
```

## Your Environment

* Presto version used: latest code base
* Storage (HDFS/S3/GCS..): 
* Data source and connector used: N/A
* Deployment (Cloud or On-prem): N/A
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

Full log from one run attached.

Excerpt copy from log:

```
2023-09-11T19:04:15.0864014Z 2023-09-12 00:49:15 INFO: [282 of 427] sql_tests.testcases.insert.insert_select_star_union_all (Groups: insert)
2023-09-11T19:04:17.6091799Z presto-worker_1       | 2023-09-12T00:49:17.607+0545	INFO	20230911_190417_01242_y28b5.1.0.0.0-33-37	org.apache.hadoop.io.compress.CodecPool	Got brand-new compressor [.gz]
2023-09-11T19:04:17.6546576Z presto-worker_1       | 2023-09-12T00:49:17.649+0545	WARN	Thread-559	org.apache.hadoop.hdfs.DFSClient	DataStreamer Exception
2023-09-11T19:04:17.6553962Z presto-worker_1       | org.apache.hadoop.ipc.RemoteException(java.io.IOException): File /tmp/presto-hdfs/86c63d9f-ad56-49b6-b9e8-75a2bf2f5e3f/20230911_190417_01242_y28b5_fbce23af-6b1a-4b59-a14d-15295a456eda.gz could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
2023-09-11T19:04:17.6558459Z presto-worker_1       | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1719)
2023-09-11T19:04:17.6564493Z presto-worker_1       | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3372)
2023-09-11T19:04:17.6565922Z presto-worker_1       | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3296)
2023-09-11T19:04:17.6570949Z presto-worker_1       | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:850)
2023-09-11T19:04:17.6573051Z presto-worker_1       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:504)
2023-09-11T19:04:17.6578961Z presto-worker_1       | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2023-09-11T19:04:17.6584598Z presto-worker_1       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
2023-09-11T19:04:17.6585565Z presto-worker_1       | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
2023-09-11T19:04:17.6590151Z presto-worker_1       | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
2023-09-11T19:04:17.6591212Z presto-worker_1       | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
2023-09-11T19:04:17.6591956Z presto-worker_1       | 	at java.security.AccessController.doPrivileged(Native Method)
2023-09-11T19:04:17.6597077Z presto-worker_1       | 	at javax.security.auth.Subject.doAs(Subject.java:422)
2023-09-11T19:04:17.6597915Z presto-worker_1       | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869)
2023-09-11T19:04:17.6603042Z presto-worker_1       | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2347)
2023-09-11T19:04:17.6603835Z presto-worker_1       | 
2023-09-11T19:04:17.6613607Z presto-worker_1       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
2023-09-11T19:04:17.6674921Z presto-worker_1       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
2023-09-11T19:04:17.6705287Z presto-worker_1       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
2023-09-11T19:04:17.6706345Z presto-worker_1       | 	at com.sun.proxy.$Proxy319.addBlock(Unknown Source)
2023-09-11T19:04:17.6712480Z presto-worker_1       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:418)
2023-09-11T19:04:17.6713737Z presto-worker_1       | 	at sun.reflect.GeneratedMethodAccessor425.invoke(Unknown Source)
2023-09-11T19:04:17.6718560Z presto-worker_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-11T19:04:17.6719659Z presto-worker_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-09-11T19:04:17.6720442Z presto-worker_1       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
2023-09-11T19:04:17.6725565Z presto-worker_1       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
2023-09-11T19:04:17.6726333Z presto-worker_1       | 	at com.sun.proxy.$Proxy320.addBlock(Unknown Source)
2023-09-11T19:04:17.6732049Z presto-worker_1       | 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1588)
2023-09-11T19:04:17.6733027Z presto-worker_1       | 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1373)
2023-09-11T19:04:17.6739715Z presto-worker_1       | 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:554)
2023-09-11T19:04:17.6740317Z presto-worker_1       | 
2023-09-11T19:04:17.6743836Z presto-worker_1       | 
2023-09-11T19:04:17.6745424Z presto-worker_1       | 2023-09-12T00:49:17.651+0545	ERROR	SplitRunner-2-37	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20230911_190417_01242_y28b5.1.0.0.0-33  (start = 3273221.694011, wall = 161 ms, cpu = 0 ms, wait = 0 ms, calls = 2): HIVE_WRITER_CLOSE_ERROR: Error committing write to Hive
2023-09-11T19:04:17.6752081Z presto-master_1       | 2023-09-12T00:49:17.660+0545	ERROR	remote-task-callback-47	com.facebook.presto.execution.StageExecutionStateMachine	Stage execution 20230911_190417_01242_y28b5.1.0 failed
2023-09-11T19:04:17.6753131Z presto-master_1       | com.facebook.presto.spi.PrestoException: Error committing write to Hive
2023-09-11T19:04:17.6759669Z presto-master_1       | 	at com.facebook.presto.hive.RecordFileWriter.commit(RecordFileWriter.java:186)
2023-09-11T19:04:17.6765227Z presto-master_1       | 	at com.facebook.presto.hive.HiveWriter.commit(HiveWriter.java:102)
2023-09-11T19:04:17.6765984Z presto-master_1       | 	at com.facebook.presto.hive.HivePageSink.doFinish(HivePageSink.java:237)
2023-09-11T19:04:17.6771154Z presto-master_1       | 	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
2023-09-11T19:04:17.6773147Z presto-master_1       | 	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
2023-09-11T19:04:17.6778371Z presto-master_1       | 	at com.facebook.presto.hive.HivePageSink.finish(HivePageSink.java:228)
2023-09-11T19:04:17.6779457Z presto-master_1       | 	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:74)
2023-09-11T19:04:17.6785562Z presto-master_1       | 	at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:292)
2023-09-11T19:04:17.6786769Z presto-master_1       | 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:451)
2023-09-11T19:04:17.6792377Z presto-master_1       | 	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
2023-09-11T19:04:17.6793509Z presto-master_1       | 	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
2023-09-11T19:04:17.6797545Z presto-master_1       | 	at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
2023-09-11T19:04:17.6802203Z presto-master_1       | 	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
2023-09-11T19:04:17.6803696Z presto-master_1       | 	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
2023-09-11T19:04:17.6810333Z presto-master_1       | 	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
2023-09-11T19:04:17.6811230Z presto-master_1       | 	at com.facebook.presto.$gen.Presto_0_284_SNAPSHOT_2d1757c____20230911_183121_1.run(Unknown Source)
2023-09-11T19:04:17.6816654Z presto-master_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-09-11T19:04:17.6817670Z presto-master_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-09-11T19:04:17.6822258Z presto-master_1       | 	at java.lang.Thread.run(Thread.java:748)
2023-09-11T19:04:17.6823829Z presto-master_1       | Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hdfs/86c63d9f-ad56-49b6-b9e8-75a2bf2f5e3f/20230911_190417_01242_y28b5_fbce23af-6b1a-4b59-a14d-15295a456eda.gz could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
2023-09-11T19:04:17.6829879Z presto-master_1       | 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1719)
2023-09-11T19:04:17.6830900Z presto-master_1       | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3372)
2023-09-11T19:04:17.6835812Z presto-master_1       | 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3296)
2023-09-11T19:04:17.6836856Z presto-master_1       | 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:850)
2023-09-11T19:04:17.6842976Z presto-master_1       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:504)
2023-09-11T19:04:17.6844421Z presto-master_1       | 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2023-09-11T19:04:17.6850273Z presto-master_1       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
2023-09-11T19:04:17.6851089Z presto-master_1       | 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
2023-09-11T19:04:17.6855915Z presto-master_1       | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
2023-09-11T19:04:17.6856704Z presto-master_1       | 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
2023-09-11T19:04:17.6857343Z presto-master_1       | 	at java.security.AccessController.doPrivileged(Native Method)
2023-09-11T19:04:17.6862373Z presto-master_1       | 	at javax.security.auth.Subject.doAs(Subject.java:422)
2023-09-11T19:04:17.6863606Z presto-master_1       | 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869)
2023-09-11T19:04:17.6869369Z presto-master_1       | 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2347)
2023-09-11T19:04:17.6869888Z presto-master_1       | 
2023-09-11T19:04:17.6875244Z presto-master_1       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
2023-09-11T19:04:17.6875865Z presto-master_1       | 	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
2023-09-11T19:04:17.6881579Z presto-master_1       | 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
2023-09-11T19:04:17.6882421Z presto-master_1       | 	at com.sun.proxy.$Proxy319.addBlock(Unknown Source)
2023-09-11T19:04:17.6887371Z presto-master_1       | 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:418)
2023-09-11T19:04:17.6888824Z presto-master_1       | 	at sun.reflect.GeneratedMethodAccessor425.invoke(Unknown Source)
2023-09-11T19:04:17.6893634Z presto-master_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-11T19:04:17.6894507Z presto-master_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-09-11T19:04:17.6895276Z presto-master_1       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
2023-09-11T19:04:17.6901616Z presto-master_1       | 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
2023-09-11T19:04:17.6902557Z presto-master_1       | 	at com.sun.proxy.$Proxy320.addBlock(Unknown Source)
2023-09-11T19:04:17.6908042Z presto-master_1       | 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1588)
2023-09-11T19:04:17.6909013Z presto-master_1       | 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1373)
2023-09-11T19:04:17.6914897Z presto-master_1       | 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:554)
2023-09-11T19:04:17.6915492Z presto-master_1       | 
2023-09-11T19:04:17.6919736Z presto-master_1       | 
2023-09-11T19:04:17.6966308Z 2023-09-12 00:49:17 INFO: FAILURE     /    sql_tests.testcases.insert.insert_select_star_union_all (Groups: insert) took 2.6 seconds
2023-09-11T19:04:17.7053439Z 2023-09-12 00:49:17 SEVERE: Failure cause:
2023-09-11T19:04:17.7057622Z io.prestodb.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20230911_190417_01242_y28b5): Error committing write to Hive
2023-09-11T19:04:17.7062796Z 	at io.prestodb.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:115)
2023-09-11T19:04:17.7063570Z 	at io.prestodb.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:83)
2023-09-11T19:04:17.7069158Z 	at io.prestodb.tempto.internal.convention.sql.SqlQueryConventionBasedTest.runTestQuery(SqlQueryConventionBasedTest.java:118)
2023-09-11T19:04:17.7070407Z 	at io.prestodb.tempto.internal.convention.sql.SqlQueryConventionBasedTest.test(SqlQueryConventionBasedTest.java:101)
2023-09-11T19:04:17.7075777Z 	at io.prestodb.tempto.internal.convention.ConventionBasedTestProxyGenerator$ConventionBasedTestProxy.test(ConventionBasedTestProxyGenerator.java:124)
2023-09-11T19:04:17.7076650Z 	at io.prestodb.tempto.insert.insert_select_star_union_all(Unknown Source)
2023-09-11T19:04:17.7077152Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-09-11T19:04:17.7081822Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-09-11T19:04:17.7082499Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-11T19:04:17.7088155Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-09-11T19:04:17.7088995Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2023-09-11T19:04:17.7095045Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2023-09-11T19:04:17.7095848Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2023-09-11T19:04:17.7100594Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2023-09-11T19:04:17.7101509Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2023-09-11T19:04:17.7105750Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2023-09-11T19:04:17.7106535Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2023-09-11T19:04:17.7111174Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2023-09-11T19:04:17.7112036Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-09-11T19:04:17.7112648Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-09-11T19:04:17.7120399Z 	at java.lang.Thread.run(Thread.java:748)
2023-09-11T19:04:17.7126390Z Caused by: java.sql.SQLException: Query failed (#20230911_190417_01242_y28b5): Error committing write to Hive
2023-09-11T19:04:17.7130709Z 	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841)
2023-09-11T19:04:17.7138516Z 	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1821)
2023-09-11T19:04:17.7143234Z 	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1760)
2023-09-11T19:04:17.7144167Z 	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
2023-09-11T19:04:17.7149994Z 	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
2023-09-11T19:04:17.7150906Z 	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
2023-09-11T19:04:17.7156311Z 	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1311)
2023-09-11T19:04:17.7157232Z 	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1327)
2023-09-11T19:04:17.7161864Z 	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:146)
2023-09-11T19:04:17.7162619Z 	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:291)
2023-09-11T19:04:17.7167433Z 	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)
2023-09-11T19:04:17.7168222Z 	at io.prestodb.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:123)
2023-09-11T19:04:17.7168946Z 	at io.prestodb.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:108)
2023-09-11T19:04:17.7173556Z 	... 20 more
2023-09-11T19:04:17.7174532Z Caused by: com.facebook.presto.spi.PrestoException: Error committing write to Hive
2023-09-11T19:04:17.7179565Z 	at com.facebook.presto.hive.RecordFileWriter.commit(RecordFileWriter.java:186)
2023-09-11T19:04:17.7180202Z 	at com.facebook.presto.hive.HiveWriter.commit(HiveWriter.java:102)
2023-09-11T19:04:17.7184854Z 	at com.facebook.presto.hive.HivePageSink.doFinish(HivePageSink.java:237)
2023-09-11T19:04:17.7185586Z 	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
2023-09-11T19:04:17.7190510Z 	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
2023-09-11T19:04:17.7191180Z 	at com.facebook.presto.hive.HivePageSink.finish(HivePageSink.java:228)
2023-09-11T19:04:17.7195869Z 	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:74)
2023-09-11T19:04:17.7196819Z 	at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:292)
2023-09-11T19:04:17.7197883Z 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:451)
2023-09-11T19:04:17.7202870Z 	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
2023-09-11T19:04:17.7203603Z 	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
2023-09-11T19:04:17.7208907Z 	at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
2023-09-11T19:04:17.7209757Z 	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
2023-09-11T19:04:17.7214828Z 	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
2023-09-11T19:04:17.7215939Z 	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
2023-09-11T19:04:17.7220991Z 	at com.facebook.presto.$gen.Presto_0_284_SNAPSHOT_2d1757c____20230911_183121_1.run(Unknown Source)
2023-09-11T19:04:17.7221632Z 	... 3 more
2023-09-11T19:04:17.7227917Z Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hdfs/86c63d9f-ad56-49b6-b9e8-75a2bf2f5e3f/20230911_190417_01242_y28b5_fbce23af-6b1a-4b59-a14d-15295a456eda.gz could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
2023-09-11T19:04:17.7229070Z 	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1719)
2023-09-11T19:04:17.7234084Z 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getNewBlockTargets(FSNamesystem.java:3372)
2023-09-11T19:04:17.7234939Z 	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3296)
2023-09-11T19:04:17.7239840Z 	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:850)
2023-09-11T19:04:17.7240909Z 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:504)
2023-09-11T19:04:17.7242004Z 	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
2023-09-11T19:04:17.7247859Z 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:640)
2023-09-11T19:04:17.7248617Z 	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
2023-09-11T19:04:17.7253720Z 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2351)
2023-09-11T19:04:17.7254404Z 	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2347)
2023-09-11T19:04:17.7258913Z 	at java.security.AccessController.doPrivileged(Native Method)
2023-09-11T19:04:17.7259380Z 	at javax.security.auth.Subject.doAs(Subject.java:422)
2023-09-11T19:04:17.7264631Z 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1869)
2023-09-11T19:04:17.7265297Z 	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2347)
2023-09-11T19:04:17.7265579Z 
2023-09-11T19:04:17.7269562Z 	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
2023-09-11T19:04:17.7270938Z 	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
2023-09-11T19:04:17.7275959Z 	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
2023-09-11T19:04:17.7276584Z 	at com.sun.proxy.$Proxy319.addBlock(Unknown Source)
2023-09-11T19:04:17.7277261Z 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:418)
2023-09-11T19:04:17.7283297Z 	at sun.reflect.GeneratedMethodAccessor425.invoke(Unknown Source)
2023-09-11T19:04:17.7283926Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-11T19:04:17.7288524Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-09-11T19:04:17.7290338Z 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
2023-09-11T19:04:17.7305239Z 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
2023-09-11T19:04:17.7305837Z 	at com.sun.proxy.$Proxy320.addBlock(Unknown Source)
2023-09-11T19:04:17.7311784Z 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1588)
2023-09-11T19:04:17.7312632Z 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1373)
2023-09-11T19:04:17.7317421Z 	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:554)
2023-09-11T19:04:17.7317978Z 
```

## Expected Behavior
Tests should pass

## Current Behavior
Tests fail

## Steps to Reproduce
Pipeline for PRs is affected that do not change Java code (e.g. native changes only).

**Comment by czentgr** [comment]
One pipeline run log - error in 1-product-tests-basic-environment.txt.

[logs_288341.zip](https://github.com/prestodb/presto/files/12580128/logs_288341.zip)
