### ISSUE TITLE
map_union_sum(x, REAL) fails with UnsupportedOperationException: com.facebook.presto.common.type.RealType

### ISSUE THREAD

**Issue by mbasmanova** [prestodb/presto#20951]
```
CREATE TABLE tmp(c0, g0, g1) AS SELECT cast(null as map(TINYINT, REAL)), cast(null as TIMESTAMP), cast(null as BIGINT);

SELECT g0 as g0, g1 as g1, array_sort(map_keys(a0)) as p2 
FROM (SELECT g0, g1, map_union_sum(c0) as a0 FROM tmp GROUP BY g0, g1);

java.lang.UnsupportedOperationException: com.facebook.presto.common.type.RealType
	at com.facebook.presto.common.type.AbstractType.writeDouble(AbstractType.java:128)
	at com.facebook.presto.operator.aggregation.MapUnionSumResult.appendValue(MapUnionSumResult.java:82)
	at com.facebook.presto.operator.aggregation.MapUnionSumResult$SingleMapBlock.appendValue(MapUnionSumResult.java:202)
	at com.facebook.presto.operator.aggregation.MapUnionSumResult.unionSum(MapUnionSumResult.java:140)
	at com.facebook.presto.operator.aggregation.MapUnionSumResult.unionSum(MapUnionSumResult.java:165)
	at com.facebook.presto.operator.aggregation.MapUnionSumAggregation.input(MapUnionSumAggregation.java:135)
```

This issue was discovered by running Velox AggregationFuzzer with Presto as source of truth.

CC: @kaikalur @tdcmeehan

**Comment by kaikalur** [comment]
I believe this has been fixed. Have you updated the code?

**Comment by kaikalur** [comment]
Oh this is MAP_UNION_SUM! let me check

**Comment by mbasmanova** [comment]
@kaikalur Sreeni, any update on this?

**Comment by kaikalur** [comment]
No not really :) it's a crash so I'm going to fix it at some point if needed. We haven't seen this much in our prod.

**Comment by tdcmeehan** [comment]
This seems like a pretty simple fix.  If I'm not mistaken, we simply needs to change this line: https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/aggregation/MapUnionSumResult.java#L78

Perhaps by adding an if/else check to see if it's REAL (or ideally a more clever solution).

**Comment by mbasmanova** [comment]
CC: @karteekmurthys @aditi-pandit

**Comment by tsafacjo** [comment]
can I take this issue ?

**Comment by tdcmeehan** [comment]
Please go ahead @tsafacjo

**Comment by yyy1000** [comment]
Hi, I want to help this issue in #21604 :)

**Comment by mbasmanova** [comment]
@yyy1000 Thank you for helping fix this issue.
