### ISSUE TITLE
[Native] - Query with select count distinct failing with "No nodes available to run query" if run under spilling enabled configuration

### ISSUE THREAD

**Issue by mknegi** [prestodb/presto#20982]
## Expected Behavior

Following query fails with error "No nodes available to run query" when run under a specific configuration. Strangely though no stack trace is generated for any of the workers.
```
        assertQuery(builder(TEST_SESSION)
                        .setSystemProperty("use_mark_distinct", "false")
                        .build(),
                " SELECT COUNT(*) FROM (SELECT orderkey, COUNT(DISTINCT partkey) FROM lineitem " +
                        "  GROUP BY orderkey " +
                        "HAVING COUNT(DISTINCT partkey) != CARDINALITY(ARRAY_DISTINCT(ARRAY_AGG(partkey))))",
                "VALUES 0");
```

**Configuration Used:**
Set the following configuration parameters in the session:
```
set session AGGREGATION_OPERATOR_UNSPILL_MEMORY_LIMIT='128kB';
set session TASK_CONCURRENCY=2;
set session DEDUP_BASED_DISTINCT_AGGREGATION_SPILL_ENABLED=false;
set session USE_MARK_DISTINCT=false;
```

Set the following properties in the config.properties file
```
experimental.spill-enabled=true
experimental.spiller-spill-path=/Users/mknegi/tmp/spill
experimental.spiller-max-used-space-threshold=1.0
experimental.memory-revoking-threshold=0.0
experimental.memory-revoking-target=0.0
```

## Current Behavior

```
Caused by: com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.spi.NodeManager.getRequiredWorkerNodes(NodeManager.java:34)
	at com.facebook.presto.tpch.TpchNodePartitioningProvider.getBucketNodeMap(TpchNodePartitioningProvider.java:53)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getConnectorBucketNodeMap(NodePartitioningManager.java:223)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getBucketNodeMap(NodePartitioningManager.java:181)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:344)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:252)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:230)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:176)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:355)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:244)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:173)
	at com.facebook.presto.execution.SqlQueryExecution.getScheduler(SqlQueryExecution.java:633)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:614)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:457)
	at com.facebook.presto.$gen.Presto_null__testversion____20230926_100834_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:306)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Some excerpts from the workers log, not sure if these would lead into the problem eventually:
```
I20230926 21:36:33.392150 4725476 TaskManager.cpp:549] Deleting task 20230926_160632_00002_5y8ue.2.0.1.0
I20230926 21:36:33.392419 4726390 PrestoExchangeSource.cpp:224] Fetched data for /v1/task/20230926_160632_00002_5y8ue.2.0.3.0/results/1/2: 0 bytes
I20230926 21:36:33.392467 4726390 PrestoExchangeSource.cpp:231] Received buffer-complete header for /v1/task/20230926_160632_00002_5y8ue.2.0.3.0/results/1/2
I20230926 21:36:33.392499 4726390 PrestoExchangeSource.cpp:289] Enqueuing empty page for /v1/task/20230926_160632_00002_5y8ue.2.0.3.0/results/1/2
I20230926 21:36:33.392565 4726390 PrestoExchangeSource.cpp:383] Sending abort results /v1/task/20230926_160632_00002_5y8ue.2.0.3.0/results/1
I20230926 21:36:33.393939 4726377 PrestoExchangeSource.cpp:224] Fetched data for /v1/task/20230926_160632_00002_5y8ue.2.0.0.0/results/1/2: 0 bytes
I20230926 21:36:33.394037 4726377 PrestoExchangeSource.cpp:231] Received buffer-complete header for /v1/task/20230926_160632_00002_5y8ue.2.0.0.0/results/1/2
I20230926 21:36:33.394083 4726377 PrestoExchangeSource.cpp:289] Enqueuing empty page for /v1/task/20230926_160632_00002_5y8ue.2.0.0.0/results/1/2
I20230926 21:36:33.394424 4726296 PrestoExchangeSource.cpp:383] Sending abort results /v1/task/20230926_160632_00002_5y8ue.2.0.0.0/results/1
I20230926 21:36:33.395223 4726377 PrestoExchangeSource.cpp:383] Sending abort results /v1/task/20230926_160632_00002_5y8ue.2.0.0.0/results/1
```

**Comment by ashokku2022** [comment]
Assigning it to @pdabre12 to work on it in the backend when he finds time in between.

**Comment by ashokku2022** [comment]
Talking with Aditi, seems like there are multiple cleanup efforts in progress for spill functionality so would not start the work yet @pdabre12

**Comment by yzhang1991** [comment]
@mknegi can we try this again to see if latest changes got this fixed?

**Comment by mknegi** [comment]
Tried the steps against the latest builds and it doesn't reproduce anymore therefore closing this issue.
