### ISSUE TITLE
Product test product-tests-basic-environment fails frequently with no space left on device

### ISSUE THREAD

**Issue by nmahadevuni** [prestodb/presto#20984]
The product test `product-tests-basic-environment` is failing frequently with `failed to register layer: write /usr/share/ghostscript/8.70/Resource/CMap/UniCNS-UTF16-H: no space left on device`

## Your Environment
Presto CI checks

## Possible Solution
Its possible that recent test additions to CI checks is causing an increase in the required disk space. Either queue the CI checks to limit the number of PRs that can run CI checks simultaneously or assuming all tests are run on a shared cluster, the number of parallel jobs that are run can be reduced for e.g., there are three product tests, product-test-basic-environment, product-test-specific-environment1, product-test-specific-environment2 can be run sequentially since they are resource heavy.

**Comment by nmahadevuni** [comment]
@wanglinsong Can you please check this?

**Comment by pratyakshsharma** [comment]
Few sample failures - 
https://github.com/prestodb/presto/actions/runs/6337095783/job/17211471012?pr=19872
https://github.com/prestodb/presto/actions/runs/6337095787/job/17211473346?pr=19872
https://github.com/prestodb/presto/actions/runs/6337095787/job/17211473632?pr=19872

**Comment by tdcmeehan** [comment]
CC: @mshang816 who is looking into using larger runners to help solve this.  Perhaps we could also divide the product tests into more partitions?

**Comment by tdcmeehan** [comment]
See #20976

**Comment by mshang816** [comment]
the two jobs make a series of calls to run_on_docker.sh. Not sure if it's because some leftover from docker contains runs

**Comment by mshang816** [comment]
But it looks there is a cleanup function already

**Comment by tdcmeehan** [comment]
Giving #20988 a try as well to see if that helps to resolve it.

**Comment by ZacBlanco** [comment]
I also took a stab at a band-aid fix here: https://github.com/prestodb/presto/pull/21000

**Comment by pratyakshsharma** [comment]
Singlestore dockerized tests are failing with the same error now. Below is the stacktrace - 

```
Error:  Tests run: 535, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 751.824 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping.init  Time elapsed: 14.292 s  <<< FAILURE!
java.sql.SQLException: (conn=370) Not enough disk space to create or attach database tpch on leaf 127.0.0.1:3307.  Estimate Available 11407 MB, Estimate Needed 12736 MB.
	at com.singlestore.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:216)
	at com.singlestore.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:250)
	at com.singlestore.jdbc.message.ClientMessage.readPacket(ClientMessage.java:85)
	at com.singlestore.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:711)
	at com.singlestore.jdbc.client.impl.StandardClient.readResults(StandardClient.java:659)
	at com.singlestore.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:582)
	at com.singlestore.jdbc.client.impl.StandardClient.execute(StandardClient.java:556)
	at com.singlestore.jdbc.Statement.executeInternal(Statement.java:900)
	at com.singlestore.jdbc.Statement.execute(Statement.java:1024)
	at com.singlestore.jdbc.Statement.execute(Statement.java:431)
	at com.facebook.presto.plugin.singlestore.SingleStoreQueryRunner.createSchema(SingleStoreQueryRunner.java:85)
	at com.facebook.presto.plugin.singlestore.SingleStoreQueryRunner.createSingleStoreQueryRunner(SingleStoreQueryRunner.java:65)
	at com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping.createQueryRunner(TestSingleStoreTypeMapping.java:72)
	at com.facebook.presto.tests.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Sample run - https://github.com/prestodb/presto/actions/runs/6388621591/job/17338765149?pr=19872

**Comment by tdcmeehan** [comment]
> Singlestore dockerized tests are failing with similar error now. Below is the stacktrace -
> 
> ```
> Error:  Tests run: 535, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 751.824 s <<< FAILURE! - in TestSuite
> Error:  com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping.init  Time elapsed: 14.292 s  <<< FAILURE!
> java.sql.SQLException: (conn=370) Not enough disk space to create or attach database tpch on leaf 127.0.0.1:3307.  Estimate Available 11407 MB, Estimate Needed 12736 MB.
> 	at com.singlestore.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:216)
> 	at com.singlestore.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:250)
> 	at com.singlestore.jdbc.message.ClientMessage.readPacket(ClientMessage.java:85)
> 	at com.singlestore.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:711)
> 	at com.singlestore.jdbc.client.impl.StandardClient.readResults(StandardClient.java:659)
> 	at com.singlestore.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:582)
> 	at com.singlestore.jdbc.client.impl.StandardClient.execute(StandardClient.java:556)
> 	at com.singlestore.jdbc.Statement.executeInternal(Statement.java:900)
> 	at com.singlestore.jdbc.Statement.execute(Statement.java:1024)
> 	at com.singlestore.jdbc.Statement.execute(Statement.java:431)
> 	at com.facebook.presto.plugin.singlestore.SingleStoreQueryRunner.createSchema(SingleStoreQueryRunner.java:85)
> 	at com.facebook.presto.plugin.singlestore.SingleStoreQueryRunner.createSingleStoreQueryRunner(SingleStoreQueryRunner.java:65)
> 	at com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping.createQueryRunner(TestSingleStoreTypeMapping.java:72)
> 	at com.facebook.presto.tests.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:83)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
> 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
> 	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
> 	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
> 	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
> 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:750)
> ```
> 
> Sample run - https://github.com/prestodb/presto/actions/runs/6388621591/job/17338765149?pr=19872

CC: @oyeliseiev-ua

**Comment by karteekmurthys** [comment]
Another failure with no disk space left: https://github.com/prestodb/presto/actions/runs/6410514523/job/17403977560?pr=20812

```
Error:  Tests run: 535, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 1,102.629 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping.init  Time elapsed: 17.298 s  <<< FAILURE!
java.sql.SQLException: (conn=517) Not enough disk space to create or attach database tpch on leaf 127.0.0.1:3307.  Estimate Available 11397 MB, Estimate Needed 12736 MB.
	at com.singlestore.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:216)
	at com.singlestore.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:250)
	at com.singlestore.jdbc.message.ClientMessage.readPacket(ClientMessage.java:85)
	at com.singlestore.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:711)
	at com.singlestore.jdbc.client.impl.StandardClient.readResults(StandardClient.java:659)
	at com.singlestore.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:582)
	at com.singlestore.jdbc.client.impl.StandardClient.execute(StandardClient.java:556)
```

**Comment by ZacBlanco** [comment]
I've created https://github.com/prestodb/presto/issues/21038 to track this specific issue with Singlestore. It seems like a weird error or configuration bug coming from the Singlestore docker image.

Since #21000 has been merged I don't think there have been any errors due to disk space. We should probably close this issue and move any discussion with Singlestore tests to #21038

**Comment by tdcmeehan** [comment]
Agreed, closing.  Thanks @ZacBlanco
