### ISSUE TITLE
Singlestore tests fail with Not enough disk space 

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#21038]
GH Actions CI are failing pretty frequently with an error like:

```
Error:  Tests run: 535, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 1,102.629 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.plugin.singlestore.TestSingleStoreTypeMapping.init  Time elapsed: 17.298 s  <<< FAILURE!
java.sql.SQLException: (conn=517) Not enough disk space to create or attach database tpch on leaf 127.0.0.1:3307.  Estimate Available 11397 MB, Estimate Needed 12736 MB.
	at com.singlestore.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:216)
	at com.singlestore.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:250)
	at com.singlestore.jdbc.message.ClientMessage.readPacket(ClientMessage.java:85)
	at com.singlestore.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:711)
	at com.singlestore.jdbc.client.impl.StandardClient.readResults(StandardClient.java:659)
	at com.singlestore.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:582)
	at com.singlestore.jdbc.client.impl.StandardClient.execute(StandardClient.java:556)
```

## Your Environment

GH Actions CI Runner

## Expected Behavior

No Failures

## Current Behavior

CI fails to create schema, even with > 10G of disk space available.

## Possible Solution

Investigating...

**Comment by gs-kotang** [comment]
> New instance from yesterday https://github.com/prestodb/presto/actions/runs/6476432057/job/17585144192?pr=21097

Is the new instance a bigger instance?
