### ISSUE TITLE
HiveExternalWorkerQueryRunner fails to run queries "No nodes available to run query"

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#21103]
Following https://github.com/prestodb/presto/tree/master/presto-native-execution#build-from-source, and start HiveExternalWorkerQueryRunner and presto_server as directed. The HiveExternalWorkerQueryRunner and presto_server started successfully, and was able to run show schemas or show tables, but failed to run select queries:

```
presto:tpch> select * from tpch.sf1.lineitem;
Query 20231010_071426_00002_hmtb9 failed: No nodes available to run query
com.facebook.presto.spi.PrestoException: No nodes available to run query
	at com.facebook.presto.spi.NodeManager.getRequiredWorkerNodes(NodeManager.java:34)
	at com.facebook.presto.tpch.TpchNodePartitioningProvider.getBucketNodeMap(TpchNodePartitioningProvider.java:53)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getConnectorBucketNodeMap(NodePartitioningManager.java:223)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getBucketNodeMap(NodePartitioningManager.java:181)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStageScheduler(SectionExecutionFactory.java:344)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:252)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createStreamingLinkedStageExecutions(SectionExecutionFactory.java:230)
	at com.facebook.presto.execution.scheduler.SectionExecutionFactory.createSectionExecutions(SectionExecutionFactory.java:176)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createStageExecutions(LegacySqlQueryScheduler.java:355)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.<init>(LegacySqlQueryScheduler.java:244)
	at com.facebook.presto.execution.scheduler.LegacySqlQueryScheduler.createSqlQueryScheduler(LegacySqlQueryScheduler.java:173)
	at com.facebook.presto.execution.SqlQueryExecution.getScheduler(SqlQueryExecution.java:633)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:614)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:457)
	at com.facebook.presto.$gen.Presto_null__testversion____20231010_070813_9.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:306)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:211)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
## Your Environment
* Presto version used: latest master as of today
* Storage (HDFS/S3/GCS..):  MacOS
* Data source and connector used: tpch

**Comment by yingsu00** [comment]
cc @pramodsatya @aditi-pandit

**Comment by yingsu00** [comment]
In HiveExternalWorkerQueryRunner, there was a recent change "[native] Create all tables when launching HiveExternalWorkerQueryRunner". Not sure if it's related.

**Comment by pramodsatya** [comment]
The tables are only created in the default catalog/schema, which is hive/tpch. The Tpch connector is not present for the native worker and this is the expected error: https://github.com/prestodb/presto/blob/master/presto-native-execution/src/test/java/com/facebook/presto/nativeworker/AbstractTestNativeTpchConnectorQueries.java#L32 .

**Comment by majetideepak** [comment]
As Pramod mentioned, there is no `tpch` catalog registered by HiveExternalWorkerQueryRunner. However, there is a `tpchstandard` catalog with `tiny` schema.
Closing this.
