### ISSUE TITLE
Assertion Failure in revocable memory in SpillableHashAggregationBuilder

### ISSUE THREAD

**Issue by vermapratyush** [prestodb/presto#21134]
After https://github.com/prestodb/presto/pull/20360 was landed, we are seeing assertion failure in SpillableHashAggregationBuilder.
The codepath which contains the assertion is never triggered in any of the unit test.

## Current Behavior
Stacktrace:
```
23/10/12 06:10:13 ERROR (TID 337) TaskExecutor: Error processing Split 20231012_122637_00000_urafm.7.0.82.0-48  (start = 8.4884298582635E8, wall = 273809 ms, cpu = 57000 ms, wait = 465 ms, calls = 7143)
com.google.common.base.VerifyException
        at com.google.common.base.Verify.verify(Verify.java:100)
        at com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder.startMemoryRevoke(SpillableHashAggregationBuilder.java:181)
        at com.facebook.presto.operator.HashAggregationOperator.startMemoryRevoke(HashAggregationOperator.java:412)
        at com.facebook.presto.operator.Driver.handleMemoryRevoke(Driver.java:541)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:386)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
        at com.facebook.presto.spark.execution.task.PrestoSparkTaskExecution$DriverSplitRunner.processFor(PrestoSparkTaskExecution.java:480)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
        at com.facebook.presto.$gen.Presto_0_285_SNAPSHOT_0512e06____20231012_130516_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Possible Solution
One hypothesis is that under rehashing scenario we are not updating the correct memory context.

## Steps to Reproduce
A number of internal queries fail.
N/A working on a repro for OSS.

## Context
This bug blocks internal rollout as a number of query which trigger spilling crashes.

**Comment by hantangwangd** [comment]
Do you have some explicit steps to reproduce this problem?

**Comment by vermapratyush** [comment]
@hantangwangd  The issue is in the lambda `updateMmory` passed to InMemoryHashAggregationBuilder. The correct lambda would be:
```
Optional.of((memorySize) -> {
    if (producingOutput) {
        localUserMemoryContext.setBytes(memorySize);
    }
    else {
        localRevocableMemoryContext.setBytes(memorySize);
    }
}));
```

This lambda is also called as part of spillable accumulators like `DedupBasedSpillableDistinctGroupedAccumulator` during during rehash while the operator is producing output. During this stage the memory should be part of user memory and non-revocable.

Notice the code flow in the following stacktrace:
```
java.lang.Throwable
        at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.logMemory(InMemoryHashAggregationBuilder.java:506)
        at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.updateMemoryWithYieldInfo(InMemoryHashAggregationBuilder.java:384)
        at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.lambda$new$0(InMemoryHashAggregationBuilder.java:166)
        at com.facebook.presto.operator.aggregation.GenericAccumulatorFactory$DistinctingGroupedAccumulator.lambda$createMarkDistinctHash$0(GenericAccumulatorFactory.java:557)
        at com.facebook.presto.operator.MultiChannelGroupByHash.tryRehash(MultiChannelGroupByHash.java:449)
        at com.facebook.presto.operator.MultiChannelGroupByHash.addNewGroup(MultiChannelGroupByHash.java:362)
        at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:326)
        at com.facebook.presto.operator.MultiChannelGroupByHash.putIfAbsent(MultiChannelGroupByHash.java:298)
        at com.facebook.presto.operator.MultiChannelGroupByHash.access$200(MultiChannelGroupByHash.java:56)
        at com.facebook.presto.operator.MultiChannelGroupByHash$GetNonDictionaryGroupIdsWork.process(MultiChannelGroupByHash.java:757)
        at com.facebook.presto.operator.TransformWork.process(TransformWork.java:40)
        at com.facebook.presto.operator.aggregation.GenericAccumulatorFactory$DistinctingGroupedAccumulator.computeDistinctMask(GenericAccumulatorFactory.java:640)
        at com.facebook.presto.operator.aggregation.GenericAccumulatorFactory$DistinctingGroupedAccumulator.addInput(GenericAccumulatorFactory.java:584)
        at com.facebook.presto.operator.aggregation.GenericAccumulatorFactory$SpillableFinalOnlyGroupedAccumulator.prepareFinal(GenericAccumulatorFactory.java:1123)
        at com.facebook.presto.operator.aggregation.GenericAccumulatorFactory$DedupBasedSpillableDistinctGroupedAccumulator.prepareFinal(GenericAccumulatorFactory.java:1219)
        at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder$Aggregator.prepareFinal(InMemoryHashAggregationBuilder.java:465)
        at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.buildResult(InMemoryHashAggregationBuilder.java:302)
        at com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder.buildResult(SpillableHashAggregationBuilder.java:225)
        at com.facebook.presto.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:460)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:428)
        at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
        at com.facebook.presto.spark.execution.task.PrestoSparkTaskExecution$DriverSplitRunner.processFor(PrestoSparkTaskExecution.java:480)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
        at com.facebook.presto.$gen.Presto_0_285_SNAPSHOT_afca768____20231012_170616_1.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by hantangwangd** [comment]
@vermapratyush Oh I see, it's a great catch. Thanks for fix.
