### ISSUE TITLE
Read delta lake tables with Apache Presto: readDirect unsupported in RemoteBlockReader

### ISSUE THREAD

**Issue by daniellj** [prestodb/presto#21283]
Hi, everyone.

We are having problems reading delta lake tables (stored in Hadoop HDFS) through Apache Presto. We run the query using the Apache Presto SQL engine through presto-cli (0.283), DBeaver (IDE) and Qlik Sense.

select * from delta.gold.MY_TABLE limit 10

error: “readDirect unsupported in RemoteBlockReader” 

**If we execute the same query through an Apache Spark cluster session, the data is read successfully.**

## Here's the architecture (environment on-premises)

Cluster A: Apache Hadoop 3.3.4 with HDFS service with 3 data nodes (replication factor = 3). There is a data lake layer and a delta lake (tables created with Apache Spark via PySpark).

Cluster B: Apache Spark 3.3.0 with 6 worker nodes + Python 3.10 with libraries: pyspark 3.3.0 and delta-spark 2.3.0

Metadata: Apache Hive 3.1.3 (every table created with Apache Spark, the Apache Hive stores the metadata (HDFS path, schema name, table name, attributes, comments, etc.)

SQL Engine Apache Presto 0.283-1FA586A

All servers run with jdk-8u341.

## Delta Lake create table
```
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DecimalType, LongType, DateType, TimestampType 

DeltaTable.createIfNotExists(sparkSession=s_session_delta) \ 

  .tableName("gold.MY_TABLE") \ 
  .addColumn("COLUMN_A", dataType=LongType(), nullable=False) \ 
  .addColumn("COLUMN_B", dataType=LongType(), nullable=False) \ 
  .addColumn("COLUMN_C", dataType=StringType(), nullable=False) \ 
	...
	...
	...
  .addColumn("COLUMN_N", dataType=TimestampType(), nullable=False) \ 
  .property("description", "MMMMMMMMMMMMMMMMMMMM") \ 
  .location("hdfs://HDFS_SERVERNAME:HDFS_SERVER_PORT/data/deltalake/gold/MY_TABLE") \ 
  .execute() 
```

This table has 59 fields.

## Apache Presto configuration files
The contents of the following files are all located on the Apache Presto coordinator node:

**delta.properties**
```
connector.name=delta 
hive.metastore.uri=thrift://metastore-hive:9083 
```

**node.properties**
```
node.environment=production 
node.data-dir=/var/apache-presto/data 
```

**jvm.config**
```
-server 
-Xmx16G 
-XX:+UseG1GC 
-XX:G1HeapRegionSize=32M 
-XX:+UseGCOverheadLimit 
-XX:+ExplicitGCInvokesConcurrent 
-XX:+HeapDumpOnOutOfMemoryError 
-XX:+ExitOnOutOfMemoryError 
```

** log.properties**
com.facebook.presto=DEBUG 

**config.properties**
```
http-server.http.port=10500 
query.max-memory=10GB 
query.max-memory-per-node=2GB 
discovery.uri=http://apache-presto-coordinator1:10500 
```

**core-site.xml**
```
<configuration> 
<property> 
<name>fs.defaultFS</name> 
<value>hdfs://HDFS_SERVERNAME:HDFS_SERVER_PORT</value> 
  <description>URI do namenode.</description> 
</property> 
</configuration> 
```

**hdfs-site.xml**
```
<configuration> 
  <property> 
    <name>dfs.namenode.name.dir</name> 
    <value>/data/hdfs/namenode/HDFS_SERVERNAME</value> 
  </property> 
  <property> 
    <name>dfs.namenode.fs-limits.min-block-size</name> 
    <value>32</value> 
  </property> 
  <property> 
      <name>dfs.replication</name> 
      <value>3</value> 
    </property> 
  <property> 
    <name>dfs.namenode.handler.count</name> 
    <value>1</value> 
  </property> 
  <property> 
<name>dfs.client.use.datanode.hostname</name> 
<value>true</value> 
  <description>Whether clients should use datanode hostnames when connecting to datanodes.</description> 
  </property> 
  <property> 
<name>dfs.client.use.legacy.blockreader</name> 
<value>false</value> 
  </property> 
</configuration>
```

## The error trace when we trigger the query through Apache Presto

Error Type: INTERNAL_ERROR
Error Code: GENERIC_INTERNAL_ERROR (65536)
Stack Trace: 
 
**java.lang.UnsupportedOperationException: readDirect unsupported in RemoteBlockReader**
at org.apache.hadoop.hdfs.RemoteBlockReader.read(RemoteBlockReader.java:492)
at org.apache.hadoop.hdfs.DFSInputStream$ByteBufferStrategy.doRead(DFSInputStream.java:789)
at org.apache.hadoop.hdfs.DFSInputStream.readBuffer(DFSInputStream.java:823)
at org.apache.hadoop.hdfs.DFSInputStream.readWithStrategy(DFSInputStream.java:883)
at org.apache.hadoop.hdfs.DFSInputStream.read(DFSInputStream.java:938)
at org.apache.hadoop.fs.FSDataInputStream.read(FSDataInputStream.java:143)
at shadedelta.org.apache.parquet.hadoop.util.H2SeekableInputStream$H2Reader.read(H2SeekableInputStream.java:81)
at shadedelta.org.apache.parquet.hadoop.util.H2SeekableInputStream.readFully(H2SeekableInputStream.java:90)
at shadedelta.org.apache.parquet.hadoop.util.H2SeekableInputStream.readFully(H2SeekableInputStream.java:75)
at shadedelta.org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:575)
at shadedelta.org.apache.parquet.hadoop.ParquetFileReader.<init>(ParquetFileReader.java:776)
at shadedelta.org.apache.parquet.hadoop.ParquetFileReader.open(ParquetFileReader.java:657)
at shadedelta.org.apache.parquet.hadoop.ParquetReader.initReader(ParquetReader.java:152)
at shadedelta.org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:135)
at shadedelta.com.github.mjakubowski84.parquet4s.ParquetIterableImpl$$anon$3.hasNext(ParquetReader.scala:144)
at io.delta.standalone.internal.actions.CustomParquetIterator.hasNext(MemoryOptimizedLogReplay.scala:132)
at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.$anonfun$ensureNextIterIsReady$3(MemoryOptimizedLogReplay.scala:81)
at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.$anonfun$ensureNextIterIsReady$3$adapted(MemoryOptimizedLogReplay.scala:81)
at scala.Option.exists(Option.scala:376)
at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.ensureNextIterIsReady(MemoryOptimizedLogReplay.scala:81)
at io.delta.standalone.internal.actions.MemoryOptimizedLogReplay$$anon$1.hasNext(MemoryOptimizedLogReplay.scala:90)
at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
at scala.collection.Iterator.foreach(Iterator.scala:943)
at scala.collection.Iterator.foreach$(Iterator.scala:943)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
at io.delta.standalone.internal.SnapshotImpl.loadTableProtocolAndMetadata(SnapshotImpl.scala:141)
at io.delta.standalone.internal.SnapshotImpl.x$1$lzycompute(SnapshotImpl.scala:131)
at io.delta.standalone.internal.SnapshotImpl.x$1(SnapshotImpl.scala:131)
at io.delta.standalone.internal.SnapshotImpl.protocolScala$lzycompute(SnapshotImpl.scala:131)
at io.delta.standalone.internal.SnapshotImpl.protocolScala(SnapshotImpl.scala:131)
at io.delta.standalone.internal.SnapshotImpl.<init>(SnapshotImpl.scala:272)
at io.delta.standalone.internal.SnapshotManagement.createSnapshot(SnapshotManagement.scala:257)
at io.delta.standalone.internal.SnapshotManagement.getSnapshotAtInit(SnapshotManagement.scala:224)
at io.delta.standalone.internal.SnapshotManagement.$init$(SnapshotManagement.scala:37)
at io.delta.standalone.internal.DeltaLogImpl.<init>(DeltaLogImpl.scala:47)
at io.delta.standalone.internal.DeltaLogImpl$.apply(DeltaLogImpl.scala:263)
at io.delta.standalone.internal.DeltaLogImpl$.forTable(DeltaLogImpl.scala:245)
at io.delta.standalone.internal.DeltaLogImpl.forTable(DeltaLogImpl.scala)
at io.delta.standalone.DeltaLog.forTable(DeltaLog.java:176)
at com.facebook.presto.delta.DeltaClient.loadDeltaTableLog(DeltaClient.java:151)
at com.facebook.presto.delta.DeltaClient.getTable(DeltaClient.java:79)
at com.facebook.presto.delta.DeltaMetadata.getTableHandle(DeltaMetadata.java:220)
at com.facebook.presto.delta.DeltaMetadata.getTableHandle(DeltaMetadata.java:73)
at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:220)
at com.facebook.presto.metadata.MetadataUtil.getOptionalTableHandle(MetadataUtil.java:180)
at com.facebook.presto.metadata.MetadataManager$1.getTableHandle(MetadataManager.java:1331)
at com.facebook.presto.util.MetadataUtils.lambda$getTableColumnMetadata$2(MetadataUtils.java:83)
at com.facebook.presto.common.RuntimeStats.profileNanos(RuntimeStats.java:136)
at com.facebook.presto.util.MetadataUtils.getTableColumnMetadata(MetadataUtils.java:81)
at com.facebook.presto.util.MetadataUtils.getTableColumnsMetadata(MetadataUtils.java:54)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1282)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:338)
at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2596)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1615)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:338)
at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:360)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1116)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:338)
at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:352)
at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:330)
at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:117)
at com.facebook.presto.sql.analyzer.BuiltInQueryAnalyzer.analyze(BuiltInQueryAnalyzer.java:93)
at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:203)
at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:107)
at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:955)
at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:167)
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

**Comment by agrawalreetika** [comment]
Hi @daniellj 
I tried the below steps for creating Delta table from Spark and reading Delta table from Presto which worked fine for me. 
Am I missing anything here?

**Steps to create Delta Table -**
pyspark --packages io.delta:delta-core_2.12:1.2.1 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
```
spark.sql("CREATE TABLE delta_schema.sampletable_delta(id int, creation_date varchar(100)) USING DELTA TBLPROPERTIES(delta.compatibility.symlinkFormatManifest.enabled=true)");
// Insert 2 rows
spark.sql("INSERT INTO delta_schema.sampletable_delta values(100,'2015-01-01')");
spark.sql("INSERT INTO delta_schema.sampletable_delta values(101,'2015-01-02')");
```

**Version details -**
Local Setup :
spark-3.2.0
apache-hive-3.1.2
hadoop-3.3.4
presto - current master

**Read from Presto Delta connector -**
![image](https://github.com/prestodb/presto/assets/7887476/544def4b-f7c6-4e69-b2f1-f39b335fd1c3)

**Comment by daniellj** [comment]
Hi!

Thanks for the reply, @agrawalreetika !

I understood what you did, it's very similar to what I'm doing. But my scenario has some details in 2 tables to which the problem of reading Delta Lake data through Apache Presto occurs.

- Table "A": has 59 fields
- Table "B": has 4 fields, one of which is of type STRING and there are records within this field with polygon coordinates containing more than 700,000 characters.

I've tried all the fixes proposed by the bug in the link: https://github.com/prestodb/presto/issues/18431

But I can't fix my problem.

**Comment by daniellj** [comment]
Hi!

I solve the problem.

I was wondering, how will **Apache Presto** know what the Hadoop files are? So I added the following entry to /opt/apache-presto/etc/catalog/delta.properties:

`hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml`

The file /opt/apache-presto/etc/catalog/delta.properties looked like this:

```
connector.name=delta
hive.metastore.uri=thrift://metastore-hive:9083
hive.config.resources=/etc/hadoop/conf/core-site.xml,/etc/hadoop/conf/hdfs-site.xml
```

Thanks, I hope this helps other people.

**Comment by agrawalreetika** [comment]
Thank you @daniellj for providing the details of what worked for you. This would definitely help others facing similar issue.
So we should add `core-site.xml` & `hdfs-site.xml` in `hive.config.resources` as part of catalog configuration to supply Hadoop cluster confirgutation to solve above issue.

**Comment by agrawalreetika** [comment]
I was wondering which Hadoop cluster/file property, specifically would have helped here which was needed to be supplied as part of Presto config resource?
