### ISSUE TITLE
TestPrestoSparkQueryRunner failed due to the error message mismatch

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#21346]
Full log at https://github.com/prestodb/presto/actions/runs/6797978256?pr=20699

TestPrestoSparkQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold expects an error message with the detailed info `\[Broadcast size: 2.*MB\]` but the actual message was `[Allocated: 2.00MB, Delta: 9.97kB (HashBuilderOperator), Top Consumers: {HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"2.00MB","topConsumers":[{"type":"HashBuilderOperator","planNodeId":"4","reservations":["666.16kB","582.90kB","544.91kB","253.55kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]` 

It seems the test need to update the expected messages to be the latest in code.

```
2023-11-08T12:35:53.4069053Z [ERROR] Tests run: 1282, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1,378.35 s <<< FAILURE! - in TestSuite
2023-11-08T12:35:53.4071636Z [ERROR] com.facebook.presto.spark.adaptive.execution.TestPrestoSparkAdaptiveQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold  Time elapsed: 1.495 s  <<< FAILURE!
2023-11-08T12:35:53.4081645Z java.lang.AssertionError: Expected exception message 'Query exceeded per-node broadcast memory limit of 2MB [Allocated: 2.00MB, Delta: 9.97kB (HashBuilderOperator), Top Consumers: {HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"2.00MB","topConsumers":[{"type":"HashBuilderOperator","planNodeId":"4","reservations":["666.16kB","582.90kB","544.91kB","253.55kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]' to match 'Query exceeded per-node broadcast memory limit of 2MB \[Broadcast size: 2.*MB\]' for query: select * from lineitem l join orders o on l.orderkey = o.orderkey
2023-11-08T12:35:53.4085956Z 	at org.testng.Assert.fail(Assert.java:98)
2023-11-08T12:35:53.4087058Z 	at com.facebook.presto.tests.QueryAssertions.assertExceptionMessage(QueryAssertions.java:351)
2023-11-08T12:35:53.4088566Z 	at com.facebook.presto.tests.QueryAssertions.assertQueryFails(QueryAssertions.java:332)
2023-11-08T12:35:53.4090222Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:282)
2023-11-08T12:35:53.4092529Z 	at com.facebook.presto.spark.TestPrestoSparkQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold(TestPrestoSparkQueryRunner.java:933)
2023-11-08T12:35:53.4094379Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-08T12:35:53.4095519Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-11-08T12:35:53.4096876Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-08T12:35:53.4097984Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-11-08T12:35:53.4099229Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2023-11-08T12:35:53.4100697Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2023-11-08T12:35:53.4101986Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2023-11-08T12:35:53.4103540Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2023-11-08T12:35:53.4105126Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2023-11-08T12:35:53.4106559Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2023-11-08T12:35:53.4108014Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2023-11-08T12:35:53.4109432Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2023-11-08T12:35:53.4110893Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-11-08T12:35:53.4112193Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-11-08T12:35:53.4113153Z 	at java.lang.Thread.run(Thread.java:750)
2023-11-08T12:35:53.4116946Z Caused by: com.facebook.presto.ExceededMemoryLimitException: Query exceeded per-node broadcast memory limit of 2MB [Allocated: 2.00MB, Delta: 9.97kB (HashBuilderOperator), Top Consumers: {HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"2.00MB","topConsumers":[{"type":"HashBuilderOperator","planNodeId":"4","reservations":["666.16kB","582.90kB","544.91kB","253.55kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]
2023-11-08T12:35:53.4121102Z 	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:60)
2023-11-08T12:35:53.4123157Z 	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:396)
2023-11-08T12:35:53.4125216Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.executeWithRetryStrategies(PrestoSparkQueryRunner.java:525)
2023-11-08T12:35:53.4126943Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:508)
2023-11-08T12:35:53.4128409Z 	at com.facebook.presto.tests.QueryAssertions.assertQueryFails(QueryAssertions.java:328)
2023-11-08T12:35:53.4129370Z 	... 17 more
2023-11-08T12:35:53.4129615Z 
2023-11-08T12:35:53.4130904Z [ERROR] com.facebook.presto.spark.TestPrestoSparkQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold  Time elapsed: 0.478 s  <<< FAILURE!
2023-11-08T12:35:53.4138030Z java.lang.AssertionError: Expected exception message 'Query exceeded per-node broadcast memory limit of 2MB [Allocated: 2.00MB, Delta: 7.51kB (HashBuilderOperator), Top Consumers: {PrestoSparkRemoteSourceOperator=3.88MB, HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"5.88MB","topConsumers":[{"type":"PrestoSparkRemoteSourceOperator","planNodeId":"238","reservations":["3.88MB","0B"],"total":"3.88MB"},{"type":"HashBuilderOperator","planNodeId":"4","reservations":["657.92kB","655.67kB","372.46kB","360.00kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]' to match 'Query exceeded per-node broadcast memory limit of 2MB \[Broadcast size: 2.*MB\]' for query: select * from lineitem l join orders o on l.orderkey = o.orderkey
2023-11-08T12:35:53.4143226Z 	at org.testng.Assert.fail(Assert.java:98)
2023-11-08T12:35:53.4144571Z 	at com.facebook.presto.tests.QueryAssertions.assertExceptionMessage(QueryAssertions.java:351)
2023-11-08T12:35:53.4146086Z 	at com.facebook.presto.tests.QueryAssertions.assertQueryFails(QueryAssertions.java:332)
2023-11-08T12:35:53.4147744Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:282)
2023-11-08T12:35:53.4150047Z 	at com.facebook.presto.spark.TestPrestoSparkQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold(TestPrestoSparkQueryRunner.java:933)
2023-11-08T12:35:53.4151922Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-08T12:35:53.4153054Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2023-11-08T12:35:53.4154393Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-08T12:35:53.4155495Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2023-11-08T12:35:53.4156861Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2023-11-08T12:35:53.4158326Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2023-11-08T12:35:53.4159624Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2023-11-08T12:35:53.4160952Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2023-11-08T12:35:53.4162346Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2023-11-08T12:35:53.4163902Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2023-11-08T12:35:53.4165380Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2023-11-08T12:35:53.4166427Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2023-11-08T12:35:53.4167185Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2023-11-08T12:35:53.4168051Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2023-11-08T12:35:53.4168685Z 	at java.lang.Thread.run(Thread.java:750)
2023-11-08T12:35:53.4171692Z Caused by: com.facebook.presto.ExceededMemoryLimitException: Query exceeded per-node broadcast memory limit of 2MB [Allocated: 2.00MB, Delta: 7.51kB (HashBuilderOperator), Top Consumers: {PrestoSparkRemoteSourceOperator=3.88MB, HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"5.88MB","topConsumers":[{"type":"PrestoSparkRemoteSourceOperator","planNodeId":"238","reservations":["3.88MB","0B"],"total":"3.88MB"},{"type":"HashBuilderOperator","planNodeId":"4","reservations":["657.92kB","655.67kB","372.46kB","360.00kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]
2023-11-08T12:35:53.4174691Z 	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:60)
2023-11-08T12:35:53.4176015Z 	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:396)
2023-11-08T12:35:53.4177228Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.executeWithRetryStrategies(PrestoSparkQueryRunner.java:525)
2023-11-08T12:35:53.4178255Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:508)
2023-11-08T12:35:53.4179118Z 	at com.facebook.presto.tests.QueryAssertions.assertQueryFails(QueryAssertions.java:328)
2023-11-08T12:35:53.4179681Z 	... 17 more
2023-11-08T12:35:53.4179812Z 
2023-11-08T12:35:53.6275071Z [INFO] 
2023-11-08T12:35:53.6275559Z [INFO] Results:
2023-11-08T12:35:53.6275989Z [INFO] 
2023-11-08T12:35:53.6276358Z [ERROR] Failures: 
2023-11-08T12:35:53.6293453Z [ERROR]   TestPrestoSparkQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold:933->AbstractTestQueryFramework.assertQueryFails:282 Expected exception message 'Query exceeded per-node broadcast memory limit of 2MB [Allocated: 2.00MB, Delta: 7.51kB (HashBuilderOperator), Top Consumers: {PrestoSparkRemoteSourceOperator=3.88MB, HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"5.88MB","topConsumers":[{"type":"PrestoSparkRemoteSourceOperator","planNodeId":"238","reservations":["3.88MB","0B"],"total":"3.88MB"},{"type":"HashBuilderOperator","planNodeId":"4","reservations":["657.92kB","655.67kB","372.46kB","360.00kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]' to match 'Query exceeded per-node broadcast memory limit of 2MB \[Broadcast size: 2.*MB\]' for query: select * from lineitem l join orders o on l.orderkey = o.orderkey
2023-11-08T12:35:53.6305551Z [ERROR]   TestPrestoSparkAdaptiveQueryRunner>TestPrestoSparkQueryRunner.testStorageBasedBroadcastJoinDeserializedMaxThreshold:933->AbstractTestQueryFramework.assertQueryFails:282 Expected exception message 'Query exceeded per-node broadcast memory limit of 2MB [Allocated: 2.00MB, Delta: 9.97kB (HashBuilderOperator), Top Consumers: {HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"2.00MB","topConsumers":[{"type":"HashBuilderOperator","planNodeId":"4","reservations":["666.16kB","582.90kB","544.91kB","253.55kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]' to match 'Query exceeded per-node broadcast memory limit of 2MB \[Broadcast size: 2.*MB\]' for query: select * from lineitem l join orders o on l.orderkey = o.orderkey
```
## Your Environment
* Presto version used: latest master

## Expected Behavior
THe error message should match

## Current Behavior
expected error message with additional info "\[Broadcast size: 2.*MB\]" but actual was "[Allocated: 2.00MB, Delta: 9.97kB (HashBuilderOperator), Top Consumers: {HashBuilderOperator=2.00MB}, Details: [{"taskId":"0.0.0","reservation":"2.00MB","topConsumers":[{"type":"HashBuilderOperator","planNodeId":"4","reservations":["666.16kB","582.90kB","544.91kB","253.55kB"],"total":"2.00MB","info":"INNER;REPLICATED;"}]}]]"

## Possible Solution
Fix the test with the correct error message

**Comment by misterjpapa** [comment]
Test no longer fails due to error mismatch. Furthermore the message was changed a day later on 11/9/23 when this bug was opened. See https://github.com/prestodb/presto/commit/9a2e540a8bb90bd7a7a1c7ec8c71f1336bcf793b for more details. I just ran the tests twice on latest and everything passed.
<img width="1436" alt="Screenshot 2024-08-02 at 8 06 26 PM" src="https://github.com/user-attachments/assets/3f98967d-24d2-41d6-b9d1-7b05dfa77a3e"> - I think it's safe to close this issue.
