### ISSUE TITLE
Can't use a Noobaa Cache bucket without cache data to run TPC-DS benchmark

### ISSUE THREAD

**Issue by youhangwang** [prestodb/presto#21489]
Noobaa is used to create a cache bucket to cache TPC-DS sf100 benchmark data from a remote S3 bucket. and use presto to query the table in cache bucket.

```
CREATE SCHEMA "benchmarkcache"."sf1000cache" WITH (location = 's3a://benchmark-cache-6a8dc04a-6927-42e5-aad6-627b4b879faa/sf1000/')

CREATE TABLE "benchmarkcache"."sf1000cache".customer (
   "c_customer_sk" bigint,
   "c_customer_id" char(16),
   "c_current_cdemo_sk" bigint,
   "c_current_hdemo_sk" bigint,
   "c_current_addr_sk" bigint,
   "c_first_shipto_date_sk" bigint,
   "c_first_sales_date_sk" bigint,
   "c_salutation" char(10),
   "c_first_name" char(20),
   "c_last_name" char(30),
   "c_preferred_cust_flag" char(1),
   "c_birth_day" integer,
   "c_birth_month" integer,
   "c_birth_year" integer,
   "c_birth_country" varchar(20),
   "c_login" char(13),
   "c_email_address" char(50),
   "c_last_review_date_sk" bigint
)
WITH ( external_location = 's3a://benchmark-cache-6a8dc04a-6927-42e5-aad6-627b4b879faa/sf1000/customer/', format = 'PARQUET' )
```

presto ---(query data)---> cache bucket(craeted by noobaa) ----(cache data)-----> remote bucket(S3 in cloud)

However, query will be failed if there is no cache data in the cache:
```
SELECT
  *
FROM
  "benchmarkcache"."sf1000cache"."customer"

Error reading from s3a://benchmarkcache-6a8dc04a-6927-42e5-aad6-627b4b879faa/sf1000/customer/abc7a7ad-1d52-4d61-9b7b-b2ae6cfc18e7.parquet at position 205676755
```

After I manually download the object from cache bucket(warmup the cache). then the query will be successfull.

## Your Environment

* Presto version used: v0.282
* Storage (HDFS/S3/GCS..): S3
* Data source and connector used: .parquet in S3 bucket
* Deployment (Cloud or On-prem): On-prem
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Expected Behavior

Even there is no cache data in the cache, the query should be successful as noobaa will fill the data into the cache

## Current Behavior

query fail with error: 
```
Error reading from s3a://benchmark-cache-6a8dc04a-6927-42e5-aad6-627b4b879faa/sf1000/customer/abc7a7ad-1d52-4d61-9b7b-b2ae6cfc18e7.parquet at position 205676755
```

## Possible Solution

I doubt the noobaa cache bucket does not support the object get with range option and made some test, but it support to get object with range option.

Are there any other uncommon S3 operations used in presto query? Or any idea about how to fix this error?
```
Error reading from s3a://benchmark-cache-6a8dc04a-6927-42e5-aad6-627b4b879faa/sf1000/customer/abc7a7ad-1d52-4d61-9b7b-b2ae6cfc18e7.parquet at position 205676755
```

Thanks for your help!

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by yhwang** [comment]
@youhangwang can you fill us in with more information about the error you mentioned? like any stacktrace you can share with? and detailed steps to recreate your issue? Thanks.

**Comment by youhangwang** [comment]
Hi, here is the steps:
1. put the benchmark data into a remote s3 bucket
2. Create a cache bucket via noobaa which will cache the data from the remote s3 bucket. 
3. create hive catalog in presto based on this cache bucket
4. create schema with external location to the benchmark data in cache bucket
5. create table with external location to the benchmark data in the cache bucket
6. use presto query the data, then it fails with error: Error reading from `s3a://xxxxxx.parquet at position xxxx`
7. down the benchmark data from the cache bucket via aws s3 client which will warmup the cache bucket, then use presto query the data, it's successfully to run the query


Here is error log in coordinator:
```

2023-12-13T13:48:08.954Z	ERROR	remote-task-callback-6	com.facebook.presto.execution.StageExecutionStateMachine	Stage execution 20231213_134520_00000_xqu3u.1.0 failed
com.facebook.presto.spi.PrestoException: Error reading from s3a://benchmark-us-south-cache-6a8dc04a-6927-42e5-aad6-627b4b879faa/sf1000/customer/a747c6b6-00a9-4623-9197-25edbd940b77.parquet at position 220429496
	at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:73)
	at com.facebook.presto.parquet.AbstractParquetDataSource.readFully(AbstractParquetDataSource.java:60)
	at com.facebook.presto.parquet.AbstractParquetDataSource.readFully(AbstractParquetDataSource.java:51)
	at com.facebook.presto.parquet.cache.MetadataReader.readFooter(MetadataReader.java:112)
	at com.facebook.presto.parquet.cache.MetadataReader.getParquetMetadata(MetadataReader.java:489)
	at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.lambda$createParquetPageSource$0(ParquetPageSourceFactory.java:207)
	at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:81)
	at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createParquetPageSource(ParquetPageSourceFactory.java:207)
	at com.facebook.presto.hive.parquet.ParquetPageSourceFactory.createPageSource(ParquetPageSourceFactory.java:555)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:431)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:187)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:63)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:428)
	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:311)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:732)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:304)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:603)
	at com.facebook.presto.$gen.Presto_0_282____20231213_133801_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1219)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1165)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1524)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem$PrestoS3InputStream.lambda$read$0(PrestoS3FileSystem.java:991)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:139)
	at com.facebook.presto.hive.s3.PrestoS3FileSystem$PrestoS3InputStream.read(PrestoS3FileSystem.java:986)
	at org.apache.hadoop.fs.FSInputStream.readFully(FSInputStream.java:78)
	at org.apache.hadoop.fs.BufferedFSInputStream.readFully(BufferedFSInputStream.java:113)
	at org.apache.hadoop.fs.FSDataInputStream.readFully(FSDataInputStream.java:107)
	at com.facebook.presto.hive.parquet.HdfsParquetDataSource.readInternal(HdfsParquetDataSource.java:65)
	... 25 more
	Suppressed: com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
		... 44 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
		at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
		at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
		at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
		at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
		at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
		at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
		at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
		at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
		at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
		at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
		... 42 more
	Suppressed: com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
		... 44 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
		at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
		at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
		at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
		at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
		at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
		at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
		at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
		at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
		at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
		at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
		... 42 more
	Suppressed: com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
		... 44 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
		at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
		at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
		at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
		at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
		at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
		at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
		at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
		at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
		at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
		at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
		... 42 more
	Suppressed: com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
		... 44 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
		at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
		at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
		at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
		at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
		at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
		at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
		at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
		at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
		at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
		at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
		... 42 more
	Suppressed: com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
		... 44 more
	Caused by: java.net.SocketTimeoutException: Read timed out
		at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
		at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
		at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
		at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
		at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
		at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
		at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
		at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
		at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
		at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
		at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
		at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
		at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
		at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
		... 42 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1346)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	... 42 more



2023-12-13T13:48:09.449Z	INFO	dispatcher-query-5	com.facebook.presto.event.QueryMonitor	TIMELINE: Query 20231213_134520_00000_xqu3u :: Transaction:[cdd8bd37-9259-4533-9810-45a88467aa33] :: elapsed 167788ms :: planning 512ms :: scheduling 2880ms :: running 164412ms :: finishing 0ms :: begin 2023-12-13T13:45:21.184Z :: end 2023-12-13T13:48:08.972Z

2023-12-13T13:48:18.281Z	INFO	PolicyTimer	com.ibm.openlakehouse.prestodb.auth.base.utils.HttpClient	HttpClient url is https://lhconsole-api-svc.cpd-instance.svc.cluster.local:3333/lakehouse/api/v1/access/policy_versions
```

**Comment by guymguym** [comment]
Hi @youhangwang perhaps try increasing `hive.s3.socket-timeout`? (the default is 5 seconds and noobaa caching can delay the time to first byte on cache miss). See in https://prestodb.io/docs/current/connector/hive.html#tuning-properties.

**Comment by youhangwang** [comment]
@guymguym thanks for your help! yes, this issue was fixed after increase the timeout
