### ISSUE TITLE
TestJdbcResultSet::testObjectTypes test fails in test-other-modules job

### ISSUE THREAD

**Issue by karteekmurthys** [prestodb/presto#21533]
Module: presto-jdbc and test failure is:
```
Error:  com.facebook.presto.jdbc.TestJdbcResultSet.testObjectTypes  Time elapsed: 1.554 s  <<< FAILURE!
java.lang.AssertionError: expected [[1, 1001]] but found [{fst=1, snd=1001}]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:643)
	at com.facebook.presto.jdbc.TestJdbcResultSet.lambda$testObjectTypes$30(TestJdbcResultSet.java:232)
	at com.facebook.presto.jdbc.TestJdbcResultSet.checkRepresentation(TestJdbcResultSet.java:250)
	at com.facebook.presto.jdbc.TestJdbcResultSet.testObjectTypes(TestJdbcResultSet.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
```

Seems like this query is failing the check, the data structure returned by the query seems like a pair vs expected type an Array.
```
statement.execute("CREATE TYPE cat.sch.pair AS (fst integer, snd varchar)");
        checkRepresentation("CAST((1,'1001') AS cat.sch.pair)", Types.JAVA_OBJECT, (rs, column) -> {
            assertEquals(rs.getObject(1), Lists.newArrayList(1, "1001"));
        });
```

Job: https://github.com/prestodb/presto/actions/runs/7202098182/job/19620219039?pr=21487

**Comment by hantangwangd** [comment]
@karteekmurthys Thanks for the reporting. It's a small problem introduced by newly merged commit [Support udt when forcing values from Jackson to have expected type](https://github.com/prestodb/presto/commit/872eca121837e8bc28b232d668733b8a5975b404), and I will fixed Immediately.
