### ISSUE TITLE
zip file closed

### ISSUE THREAD

**Issue by wangyanxiya** [prestodb/presto#21678]
## Describe the problem you faced

1. I will submit the presto query task as a Flink task to Yarn for execution

2. Multiple query tasks are being executed simultaneously, connecting to the same database

3. In my own code, I take them in batches
4. 
* A clear and concise description of the problem.
* Was this working before or is this a first try?
* If this worked before, then what has changed that recently?  
* Provide table DDLs and `` EXPLAIN ANALYZE `` for your Presto queries.

## Environment Description

* Presto version used:.0.274
* Storage (HDFS/S3/GCS..):hdfs
* Data source and connectors or catalogs used:mysql
* Deployment (Cloud or On-prem):on-prem
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps To Reproduce

1.
2.
3.
5.

## Stacktrace

Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:686)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:315)
	at java.util.jar.JarFile.getEntry(JarFile.java:241)
	at sun.net.www.protocol.jar.URLJarFile.getEntry(URLJarFile.java:128)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:224)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1074)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:71)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1816)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1760)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.getTopMetaIterator(Iterators.java:1311)
	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1327)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:146)

**Comment by tdcmeehan** [comment]
Looks like there's some custom Flink code, that is not a stack trace that could originate purely from Presto, so I don't think we can help you with this.

It could be that a JAR you're trying to load is corrupted.
