### ISSUE TITLE
The official MySQL Driver cannot connect to MySQL databases of other versions

### ISSUE THREAD

**Issue by clown-k** [prestodb/presto#21701]
## Describe the problem you faced

The official MySQL driver version is 5.1.48, but the following error occurs when I connect to the MySQL database version 5.7.40:
I used the client to enter "show schemas from mysql;" and got an error "failed: Could not create connection to database server. Attempted reconnect 3 times. Giving up."

I'm sorry that my question is not well described, because this is the first question I submitted. Thank you very much for answering my question.

* A clear and concise description of the problem.
* Was this working before or is this a first try?
* If this worked before, then what has changed that recently?  
* Provide table DDLs and `` EXPLAIN ANALYZE `` for your Presto queries.

## Environment Description

* Presto version used: 0.283
* Storage (HDFS/S3/GCS..): MySQL
* Data source and connectors or catalogs used: MySQL Connector
* Deployment (Cloud or On-prem): K8S
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps To Reproduce

1.
2.
3.
4.

## Additional context

![Uploading image.png…]()

## Stacktrace

com.facebook.presto.spi.PrestoException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:157)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.listSchemaNames(JdbcMetadata.java:77)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.listSchemaNames(ClassLoaderSafeConnectorMetadata.java:212)
	at com.facebook.presto.metadata.MetadataManager.listSchemaNames(MetadataManager.java:298)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.calculatePrefixesWithSchemaName(InformationSchemaMetadata.java:277)
	at com.facebook.presto.connector.informationSchema.InformationSchemaMetadata.getTableLayouts(InformationSchemaMetadata.java:241)
	at com.facebook.presto.metadata.MetadataManager.getLayout(MetadataManager.java:360)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutWithoutPredicate.apply(PickTableLayout.java:211)
	at com.facebook.presto.sql.planner.iterative.rule.PickTableLayout$PickTableLayoutWithoutPredicate.apply(PickTableLayout.java:178)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:221)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:182)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:144)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:255)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreChildren(IterativeOptimizer.java:255)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreGroup(IterativeOptimizer.java:146)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.optimize(IterativeOptimizer.java:131)
	at com.facebook.presto.sql.Optimizer.validateAndOptimizePlan(Optimizer.java:114)
	at com.facebook.presto.execution.SqlQueryExecution.lambda$createLogicalPlanAndOptimize$3(SqlQueryExecution.java:542)
	at com.facebook.presto.common.RuntimeStats.profileNanos(RuntimeStats.java:136)
	at com.facebook.presto.execution.SqlQueryExecution.createLogicalPlanAndOptimize(SqlQueryExecution.java:540)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:449)
	at com.facebook.presto.$gen.Presto_0_283_1fa586a____20240115_112123_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:306)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2095)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2020)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at com.facebook.presto.plugin.jdbc.DriverConnectionFactory.openConnection(DriverConnectionFactory.java:82)
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getSchemaNames(BaseJdbcClient.java:151)
	... 27 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 2 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:201)
	at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4869)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1656)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2036)
	... 39 more
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:222)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
	at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:186)
	... 44 more

**Comment by clown-k** [comment]
Is there any way to fix this if I want to use MYSQL database version 5.7?

**Comment by clown-k** [comment]
If I want to use MYSQL database version 5.7 is there any way to solve this problem?

**Comment by kiersten-stokes** [comment]
Hi @clown-k - I have a few follow-up questions for you! Are you submitting your query using the presto CLI? Also, just to clarify, you mention a MySQL version of 5.7 - is that the version of your actual MySQL database? If the answer to both of these is yes, we should probably take a look at your `mysql.properties` file to see what the error might be

**Comment by clown-k** [comment]
Hi @kiersten-stokes - I created `mysql.properties` using `values.yaml` of the official Chart.
```java
#Catalogs
catalog: 
  mysql: |-
    connector.name=mysql
    connection-url=jdbc:mysql://X.X.X.X:3306?serverTimezone=UTC
    connection-user=X
    connection-password=X
```
The configuration file actually generated in Pod:
```java
$ cat /opt/presto-server/etc/catalog/mysql.properties
    connector.name=mysql
    connection-url=jdbc:mysql://X.X.X.X:3306?serverTimezone=UTC
    connection-user=X
    connection-password=X
```

**Comment by clown-k** [comment]
I don't think `mysql.properties`is erroneous. Because `mysql-connector-java-5.1.48.jar` is used in `/opt/presto-server/plugin/mysql/`, and when I use version 5.1.48 of MYSQL database(not on the k8s), it works.

**Comment by kiersten-stokes** [comment]
Ah I see! I didn't catch that you were using the helm chart earlier. The mysql properties definitely look sound. I tried it out with the latest version of MySQL and didn't run into this issue, but can reproduce using version 5.7.40, like you said! Based on my research, I think the driver v5.1.48 and MySQL v5.7.40 disagree on security protocols. For compatibility reasons the driver doesn't enable TLSv1.2 and higher by default. A workaround here would be to add the below option to your mysql connection string in the properties:

```
connection-url=jdbc:mysql://X.X.X.X:3306?enabledTLSProtocols=TLSv1.2&serverTimezone=UTC
```

Hopefully that does the trick!

**Comment by kiersten-stokes** [comment]
@clown-k glad to hear it!
