### ISSUE TITLE
Flaky Test Suite: singlestore tests / singlestore-dockerized-tests

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#21860]
https://github.com/prestodb/presto/actions/runs/7781843914/job/21217067310?pr=21855

```
Error:  Tests run: 546, Failures: 1, Errors: 0, Skipped: 511, Time elapsed: 145.727 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.plugin.singlestore.TestSingleStoreDistributedQueries.init  Time elapsed: 9.514 s  <<< FAILURE!
java.sql.SQLException: (conn=58) Not enough disk space to create or attach database tpch on leaf 127.0.0.1:3307.  Estimate Available 11818 MB, Estimate Needed 13763 MB.
	at com.singlestore.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:216)
	at com.singlestore.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:250)
	at com.singlestore.jdbc.message.ClientMessage.readPacket(ClientMessage.java:85)
	at com.singlestore.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:711)
	at com.singlestore.jdbc.client.impl.StandardClient.readResults(StandardClient.java:659)
	at com.singlestore.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:582)
	at com.singlestore.jdbc.client.impl.StandardClient.execute(StandardClient.java:556)
	at com.singlestore.jdbc.Statement.executeInternal(Statement.java:900)
	at com.singlestore.jdbc.Statement.execute(Statement.java:1024)
	at com.singlestore.jdbc.Statement.execute(Statement.java:431)
	at com.facebook.presto.plugin.singlestore.SingleStoreQueryRunner.createSchema(SingleStoreQueryRunner.java:85)
	at com.facebook.presto.plugin.singlestore.SingleStoreQueryRunner.createSingleStoreQueryRunner(SingleStoreQueryRunner.java:65)
	at com.facebook.presto.plugin.singlestore.TestSingleStoreDistributedQueries.createQueryRunner(TestSingleStoreDistributedQueries.java:47)
	at com.facebook.presto.tests.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:178)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestSingleStoreDistributedQueries>AbstractTestQueryFramework.init:83->createQueryRunner:47 » SQL (conn=58) Not enough disk space to create or attach database tpch on leaf 127.0.0.1:3307.  Estimate Available 11818 MB, Estimate Needed 13763 MB.
[INFO] 
Error:  Tests run: 546, Failures: 1, Errors: 0, Skipped: 511
```

## Possible Solution

We can plan to allocate more space for this test suite

**Comment by ajaygeorge** [comment]
This is becoming more common now.
Some recent failures.
https://github.com/prestodb/presto/actions/runs/7787344087/job/21234285356
https://github.com/prestodb/presto/actions/runs/7822428211/job/21341455930
Is some one working on increasing disk space or fixing this test?

**Comment by tdcmeehan** [comment]
CC: @oyeliseiev-ua can you please take a look at this?
