### ISSUE TITLE
TestQuickStatsProvider.testConcurrentFetchForSamePartition is flaky

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22088]
2024-03-05T15:57:21.7850395Z [INFO] 
2024-03-05T15:57:21.7851314Z [ERROR] Failures: 
2024-03-05T15:57:21.7853112Z [ERROR] com.facebook.presto.hive.statistics.TestQuickStatsProvider.testConcurrentFetchForSamePartition
2024-03-05T15:57:21.7854795Z [ERROR]   Run 1: TestQuickStatsProvider.testConcurrentFetchForSamePartition:268 
2024-03-05T15:57:21.7863826Z quickStatsBuilder.buildQuickStats(
2024-03-05T15:57:21.7864566Z     <any>,
2024-03-05T15:57:21.7864971Z     <any>,
2024-03-05T15:57:21.7865333Z     <any>,
2024-03-05T15:57:21.7865680Z     <any>,
2024-03-05T15:57:21.7866041Z     "partition1",
2024-03-05T15:57:21.7866444Z     <any>
2024-03-05T15:57:21.7866774Z );
2024-03-05T15:57:21.7867110Z Wanted 1 time:
2024-03-05T15:57:21.7868845Z -> at com.facebook.presto.hive.statistics.TestQuickStatsProvider.testConcurrentFetchForSamePartition(TestQuickStatsProvider.java:268)
2024-03-05T15:57:21.7870428Z But was 2 times:
2024-03-05T15:57:21.7871621Z -> at com.facebook.presto.hive.statistics.QuickStatsProvider.buildQuickStats(QuickStatsProvider.java:345)
2024-03-05T15:57:21.7873549Z -> at com.facebook.presto.hive.statistics.QuickStatsProvider.buildQuickStats(QuickStatsProvider.java:345)
2024-03-05T15:57:21.7874533Z 
2024-03-05T15:57:21.7874543Z 
2024-03-05T15:57:21.7874710Z [INFO]   Run 2: PASS
2024-03-05T15:57:21.7875104Z [INFO]   Run 3: PASS
2024-03-05T15:57:21.7875472Z [INFO]

**Comment by ClarenceThreepwood** [comment]
Another occurrence
https://github.com/prestodb/presto/actions/runs/8162422313/job/22313380024?pr=22013

**Comment by elharo** [comment]
I think this is likely fixed by #22098 but I can reopen if it reappears
