### ISSUE TITLE
Partial aggregation pushdown fails for aggregations on partition keys

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#22099]
A query with an aggregation on a partition key that for a regular column would be supported by partial aggregation pushdown will fail. We try to pushdown the aggregation and fail at runtime with an ArrayIndexOutOfBounds exception while creating AggregatedOrcPageSource 
We saw this in production, and I reproduced with the following test in TestHiveIntegrationSmokeTest
```
 @Test
    public void testPartialAggregatePushdownOrcWithPartitionKey()
{
    @Language("SQL") String createTable = "" +
            "CREATE TABLE test_orc_table (" +
            " _boolean BOOLEAN" +
            ", _tinyint TINYINT" +
            ", _smallint SMALLINT" +
            ", _integer INTEGER" +
            ", _bigint BIGINT" +
            ", _real REAL" +
            ", _double DOUBLE" +
            ", _shortdecimal DECIMAL(8,3)" +
            ", _longdecimal DECIMAL(25,2)" +
            ", _string VARCHAR" +
            ", _varchar VARCHAR(10)" +
            ", _singlechar CHAR" +
            ", _char CHAR(10)" +
            ", _varbinary VARBINARY" +
            ", _date DATE" +
            ", _timestamp TIMESTAMP" +
            ",_ds VARCHAR" +
            ")" +
            "WITH (format = 'orc', partitioned_by = ARRAY['_ds'])";

    Session session = Session.builder(getSession())
            .setCatalogSessionProperty(catalog, "partial_aggregation_pushdown_enabled", "true")
            .setCatalogSessionProperty(catalog, "partial_aggregation_pushdown_for_variable_length_datatypes_enabled", "true")
            .build();
    try {
        assertUpdate(session, createTable);

        TableMetadata tableMetadata = getTableMetadata(catalog, TPCH_SCHEMA, "test_orc_table");
        assertEquals(tableMetadata.getMetadata().getProperties().get(STORAGE_FORMAT_PROPERTY), HiveStorageFormat.ORC);

        assertUpdate(session, "INSERT INTO test_orc_table VALUES (" +
                "true" +
                ", cast(1 as tinyint)" +
                ", cast(2 as smallint)" +
                ", 3" +
                ", 4" +
                ", 1.2" +
                ", 2.3" +
                ", 4.5" +
                ", 55555555555555.32" +
                ", 'abc'" +
                ", 'def'" +
                ", 'g'" +
                ", 'hij'" +
                ", cast('klm' as varbinary)" +
                ", cast('2020-05-01' as date)" +
                ", cast('2020-06-04 16:55:40.777' as timestamp)" +
                ", '2024-03-06'" +
                ")", 1);

        assertUpdate(session, "INSERT INTO test_orc_table VALUES (" +
                "false" +
                ", cast(10 as tinyint)" +
                ", cast(20 as smallint)" +
                ", 30" +
                ", 40" +
                ", 10.25" +
                ", 25.334" +
                ", 465.523" +
                ", 88888888555555.91" +
                ", 'foo'" +
                ", 'bar'" +
                ", 'b'" +
                ", 'baz'" +
                ", cast('qux' as varbinary)" +
                ", cast('2020-06-02' as date)" +
                ", cast('2020-05-01 18:34:23.88' as timestamp)" +
                ", '2024-03-05'" +
                ")", 1);
        assertQuery(session, "SELECT min(_ds) FROM test_orc_table", "SELECT '2024-03-05'" );

    }
    finally {
        assertUpdate(session, "DROP TABLE test_orc_table");
    }
    assertFalse(getQueryRunner().tableExists(session, "test_orc_table"));
}
```

Stack Trace:
```
2024-03-06T10:07:14.060-0600	ERROR	SplitRunner-15-324	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20240306_160713_00013_9pcj3.1.0.0.0-0 {path=file:/var/folders/nd/7f5mz1hs6qqbl3y0kh9pnn3c0000gn/T/PrestoTest1910939588174119347/hive_data/tpch/test_orc_table/_ds=2024-03-06/20240306_160709_00011_9pcj3_044b89bb-faa3-4884-96be-9721653a7d15, start=0, length=1362, fileSize=1362, fileModifiedTime=1709741231000, hosts=[], database=tpch, table=test_orc_table, nodeSelectionStrategy=NO_PREFERENCE, partitionName=_ds=2024-03-06, s3SelectPushdownEnabled=false, cacheQuotaRequirement=CacheQuotaRequirement{cacheQuotaScope=GLOBAL, quota=Optional.empty}} (start = 3.47261709428083E8, wall = 103 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.ArrayIndexOutOfBoundsException: -12
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.writeMinMax(AggregatedOrcPageSource.java:134)
	at com.facebook.presto.hive.orc.AggregatedOrcPageSource.getNextPage(AggregatedOrcPageSource.java:119)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:266)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:436)
	at com.facebook.presto.operator.Driver.lambda$processFor$10(Driver.java:319)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:740)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:312)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
	at com.facebook.presto.$gen.Presto_null__testversion____20240306_160626_4.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rschlussel** [comment]
@ClarenceThreepwood @ajaygeorge

**Comment by ClarenceThreepwood** [comment]
@rschlussel - are you working on this? Should I pick it up?

**Comment by rschlussel** [comment]
I'm not working on it. Would be great if you're able to pick it up!
