### ISSUE TITLE
Cannot select color type

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#2210]
```
presto:tiny> select rgb(0, 0, 0);
2015-01-09T10:24:34.279-0800    DEBUG   main    com.facebook.presto.cli.StatusPrinter   error printing status
java.lang.RuntimeException: Error fetching next at http://localhost:8080/v1/statement/20150109_182434_00005_t36py/1 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={Vary=[Accept-Encoding, User-Agent], Content-Length=[879], Date=[Fri, 09 Jan 2015 18:24:34 GMT], X-Content-Type-Options=[nosniff], Content-Type=[application/json]}, hasValue=false, value=null}
    at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:258) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.client.StatementClient.advance(StatementClient.java:230) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:94) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:109) [presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.Query.renderOutput(Query.java:94) [presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.Console.process(Console.java:237) [presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.Console.runConsole(Console.java:179) [presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.Console.run(Console.java:109) [presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.cli.Presto.main(Presto.java:31) [presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.client.QueryResults from JSON response:
{"id":"20150109_182434_00005_t36py","infoUri":"http://localhost:8080/v1/query/20150109_182434_00005_t36py","partialCancelUri":"http://127.0.0.1:8080/v1/stage/20150109_182434_00005_t36py.0","nextUri":"http://localhost:8080/v1/statement/20150109_182434_00005_t36py/2","columns":[{"name":"_col0","type":"color","typeSignature":{"rawType":"color","typeArguments":[],"literalArguments":[]}}],"data":[["#000000"]],"stats":{"state":"RUNNING","scheduled":false,"nodes":1,"totalSplits":0,"queuedSplits":0,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"rootStage":{"stageId":"0","state":"SCHEDULED","done":false,"nodes":1,"totalSplits":0,"queuedSplits":0,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[]}}}

    at io.airlift.http.client.FullJsonResponseHandler$JsonResponse.<init>(FullJsonResponseHandler.java:119) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at io.airlift.http.client.FullJsonResponseHandler.handle(FullJsonResponseHandler.java:66) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at io.airlift.http.client.FullJsonResponseHandler.handle(FullJsonResponseHandler.java:35) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:233) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.client.StatementClient.advance(StatementClient.java:217) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    ... 7 common frames omitted
Caused by: java.lang.IllegalArgumentException: Invalid [simple type, class com.facebook.presto.client.QueryResults] json bytes
    at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:174) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at io.airlift.http.client.FullJsonResponseHandler$JsonResponse.<init>(FullJsonResponseHandler.java:116) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    ... 11 common frames omitted
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Instantiation of [simple type, class com.facebook.presto.client.QueryResults] value failed: Unrecognized character: #
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:405) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:234) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:167) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:398) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2262) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:171) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    ... 12 common frames omitted
Caused by: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: #
    at com.google.common.io.BaseEncoding$Alphabet.decode(BaseEncoding.java:503) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.google.common.io.BaseEncoding$StandardBaseEncoding$2.read(BaseEncoding.java:675) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:245) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:226) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.client.QueryResults.fixValue(QueryResults.java:256) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.client.QueryResults.fixData(QueryResults.java:184) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.facebook.presto.client.QueryResults.<init>(QueryResults.java:79) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_25]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_25]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_25]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_25]
    at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:230) ~[presto-cli-0.90-SNAPSHOT-executable.jar:0.90-SNAPSHOT]
    ... 20 common frames omitted
Query is gone (server restarted?)
```

**Comment by electrum** [comment]
The problem is the CLI assumes that any unknown types are encoded as binary (base64 in JSON) but `ColorType.getObjectValue()` returns a string like `#000000`.

**Comment by cberner** [comment]
I ran into this problem with the ML types too, and with those we can't special case them in the CLI. I think we need to add some kind of type descriptor so that types can specify how their "object value" is encoded. Then clients will know how to interpret the data. This would also simplify the CLI code, and allow us to remove that hard coded switch statement for decoding types.
