### ISSUE TITLE
TestHiveHistoryBasedStatsTracking. testHistoryBasedStatsCalculatorMultipleStrategies is flaky

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22118]
a failure I haven't seen before:

```
2024-03-07T08:57:29.0189796Z [ERROR] Tests run: 2940, Failures: 1, Errors: 0, Skipped: 90, Time elapsed: 2,527.734 s <<< FAILURE! - in TestSuite
2024-03-07T08:57:29.0192150Z [ERROR] com.facebook.presto.hive.TestHiveHistoryBasedStatsTracking.testHistoryBasedStatsCalculatorMultipleStrategies  Time elapsed: 0.445 s  <<< FAILURE!
2024-03-07T08:57:29.0193873Z java.lang.AssertionError: 
2024-03-07T08:57:29.0194419Z Plan does not match, expected [
2024-03-07T08:57:29.0196907Z 
2024-03-07T08:57:29.0200533Z - anyTree
2024-03-07T08:57:29.0201027Z     - node(ProjectNode)
2024-03-07T08:57:29.0201519Z         expectedOutputRowCount(48.0)
2024-03-07T08:57:29.0201940Z         - node
2024-03-07T08:57:29.0202089Z 
2024-03-07T08:57:29.0202176Z ] but found [
2024-03-07T08:57:29.0202318Z 
2024-03-07T08:57:29.0203551Z - Output[PlanNodeId 6][orderkey, orderpriority, comment, custkey, ds, ts, _col6] => [orderkey:bigint, orderpriority:varchar(15), comment:varchar(79), custkey:bigint, ds:varchar(10), ts:varchar(5), expr_5:integer]
2024-03-07T08:57:29.0204577Z         _col6 := expr_5 (1:11)
2024-03-07T08:57:29.0205576Z     - RemoteStreamingExchange[PlanNodeId 238][GATHER] => [orderkey:bigint, orderpriority:varchar(15), comment:varchar(79), custkey:bigint, ds:varchar(10), ts:varchar(5), expr_5:integer]
2024-03-07T08:57:29.0213487Z         - ScanProject[PlanNodeId 0,162][table = TableHandle {connectorId='hive', connectorHandle='HiveTableHandle{schemaName=tpch, tableName=test_orders, analyzePartitionValues=Optional.empty}', layout='Optional[tpch.test_orders{domains={orderpriority=[ [["1-URGENT"]] ]}}]'}, projectLocality = LOCAL] => [orderkey:bigint, orderpriority:varchar(15), comment:varchar(79), custkey:bigint, ds:varchar(10), ts:varchar(5), expr_5:integer]
2024-03-07T08:57:29.0216830Z                 orderpriority := VARCHAR'1-URGENT'
2024-03-07T08:57:29.0217532Z                 ds := VARCHAR'2020-09-02'
2024-03-07T08:57:29.0218139Z                 expr_5 := INTEGER'2'
2024-03-07T08:57:29.0219018Z                 LAYOUT: tpch.test_orders{domains={orderpriority=[ [["1-URGENT"]] ]}}
2024-03-07T08:57:29.0219901Z                 orderkey := orderkey:bigint:0:REGULAR (1:18)
2024-03-07T08:57:29.0223339Z                 custkey := custkey:bigint:3:REGULAR (1:18)
2024-03-07T08:57:29.0225518Z                 ts := ts:varchar(5):-14:PARTITION_KEY (1:18)
2024-03-07T08:57:29.0226188Z                     :: [["00:02"]]
2024-03-07T08:57:29.0226968Z                 comment := comment:varchar(79):2:REGULAR (1:18)
2024-03-07T08:57:29.0229211Z                 orderpriority:varchar(15):1:REGULAR
2024-03-07T08:57:29.0230111Z                     :: [["1-URGENT"]]
2024-03-07T08:57:29.0230783Z                 ds:varchar(10):-13:PARTITION_KEY
2024-03-07T08:57:29.0232572Z                     :: [["2020-09-02"]]
2024-03-07T08:57:29.0232951Z 
2024-03-07T08:57:29.0233085Z ]
2024-03-07T08:57:29.0233909Z 	at com.facebook.presto.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:56)
2024-03-07T08:57:29.0236076Z 	at com.facebook.presto.sql.planner.assertions.PlanAssert.assertPlan(PlanAssert.java:40)
2024-03-07T08:57:29.0237764Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.lambda$assertPlan$7(AbstractTestQueryFramework.java:456)
2024-03-07T08:57:29.0239529Z 	at com.facebook.presto.transaction.TransactionBuilder.execute(TransactionBuilder.java:151)
2024-03-07T08:57:29.0240470Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertPlan(AbstractTestQueryFramework.java:454)
2024-03-07T08:57:29.0243420Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertPlan(AbstractTestQueryFramework.java:446)
2024-03-07T08:57:29.0245877Z 	at com.facebook.presto.hive.TestHiveHistoryBasedStatsTracking.testHistoryBasedStatsCalculatorMultipleStrategies(TestHiveHistoryBasedStatsTracking.java:118)
2024-03-07T08:57:29.0247835Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-07T08:57:29.0248966Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-03-07T08:57:29.0250312Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-07T08:57:29.0251421Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-03-07T08:57:29.0252674Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-03-07T08:57:29.0254135Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-03-07T08:57:29.0255426Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-03-07T08:57:29.0256748Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-03-07T08:57:29.0258129Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-03-07T08:57:29.0259534Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-03-07T08:57:29.0260988Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-03-07T08:57:29.0261944Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-03-07T08:57:29.0262698Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-03-07T08:57:29.0265738Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-03-07T08:57:29.0266716Z 	at java.lang.Thread.run(Thread.java:750)
```

**Comment by elharo** [comment]
This might be a case that can be fixed by @Test(singleThreaded = true) which we need here anyway.

**Comment by rschlussel** [comment]
I suspect this is the same issue as https://github.com/prestodb/presto/issues/22204.  My guess right now about what's going on is that sometimes we get empty stats for some operator (not sure why), and we end up logging that that operator produced zero output.
