### ISSUE TITLE
TestPrestoNativeGeneralQueriesJSON is flaky

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22139]
[ERROR] Tests run: 56, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 446.418 s <<< FAILURE! - in com.facebook.presto.nativeworker.TestPrestoNativeGeneralQueriesJSON
[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeGeneralQueriesJSON.testBucket  Time elapsed: 302.013 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT "$bucket", * from customer_bucketed
	at org.testng.Assert.fail(Assert.java:98)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:154)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:149)
	at com.facebook.presto.nativeworker.AbstractTestNativeGeneralQueries.testBucket(AbstractTestNativeGeneralQueries.java:978)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://127.0.0.1:1237/v1/task/20240308_210433_00077_tasbp.0.0.0.0/results/0/0 - 604 failures, failure duration 300.18s, total failed request time 301.86s)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:733)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:701)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:175)
	... 19 more
Caused by: com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://127.0.0.1:1237/v1/task/20240308_210433_00077_tasbp.0.0.0.0/results/0/0 - 604 failures, failure duration 300.18s, total failed request time 301.86s)
	at com.facebook.presto.operator.PageBufferClient$1.onFailure(PageBufferClient.java:371)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	... 3 more
Caused by: java.io.UncheckedIOException: Server refused connection: http://127.0.0.1:1237/v1/task/20240308_210433_00077_tasbp.0.0.0.0/results/0/0
	at com.facebook.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:18)
	at com.facebook.presto.operator.HttpRpcShuffleClient$PageResponseHandler.handleException(HttpRpcShuffleClient.java:132)
	at com.facebook.presto.operator.HttpRpcShuffleClient$PageResponseHandler.handleException(HttpRpcShuffleClient.java:126)
	at com.facebook.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:122)
	at com.facebook.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:766)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:452)
	at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:234)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.failed(AbstractConnectionPool.java:140)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:614)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:183)
	at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:778)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:228)
	at org.eclipse.jetty.io.ManagedSelector.access$1400(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:489)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:352)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:206)
	... 11 more

[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeGeneralQueriesJSON.testBinaryFunctions  Time elapsed: 302.013 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT spooky_hash_v2_32(cast(comment as varbinary)) FROM orders
	at org.testng.Assert.fail(Assert.java:98)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:154)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:149)
	at com.facebook.presto.nativeworker.AbstractTestNativeGeneralQueries.testBinaryFunctions(AbstractTestNativeGeneralQueries.java:872)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://127.0.0.1:1237/v1/task/20240308_210434_00079_tasbp.0.0.0.0/results/0/0 - 604 failures, failure duration 300.18s, total failed request time 301.21s)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:733)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:701)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:175)
	... 19 more
Caused by: com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://127.0.0.1:1237/v1/task/20240308_210434_00079_tasbp.0.0.0.0/results/0/0 - 604 failures, failure duration 300.18s, total failed request time 301.21s)
	at com.facebook.presto.operator.PageBufferClient$1.onFailure(PageBufferClient.java:371)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1052)
	... 3 more
Caused by: java.io.UncheckedIOException: Server refused connection: http://127.0.0.1:1237/v1/task/20240308_210434_00079_tasbp.0.0.0.0/results/0/0
	at com.facebook.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:18)
	at com.facebook.presto.operator.HttpRpcShuffleClient$PageResponseHandler.handleException(HttpRpcShuffleClient.java:132)
	at com.facebook.presto.operator.HttpRpcShuffleClient$PageResponseHandler.handleException(HttpRpcShuffleClient.java:126)
	at com.facebook.airlift.http.client.jetty.JettyResponseFuture.failed(JettyResponseFuture.java:122)
	at com.facebook.airlift.http.client.jetty.BufferingResponseListener.onComplete(BufferingResponseListener.java:85)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:196)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:188)
	at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:269)
	at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:240)
	at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
	at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:766)
	at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:452)
	at org.eclipse.jetty.client.HttpDestination.failed(HttpDestination.java:234)
	at org.eclipse.jetty.client.AbstractConnectionPool$1.failed(AbstractConnectionPool.java:140)
	at org.eclipse.jetty.util.Promise$Wrapper.failed(Promise.java:136)
	at org.eclipse.jetty.client.HttpClient$1$1.failed(HttpClient.java:614)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport.connectFailed(AbstractConnectorHttpClientTransport.java:138)
	at org.eclipse.jetty.client.AbstractConnectorHttpClientTransport$ClientSelectorManager.connectionFailed(AbstractConnectorHttpClientTransport.java:183)
	at org.eclipse.jetty.io.ManagedSelector$Connect.failed(ManagedSelector.java:778)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:228)
	at org.eclipse.jetty.io.ManagedSelector.access$1400(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.processSelected(ManagedSelector.java:489)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:352)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produceTask(EatWhatYouKill.java:357)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:181)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.eclipse.jetty.io.SelectorManager.doFinishConnect(SelectorManager.java:355)
	at org.eclipse.jetty.io.ManagedSelector.processConnect(ManagedSelector.java:206)
	... 11 more

**Comment by czentgr** [comment]
This means the CPP worker seemingly crashed. The coordinator log doesn't help in this case.
I'm taking a loo and see if I can repro.

**Comment by czentgr** [comment]
After 1594 iterations of running `TestPrestoNativeGeneralQueriesJSON.testBucket` no failure on Linux was observed.
So not able to repro this one. Switching to running `AbstractTestNativeGeneralQueries.testBinaryFunctions`.

**Comment by elharo** [comment]
Where are you rerunning? We might have tests that flake on the CI not not on our local dev machines.

**Comment by czentgr** [comment]
I'm running on a local Linux machine. Yes, the hope is to repro the issue locally. Not sure we get enough info from the CI pipeline. In this case the workers stopped working but we don't know why. It is not a result mismatch or something that could be looked at.
It is possible there is some race condition that is morel likely to trigger on the CI pipeline because of the cpu/memory used.

Do you have ideas on attempting to repro this?

**Comment by czentgr** [comment]
When this occurs next time we need to look into the uploaded worker artifacts and take it from there. Perhaps copy some of the logs from there into the issue so we don't lose the information. I will try to keep an eye out.
