### ISSUE TITLE
TestPrestoNativeGeneralQueriesJSON.testPrestoBenchTables is flaky

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#22133]
[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeGeneralQueriesJSON.testPrestoBenchTables  Time elapsed: 189.199 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT custkey from prestobench_customer
        at org.testng.Assert.fail(Assert.java:98)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
        at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:154)
        at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:149)
        at com.facebook.presto.nativeworker.AbstractTestNativeGeneralQueries.testPrestoBenchTables(AbstractTestNativeGeneralQueries.java:1159)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException:  Failed to fetch data from 127.0.0.1:1234 /v1/task/20240308_194841_00307_w3qef.1.0.3.0/results/0/0 - Exhausted after 25 retries, duration 185488ms: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
        at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
        at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:733)
        at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:701)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:175)
        ... 19 more
Caused by: VeloxRuntimeError:  Failed to fetch data from 127.0.0.1:1234 /v1/task/20240308_194841_00307_w3qef.1.0.3.0/results/0/0 - Exhausted after 25 retries, duration 185488ms: AsyncSocketException: connect failed, type = Socket not open, errno = 111 (Connection refused)
        at Unknown.# 0  _ZN8facebook5velox7process10StackTraceC1Ei(Unknown Source)
        at Unknown.# 1  _ZN8facebook5velox14VeloxException5State4makeIZNS1_C4EPKcmS5_St17basic_string_viewIcSt11char_traitsIcEES9_S9_S9_bNS1_4TypeES9_EUlRT_E_EESt10shared_ptrIKS2_ESA_SB_(Unknown Source)
        at Unknown.# 2  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_(Unknown Source)
        at Unknown.# 3  _ZN8facebook5velox17VeloxRuntimeErrorC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bS7_(Unknown Source)
        at Unknown.# 4  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_(Unknown Source)
        at Unknown.# 5  _ZN8facebook5velox4exec13ExchangeQueue13dequeueLockedEjPbPN5folly10SemiFutureINS4_4UnitEEE(Unknown Source)
        at Unknown.# 6  _ZN8facebook5velox4exec14ExchangeClient4nextEjPbPN5folly10SemiFutureINS4_4UnitEEE(Unknown Source)
        at Unknown.# 7  _ZN8facebook5velox4exec8Exchange9isBlockedEPN5folly10SemiFutureINS3_4UnitEEE(Unknown Source)
        at Unknown.# 8  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE(Unknown Source)
        at Unknown.# 9  _ZN8facebook5velox4exec6Driver3runESt10shared_ptrIS2_E(Unknown Source)
        at Unknown.# 10 _ZZN8facebook5velox4exec6Driver7enqueueESt10shared_ptrIS2_EENKUlvE_clEv(Unknown Source)
        at Unknown.# 11 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZN8facebook5velox4exec6Driver7enqueueESt10shared_ptrIS9_EEUlvE_EEvRNS1_4DataE(Unknown Source)
        at Unknown.# 12 _ZN5folly18ThreadPoolExecutor7runTaskERKSt10shared_ptrINS0_6ThreadEEONS0_4TaskE(Unknown Source)
        at Unknown.# 13 _ZN5folly21CPUThreadPoolExecutor9threadRunESt10shared_ptrINS_18ThreadPoolExecutor6ThreadEE(Unknown Source)
        at Unknown.# 14 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallISt5_BindIFMNS_18ThreadPoolExecutorEFvSt10shared_ptrINS7_6ThreadEEEPS7_SA_EEEEvRNS1_4DataE(Unknown Source)
        at Unknown.# 15 _ZN5folly6detail8function14FunctionTraitsIFvvEEclEv(Unknown Source)
        at Unknown.# 16 _ZZN5folly18NamedThreadFactory9newThreadEONS_8FunctionIFvvEEEENUlvE_clEv(Unknown Source)
        at Unknown.# 17 _ZSt13__invoke_implIvZN5folly18NamedThreadFactory9newThreadEONS0_8FunctionIFvvEEEEUlvE_JEET_St14__invoke_otherOT0_DpOT1_(Unknown Source)
        at Unknown.# 18 _ZSt8__invokeIZN5folly18NamedThreadFactory9newThreadEONS0_8FunctionIFvvEEEEUlvE_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS8_DpOS9_(Unknown Source)
        at Unknown.# 19 _ZNSt6thread8_InvokerISt5tupleIJZN5folly18NamedThreadFactory9newThreadEONS2_8FunctionIFvvEEEEUlvE_EEE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE(Unknown Source)
        at Unknown.# 20 _ZNSt6thread8_InvokerISt5tupleIJZN5folly18NamedThreadFactory9newThreadEONS2_8FunctionIFvvEEEEUlvE_EEEclEv(Unknown Source)
        at Unknown.# 21 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5folly18NamedThreadFactory9newThreadEONS3_8FunctionIFvvEEEEUlvE_EEEEE6_M_runEv(Unknown Source)
        at Unknown.# 22 0x00000000000c2b23(Unknown Source)
        at Unknown.# 23 start_thread(Unknown Source)
        at Unknown.# 24 clone(Unknown Source)

**Comment by rschlussel** [comment]
there was already an issue for this https://github.com/prestodb/presto/issues/21821
