### ISSUE TITLE
[NATIVE] Test AbstractTestNativeWindowQueries.testOverlappingPartitionAndSortingKeys is flaky

### ISSUE THREAD

**Issue by swapsmagic** [prestodb/presto#22141]
https://app.circleci.com/pipelines/github/prestodb/presto/13282/workflows/1f8858c6-0d99-467e-9811-5619fffbb542/jobs/51633

[ERROR] Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 111.407 s <<< FAILURE! - in com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries
[ERROR] com.facebook.presto.nativeworker.TestPrestoNativeWindowQueries.testOverlappingPartitionAndSortingKeys  Time elapsed: 1.247 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: WITH t AS (SELECT linenumber, row_number() over (partition by linenumber order by linenumber) as rn FROM lineitem) SELECT * FROM t WHERE rn = 1
        at org.testng.Assert.fail(Assert.java:98)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
        at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:154)

Seeing multiple failures of the tests.

**Comment by elharo** [comment]
Hasn't reoccurred since the changes I made two weeks ago so I'll tentatively close this one. We can reopen if it reoccurs.
