### ISSUE TITLE
TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22165]
Possibly flaky. Seen on https://github.com/prestodb/presto/actions/runs/8248026106/job/22557471680?pr=22163

com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd  Time elapsed: 0.004 s  <<< FAILURE!
2024-03-12T11:52:47.9286505Z java.lang.AssertionError: Test: Inconsistent results with large group id, Expected: 47.52453364071998, actual: 42.442403576947314
2024-03-12T11:52:47.9288028Z 	at org.testng.Assert.fail(Assert.java:110)
2024-03-12T11:52:47.9290046Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertFunctionEquals(AggregationTestUtils.java:138)
2024-03-12T11:52:47.9395032Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.groupedAggregation(AggregationTestUtils.java:390)
2024-03-12T11:52:47.9397665Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.groupedAggregation(AggregationTestUtils.java:355)
2024-03-12T11:52:47.9402222Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregationInternal(AggregationTestUtils.java:124)
2024-03-12T11:52:47.9404706Z 	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregation(AggregationTestUtils.java:85)
2024-03-12T11:52:47.9409938Z 	at com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd(TestNoisySumGaussianRealAggregation.java:296)
2024-03-12T11:52:47.9413341Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-03-12T11:52:47.9420899Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-03-12T11:52:47.9422451Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-03-12T11:52:47.9423703Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-03-12T11:52:47.9424994Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-03-12T11:52:47.9426568Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-03-12T11:52:47.9427969Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-03-12T11:52:47.9429384Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-03-12T11:52:47.9430876Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-03-12T11:52:47.9432407Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-03-12T11:52:47.9433963Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-03-12T11:52:47.9435460Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-03-12T11:52:47.9436848Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-03-12T11:52:47.9438228Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-03-12T11:52:47.9439941Z 	at java.lang.Thread.run(Thread.java:750)
2024-03-12T11:52:47.9440402Z 
2024-03-12T11:52:48.1097174Z [INFO] 
2024-03-12T11:52:48.1098020Z [INFO] Results:
2024-03-12T11:52:48.1098798Z [INFO] 
2024-03-12T11:52:48.1100625Z [ERROR] Failures: 
2024-03-12T11:52:48.1102867Z [ERROR]   TestNoisySumGaussianRealAggregation.testNoisySumGaussianRealClippingSomeNoiseScaleWithinSomeStd:296 Test: Inconsistent results with large group id, Expected: 47.52453364071998, actual: 42.442403576947314

**Comment by elharo** [comment]
I think the test is misunderstanding what standard deviation is and how it's calculated, though I might have to spend some time with a statistics book in hand to explain what's really going on here.

**Comment by rschlussel** [comment]
I'm still seeing this failure: 
```
Error:  Tests run: 8285, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1,461.751 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianDoubleAggregation.testNoisySumGaussianDoubleClippingSomeNoiseScaleWithinSomeStd  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.AssertionError: Test: Inconsistent results with reversed channels, Expected: 42.7871001051494, actual: 48.01681405531419
	at org.testng.Assert.fail(Assert.java:110)
	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertFunctionEquals(AggregationTestUtils.java:138)
	at com.facebook.presto.operator.aggregation.AggregationTestUtils.groupedAggregation(AggregationTestUtils.java:351)
	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregationInternal(AggregationTestUtils.java:124)
	at com.facebook.presto.operator.aggregation.AggregationTestUtils.assertAggregation(AggregationTestUtils.java:85)
	at com.facebook.presto.operator.aggregation.noisyaggregation.TestNoisySumGaussianDoubleAggregation.testNoisySumGaussianDoubleClippingSomeNoiseScaleWithinSomeStd(TestNoisySumGaussianDoubleAggregation.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
