### ISSUE TITLE
Flaky Test: TestDistributedQueuesDb.testResourceGroupConcurrencyThreshold

### ISSUE THREAD

**Issue by hantangwangd** [prestodb/presto#22291]
2024-03-22T00:09:55.1774644Z [ERROR] Tests run: 3111, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,312.115 s <<< FAILURE! - in TestSuite
2024-03-22T00:09:55.1777234Z [ERROR] com.facebook.presto.execution.resourceGroups.db.TestDistributedQueuesDb.testResourceGroupConcurrencyThreshold  Time elapsed: 59.989 s  <<< FAILURE!
2024-03-22T00:09:55.1781141Z org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.resourceGroups.db.TestDistributedQueuesDb.testResourceGroupConcurrencyThreshold() didn't finish within the time-out 60000
2024-03-22T00:09:55.1784419Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:347)
2024-03-22T00:09:55.1786723Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
2024-03-22T00:09:55.1788440Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
2024-03-22T00:09:55.1790055Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-03-22T00:09:55.1791791Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-03-22T00:09:55.1793918Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-03-22T00:09:55.1797030Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-03-22T00:09:55.1798553Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-03-22T00:09:55.1800100Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-03-22T00:09:55.1801434Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-03-22T00:09:55.1802766Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-03-22T00:09:55.1803826Z 	at java.lang.Thread.run(Thread.java:750)

See: https://github.com/prestodb/presto/actions/runs/8383071859/job/22958084889?pr=22281

**Comment by tdcmeehan** [comment]
I am fixing this in #22182
