### ISSUE TITLE
Error while executing refreshResourceGroupRuntimeInfo com.facebook.drift.client.UncheckedTTransportException: No hosts available

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22337]
Not sure where the root cause is on this one yet but attaching the log. Or not, log is 45 MB and 25 MB is the max. let me cut it into two parts

2024-03-26T12:27:19.8767754Z 2024-03-26T06:27:19.708-0600	ERROR	resource-group-manager-refresher-1-2	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Error while executing refreshResourceGroupRuntimeInfo
2024-03-26T12:27:19.8770841Z com.facebook.drift.client.UncheckedTTransportException: No hosts available
2024-03-26T12:27:19.8772464Z 	at com.facebook.drift.client.DriftInvocationHandler.invoke(DriftInvocationHandler.java:126)
2024-03-26T12:27:19.8774034Z 	at com.sun.proxy.$Proxy159.getResourceGroupInfo(Unknown Source)

**Comment by tdcmeehan** [comment]
@elharo can you add links to the logs where you discover this?

**Comment by elharo** [comment]
It was from presto-tests on https://github.com/prestodb/presto/pull/22251. I closed the window and reran after I saved the logs. I have them and can attach. I'm just somewhere over Colorado atm so bandwidth si a bit limited. :-)
