### ISSUE TITLE
TestPrestoNativeGeneralQueriesThrift>AbstractTestNativeGeneralQueries.testBinaryFunctions flaky failure

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22338]
Haven't seen this before. Might be the same root cause as some of the others we've seen in AbstractTestNativeGeneralQueries

```
[ERROR] Failures: 
[ERROR]   TestPrestoNativeGeneralQueriesThrift>AbstractTestNativeGeneralQueries.testBinaryFunctions:907->AbstractTestQueryFramework.assertQuery:154->AbstractTestQueryFramework.assertQuery:159 Execution of 'actual' query failed: SELECT from_base64url(to_base64url(cast(comment as varbinary))) FROM orders
```

**Comment by hantangwangd** [comment]
See this flaky again in the same method of another subclass: `TestPrestoSparkNativeGeneralQueries`, see https://github.com/prestodb/presto/actions/runs/17957753601/job/51074342454?pr=26134. The error stack is as follows:

```
 [ERROR] Tests run: 73, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 300.434 s <<< FAILURE! - in com.facebook.presto.spark.TestPrestoSparkNativeGeneralQueries
 [ERROR] com.facebook.presto.spark.TestPrestoSparkNativeGeneralQueries.testBinaryFunctions  Time elapsed: 7.52 s  <<< FAILURE!
 java.lang.AssertionError: Execution of 'actual' query failed: SELECT from_big_endian_32(to_big_endian_32(INT '2147483647'))
 	at org.testng.Assert.fail(Assert.java:98)
 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:213)
 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:141)
 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:177)
 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:172)
 	at com.facebook.presto.nativeworker.AbstractTestNativeGeneralQueries.testBinaryFunctions(AbstractTestNativeGeneralQueries.java:947)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)
 Caused by: java.lang.NullPointerException:Cannot invoke "java.util.concurrent.ScheduledFuture.cancel(boolean)" because "this.scheduledFuture" is null
 	at com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.onSuccess(HttpNativeExecutionTaskResultFetcher.java:176)
 	at com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.doGetResults(HttpNativeExecutionTaskResultFetcher.java:143)
 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 	at java.base/java.lang.Thread.run(Thread.java:840)
  com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.onSuccess(HttpNativeExecutionTaskResultFetcher.java:176)
  com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.doGetResults(HttpNativeExecutionTaskResultFetcher.java:143)
  java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
  java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base/java.lang.Thread.run(Thread.java:840)

 	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:67)
 	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:397)
 	at com.facebook.presto.spark.PrestoSparkQueryRunner.executeWithStrategies(PrestoSparkQueryRunner.java:579)
 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:553)
 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:210)
 	... 19 more
```

**Comment by hantangwangd** [comment]
+1, see: https://github.com/prestodb/presto/actions/runs/18331039544/job/52209271456?pr=22659

**Comment by xin-zhang2** [comment]
+1, see https://github.com/prestodb/presto/actions/runs/19106436937/job/54600163932?pr=26505

**Comment by hantangwangd** [comment]
+1: https://github.com/prestodb/presto/actions/runs/19253365918/job/55054344754?pr=26373
