### ISSUE TITLE
TestBitmap.testRoundTrip  flakes

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22393]
This was on a docs only change in https://github.com/prestodb/presto/pull/22389

:presto-main job
https://github.com/prestodb/presto/actions/runs/8513874447/job/23318441639?pr=22389

2024-04-01T21:41:40.7645882Z [ERROR] com.facebook.presto.operator.aggregation.noisyaggregation.sketch.TestBitmap.testRoundTrip  Time elapsed: 0.005 s  <<< FAILURE!
2024-04-01T21:41:40.7648102Z java.lang.AssertionError: arrays don't have the same size.  expected [100] but found [99]
2024-04-01T21:41:40.7649634Z 	at org.testng.Assert.fail(Assert.java:110)
2024-04-01T21:41:40.7650499Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-04-01T21:41:40.7651453Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
2024-04-01T21:41:40.7652397Z 	at org.testng.Assert.assertEquals(Assert.java:131)
2024-04-01T21:41:40.7653369Z 	at org.testng.Assert.assertEquals(Assert.java:1240)
2024-04-01T21:41:40.7654443Z 	at org.testng.Assert.checkRefEqualityAndLength(Assert.java:629)
2024-04-01T21:41:40.7655481Z 	at org.testng.Assert.assertEquals(Assert.java:248)
2024-04-01T21:41:40.7656367Z 	at org.testng.Assert.assertEquals(Assert.java:236)
2024-04-01T21:41:40.7658121Z 	at com.facebook.presto.operator.aggregation.noisyaggregation.sketch.TestBitmap.testRoundTrip(TestBitmap.java:35)
2024-04-01T21:41:40.7660321Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-01T21:41:40.7661526Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-01T21:41:40.7662920Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-01T21:41:40.7664078Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-04-01T21:41:40.7665372Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-04-01T21:41:40.7666908Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-04-01T21:41:40.7668235Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-04-01T21:41:40.7669760Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-04-01T21:41:40.7671239Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-04-01T21:41:40.7672754Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-04-01T21:41:40.7674481Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-04-01T21:41:40.7675961Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-04-01T21:41:40.7677315Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-04-01T21:41:40.7678746Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-04-01T21:41:40.7679746Z 	at java.lang.Thread.run(Thread.java:750)
2024-04-01T21:41:40.7680190Z 
2024-04-01T21:41:40.9201796Z [INFO] 
2024-04-01T21:41:40.9202259Z [INFO] Results:
2024-04-01T21:41:40.9202698Z [INFO] 
2024-04-01T21:41:40.9203040Z [ERROR] Failures: 
2024-04-01T21:41:40.9204289Z [ERROR]   TestBitmap.testRoundTrip:35 arrays don't have the same size.  expected [100] but found [99]
2024-04-01T21:41:40.9205298Z [INFO] 
2024-04-01T21:41:40.9205855Z [ERROR] Tests run: 8243, Failures: 1, Errors: 0, Skipped: 1
2024-04-01T21:41:40.9206291Z [INFO] 
2024-04-01T21:41:40.9267218Z [INFO] ------------------------------------------------------------------------
2024-04-01T21:41:40.9268030Z [INFO] BUILD FAILURE

**Comment by jonhehir** [comment]
My apologies. This was an oversight in a change made when open-sourcing this. Will commit a fix soon.

**Comment by ethanyzhang** [comment]
@tdcmeehan looks like this can be closed?
