### ISSUE TITLE
TestDirectoryListCacheInvalidation.testDirectoryListCacheInvalidation flakes

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22425]
part of [product-tests-basic-environment](https://github.com/prestodb/presto/actions/runs/8563059094/job/23486572111?pr=22008#logs)

```
2024-04-05T12:44:45.2986763Z 2024-04-05 18:29:45 INFO: FAILURE     /    com.facebook.presto.tests.hive.TestDirectoryListCacheInvalidation.testDirectoryListCacheInvalidation (Groups: hive_list_caching) took 1.1 seconds
2024-04-05T12:44:45.2992676Z 2024-04-05 18:29:45 SEVERE: Failure cause:
2024-04-05T12:44:45.2993582Z java.lang.AssertionError: expected [0] but found [1]
2024-04-05T12:44:45.2994337Z 	at org.testng.Assert.fail(Assert.java:110)
2024-04-05T12:44:45.2995197Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-04-05T12:44:45.2996010Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
2024-04-05T12:44:45.2996800Z 	at org.testng.Assert.assertEquals(Assert.java:131)
2024-04-05T12:44:45.2997583Z 	at org.testng.Assert.assertEquals(Assert.java:911)
2024-04-05T12:44:45.2998343Z 	at org.testng.Assert.assertEquals(Assert.java:945)
2024-04-05T12:44:45.3001854Z 	at com.facebook.presto.tests.hive.TestDirectoryListCacheInvalidation.testDirectoryListCacheInvalidation(TestDirectoryListCacheInvalidation.java:44)
2024-04-05T12:44:45.3003719Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-05T12:44:45.3004881Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-05T12:44:45.3006245Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-05T12:44:45.3007602Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-04-05T12:44:45.3008836Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-04-05T12:44:45.3010303Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-04-05T12:44:45.3011614Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-04-05T12:44:45.3012927Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-04-05T12:44:45.3014319Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-04-05T12:44:45.3017104Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-04-05T12:44:45.3018591Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-04-05T12:44:45.3020005Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-04-05T12:44:45.3021663Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-04-05T12:44:45.3022984Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-04-05T12:44:45.3023934Z 	at java.lang.Thread.run(Thread.java:748)
2024-04-05T12:44:45.3024347Z 
```

**Comment by tdcmeehan** [comment]
@agrawalreetika could you please have a look?

**Comment by ajaygeorge** [comment]
I think it is not even flaky at this point. Consistently failing for me.

**Comment by agrawalreetika** [comment]
I missed this issue earlier.
I just checked, looks like this particular test has failed for PRs that were raised starting yesterday. 

LMK if it would be better to disable it for now, and I can check what's going on here?

**Comment by elharo** [comment]
I don't think it's consistently failing. I have had it pass on reruns, sometimes more than one. But it is failing a lot.

**Comment by elharo** [comment]
If it just started failing recently, anyone happen to know of a suspicious PR that might have caused this?
