### ISSUE TITLE
TestIcebergParquetMetadataCaching.testParquetMetadataCaching looks flaky

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22422]
Likely flaky; need to rerun to be sure

```
2024-04-04T16:12:10.2637984Z [ERROR] Tests run: 2084, Failures: 1, Errors: 0, Skipped: 23, Time elapsed: 1,512.985 s <<< FAILURE! - in TestSuite
2024-04-04T16:12:10.2640602Z [ERROR] com.facebook.presto.iceberg.TestIcebergParquetMetadataCaching.testParquetMetadataCaching  Time elapsed: 0.401 s  <<< FAILURE!
2024-04-04T16:12:10.2642202Z java.lang.AssertionError: expected [true] but found [false]
2024-04-04T16:12:10.2642946Z 	at org.testng.Assert.fail(Assert.java:110)
2024-04-04T16:12:10.2643619Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-04-04T16:12:10.2644327Z 	at org.testng.Assert.assertTrue(Assert.java:56)
2024-04-04T16:12:10.2645010Z 	at org.testng.Assert.assertTrue(Assert.java:66)
2024-04-04T16:12:10.2646669Z 	at com.facebook.presto.iceberg.TestIcebergParquetMetadataCaching.testParquetMetadataCaching(TestIcebergParquetMetadataCaching.java:90)
2024-04-04T16:12:10.2648290Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-04T16:12:10.2649495Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-04T16:12:10.2650778Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-04T16:12:10.2651817Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-04-04T16:12:10.2652984Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-04-04T16:12:10.2654377Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-04-04T16:12:10.2655619Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-04-04T16:12:10.2656869Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-04-04T16:12:10.2658170Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-04-04T16:12:10.2659474Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-04-04T16:12:10.2660890Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-04-04T16:12:10.2662323Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-04-04T16:12:10.2663650Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-04-04T16:12:10.2664963Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-04-04T16:12:10.2665931Z 	at java.lang.Thread.run(Thread.java:750)
2024-04-04T16:12:10.2666347Z 
2024-04-04T16:12:10.9334912Z [INFO] 
2024-04-04T16:12:10.9335288Z [INFO] Results:
2024-04-04T16:12:10.9335694Z [INFO] 
2024-04-04T16:12:10.9336053Z [ERROR] Failures: 
2024-04-04T16:12:10.9337099Z [ERROR]   TestIcebergParquetMetadataCaching.testParquetMetadataCaching:90 expected [true] but found [false]
2024-04-04T16:12:10.9338247Z [INFO] 
2024-04-04T16:12:10.9338794Z [ERROR] Tests run: 2084, Failures: 1, Errors: 0, Skipped: 23
2024-04-04T16:12:10.9339232Z [INFO] 
```

**Comment by elharo** [comment]
Yep, passed on first rerun so likely flaky

**Comment by tdcmeehan** [comment]
@nmahadevuni can you please have a look?

**Comment by hantangwangd** [comment]
+1, I meet this too.

**Comment by pratyakshsharma** [comment]
I encountered this too.

**Comment by nmahadevuni** [comment]
Sorry, I missed this. Created a PR @elharo @tdcmeehan
