### ISSUE TITLE
Cannot instantiate class com.facebook.presto.elasticsearch.TestPasswordAuthentication

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22439]
```
2024-04-07T20:32:51.1775860Z com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint testcontainers-ryuk-27dab44b-c623-4187-91e1-5af92619409c (101dceae9e60d9e490930b1eb32fcfab60d4b758d314240eae5579184f7f09af): fork/exec /usr/bin/docker-proxy: exec format error"}
2024-04-07T20:32:51.1778790Z [ERROR] 
2024-04-07T20:32:51.1779261Z 
2024-04-07T20:32:51.1780523Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
2024-04-07T20:32:51.1782529Z Cannot instantiate class com.facebook.presto.elasticsearch.TestPasswordAuthentication
2024-04-07T20:32:51.1800137Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
2024-04-07T20:32:51.1803590Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
2024-04-07T20:32:51.1806077Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
2024-04-07T20:32:51.1808222Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
2024-04-07T20:32:51.1810059Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
2024-04-07T20:32:51.1811892Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
2024-04-07T20:32:51.1815470Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441)
2024-04-07T20:32:51.1817055Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
2024-04-07T20:32:51.1818631Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
2024-04-07T20:32:51.1820039Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
2024-04-07T20:32:51.1821310Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
2024-04-07T20:32:51.1822583Z 	at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:78)
2024-04-07T20:32:51.1823838Z 	at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
2024-04-07T20:32:51.1825106Z 	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:229)
2024-04-07T20:32:51.1828745Z 	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
2024-04-07T20:32:51.1830304Z 	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
2024-04-07T20:32:51.1831783Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
2024-04-07T20:32:51.1833312Z 	at com.facebook.presto.elasticsearch.ElasticsearchServer.<init>(ElasticsearchServer.java:51)
2024-04-07T20:32:51.1835055Z 	at com.facebook.presto.elasticsearch.TestPasswordAuthentication.<init>(TestPasswordAuthentication.java:60)
2024-04-07T20:32:51.1836615Z 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2024-04-07T20:32:51.1838064Z 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2024-04-07T20:32:51.1839794Z 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2024-04-07T20:32:51.1841243Z 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
2024-04-07T20:32:51.1842747Z 	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:38)
2024-04-07T20:32:51.1844064Z 	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:18)
2024-04-07T20:32:51.1845773Z 	at org.testng.internal.objects.SimpleObjectDispenser.instantiateUsingDefaultConstructor(SimpleObjectDispenser.java:178)
2024-04-07T20:32:51.1847750Z 	at org.testng.internal.objects.SimpleObjectDispenser.createInstance(SimpleObjectDispenser.java:87)
2024-04-07T20:32:51.1849427Z 	at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:40)
2024-04-07T20:32:51.1851104Z 	at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
2024-04-07T20:32:51.1852792Z 	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:106)
2024-04-07T20:32:51.1853928Z 	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:136)
2024-04-07T20:32:51.1854899Z 	at org.testng.TestClass.getInstances(TestClass.java:129)
2024-04-07T20:32:51.1855952Z 	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:109)
2024-04-07T20:32:51.1856927Z 	at org.testng.TestClass.init(TestClass.java:101)
2024-04-07T20:32:51.1857674Z 	at org.testng.TestClass.<init>(TestClass.java:66)
2024-04-07T20:32:51.1858507Z 	at org.testng.TestRunner.initMethods(TestRunner.java:465)
2024-04-07T20:32:51.1859347Z 	at org.testng.TestRunner.init(TestRunner.java:333)
2024-04-07T20:32:51.1860126Z 	at org.testng.TestRunner.init(TestRunner.java:286)
2024-04-07T20:32:51.1861122Z 	at org.testng.TestRunner.<init>(TestRunner.java:176)
2024-04-07T20:32:51.1862218Z 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:635)
2024-04-07T20:32:51.1863333Z 	at org.testng.SuiteRunner.init(SuiteRunner.java:221)
2024-04-07T20:32:51.1864157Z 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
2024-04-07T20:32:51.1865003Z 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1342)
2024-04-07T20:32:51.1865901Z 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1318)
2024-04-07T20:32:51.1866805Z 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1160)
2024-04-07T20:32:51.1867618Z 	at org.testng.TestNG.runSuites(TestNG.java:1092)
2024-04-07T20:32:51.1868327Z 	at org.testng.TestNG.run(TestNG.java:1060)
2024-04-07T20:32:51.1869310Z 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
2024-04-07T20:32:51.1870948Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
2024-04-07T20:32:51.1872774Z 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
2024-04-07T20:32:51.1874587Z 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
2024-04-07T20:32:51.1876092Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
2024-04-07T20:32:51.1877540Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
2024-04-07T20:32:51.1878823Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
2024-04-07T20:32:51.1880046Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
2024-04-07T20:32:51.1880591Z 
2024-04-07T20:32:51.1881161Z 2024-04-07T14:32:51.170-0600 SEVERE There are no stdout/stderr logs available for the failed container
2024-04-07T20:32:51.1911470Z [INFO] 
2024-04-07T20:32:51.1911885Z [INFO] Results:
2024-04-07T20:32:51.1912272Z [INFO] 
2024-04-07T20:32:51.1926792Z [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
2024-04-07T20:32:51.1927469Z [INFO] 
2024-04-07T20:32:51.1965421Z [INFO] ------------------------------------------------------------------------
2024-04-07T20:32:51.1966198Z [INFO] BUILD FAILURE
2024-04-07T20:32:51.1966928Z [INFO] ------------------------------------------------------------------------
2024-04-07T20:32:51.1978725Z [INFO] Total time:  6.906 s
2024-04-07T20:32:51.1980718Z [INFO] Finished at: 2024-04-07T20:32:51Z
2024-04-07T20:32:51.1981894Z [INFO] ------------------------------------------------------------------------
2024-04-07T20:32:51.2016586Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project presto-elasticsearch: 
2024-04-07T20:32:51.2018107Z [ERROR] 
2024-04-07T20:32:51.2019627Z [ERROR] Please refer to /home/runner/work/presto/presto/presto-elasticsearch/target/surefire-reports for the individual test results.
2024-04-07T20:32:51.2021738Z [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
2024-04-07T20:32:51.2022971Z [ERROR] There was an error in the forked process
2024-04-07T20:32:51.2023625Z [ERROR] 
2024-04-07T20:32:51.2024549Z [ERROR] Cannot instantiate class com.facebook.presto.elasticsearch.TestPasswordAuthentication
2024-04-07T20:32:51.2026305Z [ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
2024-04-07T20:32:51.2027495Z [ERROR] 
2024-04-07T20:32:51.2028085Z [ERROR] Cannot instantiate class com.facebook.presto.elasticsearch.TestPasswordAuthentication
2024-04-07T20:32:51.2029013Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:701)
2024-04-07T20:32:51.2030039Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
2024-04-07T20:32:51.2030943Z [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
2024-04-07T20:32:51.2032619Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
2024-04-07T20:32:51.2033842Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
2024-04-07T20:32:51.2035000Z [ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
2024-04-07T20:32:51.2036015Z [ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
2024-04-07T20:32:51.2036974Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
2024-04-07T20:32:51.2037849Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
2024-04-07T20:32:51.2038699Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
2024-04-07T20:32:51.2068854Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
2024-04-07T20:32:51.2070487Z [ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
2024-04-07T20:32:51.2072290Z [ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2024-04-07T20:32:51.2074495Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:210)
2024-04-07T20:32:51.2076819Z [ERROR] 	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:195)
2024-04-07T20:32:51.2078525Z [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2024-04-07T20:32:51.2079696Z [ERROR] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2024-04-07T20:32:51.2080881Z [ERROR] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2024-04-07T20:32:51.2082189Z [ERROR] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-04-07T20:32:51.2083692Z [ERROR] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-04-07T20:32:51.2084804Z [ERROR] 	at java.lang.Thread.run(Thread.java:750)
2024-04-07T20:32:51.2085535Z [ERROR] -> [Help 1]
2024-04-07T20:32:51.2085924Z [ERROR] 
2024-04-07T20:32:51.2086760Z [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2024-04-07T20:32:51.2088017Z [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2024-04-07T20:32:51.2088805Z [ERROR] 
2024-04-07T20:32:51.2089972Z [ERROR] For more information about the errors and possible solutions, please read the following articles:
2024-04-07T20:32:51.2091510Z [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
2024-04-07T20:32:51.2291655Z ##[error]Process completed with exit code 1.
2024-04-07T20:32:51.2363025Z Post job cleanup.
2024-04-07T20:32:51.2899305Z Post job cleanup.
```

**Comment by pmalek** [comment]
Also hit this and was looking for answers.

This issue comes from Github itself: https://github.com/actions/runner-images/issues/9654
