### ISSUE TITLE
TestIcebergParquetMetadataCaching.testParquetMetadataCaching  flakes

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22526]
2024-04-15T14:58:42.1581752Z [ERROR] Tests run: 2135, Failures: 1, Errors: 0, Skipped: 23, Time elapsed: 1,391.552 s <<< FAILURE! - in TestSuite
2024-04-15T14:58:42.1585116Z [ERROR] com.facebook.presto.iceberg.TestIcebergParquetMetadataCaching.testParquetMetadataCaching  Time elapsed: 0.392 s  <<< FAILURE!
2024-04-15T14:58:42.1587106Z java.lang.AssertionError: expected [true] but found [false]
2024-04-15T14:58:42.1588031Z 	at org.testng.Assert.fail(Assert.java:110)
2024-04-15T14:58:42.1588888Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-04-15T14:58:42.1589789Z 	at org.testng.Assert.assertTrue(Assert.java:56)
2024-04-15T14:58:42.1590711Z 	at org.testng.Assert.assertTrue(Assert.java:66)
2024-04-15T14:58:42.1592499Z 	at com.facebook.presto.iceberg.TestIcebergParquetMetadataCaching.testParquetMetadataCaching(TestIcebergParquetMetadataCaching.java:90)
2024-04-15T14:58:42.1594428Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-15T14:58:42.1595723Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-15T14:58:42.1597398Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-15T14:58:42.1598771Z 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-04-15T14:58:42.1600349Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-04-15T14:58:42.1602012Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-04-15T14:58:42.1603526Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-04-15T14:58:42.1605101Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-04-15T14:58:42.1606791Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-04-15T14:58:42.1608507Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-04-15T14:58:42.1610194Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-04-15T14:58:42.1611788Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-04-15T14:58:42.1613474Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-04-15T14:58:42.1615621Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2024-04-15T14:58:42.1616803Z 	at java.lang.Thread.run(Thread.java:750)
2024-04-15T14:58:42.1617417Z 
2024-04-15T14:58:42.5981440Z [INFO] 
2024-04-15T14:58:42.5981932Z [INFO] Results:
2024-04-15T14:58:42.5982398Z [INFO] 
2024-04-15T14:58:42.5982804Z [ERROR] Failures: 
2024-04-15T14:58:42.5983981Z [ERROR]   TestIcebergParquetMetadataCaching.testParquetMetadataCaching:90 expected [true] but found [false]
2024-04-15T14:58:42.5985112Z [INFO]

**Comment by elharo** [comment]
dupe of #22422
