### ISSUE TITLE
estMemoryRevokingScheduler.testTaskThresholdRevokingSchedulerImmediate flakes

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22568]
```
Error:  Tests run: 8297, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1,360.655 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.execution.TestMemoryRevokingScheduler.testTaskThresholdRevokingSchedulerImmediate  Time elapsed: 0.014 s  <<< FAILURE!
java.lang.AssertionError: expected memory  not requested for operator 1 expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertFalse(Assert.java:78)
	at com.facebook.presto.execution.TestMemoryRevokingScheduler.lambda$assertMemoryRevokingRequestedFor$11(TestMemoryRevokingScheduler.java:775)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.execution.TestMemoryRevokingScheduler.assertMemoryRevokingRequestedFor(TestMemoryRevokingScheduler.java:774)
	at com.facebook.presto.execution.TestMemoryRevokingScheduler.assertMemoryRevokingNotRequested(TestMemoryRevokingScheduler.java:780)
	at com.facebook.presto.execution.TestMemoryRevokingScheduler.testTaskThresholdRevokingSchedulerImmediate(TestMemoryRevokingScheduler.java:480)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
﻿2024-04-19T14:24:00.1890296Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestMemoryRevokingScheduler.testTaskThresholdRevokingSchedulerImmediate:480->assertMemoryRevokingNotRequested:780->assertMemoryRevokingRequestedFor:774->lambda$assertMemoryRevokingRequestedFor$11:775 expected memory  not requested for operator 1 expected [false] but found [true]
```

**Comment by hantangwangd** [comment]
+1, see here: https://github.com/prestodb/presto/actions/runs/12648120842/job/35241846612?pr=24221

**Comment by sumi-mathew** [comment]
+1 see here: https://github.com/prestodb/presto/actions/runs/18336815589/job/52222694264?pr=26199
