### ISSUE TITLE
Flaky TestSingleStoreDistributedQueries.testStdDev 

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22564]
Error:  Tests run: 552, Failures: 1, Errors: 0, Skipped: 10, Time elapsed: 552.735 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.plugin.singlestore.TestSingleStoreDistributedQueries.testStdDev  Time elapsed: 0.362 s  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT STDDEV_SAMP(totalprice) FROM (SELECT totalprice FROM orders ORDER BY totalprice LIMIT 2) T
	at org.testng.Assert.fail(Assert.java:98)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:159)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:154)
	at com.facebook.presto.tests.AbstractTestQueries.testStdDev(AbstractTestQueries.java:1249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: java.util.LinkedHashMap$Entry cannot be cast to java.util.HashMap$TreeNode
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:124)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:733)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:701)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:175)
	... 19 more
Caused by: com.facebook.presto.spi.PrestoException: java.util.LinkedHashMap$Entry cannot be cast to java.util.HashMap$TreeNode
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:236)
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:95)
	at com.facebook.presto.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:59)
	at com.facebook.presto.spi.RecordPageSource.<init>(RecordPageSource.java:40)
	at com.facebook.presto.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:48)
	at com.facebook.presto.spi.connector.ConnectorPageSourceProvider.createPageSource(ConnectorPageSourceProvider.java:52)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:80)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:263)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:441)
	at com.facebook.presto.operator.Driver.lambda$processFor$10(Driver.java:324)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:750)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:317)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
	at com.facebook.presto.$gen.Presto_0_288_SNAPSHOT_9d8e4a3__testversion____20240418_182206_133.run(Unknown Source)
	... 3 more
Caused by: java.lang.ClassCastException: java.util.LinkedHashMap$Entry cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1859)
	at java.util.HashMap$TreeNode.treeify(HashMap.java:1975)
	at java.util.HashMap.treeifyBin(HashMap.java:773)
	at java.util.HashMap.putVal(HashMap.java:645)
	at java.util.HashMap.put(HashMap.java:613)
	at com.singlestore.jdbc.util.ClientParser.parameterParts(ClientParser.java:180)
	at com.singlestore.jdbc.ClientPreparedStatement.<init>(ClientPreparedStatement.java:68)
	at com.singlestore.jdbc.Connection.prepareInternal(Connection.java:143)
	at com.singlestore.jdbc.Connection.prepareStatement(Connection.java:110)
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getPreparedStatement(BaseJdbcClient.java:605)
	at com.facebook.presto.plugin.jdbc.QueryBuilder.buildSql(QueryBuilder.java:150)
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.buildSql(BaseJdbcClient.java:308)
	at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:90)
	... 17 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    TestSingleStoreDistributedQueries>AbstractTestQueries.testStdDev:1249->AbstractTestQueryFramework.assertQuery:154->AbstractTestQueryFramework.assertQuery:159 Execution of 'actual' query failed: SELECT STDDEV_SAMP(totalprice) FROM (SELECT totalprice FROM orders ORDER BY totalprice LIMIT 2) T

**Comment by tdcmeehan** [comment]
@oyeliseiev-ua could you help look at this?  Looks like a bug in the SingleStore client.
