### ISSUE TITLE
presto-cli should not print stack trace for recognized user error 

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22613]
Here's an error I just got. This is fine. The query is syntactically incorrect. I should have quoted $row_id. This is a user mistake and presto-cli correctly recognized and reported it. 

What presto shouldn't do in this case is print a stack trace. There's no internal failure here, or any debugging to be done inside presto. The stack trace is inappropriate useless cruft. It blurs the distinction between presto users and presto developers. Syntactically incorrect user input is not an exceptional condition. It is an expected and regular occurrence. Even if exceptions are used internally for managing this, it should not be exposed to end users. 

```
presto:sf1> select $row_id from customer limit 10;
Query 20240424_230834_00067_y9zaa failed: line 1:8: mismatched input '$'. Expecting: '*', 'ALL', 'DISTINCT', <expression>, <identifier>
com.facebook.presto.sql.parser.ParsingException: line 1:8: mismatched input '$'. Expecting: '*', 'ALL', 'DISTINCT', <expression>, <identifier>
	at com.facebook.presto.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
	at org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:266)
	at com.facebook.presto.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:6313)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:6091)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:5896)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:5687)
	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:4481)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2116)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:268)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:173)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:108)
	at com.facebook.presto.sql.analyzer.BuiltInQueryPreparer.prepareQuery(BuiltInQueryPreparer.java:70)
	at com.facebook.presto.sql.analyzer.BuiltInQueryPreparer.prepareQuery(BuiltInQueryPreparer.java:56)
	at com.facebook.presto.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:290)
	at com.facebook.presto.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:254)
	at com.facebook.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
select $row_id from customer limit 10
```

**Comment by elharo** [comment]
Only happens with --debug flag, probably OK
