### ISSUE TITLE
TestIcebergParquetMetadataCaching.testParquetMetadataCaching is flaky

### ISSUE THREAD

**Issue by ZacBlanco** [prestodb/presto#22810]
```
 Error:  Tests run: 2194, Failures: 1, Errors: 0, Skipped: 23, Time elapsed: 1,406.876 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.iceberg.TestIcebergParquetMetadataCaching.testParquetMetadataCaching  Time elapsed: 0.481 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertTrue(Assert.java:56)
	at org.testng.Assert.assertTrue(Assert.java:66)
	at com.facebook.presto.iceberg.TestIcebergParquetMetadataCaching.testParquetMetadataCaching(TestIcebergParquetMetadataCaching.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

in this [action](https://github.com/prestodb/presto/actions/runs/9195360958/job/25295952641?pr=22694)

[logs_24067574839.zip](https://github.com/prestodb/presto/files/15407957/logs_24067574839.zip)

**Comment by hantangwangd** [comment]
This problem have been reported before in #22422 , #22526. Feels like something involving race condition.

**Comment by ZacBlanco** [comment]
Huh. This didn't come up when I searched before. I'll close this issue
