### ISSUE TITLE
Fencepost error in row IDs

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#22822]
Select "$row_id" AS verify_row_id from di.global_compendium_tables where ds='2024-05-20' LIMIT 9; fails 

whereas

select "$row_id" AS verify_row_id from di.global_compendium_tables where ds='2024-05-20' LIMIT 8; succeeds

```
Caused by: java.lang.IllegalArgumentException: Invalid position 1 in block with 1 positions
        at com.facebook.presto.common.block.BlockUtil.checkValidPosition(BlockUtil.java:76)
        at com.facebook.presto.common.block.AbstractVariableWidthBlock.checkReadablePosition(AbstractVariableWidthBlock.java:191)
        at
```

This is a big clue:

select table_id, "$row_id" from di.global_compendium_tables where ds='2024-05-20' LIMIT 9;

succeeds but

select "$row_id", table_id from di.global_compendium_tables where ds='2024-05-20' LIMIT 9;
fails

That is, the problem only occurs when "$row_id" is the last columns selected by the query.

Note this code in RowIterable

```
        @Override
        protected List<Object> computeNext()
        {
            position++;
            if (position >= page.getPositionCount()) {
                return endOfData();
            }
 ```

        
Problem might not be that we're counting too far but that page.getPositionCount() is returning a number that's 1 too small

**Comment by elharo** [comment]
What kind of block do we have in this case and is the position count there accurate for a terminal row ID?
