### ISSUE TITLE
Flaky test TestParquetReader.testStructOfTwoNestedArrays

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#22907]
Error:  Tests run: 3131, Failures: 1, Errors: 0, Skipped: 90, Time elapsed: 2,626.714 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.hive.parquet.TestParquetReader.testStructOfTwoNestedArrays  Time elapsed: 0.238 s  <<< FAILURE!
java.lang.NullPointerException
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.readDictionaryPage(ParquetColumnChunk.java:241)
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.buildPageReader(ParquetColumnChunk.java:116)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReaderInternal(ParquetReader.java:494)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReader(ParquetReader.java:487)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:366)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:550)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readStruct(ParquetReader.java:309)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:541)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:533)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:208)
	at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:313)
	at com.facebook.presto.common.block.LazyBlock.isNull(LazyBlock.java:277)
	at com.facebook.presto.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:811)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:546)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:530)
	at com.facebook.presto.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:522)
	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:391)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:321)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:223)
	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testStructOfTwoNestedArrays(AbstractTestParquetReader.java:787)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by rschlussel** [comment]
https://github.com/prestodb/presto/actions/runs/9356119094/job/25752830540

**Comment by hantangwangd** [comment]
It seems that I met the same problem that caused flaky in another test method:

```
Error:  Failures: 
Error:    TestFullParquetReader>AbstractTestParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray:285 » NullPointer
```

Error stack:

```
Error:  com.facebook.presto.hive.parquet.TestFullParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray  Time elapsed: 11.192 s  <<< FAILURE!
java.lang.NullPointerException
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.readDictionaryPage(ParquetColumnChunk.java:241)
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.buildPageReader(ParquetColumnChunk.java:116)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReaderInternal(ParquetReader.java:494)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReader(ParquetReader.java:487)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:366)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:550)
	at com.facebook.presto.parquet.reader.ParquetReader.readStruct(ParquetReader.java:309)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:541)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:533)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:208)
	at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:313)
	at com.facebook.presto.common.block.LazyBlock.isNull(LazyBlock.java:277)
	at com.facebook.presto.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:811)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:546)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:530)
	at com.facebook.presto.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:522)
	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:391)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:330)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:304)
	at com.facebook.presto.hive.parquet.ParquetTester.testSingleLevelArrayRoundTrip(ParquetTester.java:271)
	at com.facebook.presto.hive.parquet.ParquetTester.testSingleLevelArraySchemaRoundTrip(ParquetTester.java:212)
	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray(AbstractTestParquetReader.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

The link is: https://github.com/prestodb/presto/actions/runs/12152493908/job/33888990649?pr=24074

**Comment by ZacBlanco** [comment]
I have recently seen this error come up again in `testSingleLevelSchemaArrayOfArrayOfStructOfArray` today. I did some local testing and just set the invocation count to a large number and was able to reproduce it several times on my local machine.

```java
    @Test(invocationCount = 1024)
    public void testSingleLevelSchemaArrayOfArrayOfStructOfArray()
            throws Exception
....
```


<details><summary>Stacktrace</summary>
<p>

```

java.lang.NullPointerException
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.readDictionaryPage(ParquetColumnChunk.java:241)
	at com.facebook.presto.parquet.reader.ParquetColumnChunk.buildPageReader(ParquetColumnChunk.java:116)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReaderInternal(ParquetReader.java:494)
	at com.facebook.presto.parquet.reader.ParquetReader.createPageReader(ParquetReader.java:487)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:366)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:550)
	at com.facebook.presto.parquet.reader.ParquetReader.readStruct(ParquetReader.java:309)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:541)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readArray(ParquetReader.java:273)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:547)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:533)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:208)
	at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:313)
	at com.facebook.presto.common.block.LazyBlock.isNull(LazyBlock.java:277)
	at com.facebook.presto.hive.parquet.ParquetTester.decodeObject(ParquetTester.java:811)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:546)
	at com.facebook.presto.hive.parquet.ParquetTester.assertPageSource(ParquetTester.java:530)
	at com.facebook.presto.hive.parquet.ParquetTester.assertFileContents(ParquetTester.java:522)
	at com.facebook.presto.hive.parquet.ParquetTester.assertRoundTrip(ParquetTester.java:391)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTripType(ParquetTester.java:330)
	at com.facebook.presto.hive.parquet.ParquetTester.testRoundTrip(ParquetTester.java:304)
	at com.facebook.presto.hive.parquet.ParquetTester.testSingleLevelArrayRoundTrip(ParquetTester.java:271)
	at com.facebook.presto.hive.parquet.ParquetTester.testSingleLevelArraySchemaRoundTrip(ParquetTester.java:212)
	at com.facebook.presto.hive.parquet.AbstractTestParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray(AbstractTestParquetReader.java:386)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```

</p>
</details>

**Comment by hantangwangd** [comment]
I have risen a PR to fix this problem. The core thing is that we should close and recreate `ValuesWriter`s rather than reuse them after write and flush a whole column chunk (row group level flush). See the comment for `ValuesWriterFactory` [here](https://github.com/apache/parquet-java/blob/92354f6be7ee3b5930c82408102b10a6b2b5f3c2/parquet-column/src/main/java/org/apache/parquet/column/values/factory/ValuesWriterFactory.java#L35).

Please take a look when available @rschlussel @ZacBlanco, thanks!

**Comment by hantangwangd** [comment]
Meet another fail in method `TestFullParquetReader.testSingleLevelSchemaArrayOfArrayOfStructOfArray`, which seems to be the same issue. See here: https://github.com/prestodb/presto/actions/runs/14004593199/job/39216720785?pr=24524.
