### ISSUE TITLE
PREPARE fails for INSERT statements using non-standard characters (ex: '-') in quoted identifiers

### ISSUE THREAD

**Issue by scott-hart-domo** [prestodb/presto#23187]
When executing a PREPARE command for an INSERT statement, if the quoted identifiers used in the query contain characters not permitted in an unquoted identifier (ex: '-') then the PREPARE command fails during query parsing.

## Your Environment

* Presto version used: 0.285
* Storage (HDFS/S3/GCS..): N/A - the PREPARE fails before accessing storage
* Data source and connector used: N/A - the PREPARE fails before accessing the datasource
* Deployment (Cloud or On-prem): On-premise

## Expected Behavior

PREPARE commands should preserve the quoted state of the identifiers used in INSERT commands so non-standard characters can be used in quoted identifiers.

## Current Behavior

The PREPARE command fails with the following error:
```
com.facebook.presto.jdbc.internal.client.FailureInfo$FailureException: Formatted query does not parse: Insert{target=hive_data.my-testing.dataset, columns=Optional.empty, query=Query{queryBody=(ROW (?, ?)), orderBy=Optional.empty}}
	at com.facebook.presto.sql.SqlFormatterUtil.getFormattedSql(SqlFormatterUtil.java:44)
	at com.facebook.presto.execution.PrepareTask.execute(PrepareTask.java:72)
	at com.facebook.presto.execution.PrepareTask.execute(PrepareTask.java:40)
	at com.facebook.presto.execution.SessionDefinitionExecution.executeTask(SessionDefinitionExecution.java:64)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:217)
	at com.facebook.presto.$gen.Presto_0_285_1____20240530_172523_1.run(Unknown Source)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:307)
	at com.facebook.presto.dispatcher.LocalDispatchQuery.lambda$startExecution$8(LocalDispatchQuery.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:839)
Wrapped by: java.sql.SQLException: Query failed (#20240711_144135_00011_9mhud): Formatted query does not parse: Insert{target=hive_data.my-testing.dataset, columns=Optional.empty, query=Query{queryBody=(ROW (?, ?)), orderBy=Optional.empty}}
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1841)
	at com.facebook.presto.jdbc.PrestoResultSet.getColumns(PrestoResultSet.java:1751)
	at com.facebook.presto.jdbc.PrestoResultSet.<init>(PrestoResultSet.java:121)
	at com.facebook.presto.jdbc.PrestoStatement.internalExecute(PrestoStatement.java:272)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:230)
	at com.facebook.presto.jdbc.PrestoPreparedStatement.<init>(PrestoPreparedStatement.java:85)
	at com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:167)
	at com.facebook.presto.jdbc.PrestoConnection.prepareStatement(PrestoConnection.java:360)
```

## Steps to Reproduce

1. Execute the following SQL command (modified from https://prestodb.io/docs/current/sql/prepare.html): `PREPARE my_insert FROM INSERT INTO "cities-1" VALUES (1, 'San Francisco');`
2. Note the error thrown.
3. Comparable SQL that executes normally: `PREPARE my_insert FROM INSERT INTO "cities_1" VALUES (1, 'San Francisco');`

## Context

INSERT statements are highly suspect as they often utilize user-provided data, and as such expose a SQL injection attack vector. A common mitigation to SQL injection is to utilize parameterized prepared statements, but being unable to prepare statements to insert into catalogs/schemas/tables that require using quoted identifiers due to non-standard characters severely limits the ability to mitigate this attack vector for those catalogs/schemas/tables.

**Comment by imjalpreet** [comment]
@scott-hart-domo Can you try cherry-picking the changes in #19827 and see if it resolves your issue? If yes, I can try to move it forward soon.

**Comment by scott-hart-domo** [comment]
@imjalpreet Unfortunately I don't have control over the prestodb installation the bug was identified in, as it is used as a component in a watsonx.data installation and I have to wait for them to issue an update to their product.

The following test demonstrates the issue, but requires a fully deployed prestodb installation:

    public void testPrepareWithQuotedDashIdentifier(Connection conn) throws Exception {

        boolean prepared = false;
        try(PreparedStatement statement = conn.prepareStatement("INSERT INTO \"cities-1\" VALUES (1, 'San Francisco')")
        ) {
            prepared = true;
        }

        Assert.assertTrue("Failed to prepare insert statement using quoted identifier with a '-' character included", prepared);
    }
