### ISSUE TITLE
testQueryHeartbeat is flaky

### ISSUE THREAD

**Issue by elharo** [prestodb/presto#23235]
Another test that looks fundamentally probabilistic and flaky. We really should stop writing and including these.

```
2024-07-17T00:52:18.1917691Z [ERROR] Tests run: 8391, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1,346.493 s <<< FAILURE! - in TestSuite
2024-07-17T00:52:18.1920380Z [ERROR] com.facebook.presto.resourcemanager.TestResourceManagerClusterStatusSender.testQueryHeartbeat  Time elapsed: 1.008 s  <<< FAILURE!
2024-07-17T00:52:18.1923186Z java.lang.AssertionError: Expect number of heartbeats to fall within target range (10), +/- 50%.  Was: 4 expected [true] but found [false]
2024-07-17T00:52:18.1942673Z 	at org.testng.Assert.fail(Assert.java:110)
2024-07-17T00:52:18.1943656Z 	at org.testng.Assert.failNotEquals(Assert.java:1413)
2024-07-17T00:52:18.1944462Z 	at org.testng.Assert.assertTrue(Assert.java:56)
2024-07-17T00:52:18.2040828Z 	at 
```

**Comment by hantangwangd** [comment]
+1

https://github.com/prestodb/presto/actions/runs/11669419952/job/32491350301?pr=23793

**Comment by hantangwangd** [comment]
Reopen this issue, see again here: https://github.com/prestodb/presto/actions/runs/15641521576/job/44071025616?pr=25293

```
Error:  Tests run: 8547, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1,253.092 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.resourcemanager.TestResourceManagerClusterStatusSender.testQueryHeartbeat  Time elapsed: 0.16 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertTrue(Assert.java:56)
	at org.testng.Assert.assertTrue(Assert.java:66)
	at com.facebook.presto.resourcemanager.TestResourceManagerClusterStatusSender.testQueryHeartbeat(TestResourceManagerClusterStatusSender.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:44)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:72)
	at org.testng.internal.invokers.InvokeMethodRunnable.run(InvokeMethodRunnable.java:32)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:331)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by hantangwangd** [comment]
+1, see: https://github.com/prestodb/presto/actions/runs/16877500794/job/47807074452?pr=25737
