### ISSUE TITLE
Iceberg read failing for Decimal type

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#23274]
After the introduction of the decimal batch reader(https://github.com/prestodb/presto/pull/22636) in Presto, when trying to read iceberg tables with decimal columns with `parquet_batch_read_optimization_enabled`=true, we are getting the below error

```
java.lang.ClassCastException: com.facebook.presto.parquet.batchreader.decoders.rle.Int32RLEDictionaryValuesDecoder cannot be cast to com.facebook.presto.parquet.batchreader.decoders.ValuesDecoder$ShortDecimalValuesDecoder
	at com.facebook.presto.parquet.batchreader.ShortDecimalFlatBatchReader.readNextPage(ShortDecimalFlatBatchReader.java:139)
	at com.facebook.presto.parquet.batchreader.ShortDecimalFlatBatchReader.readWithNull(ShortDecimalFlatBatchReader.java:156)
	at com.facebook.presto.parquet.batchreader.ShortDecimalFlatBatchReader.readNext(ShortDecimalFlatBatchReader.java:104)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:389)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:550)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:533)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:208)
	at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:313)
	at com.facebook.presto.common.block.LazyBlock.getLoadedBlock(LazyBlock.java:304)
	at com.facebook.presto.common.Page.getLoadedPage(Page.java:335)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:269)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:441)
	at com.facebook.presto.operator.Driver.lambda$processFor$10(Driver.java:324)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:750)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:317)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
	at com.facebook.presto.$gen.Presto_null__testversion____20240722_195546_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The issue happens when trying to read dictionary-encoded data.

## Your Environment

* Presto version used: latest master
* Storage (HDFS/S3/GCS..): S3
* Data source and connector used: Iceberg
* Deployment (Cloud or On-prem): Cloud

## Expected Behavior

We should be able to read the data without any issue

## Current Behavior

```
java.lang.ClassCastException: com.facebook.presto.parquet.batchreader.decoders.rle.Int32RLEDictionaryValuesDecoder cannot be cast to com.facebook.presto.parquet.batchreader.decoders.ValuesDecoder$ShortDecimalValuesDecoder
	at com.facebook.presto.parquet.batchreader.ShortDecimalFlatBatchReader.readNextPage(ShortDecimalFlatBatchReader.java:139)
	at com.facebook.presto.parquet.batchreader.ShortDecimalFlatBatchReader.readWithNull(ShortDecimalFlatBatchReader.java:156)
	at com.facebook.presto.parquet.batchreader.ShortDecimalFlatBatchReader.readNext(ShortDecimalFlatBatchReader.java:104)
	at com.facebook.presto.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:389)
	at com.facebook.presto.parquet.reader.ParquetReader.readColumnChunk(ParquetReader.java:550)
	at com.facebook.presto.parquet.reader.ParquetReader.readBlock(ParquetReader.java:533)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:230)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:208)
	at com.facebook.presto.common.block.LazyBlock.assureLoaded(LazyBlock.java:313)
	at com.facebook.presto.common.block.LazyBlock.getLoadedBlock(LazyBlock.java:304)
	at com.facebook.presto.common.Page.getLoadedPage(Page.java:335)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:269)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:441)
	at com.facebook.presto.operator.Driver.lambda$processFor$10(Driver.java:324)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:750)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:317)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:165)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:621)
	at com.facebook.presto.$gen.Presto_null__testversion____20240722_195546_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
## Possible Solution

We need to add an implementation for Int32ShortDecimalRLEDictionaryValuesDecoder and the remaining missing decoders similar to how we have added when it's `PLAIN` and `DELTA_BINARY_PACKED` parquet encoding.

## Steps to Reproduce

1. CREATE TABLE iceberg_decimal (decimal_column decimal(5,2));
2. INSERT into iceberg_decimal values(-1.00),(1.00),(-1.00),(1.00);
3. SET SESSION iceberg.parquet_batch_read_optimization_enabled=true; 
4. SELECT * from iceberg_decimal;

**Comment by imjalpreet** [comment]
When writing Hive Parquet Files, the decimal type gets mapped to the FIXED_LEN_BYTE_ARRAY primitive type. Since we have the respective dictionary decoders for that, we don't see any issues from the Hive connector. But in the case of the Iceberg Parquet Files, similar writes for decimal columns get mapped to int32/int64 and since we don't have dictionary decoders for short decimals as int32/int64, we are facing the above issue.

**Comment by wypb** [comment]
Hi @imjalpreet Thanks for the feedback, I will fix this issue.

**Comment by ethanyzhang** [comment]
We did see this on our TPC-DS tests with hive tables as well.
56 out of 99 TPC-DS queries are affected.
