### ISSUE TITLE
TestEventListener.testPrepareAndExecute is flaky

### ISSUE THREAD

**Issue by rschlussel** [prestodb/presto#23448]
Example failure: https://github.com/prestodb/presto/actions/runs/10393975339/job/28782708706?pr=23447
```
Error:  Tests run: 76, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 350.615 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.execution.TestEventListener.testPrepareAndExecute  Time elapsed: 1.419 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.assertNotNull(Assert.java:1319)
	at org.testng.Assert.assertNotNull(Assert.java:1303)
	at com.facebook.presto.execution.TestEventListener.testPrepareAndExecute(TestEventListener.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by rschlussel** [comment]
@pgupta2 the failure is in the part of the test you added in https://github.com/prestodb/presto/pull/23195. Can you take a look?

**Comment by hantangwangd** [comment]
+1, see: https://github.com/prestodb/presto/actions/runs/15098815426/job/42437063785?pr=25140

**Comment by rschlussel** [comment]
seeing this again

**Comment by hantangwangd** [comment]
From my observation, in this flaky test case, the methods `addQueryProgress` and `getQueryProgressEvent` of `generatedEvents` would be invoked by different threads (e.g. `query-progress-monitor-executor` and `main`). This could lead to a scenario where thread `main` calling `getQueryProgressEvent` fails to immediately observe the updated `generatedEvents.queryProgressEvent` set by thread `query-progress-monitor-executor` via `addQueryProgress`, due to lack of proper synchronization.

So I think that adding a `volatile` modifier to field `queryProgressEvent` in `EventsBuilder` should resolve this issue. Will send a PR for this fix.

**Comment by hantangwangd** [comment]
Closing as fixed by #25270.
