### ISSUE TITLE
Presto encountered a Malformed ORC file while querying Hive tables, specifically Caused by: java. io. IOException: java. lang. CollectalArgumentException: minimum is not less than maximum

### ISSUE THREAD

**Issue by lijingzhuang** [prestodb/presto#23709]
Presto：0.285 Hive：CDH6.3 Hive 2.1
SQL:
`CREATE TABLE tmp.xxxxx AS
SELECT
A.cid                                                                       AS cid
,COALESCE(B.create_time                  ,A.create_time                    ) AS create_time
,COALESCE(B.product_code                 ,A.product_code                   ) AS product_code
,COALESCE(B.strategy_code                ,A.strategy_code                  ) AS strategy_code
,COALESCE(B.input                        ,A.input                          ) AS input
,COALESCE(B.output                       ,A.output                         ) AS output
,COALESCE(B.reject_reason                ,A.reject_reason                  ) AS reject_reason
,COALESCE(B.sms_ownerbusiness            ,A.sms_ownerbusiness              ) AS sms_ownerbusiness
,COALESCE(B.status                       ,A.status                         ) AS status
,COALESCE(B.policy                       ,A.policy                         ) AS policy
,COALESCE(B.isinformationflow            ,A.isinformationflow              ) AS isinformationflow
,COALESCE(B.is_xxl_accesss               ,A.is_xxl_accesss                 ) AS is_xxl_accesss
,COALESCE(B.merchanttype                 ,A.merchanttype                   ) AS merchanttype
,COALESCE(B.ownerbusiness                ,A.ownerbusiness                  ) AS ownerbusiness
,COALESCE(B.ownersubject                 ,A.ownersubject                   ) AS ownersubject
,COALESCE(B.adchannel                    ,A.adchannel                      ) AS adchannel
,COALESCE(B.addchannel                   ,A.addchannel                     ) AS addchannel
,COALESCE(B.businessid                   ,A.businessid                     ) AS businessid
,COALESCE(B.dzlprotocolflag              ,A.dzlprotocolflag                ) AS dzlprotocolflag
,COALESCE(B.is_capital_update            ,A.is_capital_update              ) AS is_capital_update
,COALESCE(B.if_risk_dzl                  ,A.if_risk_dzl                    ) AS if_risk_dzl
,COALESCE(B.is_rule_test                 ,A.is_rule_test                   ) AS is_rule_test
,COALESCE(B.is_rule_test_tcuni           ,A.is_rule_test_tcuni             ) AS is_rule_test_tcuni
,COALESCE(B.isapproval                   ,A.isapproval                     ) AS isapproval
,COALESCE(B.if_strategy_recall           ,A.if_strategy_recall             ) AS if_strategy_recall
,COALESCE(B.reject_reason_hit_cnt        ,A.reject_reason_hit_cnt          ) AS reject_reason_hit_cnt
,COALESCE(B.risktype                     ,A.risktype                       ) AS risktype
,COALESCE(B.is_highpass_test             ,A.is_highpass_test               ) AS is_highpass_test
,COALESCE(B.lh_dl_001                    ,A.lh_dl_001                      ) AS lh_dl_001
,COALESCE(B.lh_dl_002                    ,A.lh_dl_002                      ) AS lh_dl_002
,COALESCE(B.lh_dl_003                    ,A.lh_dl_003                      ) AS lh_dl_003
,COALESCE(B.lh_dl_004                    ,A.lh_dl_004                      ) AS lh_dl_004
,COALESCE(B.hard_reject_rules_hit        ,A.hard_reject_rules_hit          ) AS hard_reject_rules_hit
,COALESCE(B.hard_reject_rules_hit_2      ,A.hard_reject_rules_hit_2        ) AS hard_reject_rules_hit_2
,COALESCE(B.is_api_dl                    ,A.is_api_dl                      ) AS is_api_dl
,COALESCE(B.base_amount                  ,A.base_amount                    ) AS base_amount
,COALESCE(B.adjust_amount                ,A.adjust_amount                  ) AS adjust_amount
,COALESCE(B.suggestamount                ,A.suggestamount                  ) AS suggestamount
,COALESCE(B.if_increase_amount           ,A.if_increase_amount             ) AS if_increase_amount
,COALESCE(B.quota_eff_end_time           ,A.quota_eff_end_time             ) AS quota_eff_end_time
,COALESCE(B.amtadj_ratio                 ,A.amtadj_ratio                   ) AS amtadj_ratio
,COALESCE(B.scorecard_cross              ,A.scorecard_cross                ) AS scorecard_cross
,COALESCE(B.jc_newgradelevel             ,A.jc_newgradelevel               ) AS jc_newgradelevel
,COALESCE(B.amt_level                    ,A.amt_level                      ) AS amt_level
,COALESCE(B.brsr_income_pre              ,A.brsr_income_pre                ) AS brsr_income_pre
,COALESCE(B.dxm_income_pre               ,A.dxm_income_pre                 ) AS dxm_income_pre
,COALESCE(B.pfsr_income_pre              ,A.pfsr_income_pre                ) AS pfsr_income_pre
,COALESCE(B.pfsr_income_pre_true         ,A.pfsr_income_pre_true           ) AS pfsr_income_pre_true
,COALESCE(B.final_income_pre             ,A.final_income_pre               ) AS final_income_pre
,COALESCE(B.dxm_income_pre_update        ,A.dxm_income_pre_update          ) AS dxm_income_pre_update
,COALESCE(B.pfsr_income_pre_update       ,A.pfsr_income_pre_update         ) AS pfsr_income_pre_update
,COALESCE(B.brsr_group                   ,A.brsr_group                     ) AS brsr_group
,COALESCE(B.pfsr_group                   ,A.pfsr_group                     ) AS pfsr_group
,COALESCE(B.brsr_suggest_amount          ,A.brsr_suggest_amount            ) AS brsr_suggest_amount
,COALESCE(B.pfsr_suggest_amount          ,A.pfsr_suggest_amount            ) AS pfsr_suggest_amount
,COALESCE(B.dxm_suggest_amount           ,A.dxm_suggest_amount             ) AS dxm_suggest_amount
,COALESCE(B.brsr_increase_ratio          ,A.brsr_increase_ratio            ) AS brsr_increase_ratio
,COALESCE(B.pfsr_increase_ratio          ,A.pfsr_increase_ratio            ) AS pfsr_increase_ratio
,COALESCE(B.dxm_increase_ratio           ,A.dxm_increase_ratio             ) AS dxm_increase_ratio
,COALESCE(B.prior_route                  ,A.prior_route                    ) AS prior_route
,COALESCE(B.pbcagreement_state_plus      ,A.pbcagreement_state_plus        ) AS pbcagreement_state_plus
,COALESCE(B.auth_target                  ,A.auth_target                    ) AS auth_target
,COALESCE(B.rhjx_adjustmentfactor        ,A.rhjx_adjustmentfactor          ) AS rhjx_adjustmentfactor
,COALESCE(B.rhjx_ad_hit_cnt              ,A.rhjx_ad_hit_cnt                ) AS rhjx_ad_hit_cnt
,COALESCE(B.rhjx_ra_hit_cnt              ,A.rhjx_ra_hit_cnt                ) AS rhjx_ra_hit_cnt
,COALESCE(B.ct_24_amount_005             ,A.ct_24_amount_005               ) AS ct_24_amount_005
,COALESCE(B.ct_24_new_007                ,A.ct_24_new_007                  ) AS ct_24_new_007
,COALESCE(B.customer_price               ,A.customer_price                 ) AS customer_price
,COALESCE(B.feetype                      ,A.feetype                        ) AS feetype
,COALESCE(B.price_type                   ,A.price_type                     ) AS price_type
,COALESCE(B.process_type                 ,A.process_type                   ) AS process_type
,COALESCE(B.limit_cap_01_amount_age      ,A.limit_cap_01_amount_age        ) AS limit_cap_01_amount_age
,COALESCE(B.limit_cap_02_amount_age      ,A.limit_cap_02_amount_age        ) AS limit_cap_02_amount_age
,COALESCE(B.limit_cap_03_amount_antifraud,A.limit_cap_03_amount_antifraud  ) AS limit_cap_03_amount_antifraud
,COALESCE(B.limit_cap_04_amount_dxm      ,A.limit_cap_04_amount_dxm        ) AS limit_cap_04_amount_dxm
,COALESCE(B.limit_cap_05_amount_rh       ,A.limit_cap_05_amount_rh         ) AS limit_cap_05_amount_rh
,COALESCE(B.real_time_marketing_limit    ,A.real_time_marketing_limit      ) AS real_time_marketing_limit
,COALESCE(B.is_xxlhc_back                ,A.is_xxlhc_back                  ) AS is_xxlhc_back
,COALESCE(B.antifraud_flag               ,A.antifraud_flag                 ) AS antifraud_flag
,COALESCE(B.jc_g_user_profile_score      ,A.jc_g_user_profile_score        ) AS jc_g_user_profile_score
,COALESCE(B.rand_no                      ,A.rand_no                        ) AS rand_no
,COALESCE(B.als_m3_id_nbank_orgnum       ,A.als_m3_id_nbank_orgnum         ) AS als_m3_id_nbank_orgnum
,COALESCE(B.als_m3_id_bank_orgnum        ,A.als_m3_id_bank_orgnum          ) AS als_m3_id_bank_orgnum
,COALESCE(B.bad_hit_cnt                  ,A.bad_hit_cnt                    ) AS bad_hit_cnt
,COALESCE(B.good_hit_cnt                 ,A.good_hit_cnt                   ) AS good_hit_cnt
,COALESCE(B.bad_hit                      ,A.bad_hit                        ) AS bad_hit
,COALESCE(B.good_hit                     ,A.good_hit                       ) AS good_hit
,COALESCE(B.corp_increase_ratio          ,A.corp_increase_ratio            ) AS corp_increase_ratio
,COALESCE(B.zx_increase_ratio            ,A.zx_increase_ratio              ) AS zx_increase_ratio
,COALESCE(B.overdueamt                   ,A.overdueamt                     ) AS overdueamt
,COALESCE(B.score_334_bin                ,A.score_334_bin                  ) AS score_334_bin
,COALESCE(B.score_337_bin                ,A.score_337_bin                  ) AS score_337_bin
,COALESCE(B.xxl_model_score_bin          ,A.xxl_model_score_bin            ) AS xxl_model_score_bin
,COALESCE(B.xxl_rule_score_bin           ,A.xxl_rule_score_bin             ) AS xxl_rule_score_bin
,COALESCE(B.quality_group                ,A.quality_group                  ) AS quality_group
,COALESCE(B.cust_type_real               ,A.cust_type_real                 ) AS cust_type_real
,COALESCE(B.cust_type                    ,A.cust_type                      ) AS cust_type
,COALESCE(B.score_379_lr_bin             ,A.score_379_lr_bin               ) AS score_379_lr_bin
,COALESCE(B.score337_ql_fill_bin         ,A.score337_ql_fill_bin           ) AS score337_ql_fill_bin
,COALESCE(B.score359_1_bin2              ,A.score359_1_bin2                ) AS score359_1_bin2
,COALESCE(B.score367_1_bin               ,A.score367_1_bin                 ) AS score367_1_bin
,COALESCE(B.if_strategy_recall_dl        ,A.if_strategy_recall_dl          ) AS if_strategy_recall_dl
,COALESCE(B.if_strategy_recall_dl_2      ,A.if_strategy_recall_dl_2        ) AS if_strategy_recall_dl_2
,COALESCE(B.is_xxlhc_fullvalue           ,A.is_xxlhc_fullvalue             ) AS is_xxlhc_fullvalue
,COALESCE(B.rules_score_v1               ,A.rules_score_v1                 ) AS rules_score_v1
,COALESCE(B.cz_type                      ,A.cz_type                        ) AS cz_type
,COALESCE(B.yj_score                     ,A.yj_score                       ) AS yj_score
,COALESCE(B.is_xxlhc_riskback            ,A.is_xxlhc_riskback              ) AS is_xxlhc_riskback
,COALESCE(B.is_xxlhc_risklevel           ,A.is_xxlhc_risklevel             ) AS is_xxlhc_risklevel
,COALESCE(B.lh_dl_004_new                ,A.lh_dl_004_new                  ) AS lh_dl_004_new
,COALESCE(B.lh_dl_005                    ,A.lh_dl_005                      ) AS lh_dl_005
,COALESCE(B.lh_dl_006                    ,A.lh_dl_006                      ) AS lh_dl_006
,COALESCE(B.randomNum20_zrx              ,A.randomNum20_zrx                ) AS randomNum20_zrx
,COALESCE(B.score436                     ,A.score436                       ) AS score436
,COALESCE(B.hard_reject_rules_hit_data   ,A.hard_reject_rules_hit_data     ) AS hard_reject_rules_hit_data
FROM dwd.dwd_loan_analysis_of_xxl_info a
LEFT JOIN tmp.xxxxxx b
ON a.cid = b.cid
UNION ALL
SELECT  *
FROM tmp.xxx t
WHERE not exists (
SELECT  1
FROM dwd.dwd_loan_analysis_of_xxl_info t2
WHERE t.cid = t2.cid)
;`
Error:
`[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - Query 20240922_192413_05990_63xa5 failed: Malformed ORC file. Invalid stripe row index [hdfs://nwdservice/user/hive/warehouse/dwd.db/dwd_loan_analysis_of_xxl_info/000003_0]
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - com.facebook.presto.spi.PrestoException: Malformed ORC file. Invalid stripe row index [hdfs://nwdservice/user/hive/warehouse/dwd.db/dwd_loan_analysis_of_xxl_info/000003_0]
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.hive.orc.OrcBatchPageSource.getNextPage(OrcBatchPageSource.java:173)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:129)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:293)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:258)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:426)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.operator.Driver.lambda$processFor$9(Driver.java:309)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:730)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.operator.Driver.processFor(Driver.java:302)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1079)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:166)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:599)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.$gen.Presto_0_275_f3f1035____20240922_140158_1.run(Unknown Source)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.lang.Thread.run(Thread.java:835)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - Caused by: com.facebook.presto.orc.OrcCorruptionException: Malformed ORC file. Invalid stripe row index [hdfs://nwdservice/user/hive/warehouse/dwd.db/dwd_loan_analysis_of_xxl_info/000003_0]
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.propagate(ExceptionWrappingMetadataReader.java:128)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.readRowIndexes(ExceptionWrappingMetadataReader.java:107)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.StorageStripeMetadataSource.getRowIndexes(StorageStripeMetadataSource.java:74)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.StripeReader.readColumnIndexes(StripeReader.java:533)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:194)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextStripe(AbstractOrcRecordReader.java:667)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.AbstractOrcRecordReader.advanceToNextRowGroup(AbstractOrcRecordReader.java:551)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.AbstractOrcRecordReader.prepareNextBatch(AbstractOrcRecordReader.java:606)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.OrcBatchRecordReader.nextBatch(OrcBatchRecordReader.java:114)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.hive.orc.OrcBatchPageSource.getNextPage(OrcBatchPageSource.java:148)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	... 14 more
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - Caused by: java.io.IOException: java.lang.IllegalArgumentException: minimum is not less than maximum
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.OrcCorruptionException.<init>(OrcCorruptionException.java:36)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	... 24 more
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - Caused by: java.lang.IllegalArgumentException: minimum is not less than maximum
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:141)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.statistics.StringStatistics.<init>(StringStatistics.java:43)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.OrcMetadataReader.toStringStatistics(OrcMetadataReader.java:343)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.OrcMetadataReader.toColumnStatistics(OrcMetadataReader.java:275)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.OrcMetadataReader.toRowGroupIndex(OrcMetadataReader.java:265)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.OrcMetadataReader.lambda$readRowIndexes$3(OrcMetadataReader.java:235)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.OrcMetadataReader.readRowIndexes(OrcMetadataReader.java:236)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	at com.facebook.presto.orc.metadata.ExceptionWrappingMetadataReader.readRowIndexes(ExceptionWrappingMetadataReader.java:104)
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - 	... 22 more
[2024-09-23, 03:24:08 UTC] {subprocess.py:92} INFO - execute faied!
[2024-09-23, 03:24:08 UTC] {subprocess.py:96} INFO - Command exited with return code 1
[2024-09-23, 03:24:10 UTC] {taskinstance.py:1920} ERROR - Task failed with exception`

**Comment by agrawalreetika** [comment]
@lijingzhuang Could you please share your cluster configuration & catalog configurations?
