### ISSUE TITLE
Preston on Spark for SQL Server Connector Error: Catalog doesn't support page sink commit.

### ISSUE THREAD

**Issue by samer1977** [prestodb/presto#23720]
Initially I opened this as usage post and did not hear anything. Given that I could not find any documentation in Presto Docs that says  that SQL Server Connector is not supported for this feature, Im going to assume its a bug.

To reproduce, I followed the instructions [here](https://prestodb.io/docs/current/installation/spark.html) and my spark-sbmit looks like the following:
```
spark-submit 
--master spark://localhost:7077 
--executor-cores 4 
--conf spark.task.cpus=4
--class com.facebook.presto.spark.launcher.PrestoSparkLauncher 
  presto-spark-launcher-0.289.jar 
--package presto-spark-package-0.289.tar.gz 
--config ./presto/config.properties 
--catalogs ./presto/catalog 
--catalog sqlserver 
--schema dbo 
--file ./presto/jobs/insert_transform.sql
```
Once I run the above command it looks its starting to run and I see a lot of log for PluginManager, Bootstrap then my query then it start showing different fragements ....until it throws the following exception:

```

24/09/24 14:48:06 INFO LifeCycleManager: Life cycle stopping...
24/09/24 14:48:06 INFO LifeCycleManager: Life cycle stopping...
24/09/24 14:48:06 INFO LifeCycleManager: Life cycle stopped.
24/09/24 14:48:06 INFO LifeCycleManager: Life cycle stopped.
com.facebook.presto.spi.PrestoException: catalog does not support page sink commit: sqlserver
        at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:59)
        at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:395)
        at com.facebook.presto.spark.launcher.PrestoSparkRunner.execute(PrestoSparkRunner.java:181)
        at com.facebook.presto.spark.launcher.PrestoSparkRunner.run(PrestoSparkRunner.java:125)
        at com.facebook.presto.spark.launcher.PrestoSparkLauncherCommand.run(PrestoSparkLauncherCommand.java:78)
        at com.facebook.presto.spark.launcher.PrestoSparkLauncher.main(PrestoSparkLauncher.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:75)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:52)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
24/09/24 14:48:06 INFO SparkContext: Invoking stop() from shutdown hook
```

Thanks

**Comment by samer1977** [comment]
Hi, 
I was trying to do an insert statement in my query and it turns out that its what is not supported. You can run select query and it will work just fine, however I was so disappointed with the performance. I was thinking by combining the power of spark with Presto the performance would be better at least compared to Presto **but to the contrary it tooks much longer to execute under spark its not even comparable**. Does anybody know why is that. Is there something that can be done to tune\improve performance? I tried to run sql jobs using Apache spark and we had a lot of success with that and Im running the presto sql jub under the same spark configuration. my sql query is multiple CTE statement that get all combined using union all:


```

with cte1 as (
....
), cte2 as
(
...
), cte3 
(
...
)
select * from cte1
union all
select * from cte2
union all
select * from cte3
```

**Comment by agrawalreetika** [comment]
@samer1977 Just curious is it working with hive catalog in spark-submit as mentioned in https://prestodb.io/docs/current/installation/spark.html?
