### ISSUE TITLE
[native] int64 timestamp column in Parquet overflowing to large values

### ISSUE THREAD

**Issue by kishansairam9** [prestodb/presto#23769]
Running the following query failed multiple times with too large timestamp error
```sql
select stringcol1, stringcol2 from iceberg_table where hour(start_time_millis_ts) = hour(from_unixtime(1727568000)) limit 10;
```
The exact same query on same datasource finished on Trino without any issues, so no corruption in data, something is happening in presto native layer.

## Your Environment

* Presto version used: main of native
* Storage (HDFS/S3/GCS..): GCS
* Data source and connector used: Hive Iceberg
* Deployment (Cloud or On-prem): Cloud
* [Pastebin](https://pastebin.com/) link to the complete debug logs: none

## Expected Behavior

Query finishes with no error and returns columns

## Current Behavior

Fails with timestamp conversion as too large since epoch. Each time a different seconds from epoch is provided with large values. Probably initialisation or invalid access issue.
```
presto:iceberg_datalake> select stringcol1, stringcol2 from iceberg_table where hour(start_time_millis_ts) = hour(from_unixtime(1727568000)) limit 10;
Query 20241001_192148_00013_4su8m, FAILED, 2 nodes
Splits: 49 total, 14 done (28.57%)
[Latency: client-side: 0:14, server-side: 0:14] [2.56K rows, 1MB] [185 rows/s, 74.1KB/s]
Query 20241001_192148_00013_4su8m failed: Timestamp::epochToCalendarUtc(seconds, dateTime) Timestamp is too large: 8030609101356820831 seconds since epoch presto.default.hour(start_time_millis_ts) Top-level Expression: presto.default.eq(presto.default.hour(start_time_millis_ts), 0:BIGINT)
presto:iceberg_datalake> select stringcol1, stringcol2 from iceberg_table where hour(start_time_millis_ts) = hour(from_unixtime(1727568000)) limit 10;
Query 20241001_192522_00016_4su8m, FAILED, 2 nodes
Splits: 33 total, 0 done (0.00%)
[Latency: client-side: 0:13, server-side: 0:13] [403 rows, 197KB] [30 rows/s, 15KB/s]
Query 20241001_192522_00016_4su8m failed: Timestamp::epochToCalendarUtc(seconds, dateTime) Timestamp is too large: 3759773652000976176 seconds since epoch presto.default.hour(start_time_millis_ts) Top-level Expression: presto.default.eq(presto.default.hour(start_time_millis_ts), 0:BIGINT)
presto:iceberg_datalake> select stringcol1, stringcol2 from iceberg_table where hour(start_time_millis_ts) = hour(from_unixtime(1727568000)) limit 10;
Query 20241001_192842_00017_4su8m, FAILED, 2 nodes
Splits: 33 total, 12 done (36.36%)
[Latency: client-side: 0:14, server-side: 0:14] [640 rows, 289KB] [47 rows/s, 21.4KB/s]
Query 20241001_192842_00017_4su8m failed: Timestamp::epochToCalendarUtc(seconds, dateTime) Timestamp is too large: 2484628535384698473 seconds since epoch presto.default.hour(start_time_millis_ts) Top-level Expression: presto.default.eq(presto.default.hour(start_time_millis_ts), 0:BIGINT)
```

## Steps to Reproduce

I have shared a sample data from the iceberg partition which this query should act on to @majetideepak, cannot attach it here on public forum. Please reach out over Presto Slack `@Kishan` if you would like to investigate this.

## Context

We are experimenting with presto native to improve our SLAs on datalake. This failure of simple query doesn't inspire confidence for switching in near future.

**Comment by yingsu00** [comment]
@kishansairam9 What is the data type for start_time_millis_ts? timestamp(3)? Do you have the sample data that we can reproduce it?

**Comment by zuyu** [comment]
It seems `hour` in Presto does NOT support to take a varchar as input.

```
presto> select hour('2024-09-29T00:00:38.186Z');
Query 20241112_024444_00002_n2fkv failed: line 1:8: Unexpected parameters (varchar(24)) for function hour. Expected: hour(timestamp) , hour(time) , hour(time with time zone) , hour(interval day to second) , hour(timestamp with time zone)
com.facebook.presto.sql.analyzer.SemanticException: line 1:8: Unexpected parameters (varchar(24)) for function hour. Expected: hour(timestamp) , hour(time) , hour(time with time zone) , hour(interval day to second) , hour(timestamp with time zone)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.resolveFunction(ExpressionAnalyzer.java:1833)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1110)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:389)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:136)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:412)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:350)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1937)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1921)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:2922)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:2746)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1738)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:359)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:373)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:381)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1166)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:359)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:373)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:351)
	at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:117)
	at com.facebook.presto.sql.analyzer.BuiltInQueryAnalyzer.analyze(BuiltInQueryAnalyzer.java:93)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:210)
	at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:111)
	at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:990)
	at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:170)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
select hour('2024-09-29T00:00:38.186Z')
```

**Comment by zuyu** [comment]
Fixed by https://github.com/facebookincubator/velox/pull/11530
