### ISSUE TITLE
Java 17 Upgrade

### ISSUE THREAD

**Issue by imjalpreet** [prestodb/presto#23788]
Parent Issue: https://github.com/prestodb/presto/issues/23785

Based on my preliminary analysis, we need to make the below changes to successfully build and run Presto with Java 17.

### Upgrade spotbugs-annotations and spotbugs-maven-plugin to 4.2.2
This change needs to be made in [airbase/pom.xml](https://github.com/prestodb/airbase/blob/df953500d1754d307821be5756ef9c8c8bb00f0f/airbase/pom.xml#L191)

```
[ERROR] Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:3.1.10:spotbugs (spotbugs) on project presto-root: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:3.1.10:spotbugs failed: Unable to load the mojo 'spotbugs' in the plugin 'com.github.spotbugs:spotbugs-maven-plugin:3.1.10'. A required class is missing: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
```

### Upgrade provisio-maven-plugin
We see the below exception in multiple plugins

```
[ERROR] Failed to execute goal io.takari.maven.plugins:provisio-maven-plugin:0.1.40:provision (default-provision) on project presto-cluster-ttl-providers: Execution default-provision of goal io.takari.maven.plugins:provisio-maven-plugin:0.1.40:provision failed: A required class was missing while executing io.takari.maven.plugins:provisio-maven-plugin:0.1.40:provision: Could not initialize class com.thoughtworks.xstream.converters.collections.TreeMapConverter
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>io.takari.maven.plugins:provisio-maven-plugin:0.1.40
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/imjalpreet/.m2/repository/io/takari/maven/plugins/provisio-maven-plugin/0.1.40/provisio-maven-plugin-0.1.40.jar
[ERROR] urls[1] = file:/Users/imjalpreet/.m2/repository/io/provis/provisio-model/0.1.40/provisio-model-0.1.40.jar
[ERROR] urls[2] = file:/Users/imjalpreet/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[3] = file:/Users/imjalpreet/.m2/repository/com/thoughtworks/xstream/xstream/1.4.7/xstream-1.4.7.jar
[ERROR] urls[4] = file:/Users/imjalpreet/.m2/repository/xmlpull/xmlpull/1.1.3.1/xmlpull-1.1.3.1.jar
[ERROR] urls[5] = file:/Users/imjalpreet/.m2/repository/xpp3/xpp3_min/1.1.4c/xpp3_min-1.1.4c.jar
[ERROR] urls[6] = file:/Users/imjalpreet/.m2/repository/org/codehaus/swizzle/swizzle-stream/1.6.2/swizzle-stream-1.6.2.jar
[ERROR] urls[7] = file:/Users/imjalpreet/.m2/repository/io/provis/provisio-core/0.1.40/provisio-core-0.1.40.jar
[ERROR] urls[8] = file:/Users/imjalpreet/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[9] = file:/Users/imjalpreet/.m2/repository/org/apache/maven/maven-builder-support/3.3.3/maven-builder-support-3.3.3.jar
[ERROR] urls[10] = file:/Users/imjalpreet/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[11] = file:/Users/imjalpreet/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[12] = file:/Users/imjalpreet/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[13] = file:/Users/imjalpreet/.m2/repository/org/sonatype/plexus/plexus-cipher/1.7/plexus-cipher-1.7.jar
[ERROR] urls[14] = file:/Users/imjalpreet/.m2/repository/com/squareup/okhttp/okhttp/2.0.0/okhttp-2.0.0.jar
[ERROR] urls[15] = file:/Users/imjalpreet/.m2/repository/com/squareup/okio/okio/1.0.0/okio-1.0.0.jar
[ERROR] urls[16] = file:/Users/imjalpreet/.m2/repository/io/takari/takari-archiver/0.1.17/takari-archiver-0.1.17.jar
[ERROR] urls[17] = file:/Users/imjalpreet/.m2/repository/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
[ERROR] urls[18] = file:/Users/imjalpreet/.m2/repository/io/takari/incrementalbuild/0.7.0/incrementalbuild-0.7.0.jar
[ERROR] urls[19] = file:/Users/imjalpreet/.m2/repository/io/takari/incrementalbuild-workspace/0.7.0/incrementalbuild-workspace-0.7.0.jar
[ERROR] urls[20] = file:/Users/imjalpreet/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>com.facebook.presto:presto-root:0.290-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : Exception java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @7fa7b865 [in thread "mvn-builder-presto-node-ttl-fetchers"]
```

To fix this, we need to upgrade the `provisio-maven-plugin` . Currently we are using `io.takari.maven.plugins:provisio-maven-plugin:0.1.40` but this doesn’t support Java 17. We will be upgrading it to 
`ca.vanzyl.provisio.maven.plugins:provisio-maven-plugin:1.0.18`  which supports Java 17.

This change needs to happen in [presto-maven-plugin/pom.xml](https://github.com/prestodb/presto-maven-plugin/blob/78d45d1a1b125488c4894a34e2f6733081b1381d/pom.xml#L23)

https://central.sonatype.com/artifact/ca.vanzyl.provisio.maven.plugins/provisio-maven-plugin/1.0.18/overview

### Changes due to Maven Plugins Upgrade

Due to the [airbase/pom.xml](https://github.com/prestodb/airbase/blob/df953500d1754d307821be5756ef9c8c8bb00f0f/airbase/pom.xml#L191) upgrade, some maven plugins will also be upgraded to 3.1.x. This leads to a few exceptions as mentioned below.

- To resolve the below exception, we must add the license to `presto-grpc-api/src/main/proto/GrpcUdfInvoke.proto` . We can do this by running `../mvnw license:format` from `presto-grpc-api` directory.

```
[INFO] --- license-maven-plugin:4.3:check (default) @ presto-grpc-api ---
[INFO] Checking licenses...
[WARNING] Missing header in: /Users/imjalpreet/Documents/OSS/master/presto-grpc-api/src/main/proto/GrpcUdfInvoke.proto

[ERROR] Failed to execute goal com.mycila:license-maven-plugin:4.3:check (default) on project presto-grpc-api: Some files do not have the expected license header. Run license:format to update them. -> [Help 1]
```

- The below exception is related to: https://issues.apache.org/jira/browse/MINSTALL-151. With `maven-install-plugin` and `maven-deploy-plugin` versions ≥ 3.0.0-M1, we start to see the below exception. 

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:27 min (Wall Clock)
[INFO] Finished at: 2024-10-01T02:14:26+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:3.1.1:install (default-install) on project presto-native-execution: The packaging plugin for this project did not assign a main file to the project but it has attachments. Change packaging to 'pom'. -> [Help 1]
```

To overcome this, we need to set 
```
<configuration>
     <allowIncompleteProjects>true</allowIncompleteProjects>
</configuration>
```

This needs to be set in [airbase/pom.xml](https://github.com/prestodb/airbase/blob/df953500d1754d307821be5756ef9c8c8bb00f0f/airbase/pom.xml#L256). This above property was added since version 3.1.1 which is the version we are using in Presto. [Apache Maven Deploy Plugin – deploy:deploy](https://maven.apache.org/plugins/maven-deploy-plugin/deploy-mojo.html#allowIncompleteProjects) and [Apache Maven Install Plugin – install:install](https://maven.apache.org/plugins/maven-install-plugin/install-mojo.html#allowIncompleteProjects)

After the above changes, we will be able to successfully build Presto with Java 17. But when starting the server in Java 17 runtime, we see the below exceptions.

### Upgrade Guice

The below exception can be resolved by upgrading Guice from 4.2.2 to 5.0.1.

This change needs to be done in [airbase/pom.xml ](https://github.com/prestodb/airbase/blob/df953500d1754d307821be5756ef9c8c8bb00f0f/airbase/pom.xml#L179)

```
2024-10-03T00:28:40.327+0530    INFO    main    com.google.inject.Guice An exception was caught and reported. Message: java.lang.ExceptionInInitializerError: Exception com.google.inject.internal.cglib.core.$CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @136636fa [in thread "main"]
java.lang.IllegalStateException: Unable to load cache item
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:291)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
...
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
        ... 19 more
```

### Bypass module restrictions to access JDK internal APIs

After upgrading Guice, we see multiple exceptions. One of them is below:

```
2024-10-03T01:22:08.975+0530    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at HdfsEnvironment.<init>(HdfsEnvironment.java:47)
  at IcebergCommonModule.setup(IcebergCommonModule.java:121)
  at IcebergPageSourceProvider.<init>(IcebergPageSourceProvider.java:213)
      \_ for 1st parameter hdfsEnvironment
  while locating IcebergPageSourceProvider
  at IcebergCommonModule.setup(IcebergCommonModule.java:146)
  while locating ConnectorPageSourceProvider

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: ExceptionInInitializerError
        at HdfsEnvironment$$FastClassByGuice$$7433095.GUICE$TRAMPOLINE(<generated>)
        at HdfsEnvironment$$FastClassByGuice$$7433095.apply(<generated>)
        at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at ConstructorInjector.provision(ConstructorInjector.java:114)
        at ConstructorInjector.access$000(ConstructorInjector.java:33)
        at ConstructorInjector$1.call(ConstructorInjector.java:98)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        ...
Caused by: InaccessibleObjectException: Unable to make private native Field[] Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @144658b1
        at java.base/AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/Method.checkCanSetAccessible(Method.java:200)
        at java.base/Method.setAccessible(Method.java:194)
        at HadoopExtendedFileSystemCache.getModifiersField(HadoopExtendedFileSystemCache.java:60)
        at HadoopExtendedFileSystemCache.setFinalStatic(HadoopExtendedFileSystemCache.java:39)
        at HadoopExtendedFileSystemCache.initialize(HadoopExtendedFileSystemCache.java:29)
        at HdfsEnvironment.<clinit>(HdfsEnvironment.java:35)
        ... 51 more
```

We can overcome this exception by adding the below flag in jvm.config

`--add-opens=java.base/java.lang=ALL-UNNAMED`

Next exception we see is similar to the below stacktrace:

```
2024-10-03T01:28:18.349+0530    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ExceptionInInitializerError
  at HdfsEnvironment.<init>(HdfsEnvironment.java:47)
  at IcebergCommonModule.setup(IcebergCommonModule.java:121)
  at IcebergPageSourceProvider.<init>(IcebergPageSourceProvider.java:213)
      \_ for 1st parameter hdfsEnvironment
  while locating IcebergPageSourceProvider
  at IcebergCommonModule.setup(IcebergCommonModule.java:146)
  while locating ConnectorPageSourceProvider

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Caused by: ExceptionInInitializerError
        at HdfsEnvironment$$FastClassByGuice$$8035720.GUICE$TRAMPOLINE(<generated>)
        at HdfsEnvironment$$FastClassByGuice$$8035720.apply(<generated>)
        at DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
        at ConstructorInjector.provision(ConstructorInjector.java:114)
        at ConstructorInjector.access$000(ConstructorInjector.java:33)
        at ConstructorInjector$1.call(ConstructorInjector.java:98)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
        at LifeCycleModule.provision(LifeCycleModule.java:54)
        at ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        ...
Caused by: InaccessibleObjectException: Unable to make field private int Field.modifiers accessible: module java.base does not "opens java.lang.reflect" to unnamed module @7499553f
        at java.base/AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/Field.checkCanSetAccessible(Field.java:178)
        at java.base/Field.setAccessible(Field.java:172)
        at HadoopExtendedFileSystemCache.setFinalStatic(HadoopExtendedFileSystemCache.java:40)
        at HadoopExtendedFileSystemCache.initialize(HadoopExtendedFileSystemCache.java:29)
        at HdfsEnvironment.<clinit>(HdfsEnvironment.java:35)
        ... 51 more
```

We can overcome this by adding the below flag in jvm.config

`--add-opens=java.base/java.lang.reflect=ALL-UNNAMED`

After making the above changes, we can successfully build and start Presto Server with Java 17.

[Java17Upgrade.pdf](https://github.com/user-attachments/files/17295700/Java17Upgrade.pdf)

**Comment by aaneja** [comment]
## W.r.t to the Guice exceptions

Looking at the error stack, I see the common trace path of
```
at HadoopExtendedFileSystemCache.setFinalStatic
...
```

that is forcing us to use the `add-opens` for the internal JVM class(es).
Could upgrading the HDFS dependency mitigate this need ?

**Comment by beinan** [comment]
Awesome!  Thank you so much for the work @imjalpreet !  As @aaneja mentioned, do we have any plan to upgrade hdfs dependecies?

**Comment by imjalpreet** [comment]
Closed by #24866
