### ISSUE TITLE
TestQueues.testEagerPlanValidation() is flaky

### ISSUE THREAD

**Issue by hantangwangd** [prestodb/presto#23838]
Example failure: https://github.com/prestodb/presto/actions/runs/11350506950/job/31569394356?pr=23837

```
Error:  Tests run: 77, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 469.432 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.execution.TestQueues.testEagerPlanValidation  Time elapsed: 46.685 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.TestQueues.testEagerPlanValidation() didn't finish within the time-out 240000
	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:347)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:294)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:679)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by BryanCutler** [comment]
A fix has been merged and I haven't seen the test acting flaky, can this be closed?

**Comment by hantangwangd** [comment]
Sure, thanks for the fix! @BryanCutler
