### ISSUE TITLE
Error 'The scope is invalid' when connecting to Polaris using OAuth2 credentials

### ISSUE THREAD

**Issue by denodo-research-labs** [prestodb/presto#23833]
When we configure the `iceberg.rest.auth.oauth2.credential` property to connect to a Polaris catalog we get the error `The scope is invalid`. 
Since the Presto code does not set the 'scope' property, the Iceberg code is using 'catalog' as scope and the OAuth2 endpoint is considering it an invalid scope.

## Your Environment
* Presto  0.289
* Storage S3
* Connector used: Iceberg connector with Rest Catalog
* Trace:
```
Caused by: org.apache.iceberg.exceptions.BadRequestException: Malformed request: invalid_scope: The scope is invalid
    at org.apache.iceberg.rest.ErrorHandlers$OAuthErrorHandler.accept(ErrorHandlers.java:254)
    at org.apache.iceberg.rest.ErrorHandlers$OAuthErrorHandler.accept(ErrorHandlers.java:228)
    at org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:201)
    at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:313)
    at org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:252)
    at org.apache.iceberg.rest.HTTPClient.postForm(HTTPClient.java:399)
    at org.apache.iceberg.rest.auth.OAuth2Util.fetchToken(OAuth2Util.java:216)
    at org.apache.iceberg.rest.RESTSessionCatalog.initialize(RESTSessionCatalog.java:189)
    at org.apache.iceberg.rest.RESTCatalog.initialize(RESTCatalog.java:78)
    at org.apache.iceberg.CatalogUtil.loadCatalog(CatalogUtil.java:255)
    at com.facebook.presto.iceberg.IcebergNativeCatalogFactory.lambda$getCatalog$0(IcebergNativeCatalogFactory.java:83)
```

## Expected Behavior
The request to obtain the OAuth2 token should be valid.

## Current Behavior
The following error is obtained:
`  Query failed (#20241015_085300_00005_qxhdt): org.apache.iceberg.exceptions.BadRequestException: Malformed request: invalid_scope: The scope is invalid`

## Possible Solution
A new configuration property to set the scope

## Steps to Reproduce

This is the properties file of the Iceberg catalog:
```
connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest.uri=<polaris URI>
iceberg.rest.auth.type=OAUTH2
iceberg.rest.auth.oauth2.credential=<key:secret>
iceberg.catalog.warehouse=<catalog name>
```

## Context
We cannot connect to the Polaris catalog using the `iceberg.rest.auth.oauth2.credential` property.
Alternatively, we can connect to Polaris with `iceberg.rest.auth.oauth2.token`, but without the token refresh mechanism it is a bit cumbersome.

**Comment by ZacBlanco** [comment]
cc @kiersten-stokes
