### ISSUE TITLE
Internal Error in Presto When Querying Elastic search Index with No Mapped Columns

### ISSUE THREAD

**Issue by K-Naga-Vivek** [prestodb/presto#23849]
When querying an Elasticsearch index that has no defined columns, Presto throws an internal error. Elasticsearch allows the creation of indices without any mapped columns, which causes Presto to fail when attempting to retrieve data from such indices. 

## Your Environment

* Presto version used: latest
* Data source and connector used: ElasticSearch
* Debug logs :

> Query 20241017_031656_00002_9vw2m failed: Internal error
> java.util.NoSuchElementException
>         at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:721)
>         at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
>         at com.facebook.presto.elasticsearch.client.ElasticsearchClient.lambda$getIndexMetadata$8(ElasticsearchClient.java:495)
>         at com.facebook.presto.elasticsearch.client.ElasticsearchClient.doRequest(ElasticsearchClient.java:726)
>         at com.facebook.presto.elasticsearch.client.ElasticsearchClient.getIndexMetadata(ElasticsearchClient.java:485)
>         at com.facebook.presto.elasticsearch.ElasticsearchMetadata.makeInternalTableMetadata(ElasticsearchMetadata.java:202)
>         at com.facebook.presto.elasticsearch.ElasticsearchMetadata.makeInternalTableMetadata(ElasticsearchMetadata.java:197)
>         at com.facebook.presto.elasticsearch.ElasticsearchMetadata.getColumnHandles(ElasticsearchMetadata.java:377)
>         at com.facebook.presto.metadata.MetadataManager.getColumnHandles(MetadataManager.java:507)
>         at com.facebook.presto.metadata.MetadataManager$1.getColumnHandles(MetadataManager.java:1383)
>         at com.facebook.presto.util.MetadataUtils.lambda$getTableColumnMetadata$3(MetadataUtils.java:97)
>         at com.facebook.presto.common.RuntimeStats.profileNanos(RuntimeStats.java:136)
>         at com.facebook.presto.util.MetadataUtils.getTableColumnMetadata(MetadataUtils.java:95)
>         at com.facebook.presto.util.MetadataUtils.getTableColumnsMetadata(MetadataUtils.java:54)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1332)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:359)
>         at com.facebook.presto.sql.tree.Table.accept(Table.java:60)
>         at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:373)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2789)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1727)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:359)
>         at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:138)
>         at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:373)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:381)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1166)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:359)
>         at com.facebook.presto.sql.tree.Query.accept(Query.java:105)
>         at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:373)
>         at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:351)
>         at com.facebook.presto.sql.analyzer.Analyzer.analyzeSemantic(Analyzer.java:117)
>         at com.facebook.presto.sql.analyzer.BuiltInQueryAnalyzer.analyze(BuiltInQueryAnalyzer.java:93)
>         at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:210)
>         at com.facebook.presto.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:111)
>         at com.facebook.presto.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:990)
>         at com.facebook.presto.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:170)
>         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
>         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
>         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:834)

## Expected Behavior
Instead of throwing an internal error, Presto should display a meaningful error message when querying.

## Current Behavior

Getting the Internal Error.
<img width="612" alt="image" src="https://github.com/user-attachments/assets/b3b9991a-4ff8-429a-bac4-eb2444ceef59">

The code iterates through the mappings (columns) but lacks an exception handler for cases where an element is not found. Adding appropriate exception handling can address this issue.

## Steps to Reproduce

1. Create an index in Elasticsearch using the command: PUT /test_empty_profile.
2. In Presto, establish a connection to Elasticsearch.
3. Execute a query on the table test_empty_profile using SELECT.
4. Observe that it throws an internal error.

**Comment by K-Naga-Vivek** [comment]
PR merged and working fine now. Closing this issue!
