### ISSUE TITLE
Flaky test: TestHiveCommitHandleOutput.testCommitOutputForPartitions

### ISSUE THREAD

**Issue by pratyakshsharma** [prestodb/presto#24032]
TestHiveCommitHandleOutput.testCommitOutputForPartitions fails with below result - 

```
Error:  Tests run: 3204, Failures: 1, Errors: 0, Skipped: 90, Time elapsed: 3,252.661 s <<< FAILURE! - in TestSuite
Error:  com.facebook.presto.hive.TestHiveCommitHandleOutput.testCommitOutputForPartitions  Time elapsed: 0.047 s  <<< FAILURE!
java.lang.AssertionError: expected [1731482824] but found [1731482825]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1413)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:655)
	at org.testng.Assert.assertEquals(Assert.java:665)
	at com.facebook.presto.hive.TestHiveCommitHandleOutput.testCommitOutputForPartitions(TestHiveCommitHandleOutput.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
Sample run: https://github.com/prestodb/presto/actions/runs/11812511039/job/32907846576?pr=21495

## Your Environment
* Presto version used: Latest master (fails on github CI)
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by hantangwangd** [comment]
Closing this as completed by #25677
