### ISSUE TITLE
Hive service not working in presto

### ISSUE THREAD

**Issue by vikashmalakar275** [prestodb/presto#24180]
## Your Environment

* Presto version used:
* Storage (HDFS/S3/GCS..):
* Data source and connector used:
* Deployment (Cloud or On-prem):
* [Pastebin](https://pastebin.com/) link to the complete debug logs:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by imjalpreet** [comment]
@vikashmalakar275 Can you please add an issue description?

**Comment by vikashmalakar275** [comment]
I have follow the below steps:

working on centos:

docker run -it --name prestotesting -p 8047:8047 -p 8080:8080 -p 8043:8043 -p 31010:31010 -p 10000:10000 -p 9083:9083 --detach prestodb/presto:latest

Login as root:
docker exec -it -u 0 prestotesting /bin/bash

follow all the below process in root user:

yum update
yum install -y openssh
yum install -y openssh-server
yum install -y nano
yum install -y wget
yum install -y openssh-clients
yum install -y sudo
yum install -y hostname


Generate the missing host keys
Run the following command to generate the default SSH host keys:

ssh-keygen -A

This will create the required keys in /etc/ssh/.

start ssh service:
/usr/sbin/sshd -D

install openjdk-8

mkdir /opt/hadoop
mkdir /opt/hive

cd /opt/hadoop
wget https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz
tar -xvf hadoop-3.4.0.tar.gz

cd /opt/hive
wget https://downloads.apache.org/hive/hive-4.0.1/apache-hive-4.0.1-bin.tar.gz
tar -xvf apache-hive-4.0.1-bin.tar.gz

export HADOOP_HOME=/opt/hadoop/hadoop-3.4.0
export JAVA_HOME=/usr/local/openjdk-8
export HIVE_HOME=/opt/hive/apache-hive-4.0.1-bin
export HDFS_NAMENODE_USER=prestouser
export HDFS_DATANODE_USER=prestouser
export HDFS_SECONDARYNAMENODE_USER=prestouser

cd $HIVE_HOME/lib
wget https://repo1.maven.org/maven2/org/apache/tez/tez-dag/0.10.4/tez-dag-0.10.4.jar

chmod -R 777 /opt


Login as prestouser:

follow all the steps below in prestouser

if prestouser is not present, login as root and create this:
adduser prestouser
su -u prestouser

use this:
docker exec -it -u prestouser prestotesting /bin/bash


ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
chmod 0600 ~/.ssh/authorized_keys

export HADOOP_HOME=/opt/hadoop/hadoop-3.4.0
export JAVA_HOME=/usr/local/openjdk-8
export HIVE_HOME=/opt/hive/apache-hive-4.0.1-bin
export HDFS_NAMENODE_USER=prestouser
export HDFS_DATANODE_USER=prestouser
export HDFS_SECONDARYNAMENODE_USER=prestouser

Edit:
$HADOOP_HOME/etc/hadoop/hadoop-env.sh
add
export JAVA_HOME=/usr/local/openjdk-8

edit:
$HIVE_HOME/conf/hive-site.xml
add
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
    <property>
        <name>hive.metastore.sasl.enabled</name>
        <value>false</value>
    </property>
    <property>
        <name>hive.execution.engine</name>
        <value>tez</value>
    </property>
    <property>
        <name>hive.server2.thrift.sasl.qop</name>
        <value>auth-conf</value>
    </property>
    <property>
        <name>hive.metastore.execute.setugi</name>
        <value>false</value>
    </property>
    <property>
        <name>hive.security.metastore.authorization.manager</name>
        <value>org.apache.hadoop.hive.ql.security.authorization.StorageBasedAuthorizationProvider</value>
    </property>
    <property>
        <name>hive.metastore.pre.event.listeners</name>
        <value>org.apache.hadoop.hive.ql.security.authorization.AuthorizationPreEventListener</value>
    </property>
    <property>
        <name>hive.server2.webui.use.pam</name>
        <value>false</value>
    </property>
    <property>
        <name>hive.server2.webui.use.ssl</name>
        <value>false</value>
    </property>
    <property>
        <name>hive.server2.use.SSL</name>
        <value>ssl</value>
    </property>
    <property>
        <name>hive.server2.webui.jetty.response.headers.file</name>
        <value>/opt/hive/conf/headers.xml</value>
    </property>
    <property>
        <name>hive.delegation.token.authentication</name>
        <value>DIGEST</value>
    </property>
    <property>
        <name>hive.users.in.admin.role</name>
        <value>prestouser</value>
    </property>
    <property>
        <name>hive.conf.restricted.list</name>
        <value>hive.security.authenticator.manager,hive.security.authorization.manager,hive.security.metastore.authorization.manager,hive.security.metastore.authenticator.manager,hive.users.in.admin.role,hive.server2.xsrf.filter.enabled,hive.security.authorization.enabled,hive.distcp.privileged.doAs,hive.server2.authentication.ldap.baseDN,hive.server2.authentication.ldap.url,hive.server2.authentication.ldap.Domain,hive.server2.authentication.ldap.groupDNPattern,hive.server2.authentication.ldap.groupFilter,hive.server2.authentication.ldap.userDNPattern,hive.server2.authentication.ldap.userFilter,hive.server2.authentication.ldap.groupMembershipKey,hive.server2.authentication.ldap.userMembershipKey,hive.server2.authentication.ldap.groupClassKey,hive.server2.authentication.ldap.customLDAPQuery,hive.privilege.synchronizer,hive.privilege.synchronizer.interval,hive.spark.client.connect.timeout,hive.spark.client.server.connect.timeout,hive.spark.client.channel.log.level,hive.spark.client.rpc.max.size,hive.spark.client.rpc.threads,hive.spark.client.secret.bits,hive.spark.client.rpc.server.address,hive.spark.client.rpc.server.port,hive.spark.client.rpc.sasl.mechanisms,bonecp.,hive.druid.broker.address.default,hive.druid.coordinator.address.default,hikari.,hadoop.bin.path,yarn.bin.path,spark.home,hive.exec.pre.hooks,hive.exec.post.hooks,hive.exec.failure.hooks,hive.exec.query.redactor.hooks,hive.semantic.analyzer.hook,hive.query.lifetime.hooks,hive.exec.driver.run.hooks,hive.server2.session.hook</value>
    </property>
    <property>
        <name>hive.security.authorization.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.security.authorization.manager</name>
        <value>org.apache.hadoop.hive.ql.security.authorization.plugin.fallback.FallbackHiveAuthorizerFactory</value>
    </property>
    <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:derby:;databaseName=/opt/hive/presto_hive_meta_db;create=true</value>
    </property>
    <property>
        <name>hive.server2.metrics.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.server2.metrics.file.location</name>
        <value>/tmp/hiveserver2_report.json</value>
    </property>
    <property>
        <name>hive.metastore.metrics.enabled</name>
        <value>true</value>
    </property>
    <property>
        <name>hive.metastore.metrics.file.location</name>
        <value>/tmp/hivemetastore_report.json</value>
    </property>
    <property>
        <name>hive.metastore.uris</name>
        <value>thrift://localhost:9083</value>
    </property>
    <property>
        <name>hive.service.metrics.reporter</name>
        <value>JSON_FILE,JMX</value>
    </property>
</configuration>


edit:
$HADOOP_HOME/etc/hadoop/core-site.xml
add
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>




<configuration>
  <property>
    <name>fs.defaultFS</name>
    <value>hdfs://localhost:9000</value>
  </property>
  <property>
    <name>hadoop.proxyuser.prestouser.hosts</name>
    <value>*</value>
    <description>The superuser mapr can connect from any host to impersonate a user</description>
  </property>
  <property>
    <name>hadoop.proxyuser.prestouser.groups</name>
    <value>*</value>
    <description>Allow the superuser mapr to impersonate any member of any group</description>
  </property>
</configuration>

In above core-site.xml file hadoop.proxyuser.drilluser.hosts and hadoop.proxyuser.drilluser.groups follows format hadoop.proxyuser.<adminuser>.groups in my case it is "root"

Setup schema:
$HIVE_HOME/bin/schematool -dbType derby -initSchema

start service:
$HADOOP_HOME/bin/hdfs namenode -format
$HADOOP_HOME/sbin/start-dfs.sh
$HIVE_HOME/bin/hive --service metastore &         (don't run this command again if already running)
$HIVE_HOME/bin/hive --service hiveserver2 &


For Debugging logs are present in /tmp/root/hive.log

$HIVE_HOME/bin/beeline -n prestouser -u jdbc:hive2://localhost:10000/default;transportMode=http;httpPath=cliservice


add hive service:
path = /opt/presto-server/etc/catalog

cretae file = hive.properties & sen.properties

connector.name=hive-hadoop2
hive.metastore.uri=thrift://localhost:9083
hive.allow-drop-table=true
hive.allow-rename-table=true
hive.time-zone=UTC
hive.metastore-cache-ttl=0s



error:

$HIVE_HOME/bin/beeline -n prestouser -u jdbc:hive2://localhost:10000/default;transportMode=http;httpPath=cliservice



2024-12-02 11:15:52 2024-12-02T05:45:52.015Z    INFO    main    com.facebook.presto.server.PrestoServer ======== SERVER STARTED ========
2024-12-02 11:20:04 2024-12-02T05:50:04.205Z    INFO    dispatcher-query-3      com.facebook.presto.event.QueryMonitor  TIMELINE: Query 20241202_055010_00000_57acd :: Transaction:[ad43f26d-1f8a-4517-8a26-3996961e5e17] :: elapsed 1078ms :: planning 361ms :: scheduling 556ms :: running 86ms :: finishing 75ms :: begin 2024-12-02T05:50:02.984Z :: end 2024-12-02T05:50:04.062Z
2024-12-02 11:20:42 2024-12-02T05:50:42.596Z    INFO    dispatcher-query-1      com.facebook.presto.event.QueryMonitor  TIMELINE: Query 20241202_055051_00001_57acd :: Transaction:[0ec33e43-569a-4c72-82cb-bfc8b872f749] :: elapsed 143ms :: planning 29ms :: scheduling 46ms :: running 37ms :: finishing 31ms :: begin 2024-12-02T05:50:42.418Z :: end 2024-12-02T05:50:42.561Z
2024-12-02 11:20:54 2024-12-02T05:50:54.203Z    INFO    dispatcher-query-6      com.facebook.presto.event.QueryMonitor  TIMELINE: Query 20241202_055102_00002_57acd :: Transaction:[b1e8cc2a-a700-4705-91f6-a81ec3a48a31] :: elapsed 316ms :: planning 43ms :: scheduling 145ms :: running 59ms :: finishing 69ms :: begin 2024-12-02T05:50:53.823Z :: end 2024-12-02T05:50:54.139Z
2024-12-02 11:21:25 2024-12-02T05:51:25.726Z    INFO    dispatcher-query-4      com.facebook.presto.event.QueryMonitor  TIMELINE: Query 20241202_055103_00003_57acd :: Transaction:[e0c71252-e8da-4a88-b793-77e0ebb59745] :: elapsed 32387ms :: planning 32345ms :: scheduling 42ms :: running 0ms :: finishing 42ms :: begin 2024-12-02T05:50:54.173Z :: end 2024-12-02T05:51:26.560Z
2024-12-02 11:21:25 2024-12-02T05:51:25.726Z    ERROR   dispatcher-query-4      com.facebook.presto.execution.StateMachine      Error notifying state change listener for finalQueryInfo-20241202_055103_00003_57acd
2024-12-02 11:21:25 java.lang.NullPointerException
2024-12-02 11:21:25     at com.facebook.presto.execution.SqlQueryExecution.lambda$pruneFinishedQueryInfo$7(SqlQueryExecution.java:758)
2024-12-02 11:21:25     at java.base/java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:187)
2024-12-02 11:21:25     at com.facebook.presto.execution.SqlQueryExecution.pruneFinishedQueryInfo(SqlQueryExecution.java:757)
2024-12-02 11:21:25     at com.facebook.presto.execution.QueryTracker.lambda$expireQuery$2(QueryTracker.java:201)
2024-12-02 11:21:25     at java.base/java.util.Optional.ifPresent(Optional.java:183)
2024-12-02 11:21:25     at com.facebook.presto.execution.QueryTracker.expireQuery(QueryTracker.java:200)
2024-12-02 11:21:25     at com.facebook.presto.execution.SqlQueryManager.lambda$createQuery$5(SqlQueryManager.java:311)
2024-12-02 11:21:25     at com.facebook.presto.execution.QueryStateMachine.lambda$addQueryInfoStateChangeListener$18(QueryStateMachine.java:985)
2024-12-02 11:21:25     at com.facebook.presto.execution.StateMachine.fireStateChangedListener(StateMachine.java:229)
2024-12-02 11:21:25     at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:221)
2024-12-02 11:21:25     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-12-02 11:21:25     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-12-02 11:21:25     at java.base/java.lang.Thread.run(Thread.java:829)
2024-12-02 11:21:25 
2024-12-02 11:21:25



My goal is to tun Presto and hive service both in same container to test PrestoODBC Driver.

But i am not able to achive that.


If you have steps to do for the same.

CAn you please share ?
