### ISSUE TITLE
[Spark] Native test TestPrestoSparkNativeAggregations.testAggregations fails in CI

### ISSUE THREAD

**Issue by czentgr** [prestodb/presto#24254]
The CircleCI tests only tests a subset of the Spark native E2E tests.

It only tests these three test classes (56 total tests):
```
TESTCLASSES=TestPrestoSparkExpressionCompiler,TestPrestoSparkNativeJoinQueries,TestPrestoSparkSqlFunctions
```

Meanwhile, when migrating to github actions a larger number of tests is run revealing test issues.

The following set of test classes is run:

```
TESTCLASSES = TestPrestoSparkExpressionCompiler,TestPrestoSparkNativeBitwiseFunctionQueries,TestPrestoSparkNativeAggregations,TestPrestoSparkNativeTpchConnectorQueries,TestPrestoSparkNativeSimpleQueries,TestPrestoSparkSqlFunctions,TestPrestoSparkNativeJoinQueries,TestPrestoSparkNativeWindowQueries,TestPrestoSparkNativeTpchQueries,TestPrestoSparkNativeArrayFunctionQueries,TestPrestoSparkNativeGeneralQueries
```

TestPrestoSparkNativeAggregations.testAggregations fails:
```
2024-12-12T20:02:17.6606016Z [ERROR] Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 347.388 s <<< FAILURE! - in com.facebook.presto.spark.TestPrestoSparkNativeAggregations
2024-12-12T20:02:17.6607466Z [ERROR] com.facebook.presto.spark.TestPrestoSparkNativeAggregations.testAggregations[with_row_wise_exchange_encoding](2)  Time elapsed: 24.913 s  <<< FAILURE!
2024-12-12T20:02:17.6608434Z java.lang.NullPointerException
2024-12-12T20:02:17.6609186Z 	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:59)
2024-12-12T20:02:17.6610417Z 	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:395)
2024-12-12T20:02:17.6611611Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.executeWithStrategies(PrestoSparkQueryRunner.java:548)
2024-12-12T20:02:17.6612597Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:522)
2024-12-12T20:02:17.6613732Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:515)
2024-12-12T20:02:17.6614890Z 	at com.facebook.presto.nativeworker.AbstractTestNativeAggregations.assertQueryResultCount(AbstractTestNativeAggregations.java:401)
2024-12-12T20:02:17.6616263Z 	at com.facebook.presto.nativeworker.AbstractTestNativeAggregations.testAggregations(AbstractTestNativeAggregations.java:108)
2024-12-12T20:02:17.6617529Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-12-12T20:02:17.6618490Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-12-12T20:02:17.6619507Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-12-12T20:02:17.6620304Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-12-12T20:02:17.6621054Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-12-12T20:02:17.6621912Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-12-12T20:02:17.6622653Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-12-12T20:02:17.6623412Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-12-12T20:02:17.6624065Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-12-12T20:02:17.6624690Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-12-12T20:02:17.6625344Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-12-12T20:02:17.6625950Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-12-12T20:02:17.6626543Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-12-12T20:02:17.6627171Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-12-12T20:02:17.6627639Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2024-12-12T20:02:17.6627846Z 
2024-12-12T20:02:18.5127455Z [INFO] Running com.facebook.presto.spark.TestPrestoSparkNativeArrayFunctionQueries
2024-12-12T20:02:18.8742040Z 2024-12-12T14:02:18.793-0600	INFO	TestNG-test=Surefire test-1	com.facebook.airlift.log.Logging	Logging to stderr
2024-12-12T20:02:20.4462581Z WARNING: An illegal reflective access operation has occurred
2024-12-12T20:02:20.4467872Z WARNING: Illegal reflective access by org.apache.hadoop.fs.HadoopExtendedFileSystemCache (file:/root/.m2/repository/com/facebook/presto/presto-hdfs-core/0.291-SNAPSHOT/presto-hdfs-core-0.291-SNAPSHOT.jar) to field java.lang.reflect.Field.modifiers
2024-12-12T20:02:20.4470169Z WARNING: Please consider reporting this to the maintainers of org.apache.hadoop.fs.HadoopExtendedFileSystemCache
2024-12-12T20:02:20.4471412Z WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2024-12-12T20:02:20.4472532Z WARNING: All illegal access operations will be denied in a future release
```

See:
https://github.com/czentgr/presto/actions/runs/12303617334/job/34339523632

## Your Environment
N/A

## Expected Behavior
Test succeeds.

## Current Behavior
Test fails.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by czentgr** [comment]
Good run: https://github.com/prestodb/presto/actions/runs/12307010027/job/34350124877?pr=24236

**Comment by hantangwangd** [comment]
Encounter flakiness of this test method again, but due to a different cause. The error stack is as follows:

```
2025-09-30T19:59:01.9237139Z [ERROR] Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 329.491 s <<< FAILURE! - in com.facebook.presto.spark.TestPrestoSparkNativeAggregations
2025-09-30T19:59:01.9238926Z [ERROR] com.facebook.presto.spark.TestPrestoSparkNativeAggregations.testAggregations[with_columnar_exchange_encoding](1)  Time elapsed: 3.485 s  <<< FAILURE!
2025-09-30T19:59:01.9240519Z java.lang.AssertionError: Execution of 'actual' query failed: SELECT bitwise_and_agg(custkey), bitwise_or_agg(orderkey) FROM orders
2025-09-30T19:59:01.9241409Z 	at org.testng.Assert.fail(Assert.java:98)
2025-09-30T19:59:01.9242095Z 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:213)
2025-09-30T19:59:01.9243003Z 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:141)
2025-09-30T19:59:01.9244329Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:177)
2025-09-30T19:59:01.9245687Z 	at com.facebook.presto.nativeworker.AbstractTestNativeAggregations.testAggregations(AbstractTestNativeAggregations.java:64)
2025-09-30T19:59:01.9246682Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2025-09-30T19:59:01.9247508Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2025-09-30T19:59:01.9248469Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2025-09-30T19:59:01.9249272Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
2025-09-30T19:59:01.9250027Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2025-09-30T19:59:01.9250853Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2025-09-30T19:59:01.9251573Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2025-09-30T19:59:01.9252304Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2025-09-30T19:59:01.9253391Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2025-09-30T19:59:01.9254199Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2025-09-30T19:59:01.9255108Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2025-09-30T19:59:01.9255876Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2025-09-30T19:59:01.9256933Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-09-30T19:59:01.9258225Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2025-09-30T19:59:01.9259084Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2025-09-30T19:59:01.9259849Z Caused by: java.lang.NullPointerException:Cannot invoke "java.util.concurrent.ScheduledFuture.cancel(boolean)" because "this.scheduledFuture" is null
2025-09-30T19:59:01.9261213Z 	at com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.onSuccess(HttpNativeExecutionTaskResultFetcher.java:176)
2025-09-30T19:59:01.9262999Z 	at com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.doGetResults(HttpNativeExecutionTaskResultFetcher.java:143)
2025-09-30T19:59:01.9264297Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2025-09-30T19:59:01.9265502Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2025-09-30T19:59:01.9266648Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2025-09-30T19:59:01.9267751Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-09-30T19:59:01.9268735Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2025-09-30T19:59:01.9269510Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2025-09-30T19:59:01.9270731Z  com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.onSuccess(HttpNativeExecutionTaskResultFetcher.java:176)
2025-09-30T19:59:01.9272799Z  com.facebook.presto.spark.execution.nativeprocess.HttpNativeExecutionTaskResultFetcher.doGetResults(HttpNativeExecutionTaskResultFetcher.java:143)
2025-09-30T19:59:01.9274736Z  java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2025-09-30T19:59:01.9275636Z  java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
2025-09-30T19:59:01.9277020Z  java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
2025-09-30T19:59:01.9283965Z  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2025-09-30T19:59:01.9285165Z  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2025-09-30T19:59:01.9286022Z  java.base/java.lang.Thread.run(Thread.java:840)
2025-09-30T19:59:01.9286419Z
2025-09-30T19:59:01.9287148Z 	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:67)
2025-09-30T19:59:01.9288721Z 	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:397)
2025-09-30T19:59:01.9290402Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.executeWithStrategies(PrestoSparkQueryRunner.java:580)
2025-09-30T19:59:01.9291734Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:554)
2025-09-30T19:59:01.9292897Z 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:210)
2025-09-30T19:59:01.9293860Z 	... 18 more
```

See: https://github.com/prestodb/presto/actions/runs/18138777030/job/51631175202?pr=26178
