### ISSUE TITLE
[Spark] Native test TestPrestoSparkNativeGeneralQueries.testRegexp fails in CI

### ISSUE THREAD

**Issue by czentgr** [prestodb/presto#24253]
The CircleCI tests only tests a subset of the Spark native E2E tests.

It only tests these three test classes (56 total tests):
```
TESTCLASSES=TestPrestoSparkExpressionCompiler,TestPrestoSparkNativeJoinQueries,TestPrestoSparkSqlFunctions
```

Meanwhile, when migrating to github actions a larger number of tests is run revealing test issues.

The following set of test classes is run:

```
TESTCLASSES = TestPrestoSparkExpressionCompiler,TestPrestoSparkNativeBitwiseFunctionQueries,TestPrestoSparkNativeAggregations,TestPrestoSparkNativeTpchConnectorQueries,TestPrestoSparkNativeSimpleQueries,TestPrestoSparkSqlFunctions,TestPrestoSparkNativeJoinQueries,TestPrestoSparkNativeWindowQueries,TestPrestoSparkNativeTpchQueries,TestPrestoSparkNativeArrayFunctionQueries,TestPrestoSparkNativeGeneralQueries
```

TestPrestoSparkNativeGeneralQueries.testRegexp fails:

```
2024-12-12T20:28:26.0938420Z [ERROR] Tests run: 70, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 276.79 s <<< FAILURE! - in com.facebook.presto.spark.TestPrestoSparkNativeGeneralQueries
2024-12-12T20:28:26.0940125Z [ERROR] com.facebook.presto.spark.TestPrestoSparkNativeGeneralQueries.testRegexp  Time elapsed: 0.173 s  <<< FAILURE!
2024-12-12T20:28:26.0942182Z java.lang.AssertionError: Execution of 'actual' query failed: SELECT regexp_extract(key, '[^\.]+'), regexp_extract(key, '([^\.]+)\.([^\.]+)', 1), regexp_extract(key, '([^\.]+)\.([^\.]+)', 2) FROM (SELECT concat(name, '.', cast(regionkey AS VARCHAR), '.', cast(nationkey AS VARCHAR)) AS key FROM nation)
2024-12-12T20:28:26.0943706Z 	at org.testng.Assert.fail(Assert.java:98)
2024-12-12T20:28:26.0944461Z 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:178)
2024-12-12T20:28:26.0945483Z 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
2024-12-12T20:28:26.0946658Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:169)
2024-12-12T20:28:26.0948023Z 	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:164)
2024-12-12T20:28:26.0949590Z 	at com.facebook.presto.nativeworker.AbstractTestNativeGeneralQueries.testRegexp(AbstractTestNativeGeneralQueries.java:605)
2024-12-12T20:28:26.0950959Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-12-12T20:28:26.0952109Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-12-12T20:28:26.0953470Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-12-12T20:28:26.0954515Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-12-12T20:28:26.0955519Z 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
2024-12-12T20:28:26.0956662Z 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
2024-12-12T20:28:26.0957655Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
2024-12-12T20:28:26.0958671Z 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
2024-12-12T20:28:26.0959744Z 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
2024-12-12T20:28:26.0960855Z 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
2024-12-12T20:28:26.0961999Z 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
2024-12-12T20:28:26.0963082Z 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
2024-12-12T20:28:26.0964144Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-12-12T20:28:26.0965251Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-12-12T20:28:26.0966066Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2024-12-12T20:28:26.0966603Z Caused by: java.lang.NullPointerException
2024-12-12T20:28:26.0967845Z 	at com.facebook.presto.spark.util.PrestoSparkFailureUtils.toPrestoSparkFailure(PrestoSparkFailureUtils.java:59)
2024-12-12T20:28:26.0969652Z 	at com.facebook.presto.spark.execution.AbstractPrestoSparkQueryExecution.execute(AbstractPrestoSparkQueryExecution.java:395)
2024-12-12T20:28:26.0971373Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.executeWithStrategies(PrestoSparkQueryRunner.java:548)
2024-12-12T20:28:26.0972800Z 	at com.facebook.presto.spark.PrestoSparkQueryRunner.execute(PrestoSparkQueryRunner.java:522)
2024-12-12T20:28:26.0973898Z 	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:175)
2024-12-12T20:28:26.0974603Z 	... 19 more
2024-12-12T20:28:26.0974769Z 
2024-12-12T20:28:26.5221015Z [INFO] 
2024-12-12T20:28:26.5221397Z [INFO] Results:
2024-12-12T20:28:26.5221778Z [INFO] 
```

See:
https://github.com/czentgr/presto/actions/runs/12303617334/job/34339523632

## Your Environment
N/A

## Expected Behavior
Test succeeds.

## Current Behavior
Test fails.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by majetideepak** [comment]
@amitkdutta do you know who can help with this?

**Comment by czentgr** [comment]
Good run: https://github.com/prestodb/presto/actions/runs/12307010027/job/34350124877?pr=24236
