### ISSUE TITLE
Transient Null Pointer Exception

### ISSUE THREAD

**Issue by Cidan** [prestodb/presto#2904]
Every once in a while, we'll get the following error when running a query on presto:

```
java.lang.NullPointerException
	at org.apache.hadoop.hive.serde2.lazy.LazyStruct.parse(LazyStruct.java:125)
	at org.apache.hadoop.hive.serde2.lazy.LazyStruct.getField(LazyStruct.java:190)
	at org.apache.hadoop.hive.serde2.lazy.objectinspector.LazySimpleStructObjectInspector.getStructFieldData(LazySimpleStructObjectInspector.java:193)
	at com.facebook.presto.hive.GenericHiveRecordCursor.parseStringColumn(GenericHiveRecordCursor.java:399)
	at com.facebook.presto.hive.GenericHiveRecordCursor.parseColumn(GenericHiveRecordCursor.java:448)
	at com.facebook.presto.hive.GenericHiveRecordCursor.isNull(GenericHiveRecordCursor.java:430)
	at com_facebook_presto_$gen_CursorProcessor_45.filter(Unknown Source)
	at com_facebook_presto_$gen_CursorProcessor_45.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:183)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:343)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:287)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Re-running the query normally works. I'm not sure what else to include in this issue, so please let me know what else you need from me.

Thanks!

**Comment by cberner** [comment]
That looks like a bug in the Hive file format you're using. What file format is this data?
