### ISSUE TITLE
Query  failed: Too large ..... expected elements with load factor 0.75

### ISSUE THREAD

**Issue by arthurhsk** [prestodb/presto#3005]
Hi,

Please help!! I have a 3-node cluster, my version is 0.100, I got the following issue:

Query 20150602_051618_00003_z8uug, FAILED, 3 nodes
Splits: 2,543 total, 2,007 done (78.92%)
9:08 [5.76B rows, 281GB] [10.5M rows/s, 526MB/s]
Query 20150602_051618_00003_z8uug failed: Too large (960017389 expected elements with load factor 0.75)

Please advise how to resolve it.  

Reagrds

**Comment by cberner** [comment]
Could you include the query you ran, and also the full stacktrace? (you can get the stacktrace by running the CLI with the --debug flag)

**Comment by arthurhsk** [comment]
my query: select l_shipmode, o_shippriority, sum(l_quantity * l_extendedprice) as amount from orders, lineitem where o_orderkey = l_orderkey group by l_shipmode, o_shippriority;

Query 20150602_221759_00008_3rm95 failed: Too large (960017389 expected elements with load factor 0.75)
java.lang.IllegalArgumentException: Too large (960017389 expected elements with load factor 0.75)
	at it.unimi.dsi.fastutil.HashCommon.arraySize(HashCommon.java:160)
	at com.facebook.presto.operator.InMemoryJoinHash.<init>(InMemoryJoinHash.java:57)
	at com.facebook.presto.operator.PagesIndex.createLookupSource(PagesIndex.java:285)
	at com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:138)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:358)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cberner** [comment]
Ah, I believe that's because JOINs are limited to 2^31 elements per task. As a workaround, you could try enabling "node-scheduler.multiple-tasks-per-node-enabled" and then increase "query.initial-hash-partitions"

**Comment by arthurhsk** [comment]
Hi,

I added the following to config properties:
node-scheduler.multiple-tasks-per-node-enabled=true
query.initial-hash-partitions=80

Still got the same error, please advise if above are two are correct?

Log:
Query 20150603_064623_00003_4z6ku failed: Too large (960017389 expected elements with load factor 0.75)
java.lang.IllegalArgumentException: Too large (960017389 expected elements with load factor 0.75)
	at it.unimi.dsi.fastutil.HashCommon.arraySize(HashCommon.java:160)
	at com.facebook.presto.operator.InMemoryJoinHash.<init>(InMemoryJoinHash.java:57)
	at com.facebook.presto.operator.PagesIndex.createLookupSource(PagesIndex.java:285)
	at com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:138)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:358)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:283)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:563)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cberner** [comment]
What's the cardinality of l_shipmode and l_shippriority?

**Comment by shaiktas** [comment]
Hi All, how splits are allocated in trino/presto? is it per table or per query? any config to control number of splits?
