### ISSUE TITLE
About the settings

### ISSUE THREAD

**Issue by fengshihua** [prestodb/presto#3110]
hi,

I just found that the parameter "node.environment" of  node.properties file. The value can't be capital letter. I'm not sure whether it is a bug.

FYI.
node.environment=ABC
The server.log as below.
"2015-06-15T17:42:37.385-0700    ERROR   main    com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:

1) Error: Constraint violation with property prefix '': environment is malformed (for class io.airlift.node.NodeConfig)
  at io.airlift.configuration.ConfigBinder.bindConfig(ConfigBinder.java:78)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error: Constraint violation with property prefix '': environment is malformed (for class io.airlift.node.NodeConfig)
  at io.airlift.configuration.ConfigBinder.bindConfig(ConfigBinder.java:78)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:448)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:103)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:59)
"

**Comment by cawallin** [comment]
I'm not sure the reasoning behind it, but it is intentional that the environment be only lower case. See https://github.com/airlift/airlift/blob/master/node/src/main/java/io/airlift/node/NodeConfig.java, and https://github.com/airlift/airlift/blob/master/node/src/test/java/io/airlift/node/TestNodeConfig.java for a test that verifies that the environment is not upper case.

@electrum, can you confirm? If so, I can add a note to the docs that the environment must be lower case.

**Comment by nsabharwal** [comment]
I had the same issue and in my case, I forgot to put the node.properties in the worker node.

**Comment by losipiuk** [comment]
As @cawallin pointed out this is intentional. Closing.
