### ISSUE TITLE
Bad error message when casting to parametric type without type parameters

### ISSUE THREAD

**Issue by martint** [prestodb/presto#3171]
```
SELECT CAST(NULL AS MAP);
```

Fails with:

```
Query 20150625_162057_09252_bhbmd failed: Expected two types
java.lang.IllegalArgumentException: Expected two types
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.type.MapParametricType.createType(MapParametricType.java:41)
	at com.facebook.presto.type.MapParametricType.createType(MapParametricType.java:23)
	at com.facebook.presto.type.TypeRegistry.instantiateParametricType(TypeRegistry.java:136)
	at com.facebook.presto.type.TypeRegistry.getType(TypeRegistry.java:110)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:726)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:206)
	at com.facebook.presto.sql.tree.Cast.accept(Cast.java:61)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:179)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1018)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeExpression(TupleAnalyzer.java:1106)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeSelect(TupleAnalyzer.java:913)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:353)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:135)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:520)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:115)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:252)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:238)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:202)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$130(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$237/901458406.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cberner** [comment]
Oh sorry, @zhenxiao didn't see that you were already working on this one. I think the right way to fix this is https://github.com/facebook/presto/pull/4320

**Comment by zhenxiao** [comment]
@cberner sure. I will close the PR.
