### ISSUE TITLE
Can't concat an Array with an empty Array.

### ISSUE THREAD

**Issue by yaoxin226** [prestodb/presto#3357]
Concat an Array with an empty Array will failed because we can't cast the empty Array to the type of the non-empty array.
```
presto:tiny> select ARRAY[1] || ARRAY[];
Query 20150727_073421_00004_25tug failed: Can not cast array<unknown> to array<bigint>
com.facebook.presto.spi.PrestoException: Can not cast array<unknown> to array<bigint>
	at com.facebook.presto.operator.scalar.ArrayToArrayCast.specialize(ArrayToArrayCast.java:81)
	at com.facebook.presto.metadata.FunctionRegistry$1.load(FunctionRegistry.java:224)
	at com.facebook.presto.metadata.FunctionRegistry$1.load(FunctionRegistry.java:219)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.presto.metadata.FunctionRegistry.getExactFunction(FunctionRegistry.java:512)
	at com.facebook.presto.metadata.FunctionRegistry.getCoercion(FunctionRegistry.java:552)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:750)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:211)
	at com.facebook.presto.sql.tree.Cast.accept(Cast.java:61)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:230)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:681)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:211)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:184)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1010)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:982)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:944)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:934)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:131)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter$$Lambda$251/554780878.apply(Unknown Source)
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:1812)
	at com.google.common.collect.Maps$10.getValue(Maps.java:1857)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:292)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:92)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:99)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:110)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:99)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:110)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:99)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:110)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:99)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$41(PlanRewriter.java:73)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext$$Lambda$247/34398165.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:74)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:38)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:22)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:79)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:27)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions.optimize(SimplifyExpressions.java:67)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:93)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:258)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:237)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:201)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$61(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$236/1947247162.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by komamitsu** [comment]
This issue seems to have the same cause as https://github.com/facebook/presto/issues/2852

**Comment by cberner** [comment]
Fixed
