### ISSUE TITLE
ClusterMemoryManager makes requests while server is still starting

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3381]
```
2015-07-30T13:57:38.073-0700    WARN    http-client-shared-84   com.facebook.presto.memory.RemoteNodeMemory Error fetching memory info from http://127.0.0.1:8080/v1/memory
io.airlift.http.client.RuntimeIOException: Server refused connection: http://127.0.0.1:8080/v1/memory
    at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:17)
    at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:55)
    at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:35)
    at io.airlift.http.client.jetty.JettyHttpClient$JettyResponseFuture.failed(JettyHttpClient.java:793)
    at io.airlift.http.client.jetty.JettyHttpClient$BufferingResponseListener.onComplete(JettyHttpClient.java:1027)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
    at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:271)
    at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:242)
    at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
    at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:704)
    at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:252)
    at org.eclipse.jetty.client.PoolingHttpDestination$1.run(PoolingHttpDestination.java:68)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:340)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:675)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:644)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:611)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:549)
    at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
    ... 3 more
```

**Comment by cberner** [comment]
This is a bug in airlift: https://github.com/airlift/airlift/issues/349
