### ISSUE TITLE
Discovery server could not start while running Presto server in IDEA

### ISSUE THREAD

**Issue by ricdong** [prestodb/presto#3428]
I follow the README building steps and load the project into IDEA,  while running the main class PrestoServer with run configurations, the error met:

with the config.properties as below by default:

> node.id=ffffffff-ffff-ffff-ffff-ffffffffffff
> node.environment=test
> http-server.http.port=8080
> 
> discovery-server.enabled=true
> discovery.uri=http://localhost:8080
> 
> exchange.http-client.max-connections=1000
> exchange.http-client.max-connections-per-server=1000
> exchange.http-client.connect-timeout=1m
> exchange.http-client.idle-timeout=1m
> 
> scheduler.http-client.max-connections=1000
> scheduler.http-client.max-connections-per-server=1000
> scheduler.http-client.connect-timeout=1m
> scheduler.http-client.idle-timeout=1m
> 
> query.client.timeout=5m
> query.max-age=30m
> 
> plugin.bundles=\
>   ../presto-jmx/pom.xml,\
>   ../presto-raptor/pom.xml,\
>   ../presto-hive-cdh4/pom.xml,\
>   ../presto-example-http/pom.xml,\
>   ../presto-kafka/pom.xml, \
>   ../presto-tpch/pom.xml
> 
> presto.version=testversion
> experimental-syntax-enabled=true
> distributed-joins-enabled=true

---

```
2015-08-08T13:02:56.717+0800    ERROR   Discovery-0 io.airlift.discovery.client.CachingServiceSelector  Cannot connect to discovery server for refresh (collector/general): Lookup of collector failed for http://localhost:8080/v1/service/collector/general
2015-08-08T13:02:56.759+0800    ERROR   Discovery-4 io.airlift.discovery.client.CachingServiceSelector  Cannot connect to discovery server for refresh (presto/general): Lookup of presto failed for http://localhost:8080/v1/service/presto/general
2015-08-08T13:02:57.893+0800    INFO    main    org.eclipse.jetty.server.Server jetty-9.2.11.v20150529
2015-08-08T13:02:57.904+0800    WARN    main    org.eclipse.jetty.server.handler.AbstractHandler    No Server set for org.eclipse.jetty.server.handler.ErrorHandler@4c361f63
2015-08-08T13:02:58.650+0800    WARN    http-client-shared-68   com.facebook.presto.memory.RemoteNodeMemory Error fetching memory info from http://192.168.1.100:8080/v1/memory
io.airlift.http.client.RuntimeIOException: Server refused connection: http://192.168.1.100:8080/v1/memory
    at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:17)
    at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:55)
    at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:35)
    at io.airlift.http.client.jetty.JettyHttpClient$JettyResponseFuture.failed(JettyHttpClient.java:793)
    at io.airlift.http.client.jetty.JettyHttpClient$BufferingResponseListener.onComplete(JettyHttpClient.java:1027)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
    at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
    at org.eclipse.jetty.client.HttpExchange.notifyFailureComplete(HttpExchange.java:271)
    at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:242)
    at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
    at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:704)
    at org.eclipse.jetty.client.HttpDestination.abort(HttpDestination.java:252)
    at org.eclipse.jetty.client.PoolingHttpDestination$1.run(PoolingHttpDestination.java:68)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.eclipse.jetty.io.SelectorManager.finishConnect(SelectorManager.java:340)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processConnect(SelectorManager.java:675)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.processKey(SelectorManager.java:644)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:611)
    at org.eclipse.jetty.io.SelectorManager$ManagedSelector.run(SelectorManager.java:549)
    at org.eclipse.jetty.util.thread.NonBlockingThread.run(NonBlockingThread.java:52)
    ... 3 more
```

**Comment by ricdong** [comment]
but it can load plugins normally and execute the SQL query normally even though the exception throwed

**Comment by RobinUS2** [comment]
It seems to me that this is #3381 looking at the "Error fetching memory" which makes this issue a duplicate.
