### ISSUE TITLE
ORC Reader Out of range Exception

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#3457]
```
presto> select * from presto_queries where error_code_name = 'PAGE_TRANSPORT_TIMEOUT'\G

Query 20150815_005946_01110_3a7m7 failed: Out of range: 2551255893
java.lang.IllegalArgumentException: Out of range: 2551255893
    at com.google.common.primitives.Ints.checkedCast(Ints.java:91)
    at com.facebook.presto.orc.reader.SliceDirectStreamReader.readBatch(SliceDirectStreamReader.java:108)
    at com.facebook.presto.orc.reader.SliceStreamReader.readBatch(SliceStreamReader.java:51)
    at com.facebook.presto.orc.OrcRecordReader.readVector(OrcRecordReader.java:279)
    at com.facebook.presto.hive.orc.OrcPageSource$LazySliceBlockLoader.load(OrcPageSource.java:473)
    at com.facebook.presto.hive.orc.OrcPageSource$LazySliceBlockLoader.load(OrcPageSource.java:453)
    at com.facebook.presto.spi.block.LazySliceArrayBlock.assureLoaded(LazySliceArrayBlock.java:180)
    at com.facebook.presto.spi.block.LazySliceArrayBlock.isEntryNull(LazySliceArrayBlock.java:96)
    at com.facebook.presto.spi.block.AbstractVariableWidthBlock.isNull(AbstractVariableWidthBlock.java:158)
    at com_facebook_presto_$gen_PageProcessor_44833.project_29(Unknown Source)
    at com_facebook_presto_$gen_PageProcessor_44833.process(Unknown Source)
    at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:232)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by electrum** [comment]
This seems to be a corrupt file. Rather than using `Ints.checkedCast`, it should check for out of range and throw `OrcCorruptionException`.

**Comment by electrum** [comment]
We should check for other places in the ORC reader that throw the wrong exception.
