### ISSUE TITLE
Filtering for information_schema fails with uppercase

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#3507]
```
select * from system.information_schema.columns where table_schema = 'FOO';
select * from system.information_schema.columns where table_schema = 'runtime' and table_name = 'FOO';

java.lang.IllegalArgumentException: schemaName is not lowercase
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.metadata.MetadataUtil.checkLowerCase(MetadataUtil.java:94)
	at com.facebook.presto.metadata.MetadataUtil.checkLowerCase(MetadataUtil.java:86)
	at com.facebook.presto.metadata.MetadataUtil.checkSchemaName(MetadataUtil.java:58)
	at com.facebook.presto.metadata.MetadataUtil.checkTableName(MetadataUtil.java:40)
	at com.facebook.presto.metadata.QualifiedTablePrefix.<init>(QualifiedTablePrefix.java:57)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.extractQualifiedTablePrefix(InformationSchemaPageSourceProvider.java:324)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getColumnsList(InformationSchemaPageSourceProvider.java:182)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:156)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:132)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:126)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:87)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.createSourceIfNecessary(ScanFilterAndProjectOperator.java:254)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.isFinished(ScanFilterAndProjectOperator.java:169)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yuananf** [comment]
fixed by #3611
