### ISSUE TITLE
Failure when window function is used in `having` gives unclear error message

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#3713]
I'm not sure if this is legal SQL. But either way, the failure message is not proper.

```
presto:tiny> select x, rank() over (order by x) from (values 1, 2, 3, 4, 5, 6, 10, 7) t(x) having rank() over (order by x) <= 3;
Query 20151006_171254_25508_9dwfy failed: not a scalar function or operator
java.lang.IllegalStateException: not a scalar function or operator
    at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
    at com.facebook.presto.metadata.FunctionInfo.getMethodHandle(FunctionInfo.java:202)
    at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:785)
    at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:606)
    at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:77)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:234)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:133)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:100)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$115(PlanRewriter.java:74)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
    at com.facebook.presto.sql.planner.plan.PlanVisitor.visitWindow(PlanVisitor.java:105)
    at com.facebook.presto.sql.planner.plan.WindowNode.accept(WindowNode.java:171)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$115(PlanRewriter.java:74)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
    at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:28)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions.optimize(SimplifyExpressions.java:67)
    at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:97)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:266)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:245)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:209)
    at com.facebook.presto.execution.QueuedExecution.lambda$start$117(QueuedExecution.java:68)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by electrum** [comment]
This is not valid SQL, since window functions are evaluated on the result of HAVING.

**Comment by maciejgrzybek** [comment]
This is not correct to use WF in `HAVING` clause.
Given that, I'm renaming the issue to be more specific what's the subject.
Also, I mark it as `beginner-task` because it should be relatively easy to discover the problem within the WF context and raise more clear exception / message.

**Comment by findepi** [comment]
Today the error is quite explicit:
```
presto> select x, rank() over (order by x) from (values 1, 2, 3, 4, 5, 6, 10, 7) t(x) having rank() over (order by x) <= 3;
Query 20181029_192958_00001_dr5u8 failed: line 1:86: HAVING clause cannot contain window functions
```
