### ISSUE TITLE
Create Table As fails with nested columns

### ISSUE THREAD

**Issue by kadaan** [prestodb/presto#3781]
Running a query like:

```
CREATE TABLE test AS
SELECT m.d1, m.d2, m.d3 FROM default.table LIMIT 10000;
```

results in the following error:

```
Column name not specified at position 1
com.facebook.presto.sql.analyzer.SemanticException: Column name not specified at position 1
at com.facebook.presto.sql.analyzer.StatementAnalyzer.validateColumnNames(StatementAnalyzer.java:441)
at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitCreateTableAsSelect(StatementAnalyzer.java:415)
at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitCreateTableAsSelect(StatementAnalyzer.java:114)
at com.facebook.presto.sql.tree.CreateTableAsSelect.accept(CreateTableAsSelect.java:46)
at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:241)
at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:227)
at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:188)
at com.facebook.presto.execution.QueuedExecution.lambda$start$111(QueuedExecution.java:68)
at com.facebook.presto.execution.QueuedExecution$$Lambda$194/1752238939.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by cberner** [comment]
This is a feature actually. You need to specify a column name for your columns. For example: 

```
CREATE TABLE test AS
SELECT m.d1 as d1, m.d2 as d2, m.d3 as d3 FROM default.table LIMIT 10000;
``

**Comment by electrum** [comment]
The intention is to require column names for un-named projections like `SELECT 123` or `SELECT x + 1` where we don't actually have a name and would have to make one up. But for qualified column names, we actually do have a name. Also, these queries are equivalent:
```sql
SELECT a.b.t.x FROM a.b.t;
SELECT t.x FROM t;
SELECT x FROM t;
```
If we wanted to require explicitly naming every column, we should require it for unqualified names as well:
```sql
SELECT x AS x FROM t;
SELECT t.x AS x FROM t;
```

**Comment by martint** [comment]
Although the issue reported above is slightly different. The column in the underlying table is named `m`, but it's a structural type, so it has fields `d1`, `d2` and `d3`. Today, we infer output column names based on the column name in the source relation.

**Comment by electrum** [comment]
Oh, I didn't see it is a structural type. Though  I think the same reasoning applies. No need to re-declare all the names since we already have valid names (no need to generate any).

**Comment by martint** [comment]
I agree. In fact, a table is no more than a collection of values of a structural type matching the schema of the table, so they should behave identically.
