### ISSUE TITLE
using hive parquet table with date partition

### ISSUE THREAD

**Issue by Liorba** [prestodb/presto#3786]
Hey I'm using AWS EMR distribution of presto  (version 0.119) and when trying to read data from a hive parquet table which has date type partition I'm getting an error (see below), when advised with aws support they said I need to change the partition filed type to string instead of date.

does presto support date fields partitions?

Thanks
Lior.

the HIVE create table statement:

CREATE external table  DRIVERS_LOCATIONS(
              `event_at_utc` timestamp,
              `drivergk` BIGINT,
              `latitude` decimal(9,6),
              `longitude` decimal(9,6),
              `status` string,
              `ordergk` BIGINT,
              `gps_at` timestamp,
              `bearing` int
             )
        PARTITIONED BY (country string, gps_date date)
        STORED AS parquet
        LOCATION 's3://some-place/DRIVERS_LOCATIONS'

The error I'm getting:

presto:dev> select * from drivers_locations_test limit 10;

Query 20151008_113848_00032_wjqrm, FAILED, 10 nodes
http://ip-10-100-144-234.eu-west-1.compute.internal:8889/v1/query/20151008_113848_00032_wjqrm?pretty
Splits: 20 total, 4 done (20.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 33% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20151008_113848_00032_wjqrm failed: Can not read Parquet column: [HiveColumnHandle{clientId=hive, name=gps_date, ordinalPosition=9, hiveType=date, hiveColumnIndex=-1, partitionKey=true}]
java.lang.IllegalArgumentException: Can not read Parquet column: [HiveColumnHandle{clientId=hive, name=gps_date, ordinalPosition=9, hiveType=date, hiveColumnIndex=-1, partitionKey=true}]
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:88)
	at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:128)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:106)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:43)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
	at com.facebook.presto.operator.TableScanOperator.createSourceIfNecessary(TableScanOperator.java:258)
	at com.facebook.presto.operator.TableScanOperator.isFinished(TableScanOperator.java:206)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zhenxiao** [comment]
Currently does not support date partitions, I've just sent a PR to fix it:
https://github.com/facebook/presto/pull/3791
Let's wait for the review, and you could ask EMR to backport this PR.

**Comment by haozhun** [comment]
Fixed by #3791
