### ISSUE TITLE
exception of page_transport_timeout

### ISSUE THREAD

**Issue by clarke0922** [prestodb/presto#3876]
how to pass the exception of page_transport_timeout.
PAGE_TRANSPORT_TIMEOUT:Encountered too many errors talking to a worker node. The node may
have crashed or be under load.

The scene is  two hard SQL, one is  two tables(1MM left join 6MM：results 70MM) have left join, one is count number（6MM）.

**Comment by clarke0922** [comment]
is there any parameter can avoid this problem？  
by the way , 4 node ,one is set to coodinator ,three is set to work nodes

**Comment by spragues-trulia** [comment]
hi, 
i'm going to climb around this ticket too.... :)  running version 0.123 .  i'm getting the same error ultimately returned back to the client.  I can't duplicate using TPCH data unfortunately but it is a pretty big query with a join.

i dug around in the server logs and found this: 

{code}
java.lang.NullPointerException: maxSize is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.facebook.presto.execution.SqlTaskManager.getTaskResults(SqlTaskManager.java:272)
	at com.facebook.presto.server.TaskResource.getResults(TaskResource.java:201)
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:136)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
{code}

lemme know if there's anything else i can supply.

thanks,
Stephen

**Comment by dain** [comment]
Assuming your machines didn't actually crash, there are two main causes of this long GC pauses and network saturation.  Both of these can sometimes be fixed by tweaking the query.  Use `explain (type distributed)` to see the join order and exchanges, and make sure you are building hash tables out of the smaller table.

The first is you are getting very long full GCs, you can see this by enabling GC logging on the workers.  If you are getting log GCs, sometimes you can tweak the JVM settings to help things, but if you need more memory then you have, you will need to add more memory or machines.  

When it comes to network saturation, there isn't much that can be done.  I suggest you run on 10gig networks.

**Comment by dain** [comment]
@spragues-trulia I've never seen that error before.  It implies that the client did not send a well formed request (it was missing a required header).  If true, you should be seeing this everywhere.

**Comment by spragues-trulia** [comment]
thanks @dain .    i think i'm going to try to enable GC logging as well as the error returned to my client is the same (page_transport_timeout). however, digging deeper into the server logs i was able to find a uri and follow it - and its that that reported the NPE on maxsize is null.  maybe that's just a symptom though but figured it be worth bringing to your attention.

Sun Nov  1 11:05:21 2015 - error executing query. Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://172.19.76.117:8080/v1/task/20151101_190201_00001_g95t8.2.3/results/20151101_190201_00001_g95t8.1.7/2874 - requests failed for 60.07s)

clicking on that uri yields:

java.lang.NullPointerException: maxSize is null at java.util.Objects.requireNonNull(Objects.java:228) at com.facebook.presto.execution.SqlTaskManager.getTaskResults(SqlTaskManager.java:272) at com.facebook.presto.server.TaskResource.getResults(TaskResource.java:201) at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:483)
<snip>

the other interesting thing is v0.112 does not exhibit this error while v0.123 (and 0.121 do) which leads me to believe something in the presto server code is at play here and not GC or environment.  Also, given clark0922 has something very, very similar i'm guessing there's something going on inside the presto code.  maybe between the two of us we can help narrow it down.

**Comment by cberner** [comment]
By follow, do you mean load that URI in your browser? That probably won't work, and would explain the NPE, because your browser won't include the necessary HTTP header

**Comment by spragues-trulia** [comment]
ahhhh.... that is correct.  okay, that explains that!   so back to the original "page_transport_timeout" investigation.  i'll work at logging GC and see what that shows.

out of curiosity would there be any timeout/heartbeat config setting on the presto side to control the server's behavior under these circumstances?  or is it entirely up to the JVM?  Judging from Dain's response above seems like the latter, eh?

**Comment by nazgul33** [comment]
Same error here, with PAGE_TRANSPORT_TIMEOUT error on worker node.
by the time problematic SQL running, here's the gc log (g1gc)

app/presto/var/log>$ grep pause presto-gc.log 
2.132: [GC pause (Metadata GC Threshold) (young) (initial-mark), 0.0322798 secs]
3.682: [GC pause (Metadata GC Threshold) (young) (initial-mark), 0.0285097 secs]
79.510: [GC pause (Metadata GC Threshold) (young) (initial-mark), 0.0460919 secs]
94.349: [GC pause (G1 Evacuation Pause) (young), 0.0465602 secs]
95.014: [GC pause (G1 Evacuation Pause) (young), 0.0474994 secs]
95.702: [GC pause (G1 Evacuation Pause) (young), 0.1224174 secs]
96.204: [GC pause (G1 Evacuation Pause) (young), 0.0275629 secs]
96.740: [GC pause (G1 Evacuation Pause) (young), 0.0319387 secs]
97.126: [GC pause (G1 Evacuation Pause) (young), 0.0362247 secs]
97.584: [GC pause (G1 Evacuation Pause) (young), 0.0285603 secs]
98.189: [GC pause (G1 Evacuation Pause) (young), 0.0380048 secs]
98.781: [GC pause (G1 Evacuation Pause) (young), 0.0169775 secs]
99.428: [GC pause (G1 Evacuation Pause) (young), 0.0268498 secs]
100.230: [GC pause (G1 Evacuation Pause) (young), 0.0233163 secs]
101.486: [GC pause (G1 Evacuation Pause) (young), 0.0218672 secs]
1078.338: [GC pause (G1 Evacuation Pause) (young), 0.0495063 secs]

it seems that long GC is not the issue here.
I'm running 0.126 on 1 coordinator, 74 worker,
each node with 192MB ram, 28core w/ hyperthreading.

I tried with CMS GC before trying G1GC, global pause was long enough to think that GC is causing this.
But, switching to G1GC shows that this issue might not be closely related to GC problem.

here's my configuration
--- config.properties
query.max-memory=740GB
query.max-memory-per-node=15GB

--- jvm.config
-Xmx40G
-Xms40G
-XX:+UseNUMA
-XX:+UseG1GC
-XX:+AggressiveOpts
-XX:ReservedCodeCacheSize=512M
-XX:PermSize=1024M
-XX:MaxPermSize=1024M
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:+PrintGCDetails
-XX:+PrintGCTimeStamps
-verbose:gc
-Xloggc:/app/presto/var/log/presto-gc.log

problematic query was a
"union all" of many following subqueries. (15 union or so)

select TA.c, TB. b, count(distinct TA.a) from
(select a, b, count(distinct c) from bigtable where part_date between blahblah group b) TA
left outer join
(select a, b, from smalltable where blahblah) TB on (TA.a = TB.a)
group by TA.c, TB.b

**Comment by spragues-trulia** [comment]
thanks for this. good to get another data point on this seemingly mysterious error.   Anything in your traceback that looks like a smoking gun? did this query work in a previous version of presto?

**Comment by nazgul33** [comment]
I am trying to evaluate presto, comparing performance with impala.
I just tried version 0.125 and 0.126, the query ran just two time successfully w/ 0.125, CMS gc.
I'll try with 0.125 again. and share the results.
thanks.

**Comment by nazgul33** [comment]
both 0.123 and 0.126 sometimes produce this error in my case.
as the error message says, this error is transient.

today i was able to reproduce this error again. ( 0.126, g1gc, hash join )
servers were under modest load (5~10%), before issuing a problematic presto query.

coordinator log is flooded with following two exceptions, with many different task ids

ContinuousTaskInfoFetcher-20151126_065330_00016_h9z52.52.3-3310 com.facebook.presto.server.HttpRemoteTask       Error getting info for task 20151126_065330_00016_h9z52.52.3: java.util.concurrent.TimeoutException: http://10.10.34.189:12303/v1/task/20151126_065330_00016_h9z52.52.3

UpdateResponseHandler-20151126_065330_00016_h9z52.52.3-3310     com.facebook.presto.server.HttpRemoteTask       Error updating task 20151126_065330_00016_h9z52.52.3: java.util.concurrent.TimeoutException: http://10.10.34.189:12303/v1/task/20151126_065330_00016_h9z52.52.3

worker 10.10.34.189's log file is flooded with following exception, just showing that the TCP connection was dropped.

http-worker-507 org.glassfish.jersey.server.ServerRuntime$Responder     An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:91)


by that time, cpu usage was just 10~20 percent.
network usage was about 100MB/s (10G NIC).

so, here's my interpretation of this situation.
1. the task info api on worker node is not responding within 2.5 seconds -> time out exception
2. coordinator cancels http request.
3. worker node's pending http request handler is canceled.
and this goes on for 60 seconds for one or more task id.
boom, a query failed to run with com.facebook.presto.operator.PageTransportTimeoutException

and here's the question.
why task info api is not responding within 2.5 second?
- (maybe a synchronization mechanism is blocking the api to read and send the relevant info?)
and why this can go on for 1 full minute?
- (maybe the task is running over 1 minute)
I'm just a new guy trying to evaluate presto, haven't read any source code yet.
so please forgive my wild guess :smile: 


again, g1gc was not the issue this time.

1.876: [GC pause (Metadata GC Threshold) (young) (initial-mark), 0.0298931 secs]
3.457: [GC pause (Metadata GC Threshold) (young) (initial-mark), 0.0297466 secs]
175.897: [GC pause (Metadata GC Threshold) (young) (initial-mark), 0.0557843 secs]
192.229: [GC pause (G1 Evacuation Pause) (young), 0.0501541 secs]
192.840: [GC pause (G1 Evacuation Pause) (young), 0.0526955 secs]
193.375: [GC pause (G1 Evacuation Pause) (young), 0.1079034 secs]
193.976: [GC pause (G1 Evacuation Pause) (young), 0.0249508 secs]
194.488: [GC pause (G1 Evacuation Pause) (young), 0.0300828 secs]
194.968: [GC pause (G1 Evacuation Pause) (young), 0.0349214 secs]
195.565: [GC pause (G1 Evacuation Pause) (young), 0.0230370 secs]
196.182: [GC pause (G1 Evacuation Pause) (young), 0.0332278 secs]
196.897: [GC pause (G1 Evacuation Pause) (young), 0.0148208 secs]
197.776: [GC pause (G1 Evacuation Pause) (young), 0.0208706 secs]
202.481: [GC pause (G1 Evacuation Pause) (young), 0.0257344 secs]
207.367: [GC pause (G1 Evacuation Pause) (young), 0.0313098 secs]
274.000: [GC pause (G1 Evacuation Pause) (young), 0.0504157 secs]
275.167: [GC pause (G1 Evacuation Pause) (young), 0.1701280 secs]
275.558: [GC pause (G1 Evacuation Pause) (young), 0.1799314 secs]
277.057: [GC pause (G1 Evacuation Pause) (young), 0.0226901 secs]
279.010: [GC pause (G1 Evacuation Pause) (young), 0.0230688 secs]
282.200: [GC pause (G1 Evacuation Pause) (young), 0.0409713 secs]
623.944: [GC pause (G1 Evacuation Pause) (young), 4.9323951 secs]
654.289: [GC pause (G1 Evacuation Pause) (young), 1.2856842 secs]
721.647: [GC pause (G1 Evacuation Pause) (young), 0.0205140 secs]
733.077: [GC pause (G1 Evacuation Pause) (young), 0.0254692 secs]
738.076: [GC pause (G1 Evacuation Pause) (young), 0.0195499 secs]
747.856: [GC pause (G1 Evacuation Pause) (young), 0.0156343 secs]
748.201: [GC pause (G1 Evacuation Pause) (young), 0.0198900 secs]
748.429: [GC pause (G1 Evacuation Pause) (young), 0.0224698 secs]
748.643: [GC pause (G1 Evacuation Pause) (young), 0.0153802 secs]
778.621: [GC pause (G1 Evacuation Pause) (young), 0.0196391 secs]
852.163: [GC pause (G1 Evacuation Pause) (young), 0.0332444 secs]
881.130: [GC pause (G1 Evacuation Pause) (young), 0.0254832 secs]
977.958: [GC pause (G1 Evacuation Pause) (young), 0.0252212 secs]
1122.747: [GC pause (G1 Evacuation Pause) (young), 0.0240858 secs]

that 5 sec was pretty big at 623.944, but it doesn't stop the world for 60 seconds.

i couldn't reproduce this error with 0.123 yet,
but i'm pretty sure that the same has happened with 0.123.

If there's anything I can provide to narrow down this problem, pls tell me.

**Comment by spragues-trulia** [comment]
Thanks nazgul33. Great analysis.   I'm in the same boat as you - a user evaluating presto - not a developer.  

If you're in the experimenting mood I've found that v0.112 does not exhibit this particular behavior for our company. I'd be curious if you see the same thing.  

My _hunch_ is the changes between 0.112 and 0.121 have contributed to what we're seeing though just what that is i have no idea.
