### ISSUE TITLE
Partitioned BZ2 tables HIVE_CURSOR_ERROR (Hive connector)

### ISSUE THREAD

**Issue by CKovar** [prestodb/presto#3947]
Having a table with multiple partitions containing BZ2 files results in a HIVE_CURSOR_ERROR.

Reproduced under the following builds:
- Presto 0.117, 0.119
- Presto 0.125 compiled with Hadoop 2.6 
### Presto Worker Error:

```
2015-09-11T12:28:00.850Z ERROR SplitRunner-31-68 com.facebook.presto.execution.TaskExecutor
Error processing Split 20150911_122800_00009_rh7es.1.3-0 {path=hdfs://10.162.10.65/user/hadoop/data/adhoc_test/tdate=2015-06-23/file_12675_2_2.bz2, start=0, length=45637749, hosts=[ip-10-162-9-136.ec2.internal, ip-10-162-8-136.ec2.internal], database=adhoc, table=adhoc_test, forceLocalScheduling=false, partitionName=tdate=2015-06-23, effectivePredicate=TupleDomain:ALL} (start = 1441974480709, wall = 141 ms, cpu = 0 ms, calls = 1): HIVE_CURSOR_ERROR: 18002 2015-09-11T12:28:00.859Z ERROR SplitRunner-43-56 com.facebook.presto.execution.TaskExecutor Error processing Split 20150911_122800_00009_rh7es.1.3-2 {path=hdfs://10.162.10.65/user/hadoop/data/adhoc_test/tdate=2015-06-23/file_12675_3_3.bz2, start=0, length=44107370, hosts=[ip-10-162-9-136.ec2.internal, ip-10-162-10-137.ec2.internal], database=adhoc, table=adhoc_test, forceLocalScheduling=false, partitionName=tdate=2015-06-23, effectivePredicate=TupleDomain:ALL} (start = 1441974480709, wall = 150 ms, cpu = 0 ms, calls = 1): HIVE_CURSOR_ERROR: 6
```
### Presto Coordinator Error:

```
2015-09-11T12:28:00.754Z ERROR query-execution-9 com.facebook.presto.execution.QueryStateMachine Query 20150911_122800_00009_rh7es failed com.facebook.presto.spi.PrestoException: HIVE_CURSOR_ERROR at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:255) at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:93) at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239) at com.facebook.presto.operator.Driver.processInternal(Driver.java:380) at com.facebook.presto.operator.Driver.processFor(Driver.java:303) at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587) at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505) at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.ArrayIndexOutOfBoundsException
```

We have come to the conclusion that it is the combination of BZ2 with partitions by testing the following:
- Created a Hive table WITHOUT partitioning pointing to the same bz2 data - successfully queried
- Created a Hive table partitioned pointing to an uncompressed text copy of the data - successfully queried
- We have only been able to reproduce this error against a partitioned table containing bz2 data.

This seems to be related to the following closed issues:
- #2467 - HIVE_CURSOR_ERROR - Could not obtain block
- #1057 - inconsistent results of presto query with bzip2 compression

**Comment by electrum** [comment]
We definitely should fix this, but in the mean time, we recommend using a different compression codec, like zlib, since bzip2 is extremely slow (and typically does not save much space over zlib).

**Comment by electrum** [comment]
Could you run the query using the CLI with `--debug` and post the full stack trace? The coordinator error shows an `ArrayIndexOutOfBoundsException` but not where it happens.

**Comment by cawallin** [comment]
@CKovar -- have you been able to reproduce this recently? I created a partitioned table with multiple BZ2 files per directory, and it worked fine.
