### ISSUE TITLE
Improve error message when casting from JSON to MAP<VARCHAR, VARCHAR>

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#3959]
It would be useful to include the value that cannot be cast. Also, attaching the underlying exception may just cause confusion.

This query: `select cast(json '{"x":["y"]}' as map<varchar, varchar>);`
Results in the below exception, which looks like a bug since it references a NPE:

```
com.facebook.presto.spi.PrestoException: Value cannot be cast to map<varchar,varchar>
    at com.facebook.presto.operator.scalar.JsonToMapCast.toMap(JsonToMapCast.java:88)
    at com_facebook_presto_$gen_PageProcessor_23539.project_0(Unknown Source)
    at com_facebook_presto_$gen_PageProcessor_23539.process(Unknown Source)
    at com.facebook.presto.operator.FilterAndProjectOperator.getOutput(FilterAndProjectOperator.java:91)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: string is null
    at io.airlift.slice.Preconditions.checkNotNull(Preconditions.java:30)
    at io.airlift.slice.Slices.copiedBuffer(Slices.java:222)
    at io.airlift.slice.Slices.utf8Slice(Slices.java:230)
    at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObjectHelper(TypeJsonUtils.java:124)
    at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObjectHelper(TypeJsonUtils.java:99)
    at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObject(TypeJsonUtils.java:64)
    at com.facebook.presto.operator.scalar.JsonToMapCast.toMap(JsonToMapCast.java:74)
    ... 11 more
```

**Comment by harunurhan** [comment]
Hi, 

I looked at the code (`com.facebook.presto.type.TypeJsonUtils`). In the code, type checking is done via checkState in each `if` block I think the easiest thing to do here is inserting a checkState like below, where we expect a string. At least that throws an IllegalStateException with a little better message.

```
        if (type.getJavaType() == Slice.class) {
            checkState(parser.getCurrentToken() == JsonToken.VALUE_STRING, "Expected a string");
            sliceValue = Slices.utf8Slice(parser.getValueAsString());
        }
```

However, I think this might not be helpful and it would be better have something which gives us an exception message like "Expected TypeX but found TypeY" instead of this and all other checks in stackRepresentationToObjectHelper. If you meant something like this, please let me know I would like to help you.

FYI: I am an interested undergrad student, just started reading source code and issues randomly several days ago. May be I completely misunderstood all thing, sorry about that in advanced, still trying to figure out.

Harun.
