### ISSUE TITLE
I am trying to configure presto 0.119 on EMR and I am getting the following error when running ./launcher run

### ISSUE THREAD

**Issue by rraghuram64** [prestodb/presto#3964]
2015-11-13T20:37:24.532Z        INFO    main    com.facebook.presto.server.PrestoServer ======== SERVER STARTED ========
2015-11-13T20:37:29.603Z        WARN    http-client-shared-82   com.facebook.presto.memory.RemoteNodeMemory     Error fetching memory info from http://172.31.25.119:8080/v1/memory
java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at com.google.common.base.Throwables.propagate(Throwables.java:160)
        at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:22)
        at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:55)
        at io.airlift.http.client.FullJsonResponseHandler.handleException(FullJsonResponseHandler.java:35)
        at io.airlift.http.client.jetty.JettyHttpClient$JettyResponseFuture.failed(JettyHttpClient.java:798)
        at io.airlift.http.client.jetty.JettyHttpClient$BufferingResponseListener.onComplete(JettyHttpClient.java:1032)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
        at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
        at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:446)
        at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:517)
        at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:130)
        at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:123)
        at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:259)
        at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
        at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:704)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.abort(HttpConnectionOverHTTP.java:157)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:145)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onReadTimeout(HttpConnectionOverHTTP.java:98)
        at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:173)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback$1.run(AbstractConnection.java:582)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.TimeoutException
        ... 6 more

**Comment by cawallin** [comment]
Closing this issue, if you have further questions ask on the presto-users mailing list.
