### ISSUE TITLE
Bad error message when window function is used in HAVING clause

### ISSUE THREAD

**Issue by martint** [prestodb/presto#3979]
``` sql
SELECT count(*) OVER ()
FROM (VALUES 1) 
HAVING count(*) OVER () > 1
```

fails with:

```
count():bigint is not a scalar function
```

full stacktrace:

```
java.lang.IllegalArgumentException: count():bigint is not a scalar function
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:546)
    at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:798)
    at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:628)
    at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:77)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:251)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:133)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:100)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$130(PlanRewriter.java:74)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
    at com.facebook.presto.sql.planner.plan.PlanVisitor.visitWindow(PlanVisitor.java:105)
    at com.facebook.presto.sql.planner.plan.WindowNode.accept(WindowNode.java:171)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$130(PlanRewriter.java:74)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
    at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
    at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:28)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions.optimize(SimplifyExpressions.java:67)
    at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:98)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:266)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:245)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:209)
    at com.facebook.presto.execution.QueuedExecution.lambda$start$201(QueuedExecution.java:68)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

This might be related to the changes in eb3d13eb0b1ec96802d338bab9f069b124166512

**Comment by cberner** [comment]
It has always been like that. In fact, I'd say my change made it better :)

What it used to say is:

```
java.lang.IllegalStateException: not a scalar function or operator

	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.facebook.presto.metadata.FunctionInfo.getMethodHandle(FunctionInfo.java:202)
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:785)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:606)
	at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:77)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:234)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:133)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:100)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:70)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:111)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
```

**Comment by cberner** [comment]
@martint can you comment with the message you'd like to see? Then this will be a good beginner task

**Comment by martint** [comment]
It should actually work, I think. This should be equivalent to:

```sql
SELECT * FROM (
    SELECT count(*) OVER () x 
    FROM (VALUES 1)
) 
WHERE x > 1;

**Comment by cberner** [comment]
Looked through the spec, and I think it specifically forbids that:

Section 7.10
"<having clause> ::=
HAVING <search condition>"

Section 7.10.5
"The <search condition> shall not contain a <window function> without an intervening <query expression>."

**Comment by martint** [comment]
I don't understand what that means. There's no `query expression` involved in a `having clause` or `table expression` (which is what the having clause is attached to). Maybe it's referring to whether that `having clause` is contained in a `query expression`? This would be the case for the common `SELECT` syntax we support, but not for `<select statement: single row>`, which is defined as:

```
<select statement: single row>
  : SELECT <set quantifier>? <select list> INTO <select target list> <table expression>
  ;
```

**Comment by electrum** [comment]
It's not clear to me how a window function could work in the HAVING clause, since window functions run after HAVING. Would it see a different set of rows?

Regardless, supporting that is a separate issue. For this issue, we need to fix the error message.

**Comment by kokosing** [comment]
I have a problem with this. So far I understand that query like:

```
SELECT projection FROM source HAVING [window function] > x
```
is equivalent to
 
```
SELECT projection FROM (SELECT projection, [window function] as wf FROM source) WHERE wf > x
```
And so I do not understand what is the problem with such query. Is not that HAVING is just a syntax sugar?

**Comment by kokosing** [comment]
Sorry, I pressed the wrong button ; /

I am OK with this change as it makes Presto more coherent with ANSI. I just would like to understand the ANSI motivation.

**Comment by electrum** [comment]
@kokosing the window function is evaluated after the having clause.

**Comment by kokosing** [comment]
@electrum Thanks. That makes sense. So the queries I mentioned above are not equivalent. The one with window function in HAVING is just incorrect.
