### ISSUE TITLE
Orc File Read Error

### ISSUE THREAD

**Issue by syed72** [prestodb/presto#4055]
I am trying to read a orc file, this file has >5million rows and below is code  to read, I faced problem when i am getting int batchSize = recordReader.nextBatch();

please check this and suggest me a fix. 

 OrcRecordReader recordReader = orcReader.createRecordReader(columnTypes, OrcPredicate.TRUE, DateTimeZone.getDefault());
        long rows = 0;
        Block[] blocks = new Block[columnTypes.size()];
        int batchSize = recordReader.nextBatch();

```
   /* for (int batchSize = recordReader.nextBatch(); batchSize > 0; batchSize = recordReader.nextBatch()) {
       rows += readBatch(columnTypes, recordReader, batchSize);
        //rows += readColumns(columnTypes, recordReader, batchSize);
    }*/
    while (batchSize > 0)
    {
        int k = 0;
        for (Entry<Integer, Type> entry : columnTypes.entrySet()) {
            Block b = recordReader.readBlock(entry.getValue(), entry.getKey());
            blocks[k] = b;
            k++;
            //System.out.print(entry.getValue().getObjectValue(TestingConnectorSession.SESSION, block, 0));
            //System.out.print(",");
        }
        int p = 0;
        for (Entry<Integer, Type> entry : columnTypes.entrySet()) 
        {
            for (int l=0; l<batchSize; l++)
            {
                Block block = blocks[p];
                System.out.print(entry.getValue().getObjectValue(TestingConnectorSession.SESSION, block, l));
            }
            p++;
        }
    }
```

and i got below exception,

Exception in thread "main" java.lang.IndexOutOfBoundsException: end index (4197522) must not be greater than size (1670)
    at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:94)
    at io.airlift.slice.Slice.checkIndexLength(Slice.java:1185)
    at io.airlift.slice.Slice.slice(Slice.java:739)
    at io.airlift.slice.BasicSliceInput.readSlice(BasicSliceInput.java:156)
    at com.facebook.presto.orc.stream.OrcInputStream.advance(OrcInputStream.java:210)
    at com.facebook.presto.orc.stream.OrcInputStream.read(OrcInputStream.java:125)
    at java.io.InputStream.read(InputStream.java:101)
    at com.facebook.presto.hive.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:737)
    at com.facebook.presto.hive.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:701)
    at com.facebook.presto.hive.protobuf.CodedInputStream.readTag(CodedInputStream.java:99)
    at org.apache.hadoop.hive.ql.io.orc.OrcProto$StripeFooter.<init>(OrcProto.java:10661)
    at org.apache.hadoop.hive.ql.io.orc.OrcProto$StripeFooter.<init>(OrcProto.java:10625)
    at org.apache.hadoop.hive.ql.io.orc.OrcProto$StripeFooter$1.parsePartialFrom(OrcProto.java:10730)
    at org.apache.hadoop.hive.ql.io.orc.OrcProto$StripeFooter$1.parsePartialFrom(OrcProto.java:10725)
    at com.facebook.presto.hive.protobuf.AbstractParser.parseFrom(AbstractParser.java:89)
    at com.facebook.presto.hive.protobuf.AbstractParser.parseFrom(AbstractParser.java:95)
    at com.facebook.presto.hive.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
    at org.apache.hadoop.hive.ql.io.orc.OrcProto$StripeFooter.parseFrom(OrcProto.java:10958)
    at com.facebook.presto.orc.metadata.OrcMetadataReader.readStripeFooter(OrcMetadataReader.java:112)
    at com.facebook.presto.orc.StripeReader.readStripeFooter(StripeReader.java:321)
    at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:100)
    at com.facebook.presto.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:355)
    at com.facebook.presto.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:317)
    at com.facebook.presto.orc.OrcRecordReader.nextBatch(OrcRecordReader.java:281)

**Comment by syed72** [comment]
Any Update on this?

**Comment by dain** [comment]
Sorry, I never saw this issue.  If this is still a problem, please open a new issue and attach a sample file.
