### ISSUE TITLE
java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.DistributedFileSystem not found

### ISSUE THREAD

**Issue by syed72** [prestodb/presto#4090]
Hi,

I am using a custom connector to read orc file using hive orc reader, 
so when i try to read a file from hdfs

it throws below exception

java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hdfs.DistributedFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:1720)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2415)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:69)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:367)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:287)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:53)
        at com.facebook.presto.example.ORCBatchReader.readBatch(ORCBatchReader.java:56)
        at com.facebook.presto.example.ExampleRecordSet.<init>(ExampleRecordSet.java:54)
        at com.facebook.presto.example.ExampleRecordSetProvider.getRecordSet(ExampleRecordSetProvider.java:54)
        at com.facebook.presto.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:41)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
        at com.facebook.presto.operator.TableScanOperator.createSourceIfNecessary(TableScanOperator.java:258)
        at com.facebook.presto.operator.TableScanOperator.isFinished(TableScanOperator.java:206)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)

is this any jar version problem? or any other thing?

As Dain replied to the above thread in google groups,
Based on this part of the stack trace: 

> at com.facebook.presto.example.ExampleRecordSetProvider.getRecordSet(ExampleRecordSetProvider.java:54) 

It appears that you have modified the example http connector to support reading ORC files from HDFS.  To get HDFS to work properly is a lot of work because it uses dynamic class loading to resolve things like the file system, and it has global statics.  We have resolved all of these problem in the Hive connector, but it was a lot of work. 

To fix class loader issue, you might be able to use the ClassLoaderSafe\* wrappers in the SPI.  See HiveConnectorFactory for an example on how to use them. 

Additionally it looks like you are using an ORC reader under a RecordSet interface.  This is much slower than using the PageSource interface, as the Presto ORC reader natively return Presto blocks (which become pages).  See OrcPageSource for how to implement this. 

-dain 

Still i need some more info on how to use this classLoaderSafe wrappers...

can somebody help me out thr?

Thanks
Akram Syed

**Comment by cawallin** [comment]
Is there any reason you need a custom connector rather than reading your ORC files via the Hive metastore?

**Comment by syed72** [comment]
I was trying to put my table data in cache? so wanna implement that caching using custom connector.
Thanks

**Comment by dain** [comment]
HDFS (and Hive) use dynamic class loading to find their plugins (e.g., the reader for a file format or the implementation of a compression algorithm), so if you want to use these in your new plugin, you will need to set the thread context class loader when Presto calls into your plugin (and unset it on the way out).  This is what the existing Hive connector does.  You can see the code for this here:

https://github.com/facebook/presto/blob/master/presto-hive/src/main/java/com/facebook/presto/hive/HiveConnectorFactory.java#L134

**Comment by dain** [comment]
I assume using the `ClassLoaderSafe` wrappers fixed this problem.  If not, please open a new issue.
