### ISSUE TITLE
Get PageTransportTimeoutException, while the worker does not crash

### ISSUE THREAD

**Issue by zhenxiao** [prestodb/presto#4182]
We recently upgraded to Presto 0.125, with another 2 commits in Presto 0.126:
https://github.com/facebook/presto/commit/9d0f89446f62146337137c5954b5739edd6a5799
https://github.com/facebook/presto/commit/633dc4a675df376e23f497dac4312540b5a336a5

Some of our queries(mostly joins) kept getting the following error:

> > Query 20151216_015337_00741_mcnbp failed: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://10.61.206.175:8080/v1/task/20151216_015337_00741_mcnbp.2.20/results/20151216_015337_00741_mcnbp.1.6/21 - requests failed for 60.04s)
> > com.facebook.presto.operator.PageTransportTimeoutException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://10.61.206.175:8080/v1/task/20151216_015337_00741_mcnbp.2.20/results/20151216_015337_00741_mcnbp.1.6/21 - requests failed for 60.04s)
> >  at com.facebook.presto.operator.HttpPageBufferClient$1.onFailure(HttpPageBufferClient.java:332)
> >  at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
> >  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> >  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> >  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> >  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> >  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> >  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> >  at java.lang.Thread.run(Thread.java:745)
> > Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
> >  at com.google.common.base.Throwables.propagate(Throwables.java:160)
> >  at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:22)
> >  at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:490)
> >  at com.facebook.presto.operator.HttpPageBufferClient$PageResponseHandler.handleException(HttpPageBufferClient.java:477)
> >  at io.airlift.http.client.jetty.JettyHttpClient$JettyResponseFuture.failed(JettyHttpClient.java:804)
> >  at io.airlift.http.client.jetty.JettyHttpClient$BufferingResponseListener.onComplete(JettyHttpClient.java:1038)
> >  at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:193)
> >  at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:185)
> >  at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:446)
> >  at org.eclipse.jetty.client.HttpReceiver.abort(HttpReceiver.java:517)
> >  at org.eclipse.jetty.client.HttpChannel.abortResponse(HttpChannel.java:130)
> >  at org.eclipse.jetty.client.HttpChannel.abort(HttpChannel.java:123)
> >  at org.eclipse.jetty.client.HttpExchange.abort(HttpExchange.java:259)
> >  at org.eclipse.jetty.client.HttpConversation.abort(HttpConversation.java:141)
> >  at org.eclipse.jetty.client.HttpRequest.abort(HttpRequest.java:704)
> >  at org.eclipse.jetty.client.TimeoutCompleteListener.run(TimeoutCompleteListener.java:71)
> >  ... 7 more
> > Caused by: java.util.concurrent.TimeoutException: Total timeout elapsed
> >  ... 8 more

These errors used to be worker JVM crash or transient issue. But this time, the worker does not crash. And we could reproduce it consistently. In the worker's log, there are a large number of:

> > 2015-12-16T01:54:43.166Z  DEBUG   exchange-client-12  com.facebook.presto.operator.HttpPageBufferClient   Request to >>http://10.81.216.92:8080/v1/task/20151216_015337_00741_mcnbp.2.30/results/20151216_015337_00741_mcnbp.1.6/45 failed java.util.concurrent.CancellationException: Task was cancelled.

Does anyone see similar problems? Or is it some configuration for jetty/http?

**Comment by zhenxiao** [comment]
we already set:
http-server.threads.max=500
are there other configurations related?

**Comment by nezihyigitbasi** [comment]
Related issues #4004 #3876

**Comment by nezihyigitbasi** [comment]
Checked the gc logs around the time tasks failed and there is no full GC happening.

**Comment by zhenxiao** [comment]
try playing with it, by setting:
task.max-worker-threads=32
in the worker does not solve the problem

**Comment by nezihyigitbasi** [comment]
@dain any settings that we can try tweaking? We started seeing this after we deployed version `0.125`.

**Comment by nileema** [comment]
Can you check the http request log on the server to see if the request was received/processed?

**Comment by nileema** [comment]
I would look at the http request logs on the server and check how long it takes for the server to process requests from this client. As a break-fix you can bump up the exchange.min-error-duration which will make the client wait for a response longer than 60s (which is the default). Typically requests are processed within few ms so this does seem suspicious.

**Comment by nezihyigitbasi** [comment]
```
# grep '20151218_223556_03240_dc5sb.4.12/0' server.log
2015-12-18T22:36:17.056Z	DEBUG	exchange-client-19	com.facebook.presto.operator.HttpPageBufferClient	Request to http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
2015-12-18T22:36:29.382Z	DEBUG	exchange-client-7	com.facebook.presto.operator.HttpPageBufferClient	Request to http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
2015-12-18T22:36:41.410Z	DEBUG	exchange-client-17	com.facebook.presto.operator.HttpPageBufferClient	Request to http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
2015-12-18T22:36:53.610Z	DEBUG	exchange-client-23	com.facebook.presto.operator.HttpPageBufferClient	Request to http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
2015-12-18T22:37:05.773Z	DEBUG	exchange-client-0	com.facebook.presto.operator.HttpPageBufferClient	Request to http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
2015-12-18T22:37:17.384Z	DEBUG	exchange-client-11	com.facebook.presto.operator.HttpPageBufferClient	Request to http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout elapsed
2015-12-18T22:37:17.388Z	ERROR	SplitRunner-598-61	com.facebook.presto.execution.TaskExecutor	Error processing Split 20151218_223556_03240_dc5sb.4.12-1  (start = 1450478162344, wall = 75044 ms, cpu = 23705 ms, calls = 2125): PAGE_TRANSPORT_TIMEOUT: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (http://10.203.231.75:8080/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0 - requests failed for 60.04s)
```

Then I checked http request logs of `10.203.231.75` for that specific url

```
# grep 'results/20151218_223556_03240_dc5sb.4.12/0' http-request.log
2015-12-18T22:36:05.652Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	204	0	0	1002	null
2015-12-18T22:36:07.061Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	200	0	5474393	10040	null
2015-12-18T22:36:19.435Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	200	0	7074934	10024	null
2015-12-18T22:36:31.464Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	200	0	6023495	10037	null
2015-12-18T22:36:43.713Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	200	0	5336183	9954	null
2015-12-18T22:36:55.847Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	200	0	4280759	9986	null
2015-12-18T22:37:07.442Z	10.35.184.196	GET	/v1/task/20151218_223556_03240_dc5sb.5.227/results/20151218_223556_03240_dc5sb.4.12/0	null	null	200	0	5956390	10047	null
```

**Comment by nezihyigitbasi** [comment]
Looking at `ServerMainModule` I see that the request timeout for the http client of the exchange client is 10s, so all these requests timed out and in total 6 requests timeout summing up to 60s+.

**Comment by nileema** [comment]
Looks like there were 6 retries in 10 seconds so each request waited for 10 seconds before it timed out. 
On the serverside the last but one column indicates the time to last byte in ms 
https://github.com/airlift/airlift/blob/master/http-server/src/main/java/io/airlift/http/server/HttpLogLayout.java

The http log shows that it took more than 10s to process the request.  Which is probably why you got a timeout on the client. 

Do you have ``exchange.http-client.request-timeout`` set in worker configs?

**Comment by nezihyigitbasi** [comment]
Nope we use the default of 10s.

**Comment by nileema** [comment]
Ah, update your worker config to set exchange.http-client.request-timeout=20s that should help with the timeouts. 

As a side note we need to investigate why it takes 10s to complete that call. This has been on our list of todos. Hopefully we will get to it soon.

**Comment by nileema** [comment]
I would also bump up the `scheduler.http-client.request-timeout` if you are seeing timeouts from the `HttpRemoteTask`

**Comment by nezihyigitbasi** [comment]
@nileema did you have a chance to investigate the root cause of this issue?

**Comment by miniway** [comment]
For me, Full GC was main cause of the timeout and very high cpu usage was another occational cause.

**Comment by hustnn** [comment]
@nezihyigitbasi 

Is parameter scheduler.http-client.request-timeout replaced by other name? I can't find it in the source code.

**Comment by hustnn** [comment]
I think we should set "exchange.http-client.request-timeout" instead of "scheduler.http-client.request-timeout".

**Comment by nezihyigitbasi** [comment]
@hustnn These are both valid configuration parameters, [here](https://github.com/airlift/airlift/blob/master/http-client/src/main/java/io/airlift/http/client/HttpClientConfig.java#L110-L115) is the relevant source in airlift. Each HTTP client can be configured separately and the name of the configuration parameter will be `<client_name>.http-client.request-timeout`. `scheduler` and `exchange` are the name of the HTTP clients, for example [here](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/CoordinatorModule.java#L216-L222) is the definition for the `scheduler` HTTP client. 

What is the error that you seeing?

**Comment by hustnn** [comment]
@nezihyigitbasi Thanks.
Got it, I already find the related source code in CoordinatorModule.java. 

The error I met is same as the error here. After increasing it from the default value 10s to 60s. The errors rarely occur now. 

Now, another time error occurs. It seems that the default timeout of this error is also only 10 sec,
I am looking for it in the source code.

"com.facebook.presto.spi.PrestoTransportException: Encountered too many errors talking to a worker node. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes. (updating task http://10.65.20.96:8000/v1/task/20180221_042220_00035_f355m.2.14 - 17 failures, time since last success 126.65s)
	at com.facebook.presto.server.remotetask.RequestErrorTracker.requestFailed(RequestErrorTracker.java:129)
	at com.facebook.presto.server.remotetask.HttpRemoteTask$UpdateResponseHandler.failed(HttpRemoteTask.java:781)
	at com.facebook.presto.server.remotetask.SimpleHttpResponseHandler.onFailure(SimpleHttpResponseHandler.java:86)
	at com.google.common.util.concurrent.Futures$4.run(Futures.java:1126)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Total timeout 10000 ms elapsed"

**Comment by viczhang861** [comment]
Can be related to https://github.com/prestodb/presto/issues/14071
