### ISSUE TITLE
Join with multiple IN-subquery clauses fails

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4250]
I believe this is due to the fact that `analysis.addJoinInPredicates` is called in a loop in `StatementAnalyzer`. This is almost certainly wrong, as it does a `put` into an identity map, ignoring any previous value

```
select * from (values 1) t(x) join (values 1) t2(y) on (x in (values 1)) = (y in (values 1)) and (x in (values 2)) = (y in (values 2));
```

Fails with:
```
Query 20151230_004032_00259_cku6f failed: com.facebook.presto.sql.tree.Query cannot be cast to com.facebook.presto.sql.tree.Expression
java.lang.ClassCastException: com.facebook.presto.sql.tree.Query cannot be cast to com.facebook.presto.sql.tree.Expression
	at com.facebook.presto.sql.planner.SubExpressionExtractor$1.process(SubExpressionExtractor.java:65)
	at com.facebook.presto.sql.planner.SubExpressionExtractor$1.process(SubExpressionExtractor.java:61)
	at com.facebook.presto.sql.tree.DefaultTraversalVisitor.visitSubqueryExpression(DefaultTraversalVisitor.java:319)
	at com.facebook.presto.sql.tree.SubqueryExpression.accept(SubqueryExpression.java:47)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.SubExpressionExtractor$1.process(SubExpressionExtractor.java:68)
	at com.facebook.presto.sql.planner.SubExpressionExtractor$1.process(SubExpressionExtractor.java:61)
	at com.facebook.presto.sql.tree.DefaultTraversalVisitor.visitInPredicate(DefaultTraversalVisitor.java:149)
	at com.facebook.presto.sql.tree.InPredicate.accept(InPredicate.java:54)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.SubExpressionExtractor$1.process(SubExpressionExtractor.java:68)
	at com.facebook.presto.sql.planner.SubExpressionExtractor.extract(SubExpressionExtractor.java:70)
	at com.facebook.presto.sql.planner.SubExpressionExtractor.extract(SubExpressionExtractor.java:54)
	at com.facebook.presto.sql.planner.EqualityInference$1.compare(EqualityInference.java:69)
	at com.facebook.presto.sql.planner.EqualityInference$1.compare(EqualityInference.java:58)
	at com.google.common.collect.ComparatorOrdering.compare(ComparatorOrdering.java:38)
	at com.google.common.collect.Ordering.min(Ordering.java:499)
	at com.google.common.collect.Ordering.min(Ordering.java:466)
	at com.google.common.collect.Ordering.min(Ordering.java:482)
	at com.facebook.presto.sql.planner.EqualityInference.<init>(EqualityInference.java:83)
	at com.facebook.presto.sql.planner.EqualityInference.<init>(EqualityInference.java:54)
	at com.facebook.presto.sql.planner.EqualityInference$Builder.build(EqualityInference.java:406)
	at com.facebook.presto.sql.planner.EqualityInference.createEqualityInference(EqualityInference.java:297)
	at com.facebook.presto.sql.planner.EffectivePredicateExtractor.pullExpressionThroughSymbols(EffectivePredicateExtractor.java:294)
	at com.facebook.presto.sql.planner.EffectivePredicateExtractor.visitProject(EffectivePredicateExtractor.java:148)
	at com.facebook.presto.sql.planner.EffectivePredicateExtractor.visitProject(EffectivePredicateExtractor.java:69)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.EffectivePredicateExtractor.extract(EffectivePredicateExtractor.java:74)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:260)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitJoin(PredicatePushDown.java:117)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:159)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitFilter(PredicatePushDown.java:249)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitFilter(PredicatePushDown.java:117)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$193(SimplePlanRewriter.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitProject(PredicatePushDown.java:200)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitProject(PredicatePushDown.java:117)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$193(SimplePlanRewriter.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:143)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown$Rewriter.visitPlan(PredicatePushDown.java:117)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:34)
	at com.facebook.presto.sql.planner.optimizations.PredicatePushDown.optimize(PredicatePushDown.java:114)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:101)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:261)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:240)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:204)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$269(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by yuananf** [comment]
fixed by #3954
