### ISSUE TITLE
Raptor large INSERT times out committing to MySQL

### ISSUE THREAD

**Issue by dain** [prestodb/presto#4557]
I attempted a large insert that resulted in ~140k shards.  This failed with:

```
com.facebook.presto.spi.PrestoException: Failed to perform metadata operation
    at com.facebook.presto.raptor.util.DatabaseUtil.metadataError(DatabaseUtil.java:68)
    at com.facebook.presto.raptor.util.DatabaseUtil.runTransaction(DatabaseUtil.java:62)
    at com.facebook.presto.raptor.metadata.DatabaseShardManager.commitShards(DatabaseShardManager.java:224)
    at com.facebook.presto.raptor.RaptorMetadata.finishInsert(RaptorMetadata.java:645)
    at com.facebook.presto.metadata.MetadataManager.finishInsert(MetadataManager.java:559)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner$1.finishTable(LocalExecutionPlanner.java:2009)
    at com.facebook.presto.operator.TableFinishOperator.getOutput(TableFinishOperator.java:156)

Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 300,057 milliseconds ago.  The last packet sent successfully to the server was 300,057 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
```

**Comment by erichwang** [comment]
Yup, I'm getting a lot of this too with large backfill inserts.
