### ISSUE TITLE
Uncategorized error for OrcInputStream

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4773]
```
java.lang.IndexOutOfBoundsException: end index (3737344) must not be greater than size (13)
	at io.airlift.slice.Preconditions.checkPositionIndexes(Preconditions.java:94)
	at io.airlift.slice.Slice.checkIndexLength(Slice.java:1194)
	at io.airlift.slice.Slice.slice(Slice.java:748)
	at io.airlift.slice.BasicSliceInput.readSlice(BasicSliceInput.java:156)
	at com.facebook.presto.orc.stream.OrcInputStream.advance(OrcInputStream.java:229)
	at com.facebook.presto.orc.stream.OrcInputStream.read(OrcInputStream.java:131)
	at com.facebook.presto.orc.stream.LongStreamV1.readValues(LongStreamV1.java:54)
	at com.facebook.presto.orc.stream.LongStreamV1.next(LongStreamV1.java:90)
	at com.facebook.presto.orc.stream.LongStreamV1.nextIntVector(LongStreamV1.java:199)
	at com.facebook.presto.orc.reader.SliceDirectStreamReader.readBlock(SliceDirectStreamReader.java:124)
	at com.facebook.presto.orc.reader.SliceStreamReader.readBlock(SliceStreamReader.java:53)
	at com.facebook.presto.orc.OrcRecordReader.readBlock(OrcRecordReader.java:311)
	at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:316)
	at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:292)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:249)
	at com.facebook.presto.spi.block.LazyBlock.isNull(LazyBlock.java:225)
	at com_facebook_presto_$gen_PageProcessor_4951.filter(Unknown Source)
	at com_facebook_presto_$gen_PageProcessor_4951.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:259)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:577)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	... 3 more

**Comment by electrum** [comment]
I think the `OrcInputStream.advance()` method should validate `chunkLength` and throw `OrcCorruptionException`.

**Comment by petroav** [comment]
Looks like this was fixed. Closing.
