### ISSUE TITLE
Raptor system.shards table needs to ignore missing index tables

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#4800]
The distributed tests can fail due to this race condition:

```
com.facebook.presto.spi.PrestoException: Failed to perform metadata operation
    at com.facebook.presto.raptor.util.DatabaseUtil.metadataError(DatabaseUtil.java:68)
    at com.facebook.presto.raptor.systemtables.ShardMetadataRecordCursor.getNextResultSet(ShardMetadataRecordCursor.java:281)
    at com.facebook.presto.raptor.systemtables.ShardMetadataRecordCursor.<init>(ShardMetadataRecordCursor.java:108)
    at com.facebook.presto.raptor.systemtables.ShardMetadataSystemTable.cursor(ShardMetadataSystemTable.java:57)
    at com.facebook.presto.connector.system.SystemRecordSetProvider$1.cursor(SystemRecordSetProvider.java:118)
    at com.facebook.presto.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
    at com.facebook.presto.spi.RecordPageSource.<init>(RecordPageSource.java:37)
    at com.facebook.presto.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:42)
    at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
    at com.facebook.presto.operator.ScanFilterAndProjectOperator.createSourceIfNecessary(ScanFilterAndProjectOperator.java:287)
    at com.facebook.presto.operator.ScanFilterAndProjectOperator.isFinished(ScanFilterAndProjectOperator.java:180)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:577)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Table "X_SHARDS_T47" not found; SQL statement:
SELECT
tables.schema_name,
tables.table_name,
shards.shard_uuid,
shards.bucket_number,
shards.uncompressed_size,
shards.compressed_size,
shards.row_count,
null,
null
FROM x_shards_t47 x
JOIN shards ON (x.shard_id = shards.shard_id)
JOIN tables ON (shards.table_id = tables.table_id)
WHERE (tables.schema_name = ?) AND
(tables.table_name IN (?,?)) [42102-189]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    at org.h2.message.DbException.get(DbException.java:179)
    at org.h2.message.DbException.get(DbException.java:155)
    at org.h2.command.Parser.readTableOrView(Parser.java:5293)
    at org.h2.command.Parser.readTableFilter(Parser.java:1234)
    at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1873)
    at org.h2.command.Parser.parseSelectSimple(Parser.java:1982)
    at org.h2.command.Parser.parseSelectSub(Parser.java:1867)
    at org.h2.command.Parser.parseSelectUnion(Parser.java:1688)
    at org.h2.command.Parser.parseSelect(Parser.java:1676)
    at org.h2.command.Parser.parsePrepared(Parser.java:432)
    at org.h2.command.Parser.parse(Parser.java:304)
    at org.h2.command.Parser.parse(Parser.java:276)
    at org.h2.command.CommandContainer.recompileIfRequired(CommandContainer.java:54)
    at org.h2.command.CommandContainer.query(CommandContainer.java:86)
    at org.h2.command.Command.executeQuery(Command.java:196)
    at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:108)
    at com.facebook.presto.raptor.systemtables.ShardMetadataRecordCursor.getNextResultSet(ShardMetadataRecordCursor.java:277)
    ... 17 more
```

**Comment by electrum** [comment]
There's probably not a good way to check for this exact "table not found" exception for multiple databases. Instead, we can check if the table exists when catching any exception in `getNextResultSet()`. I think this will work:
```java
catch (SQLException | DBIException e) {
    close();
    if (!metadataDao.tableExists(tableId)) {
        return getNextResultSet();
    }
    throw metadataError(e);
}
```
This will need a new method on `MetadataDao`.

**Comment by AlkisPlas** [comment]
I will take this

**Comment by ron819** [comment]
@AlekseiS  was this done?
