### ISSUE TITLE
Support for column aliases in WITH clause

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4801]
```sql
WITH a(x) AS (VALUES 1,2,3) 
SELECT * FROM a
```

```
Query 20160316_210951_08931_ukuwz failed: line 1:6: Column alias not supported in WITH queries
com.facebook.presto.sql.analyzer.SemanticException: line 1:6: Column alias not supported in WITH queries
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeWith(StatementAnalyzer.java:1922)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:809)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:220)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:103)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:258)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:244)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:208)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$258(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by harunurhan** [comment]
I have done something that seems to work but not for VALUES, currently it is a draft not the final code. It re-writes the WITH query with alias.

I am not sure if my approach is correct. Can you have a look at it? @martint  https://github.com/harunurhan/presto/commit/d233f656ccb243fa8dcf431e3a0340efd5963c5b

**Comment by martint** [comment]
@harunurhan I took a look. The analyzer should not rewrite queries. What it should do, instead, is record the name of the columns associated with the "named query" (in the analysis object) and resolve names against that when processing clauses that refer to those columns. The planner should also use that information to resolve the names of the fields as it produces the relational plan.

**Comment by maciejgrzybek** [comment]
Closing since #5104 is merged.
