### ISSUE TITLE
Error when GROUPING SETS is used with UNION

### ISSUE THREAD

**Issue by buremba** [prestodb/presto#4838]
The following query 
`select * from (select 'a' col1, 'b' col2 union all select 'a', 'b' col2) group by grouping sets (col1,col2);`
throws this exception:

```
java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:1074)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.UnionNode.accept(UnionNode.java:139)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1113)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:212)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitGroupId(PlanVisitor.java:145)
	at com.facebook.presto.sql.planner.plan.GroupIdNode.accept(GroupIdNode.java:102)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1113)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:228)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1113)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:272)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:180)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1113)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:228)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1113)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTopN(AddExchanges.java:530)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTopN(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.TopNNode.accept(TopNNode.java:112)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1113)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:234)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:185)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:147)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:127)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:265)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:244)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:208)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$218(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$899/1023216403.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by anusudarsan** [comment]
https://github.com/prestodb/presto/pull/4949 fixed this issue and was included in release 0.144

**Comment by anusudarsan** [comment]
@raghavsethi Can you close this issue?

**Comment by raghavsethi** [comment]
Yes, thank you!
