### ISSUE TITLE
Error during analysis in GROUP BY query with AT TIMEZONE

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4904]
```sql
SELECT MIN(x) AT TIME ZONE 'America/Chicago' from (VALUES now()) t(x);
```

```
java.lang.UnsupportedOperationException: aggregation analysis not yet implemented for: com.facebook.presto.sql.tree.AtTimeZone
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer$Visitor.visitExpression(AggregationAnalyzer.java:150)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer$Visitor.visitExpression(AggregationAnalyzer.java:144)
	at com.facebook.presto.sql.tree.AstVisitor.visitAtTimeZone(AstVisitor.java:542)
	at com.facebook.presto.sql.tree.AtTimeZone.accept(AtTimeZone.java:59)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer$Visitor.process(AggregationAnalyzer.java:455)
	at com.facebook.presto.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:139)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.verifyAggregations(StatementAnalyzer.java:1791)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeAggregations(StatementAnalyzer.java:1749)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:1022)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:219)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:810)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:219)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:103)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:269)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:255)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:219)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by geraint0923** [comment]
Fixed by #4905
