### ISSUE TITLE
Cannot insert null into table without explicit cast

### ISSUE THREAD

**Issue by martint** [prestodb/presto#4909]
```sql
create table test (a bigint);
insert into test (a) values (null);
```

```
Query 20160331_004854_02765_vpwmu failed: Insert query has mismatched column types: Table: [bigint], Query: [unknown]
com.facebook.presto.sql.analyzer.SemanticException: Insert query has mismatched column types: Table: [bigint], Query: [unknown]
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitInsert(StatementAnalyzer.java:583)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitInsert(StatementAnalyzer.java:219)
	at com.facebook.presto.sql.tree.Insert.accept(Insert.java:61)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:269)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:255)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:219)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by maciejgrzybek** [comment]
@martint is simple check for null in type matching fine (if type match OR inserted type = `null`) or you expected something more clever here?

**Comment by martint** [comment]
Yes, I think that would be sufficient for now. Once we revamp the type system/coercions/inference, we can fix it the right way.

**Comment by maciejgrzybek** [comment]
Okay, so I will make it.
