### ISSUE TITLE
Non-deterministic test failure in TestRaptorDistributedQueries.testCreateBucketedTable()

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#4915]
This test seems to fail about 1 in 5000 runs

```
java.lang.AssertionError: not equal
Actual 1 rows:
    [75]
Expected 1 rows:
    [100]


    at org.testng.Assert.fail(Assert.java:94)
    at com.facebook.presto.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:132)
    at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:120)
    at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:106)
    at com.facebook.presto.raptor.TestRaptorDistributedQueries.testCreateBucketedTable(TestRaptorDistributedQueries.java:138)
```

**Comment by findepi** [comment]
The test method is now in `TestRaptorIntegrationSmokeTest` and so the issue is now https://github.com/prestodb/presto/issues/6434
