### ISSUE TITLE
In memory hash join causing OOM

### ISSUE THREAD

**Issue by knowledgehacker** [prestodb/presto#4966]
I am using Presto 0.110. One of our query causes out of memory error when doing in memory hash join.
From the heap dump, I see the compiled PagesHashStrategy occupies most retained memory.
From the code, I see channels(one channel per column), a join channel, and a  hash channel are setup. In my understanding the channels are used to get column data from the hashed splits, while the join channel is used to get column data from lookup source. What is the hash channel used for?
By looking into the OutOfMemory stack trace and the code, it seems that when PartitionedOutputOperator pulls data from HashAggregateOperator, the PartitionedOutputOperator needs to partitions each page into several pages(number of partitions) and add them to output buffer. So a lot of blocks(FixedWidthBlock, VariableWidthBlock) are buffered. is it cause the out of memory?
In my understanding, if we control the output buffer size and driver number, the memory usage will be under control, no OOM will occur. Can Presto's cluster memory management cover the memory used here?
I am not familiar with the implementation of hash join in Presto.
I appreciate anyone can help to explain it to me.
OOM stack trace:

"20160407_033922_00026_f58x8.2.26-0-76" prio=5 tid=76 RUNNABLE
        at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
        at io.airlift.slice.Slices.allocate(Slices.java:82)
        at io.airlift.slice.Slices.ensureSize(Slices.java:72)
           Local Variable: io.airlift.slice.Slice#272676
        at io.airlift.slice.DynamicSliceOutput.writeInt(DynamicSliceOutput.java:81)
        at io.airlift.slice.DynamicSliceOutput.appendInt(DynamicSliceOutput.java:171)
           Local Variable: io.airlift.slice.DynamicSliceOutput#72707
        at io.airlift.slice.DynamicSliceOutput.appendInt(DynamicSliceOutput.java:27)
        at com.facebook.presto.spi.block.VariableWidthBlockBuilder.entryAdded(VariableWidthBlockBuilder.java:187)
        at com.facebook.presto.spi.block.VariableWidthBlockBuilder.closeEntry(VariableWidthBlockBuilder.java:166)
           Local Variable: com.facebook.presto.spi.block.VariableWidthBlockBuilder#19670
        at com.facebook.presto.spi.type.VarcharType.appendTo(VarcharType.java:91)
        at com.facebook.presto.operator.PartitionedOutputOperator$PartitionFunction.partitionPage(PartitionedOutputOperator.java:231)
           Local Variable: com.facebook.presto.spi.PageBuilder#3352
           Local Variable: com.facebook.presto.operator.PartitionedOutputOperator$PartitionFunction#3
        at com.facebook.presto.operator.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:160)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:386)
           Local Variable: com.facebook.presto.operator.HashAggregationOperator#3
           Local Variable: com.facebook.presto.spi.Page#1944
           Local Variable: com.facebook.presto.operator.PartitionedOutputOperator#2
        at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
           Local Variable: com.facebook.presto.operator.Driver$DriverLockResult#19
           Local Variable: com.facebook.presto.operator.Driver#113
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
           Local Variable: com.facebook.presto.util.CpuTimer#21
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
           Local Variable: io.airlift.concurrent.SetThreadName#85
           Local Variable: com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner#150
           Local Variable: io.airlift.concurrent.SetThreadName#57
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
           Local Variable: com.facebook.presto.execution.TaskExecutor$Runner#57
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
           Local Variable: java.util.concurrent.ThreadPoolExecutor$Worker#118
        at java.lang.Thread.run(Thread.java:745)
The 20 biggest objects by retained size:
Class Name                                                                                              Retained Size
com_facebook_presto_$gen_PagesHashStrategy_88#3                        1,527,823,041
com_facebook_presto_$gen_PagesHashStrategy_88#2                        1,527,823,041
it.unimi.dsi.fastutil.objects.ObjectArrayList#44                                        822,308,077
it.unimi.dsi.fastutil.objects.ObjectArrayList#11                                        822,308,077
com.facebook.presto.spi.block.Block[]#1235                                          822,308,048
com.facebook.presto.spi.block.Block[]#180                                            822,308,048
...

From the source code, if the shared buffer is full, pages will be translated into QueuedPages and put into a unlimited BlockingQueue. Will this make the memory use out of control?

**Comment by cawallin** [comment]
@knowledgehacker That definitely shouldn't happen. If you're still facing this issue, try again on the most recent version of Presto (0.170). If you still see it, please re-open this issue.
