### ISSUE TITLE
Presto not able to query Hive Avro tables when avro schema is not stored with table

### ISSUE THREAD

**Issue by kadaan** [prestodb/presto#5009]
Presto is not able query Hive Avro tables when avro schema is not stored with table.  The issue seems to be that the shaded version of `org.apache.hadoop.hive.serde2.avro.AvroSerde` from [presto-hive-apache](https://github.com/prestodb/presto-hive-apache) tries to pass the shaded version of `com.facebook.presto.hive.$internal.org.codehaus.jackson.JsonNode` to an unshaded version of `org.apache.avro.Schema.Field` which expects `org.codehaus.jackson.JsonNode`.
### Error

```
org.apache.avro.Schema$Field.(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;Lcom/facebook/presto/hive/shaded/org/codehaus/jackson/JsonNode;)V
java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;Lcom/facebook/presto/hive/shaded/org/codehaus/jackson/JsonNode;)V
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.createAvroField(TypeInfoToSchema.java:76)
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.createAvroRecord(TypeInfoToSchema.java:203)
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.createAvroSchema(TypeInfoToSchema.java:92)
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.createAvroField(TypeInfoToSchema.java:76)
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.convert(TypeInfoToSchema.java:61)
at org.apache.hadoop.hive.serde2.avro.AvroSerDe.getSchemaFromCols(AvroSerDe.java:150)
at org.apache.hadoop.hive.serde2.avro.AvroSerDe.initialize(AvroSerDe.java:109)
at com.facebook.presto.hive.HiveUtil.initializeDeserializer(HiveUtil.java:335)
```
### Example Table

```
CREATE TABLE kst (
    string1 string,
    string2 string,
    int1 int,
    boolean1 boolean,
    long1 bigint,
    float1 float,
    double1 double,
    inner_record1 struct<int_in_inner_record1:int,string_in_inner_record1:string>,
    enum1 string,
    array1 array<string>,
    map1 map<string,string>,
    union1 uniontype<float,boolean,string>,
    fixed1 binary,
    null1 void,
    unionnullint int,
    bytes1 binary)
  PARTITIONED BY (ds string)
  STORED AS AVRO;
```

**Comment by electrum** [comment]
This should be fixed in https://github.com/prestodb/presto/pull/6370
