### ISSUE TITLE
Allow support for USE statements when using -f option for Presto CLI

### ISSUE THREAD

**Issue by akshatnair** [prestodb/presto#5027]
If you try to run a SQL script with Presto CLI using -f option and the script contains USE statement to connect to a different catalog/schema then you get an error.

`com.facebook.presto.sql.analyzer.SemanticException: line 1:1: USE statement is not supported
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitUse(StatementAnalyzer.java:468)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitUse(StatementAnalyzer.java:231)
    at com.facebook.presto.sql.tree.Use.accept(Use.java:60)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:258)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:244)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:208)
    at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
    at com.facebook.presto.execution.QueuedExecution$$Lambda$379/1196174520.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by harunurhan** [comment]
I will do this after #5038 is merged.

**Comment by ankitdixit** [comment]
Was this issue resolved in a later version, things seem to be working in presto 0.194.

**Comment by electrum** [comment]
This should be fixed. Please reopen if still an issue.
