### ISSUE TITLE
Query failed when using MAP in IN expression

### ISSUE THREAD

**Issue by geraint0923** [prestodb/presto#5279]
```
presto:tiny> select x from (values 1,2,3) t(x) where map(array[1], array[x]) in (map(array[1], array[2]));
Query 20160514_021759_00003_w3xrp failed: Compiler failed and interpreter is disabled
com.facebook.presto.spi.PrestoException: Compiler failed and interpreter is disabled
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1010)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitFilter(LocalExecutionPlanner.java:885)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitFilter(LocalExecutionPlanner.java:521)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:554)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:521)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:336)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:277)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:157)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:119)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:73)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:275)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:314)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:314)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com_facebook_presto_$gen_PageProcessor_267.filter(Lcom/facebook/presto/spi/ConnectorSession;Lcom/facebook/presto/spi/block/Block;I)Z @135: ifeq
  Reason:
    Type 'java/lang/Boolean' (current frame, stack[1]) is not assignable to integer
  Current Frame:
    bci: @135
    flags: { }
    locals: { 'com_facebook_presto_$gen_PageProcessor_267', 'com/facebook/presto/spi/ConnectorSession', 'com/facebook/presto/spi/block/Block', integer, integer }
    stack: { 'com/facebook/presto/spi/block/Block', 'java/lang/Boolean' }
  Bytecode:
    0x0000000: 0336 04ba 011e 0000 1504 9900 0857 01a7
    0x0000010: 0048 2c1d b900 1702 0099 000a 0436 0409
    0x0000020: a700 0fba 0123 0000 2c1d b900 2a03 0015
    0x0000030: 0499 000b 5801 c001 25a7 0006 b801 2903
    0x0000040: 3604 ba01 2f00 0015 0499 0009 5757 01a7
    0x0000050: 0008 ba01 3500 0015 0499 0008 5703 a700
    0x0000060: 4c59 ba01 3b00 00b8 013f ab00 0000 0029
    0x0000070: 0000 0001 0000 0003 0000 0012 59ba 0144
    0x0000080: 0000 ba01 4a00 0099 0009 a700 1300 00bf
    0x0000090: a700 0303 3605 1505 3604 a700 0b57 0336
    0x00000a0: 0404 a700 0857 03a7 0003 3606 1504 9900
    0x00000b0: 0803 ac00 00bf 1506 ac
  Stackmap Table:
    full_frame(@18,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19]})
    same_locals_1_stack_item_frame(@35,Object[#19])
    full_frame(@47,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Long})
    full_frame(@60,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Long})
    full_frame(@63,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Object[#293]})
    full_frame(@82,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Object[#19]})
    same_locals_1_stack_item_frame(@87,Object[#19])
    same_locals_1_stack_item_frame(@97,Object[#19])
    same_locals_1_stack_item_frame(@124,Object[#19])
    full_frame(@141,{},{Object[#281]})
    full_frame(@144,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19]})
    same_locals_1_stack_item_frame(@147,Object[#19])
    same_locals_1_stack_item_frame(@157,Object[#19])
    full_frame(@165,{Object[#2],Object[#73],Object[#19],Integer,Integer,Integer},{Object[#19]})
    full_frame(@170,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Integer})
    full_frame(@179,{},{Object[#281]})
    full_frame(@182,{Object[#2],Object[#73],Object[#19],Integer,Integer,Top,Integer},{})

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:99)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:997)
	... 68 more
Caused by: java.lang.RuntimeException: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com_facebook_presto_$gen_PageProcessor_267.filter(Lcom/facebook/presto/spi/ConnectorSession;Lcom/facebook/presto/spi/block/Block;I)Z @135: ifeq
  Reason:
    Type 'java/lang/Boolean' (current frame, stack[1]) is not assignable to integer
  Current Frame:
    bci: @135
    flags: { }
    locals: { 'com_facebook_presto_$gen_PageProcessor_267', 'com/facebook/presto/spi/ConnectorSession', 'com/facebook/presto/spi/block/Block', integer, integer }
    stack: { 'com/facebook/presto/spi/block/Block', 'java/lang/Boolean' }
  Bytecode:
    0x0000000: 0336 04ba 011e 0000 1504 9900 0857 01a7
    0x0000010: 0048 2c1d b900 1702 0099 000a 0436 0409
    0x0000020: a700 0fba 0123 0000 2c1d b900 2a03 0015
    0x0000030: 0499 000b 5801 c001 25a7 0006 b801 2903
    0x0000040: 3604 ba01 2f00 0015 0499 0009 5757 01a7
    0x0000050: 0008 ba01 3500 0015 0499 0008 5703 a700
    0x0000060: 4c59 ba01 3b00 00b8 013f ab00 0000 0029
    0x0000070: 0000 0001 0000 0003 0000 0012 59ba 0144
    0x0000080: 0000 ba01 4a00 0099 0009 a700 1300 00bf
    0x0000090: a700 0303 3605 1505 3604 a700 0b57 0336
    0x00000a0: 0404 a700 0857 03a7 0003 3606 1504 9900
    0x00000b0: 0803 ac00 00bf 1506 ac
  Stackmap Table:
    full_frame(@18,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19]})
    same_locals_1_stack_item_frame(@35,Object[#19])
    full_frame(@47,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Long})
    full_frame(@60,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Long})
    full_frame(@63,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Object[#293]})
    full_frame(@82,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Object[#19]})
    same_locals_1_stack_item_frame(@87,Object[#19])
    same_locals_1_stack_item_frame(@97,Object[#19])
    same_locals_1_stack_item_frame(@124,Object[#19])
    full_frame(@141,{},{Object[#281]})
    full_frame(@144,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19]})
    same_locals_1_stack_item_frame(@147,Object[#19])
    same_locals_1_stack_item_frame(@157,Object[#19])
    full_frame(@165,{Object[#2],Object[#73],Object[#19],Integer,Integer,Integer},{Object[#19]})
    full_frame(@170,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Integer})
    full_frame(@179,{},{Object[#281]})
    full_frame(@182,{Object[#2],Object[#73],Object[#19],Integer,Integer,Top,Integer},{})

	at com.facebook.presto.bytecode.CompilerUtils.defineClasses(CompilerUtils.java:148)
	at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:72)
	at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:78)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:147)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:114)
	at com.facebook.presto.sql.gen.ExpressionCompiler.access$300(ExpressionCompiler.java:46)
	at com.facebook.presto.sql.gen.ExpressionCompiler$1.load(ExpressionCompiler.java:57)
	at com.facebook.presto.sql.gen.ExpressionCompiler$1.load(ExpressionCompiler.java:52)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 74 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com_facebook_presto_$gen_PageProcessor_267.filter(Lcom/facebook/presto/spi/ConnectorSession;Lcom/facebook/presto/spi/block/Block;I)Z @135: ifeq
  Reason:
    Type 'java/lang/Boolean' (current frame, stack[1]) is not assignable to integer
  Current Frame:
    bci: @135
    flags: { }
    locals: { 'com_facebook_presto_$gen_PageProcessor_267', 'com/facebook/presto/spi/ConnectorSession', 'com/facebook/presto/spi/block/Block', integer, integer }
    stack: { 'com/facebook/presto/spi/block/Block', 'java/lang/Boolean' }
  Bytecode:
    0x0000000: 0336 04ba 011e 0000 1504 9900 0857 01a7
    0x0000010: 0048 2c1d b900 1702 0099 000a 0436 0409
    0x0000020: a700 0fba 0123 0000 2c1d b900 2a03 0015
    0x0000030: 0499 000b 5801 c001 25a7 0006 b801 2903
    0x0000040: 3604 ba01 2f00 0015 0499 0009 5757 01a7
    0x0000050: 0008 ba01 3500 0015 0499 0008 5703 a700
    0x0000060: 4c59 ba01 3b00 00b8 013f ab00 0000 0029
    0x0000070: 0000 0001 0000 0003 0000 0012 59ba 0144
    0x0000080: 0000 ba01 4a00 0099 0009 a700 1300 00bf
    0x0000090: a700 0303 3605 1505 3604 a700 0b57 0336
    0x00000a0: 0404 a700 0857 03a7 0003 3606 1504 9900
    0x00000b0: 0803 ac00 00bf 1506 ac
  Stackmap Table:
    full_frame(@18,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19]})
    same_locals_1_stack_item_frame(@35,Object[#19])
    full_frame(@47,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Long})
    full_frame(@60,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Long})
    full_frame(@63,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Object[#293]})
    full_frame(@82,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19],Object[#19]})
    same_locals_1_stack_item_frame(@87,Object[#19])
    same_locals_1_stack_item_frame(@97,Object[#19])
    same_locals_1_stack_item_frame(@124,Object[#19])
    full_frame(@141,{},{Object[#281]})
    full_frame(@144,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Object[#19]})
    same_locals_1_stack_item_frame(@147,Object[#19])
    same_locals_1_stack_item_frame(@157,Object[#19])
    full_frame(@165,{Object[#2],Object[#73],Object[#19],Integer,Integer,Integer},{Object[#19]})
    full_frame(@170,{Object[#2],Object[#73],Object[#19],Integer,Integer},{Integer})
    full_frame(@179,{},{Object[#281]})
    full_frame(@182,{Object[#2],Object[#73],Object[#19],Integer,Integer,Top,Integer},{})

	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.google.common.reflect.Reflection.initialize(Reflection.java:69)
	at com.facebook.presto.bytecode.CompilerUtils.defineClasses(CompilerUtils.java:144)
	... 85 more
```

**Comment by geraint0923** [comment]
`MapEqualOperator` returns `Boolean` while `InCodeGenerator` always assume the result is a `boolean`, and then operate `Boolean` as `boolean`.
