### ISSUE TITLE
Planning error when same subquery appears in SELECT and WHERE clause

### ISSUE THREAD

**Issue by martint** [prestodb/presto#5346]
```sql
SELECT x IN (SELECT * FROM (VALUES 1))
FROM (VALUES 2) t(x)
WHERE x IN (SELECT * FROM (VALUES 1))
```

fails with 

```
java.lang.IllegalArgumentException: Invalid node. Expression dependencies ([field, field_1]) not in source plan output ([field, semijoin_result])

	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:564)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.access$100(ValidateDependenciesChecker.java:71)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:248)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:80)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:291)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:80)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:77)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:35)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:35)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:105)
	at com.facebook.presto.testing.LocalQueryRunner.createPlan(LocalQueryRunner.java:583)
    ...
```

We've bisected it to this commit b5d8bf55da276e55a7be4b43e5c275ea2eb21193

**Comment by martint** [comment]
@kokosing, can you take a look?

**Comment by kokosing** [comment]
Sure... I am sorry for introducing this bug. I am going to fix this immediately.

**Comment by christingh** [comment]
visitProject(ValidateDependenciesChecker.java:248)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:80)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:291)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:80)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java
