### ISSUE TITLE
PrestoS3FileSystem presto.s3.encryption-materials-provider cannot accept StaticEncryptionMaterialsProvider

### ISSUE THREAD

**Issue by renxiawang** [prestodb/presto#5436]
I am running Presto on EMR and trying to use the EMR default KMS encryption provider in Presto but ran into issues. 

The EMR default one is ```com.amazon.ws.emr.hadoop.fs.cse.KMSEncryptionMaterialsProvider```, which extends ```com.amazonaws.services.s3.model.StaticEncryptionMaterialsProvider```. 

I set ```presto.s3.encryption-materials-provider=com.amazon.ws.emr.hadoop.fs.cse.KMSEncryptionMaterialsProvider```. But ```PrestoS3FileSystem``` is expecting ```com.amazonaws.services.s3.model.EncryptionMaterialsProvider```. Thus, it throws the following exception.

Will be nice if PrestoS3FileSystem can also support the StaticEncryptionMaterialsProvider, that will make people running Presto on EMR with KMS easier. 

```
com.facebook.presto.spi.PrestoException: Invalid encryption materials provider class: com.amazon.ws.emr.hadoop.fs.cse.KMSEncryptionMaterialsProvider
        at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:145)
        at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:123)
        at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:62)
        at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:114)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:332)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Invalid encryption materials provider class: com.amazon.ws.emr.hadoop.fs.cse.KMSEncryptionMaterialsProvider
        at com.facebook.presto.hive.PrestoS3FileSystem.createEncryptionMaterialsProvider(PrestoS3FileSystem.java:624)
        at com.facebook.presto.hive.PrestoS3FileSystem.createAmazonS3Client(PrestoS3FileSystem.java:594)
        at com.facebook.presto.hive.PrestoS3FileSystem.initialize(PrestoS3FileSystem.java:188)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:74)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:53)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:298)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:210)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:68)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:166)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
        at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$46(ResumableTasks.java:33)
        at io.airlift.concurrent.BoundedExecutor.executeOrMerge(BoundedExecutor.java:69)
```

**Comment by nezihyigitbasi** [comment]
I see that in the aws sdk version Presto currently depends on (v 1.9.40) the fully classified class name for `KMSEncryptionMaterialsProvider` is  `com.amazonaws.services.s3.model.KMSEncryptionMaterialsProvider`. Can you try setting this name in your config?

**Comment by renxiawang** [comment]
Thanks @nezihyigitbasi, but it is not working with com.amazonaws.services.s3.model.KMSEncryptionMaterialsProvider. 

```
com.facebook.presto.spi.PrestoException: Unable to load or create S3 encryption materials provider: com.amazonaws.services.s3.model.KMSEnc
ryptionMaterialsProvider
        at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:145)
        at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:123)
        at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:62)
        at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:114)
        at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:332)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to load or create S3 encryption materials provider: com.amazonaws.services.s3.model.KMSEncry
ptionMaterialsProvider
        at com.facebook.presto.hive.PrestoS3FileSystem.createEncryptionMaterialsProvider(PrestoS3FileSystem.java:633)
ptionMaterialsProvider
        at com.facebook.presto.hive.PrestoS3FileSystem.createEncryptionMaterialsProvider(PrestoS3FileSystem.java:633)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Unable to load or create S3 encryption materials provider: com.amazonaws.services.s3.model.KMSEncry
ptionMaterialsProvider
        at com.facebook.presto.hive.PrestoS3FileSystem.createEncryptionMaterialsProvider(PrestoS3FileSystem.java:633)
        at com.facebook.presto.hive.PrestoS3FileSystem.createAmazonS3Client(PrestoS3FileSystem.java:594)
        at com.facebook.presto.hive.PrestoS3FileSystem.initialize(PrestoS3FileSystem.java:188)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:74)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at com.facebook.presto.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:53)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:298)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:210)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:68)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:166)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
        at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$46(ResumableTasks.java:33)
        at io.airlift.concurrent.BoundedExecutor.executeOrMerge(BoundedExecutor.java:69)
        at io.airlift.concurrent.BoundedExecutor.access$000(BoundedExecutor.java:28)
        at io.airlift.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:40)
        ... 3 more
Caused by: java.lang.NoSuchMethodException: com.amazonaws.services.s3.model.KMSEncryptionMaterialsProvider.<init>()
        at java.lang.Class.getConstructor0(Class.java:3082)
        at java.lang.Class.getConstructor(Class.java:1825)
        at com.facebook.presto.hive.PrestoS3FileSystem.createEncryptionMaterialsProvider(PrestoS3FileSystem.java:622)
        ... 20 more
```

**Comment by nezihyigitbasi** [comment]
I see that some of the encryption materials provider classes take an `EncryptionMaterials` to their constructors, and Presto doesn't pass that and simply tries to use the default constructors, which don't exist for many of these providers. So properly supporting `KMSEncryptionMaterialsProvider` seems to require code change.

**Comment by nezihyigitbasi** [comment]
@natesammons-nasdaq can you think of a simple workaround for this one?

**Comment by natesammons-nasdaq** [comment]
I will look into this.  If they just want to use the AWS KMS, probably the easiest thing to do would be to make a new EMP implementation that reads a KMS key ID from the hadoop properties system and then creates an EMP instance.  I can easily make these changes if you'd like.

**Comment by natesammons-nasdaq** [comment]
Thoughts?  AWS KMS is now widely used and I think it makes sense to have additional config for it.  Instead of setting presto.s3.encryption-materials-provider, I think we should add presto.s3.kms-key-id and if that's set, don't use a custom encryption materials provider and instead setup the KMS provider.  This would be a special case but since KMS is so widely used I think it makes sense.

**Comment by natesammons-nasdaq** [comment]
I've made these changes on a local branch, it's very simple:

https://github.com/prestodb/presto/commit/6acb12bdc4e4c08978aed5c5220681a65faa272e

**Comment by natesammons-nasdaq** [comment]
I created a PR for this:  https://github.com/prestodb/presto/pull/5701

**Comment by natesammons-nasdaq** [comment]
As a side note, I think some docs on the S3 integration would be good.  I'm happy to contribute, is there a suggested place?  I almost think it belongs in the hive-security.rst file?

**Comment by electrum** [comment]
That seems fine. We can reorganize the content later if needed.

**Comment by natesammons-nasdaq** [comment]
OK, cool.  I updated the hive docs to add notes about each S3 config and some commentary about encryption settings, etc.  Updated the above PR
