### ISSUE TITLE
Client gets hard fail when query had a normal max memory error

### ISSUE THREAD

**Issue by dain** [prestodb/presto#5437]
Verifier log
```
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	----------
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	Name: </cut>
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	Schema (control): </cut>
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	Schema (test): </cut>
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	Valid: false
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	Query (test):  </cut>
19:50:44 2016-06-11T19:50:44.445-0700	INFO	main	stdout	
19:50:44 Error message:
19:50:44 Test state FAILED, Control state SUCCESS
19:50:44 java.lang.RuntimeException: Error fetching next at http://</cut>:7777/v1/statement/20160612_023612_01126_684br/13153 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={Content-Length=[5363], Date=[Sun, 12 Jun 2016 02:50:44 GMT], Content-Type=[text/plain]}, hasValue=false, value=null} [Error: java.util.NoSuchElementException
19:50:44 	at com.facebook.presto.execution.SqlQueryManager.getQueryInfo(SqlQueryManager.java:243)
19:50:44 	at com.facebook.presto.server.StatementResource$Query.getData(StatementResource.java:475)
19:50:44 	at com.facebook.presto.server.StatementResource$Query.getNextResults(StatementResource.java:387)
19:50:44 	at com.facebook.presto.server.StatementResource$Query.getResults(StatementResource.java:381)
19:50:44 	at com.facebook.presto.server.StatementResource.getQueryResults(StatementResource.java:201)
19:50:44 	at com.facebook.presto.server.StatementResource.getQueryResults(StatementResource.java:193)
....
	at com.facebook.presto.jdbc.internal.client.StatementClient.requestFailedException(StatementClient.java:344)
	at com.facebook.presto.jdbc.internal.client.StatementClient.advance(StatementClient.java:294)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1805)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1781)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$5.hasNext(Iterators.java:547)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:166)
	at com.facebook.presto.verifier.Validator.convertJdbcResultSet(Validator.java:520)
	at com.facebook.presto.verifier.Validator.lambda$getResultSetConverter$4(Validator.java:494)
```

Coordinator log:
```
2016-06-11T19:26:43.839-0700    DEBUG   query-execution-175     com.facebook.presto.execution.QueryStateMachine Query 20160612_022643_01058_684br is PLANNING
2016-06-11T19:26:44.090-0700    DEBUG   query-execution-175     com.facebook.presto.execution.QueryStateMachine Query 20160612_022643_01058_684br is STARTING
2016-06-11T19:26:44.090-0700    DEBUG   query-execution-175     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.0 is SCHEDULING
2016-06-11T19:26:44.090-0700    DEBUG   query-execution-175     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.0 is SCHEDULED
2016-06-11T19:26:44.090-0700    DEBUG   query-execution-185     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.1 is SCHEDULING
2016-06-11T19:26:44.091-0700    DEBUG   query-execution-179     com.facebook.presto.execution.QueryStateMachine Query 20160612_022643_01058_684br is RUNNING
2016-06-11T19:26:44.092-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.0 is RUNNING
2016-06-11T19:26:44.094-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.1 is SCHEDULED
2016-06-11T19:26:44.094-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.1 is RUNNING
2016-06-11T19:26:44.095-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.2 is SCHEDULING
2016-06-11T19:26:44.098-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.2 is SCHEDULED
2016-06-11T19:26:44.101-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.2 is RUNNING
2016-06-11T19:26:44.102-0700    DEBUG   query-execution-179     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.4 is SCHEDULING
...
2016-06-11T19:28:37.946-0700    DEBUG   query-execution-188     com.facebook.presto.execution.QueryStateMachine Query 20160612_022643_01058_684br is FAILED
2016-06-11T19:28:37.946-0700    DEBUG   query-management-2      com.facebook.presto.execution.QueryStateMachine Query 20160612_022643_01058_684br failed
com.facebook.presto.ExceededMemoryLimitException: Query exceeded max memory size of 300GB
        at com.facebook.presto.ExceededMemoryLimitException.exceededGlobalLimit(ExceededMemoryLimitException.java:29)
        at com.facebook.presto.memory.ClusterMemoryManager.process(ClusterMemoryManager.java:170)
        at com.facebook.presto.execution.SqlQueryManager.enforceMemoryLimits(SqlQueryManager.java:410)
        at com.facebook.presto.execution.SqlQueryManager$1.run(SqlQueryManager.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


2016-06-11T19:28:37.946-0700    DEBUG   query-execution-168     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.0 is ABORTED
2016-06-11T19:28:37.946-0700    DEBUG   query-execution-183     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.1 is CANCELED
2016-06-11T19:28:37.946-0700    DEBUG   query-execution-184     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.2 is CANCELED
2016-06-11T19:28:37.946-0700    DEBUG   query-execution-185     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.3 is CANCELED
2016-06-11T19:28:37.946-0700    DEBUG   query-execution-189     com.facebook.presto.execution.StageStateMachine Stage 20160612_022643_01058_684br.4 is CANCELED
2016-06-11T19:28:37.965-0700    INFO    query-execution-188     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20160612_022643_01058_684br :: Transaction:[b22b9de3-28aa-43c2-bc91-bebe3dde3648] :: elapsed 114107.00ms :: planning 251.68ms :: scheduling 62.00ms :: running 0.00ms :: finishing 113855.00ms :: begin 2016-06-11T19:26:43.838-07:00 :: end 2016-06-11T19:28:37.945-07:00
2016-06-11T19:28:38.038-0700    DEBUG   exchange-client-13      com.facebook.presto.operator.HttpPageBufferClient       Request to http://[2401:db00:20:b1bb:face:0:23:0]:7777/v1/task/20160612_022643_01058_684br.0.0/results/output.buffer.id/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-06-11T19:28:38.039-0700    ERROR   exchange-client-11      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://[2401:db00:20:b1bb:face:0:23:0]:7777/v1/task/20160612_022643_01058_684br.0.0/results/output.buffer.id failed java.util.concurrent.CancellationException: Task was cancelled.
```

**Comment by dain** [comment]
Here is another one which has the ERROR message `taskStatus done but taskInfo is not`:

verifier log:
```
9:08:32 2016-06-11T19:08:32.810-0700	INFO	main	stdout	Name: </cut>
19:08:32 2016-06-11T19:08:32.810-0700	INFO	main	stdout	Schema (control): </cut>
19:08:32 2016-06-11T19:08:32.810-0700	INFO	main	stdout	Schema (test): </cut>
19:08:32 2016-06-11T19:08:32.810-0700	INFO	main	stdout	Valid: false
19:08:32 2016-06-11T19:08:32.810-0700	INFO	main	stdout	Query (test): </cut>
19:08:32 2016-06-11T19:08:32.810-0700	INFO	main	stdout	
19:08:32 Error message:
19:08:32 Test state FAILED, Control state SUCCESS
19:08:32 java.lang.RuntimeException: Error fetching next at http:/</cut>:7777/v1/statement/20160612_015813_00805_684br/7258 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={Content-Length=[5363], Date=[Sun, 12 Jun 2016 02:08:32 GMT], Content-Type=[text/plain]}, hasValue=false, value=null} [Error: java.util.NoSuchElementException
19:08:32 	at com.facebook.presto.execution.SqlQueryManager.getQueryInfo(SqlQueryManager.java:243)
19:08:32 	at com.facebook.presto.server.StatementResource$Query.getData(StatementResource.java:475)
19:08:32 	at com.facebook.presto.server.StatementResource$Query.getNextResults(StatementResource.java:387)
19:08:32 	at com.facebook.presto.server.StatementResource$Query.getResults(StatementResource.java:381)
19:08:32 	at com.facebook.presto.server.StatementResource.getQueryResults(StatementResource.java:201)
19:08:32 	at com.facebook.presto.server.StatementResource.getQueryResults(StatementResource.java:193)
19:08:32 	at sun.reflect.GeneratedMethodAccessor694.invoke(Unknown Source)
19:08:32 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:08:32 	at java.lang.reflect.Method.invoke(Method.java:498)
19:08:32 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
19:08:32 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
19:08:32 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
19:08:32 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
19:08:32 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
19:08:32 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
19:08:32 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
19:08:32 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
19:08:32 	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
19:08:32 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
19:08:32 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
19:08:32 	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
19:08:32 	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
19:08:32 	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
19:08:32 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
19:08:32 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
19:08:32 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
19:08:32 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
19:08:32 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
19:08:32 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
19:08:32 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
19:08:32 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
19:08:32 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
19:08:32 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
19:08:32 	at com.facebook.presto.server.security.SpnegoFilter.doFilter(SpnegoFilter.java:136)
19:08:32 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
19:08:32 	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
19:08:32 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
19:08:32 	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
19:08:32 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
19:08:32 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
19:08:32 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
19:08:32 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:386)
19:08:32 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1176)
19:08:32 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
19:08:32 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
19:08:32 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
19:08:32 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
19:08:32 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
19:08:32 	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
19:08:32 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
19:08:32 	at org.eclipse.jetty.server.Server.handle(Server.java:518)
19:08:32 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:314)
19:08:32 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
19:08:32 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
19:08:32 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
19:08:32 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
19:08:32 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
19:08:32 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
19:08:32 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
19:08:32 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
19:08:32 	at java.lang.Thread.run(Thread.java:745)
19:08:32 ]
19:08:32 	at com.facebook.presto.jdbc.internal.client.StatementClient.requestFailedException(StatementClient.java:344)
19:08:32 	at com.facebook.presto.jdbc.internal.client.StatementClient.advance(StatementClient.java:294)
19:08:32 	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1805)
19:08:32 	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1781)
19:08:32 	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
19:08:32 	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
19:08:32 	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
19:08:32 	at com.facebook.presto.jdbc.internal.guava.collect.Iterators$5.hasNext(Iterators.java:547)
19:08:32 	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:166)
19:08:32 	at com.facebook.presto.verifier.Validator.convertJdbcResultSet(Validator.java:520)
19:08:32 	at com.facebook.presto.verifier.Validator.lambda$getResultSetConverter$4(Validator.java:494)
19:08:32 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:08:32 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
19:08:32 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
19:08:32 	at java.lang.Thread.run(Thread.java:745)
```

coordinator log:
```
2016-06-11T18:58:14.627-0700    DEBUG   query-execution-128     com.facebook.presto.execution.QueryStateMachine Query 20160612_015813_00805_684br is STARTING
2016-06-11T18:58:14.627-0700    DEBUG   query-execution-128     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.2 is SCHEDULING
2016-06-11T18:58:14.631-0700    DEBUG   query-execution-128     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.2 is SCHEDULED
2016-06-11T18:58:14.631-0700    DEBUG   query-execution-153     com.facebook.presto.execution.QueryStateMachine Query 20160612_015813_00805_684br is RUNNING
2016-06-11T18:58:14.631-0700    DEBUG   query-execution-128     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.4 is SCHEDULING
2016-06-11T18:58:14.631-0700    DEBUG   query-execution-150     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.2 is RUNNING
2016-06-11T18:58:14.634-0700    DEBUG   query-execution-150     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.4 is SCHEDULED
2016-06-11T18:58:14.634-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.4 is RUNNING
2016-06-11T18:58:14.634-0700    DEBUG   query-execution-150     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.8 is SCHEDULING
2016-06-11T18:58:14.634-0700    DEBUG   query-execution-150     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.0 is SCHEDULING
2016-06-11T18:58:14.635-0700    DEBUG   query-execution-150     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.0 is SCHEDULED
2016-06-11T18:58:14.635-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.1 is SCHEDULING
2016-06-11T18:58:14.641-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.0 is RUNNING
2016-06-11T18:58:14.642-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.1 is SCHEDULED
2016-06-11T18:58:14.642-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.1 is RUNNING
2016-06-11T18:58:14.642-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.3 is SCHEDULING
2016-06-11T18:58:14.649-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.3 is SCHEDULED
2016-06-11T18:58:14.650-0700    DEBUG   query-execution-153     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.3 is RUNNING
...
2016-06-11T19:00:31.204-0700    DEBUG   query-execution-160     com.facebook.presto.execution.QueryStateMachine Query 20160612_015813_00805_684br is FAILED
2016-06-11T19:00:31.204-0700    DEBUG   query-management-4      com.facebook.presto.execution.QueryStateMachine Query 20160612_015813_00805_684br failed
com.facebook.presto.ExceededMemoryLimitException: Query exceeded max memory size of 300GB
        at com.facebook.presto.ExceededMemoryLimitException.exceededGlobalLimit(ExceededMemoryLimitException.java:29)
        at com.facebook.presto.memory.ClusterMemoryManager.process(ClusterMemoryManager.java:170)
        at com.facebook.presto.execution.SqlQueryManager.enforceMemoryLimits(SqlQueryManager.java:410)
        at com.facebook.presto.execution.SqlQueryManager$1.run(SqlQueryManager.java:150)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


2016-06-11T19:00:31.204-0700    DEBUG   query-execution-158     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.0 is ABORTED
2016-06-11T19:00:31.204-0700    DEBUG   query-execution-159     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.1 is CANCELED
2016-06-11T19:00:31.204-0700    DEBUG   query-execution-154     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.2 is CANCELED
2016-06-11T19:00:31.204-0700    DEBUG   query-execution-161     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.3 is CANCELED
2016-06-11T19:00:31.205-0700    DEBUG   query-execution-162     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.4 is CANCELED
2016-06-11T19:00:31.205-0700    DEBUG   query-execution-163     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.5 is CANCELED
2016-06-11T19:00:31.205-0700    DEBUG   query-execution-164     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.8 is CANCELED
2016-06-11T19:00:31.205-0700    DEBUG   query-execution-164     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.7 is CANCELED
2016-06-11T19:00:31.205-0700    DEBUG   query-execution-165     com.facebook.presto.execution.StageStateMachine Stage 20160612_015813_00805_684br.6 is CANCELED
2016-06-11T19:00:31.244-0700    INFO    query-execution-160     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20160612_015813_00805_684br :: Transaction:[09495713-427b-4006-943f-d66301df5d0b] :: elapsed 137797.00ms ::
 planning 1.22s :: scheduling 79.00ms :: running 0.00ms :: finishing 136578.00ms :: begin 2016-06-11T18:58:13.407-07:00 :: end 2016-06-11T19:00:31.204-07:00
2016-06-11T19:00:31.338-0700    DEBUG   exchange-client-8       com.facebook.presto.operator.HttpPageBufferClient       Request to http://[2401:db00:20:b1be:face:0:21:0]:7777/v1/task/20160612_015813_00805_684br.0.0/results/output.buffe
r.id/0 failed java.util.concurrent.CancellationException: Task was cancelled.
2016-06-11T19:00:31.338-0700    ERROR   exchange-client-6       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://[2401:db00:20:b1be:face:0:21:0]:7777/v1/task/20160612_015813_00805_684br.0.0/results/outpu
t.buffer.id failed java.util.concurrent.CancellationException: Task was cancelled.
2016-06-11T19:00:31.365-0700    ERROR   TaskInfoFetcher-20160612_015813_00805_684br.3.1-61821   com.facebook.presto.server.remotetask.TaskInfoFetcher   20160612_015813_00805_684br.3.1 taskStatus done but taskInfo is not
```

**Comment by dain** [comment]
@nileema fixed this
