### ISSUE TITLE
Insert into Hive partitioned table query failure

### ISSUE THREAD

**Issue by stagraqubole** [prestodb/presto#5456]
Insert into fails in following scenario:
1. Insert into a non-existing partition P of table X, this works fine
2. Insert again into partition P of table X, this fails with exception:

```
com.facebook.presto.spi.TableNotFoundException: Table 'default.X' not found
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.addPartitions(CachingHiveMetastore.java:656)
        at com.facebook.presto.hive.HiveMetadata$PartitionCommitter.addBatch(HiveMetadata.java:728)
        at com.facebook.presto.hive.HiveMetadata$PartitionCommitter.flush(HiveMetadata.java:709)
        at com.facebook.presto.hive.HiveMetadata.finishInsert(HiveMetadata.java:806)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.finishInsert(ClassLoaderSafeConnectorMetadata.java:225)
        at com.facebook.presto.metadata.MetadataManager.finishInsert(MetadataManager.java:544)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$1.finishTable(LocalExecutionPlanner.java:1908)
        at com.facebook.presto.operator.TableFinishOperator.getOutput(TableFinishOperator.java:156)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

This happens because with query1 worker node does negative caching of partition P. When query2 comes, it fetches stale data for P and returns P as new partition in partition update.

Simple workaround is to disable metastore caching in worker nodes.

**Comment by sayap** [comment]
I got the same error in the exact scenario. For the workaround (thanks!), does the following equal to disabling metastore caching?

    hive.metastore-cache-ttl=1s
    hive.metastore-refresh-interval=1s

The worker nodes can't start if I set them to `0s`, with error `duration must be positive: 0 MILLISECONDS`. Setting them to `1s` works for me.

**Comment by stagraqubole** [comment]
This much is enough to disable the cache:
```
hive.metastore-cache-ttl=0s
```

Leave `hive.metastore-refresh-interval` to be non-zero.
The config you mentioned should also work, it wouldnt disable the cache but it reduces the chances of hitting this issue by invalidating cache much faster.
