### ISSUE TITLE
GROUPING SETS over UNION fails

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#5498]
The following query:
```
SELECT x, COUNT(DISTINCT x) AS c
   FROM
     (
     SELECT *
     FROM (values (1)) t(x)
     UNION ALL
     SELECT *
     FROM (values (1)) t(x)
     ) t2
   GROUP BY GROUPING SETS ((x), ())
```

fails with:
```
Query 20160622_013115_00003_u5amn failed: index (0) must be less than size (0)
java.lang.IndexOutOfBoundsException: index (0) must be less than size (0)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:310)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:292)
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:65)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:1104)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitUnion(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.UnionNode.accept(UnionNode.java:139)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1143)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:215)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitPlan(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitGroupId(PlanVisitor.java:150)
	at com.facebook.presto.sql.planner.plan.GroupIdNode.accept(GroupIdNode.java:125)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1143)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:283)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:189)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1143)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:231)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1143)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:283)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitAggregation(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:189)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1143)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:231)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitProject(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1143)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:237)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:188)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:150)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:100)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:277)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:256)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:220)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by raghavsethi** [comment]
Might be related to #5439. I'm investigating.

**Comment by raghavsethi** [comment]
This was unearthed by the unholy interaction of SingleDistinctOptimizer, the recent union partitioning changes, AddLocalExchanges, and the passthrough changes to GroupId made as a result of the grouping on aggregation arguments bug. Still trying to figure out how to fix it.
