### ISSUE TITLE
Test fails for presto-redis

### ISSUE THREAD

**Issue by ArchaB** [prestodb/presto#5548]
When i try to build presto-redis, the testcases fail with a Connection refused exception.

Forking command line: 

```
/bin/sh -c cd /root/presto_redis/prestodb/presto/presto-redis && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el7_2.ppc64le/jre/bin/java -Duser.timezone=Asia/Katmandu -Xmx2g -Xms2g '-XX:OnOutOfMemoryError=kill -9 %p' -XX:+HeapDumpOnOutOfMemoryError -jar /root/presto_redis/prestodb/presto/presto-redis/target/surefire/surefirebooter1622780572342227627.jar /root/presto_redis/prestodb/presto/presto-redis/target/surefire/surefire6816665342627903538tmp /root/presto_redis/prestodb/presto/presto-redis/target/surefire/surefire_02057310190638461869tmp
```

Failure seen on console. 

```
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test (default-test) on project presto-redis: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test failed: There was an error in the forked process
org.testng.TestNGException: 
Cannot instantiate class com.facebook.presto.redis.TestRedisIntegrationSmokeTest
    at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:38)
    at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:380)
    at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:293)
    at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:115)
    .
    .
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
    ... 29 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at com.facebook.presto.redis.util.RedisLoader$RedisLoadingSession.addResults(RedisLoader.java:110)
    at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:91)
    .
    .
    at com.facebook.presto.redis.TestRedisIntegrationSmokeTest.<init>(TestRedisIntegrationSmokeTest.java:43)
    at com.facebook.presto.redis.TestRedisIntegrationSmokeTest.<init>(TestRedisIntegrationSmokeTest.java:37)
    ... 34 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
    at redis.clients.jedis.Connection.connect(Connection.java:148)
    at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
    .
    .
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at redis.clients.jedis.Connection.connect(Connection.java:142)
    ... 51 more
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test failed: There was an error in the forked process
org.testng.TestNGException: 
Cannot instantiate class com.facebook.presto.redis.TestRedisIntegrationSmokeTest
    at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:38)
    at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:380)
    .
    .
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
    ... 29 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at com.facebook.presto.redis.util.RedisLoader$RedisLoadingSession.addResults(RedisLoader.java:110)
    at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:91)
    .
    .
    at com.facebook.presto.redis.TestRedisIntegrationSmokeTest.<init>(TestRedisIntegrationSmokeTest.java:43)
    at com.facebook.presto.redis.TestRedisIntegrationSmokeTest.<init>(TestRedisIntegrationSmokeTest.java:37)
    ... 34 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
    at redis.clients.jedis.Connection.connect(Connection.java:148)
    at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
    .
    .
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    .
    .
Caused by: java.lang.RuntimeException: There was an error in the forked process
org.testng.TestNGException: 
Cannot instantiate class com.facebook.presto.redis.TestRedisIntegrationSmokeTest
    at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:38)
    at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:380)
    .
    .
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    .
    .
    at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
    ... 29 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
    at redis.clients.util.Pool.getResource(Pool.java:50)
    at redis.clients.jedis.JedisPool.getResource(JedisPool.java:88)
    at com.facebook.presto.redis.util.RedisLoader$RedisLoadingSession.addResults(RedisLoader.java:110)
    .
    .
    at com.facebook.presto.redis.TestRedisIntegrationSmokeTest.<init>(TestRedisIntegrationSmokeTest.java:43)
    at com.facebook.presto.redis.TestRedisIntegrationSmokeTest.<init>(TestRedisIntegrationSmokeTest.java:37)
    ... 34 more
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused
    at redis.clients.jedis.Connection.connect(Connection.java:148)
    at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:75)
    .
    .
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    .
    .
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:701)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:629)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 12 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Any pointer will be really helpful.

**Comment by electrum** [comment]
The `embedded-redis` that is used for testing doesn't have a Redis binary for PPC64LE. We should switch to https://github.com/kstyrc/embedded-redis and ask them to add a binary for that version.

**Comment by kstyrc** [comment]
Could somebody confirm that I can use the following RPMs for all Linux distros on PPC64 and PPC64LE? 

```
> rpm2cpio ../redis-2.8.19-1.fc22.1.ppc64.rpm | cpio -idmv
/etc/logrotate.d/redis
./etc/redis-sentinel.conf
./etc/redis.conf
./etc/systemd/system/redis-sentinel.service.d
./etc/systemd/system/redis-sentinel.service.d/limit.conf
./etc/systemd/system/redis.service.d
./etc/systemd/system/redis.service.d/limit.conf
./usr/bin/redis-benchmark
./usr/bin/redis-check-aof
./usr/bin/redis-check-dump
./usr/bin/redis-cli
./usr/bin/redis-sentinel
./usr/bin/redis-server
./usr/bin/redis-shutdown
./usr/lib/systemd/system/redis-sentinel.service
./usr/lib/systemd/system/redis.service
./usr/lib/tmpfiles.d/redis.conf
./usr/share/doc/redis
./usr/share/doc/redis/00-RELEASENOTES
./usr/share/doc/redis/BUGS
./usr/share/doc/redis/CONTRIBUTING
./usr/share/doc/redis/MANIFESTO
./usr/share/doc/redis/README
./usr/share/licenses/redis
./usr/share/licenses/redis/COPYING
./var/lib/redis
./var/log/redis
./var/run/redis
```

I only need /usr/bin/redis-server binary

**Comment by ArchaB** [comment]
Opened new issue for embedded-redis. Closing this one
