### ISSUE TITLE
REMOTE_TASK_MISMATCH on a simple query

### ISSUE THREAD

**Issue by tesseract2048** [prestodb/presto#5570]
I've encountered this issue during tests on 0.149:

SQL:

```
SELECT table_name FROM information_schema.tables WHERE table_schema = 'default'
```

Error Information
Error Type  INTERNAL_ERROR
Error Code  REMOTE_TASK_MISMATCH (65544)
Stack Trace 

```
com.facebook.presto.spi.PrestoException: Could not communicate with the remote task. The node may have crashed or be under too much load. This is probably a transient issue, so please retry your query in a few minutes.
    at com.facebook.presto.server.remotetask.ContinuousTaskStatusFetcher.updateTaskStatus(ContinuousTaskStatusFetcher.java:234)
    at com.facebook.presto.server.remotetask.ContinuousTaskStatusFetcher.success(ContinuousTaskStatusFetcher.java:168)
    at com.facebook.presto.server.remotetask.ContinuousTaskStatusFetcher.success(ContinuousTaskStatusFetcher.java:52)
    at com.facebook.presto.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:49)
    at com.facebook.presto.server.remotetask.SimpleHttpResponseHandler.onSuccess(SimpleHttpResponseHandler.java:27)
    at com.google.common.util.concurrent.Futures$6.run(Futures.java:1319)
    at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:77)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Any idea? Thanks.

**Comment by delbao** [comment]
+1 same here

**Comment by ayush-chauhan** [comment]
Have you found the solution or any workaround for this error?

**Comment by dain** [comment]
REMOTE_TASK_MISMATCH means the process restarted.  The other errors are general communication errors that typically mean the machine had a very long GC or was generally unreachable for a long time.

**Comment by dain** [comment]
BTW, make sure you are running a recent release.
