### ISSUE TITLE
Some queries with varchar(n) fail

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#5630]
Unfortunately, I don't have a good repro that I can share publically. @geraint0923  please see the internal task I filed

```
Query 20160712_160542_00845_kqp2p failed: type of symbol 'expr_249' is expected to be varchar, but the actual type is varchar(3)
java.lang.IllegalArgumentException: type of symbol 'expr_249' is expected to be varchar, but the actual type is varchar(3)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.verifyTypeSignature(TypeValidator.java:161)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:116)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:56)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:106)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:56)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:170)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:208)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitJoin(PlanVisitor.java:90)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:170)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:106)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:56)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:170)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:208)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitTableWriter(PlanVisitor.java:115)
	at com.facebook.presto.sql.planner.plan.TableWriterNode.accept(TableWriterNode.java:127)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:170)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:208)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitTableFinish(PlanVisitor.java:130)
	at com.facebook.presto.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:80)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:53)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:42)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:42)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:109)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:280)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:259)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:223)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by geraint0923** [comment]
Seems like a planner bug, after temporarily disabling all the optimizers:
```
presto:di> create table test_yangy_001 (id bigint, val varchar);

presto:di> explain select val w from test_yangy_001 where id=0 union all select 'web' w from test_yangy_001;
                                                                   Query Plan
-------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[w] => [expr_8:varchar]
         w := expr_8
     - Project => [expr_8:varchar]
             expr_8 := "expr_7"
         - Project => [expr_7:varchar]
                 expr_7 := "val_6"
             - Union => [val_6:varchar]
                 - Project => [val_1:varchar]
                         val_1 := "val_0"
                     - Project => [val_0:varchar]
                             val_0 := "val"
                         - Filter[("id" = CAST(0 AS BIGINT))] => [id:bigint, val:varchar]
                             - TableScan[prism:diprism:di:test_yangy_001, originalConstraint = null] => [id:bigint, val:varchar]
                                     id := HiveColumnHandle{clientId=prism, name=id, hiveType=bigint, hiveColumnIndex=0, partitionKey=false}
                                     val := HiveColumnHandle{clientId=prism, name=val, hiveType=string, hiveColumnIndex=1, partitionKey=false}
                 - Project => [expr_5:varchar]
                         expr_5 := "expr_4"      <=============== assign varchar(3) to varchar
                     - Project => [expr_4:varchar(3)]
                             expr_4 := "expr"
                         - Project => [expr:varchar(3)]
                                 expr := 'web'
                             - TableScan[prism:diprism:di:test_yangy_001, originalConstraint = null] => [id_2:bigint, val_3:varchar]
                                     id_2 := HiveColumnHandle{clientId=prism, name=id, hiveType=bigint, hiveColumnIndex=0, partitionKey=false}
                                     val_3 := HiveColumnHandle{clientId=prism, name=val, hiveType=string, hiveColumnIndex=1, partitionKey=false}
```

I am finding the problematic place.

**Comment by geraint0923** [comment]
I disabled all the optimizers and plan sanity checkers, and finally simplified the problematic query:
```
presto:tiny> explain select cast('web' as varchar) union all select 'web' w;
                         Query Plan
------------------------------------------------------------
 - Output[_col0] => [expr_6:varchar]
         _col0 := expr_6
     - Project => [expr_6:varchar]
             expr_6 := "expr_5"
         - Project => [expr_5:varchar]
                 expr_5 := "expr_4"
             - Union => [expr_4:varchar]
                 - Project => [expr_0:varchar]
                         expr_0 := "expr"
                     - Project => [expr:varchar]
                             expr := CAST('web' AS VARCHAR)
                         - Values => []
                                 ()
                 - Project => [expr_3:varchar]
                         expr_3 := "expr_2"       <==== assign "expr_2"(varchar(3)) to "expr_3"(varchar) without using CAST
                     - Project => [expr_2:varchar(3)]
                             expr_2 := "expr_1"
                         - Project => [expr_1:varchar(3)]
                                 expr_1 := 'web'
                             - Values => []
                                     ()
```
This is caused by:
1. https://github.com/prestodb/presto/blob/344b24653dff58c6986ec13ba6a6623d698a00dd/presto-main/src/main/java/com/facebook/presto/sql/planner/RelationPlanner.java#L531 
and
2. https://github.com/prestodb/presto/blob/dfa16d9b104ae8f117e6a2335dae4da5ef83e913/presto-main/src/main/java/com/facebook/presto/type/TypeRegistry.java#L194
in which `isTypeOnlyCoercion` considers coercion from `varchar(3)` to `varchar` is type only coercion and then there is no explicit CAST inserted, which leads to a type mismatch in `TypeValidator`.

@martint @cberner 

If coercion from `varchar(n)` to `varchar` without explicitly using CAST is valid, then I need to update `TypeValidator` to allow this case.
