### ISSUE TITLE
VARCHAR(n) and var-args functions

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#5671]
The following queries fails.

```
SELECT * FROM (
  SELECT concat (t.x, t.z) cc from (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) t(x, z)
  ) t
  JOIN (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) u(x, z)
    WHERE z='c' --split_part('b.c', '.', 2)
  ) u
  ON t.z = u.z
)
WHERE
  cc = 'ac';
```

```
SELECT * FROM (
  SELECT greatest (t.x, t.z) cc from (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) t(x, z)
  ) t
  JOIN (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) u(x, z)
    WHERE z='c' --split_part('b.c', '.', 2)
  ) u
  ON t.z = u.z
)
WHERE
  cc = 'c';
```

```
SELECT * FROM (
  SELECT least (t.x, t.z) cc from (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) t(x, z)
  ) t
  JOIN (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) u(x, z)
    WHERE z='c' --split_part('b.c', '.', 2)
  ) u
  ON t.z = u.z
)
WHERE
  cc = 'a';
```

```
SELECT * FROM (
  SELECT array[t.x, t.z] cc from (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) t(x, z)
  ) t
  JOIN (
    SELECT *
    FROM (VALUES (VARCHAR 'a', VARCHAR 'c')) u(x, z)
    WHERE z='c' --split_part('b.c', '.', 2)
  ) u
  ON t.z = u.z
)
WHERE
  cc = array['a', 'c'];
```

Stacktrace:
```
com.facebook.presto.spi.PrestoException: array_constructor(varchar,varchar(1)):array(varchar) not found
        at com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:852)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:145)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:70)
        at com.facebook.presto.sql.relational.CallExpression.accept(CallExpression.java:88)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.lambda$visitCall$3(ExpressionOptimizer.java:150)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:151)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:70)
        at com.facebook.presto.sql.relational.CallExpression.accept(CallExpression.java:88)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.lambda$visitCall$2(ExpressionOptimizer.java:140)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:141)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer$Visitor.visitCall(ExpressionOptimizer.java:70)
        at com.facebook.presto.sql.relational.CallExpression.accept(CallExpression.java:88)
        at com.facebook.presto.sql.relational.optimizer.ExpressionOptimizer.optimize(ExpressionOptimizer.java:67)
        at com.facebook.presto.sql.relational.SqlToRowExpressionTranslator.translate(SqlToRowExpressionTranslator.java:141)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.toRowExpression(LocalExecutionPlanner.java:1100)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1002)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:933)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:525)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.createNestedLoopJoin(LocalExecutionPlanner.java:1418)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitJoin(LocalExecutionPlanner.java:1399)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitJoin(LocalExecutionPlanner.java:525)
        at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:170)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:973)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:933)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:525)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:564)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:525)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:340)
        at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:279)
        at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:161)
        at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:120)
        at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:74)
        at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:313)
        at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:323)
        at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:125)
        at sun.reflect.GeneratedMethodAccessor779.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
        at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:397)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:524)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by haozhun** [comment]
https://github.com/prestodb/presto/pull/5387 fixes the `concat` case and presumably paves the way to fix the others.

**Comment by cberner** [comment]
CC: @losipiuk or @fiedukow could you take a look? I've been investigating this, but am not too familiar with the code and it's blocking us from pushing the new release to our clusters.

**Comment by fiedukow** [comment]
I'll take a look.

**Comment by cberner** [comment]
@fiedukow how is a "type only" coercion suppose to work? I came up with https://github.com/prestodb/presto/pull/5717 which seems to fix this issue, but it seems very hacky

**Comment by fiedukow** [comment]
Workaround is here:
https://github.com/prestodb/presto/pull/5729

As for real solution it seems like predicate pushdown should care about type consistency OR we should always ensure that there are no functions accepting unparametrized varchar. I think first one is better as it will allow to avoid such problem in future.

**Comment by cberner** [comment]
@erichwang can you take a look? @fiedukow believes this is an issue introduced by 8c43eb4. See discussion in https://github.com/prestodb/presto/pull/5717

**Comment by fiedukow** [comment]
Just to clarify: Not really introduced by 8c43eb4, but the `PredicatePushDown` and `UnaliasSymbolReferences` together are causing troubles AFAIU.

**Comment by cberner** [comment]
I attempted another fix by changing `EQUAL(varchar(x), varchar(y))` to `EQUAL(varchar(x), varchar(x))`, however this did not work due to https://github.com/prestodb/presto/issues/5732.

I think this leaves us with the only option being to fix the constant folding to account for types, or a more extensive fix of the type system

**Comment by fiedukow** [comment]
You can change it to `EQUAL(varchar, varchar)`, it's step back, but should work.
Also I think `EQUAL(varchar(x), varchar(x))` wouldn't fix this issue anyway, it will just change breaking cases I believe.

**Comment by cberner** [comment]
I see. I can try that. I had expected `EQUAL(varchar(x), varchar(x))` to fix it as that should have forced a coercion to be added, so that `x = 'a'` (with x is a `varchar`) should become `EQUAL(x, CAST('a' as varchar))` and it would preserve the assumption that the optimizer is making (that equality is only defined for arguments which are the same type)

**Comment by fiedukow** [comment]
Oh yes, you're right `EQUAL(varchar(x), varchar(x))` should work, there was a flaw in my thinking.
