### ISSUE TITLE
java.lang.IllegalArgumentException: tried to free more memory than is reserved

### ISSUE THREAD

**Issue by tesseract2048** [prestodb/presto#5688]
I've got the following error on 0.150 today:

```
2016-07-18T17:46:26.909+0800    ERROR   SplitRunner-1-43        com.facebook.presto.operator.Driver     Error freeing memory for operator 1 for task 20160718_094553_00024_iiz4f.1.43
java.lang.IllegalArgumentException: tried to free more memory than is reserved
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.facebook.presto.operator.DriverContext.freeMemory(DriverContext.java:233)
        at com.facebook.presto.operator.OperatorContext.freeMemory(OperatorContext.java:284)
        at com.facebook.presto.operator.OperatorContext.setMemoryReservation(OperatorContext.java:333)
        at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:464)
        at com.facebook.presto.operator.Driver.access$400(Driver.java:60)
        at com.facebook.presto.operator.Driver$DriverLockResult.close(Driver.java:617)
        at com.facebook.presto.operator.Driver.close(Driver.java:151)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:637)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.destroy(TaskExecutor.java:500)
        at com.facebook.presto.execution.TaskExecutor.splitFinished(TaskExecutor.java:273)
        at com.facebook.presto.execution.TaskExecutor.access$2300(TaskExecutor.java:69)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:703)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by buremba** [comment]
+1

**Comment by davseitsev** [comment]
We get a lot of such exceptions on 0.161

**Comment by miniway** [comment]
I might be wrong but this could happen by trying to `freeMemory` at the same time by `DriverContext.failed at Driver.processInternal()` and `OperatorContext.setMemoryReservation(0) at Driver.destroyIfNecessary()`at a failed task, 

A severe side effect of this error is it could screw up the MemoryPool and make cluster logically out-of-memory. We see cases that MemoryPool contains entries of finished (mostly failed) query.

```
{
  "totalNodeMemory":"180388626432B",
  "pools":{
    "reserved":{
      "maxBytes":85899345920,
      "freeBytes":85899345920,
      "queryMemoryReservations":{

      }
    },
    "general":{
      "maxBytes":94489280512,
      "freeBytes":92110143000,
      "queryMemoryReservations":{
        "20161024_200108_28665_bwk4k":47143296,
        "20161024_204035_33184_bwk4k":2036048,
        "20161024_203321_32674_bwk4k":57632876,
        "20161024_204622_33659_bwk4k":1251789192,
        "20161023_113231_60648_bwk4k":3334592,
        "20161021_115023_90066_bwk4k":1017201508 // failed query
      }
    },
    "system":{
      "maxBytes":25769803776,
      "freeBytes":25504795994,
      "queryMemoryReservations":{
        "20161024_200108_28665_bwk4k":37471845,
        "20161024_203321_32674_bwk4k":188348592,
        "20161024_204622_33659_bwk4k":24408766,
        "20161023_113231_60648_bwk4k":11348640,  
        "20161021_115023_90066_bwk4k":3429939  // failed query
      }
    }
  }
```

**Comment by miniway** [comment]
I think it would safe to remove https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/DriverContext.java#L179

**Comment by nezihyigitbasi** [comment]
@armsword `/v1/status` endpoint should give that info.

**Comment by armsword** [comment]
@nezihyigitbasi  Thanks.
