### ISSUE TITLE
Testcase failure for presto-postgresql on Power Systems

### ISSUE THREAD

**Issue by ArchaB** [prestodb/presto#5710]
Tried building presto-postgresql on Power Systems. 
To support the same, modified the testing-postgresql-server-0.3.jar to include jars compatible for Power Systems.

Testcases still fail with the following exception:

**Caused by: io.airlift.command.CommandFailedException: [/tmp/testing-postgresql-server7462338320829989884/bin/initdb, -A, trust, -U, postgres, -D, /tmp/testing-postgresql-server7462338320829989884/data, -E, UTF-8] exited with 1
/tmp/testing-postgresql-server7462338320829989884/bin/postgres: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
no data was returned by command ""/tmp/testing-postgresql-server7462338320829989884/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/tmp/testing-postgresql-server7462338320829989884/bin/initdb".
Check your installation.

```
    at io.airlift.command.ProcessCallable.call(ProcessCallable.java:64)
    at io.airlift.command.ProcessCallable.call(ProcessCallable.java:22)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:475)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:349)
    at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:152)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:806)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:701)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:629)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ... 12 more**
```

Tried to replace the libssl.so.1.0.0 from the one existing in /usr/lib64 on the system, but did not help. 

Any pointer on how this can be resolved would be helpful.

**Comment by ArchaB** [comment]
Gentle reminder
