### ISSUE TITLE
presto mongodb fails when table names contain underscores

### ISSUE THREAD

**Issue by xwinie** [prestodb/presto#5721]
环境 presto 147版本：
select \* from mtest 这样查询是正常的，但是select \* from sys_dict这样查询会报Error: Query failed (#20160721_041203_00017_wsust): null
SQLState:  null
ErrorCode: 65536  错误

4.13ms
End Time
2016-07-21 12:12:03 +0800
Memory Pool
general
Total Memory
0B
CPU Time
0.00ns
Rows
0
Data Size
0B
Cumulative Memory
0GB seconds
Raw
/v1/query/20160721_041203_00017_wsust?pretty
Plan
/ui/plan?20160721_041203_00017_wsust
Visualization
Timeline
Error Type
INTERNAL_ERROR
Error Code
INTERNAL_ERROR (65536)

java.lang.NullPointerException
    at com.facebook.presto.mongodb.MongoSession.guessTableFields(MongoSession.java:508)
    at com.facebook.presto.mongodb.MongoSession.getTableMetadata(MongoSession.java:403)
    at com.facebook.presto.mongodb.MongoSession.loadTableSchema(MongoSession.java:189)
    at com.facebook.presto.mongodb.MongoSession.access$000(MongoSession.java:78)
    at com.facebook.presto.mongodb.MongoSession$1.load(MongoSession.java:137)
    at com.facebook.presto.mongodb.MongoSession$1.load(MongoSession.java:132)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    at com.facebook.presto.mongodb.MongoSession.getCacheValue(MongoSession.java:241)
    at com.facebook.presto.mongodb.MongoSession.getTable(MongoSession.java:169)
    at com.facebook.presto.mongodb.MongoMetadata.getTableHandle(MongoMetadata.java:83)
    at com.facebook.presto.mongodb.MongoMetadata.getTableHandle(MongoMetadata.java:56)
    at com.facebook.presto.transaction.LegacyConnectorMetadata.getTableHandle(LegacyConnectorMetadata.java:71)
    at com.facebook.presto.metadata.MetadataManager.getTableHandle(MetadataManager.java:287)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitTable(StatementAnalyzer.java:1053)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitTable(StatementAnalyzer.java:232)
    at com.facebook.presto.sql.tree.Table.accept(Table.java:50)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeFrom(StatementAnalyzer.java:1858)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:1165)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:232)
    at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:931)
    at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:232)
    at com.facebook.presto.sql.tree.Query.accept(Query.java:103)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:277)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:263)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:227)
    at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by miniway** [comment]
I think a document contains `null` value but there seems to be a bug at handling null value.

**Comment by xwinie** [comment]
我的collection name: sys_dict  不带下划线的collection 都是正常的，带了就是错误的！

**Comment by xwinie** [comment]
![image](https://cloud.githubusercontent.com/assets/3609288/17014237/151c4088-4f56-11e6-9816-c6012d3d018c.png)
![image](https://cloud.githubusercontent.com/assets/3609288/17014240/1bf8677e-4f56-11e6-8998-c2a36921a323.png)

**Comment by xwinie** [comment]
![image](https://cloud.githubusercontent.com/assets/3609288/17014470/585869fc-4f57-11e6-9370-c147d6b53102.png)

![image](https://cloud.githubusercontent.com/assets/3609288/17014507/7e73629a-4f57-11e6-88f6-3d473f38188c.png)

**Comment by miniway** [comment]
please try creating special collection `_schema` and setting table definition based on https://prestodb.io/docs/current/connector/mongodb.html#table-definition-label
