### ISSUE TITLE
PostgreSQL connector: ERROR: stack depth limit exceeded

### ISSUE THREAD

**Issue by ArturGajowy** [prestodb/presto#5752]
The `TestPostgreSqlDistributedQueries#testLargeIn` test for PostgreSQL connector is failing,  since 0.149 or ealier.

The error was not caught by the CI build because of `TestPostgreSqlDistributedQueries.java` being excluded in postgresql connector pom (which maybe is another issue?).

I am going to disable this test with a link to this issue, so that people don't need to re-verify this failure again and again.

---

How to reproduce:

```
git checkout 0.149    #the oldest commit I've reproduced it for so far
./mvnw clean install -T C1 -pl '!presto-docs,!presto-server-rpm' -DskipTests=true -Dair.check.skip-all=true -Dmaven.javadoc.skip=true
./mvnw clean test -pl presto-postgresql -Dtest=com.facebook.presto.plugin.postgresql.TestPostgreSqlDistributedQueries#testLargeIn
```

The relevant part of the output should be:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 34.96 sec <<< FAILURE!
testLargeIn(com.facebook.presto.plugin.postgresql.TestPostgreSqlDistributedQueries)  Time elapsed: 15.478 sec  <<< FAILURE!
com.facebook.presto.client.FailureInfo$FailureException: org.postgresql.util.PSQLException: ERROR: stack depth limit exceeded
  Hint: Increase the configuration parameter "max_stack_depth" (currently 2048kB), after ensuring the platform's stack depth limit is adequate.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
        at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.<init>(JdbcRecordCursor.java:74)
        at com.facebook.presto.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:56)
        at com.facebook.presto.spi.RecordPageSource.<init>(RecordPageSource.java:37)
        at com.facebook.presto.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:42)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.createSourceIfNecessary(ScanFilterAndProjectOperator.java:292)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.isFinished(ScanFilterAndProjectOperator.java:180)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:375)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)


Results :

Failed tests: 
   » Failure org.postgresql.util.PSQLException: ERROR: stack depth limit exceede...

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.695 s
[INFO] Finished at: 2016-07-26T13:32:05+02:00
[INFO] Final Memory: 105M/941M
[INFO] ------------------------------------------------------------------------
```

**Comment by electrum** [comment]
What platform does this fail on?

**Comment by ArturGajowy** [comment]
OS X and Ubuntu

**Comment by electrum** [comment]
That's weird, because it works on our CI.

**Comment by ArturGajowy** [comment]
You mean travis? Or FB internal? Does the CI somehow override the following lines in the connector's pom?

```
<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!-- integration tests take a very long time so only run them in the CI server -->
                    <excludes>
                        <exclude>**/TestMySqlDistributedQueries.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by electrum** [comment]
@ArturGajowy yes, we set the `ci` profile, defined below in that POM

**Comment by findepi** [comment]
Test suppression reverted in https://github.com/prestodb/presto/pull/9944. Closing this.
