### ISSUE TITLE
Raptor - connection leak 

### ISSUE THREAD

**Issue by jefimm** [prestodb/presto#5762]
When using MySQL as backend there is a connection leak:

```
2016-07-28T14:32:56.300Z        WARN    HikariPool-1 housekeeper        com.zaxxer.hikari.pool.ProxyLeakTask    Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@7ef9c8a5, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at org.skife.jdbi.v2.DBI.open(DBI.java:212)
        at com.facebook.presto.raptor.metadata.ShardIterator.<init>(ShardIterator.java:87)
        at com.facebook.presto.raptor.metadata.DatabaseShardManager.getShardNodes(DatabaseShardManager.java:460)
        at com.facebook.presto.raptor.RaptorSplitManager$RaptorSplitSource.<init>(RaptorSplitManager.java:164)
        at com.facebook.presto.raptor.RaptorSplitManager.getSplits(RaptorSplitManager.java:107)
        at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:45)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:112)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:92)
        at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:228)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:92)
        at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:78)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
        at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:303)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:226)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```
I guess that the following code from ShardIterator.java should be catching Exception not SqlException
```
        try {
            connection = dbi.open().getConnection();
            statement = connection.prepareStatement(sql);
            enableStreamingResults(statement);
            predicate.bind(statement);
            log.debug("Running query: %s", statement);
            resultSet = statement.executeQuery();
        }
        catch (SQLException e) {
            close();
            throw metadataError(e);
        }

**Comment by electrum** [comment]
Thank you! We had a sporadic leak when using Hikari and were never able to track it down.

**Comment by electrum** [comment]
Actually, this might be a false positive from Hikari. The leak detection works by grabbing a stack trace at connection initiation, then starting a timer which prints this message if the thread hasn't been returned to the pool. Hikari has no way of knowing if the connection is still being used.

`ShardIterator` uses a streaming query and can legitimately take a long time (if it's a large query with many shards). 

It might be useful if the leak detection could print an ID for the connection, then print a message later indicating that the previous message was a false positive. Something like this:
```
Connection #123 leak detection triggered
...
Connection #123 was returned to pool
```

But you are right that the code could leak and needs to handle `Throwable`.

**Comment by electrum** [comment]
I filed a Hikari issue for the false positive idea: https://github.com/brettwooldridge/HikariCP/issues/694

**Comment by jefimm** [comment]
This is not a false positive, we experienced the real connection leak (no
queries running and no connections awailable) and had to turn on leak
detection to diagnose.

Regards

**Comment by electrum** [comment]
Do you have an example stack trace of a non-SQLException that was thrown from this block?

I definitely believe there is a leak when using Hikari, because we tried for quite a while but couldn't track down the "no connections available" issue.

This code definitely could leak if the wrong exception is thrown, but it's hard to say for certain that this is the problem (or if there are others).

Please try the patch from that Pull Request.

**Comment by jefimm** [comment]
Unfortunately we were not able to pinpoint the issue but that code looked
like one could be improved
I doubt this is hikari - related issue

Regards
