### ISSUE TITLE
Categorize errors for Joda time ArithmeticException

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5893]
```
presto> select hour(from_unixtime(-pow(2, 54)));
Query 20160818_221052_21696_4xh5v failed: Adding time zone offset caused overflow
java.lang.ArithmeticException: Adding time zone offset caused overflow
    at org.joda.time.DateTimeZone.convertUTCToLocal(DateTimeZone.java:929)
    at org.joda.time.chrono.ZonedChronology$ZonedDateTimeField.get(ZonedChronology.java:422)
    at com.facebook.presto.operator.scalar.DateTimeFunctions.hourFromTimestamp(DateTimeFunctions.java:648)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
    at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649)
    at com.facebook.presto.sql.planner.ExpressionInterpreter.invoke(ExpressionInterpreter.java:1093)
    at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:826)
    at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:96)
    at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
    at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:231)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:153)
    at com.google.common.collect.Maps$7.transformEntry(Maps.java:1812)
    at com.google.common.collect.Maps$10.getValue(Maps.java:1857)
    at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:292)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:110)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:109)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:109)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:109)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:75)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
    at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
    at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:29)
    at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions.optimize(SimplifyExpressions.java:85)
    at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:100)
    at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:277)
    at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:256)
    at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:220)
    at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by rongrong** [comment]
What should be the expected behavior?

**Comment by electrum** [comment]
This should throw `PrestoException` with `INVALID_FUNCTION_ARGUMENT`.

Note that the stack trace above is just an example of one place where this can happen. Any code in `DateTimeFunctions` that calls `org.joda.time.DateTimeField#get()` with a Chronology returned by `getChronology()` or `unpackChronology()` will throw. I'd add a helper method that does the call and catches the `ArithmeticException` from Joda-Time.

The calls on things like `DAY_OF_MONTH.get(DAYS.toMillis(date))` are probably safe, but add some tests to confirm.

Also, we should check if any other operations in `DateTimeFunctions` can fail with huge values, or can silently overflow and produce the wrong result, but that can be a separate task.
