### ISSUE TITLE
NPE in Raptor ShardCompactionManager

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#5970]
```
2016-08-26T11:55:57.107-0700    ERROR   shard-compaction-discovery      com.facebook.presto.raptor.storage.organization.ShardCompactionManager  Error discovering shards to compact
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:339)
        at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:652)
        at com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil.getShardRange(ShardOrganizerUtil.java:231)
        at com.facebook.presto.raptor.storage.organization.ShardOrganizerUtil.toShardIndexInfo(ShardOrganizerUtil.java:118)
        at com.facebook.presto.raptor.storage.organization.ShardCompactionManager.filterAndCreateCompactionSets(ShardCompactionManager.java:199)
        at com.facebook.presto.raptor.storage.organization.ShardCompactionManager.discoverShards(ShardCompactionManager.java:174)
        at com.facebook.presto.raptor.storage.organization.ShardCompactionManager.lambda$startDiscovery$0(ShardCompactionManager.java:151)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by electrum** [comment]
The code needs to skip shards that have a null min/max.

**Comment by erichwang** [comment]
This is a pretty major fix that we need since it will cause shard compaction to completely fail on the machine.

**Comment by raghavsethi** [comment]
OK then will work on this as soon as I'm done with the other release blocker.

**Comment by raghavsethi** [comment]
@electrum from talking to @erichwang it seems like this is a broader problem that we need to discuss.

**Comment by erichwang** [comment]
@raghavsethi @electrum, this is a major problem that is still going on and is essentially prevents compaction from working properly altogether. Do we have any updates?
