### ISSUE TITLE
Add support for decimal column hive bucket

### ISSUE THREAD

**Issue by hegand** [prestodb/presto#5985]
When I would like to query a table with decimal data type as a bucketing column, it fails with the following error message:

`
java.lang.UnsupportedOperationException: Computation of Hive bucket hashCode is not supported for Hive primitive category: DECIMAL.
    at com.facebook.presto.hive.HiveBucketing.hash(HiveBucketing.java:147)
    at com.facebook.presto.hive.HiveBucketing.getBucketHashCode(HiveBucketing.java:93)
    at com.facebook.presto.hive.HiveBucketing.getHiveBucket(HiveBucketing.java:86)
    at com.facebook.presto.hive.HiveBucketFunction.getBucket(HiveBucketFunction.java:45)
    at com.facebook.presto.operator.PartitionFunction.getPartition(PartitionFunction.java:46)
    at com.facebook.presto.operator.PartitionedOutputOperator$PagePartitioner.partitionPage(PartitionedOutputOperator.java:337)
    at com.facebook.presto.operator.PartitionedOutputOperator.addInput(PartitionedOutputOperator.java:256)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)`

**Comment by hegand** [comment]
Example:
```
CREATE TABLE table1 (
  name varchar(100),
  cat decimal(15),
  amount decimal(15)
)
CLUSTERED BY (cat) into 10 buckets
STORED AS ORC tblproperties  ("orc.compress"="ZLIB");
```

This is not working (produce the fomer error message), but 
```
CREATE TABLE table1 (
  name varchar(100),
  cat decimal(15),
  amount decimal(15)
)
CLUSTERED BY (name,cat) into 10 buckets
STORED AS ORC tblproperties  ("orc.compress"="ZLIB");
```

is working

**Comment by mingmwang** [comment]
Looks like no one is working on this.

**Comment by mingmwang** [comment]
is there a patch for this?
