### ISSUE TITLE
Window functions cannot be used in some scalar expressions

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#5991]
```
SELECT
    100.0 * sum(x) OVER() / sum(x) OVER(),
    sum(x) OVER()
FROM (VALUES (1)) t(x)
```

```
Query 20160830_174122_00896_w2gwn failed: sum(bigint):bigint is not a scalar function
java.lang.IllegalArgumentException: sum(bigint):bigint is not a scalar function
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:805)
	at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:897)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:96)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:243)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:156)
	at com.google.common.collect.Maps$7.transformEntry(Maps.java:1812)
	at com.google.common.collect.Maps$10.getValue(Maps.java:1857)
	at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:87)
	at com.google.common.collect.ImmutableMap.copyOf(ImmutableMap.java:294)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:110)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:96)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:109)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:96)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:109)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:96)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:109)
	at com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:88)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
```

**Comment by maciejgrzybek** [comment]
Interesting finding, when `100` (bigint) is used instead of `100.0` (double), query works just fine:
```sql
presto> select 100*sum(x) over() / sum(x) over(), sum(x) over() from (values (1)) t(x);
 _col0 | _col1
-------+-------
   100 |     1
(1 row)
```

Another finding:
when you remove last `sum(x) over()` (the one actually used in aggregation context) it also works:
```sql
presto> select 100.0*sum(x) over()/sum(x) over()from (values (1)) t(x);
 _col0
-------
 100.0
(1 row)
```
