### ISSUE TITLE
Bad error message when SELECT * is used in GROUP BY query

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6061]
``` sql
SELECT * FROM (VALUES (1,1)) t(x,y) GROUP BY x
```

fails with:

```
Query 20160907_180025_00008_b5xgd failed: ':input(1)' must be an aggregate expression or appear in GROUP BY clause
com.facebook.presto.sql.analyzer.SemanticException: ':input(1)' must be an aggregate expression or appear in GROUP BY clause
        at com.facebook.presto.sql.analyzer.AggregationAnalyzer.analyze(AggregationAnalyzer.java:133)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.verifyAggregations(StatementAnalyzer.java:1433)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeAggregations(StatementAnalyzer.java:1394)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:655)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:161)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:409)
        at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:161)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:103)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:62)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:274)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:260)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:224)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The correct message should be:

```
Query 20160907_180138_16338_4xh5v failed: line 1:1: Column 't.y' not in GROUP BY clause
```

This seems to be a regression in a recent version. It doesn't happen in 0.144.7.

**Comment by martint** [comment]
Fixed
