### ISSUE TITLE
Sporadic test failure in TestHttpPageBufferClient

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6116]
```
java.util.concurrent.BrokenBarrierException: null
	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:207)
	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:435)
	at com.facebook.presto.operator.TestHttpPageBufferClient.testCloseDuringPendingRequest(TestHttpPageBufferClient.java:315)

**Comment by AlekseiS** [comment]
Uploaded a pull request: https://github.com/prestodb/presto/pull/6169
@electrum please have a look.

**Comment by AlekseiS** [comment]
Fix pushed
