### ISSUE TITLE
no worker nodes available?

### ISSUE THREAD

**Issue by ffpeng90** [prestodb/presto#6143]
hi all:

Recently I build presto with cluster mode, 1 coordinator& 1 worker, it works. 
Then I repackage "presto-main-0.148.jar" without any change , and relpace it to production environment, it does not work! 
Always get response with "**No worker nodes available**"

I Search the Server.log, And see below:
ERROR Discovery-0 io.airlift.discovery.client.CachingServiceSelector Cannot connect to discovery server for refresh (collector/general): Lookup of collector failed for http://10.3.2.33:18080/v1/service/collector/general
ERROR Discovery-0 io.airlift.discovery.client.CachingServiceSelector Cannot connect to discovery server for refresh (presto/general): Lookup of presto failed for http://10.3.2.33:18080/v1/service/presto/general
INFO Discovery-1 io.airlift.discovery.client.CachingServiceSelector Discovery server connect succeeded for refresh (collector/general)
INFO Discovery-2 io.airlift.discovery.client.CachingServiceSelector Discovery server connect succeeded for refresh (presto/general)

And I use command curl "http://10.3.2.33:18080/v1/service/collector/general", and get response below, 
and I also get coordinator status as 'ACTIVE'

{ "environment": "presto_**_flt", "services": [ { "id": "954e886d-7506-4f00-b954-eeab49209835", "nodeId": "4c0f2596-7e6e-11e6-ae22-56b6b6499611", "type": "presto", "pool": "general", "location": "/4c0f2596-7e6e-11e6-ae22-56b6b6499611", "properties": { "node_version": "a0e36ae", "coordinator": "false", "http": "htp://10.3.2.24:18080", "http-external": "htp://10.3.2.24:18080", "datasources": "hive,system" } }, { "id": "6790b522-cd17-48ef-b077-e4e8fa97e310", "nodeId": "4c0f2366-7e6e-11e6-ae22-56b6b6499611", "type": "presto", "pool": "general", "location": "/4c0f2366-7e6e-11e6-ae22-56b6b6499611", "properties": { "node_version": "c34bef3-dirty", "coordinator": "true", "http": "htp://10.3.2.33:18080", "http-external": "htp://10.3.2.33:18080", "datasources": "" } } ] }

All log seems to be OK, but error **stacktrace show no worker nodes**.
Is there someone encountered similar problem?

StackTrace:
DEBUG	Query-20160920_050350_00000_5gnzt-168	com.facebook.presto.execution.QueryStateMachine	Query 20160920_050350_00000_5gnzt failed
com.facebook.presto.spi.PrestoException: No worker nodes available
	at com.facebook.presto.util.Failures.checkCondition(Failures.java:76)
	at com.facebook.presto.sql.planner.SystemPartitioningHandle.getNodePartitionMap(SystemPartitioningHandle.java:149)
	at com.facebook.presto.sql.planner.NodePartitioningManager.getNodePartitioningMap(NodePartitioningManager.java:96)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.lambda$null$0(SqlQueryScheduler.java:128)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.lambda$new$1(SqlQueryScheduler.java:128)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.createStages(SqlQueryScheduler.java:220)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.<init>(SqlQueryScheduler.java:119)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:322)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:226)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ffpeng90** [comment]
after follow code, i find a checkCondition, which will assert  node_version must be the same.
 and in my situation, it is not equal,  [ "node_version": "a0e36ae", ||"node_version": "c34bef3-dirty",]

**Comment by electrum** [comment]
There is a config property "presto.version" that you can use to override the version. We set it in the development configs.

**Comment by ffpeng90** [comment]
find "presto.version", thx. 
I modified the manifest for node-version directly yesterday , hah
