### ISSUE TITLE
Poor performance when decoding ORC files with some MAP encodings

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6148]
Threads seem to be spending all their time in the following code

```
   java.lang.Thread.State: RUNNABLE
        at java.util.ArrayList.indexOf(ArrayList.java:317)
        at com.facebook.presto.spi.block.DictionaryBlock.copyPositions(DictionaryBlock.java:229)
        at com.facebook.presto.spi.block.AbstractInterleavedBlock.copyPositions(AbstractInterleavedBlock.java:243)
        at com.facebook.presto.spi.block.AbstractArrayBlock.copyPositions(AbstractArrayBlock.java:69)
        at com.facebook.presto.orc.reader.MapStreamReader.createKeyValueBlock(MapStreamReader.java:189)
        at com.facebook.presto.orc.reader.MapStreamReader.readBlock(MapStreamReader.java:146)
        at com.facebook.presto.orc.OrcRecordReader.readBlock(OrcRecordReader.java:320)
        at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:363)
        at com.facebook.presto.hive.orc.OrcPageSource$OrcBlockLoader.load(OrcPageSource.java:339)
        at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:235)
        at com.facebook.presto.spi.Page.assureLoaded(Page.java:166)
        at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:249)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
Fixed.
