### ISSUE TITLE
NPE with join on multiple conditions

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#6173]
```
presto:nyigitbasi> select * from (values(2,2)) a(x,y) join (values(2,2)) b(x,y) on (a.x=b.x, a.y=b.y);
Query 20160923_041517_00003_k64q3 failed: null
java.lang.NullPointerException
        at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:152)
        at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:84)
        at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
        at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:33)
        at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown.optimize(WindowFilterPushDown.java:81)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:116)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:107)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:291)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:270)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:228)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Not exactly sure about the difference but this works

```
presto:nyigitbasi> select * from (values(2,2)) a(x,y) inner join (values(2,2)) b(x,y) on (a.x=b.x and a.y=b.y);
 x | y | x | y
---+---+---+---
 2 | 2 | 2 | 2
(1 row)
```

**Comment by AlekseiS** [comment]
Uploaded PR fixing it: https://github.com/prestodb/presto/pull/6229
In the example the clause is invalid and should result in a semantic exception being thrown.

**Comment by AlekseiS** [comment]
Merged.
