### ISSUE TITLE
try_cast fails with unbound variable exception

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#6177]
```
presto:tiny> select try_cast('foo' as array<integer>);
Query 20160923_154931_00004_72qud failed: Variable is not bound: y
java.lang.IllegalStateException: Variable is not bound: y
        at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
        at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:440)
        at com.facebook.presto.metadata.SignatureBinder.lambda$bindVariables$1(SignatureBinder.java:415)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:416)
        at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:368)
        at com.facebook.presto.metadata.SignatureBinder.bind(SignatureBinder.java:61)
        at com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:835)
        at com.facebook.presto.metadata.FunctionRegistry.getCoercion(FunctionRegistry.java:964)
        at com.facebook.presto.metadata.FunctionRegistry.getCoercion(FunctionRegistry.java:957)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:861)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitCast(ExpressionAnalyzer.java:226)
        at com.facebook.presto.sql.tree.Cast.accept(Cast.java:94)
```

**Comment by AlekseiS** [comment]
Seems to be fixed in "master".
The query now fails with the following message: "Cannot cast varchar(3) to array(integer)"
