### ISSUE TITLE
airlift jmx dependency preventing presto to start up

### ISSUE THREAD

**Issue by dabaitu** [prestodb/presto#6187]
tag: 152.1
For env with custom Java, if the custom java version is not parseable by the airlift jmx JavaVersion.parse Presto doesn't start.
It's also really confusing to have the exact same code in airlift and under presto.server.JavaVersion

**Comment by electrum** [comment]
Can you provide a stack trace?

**Comment by dabaitu** [comment]
38) An exception was caught and reported. Message: Cannot parse version 1.8.0_60-ea
  at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
Caused by: java.lang.IllegalArgumentException: Cannot parse version 1.8.0_60-ea
	at io.airlift.jmx.JavaVersion.parse(JavaVersion.java:76)
	at io.airlift.jmx.JavaVersion.current(JavaVersion.java:46)
	at io.airlift.jmx.JmxModule.configure(JmxModule.java:50)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:114)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:65)

**Comment by martint** [comment]
https://github.com/prestodb/presto/pull/6188
https://github.com/airlift/airlift/pull/465

**Comment by martint** [comment]
Fixed. It will be in the next release.

**Comment by dabaitu** [comment]
@martint are these two files pretty much the same?
presto-main/src/main/java/com/facebook/presto/server/JavaVersion.java
jmx/src/main/java/io/airlift/jmx/JavaVersion.java

If there's a reason to have two of them, then should the change you made to airlift be also added to the Presto JavaVersion?

**Comment by martint** [comment]
I've applied the change to both.

These classes are a temporary hack until we switch to Java 9 (sometime next year). We didn't want to make them a public interface of airlift, so that's why we have two copies.
