### ISSUE TITLE
Regression: Lost symbols on right side of join lead to query failure

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6219]
Unfortunately, I don't have a public dataset that reproduces this, but I am seeing queries that fail with:
```
Query 20160928_225837_01839_evkwk failed: position is not valid
java.lang.IllegalArgumentException: position is not valid
	at com.facebook.presto.spi.block.AbstractArrayBlock.checkReadablePosition(AbstractArrayBlock.java:254)
	at com.facebook.presto.spi.block.AbstractArrayBlock.isNull(AbstractArrayBlock.java:247)
	at com.facebook.presto.operator.UnnestOperator.initializeUnnesters(UnnestOperator.java:191)
	at com.facebook.presto.operator.UnnestOperator.addInput(UnnestOperator.java:181)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

It appears that the failure is caused by a bad plan, as there are missing symbols on the right side of the InnerJoin:
```
 Fragment 1 [HASH]                                                                                                                                                         
     Output layout: [sum_22]                                                                                                                                               
     Output partitioning: SINGLE []                                                                                                                                        
     - Aggregate(PARTIAL) => [sum_22:bigint]                                                                                                                               
             sum_22 := "sum"("field")                                                                                                                                      
         - InnerJoin[] => [field:bigint]                                                                                                                                   
             - Unnest [replicate=, unnest=... <redacted>                                          
             - RemoteSource[3] => [] 
```

**Comment by geraint0923** [comment]
I simplified to another simple query:
```
select col0 
from (values 1) a(col0) JOIN 
(SELECT col1 FROM (values 1) t(col1) WHERE col1 = 0) ver 
ON col0 = col1;
```

The corresponding plan is:
```
presto:pages> explain select col0 from (values 1) a(col0) JOIN (SELECT col1 FROM (values 1) t(col1) WHERE col1 = 0) ver ON col0 = col1;
                         Query Plan
------------------------------------------------------------
 - Output[col0] => [field:integer]
         col0 := field
     - InnerJoin[] => [field:integer]
         - Filter[(0 = "field")] => [field:integer]
             - Values => [field:integer]
                     (1)
         - Project => []                     <========= the output symbol list is empty
             - Filter[("field_1" = 0)] => [field_1:integer]
                 - Values => [field_1:integer]
                         (1)

(1 row)
```

Looked into `PredicatePushDown` optimizer, and found out that it generated a `JoinNode` with a empty criteria, which makes symbol `field_1` non-referenced, and led to `field_1` being pruned in `PruneUnreferencedOutputs`.

**Comment by geraint0923** [comment]
Got a much simpler query:
```
presto:tiny> select val from (select distinct vals from (values (array[2])) t(vals)) tmp cross join unnest(tmp.vals) tt(val);

Query 20160929_222535_00023_2dx86, FAILED, 1 node
http://localhost:8080/query.html?20160929_222535_00023_2dx86
Splits: 5 total, 4 done (80.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 50% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20160929_222535_00023_2dx86 failed: position is not valid
java.lang.IllegalArgumentException: position is not valid
	at com.facebook.presto.spi.block.AbstractArrayBlock.checkReadablePosition(AbstractArrayBlock.java:188)
	at com.facebook.presto.spi.block.AbstractArrayBlock.isNull(AbstractArrayBlock.java:181)
	at com.facebook.presto.operator.UnnestOperator.initializeUnnesters(UnnestOperator.java:191)
	at com.facebook.presto.operator.UnnestOperator.addInput(UnnestOperator.java:181)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

while without the `distinct` the query will succeed:
```
presto:tiny> select val from (select  vals from (values (array[2])) t(vals)) tmp cross join unnest(tmp.vals) tt(val);
 val
-----
   2
(1 row)
```
