### ISSUE TITLE
Getting  BoundedExecutor is in a failed state exception

### ISSUE THREAD

**Issue by ujjwal009** [prestodb/presto#6262]
Hi while running query getting:

presto:roam_insight_new6> select \* from ri_grq_mapsig_node_hrly;
Query 20161004_101218_00580_9euxy failed: BoundedExecutor is in a failed state

**Comment by electrum** [comment]
Can you show the full stack trace? Run the CLI with `--debug`. Also, please post the query that reproduces this and information about what connector(s) it's using.

**Comment by ujjwal009** [comment]
full stack trace:

java.lang.IllegalStateException: BoundedExecutor is in a failed state
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at io.airlift.concurrent.BoundedExecutor.execute(BoundedExecutor.java:54)
	at com.facebook.presto.hive.HiveSplitManager$ErrorCodedExecutor.execute(HiveSplitManager.java:317)
	at com.facebook.presto.hive.util.ResumableTasks.submit(ResumableTasks.java:39)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.start(BackgroundHiveSplitLoader.java:155)
	at com.facebook.presto.hive.HiveSplitManager.getSplits(HiveSplitManager.java:176)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorSplitManager.getSplits(ClassLoaderSafeConnectorSplitManager.java:41)
	at com.facebook.presto.split.SplitManager.getSplits(SplitManager.java:45)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:112)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitTableScan(DistributedExecutionPlanner.java:92)
	at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:162)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitFilter(DistributedExecutionPlanner.java:92)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:228)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner$Visitor.visitProject(DistributedExecutionPlanner.java:92)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:78)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
	at com.facebook.presto.sql.planner.DistributedExecutionPlanner.plan(DistributedExecutionPlanner.java:83)
	at com.facebook.presto.execution.SqlQueryExecution.planDistribution(SqlQueryExecution.java:307)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:230)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:68)
	at com.facebook.presto.execution.QueuedExecution$$Lambda$372/294990961.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ujjwal009** [comment]
Sample failed query :


presto:hive_q161005_rel> select distinct scenario_type from table;
Query 20161101_072044_00051_ktbhi failed: BoundedExecutor is in a failed state

**Comment by ujjwal009** [comment]
Config.properties:

coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8180
query.max-memory=20GB
query.max-memory-per-node=4GB
#task.max-memory=4GB
discovery-server.enabled=true
discovery.uri=http://node1:8180
task.max-worker-threads=5


Lastly:

Connector is hive

**Comment by dain** [comment]
You should see this message in your logs "BoundedExecutor state corrupted due to underlying executor failure” from this line https://github.com/airlift/airlift/blob/master/concurrent/src/main/java/io/airlift/concurrent/BoundedExecutor.java#L66

Can you check the logs and see if there is a OutOfMemroyError or a stack trace from within BoundedExecutor?

-dain

**Comment by nmahadevuni** [comment]
We are on Presto version 0.152 and we face this problem very frequently while running large queries. First we get "unable to create new native thread" error due to OutOfMemory and the next run onward "BoundedExecutor is in a failed state". After this happens, whatever query we run fails with the same error. We restart Presto too but it doesn't solve this problem. Appreciate any inputs on how to recover from this problem.

**Comment by ujjwal009** [comment]
Problem can only be fixed with a presto restart. Can this be avoided ?
This is a major concern on production enviornments.

**Comment by nezihyigitbasi** [comment]
@ujjwal009 typically  the root cause of "unable to create new native thread" is hitting the limit of max user processes (there may be other reasons like running out of native memory etc.).  On the machine that you see this issue what's the output of `ulimit -a`?

**Comment by electrum** [comment]
Please update to Presto 0.176. The issue causing it to run out of threads may already have been fixed.

The JVM should be restarted after an OOM caused by lack of memory or threads. We recommend using this agent to automatically kill the JVM when this occurs: https://github.com/airlift/jvmkill

Also, make sure your OS is configured to allow enough threads. Presto can create several thousand.

**Comment by nmahadevuni** [comment]
The ulimits on our systems is 
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1032729
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1032729
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

in limits.conf

presto    soft    nproc 32768
presto    hard    nproc 65536
presto soft nofile 32768
presto hard nofile 65536

**Comment by nmahadevuni** [comment]
Thanks for your inputs. Will use jvmkill agent and see if we can restart Presto quickly.

**Comment by analog76** [comment]
I see this error on the coordinator node server.log.  Is it originating from the coordinator or worker propagating the error to the coordinator?    I don't see this error on the worker node.

**Comment by taoyouxian** [comment]
I also meet this problem in Presto 0.192 with too many queries.

**Comment by daigexuyu** [comment]
@ujjwal009 I also meet this problem in presto 0.180 with some queries, Have you solved this problem?

**Comment by purejade** [comment]
@taoyouxian  do you solved it ? i meet the same problem, and restart the master and success. do you have better solutions?

**Comment by taoyouxian** [comment]
@purejade  Maybe give more memory or clear the cache.

**Comment by ankitdixit** [comment]
@taoyouxian Can you please explain me on how to clear the cache?
