### ISSUE TITLE
Exception when pressing CTRL-C during query execution

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6266]
Pressing CTRL-C in the CLI while a query is processing causes:

```
java.lang.RuntimeException: Error fetching next
    at com.facebook.presto.client.StatementClient.advance(StatementClient.java:300)
    at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:121)
    at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:123)
    at com.facebook.presto.cli.Query.renderOutput(Query.java:107)
    at com.facebook.presto.cli.Console.process(Console.java:294)
    at com.facebook.presto.cli.Console.runConsole(Console.java:234)
    at com.facebook.presto.cli.Console.run(Console.java:139)
    at com.facebook.presto.cli.Presto.main(Presto.java:32)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at io.airlift.http.client.ResponseHandlerUtils.propagate(ResponseHandlerUtils.java:22)
```

Version: 0.152

**Comment by nezihyigitbasi** [comment]
@martint I have an open PR (#5008) that also fixes this issue. #4720 is also related, it tries to handle interrupts properly.
