### ISSUE TITLE
Planning Class cast exception

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#6278]
This query now throws an error:
```
SELECT
  (MAX(x.a) OVER () - x.a) * 100.0 / MAX(x.a) OVER ()
FROM (
  SELECT 1 as a
) x
```

```
Query 20161005_231326_03851_gb7jd failed: com.facebook.presto.sql.tree.SymbolReference cannot be cast to com.facebook.presto.sql.tree.FunctionCall
java.lang.ClassCastException: com.facebook.presto.sql.tree.SymbolReference cannot be cast to com.facebook.presto.sql.tree.FunctionCall
	at com.facebook.presto.sql.planner.QueryPlanner.window(QueryPlanner.java:617)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:140)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:443)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:94)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:220)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:113)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:436)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:94)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:103)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:358)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:150)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:112)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:107)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:270)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by erichwang** [comment]
This seems to be caused by:
https://github.com/prestodb/presto/commit/6bbf957c80a265e2e3813951641e6f23580da89a

@martint can you take a look?
