### ISSUE TITLE
Planning bug when creating bucketed table

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6330]
This query:

```sql
CREATE TABLE t
WITH (
    bucketed_by=array['k'],
    bucket_count=64) 
AS (SELECT '' a, '' b, 0 k)
```

fails with:

```
java.lang.IllegalArgumentException: Input symbols do not match output symbols
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.<init>(ExchangeNode.java:82)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.partitionedExchange(ExchangeNode.java:130)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTableWriter(AddExchanges.java:636)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTableWriter(AddExchanges.java:187)
	at com.facebook.presto.sql.planner.plan.TableWriterNode.accept(TableWriterNode.java:128)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1231)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTableFinish(AddExchanges.java:791)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitTableFinish(AddExchanges.java:187)
	at com.facebook.presto.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:80)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.planChild(AddExchanges.java:1231)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:236)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges$Rewriter.visitOutput(AddExchanges.java:187)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.optimizations.AddExchanges.optimize(AddExchanges.java:149)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:105)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:281)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:260)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:224)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
@haozhun, can you take a look?
