### ISSUE TITLE
Planning error when subquery is used in CASE/IF expression

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6346]
```
SELECT if(false, 'a' IN (VALUES 'b'))
```

Produces 

```
java.lang.IllegalArgumentException: Unsupported subquery type
	at com.facebook.presto.sql.planner.sanity.NoApplyNodeLeftChecker$1.visitApply(NoApplyNodeLeftChecker.java:39)
	at com.facebook.presto.sql.planner.plan.ApplyNode.accept(ApplyNode.java:96)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitProject(PlanVisitor.java:40)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.NoApplyNodeLeftChecker.validate(NoApplyNodeLeftChecker.java:33)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:42)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:42)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:123)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:107)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:270)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:228)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is a regression in 0.153

**Comment by martint** [comment]
It's caused by 4791a802a69f5f73d21c43b11df9b5980879f97c

**Comment by kokosing** [comment]
@martint Sorry about that. I will take care of this immediately.

**Comment by martint** [comment]
I'm looking into it, too. The problem is that because we moved the in->semijoin tranform below prune unreferenced outputs, the plan ends up like this:

```
- Output[_col0] => [expr_2:boolean]
        _col0 := expr_2
    - Project => [expr_2:boolean]
            expr_2 := CAST(null AS BOOLEAN)
        - Apply[[]] => []
            - Values => []
                    ()
            - Values => []
                    ()
```

**Comment by martint** [comment]
I think a quick solution is to implement a rule that reduces that apply to a simple Values. I'm working on that fix. I'll ping you if I need help.
