### ISSUE TITLE
Presto 0.153 class cast exception generated bytecode custom types

### ISSUE THREAD

**Issue by RobinUS2** [prestodb/presto#6365]
It seems that there's an issue with custom accumalators in the latest version where we are getting the following exception:
```
java.lang.ClassCastException: class com_facebook_presto_$gen_BloomFilterVarcharBloomFilterAccumulator_2042
    at java.lang.Class.asSubclass(Class.java:3404)
    at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:73)
    at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:78)
    at com.facebook.presto.operator.aggregation.AccumulatorCompiler.generateAccumulatorClass(AccumulatorCompiler.java:156)
    at com.facebook.presto.operator.aggregation.AccumulatorCompiler.generateAccumulatorFactoryBinder(AccumulatorCompiler.java:73)
    at com.facebook.presto.operator.aggregation.LazyAccumulatorFactoryBinder.lambda$new$0(LazyAccumulatorFactoryBinder.java:30)
    at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
    at com.facebook.presto.operator.aggregation.LazyAccumulatorFactoryBinder.bind(LazyAccumulatorFactoryBinder.java:36)
    at com.facebook.presto.operator.aggregation.InternalAggregationFunction.bind(InternalAggregationFunction.java:82)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.buildAccumulatorFactory(LocalExecutionPlanner.java:1858)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.planGlobalAggregation(LocalExecutionPlanner.java:1869)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:881)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitAggregation(LocalExecutionPlanner.java:537)
    at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:204)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:352)
    at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:291)
    at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:161)
    at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:120)
    at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:74)
    at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:315)
    at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:324)
    at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:125)
    at sun.reflect.GeneratedMethodAccessor416.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
    at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
    at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:396)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1176)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
    at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
    at org.eclipse.jetty.server.Server.handle(Server.java:518)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:314)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
```

The code of the plugin can be found here https://github.com/RobinUS2/presto-bloomfilter/tree/master/src/main/java/com/facebook/presto/bloomfilter but used to work fine before.

**Comment by electrum** [comment]
I sent a pull request to update for 0.153: https://github.com/RobinUS2/presto-bloomfilter/pull/16

I didn't test this in a full server, so it's possible there's some weird class loader issue, but we have tests for the ML plugin (which has aggregation functions) in product-tests, so I expect this will fix it.

**Comment by RobinUS2** [comment]
Thanks for doing that @electrum , I will run some tests and confirm here once it all looks good!

**Comment by RobinUS2** [comment]
@electrum I checked with changing some things in the pom to resolve the dependencies in a way that worked. The issue seems to remain the same https://github.com/RobinUS2/presto-bloomfilter/issues/20 I checked actually with debug and the same code is touched (of the accumulator compiler)  during the presto-bloomfilter plugin test suite without options. But it doesn't work runtime on a full server. 

I'm running out of clues a bit on how to fix this.

**Comment by electrum** [comment]
How can I reproduce this?

**Comment by RobinUS2** [comment]
1. Build the presto-bloom filter master (mvn clean install)
2. Copy the zip file to the nodes + unzip into the plugin folder
3. Execute below queries on catalog hive
```
USE default;
CREATE TABLE mytable (uuid VARCHAR) WITH (format = 'ORC');
INSERT INTO mytable VALUES ('one');
INSERT INTO mytable VALUES ('two');
INSERT INTO mytable VALUES ('three');
SELECT bloom_filter(distinct uuid) FROM mytable;
```
4. Yields the error above

**Comment by electrum** [comment]
I think the error is caused by having a non-test dependency on `presto-main`. When I remove that by making it `<scope>test</scope>` (as I did in my PR), the plugin works. Otherwise, I can reproduce this error.

A plugin should only depend on `presto-main` for tests (and that's only a convenience for testing -- you can write your tests however you want).

At runtime, the plugin class loader will only have access to the SPI and related dependencies. It won't be able to see anything in `presto-main`.

**Comment by RobinUS2** [comment]
Thanks @electrum I missed that while trying to resolve the issue with versions of jetty, so I kind of manually cherry picked what I thought we needed in the pom and what not: missed this important one. Apologies for getting back again but this one is now solved and running nicely in production.
