### ISSUE TITLE
Flaky test TestResourceGroupIntegration.testMemoryFraction

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6369]
```
testMemoryFraction(com.facebook.presto.execution.resourceGroups.TestResourceGroupIntegration)  Time elapsed: 60.009 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testMemoryFraction() didn't finish within the time-out 60000
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Exception.<init>(Exception.java:66)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:56)
	at java.lang.NoSuchMethodException.<init>(NoSuchMethodException.java:51)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at org.weakref.jmx.AnnotationUtils.findManagedMethod(AnnotationUtils.java:260)
	at org.weakref.jmx.AnnotationUtils.findManagedMethods(AnnotationUtils.java:243)
	at org.weakref.jmx.MBeanBuilder.<init>(MBeanBuilder.java:58)
	at org.weakref.jmx.MBeanAttributeBuilder.build(MBeanAttributeBuilder.java:169)
	at org.weakref.jmx.MBeanBuilder.build(MBeanBuilder.java:125)
	at org.weakref.jmx.MBeanAttributeBuilder.build(MBeanAttributeBuilder.java:169)
	at org.weakref.jmx.MBeanBuilder.build(MBeanBuilder.java:125)
	at org.weakref.jmx.MBeanAttributeBuilder.build(MBeanAttributeBuilder.java:146)
	at org.weakref.jmx.MBeanBuilder.build(MBeanBuilder.java:125)
	at org.weakref.jmx.MBeanExporter.export(MBeanExporter.java:72)
	at org.weakref.jmx.MBeanExporter.export(MBeanExporter.java:65)
	at org.weakref.jmx.guice.GuiceMBeanExporter.export(GuiceMBeanExporter.java:73)
	at org.weakref.jmx.guice.GuiceMBeanExporter.<init>(GuiceMBeanExporter.java:35)
	at org.weakref.jmx.guice.GuiceMBeanExporter$$FastClassByGuice$$6cc63b28.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.testing.TestingPrestoServer.<init>(TestingPrestoServer.java:235)
	at com.facebook.presto.tests.DistributedQueryRunner.createTestingPrestoServer(DistributedQueryRunner.java:177)
	at com.facebook.presto.tests.DistributedQueryRunner.<init>(DistributedQueryRunner.java:116)
	at com.facebook.presto.tests.tpch.TpchQueryRunner.createQueryRunner(TpchQueryRunner.java:54)
	at com.facebook.presto.execution.resourceGroups.TestResourceGroupIntegration.testMemoryFraction(TestResourceGroupIntegration.java:32)

**Comment by electrum** [comment]
Just saw another failure:
```
testMemoryFraction(com.facebook.presto.execution.resourceGroups.TestResourceGroupIntegration)  Time elapsed: 60.25 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testMemoryFraction() didn't finish within the time-out 60000
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1038)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:218)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:345)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:281)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:92)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:78)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:323)
	at com.facebook.presto.execution.resourceGroups.TestResourceGroupIntegration.testMemoryFraction(TestResourceGroupIntegration.java:36)
