### ISSUE TITLE
Test failures when UnaliasSymbolReferences is disabled

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6414]
Some tests in AbstractTestQueries fail with the following error. This could by a symptom of a latent bug, since the main purpose of this optimizer is just to normalize names so that plans look better when printed (it also helps dedup some computations):

```
Caused by: java.lang.IllegalArgumentException: Invalid node. Predicate dependencies ([expr_13]) not in source plan output ([orderkey, unique])
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:611)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.access$100(ValidateDependenciesChecker.java:77)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitFilter(ValidateDependenciesChecker.java:230)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitFilter(ValidateDependenciesChecker.java:91)
    at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:250)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:91)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:117)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:91)
    at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:185)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:250)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:91)
    at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:300)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:91)
    at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:88)
    at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:83)
    at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:42)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:42)
    at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:125)
    at com.facebook.presto.testing.LocalQueryRunner.createPlan(LocalQueryRunner.java:691)
    at com.facebook.presto.testing.LocalQueryRunner.createPlan(LocalQueryRunner.java:657)
    at com.facebook.presto.testing.LocalQueryRunner.createPlan(LocalQueryRunner.java:644)
    at com.facebook.presto.testing.LocalQueryRunner.createDrivers(LocalQueryRunner.java:554)
    at com.facebook.presto.testing.LocalQueryRunner.executeInternal(LocalQueryRunner.java:515)
    at com.facebook.presto.testing.LocalQueryRunner.lambda$execute$2(LocalQueryRunner.java:488)
    at com.facebook.presto.transaction.TransactionBuilder.execute(TransactionBuilder.java:149)
    at com.facebook.presto.testing.LocalQueryRunner.inTransaction(LocalQueryRunner.java:500)
    at com.facebook.presto.testing.LocalQueryRunner.execute(LocalQueryRunner.java:488)
    at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:83)
    ... 30 more
```

**Comment by sopel39** [comment]
I will take a look

**Comment by sopel39** [comment]
One fix: https://github.com/prestodb/presto/pull/6500
I guess there will be more

**Comment by sopel39** [comment]
This issue seem to be part of a bigger problem. There is plenty of implicit optimizer interdependencies. Because of that it is really hard to modify plan nodes during planning (e.g: add symbols). Some optimizers require prior unaliasing, prunning or predicate pushdown to work. Generally, I think there are two kind of so called optimizers:
* 1) (Optimizers) that optimize plan, but are not required (e.g: unalias, prune, predicate pushdown)
* 2) (Rewrites) that alter plan so that it it possible to execute it (e.g: add exchanges, subquery transformations, pick layout)

It seems that 1) optimizers are optional. It should be possible to turn them off and all queries should execute. There also shouldn't  be an order dependency between them.

2) rewrites are required and there might be an order dependency between them.

Given that I propose following steps:
1) Add possibility to execute all tests without optional optimizations 1) as part of a build process (might be nightly). This will show errors related to implicit optimizers interdependencies.
2) Refactor planner so that optional optimizers 1) are distinguished from required rewrites 2). Required rewrites should be able to specify a set of optional optimizers that cleanup plan after rewrite. Such declarative approach will make it easier to test and maintain both required and optional optimizers.

CC: @martint @kokosing
