### ISSUE TITLE
Flaky TestRaptorIntegrationSmokeTestBucketed.testCreateBucketedTable

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6434]
This might be caused due to compaction running during the test.

```
testCreateBucketedTable(com.facebook.presto.raptor.TestRaptorIntegrationSmokeTestBucketed)  Time elapsed: 0.409 sec  <<< FAILURE!
java.lang.AssertionError: For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual 1 rows:
    [75]
Expected 1 rows:
    [100]

    at org.testng.Assert.fail(Assert.java:94)
    at com.facebook.presto.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:149)
    at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:132)
    at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:112)
    at com.facebook.presto.raptor.TestRaptorIntegrationSmokeTest.testCreateBucketedTable(TestRaptorIntegrationSmokeTest.java:325)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by sopel39** [comment]
Still failing:
```
[ERROR] Failures: 
[ERROR]   TestRaptorIntegrationSmokeTestMySql>TestRaptorIntegrationSmokeTest.testCreateBucketedTable:405->AbstractTestQueryFramework.assertQuery:129 For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 matching and extra rows in total):
    [75]
Expected rows (up to 100 of 1 missing rows shown, 1 matching and missing rows in total):
    [100]
```

**Comment by findepi** [comment]
```
09:29:21 [ERROR] Failures: 
09:29:21 [ERROR]   TestRaptorIntegrationSmokeTestMySql>TestRaptorIntegrationSmokeTest.testCreateBucketedTable:412->AbstractTestQueryFramework.assertQuery:129 For query: 
09:29:21  SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
09:29:21 not equal
09:29:21 Actual rows (up to 100 of 1 extra rows shown, 1 matching and extra rows in total):
09:29:21     [75]
09:29:21 Expected rows (up to 100 of 1 missing rows shown, 1 matching and missing rows in total):
09:29:21     [100]
09:29:21 
09:29:21 [INFO] 
09:29:21 [ERROR] Tests run: 1529, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by rschlussel** [comment]
Still failing.  Example: https://api.travis-ci.org/v3/job/572005877/log.txt

**Comment by rschlussel** [comment]
@highker @jessesleeping What do you think of @electrum's theory that it's caused by compaction running during the test (I don't know raptor well enough to evaluate).  Would it make sense to run the tests with compaction disabled?

In the failure linked above the test failed 2x:

```
[ERROR] Tests run: 1668, Failures: 2, Errors: 0, Skipped: 2, Time elapsed: 2,606.633 s <<< FAILURE! - in TestSuite
[ERROR] testCreateBucketedTable(com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestMySql)  Time elapsed: 1.266 s  <<< FAILURE!
java.lang.AssertionError: 
For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [75]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [100]

	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:223)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:203)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:138)
	at com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTest.testCreateBucketedTable(TestRaptorIntegrationSmokeTest.java:517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] testCreateBucketedTable(com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTestWithOptimizedWriter)  Time elapsed: 0.648 s  <<< FAILURE!
java.lang.AssertionError: 
For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [75]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [100]

	at org.testng.Assert.fail(Assert.java:94)
	at com.facebook.presto.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:223)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:203)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:138)
	at com.facebook.presto.raptor.integration.TestRaptorIntegrationSmokeTest.testCreateBucketedTable(TestRaptorIntegrationSmokeTest.java:517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestRaptorIntegrationSmokeTestMySql>TestRaptorIntegrationSmokeTest.testCreateBucketedTable:517->AbstractTestQueryFramework.assertQuery:138 For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [75]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [100]

[ERROR]   TestRaptorIntegrationSmokeTestWithOptimizedWriter>TestRaptorIntegrationSmokeTest.testCreateBucketedTable:517->AbstractTestQueryFramework.assertQuery:138 For query: 
 SELECT count(DISTINCT "$shard_uuid") FROM orders_bucketed
not equal
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [75]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [100]

[INFO] 
[ERROR] Tests run: 1668, Failures: 2, Errors: 0, Skipped: 2
[INFO] 
```
