### ISSUE TITLE
IllegalStateException from query with scalar subquery in onclause

### ISSUE THREAD

**Issue by dain** [prestodb/presto#6493]
```sql
EXPLAIN select
    count()
from tpch.tiny.nation a
inner join tpch.tiny.nation b
  on a.name = (select max(name) from tpch.tiny.nation)
inner join tpch.tiny.nation c
  on c.name = split_part(b.name,'<',2)
```

```
java.lang.IllegalStateException
	at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
	at com.facebook.presto.sql.planner.optimizations.IndexJoinOptimizer$IndexSourceRewriter.planTableScan(IndexJoinOptimizer.java:259)
	at com.facebook.presto.sql.planner.optimizations.IndexJoinOptimizer$IndexSourceRewriter.visitTableScan(IndexJoinOptimizer.java:244)
	at com.facebook.presto.sql.planner.optimizations.IndexJoinOptimizer$IndexSourceRewriter.visitTableScan(IndexJoinOptimizer.java:201)
	at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
```

**Comment by martint** [comment]
This seems to be caused by ed291cdd6701862c82ceefaf25f557f481faedd8. @kokosing, can you take a look?

**Comment by kokosing** [comment]
sure, I will take care of this
