### ISSUE TITLE
Flaky testResourceGroupManager tests 

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#6495]
This causes ~30% of Travis runs to fail.

'''
Tests run: 1696, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2,623.875 sec <<< FAILURE!
testResourceGroupManager(com.facebook.presto.execution.TestQueues)  Time elapsed: 4.925 sec  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:265)
	at org.testng.Assert.assertEquals(Assert.java:275)
	at com.facebook.presto.execution.TestQueues.testBasic(TestQueues.java:95)
	at com.facebook.presto.execution.TestQueues.testResourceGroupManager(TestQueues.java:52)
'''

**Comment by cberner** [comment]
Should be fixed by https://github.com/prestodb/presto/pull/6504
