### ISSUE TITLE
Planning error for query containing disjunctions and IN (subquery) predicates

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6551]
```sql
SELECT *
FROM tpch.tiny.orders
WHERE orderkey IN (VALUES 1) OR TRUE
```

fails with:

```
java.lang.IllegalArgumentException: Unsupported subquery type
	at com.facebook.presto.sql.planner.sanity.NoApplyNodeLeftChecker$1.visitApply(NoApplyNodeLeftChecker.java:39)
	at com.facebook.presto.sql.planner.plan.ApplyNode.accept(ApplyNode.java:96)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:175)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:208)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.NoApplyNodeLeftChecker.validate(NoApplyNodeLeftChecker.java:33)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:42)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:42)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:123)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:107)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:270)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:228)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
cc @kokosing

**Comment by kokosing** [comment]
I will take care of this.
