### ISSUE TITLE
Exception Connecting to MySQL and JDBC Sources using Presto 

### ISSUE THREAD

**Issue by handsetvn** [prestodb/presto#6574]
Amazon RDS : 

CREATE TABLE `JDBCTable` (
  `id` int(11) NOT NULL,
  `id_double` double DEFAULT NULL,
  `names` varchar(45) DEFAULT NULL,
  `test` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

---------------------------------------------------------------------------------

hive> CREATE EXTERNAL TABLE HiveTable(
                                 id INT,
                                 id_double DOUBLE,
                                 names STRING,
                                 test INT
)
STORED BY 'org.apache.hadoop.hive.jdbc.storagehandler.JdbcStorageHandler'
TBLPROPERTIES (
  "mapred.jdbc.driver.class"="com.mysql.jdbc.Driver",
  "mapred.jdbc.url"="jdbc:mysql://xxxx.xxxx.us-east-1.rds.amazonaws.com:3306/mp_catalog",
  "mapred.jdbc.username"="root",
  "mapred.jdbc.input.table.name"="JDBCTable",
  "mapred.jdbc.output.table.name"="JDBCTable",
  "mapred.jdbc.password"="123456789"
);

hive> select * from HiveTable;
OK
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.util.StringUtils.toUpperCase(Ljava/lang/String;)Ljava/lang/String;
	at org.apache.hadoop.mapreduce.lib.db.DBInputFormat.setConf(DBInputFormat.java:167)
	at org.apache.hadoop.hive.jdbc.storagehandler.JdbcInputFormat.getSplits(JdbcInputFormat.java:64)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextSplits(FetchOperator.java:368)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getRecordReader(FetchOperator.java:300)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.getNextRow(FetchOperator.java:455)
	at org.apache.hadoop.hive.ql.exec.FetchOperator.pushRow(FetchOperator.java:424)
	at org.apache.hadoop.hive.ql.exec.FetchTask.fetch(FetchTask.java:144)
	at org.apache.hadoop.hive.ql.Driver.getResults(Driver.java:1885)
	at org.apache.hadoop.hive.cli.CliDriver.processLocalCmd(CliDriver.java:252)
	at org.apache.hadoop.hive.cli.CliDriver.processCmd(CliDriver.java:183)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:399)
	at org.apache.hadoop.hive.cli.CliDriver.executeDriver(CliDriver.java:776)
	at org.apache.hadoop.hive.cli.CliDriver.run(CliDriver.java:714)
	at org.apache.hadoop.hive.cli.CliDriver.main(CliDriver.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by martint** [comment]
This issue is not related to Presto. The output you posted is from the Hive CLI. You may want to ask about or report an issue with the Hive project, instead.
