### ISSUE TITLE
Unable to create plan for query with duplicated IN predicates

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6637]
```
presto:tiny> select 1 in (select 1), 2 in (select 1) where 1 in (select 1);
Query 20161116_072550_00005_ztdnc failed: Invalid node. Expression dependencies ([semijoin_result]) not in source plan output ([expr_4, $hashvalue_22, semijoin_result_17])
```

```
	
java.lang.IllegalArgumentException: Invalid node. Expression dependencies ([semijoin_result]) not in source plan output ([expr_4, $hashvalue_22, semijoin_result_17])
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:610)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.access$100(ValidateDependenciesChecker.java:77)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:257)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:469)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:208)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:300)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:88)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:83)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:43)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:43)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:125)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:109)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:292)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kokosing** [comment]
CC: @sopel39

**Comment by sopel39** [comment]
Fixing the issue became more problematic than I thought. It is partially because there are some conventions in current subquery handling code:
* it is hard to distinguish between apply nodes used in scalar (e.g: `1=(SELECT 1)`) or group context (e.g: `1 IN (SELECT 1)`)
* subquery transforming rewrites (`Transform*`, `RemoveRedundantApply`) need to match complex plan structure in order to identify apply nodes they can process
* pruner assumes that `ApplyNode` has one output symbol (it cannot simply remove apply nodes without output symbols since it might be used in group context, e.g: `1 IN (SELECT 1)`). This assumption is incorrect
* removing of `ApplyNodes` is required for some queries to work (e.g: `testSemiJoinLimitPushDown`)
* other optimizers might implicitly change plan structure so that subquery optimizers no longer recognize apply nodes they can handle (they could also implicitly fix the plan, but I didn't notice that) 
* optimizers might decouple group expression (e.g: `1 IN (SELECT 1)`) from subquery apply node
* there are more implicit interdependencies which make it hard to fix the issue in current model (e.g: projecting `semijoin` symbol upward in `TransformUncorrelatedInPredicateSubqueryToSemiJoin` causes pruner to incorrectly rewrite `TableWriterNode`)

In order to address those issues I propose to to distinguish between apply node used in scalar context (e.g: `ScalarApplyNode`) and apply node used in grouping context (`GroupApplyNode`). The idea is that `*ApplyNode` always returns linear rows, which isn't the case in current model (e.g: apply node for `IN` expression logically returns set of row groups).

`ScalarApplyNode` would be basically current apply node, but during rewrite `EnforceSingleRow` should be implicitly added to subquery. Symbols produced by subquery can be directly used in downstream expressions (e.g: `non_subquery_symbol + subquery_symbol`).

`GroupApplyNode` would contain group expressions that operate on subquery (e.g: `non_subquery_symbol IN (local_subquery_symbol)`, where `subquery_symbol -> (SELECT column from table)`). This would make `GroupApplyNode` similar to `AggregationNode` in a sense that both contain set operations. Additionally, group expressions would be assigned to a linear symbol (e.g: `in_symbol_1 -> x IN (y)`), which can be referenced by downstream operators.

The proposed model has several advantages:
* optimizers don't have to much complex plan structure to recognize apply node they work on (code should be simpler)
* group expressions (e.g: `1 IN (SELECT x)`) are coupled with subqueries they operate on and cannot be separated in plan by other optimizers 
* there are no subquery symbols (e.g: `(SELECT 1)`) in global planner translation map so that expressions can't be incorrectly rewritten with a subquery (non-linear) symbol 
* apply node pruning is straight-forward: just remove node if it's subquery symbols are not used
* it should be possible to fix this issue since there is more plan flexibility

CC: @kokosing @martint

**Comment by sopel39** [comment]
I have refactored apply node in a similar way as discribed. Subquery code simplied. See PR: https://github.com/prestodb/presto/pull/6701

**Comment by sopel39** [comment]
fixed
