### ISSUE TITLE
Unable to start server when cassandra host is not resolvable

### ISSUE THREAD

**Issue by kokosing** [prestodb/presto#6639]
Unable to start presto with cassandra connector when cassandra host (`cassandra.contact-points` from `cassandra.properties`) is not resolvable to an IP.

``` 
2016-11-16T09:24:39.229Z	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: cassandra: unknown error
  at com.facebook.presto.cassandra.CassandraClientModule.createCassandraSession(CassandraClientModule.java:99)
  at com.facebook.presto.cassandra.CassandraClientModule.createCassandraSession(CassandraClientModule.java:99)
  while locating com.facebook.presto.cassandra.CassandraSession
Caused by: java.lang.IllegalArgumentException: cassandra: unknown error
	at com.datastax.driver.core.Cluster$Builder.addContactPoint(Cluster.java:839)
	at com.datastax.driver.core.Cluster$Builder.addContactPoints(Cluster.java:859)
	at com.facebook.presto.cassandra.CassandraClientModule.createCassandraSession(CassandraClientModule.java:106)
	at com.facebook.presto.cassandra.CassandraClientModule$$FastClassByGuice$$2bcb94b1.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:272)
	at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:172)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.cassandra.CassandraConnectorFactory.create(CassandraConnectorFactory.java:82)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:304)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:193)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:185)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:171)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:99)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:77)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:120)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

CC: @maciejgrzybek

**Comment by maciejgrzybek** [comment]
Can you provide more details how to repro it?
I tried with:
cassandra.properties:
```
connector.name=cassandra
cassandra.contact-points=cassandra
cassandra.schema-cache-ttl=0s
```

`cassandra` resolves to a valid IP but cassandra service is not running on that host.

```
2016-11-16T13:26:13.525Z	INFO	main	com.facebook.presto.metadata.StaticCatalogStore	-- Added catalog cassandra using connector cassandra --
...
2016-11-16T13:26:15.584Z	INFO	main	com.facebook.presto.server.PrestoServer	======== SERVER STARTED ========
```

**Comment by maciejgrzybek** [comment]
Okay, it turns out that the error above appears when host used in `contact-points` is not resolvable to an IP.
It has nothing to do with accessibility of cassandra service at all.

**Comment by maciejgrzybek** [comment]
Updated title and description to reflect my finding (https://github.com/prestodb/presto/issues/6639#issuecomment-260946780).

**Comment by maciejgrzybek** [comment]
#6642 is one of the possibilities I see to make it a bit better.

**Comment by maciejgrzybek** [comment]
Closing since #6642 was merged.

**Comment by kokosing** [comment]
Maciej is right. Cassandra Was down, but ip was also wrong.

śr., 16.11.2016, 14:31 użytkownik maciejgrzybek <notifications@github.com>
napisał:
