### ISSUE TITLE
Improve error categorization for InvalidProtocolBufferException in ORC file

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#6644]
This should probably be caught inside the ORC reader and rethrown as `OrcCorruptionException` so that it gets converted to `HIVE_BAD_DATA`.

```
PrestoExternalError: com.facebook.presto.spi.PrestoException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
 at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:159)
 at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:204)
 at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:239)
 at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
 at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
 at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
 at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
 at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
 at com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:89)
 at com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:720)
 at com.google.protobuf.CodedInputStream.isAtEnd(CodedInputStream.java:666)
 at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:99)
 at com.facebook.hive.orc.OrcProto$StringStatistics$Builder.mergeFrom(OrcProto.java:1345)
 at com.facebook.hive.orc.OrcProto$StringStatistics$Builder.mergeFrom(OrcProto.java:1225)
 at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:275)
 at com.facebook.hive.orc.OrcProto$ColumnStatistics$Builder.mergeFrom(OrcProto.java:2354)
 at com.facebook.hive.orc.OrcProto$ColumnStatistics$Builder.mergeFrom(OrcProto.java:2128)
 at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:275)
 at com.facebook.hive.orc.OrcProto$RowIndexEntry$Builder.mergeFrom(OrcProto.java:3151)
 at com.facebook.hive.orc.OrcProto$RowIndexEntry$Builder.mergeFrom(OrcProto.java:2980)
 at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:275)
 at com.facebook.hive.orc.OrcProto$RowIndex$Builder.mergeFrom(OrcProto.java:3651)
 at com.facebook.hive.orc.OrcProto$RowIndex$Builder.mergeFrom(OrcProto.java:3492)
 at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:300)
 at com.facebook.hive.orc.OrcProto$RowIndex.parseFrom(OrcProto.java:3469)
 at com.facebook.presto.orc.metadata.DwrfMetadataReader.readRowIndexes(DwrfMetadataReader.java:139)
 at com.facebook.presto.orc.StripeReader.readColumnIndexes(StripeReader.java:357)
 at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:134)
 at com.facebook.presto.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:383)
 at com.facebook.presto.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:340)
 at com.facebook.presto.orc.OrcRecordReader.nextBatch(OrcRecordReader.java:299)
 at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:135)
 ... 10 more

**Comment by aramesh117** [comment]
@electrum Can I take on this task? I don't have permissions to change the assignee. Thanks!

**Comment by electrum** [comment]
Sure!

**Comment by electrum** [comment]
Turns out this was already fixed.
