### ISSUE TITLE
Expected SliceVector, but got com.facebook.presto.orc.LongVector

### ISSUE THREAD

**Issue by sarvesh-du** [prestodb/presto#6686]
I am getting error for a simple query on presto-server-0.105

select count(distinct something) somecount , category category from table  where time_start >= 1475290800 and time_start <= 1479869999 and ( col in (2,4,8,16,32,64,128,256,512,1024,2048,4096,8192,16384,32768,65536,131072,262144,524288,1048576,2097152,4194304,8388608,16777216,33554432,67108864,134217728) ) group by category;

Caused by: com.facebook.presto.jdbc.internal.client.FailureInfo$FailureException: Expected SliceVector, but got com.facebook.presto.orc.LongVector
	at com.facebook.presto.hive.orc.OrcPageSource.propagateException(OrcPageSource.java:480) ~[?]
	at com.facebook.presto.hive.orc.OrcPageSource.access$200(OrcPageSource.java:81) ~[?]
	at com.facebook.presto.hive.orc.OrcPageSource$LazyLongBlockLoader.load(OrcPageSource.java:413) ~[?]
	at com.facebook.presto.hive.orc.OrcPageSource$LazyLongBlockLoader.load(OrcPageSource.java:389) ~[?]
	at com.facebook.presto.spi.block.LazyFixedWidthBlock.assureLoaded(LazyFixedWidthBlock.java:100) ~[?]
	at com.facebook.presto.spi.block.LazyFixedWidthBlock.isEntryNull(LazyFixedWidthBlock.java:62) ~[?]
	at com.facebook.presto.spi.block.AbstractFixedWidthBlock.isNull(AbstractFixedWidthBlock.java:170) ~[?]
	at com_facebook_presto_$gen_PageProcessor_126.filter(Unknown Source) ~[?]
	at com_facebook_presto_$gen_PageProcessor_126.process(Unknown Source) ~[?]
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:211) ~[?]
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:364) ~[?]
	at com.facebook.presto.operator.Driver.processFor(Driver.java:287) ~[?]
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:586) ~[?]
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505) ~[?]
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639) ~[?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_66]

**Comment by dain** [comment]
This happens when the schema of the table does not match the schema of the file.  In this case, you have a file that contains a VARCHAR column, and the table schema says it is a BIGINT column.  You will need to either correct the table schema or rewrite the file (using something like Hive).
