### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/facebook/presto/type/JsonPathType

### ISSUE THREAD

**Issue by hawkingrei** [prestodb/presto#6693]
i  am writing  a json plugin for presto 0.155,i find a error when i start presto with my plugin,like this:
```
java.lang.NoClassDefFoundError: com/facebook/presto/type/JsonPathType
	at cc.shanruifeng.functions.udfs.UdfPlugin.getFunctions(UdfPlugin.java:23)
	at com.facebook.presto.server.PluginManager.installPlugin(PluginManager.java:201)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:175)
	at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:158)
	at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:139)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:118)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.ClassNotFoundException: com.facebook.presto.type.JsonPathType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:76)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
can you help me ?

my code at https://github.com/hawkingrei/presto-third-functions

**Comment by electrum** [comment]
Starting in 0.153, the plugin classloader uses a whitelist model: plugins are only allowed to see classes that are explicitly part of the SPI. This prevents plugins from (accidentally or intentionally) relying on internal implementation details of Presto, which makes it easier for us to evolve Presto without breaking plugins.

The problem is the plugin has a dependency on `presto-main`, which is not part of the SPI. A plugin should only depend on `presto-main` in Maven `test` scope (if it wants to use the utility code from there for unit testing). All of the built-in plugins in Presto follow this model. `presto-ml` and `presto-teradata-functions` are good examples of plugins that provide functions and types.

You should be able to fix your function by replacing `@SqlType(JsonPathType.NAME)` with `@SqlType("JsonPath")`.

**Comment by electrum** [comment]
I also recommend updating your build to use https://github.com/prestodb/presto-maven-plugin

* Add a build plugin:
```xml
<build>
    <plugins>
        <plugin>
            <groupId>io.takari.maven.plugins</groupId>
            <artifactId>presto-maven-plugin</artifactId>
            <version>0.1.12</version>
            <extensions>true</extensions>
        </plugin>
    </plugins>
</build>
```
* Add `<packaging>presto-plugin</packaging>`
* Remove the shade plugin. The above will produce a ZIP file which can be unzipped in the server `plugin` directory.

**Comment by hawkingrei** [comment]
Thank you very much

but now, it can run in the presto.but when I test it 

`select json_array_extract_scalar(arr1, '$.book.id') from (values ('[{"book":{"id":"12"}}, {"book":{"id":"14"}}]')) t(arr1);`

presto tell me 

Exact implementation of json_array_extract do not match expected java types.

can you help me?

**Comment by Crossoverrr** [comment]
I met another problem, i developed a hbase connector. When i union data between hive table and hbase table, if table contains ArrayType column, i got error because these two columns in hive and hbase table are not the same classloader.
