### ISSUE TITLE
return empty if you select hive external table by using webhdfs

### ISSUE THREAD

**Issue by wyukawa** [prestodb/presto#6697]
Hi

I use presto 0.157 + jdk1.8.0_101 + HDP 2.1 + hive connector + CentOS 6.5.

I create external hive table with remote location by using webhdfs.
```
CREATE EXTERNAL TABLE hoge (
       ...
)
PARTITIONED BY (...)
STORED AS RCFILE
LOCATION
	'webhdfs://...'
```

But query result is empty.

```
select * from hoge limit 10
```

presto server.log is as follows.
```
java.lang.NoClassDefFoundError: javax/ws/rs/core/MediaType
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem.jsonParse(WebHdfsFileSystem.java:328)
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem$FsPathResponseRunner.getResponse(WebHdfsFileSystem.java:761)
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner.runWithRetry(WebHdfsFileSystem.java:625)
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner.access$100(WebHdfsFileSystem.java:472)
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner$1.run(WebHdfsFileSystem.java:502)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem$AbstractRunner.run(WebHdfsFileSystem.java:498)
        at org.apache.hadoop.hdfs.web.WebHdfsFileSystem.listStatus(WebHdfsFileSystem.java:1330)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1517)
        at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1557)
        at org.apache.hadoop.fs.FileSystem$4.<init>(FileSystem.java:1714)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1713)
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1696)
        at com.facebook.presto.hadoop.HadoopFileSystem.listLocatedStatus(HadoopFileSystem.java:30)
        at com.facebook.presto.hive.HadoopDirectoryLister.list(HadoopDirectoryLister.java:32)
        at com.facebook.presto.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:113)
        at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:86)
        at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:41)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:227)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:78)
        at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:179)
        at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
        at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$1(ResumableTasks.java:33)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

If I use hdfs://.. , it works well. But if presto supports webhdfs, it would be nice.
```
CREATE EXTERNAL TABLE hoge (
       ...
)
PARTITIONED BY (...)
STORED AS RCFILE
LOCATION
	'hdfs://...'
```

**Comment by wyukawa** [comment]
I know if I add some jars to use webhdfs this issue will be closed.
But if presto has the jars related to webhdfs, it would be great because users don't need to add jars.
