### ISSUE TITLE
NPE thrown from `Block.getLength`

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#6720]
Depending on the answer to this question, the fix will be very different: Is it legal for `Block.getLength` to throw NPE for a null position?

* If it is legal, every function in ArrayMinMaxUtils should be fixed.
* If it is not, `SliceArrayBlock.getLength` should be fixed.

```
com.facebook.presto.spi.PrestoException: GENERIC_INTERNAL_ERROR
        at com.facebook.presto.operator.scalar.ArrayMinMaxUtils.sliceArrayMinMax(ArrayMinMaxUtils.java:139)
        at com.facebook.presto.operator.scalar.ArrayMinFunction.sliceArrayMin(ArrayMinFunction.java:95)
        at com_facebook_presto_$gen_PageProcessor_143762.project_0(Unknown Source)
        at com_facebook_presto_$gen_PageProcessor_143762.process(Unknown Source)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:268)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.facebook.presto.spi.block.SliceArrayBlock.getLength(SliceArrayBlock.java:111)
        at com.facebook.presto.spi.type.VarcharType.getSlice(VarcharType.java:131)
        at com.facebook.presto.operator.scalar.ArrayMinMaxUtils.sliceArrayMinMax(ArrayMinMaxUtils.java:123)
        ... 12 more
```

**Comment by haozhun** [comment]
cc @dain, @cberner.

**Comment by dain** [comment]
I don't think the behavior is defined, so we could define it to return `0` for nulls.  Just add it to the block tests.

**Comment by haozhun** [comment]
Defining it to return 0 will have other problems. For example, `IntArrayList.getLength` always returns 4 today. Maybe we should just say it is illegal to call `getLength` and `getLong/...` when a position is null even though Block implementations don't necessarily throw exceptions in these cases.

**Comment by dain** [comment]
Sure, we could define the return value to be arbitrary.

**Comment by dain** [comment]
As you can tell, I don't have a strong opinion on this one.

**Comment by haozhun** [comment]
`Block.getLength` has been removed. All usages have either been removed, or migrated to `Block.getSliceLength`.
