### ISSUE TITLE
TestLocalBinarySpilledQueries fails with "Too many open files in system"

### ISSUE THREAD

**Issue by dain** [prestodb/presto#6735]
I consistently get this failure when running the tests on OSX.
```
testAssignUniqueId(com.facebook.presto.tests.TestLocalBinarySpilledQueries)  Time elapsed: 2.7 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT count(*) FROM (SELECT * FROM (   SELECT (SELECT count(*) WHERE c = 1)    FROM (SELECT CASE orderkey WHEN 1 THEN orderkey ELSE 1 END        FROM (SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem UNION ALL SELECT * FROM lineitem)) o(c)) result(a) WHERE a = 1)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:85)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:108)
	at com.facebook.presto.tests.AbstractTestQueries.testAssignUniqueId(AbstractTestQueries.java:7738)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.facebook.presto.spi.PrestoException: Failed to read spilled pages
	at com.facebook.presto.spiller.BinaryFileSpiller.readPages(BinaryFileSpiller.java:121)
	at com.facebook.presto.spiller.BinaryFileSpiller.lambda$getSpills$1(BinaryFileSpiller.java:109)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.spiller.BinaryFileSpiller.getSpills(BinaryFileSpiller.java:110)
	at com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder.mergeFromDisk(SpillableHashAggregationBuilder.java:239)
	at com.facebook.presto.operator.aggregation.builder.SpillableHashAggregationBuilder.buildResult(SpillableHashAggregationBuilder.java:170)
	at com.facebook.presto.operator.HashAggregationOperator.getOutput(HashAggregationOperator.java:421)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.process(Driver.java:327)
	at com.facebook.presto.testing.LocalQueryRunner.executeInternal(LocalQueryRunner.java:508)
	at com.facebook.presto.testing.LocalQueryRunner.lambda$execute$2(LocalQueryRunner.java:473)
	at com.facebook.presto.transaction.TransactionBuilder.execute(TransactionBuilder.java:149)
	at com.facebook.presto.testing.LocalQueryRunner.inTransaction(LocalQueryRunner.java:485)
	at com.facebook.presto.testing.LocalQueryRunner.execute(LocalQueryRunner.java:473)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:82)
	... 15 more
Caused by: java.io.FileNotFoundException: /var/folders/fz/hxvyn4gd06vcggyw9hhr4fnr0000gp/T/presto/spills/presto-spill1292993305067446573/306.bin (Too many open files in system)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.facebook.presto.spiller.BinaryFileSpiller.readPages(BinaryFileSpiller.java:116)
	... 36 more
... Removed 11 stack frames
```

**Comment by electrum** [comment]
@erichwang hit this about five times in a row trying to release today

**Comment by nezihyigitbasi** [comment]
I hit this one too, in fact `testAssignUniqueId()` itself can reproduce this problem. I think what's happening is this test query creates a large number of drivers and all these drivers are closed in LocalQueryRunner::executeInternal() when *all* of them are done so the spill files that are read stay open until then (and hit the file descriptor limit).

**Comment by pnowojski** [comment]
There is also one more issue with this tests (GC time outs), I will take a look into how to fix both of this.
