### ISSUE TITLE
UnionNode symbol mapping failure

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#6778]
```
WITH temp AS (
  SELECT orderkey,
         partkey,
         suppkey,
         extendedprice
    FROM tpch.tiny.lineitem
)

SELECT NULL AS test,
     NULL AS orderkey,
     NULL AS partkey,
     SUM(extendedprice) AS extendedprice
FROM temp

UNION ALL

SELECT NULL AS test,
     ARBITRARY(orderkey) AS arbitrary_orderkey,
     NULL AS partkey,
     SUM(extendedprice) AS extendedprice
FROM temp
GROUP BY suppkey
```

results in

```
Query failed: Every source needs to map its symbols to an output UnionNode operation symbol
java.lang.IllegalArgumentException: Every source needs to map its symbols to an output UnionNode operation symbol
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at com.facebook.presto.sql.planner.plan.SetOperationNode.<init>(SetOperationNode.java:67)
        at com.facebook.presto.sql.planner.plan.UnionNode.<init>(UnionNode.java:36)
        at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitUnion(UnaliasSymbolReferences.java:584)
        at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitUnion(UnaliasSymbolReferences.java:117)
        at com.facebook.presto.sql.planner.plan.UnionNode.accept(UnionNode.java:42)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:96)
        at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitOutput(UnaliasSymbolReferences.java:473)
        at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitOutput(UnaliasSymbolReferences.java:117)
        at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
        at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:28)
        at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences.optimize(UnaliasSymbolReferences.java:114)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:292)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by raghavsethi** [comment]
Appears to be introduced by commits in this PR: https://github.com/prestodb/presto/commit/32ba4feb8c9fec5a2e04a982b58bb5de3947e445

**Comment by martint** [comment]
This is already fixed.
