### ISSUE TITLE
NPE with transform() function

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#6781]
```
presto:nyigitbasi> select transform(ARRAY [1], t -> 0);
Query 20161206_201548_00002_xpk9i failed: null
java.lang.NullPointerException
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteLambdaExpression(TranslationMap.java:281)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteLambdaExpression(TranslationMap.java:222)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitLambdaExpression(ExpressionTreeRewriter.java:561)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitLambdaExpression(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:58)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:547)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:109)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.defaultRewrite(ExpressionTreeRewriter.java:55)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteExpression(TranslationMap.java:226)
	at com.facebook.presto.sql.planner.TranslationMap$2.rewriteExpression(TranslationMap.java:222)
	at com.facebook.presto.sql.tree.ExpressionRewriter.rewriteFunctionCall(ExpressionRewriter.java:105)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:476)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:109)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewriteWith(ExpressionTreeRewriter.java:34)
	at com.facebook.presto.sql.planner.TranslationMap.translateNamesToSymbols(TranslationMap.java:221)
	at com.facebook.presto.sql.planner.TranslationMap.rewrite(TranslationMap.java:111)
	at com.facebook.presto.sql.planner.PlanBuilder.rewrite(PlanBuilder.java:84)
	at com.facebook.presto.sql.planner.QueryPlanner.handleSubqueries(QueryPlanner.java:689)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:152)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:420)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:94)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:226)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:121)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:413)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:94)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:92)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:356)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:160)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:141)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:116)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:292)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by haozhun** [comment]
Fixed in 8890651. Thank you for trying it out!
