### ISSUE TITLE
Presto Hive Connectivity on MapR

### ISSUE THREAD

**Issue by manishkaushik29** [prestodb/presto#6790]
I am trying to query Hive queries from Presto on MapR. I am getting following error while launching the Presto Server :
3 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:
 
1) Configuration property 'http-server.http.port=8080 ' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)
 
2) Error: Could not coerce value '8080 ' to int (property 'http-server.http.port') in order to call [public io.airlift.http.server.HttpServerConfig io.airlift.http.server.HttpServerConfig.setHttpPort(int)]
  at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:74)
 
3) Error: Invalid configuration property node.id: is malformed (for class io.airlift.node.NodeConfig.nodeId)
  at io.airlift.node.NodeModule.configure(NodeModule.java:34)
 
3 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:116)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

Please Suggest

**Comment by petroav** [comment]
@manishkaushik29 there's currently no support for MapR. There was a pull request a while back (https://github.com/prestodb/presto/pull/1669) but it's outdated at this point. Myself along with @akshatnair are working on getting support for MapR so stay tuned.

**Comment by petroav** [comment]
Closing this in favor of https://github.com/prestodb/presto/issues/7189.
