### ISSUE TITLE
ClassCastException in presto-cli with map_filter

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#6803]
```
presto:nyigitbasi> select map_filter(map(ARRAY[row(1,2,3)], ARRAY[1]), (k,v) -> k.field0 > 0);
java.lang.RuntimeException: Error fetching next at http://localhost:8080/v1/statement/20161208_050916_00035_vpfve/2 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={Vary=[Accept-Encoding, User-Agent], Content-Length=[2365], Date=[Thu, 08 Dec 2016 05:09:16 GMT], X-Content-Type-Options=[nosniff], Content-Type=[application/json]}, hasValue=false, value=null} [Error: {"id":"20161208_050916_00035_vpfve","infoUri":"http://localhost:8080/query.html?20161208_050916_00035_vpfve","partialCancelUri":"http://192.168.1.4:8080/v1/stage/20161208_050916_00035_vpfve.0","nextUri":"http://localhost:8080/v1/statement/20161208_050916_00035_vpfve/3","columns":[{"name":"_col0","type":"map(row(field0 integer,field1 integer,field2 integer),integer)","typeSignature":{"rawType":"map","typeArguments":[{"rawType":"row","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["field0","field1","field2"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field0","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field1","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field2","typeSignature":"integer"}}]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"row","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["field0","field1","field2"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field0","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field1","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field2","typeSignature":"integer"}}]}},{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]}}],"data":[[{"[1, 2, 3]":1}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[]}}}
]
	at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:346)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:296)
	at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:121)
	at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:123)
	at com.facebook.presto.cli.Query.renderOutput(Query.java:107)
	at com.facebook.presto.cli.Console.process(Console.java:296)
	at com.facebook.presto.cli.Console.runConsole(Console.java:236)
	at com.facebook.presto.cli.Console.run(Console.java:141)
	at com.facebook.presto.cli.Presto.main(Presto.java:32)
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.client.QueryResults from JSON response:
[{"id":"20161208_050916_00035_vpfve","infoUri":"http://localhost:8080/query.html?20161208_050916_00035_vpfve","partialCancelUri":"http://192.168.1.4:8080/v1/stage/20161208_050916_00035_vpfve.0","nextUri":"http://localhost:8080/v1/statement/20161208_050916_00035_vpfve/3","columns":[{"name":"_col0","type":"map(row(field0 integer,field1 integer,field2 integer),integer)","typeSignature":{"rawType":"map","typeArguments":[{"rawType":"row","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["field0","field1","field2"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field0","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field1","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field2","typeSignature":"integer"}}]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":[],"arguments":[{"kind":"TYPE_SIGNATURE","value":{"rawType":"row","typeArguments":[{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]},{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}],"literalArguments":["field0","field1","field2"],"arguments":[{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field0","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field1","typeSignature":"integer"}},{"kind":"NAMED_TYPE_SIGNATURE","value":{"name":"field2","typeSignature":"integer"}}]}},{"kind":"TYPE_SIGNATURE","value":{"rawType":"integer","typeArguments":[],"literalArguments":[],"arguments":[]}}]}}],"data":[[{"[1, 2, 3]":1}]],"stats":{"state":"RUNNING","queued":false,"scheduled":true,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"rootStage":{"stageId":"0","state":"RUNNING","done":false,"nodes":1,"totalSplits":17,"queuedSplits":17,"runningSplits":0,"completedSplits":0,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":0,"processedBytes":0,"subStages":[]}}}
]
	at io.airlift.http.client.FullJsonResponseHandler$JsonResponse.<init>(FullJsonResponseHandler.java:121)
	at io.airlift.http.client.FullJsonResponseHandler.handle(FullJsonResponseHandler.java:68)
	at io.airlift.http.client.FullJsonResponseHandler.handle(FullJsonResponseHandler.java:37)
	at io.airlift.http.client.jetty.JettyHttpClient.execute(JettyHttpClient.java:377)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:283)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON bytes for [simple type, class com.facebook.presto.client.QueryResults]
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:201)
	at io.airlift.http.client.FullJsonResponseHandler$JsonResponse.<init>(FullJsonResponseHandler.java:118)
	... 11 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.facebook.presto.client.QueryResults, problem: Cannot cast java.lang.String to java.util.List
 at [Source: [B@420bc288; line: 1, column: 2364]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:268)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1405)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:468)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:487)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:224)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2950)
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:198)
	... 12 more
Caused by: java.lang.ClassCastException: Cannot cast java.lang.String to java.util.List
	at java.lang.Class.cast(Class.java:3369)
	at com.facebook.presto.client.QueryResults.fixValue(QueryResults.java:255)
	at com.facebook.presto.client.QueryResults.fixValue(QueryResults.java:249)
	at com.facebook.presto.client.QueryResults.fixData(QueryResults.java:221)
	at com.facebook.presto.client.QueryResults.<init>(QueryResults.java:93)
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 21 more
Query is gone (server restarted?)
```

**Comment by electrum** [comment]
This is actually a long-standing client protocol issue caused by maps that contain a non-scalar key:
```sql
select map(ARRAY[row(1,2,3)], ARRAY[1]);
