### ISSUE TITLE
Dropping any view in the Hive catalog results in an error.

### ISSUE THREAD

**Issue by BigDataDaddy** [prestodb/presto#6810]
It appears that dropping any view in the Hive catalog results in an error.    These symptoms have already been discussed briefly with Dain in the Google Group thread: https://groups.google.com/forum/#!msg/presto-users/lL4yHAvX7ps/x6OcGdyXBQAJ

In this use case the "hive" catalog is a Hive catalog serviced by the Hive metastore service on the same cluster node as the Presto coordinator.  Both are running on an AWS EMR 5.0.0 cluster.  Presto (v0.150) and Hive (v2.1.0) versions are documented here: http://docs.aws.amazon.com//ElasticMapReduce/latest/ReleaseGuide/emr-5.0.3/emr-release-components.html.  The Hive metastore DB is an off cluster AWS RDS PostgreSQL instance running PostgreSQL 9.5.4.

The mimimal SQL statement sequence to reproduce the problem is:

In Presto CLI:

1. create table hive.presto_test.test_tbl (col1 integer, col2 varchar(10));
2. describe hive.presto_test.test_tbl;
3. <confirm 2 columns in table>
4. insert into hive.presto_test.test_tbl values (1,'string1'),(2,'string2');
5. select * from hive.presto_test.test_tbl ;
6. <confirm 2 inserted rows with 2 columns in result set>
7. create view hive.presto_test.test_view as select * from hive.presto_test.test_tbl ;
8. show columns from hive.presto_test.test_view;
9. <confirm 2 columns in view projected from table>
10. select * from hive.presto_test.test_view;
11. <confirm 2 rows with 2 columns in result set>
12. drop view hive.presto_test.test_view;
13. <results in error: Query 20161207_165150_00018_c6dic failed: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: NULL::character%20varying>

In the Presto CLI with --debug enabled the stack trace from the DROP VIEW... is:

presto> drop view hive.presto_test.test_view;
Query 20161207_165833_00019_c6dic failed: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: NULL::character%20varying
com.facebook.presto.spi.PrestoException: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: NULL::character%20varying
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:491)
        at com.facebook.presto.hive.HiveMetadata.dropView(HiveMetadata.java:1278)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.dropView(ClassLoaderSafeConnectorMetadata.java:241)
        at com.facebook.presto.metadata.MetadataManager.dropView(MetadataManager.java:671)
        at com.facebook.presto.execution.DropViewTask.execute(DropViewTask.java:57)
        at com.facebook.presto.execution.DropViewTask.execute(DropViewTask.java:32)
        at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:104)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: NULL::character%20varying
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$drop_table_result$drop_table_resultStandardScheme.read(ThriftHiveMetastore.java:31054)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$drop_table_result$drop_table_resultStandardScheme.read(ThriftHiveMetastore.java:31031)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$drop_table_result.read(ThriftHiveMetastore.java:30973)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_drop_table(ThriftHiveMetastore.java:1109)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.drop_table(ThriftHiveMetastore.java:1094)
        at com.facebook.presto.hive.ThriftHiveMetastoreClient.dropTable(ThriftHiveMetastoreClient.java:98)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.lambda$dropTable$7(CachingHiveMetastore.java:482)
        at com.facebook.presto.hive.metastore.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
        at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:136)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropTable(CachingHiveMetastore.java:480)
        ... 10 more
presto>

**Comment by electrum** [comment]
Thanks the report with detailed steps! This is strange as the error comes from the Hive metastore.

We actually haven't done much (or any?) testing against Hive 2.x. Would you be able to verify if this also occurs on Hive 1.x?

**Comment by BigDataDaddy** [comment]
As I mentioned in my original post, our Presto/Hive environment is provisioned by AWS EMR.  

As such we are limited in the combinations of Presto and Hive that specific EMR versions install.  This issue was reported against an AWS EMR 5.0.0 cluster, which installs Presto (v0.150) and Hive (v2.1.0) versions.  We'd have to revert to an earlier EMR 4.x version, the last of which was EMR 4.7.2 (or earlier), to get to a Hive 1.0.0 version.  FWIW, all versions of EMR 4.x included Hive v.1.0.0, but the Presto version changed every EMR release.  So, doing so would also include reverting to the Presto version that is installed by an earlier EMR version, for EMR 4.7.2 this would be Presto 0.148.  

Would results from an earlier Presto version, 0.148 or prior, be helpful?
