### ISSUE TITLE
Planning issue when using lambda expression

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6873]
```sql
SELECT filter(m, v -> v = 1)
FROM (SELECT array[] m)
```

Fails with:

```
java.lang.IllegalStateException: Cannot resolve symbol expr
	at com.google.common.base.Preconditions.checkState(Preconditions.java:197)
	at com.facebook.presto.sql.planner.ExpressionSymbolInliner.rewriteSymbolReference(ExpressionSymbolInliner.java:39)
	at com.facebook.presto.sql.planner.ExpressionSymbolInliner.rewriteSymbolReference(ExpressionSymbolInliner.java:25)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitSymbolReference(ExpressionTreeRewriter.java:794)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitSymbolReference(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.SymbolReference.accept(SymbolReference.java:38)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitCast(ExpressionTreeRewriter.java:768)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitCast(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.Cast.accept(Cast.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitComparisonExpression(ExpressionTreeRewriter.java:206)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitComparisonExpression(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:68)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitLambdaExpression(ExpressionTreeRewriter.java:567)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitLambdaExpression(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:58)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:547)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter$RewritingVisitor.visitFunctionCall(ExpressionTreeRewriter.java:58)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:109)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewrite(ExpressionTreeRewriter.java:46)
	at com.facebook.presto.sql.tree.ExpressionTreeRewriter.rewriteWith(ExpressionTreeRewriter.java:29)
	at com.facebook.presto.sql.planner.optimizations.MergeProjections$Rewriter.visitProject(MergeProjections.java:68)
	at com.facebook.presto.sql.planner.optimizations.MergeProjections$Rewriter.visitProject(MergeProjections.java:55)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:28)
	at com.facebook.presto.sql.planner.optimizations.MergeProjections.optimize(MergeProjections.java:52)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:131)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:88)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:119)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:103)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:59)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:73)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:56)
	at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:51)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:59)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:285)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by haozhun** [comment]
Fixed in #6836
