### ISSUE TITLE
Selecting rows in Cassandra with empty blobs throws exception. 

### ISSUE THREAD

**Issue by crcunningham** [prestodb/presto#6879]
I'm using the Cassandra connector and Presto version 0.147. 

In Cassandra I have a table with a blob column in which some rows are set to an empty buffer value. For example,

` 
column_name
-----
  0x
`

If I run a select statement that includes that row I get the following exception: 

`java.lang.IllegalArgumentException: Invalid size: 0
	at io.airlift.slice.Slice.<init>(Slice.java:245)
	at io.airlift.slice.Slices.wrappedBuffer(Slices.java:120)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:191)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:151)
	at com.facebook.presto.cassandra.CassandraRecordCursor.getSlice(CassandraRecordCursor.java:122)
	at com_facebook_presto_$gen_CursorProcessor_132.project_0(Unknown Source)
	at com_facebook_presto_$gen_CursorProcessor_132.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:215)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2016-12-14T03:03:32.145Z	ERROR	remote-task-callback-4186	com.facebook.presto.execution.StageStateMachine	Stage 20161214_030331_00047_e2v33.1 failed
java.lang.IllegalArgumentException: Invalid size: 0
	at io.airlift.slice.Slice.<init>(Slice.java:245)
	at io.airlift.slice.Slices.wrappedBuffer(Slices.java:120)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:191)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:151)
	at com.facebook.presto.cassandra.CassandraRecordCursor.getSlice(CassandraRecordCursor.java:122)
	at com_facebook_presto_$gen_CursorProcessor_132.project_0(Unknown Source)
	at com_facebook_presto_$gen_CursorProcessor_132.process(Unknown Source)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:215)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

It seems like I should be able to run this query successfully.

**Comment by delding** [comment]
this is because Slice is not allowed to be constructed with byte[0]
