### ISSUE TITLE
Analysis regression in ORDER BY queries

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#6882]
This query:
```
select x, sum(cast(x as double))
from (values '1.0') t(x)
group by x
order by sum(cast(x as double))
```

fails with the following error:
```
Caused by: java.lang.IllegalArgumentException: Expression not analyzed: CAST("x" AS double)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.analyzer.Analysis.getTypeWithCoercions(Analysis.java:174)
	at com.facebook.presto.sql.planner.QueryPlanner.project(QueryPlanner.java:291)
	at com.facebook.presto.sql.planner.QueryPlanner.aggregate(QueryPlanner.java:399)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:144)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:430)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:93)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:125)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:226)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:121)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:423)
	at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:93)
```

I bisected this to a regression introduced by ec2e8976ba9cd59f3990b8e46288b8a728065b07

**Comment by sopel39** [comment]
I think it's due to StatementAnalyzer::extractAggregates, which extracts unrewritten sort keys from QuerySpecification, see: https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/sql/analyzer/StatementAnalyzer.java#L1687.
Those sort keys should be rewritten to use projection output. I will test tomorrow if that's the issue and post some bugfix.
