### ISSUE TITLE
Integer overflow with IN and doubles.

### ISSUE THREAD

**Issue by ch-nikhodgkinson** [prestodb/presto#6901]
```
presto> with table2 (id2) as (values 1,1,2,2,3,3,4,4,5,5,6,6,7,8,9,10), table1 (id1) as (values 1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0) select * from table1 where id1 in (select id2 from table2 group by id2 having count(*) > 1);

Query 20161212_224603_01571_dvnc7, FAILED, 2 nodes
Splits: 7 total, 3 done (42.86%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20161212_224603_01571_dvnc7 failed: integer overflow
```

**Comment by electrum** [comment]
Full stack trace (use `--debug` in CLI):
```java
java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011)
	at com.facebook.presto.spi.block.LongArrayBlock.getInt(LongArrayBlock.java:111)
	at com.facebook.presto.spi.type.AbstractIntType.hash(AbstractIntType.java:91)
	at com_facebook_presto_$gen_PagesHashStrategy_921.hashRow(Unknown Source)
	at com.facebook.presto.operator.MultiChannelGroupByHash.contains(MultiChannelGroupByHash.java:220)
	at com.facebook.presto.operator.ChannelSet.contains(ChannelSet.java:62)
	at com.facebook.presto.operator.HashSemiJoinOperator.addInput(HashSemiJoinOperator.java:180)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:384)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sopel39** [comment]
fixed by: https://github.com/prestodb/presto/pull/6808
```
presto:sf0.1> with table2 (id2) as (values 1,1,2,2,3,3,4,4,5,5,6,6,7,8,9,10), table1 (id1) as (values 1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0) select * from table1 where id1 in (select id2 from table2 group by id2 having count(*) > 1);
 id1 
-----
 1.0 
 2.0 
 3.0 
 4.0 
 5.0 
 6.0 
(6 rows)
```

**Comment by electrum** [comment]
Simpler reproduction:
```sql
select * from (values 1.0,2.0,3.0) as t(id) where t.id in (select u.id from (values 1,2) as u(id));

**Comment by martint** [comment]
Fixed
