### ISSUE TITLE
GetTableLayout in HiveMetadata takes forever to create predicates

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#6970]
Depending on the order of results from the metastore, we may end up doing a n^2 computation to create predicates. This appears to be introduced by 7ea59dd37eef00e1a2d47cecad9f1eef1b4a772a

If the metastore is unable to prune partitions for us, we can spend several minutes in the planning state.

Here's a representative jstack (code as of 0.161):

```
        at com.facebook.presto.spi.predicate.Marker.compareTo(Marker.java:231)
        at com.facebook.presto.spi.predicate.Range.overlaps(Range.java:153)
        at com.facebook.presto.spi.predicate.SortedRangeSet$Builder.build(SortedRangeSet.java:409)
        at com.facebook.presto.spi.predicate.SortedRangeSet.union(SortedRangeSet.java:269)
        at com.facebook.presto.spi.predicate.SortedRangeSet.union(SortedRangeSet.java:43)
        at com.facebook.presto.spi.predicate.Domain.union(Domain.java:179)
        at com.facebook.presto.hive.HiveMetadata$$Lambda$732/1213488507.apply(Unknown Source)
        at java.util.HashMap.merge(HashMap.java:1245)
        at com.facebook.presto.hive.HiveMetadata.createPredicate(HiveMetadata.java:1125)
        at com.facebook.presto.hive.HiveMetadata.getTableLayout(HiveMetadata.java:1072)
        at com.facebook.presto.hive.PrismMetadata.getTableLayout(PrismMetadata.java:340)
        at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getTableLayout(ClassLoaderSafeConnectorMetadata.java:77)
        at com.facebook.presto.metadata.MetadataManager.getLayout(MetadataManager.java:312)
        at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.visitTableScan(PropertyDerivations.java:580)
        at com.facebook.presto.sql.planner.optimizations.PropertyDerivations$Visitor.visitTableScan(PropertyDerivations.java:124)
        at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
```

**Comment by raghavsethi** [comment]
@martint @electrum here's a test that repros it: https://gist.github.com/raghavsethi/90eeb3c014075687114124c4af118082
