### ISSUE TITLE
Bad error message when lamba expression doesn't match expected signature

### ISSUE THREAD

**Issue by martint** [prestodb/presto#6981]
```sql
SELECT filter(a, (k, v) -> true) 
FROM (VALUES array[1]) t(a)
```

fails with:

```
Query 20161229_202204_00006_suq2a failed: null
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.lambda$visitFunctionCall$1(ExpressionAnalyzer.java:795)
	at com.facebook.presto.sql.analyzer.TypeSignatureProvider.getTypeSignature(TypeSignatureProvider.java:61)
	at com.facebook.presto.metadata.SignatureBinder$FunctionSolver.update(SignatureBinder.java:725)
	at com.facebook.presto.metadata.SignatureBinder.iterativeSolve(SignatureBinder.java:399)
	at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:114)
	at com.facebook.presto.metadata.SignatureBinder.bind(SignatureBinder.java:91)
	at com.facebook.presto.metadata.FunctionRegistry.identifyApplicableFunctions(FunctionRegistry.java:692)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunction(FunctionRegistry.java:661)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunctionExact(FunctionRegistry.java:651)
	at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:606)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:821)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:255)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:111)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:274)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1408)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeExpression(StatementAnalyzer.java:1791)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeSelect(StatementAnalyzer.java:1612)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:785)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:187)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:549)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:187)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:68)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:285)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ebyhr** [comment]
I think this is resolved by 538d90bb6455af3c4bdc632fc8391d55ff876760.

Following is the error message with latest build.
```
presto:default> SELECT filter(a, (k, v) -> true) 
             -> FROM (VALUES array[1]) t(a);
Query 20170611_070303_00000_bc97k failed: line 1:18: Expected a lambda that takes 1 argument(s) but got 2
SELECT filter(a, (k, v) -> true)
FROM (VALUES array[1]) t(a)

````
