### ISSUE TITLE
Raptor system.tables throws NPE on non-existant table

### ISSUE THREAD

**Issue by erichwang** [prestodb/presto#7014]
presto:baldr> SELECT * FROM raptor.system.tables WHERE table_name = 'does_not_exist';

Query 20170106_200150_59222_asbmw failed: null
java.lang.NullPointerException
	at com.facebook.presto.split.MappedPageSource.getNextPage(MappedPageSource.java:67)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:248)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:534)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:670)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by AlekseiS** [comment]
Cannot reproduce it in the current master. Tried a unit test and local setup.
