### ISSUE TITLE
Planning failure for correlated subquery

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7064]
This query:

```sql
select
(
    select avg(custkey)
    from tpch.tiny.orders c2
    where c2.orderkey = c1.orderkey
),
(
    select avg(custkey)
    from tpch.tiny.orders c3
    where c3.orderkey = c1.orderkey
)
from tpch.tiny.orders c1
```

fails during planning with:

```
java.lang.IllegalArgumentException: Invalid node. Expression dependencies ([custkey_1]) not in source plan output ([orderkey, unique, $hashvalue_45, avg])
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:620)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.access$100(ValidateDependenciesChecker.java:77)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:257)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:91)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAssignUniqueId(ValidateDependenciesChecker.java:565)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAssignUniqueId(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.AssignUniqueId.accept(AssignUniqueId.java:73)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitJoin(ValidateDependenciesChecker.java:333)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitJoin(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:171)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:250)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:91)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:117)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:205)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:469)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:209)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:117)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitAggregation(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:205)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:250)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:91)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:469)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:209)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:300)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:91)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:88)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:83)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:44)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:44)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:127)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:292)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:271)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
cc @sopel39, @kokosing
