### ISSUE TITLE
Support UTF8 ORC bloom filters

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7120]
Bloom filters in ORC files used local encoding for String and Decimal columns. Hive community recognized the problem and updated ORC file spec with new type of Bloom filter (BLOOM_FILTER_UTF8, stream kind 8). It should be incorporated into Presto too.

Hive issue:
https://issues.apache.org/jira/browse/ORC-101
Hive PR:
https://github.com/apache/orc/pull/60

**Comment by sadowski** [comment]
Quick note on this issue: Hive now allows for one of two options when writing ORC files 1) the new utf8 format only is written (`orc.bloom.filter.write.version=utf8`), or 2) both the new uft8 format and the old format are written (`orc.bloom.filter.write.version=original`). Since both of these options write the new utf8 format into the ORC file, when Presto reads these files it throws a `BLOOM_FILTER_UTF8 stream type not implemented yet` exception.

I noticed this issue with AWS EMR 5.8.0, when generating files with the upgraded Hive 2.3.0 version, the Presto 1.7.0 version was unable to read the new files. The issue went away when I regenerated the table without the bloom filter.

**Comment by jmason** [comment]
I've run into this, too.  It would be great at least for Presto to quietly ignore BLOOM_FILTER_UTF8 streams so it can still handle Orc files with the "original" version.

**Comment by sopel39** [comment]
This seems like an important issue, FYI: @martint @dain

**Comment by jmason** [comment]
I have a hacky workaround for Hadoop writers using org.apache.orc.mapreduce.OrcOutputFormat btw -- if anyone would like to see it, drop a comment and I'll stick it up as a gist.

**Comment by sbtgn1** [comment]
even on emr 5.11 presto 1.87 this is still not supported , is there a jira on presto about this?

**Comment by ashwinhs** [comment]
Any updates on this issue? Did we fix this as a part any newer releases?

**Comment by dain** [comment]
Here is a stack from the user
```
com.facebook.presto.spi.PrestoException: BLOOM_FILTER_UTF8 stream type not implemented yet
       at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:159)
       at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:204)
       at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:265)
       at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
       at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
       at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
       at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
       at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
       at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
       at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
       at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
       at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: BLOOM_FILTER_UTF8 stream type not implemented yet
       at com.facebook.presto.orc.metadata.OrcMetadataReader.toStreamKind(OrcMetadataReader.java:474)
       at com.facebook.presto.orc.metadata.OrcMetadataReader.toStream(OrcMetadataReader.java:152)
       at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
       at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
       at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
       at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:699)
       at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
       at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
       at com.facebook.presto.orc.metadata.OrcMetadataReader.toStream(OrcMetadataReader.java:157)
       at com.facebook.presto.orc.metadata.OrcMetadataReader.readStripeFooter(OrcMetadataReader.java:147)
       at com.facebook.presto.orc.StripeReader.readStripeFooter(StripeReader.java:331)
       at com.facebook.presto.orc.StripeReader.readStripe(StripeReader.java:105)
       at com.facebook.presto.orc.OrcRecordReader.advanceToNextStripe(OrcRecordReader.java:388)
       at com.facebook.presto.orc.OrcRecordReader.advanceToNextRowGroup(OrcRecordReader.java:345)
       at com.facebook.presto.orc.OrcRecordReader.nextBatch(OrcRecordReader.java:304)
       at com.facebook.presto.hive.orc.OrcPageSource.getNextPage(OrcPageSource.java:135)
       ... 14 more
```

**Comment by rabinnh** [comment]
Just ran into this as well.

**Comment by sopel39** [comment]
@jmason could you create a PR? Would any of you guys attach a minimal ORC file (e.g: one row) that causes Presto to fail. This shouldn't be a difficult fix, but having a file would definitely help.

Ping me on github or prestodb slack (user: `sopel39`) I will give you my mail then where you could send an email.

**Comment by jmason** [comment]
@brandond here you go: https://gist.github.com/jmason/015fbd242ec241d49fef76606a26058a

However it's worth noting that we had to avoid using Bloom filters in our ORC files when Athena was in use as it couldn't read them at all, regardless of whether they were original or UTF-8 format. That was a few months ago, though, so it may be fixed by now.

**Comment by jmason** [comment]
@sopel39 here you go -- a single-record UTF-8 Bloom filter-bearing ORC file: http://taint.org/x/2018/withutf8bloomfilter.orc

**Comment by brandond** [comment]
Thanks @jmason - I'm trying to figure out how to adapt that for my purposes since I'm mostly using Hive and I'm not sure how to override the writer that Hadoop uses natively. Hive seems to have its own ORC reader and writer which does not (as far as I can tell) write bloom filters at all, so clearly I'm barking up the wrong tree by trying to adapt it for use with Hive.

**Comment by brandond** [comment]
@sopel39 use the tools jar to poke at it: 
```
[user@host orc]$ java -jar orc-tools-1.4.3-uber.jar meta withutf8bloomfilter.orc
log4j:WARN No appenders could be found for logger (org.apache.hadoop.metrics2.lib.MutableMetricsFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Processing data file withutf8bloomfilter.orc [length: 1407]
Structure for withutf8bloomfilter.orc
File Version: 0.12 with ORC_135
Rows: 1
Compression: SNAPPY
Compression size: 131072
Type: struct<userid:string,time:bigint,s1:string>

Stripe Statistics:
  Stripe 1:
    Column 0: count: 1 hasNull: false
    Column 1: count: 1 hasNull: false min: u1 max: u1 sum: 2
    Column 2: count: 1 hasNull: false min: 1523634485465 max: 1523634485465 sum: 1523634485465
    Column 3: count: 1 hasNull: false min: 20180413T154805.463Z max: 20180413T154805.463Z sum: 20

File Statistics:
  Column 0: count: 1 hasNull: false
  Column 1: count: 1 hasNull: false min: u1 max: u1 sum: 2
  Column 2: count: 1 hasNull: false min: 1523634485465 max: 1523634485465 sum: 1523634485465
  Column 3: count: 1 hasNull: false min: 20180413T154805.463Z max: 20180413T154805.463Z sum: 20

Stripes:
  Stripe: offset: 3 data: 51 rows: 1 tail: 102 index: 978
    Stream: column 0 section ROW_INDEX start: 3 length 11
    Stream: column 1 section ROW_INDEX start: 14 length 30
    Stream: column 1 section BLOOM_FILTER start: 44 length 454
    Stream: column 1 section BLOOM_FILTER_UTF8 start: 498 length 394
    Stream: column 2 section ROW_INDEX start: 892 length 39
    Stream: column 3 section ROW_INDEX start: 931 length 50
    Stream: column 1 section DATA start: 981 length 5
    Stream: column 1 section LENGTH start: 986 length 6
    Stream: column 2 section DATA start: 992 length 11
    Stream: column 3 section DATA start: 1003 length 23
    Stream: column 3 section LENGTH start: 1026 length 6
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT_V2
    Encoding column 2: DIRECT_V2
    Encoding column 3: DIRECT_V2

File length: 1407 bytes
Padding length: 0 bytes
Padding ratio: 0%
________________________________________________________________________________________________________________________
```

**Comment by jmason** [comment]
Sorry @sopel39 , I didn't spot your question until now -- does the metadata posted by @brandond cover it?

**Comment by sopel39** [comment]
@jmason @brandond I need larger file with `BLOOM_FILTER_UTF8` stream.

I created table with:
```
CREATE TABLE foo (name varchar(100)) STORED AS ORC TBLPROPERTIES(
'orc.compress'='SNAPPY',
'orc.create.index'='true',
'orc.bloom.filter.columns'='name',
'orc.bloom.filter.fpp'='0.05',
'orc.bloom.filter.write.version'='utf8');
```
Is that correct settings to enable utf8 bloom filter stream?

Hive version: `Hive 1.2.1000.2.6.3.0-235`

**Comment by brandond** [comment]
All you should need to set is `orc.bloom.filter.columns`. `orc.bloom.filter.write.version` controls whether it writes both legacy and utf8 or only utf8; unfortunately there is no way to enable ONLY legacy which would be a nice work-around for this issue. Talk about breaking changes.

How are you loading data into the table? What does the ORC tool show on the resulting file?

**Comment by brandond** [comment]
So, I'm guessing this still hasn't been fixed?

**Comment by sopel39** [comment]
@brandond Presto can now read ORC files with UTF-8 bloom filters. I don't think it will take advantage of such filter though.

**Comment by brandond** [comment]
@sopel39 do you know the commit or release that fixed that? Not reading them is fine as long as it can at least open the files without blowing up.

**Comment by sopel39** [comment]
@brandond this is PR: https://github.com/prestodb/presto/pull/10424

**Comment by javafanboy** [comment]
It would have been very interesting to know the current status of this - ie do Presto/Athena make use of bloom filter for ORC table queries? Tried googling this just now but did not find anything useful?

**Comment by sdruzkin** [comment]
> CC: @sdruzkin would you know the answer to this?

The only place that seems to be using the HiveBloomFilter is [com.facebook.presto.orc.TupleDomainOrcPredicate#columnOverlaps](https://github.com/prestodb/presto/blob/master/presto-orc/src/main/java/com/facebook/presto/orc/TupleDomainOrcPredicate.java#L138), which checks singular values against the bloom filter loaded from the column stats. I'm not very familiar with how Presto populates and uses TupleDomainOrcPredicate and whether it leverages it or not.

**Comment by tdcmeehan** [comment]
According to https://github.com/prestodb/presto/commit/55c5817261fd1c3cab0a757ad1941f4d99814104, we still skip UTF_8 bloom filters.  This is a relatively straightforward change and we'd accept a patch adding this support.
