### ISSUE TITLE
Shard organization sporadically fails with invalid schema exception

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#7130]
```
2017-01-18T18:57:31.534-0800	INFO	shard-organization-discovery	com.facebook.presto.raptor.storage.organization.ShardOrganizationManager	Running shard organizer...
2017-01-18T18:57:31.559-0800	ERROR	shard-organization-discovery	com.facebook.presto.raptor.storage.organization.ShardOrganizationManager	Error running shard organizer
com.facebook.presto.spi.PrestoException: Failed to perform metadata operation
	at com.facebook.presto.raptor.util.DatabaseUtil.metadataError(DatabaseUtil.java:80)
	at com.facebook.presto.raptor.util.DatabaseUtil.lambda$onDemandDao$0(DatabaseUtil.java:54)
	at com.sun.proxy.$Proxy226.getOrganizationEligibleTables(Unknown Source)
	at com.facebook.presto.raptor.storage.organization.ShardOrganizationManager.discoverAndInitializeTablesToOrganize(ShardOrganizationManager.java:159)
	at com.facebook.presto.raptor.storage.organization.ShardOrganizationManager.lambda$startDiscovery$81(ShardOrganizationManager.java:145)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLException: Column "ORGANIZATION_ENABLED" not found; SQL statement:
SELECT table_id
FROM tables
WHERE organization_enabled
  AND table_id IN
       (SELECT table_id
        FROM columns
        WHERE sort_ordinal_position IS NOT NULL) [42122-189] [statement:"SELECT table_id
FROM tables
WHERE organization_enabled
  AND table_id IN
       (SELECT table_id
        FROM columns
        WHERE sort_ordinal_position IS NOT NULL)", located:"SELECT table_id
FROM tables
WHERE organization_enabled
  AND table_id IN
       (SELECT table_id
        FROM columns
        WHERE sort_ordinal_position IS NOT NULL)", rewritten:"SELECT table_id
FROM tables
WHERE organization_enabled
  AND table_id IN
       (SELECT table_id
        FROM columns
        WHERE sort_ordinal_position IS NOT NULL)", arguments:{ positional:{}, named:{}, finder:[]}]
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1308)
	at org.skife.jdbi.v2.Query.fold(Query.java:173)
	at org.skife.jdbi.v2.Query.list(Query.java:82)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing$IterableReturningThing.result(ResultReturnThing.java:255)
	at org.skife.jdbi.v2.sqlobject.ResultReturnThing.map(ResultReturnThing.java:48)
	at org.skife.jdbi.v2.sqlobject.QueryHandler.invoke(QueryHandler.java:45)
	at org.skife.jdbi.v2.sqlobject.SqlObject.invoke(SqlObject.java:175)
	at org.skife.jdbi.v2.sqlobject.SqlObject$1.intercept(SqlObject.java:75)
	at org.skife.jdbi.v2.sqlobject.CloseInternalDoNotUseThisClass$$EnhancerByCGLIB$$82d180db.getOrganizationEligibleTables(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.presto.raptor.util.DatabaseUtil.lambda$onDemandDao$0(DatabaseUtil.java:48)
	... 10 more
Caused by: org.h2.jdbc.JdbcSQLException: Column "ORGANIZATION_ENABLED" not found; SQL statement:
SELECT table_id
FROM tables
WHERE organization_enabled
  AND table_id IN
       (SELECT table_id
        FROM columns
        WHERE sort_ordinal_position IS NOT NULL) [42122-189]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:147)
	at org.h2.expression.ConditionAndOr.optimize(ConditionAndOr.java:130)
	at org.h2.command.dml.Select.prepare(Select.java:838)
	at org.h2.command.Parser.prepareCommand(Parser.java:246)
	at org.h2.engine.Session.prepareLocal(Session.java:461)
	at org.h2.engine.Session.prepareCommand(Session.java:403)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1188)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:72)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:276)
	at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:52)
	at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1304)
	... 23 more
```

**Comment by raghavsethi** [comment]
The table schema in MySQL has the column, and dropping and recreating the table does not change the error message.

**Comment by raghavsethi** [comment]
This was due to invalid local state.
