### ISSUE TITLE
Flaky TestMemoryManager.testNoLeak

### ISSUE THREAD

**Issue by ArturGajowy** [prestodb/presto#7205]
```
Tests run: 690, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 498.442 sec <<< FAILURE! - in TestSuite
testNoLeak(com.facebook.presto.memory.TestMemoryManager)  Time elapsed: 7.982 sec  <<< FAILURE!
java.lang.AssertionError: expected [843043140] but found [843055104]
	at com.facebook.presto.memory.TestMemoryManager.testNoLeak(TestMemoryManager.java:178)
	at com.facebook.presto.memory.TestMemoryManager.testNoLeak(TestMemoryManager.java:153)

2017-01-23 14:07:44 INFO Life cycle stopping...
2017-01-23 14:07:44 INFO Life cycle stopping...
2017-01-23 14:07:44 INFO Life cycle stopped.
2017-01-23 14:07:44 INFO Life cycle stopping...
2017-01-23 14:07:44 INFO Life cycle stopped.
2017-01-23 14:07:44 INFO Life cycle stopped.
2017-01-23 14:07:44 INFO Life cycle stopping...
2017-01-23 14:07:44 INFO Life cycle stopped.
2017-01-23 14:07:44 INFO Life cycle stopping...
2017-01-23 14:07:44 INFO Life cycle stopped.
2017-01-23 14:07:44 INFO Life cycle stopping...
2017-01-23 14:07:44 INFO Life cycle stopping...

Results :

Failed tests: 
  TestMemoryManager.testNoLeak:153->testNoLeak:178 expected [843043140] but found [843055104]
```

**Comment by electrum** [comment]
This might be related to https://github.com/prestodb/presto/issues/7053
