### ISSUE TITLE
Query with GROUP BY and DISTINCT on same field fails

### ISSUE THREAD

**Issue by cberner** [prestodb/presto#7214]
```
EXPLAIN SELECT x, count(1), count(distinct x)
FROM (values 1) t(x)
group by 1
```

```
java.lang.IllegalStateException: Duplicate key field
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.createGroupIdNode(OptimizeMixedDistinctAggregations.java:359)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitMarkDistinct(OptimizeMixedDistinctAggregations.java:216)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitMarkDistinct(OptimizeMixedDistinctAggregations.java:91)
	at com.facebook.presto.sql.planner.plan.MarkDistinctNode.accept(MarkDistinctNode.java:95)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitAggregation(OptimizeMixedDistinctAggregations.java:134)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitAggregation(OptimizeMixedDistinctAggregations.java:91)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:206)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
```

**Comment by martint** [comment]
This is a long-standing bug that surfaced when turning on `optimizer.optimize-mixed-distinct-aggregations`.

**Comment by wenleix** [comment]
The symbols are duplicated [here](https://github.com/prestodb/presto/blob/8566cce62b03a793698168df430e4e150967e443/presto-main/src/main/java/com/facebook/presto/sql/planner/optimizations/OptimizeMixedDistinctAggregations.java#L210)

            allSymbols.addAll(groupBySymbols);
            allSymbols.addAll(nonDistinctAggregateSymbols);
            allSymbols.add(distinctSymbol);


The code takes care when same symbols present in non-distinct and distinct symbols. However, it doesn't do other check such as same symbols present in groupBy and Distinct, groupBy and Non-Distinct. 

Example test query for overlap with GroupBy and Non-Distinct:

        EXPLAIN SELECT x, count(x), count(distinct y) FROM (values (1, 2)) t(x,y) group by 1;
