### ISSUE TITLE
Error "No page sink  for connector" on hive catalog

### ISSUE THREAD

**Issue by sj860908** [prestodb/presto#7330]
Hello, I am having trouble inserting data into table using hive catalog.

My query looks like ```insert into xxxxx select emd5 from yyyyyy```

I'm currently using presto version 152.3 and *.properties catalog file looks pretty plane.

```hive.s3.max-backoff-time=10m
hive.max-partitions-per-writers=400
hive.allow-drop-table=true
hive.s3.max-connections=500
hive.s3.max-error-retries=50
hive.metastore-refresh-interval=1m
hive.s3.staging-directory=/mnt/tmp/
hive.s3.socket-timeout=2m
hive.s3.max-client-retries=50
hive.metastore-cache-ttl=20m
hive.metastore.uri=thrift://************:9083
hive.s3.connect-timeout=2m
connector.name=hive-hadoop2```

When ever I launch above query, it returns this error.

```2017-02-06T13:09:10.489Z        ERROR   remote-task-callback-269616     com.facebook.presto.execution.StageStateMachine Stage 20170206_130911_01005_gbzj4.1 failed
java.lang.IllegalArgumentException: No page sink provider for connector 'profiles'
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
        at com.facebook.presto.split.PageSinkManager.providerFor(PageSinkManager.java:57)
        at com.facebook.presto.split.PageSinkManager.createPageSink(PageSinkManager.java:51)
        at com.facebook.presto.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:99)
        at com.facebook.presto.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:90)
        at com.facebook.presto.operator.DriverFactory.createDriver(DriverFactory.java:87)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:515)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.access$1400(SqlTaskExecution.java:490)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:616)
        at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
        at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)```

It is returning the same error from both hive version 0.13 and 2.1. Also I made sure it works if I run it directly inside of hive client.

I could not find any relevant issues anywhere, any help would be helpful. Thanks.

**Comment by cawallin** [comment]
Usually you get that issue when you don't have the .properties file on all of the nodes. Make sure that your hive connector is in a file called `profiles.properties` on all of the nodes in the cluster.

**Comment by sj860908** [comment]
Thanks. That was it.

What's the behavior of the nodes missing properties file? Would that worker not able to do any tasks?

Thanks again

**Comment by cawallin** [comment]
You get arbitrary failures because Presto assumes all of the workers have all of the relevant properties files. Glad that helped!
