### ISSUE TITLE
Query stuck in join filter function

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#7367]
We saw a worker not making progress on queries today. And noticed that the 59 of the worker's 64 threads are stuck in doing work for a query that had been abadoned.

Query is a very expensive cross join:
```
SELECT COUNT (*)
FROM (
  select id
  from dim_all
  where ...) a
INNER JOIN (
  SELECT LEAST(user1, user2) AS id1, greatest(user1, user2) AS id2
  FROM dim_r
  WHERE ...
  GROUP BY 1,2) b
ON (
  a.id=b.id1 
  OR a.id=b.id2)
LIMIT 10000
``` 

Two issue we need to fix here:
* remove getBlocks call from StandardJoinFilterFunction.filter
* make sure the driver gives up its thread after processing for a while. It was stuck in our cluster for 15 hours.

Stack trace below:
```
*_*_*_*vwf*.*.*-*-* (51 threads)
    at java.lang.Object.clone(Native Method)
    at com.facebook.presto.spi.Page.getBlocks(Page.java:88)
    at com.facebook.presto.operator.StandardJoinFilterFunction.filter(StandardJoinFilterFunction.java:64)
    at com.facebook.presto.operator.JoinHash.getNextJoinPositionFrom(JoinHash.java:90)
    at com.facebook.presto.operator.JoinHash.getJoinPosition(JoinHash.java:68)
    at com.facebook.presto.operator.SimpleJoinProbe.getCurrentJoinPosition(SimpleJoinProbe.java:119)
    at com.facebook.presto.operator.LookupJoinOperator.advanceProbePosition(LookupJoinOperator.java:213)
    at com.facebook.presto.operator.LookupJoinOperator.getOutput(LookupJoinOperator.java:148)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:555)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:691)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

*_*_*_*vwf*.*.*-*-* (8 threads)
    at java.lang.Object.clone(Native Method)
    at com.facebook.presto.spi.Page.getBlocks(Page.java:88)
    at com.facebook.presto.operator.StandardJoinFilterFunction.filter(StandardJoinFilterFunction.java:64)
    at com.facebook.presto.operator.JoinHash.getNextJoinPositionFrom(JoinHash.java:90)
    at com.facebook.presto.operator.JoinHash.getNextJoinPosition(JoinHash.java:85)
    at com.facebook.presto.operator.LookupJoinOperator.joinCurrentPosition(LookupJoinOperator.java:197)
    at com.facebook.presto.operator.LookupJoinOperator.getOutput(LookupJoinOperator.java:147)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
    at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:555)
    at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:691)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by pnowojski** [comment]
> remove getBlocks call from StandardJoinFilterFunction.filter

Do we really want to optimize this path? Shouldn't we focus on using byte compiled version here?
