### ISSUE TITLE
Planning failure for mixed distinct and non-distinct aggregation

### ISSUE THREAD

**Issue by raghavsethi** [prestodb/presto#7443]
```
SELECT      
	t.c,
	count(DISTINCT a),
	count(t.c)
FROM 
	(VALUES (NULL, NULL)) t(a, b)
CROSS JOIN UNNEST(cast(b as array<varchar>)) with ORDINALITY AS t(c,d)
GROUP BY 1
```

Fails with:

```
java.lang.IllegalStateException: Duplicate key field_4
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.createGroupIdNode(OptimizeMixedDistinctAggregations.java:359)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitMarkDistinct(OptimizeMixedDistinctAggregations.java:216)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitMarkDistinct(OptimizeMixedDistinctAggregations.java:91)
	at com.facebook.presto.sql.planner.plan.MarkDistinctNode.accept(MarkDistinctNode.java:95)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitAggregation(OptimizeMixedDistinctAggregations.java:134)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations$Optimizer.visitAggregation(OptimizeMixedDistinctAggregations.java:91)
	at com.facebook.presto.sql.planner.plan.AggregationNode.accept(AggregationNode.java:252)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:33)
	at com.facebook.presto.sql.planner.optimizations.OptimizeMixedDistinctAggregations.optimize(OptimizeMixedDistinctAggregations.java:85)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:303)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:282)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:238)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by martint** [comment]
Not a release blocker. This optimizer can be turned off with a config option. 

Also, I think there an issue already filed for this and a PR pending review

**Comment by wenleix** [comment]
This duplicates https://github.com/prestodb/presto/issues/7214. The related PR to fix this: https://github.com/prestodb/presto/pull/7417
