### ISSUE TITLE
Error when plugging in UDF

### ISSUE THREAD

**Issue by felarof99** [prestodb/presto#7470]
Hi, I followed [this](https://www.qubole.com/blog/product/plugging-in-presto-udfs/?nabe=5695374637924352:1) tutorial and leveraged [this](https://github.com/qubole/presto-udfs) github project and wrote a simple 'mysum' UDF function. 

```
@ScalarFunction("mysum")
@Description("Returns summation of two numbers")
@SqlType(StandardTypes.BIGINT)
public static long sum(@SqlType(StandardTypes.BIGINT) long num1, @SqlType(StandardTypes.BIGINT) long num2) {
    return num1 + num2;
}

```
I followed the below steps to plugin the UDF but Presto fails to import the function. _Since, there is very little documentation about writing and plugging UDFs, any help would be much appreciated._ Thanks in advance.

1. ran `mvn compile` and `mvn package`
2. copied the `.jar` file into plugins folder under presto (unzipped) directory `/Users/nithin/presto-server-0.166/plugin/udfs/`
3. started coordinator using `/Users/nithin/presto-server-0.166/bin/launcher run`
4. ran the UDF `select mysum(10,100)` in Presto CLI, but throws error

Below is error log when I try to run my UDF ('mysum') in Presto CLI. **It is quite evident that Presto is not able to find the UDF, so plugging in wasn't successful. How to fix that? Am I missing any step?**

```
➜  Workspaces ./presto.jar --server localhost:8080 --catalog mysql --schema default --debug
presto:default> select mysum(99,100);
Query 20170228_183509_00002_vr5dt failed: line 1:8: Function mysum not registered
com.facebook.presto.sql.analyzer.SemanticException: line 1:8: Function mysum not registered
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:824)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:255)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:111)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:274)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1406)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeExpression(StatementAnalyzer.java:1802)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyzeSelect(StatementAnalyzer.java:1623)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:800)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuerySpecification(StatementAnalyzer.java:188)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:550)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:188)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:68)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:290)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:276)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:234)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
select mysum(99,100)

```

**Comment by nezihyigitbasi** [comment]
The github project you used to create your udf is kind of old (last commit to that repo is on Jul 26, 2016) and in the README Presto 0.142 is listed as a compatible version, which is pretty old. I recommend following the official [developer guide](https://prestodb.io/docs/current/develop.html) to write your own udf.

**Comment by electrum** [comment]
As @nezihyigitbasi points out, the developer guide should explain everything you need. There are two important parts:

1. The SPI Overview chapter explains how to package a plugin. Make sure the JAR has the `com.facebook.presto.spi.Plugin` file in the `META-INF/services` directory.
2. The Functions chapter explains the `getFunctions()` method.

When your server starts, you will see log lines like this:
```
2017-02-24T18:37:16.833-0800    INFO    main    com.facebook.presto.server.PluginManager        -- Loading plugin /data/plugin/ml --
2017-02-24T18:37:16.838-0800    INFO    main    com.facebook.presto.server.PluginManager        Installing com.facebook.presto.ml.MLPlugin
2017-02-24T18:37:16.846-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering type Model
2017-02-24T18:37:16.846-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering type Regressor
2017-02-24T18:37:16.847-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering parametric type Classifier
2017-02-24T18:37:16.851-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.LearnClassifierAggregation
2017-02-24T18:37:16.854-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.LearnVarcharClassifierAggregation
2017-02-24T18:37:16.856-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.LearnRegressorAggregation
2017-02-24T18:37:16.858-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.LearnLibSvmClassifierAggregation
2017-02-24T18:37:16.860-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.LearnLibSvmVarcharClassifierAggregation
2017-02-24T18:37:16.862-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.LearnLibSvmRegressorAggregation
2017-02-24T18:37:16.863-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.EvaluateClassifierPredictionsAggregation
2017-02-24T18:37:17.051-0800    INFO    main    com.facebook.presto.server.PluginManager        Registering functions from com.facebook.presto.ml.MLFunctions
2017-02-24T18:37:17.063-0800    INFO    main    com.facebook.presto.server.PluginManager        -- Finished loading plugin /data/plugin/ml --
```

If you don't see the line like `Installing com.facebook.presto.ml.MLPlugin`, then it's probably an issue with the `META-INF/services` file.

**Comment by electrum** [comment]
Please reopen the issue if you still need assistance.
