### ISSUE TITLE
Use a newer version of parquet-hadoop for writing parquet files

### ISSUE THREAD

**Issue by ducky427** [prestodb/presto#7489]
I created a hive table in PrestoDB as a parquet type. When I tried to read the parquet from HDFS directly, I got this warning:

```
:25:13.500 [pool-6-thread-1]    WARN  o.a.parquet.CorruptStatistics   Ignoring statistics because created_by could not be parsed (see PARQUET-251): parquet-mr
org.apache.parquet.VersionParser$VersionParseException: Could not parse created_by: parquet-mr using format: (.*?)\s+version\s*(?:([^(]*?)\s*(?:\(\s*build\s*([^)]*?)\s*\))?)?
	at org.apache.parquet.VersionParser.parse(VersionParser.java:112)
	at org.apache.parquet.CorruptStatistics.shouldIgnoreStatistics(CorruptStatistics.java:66)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetStatisticsInternal(ParquetMetadataConverter.java:346)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetStatistics(ParquetMetadataConverter.java:360)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.fromParquetMetadata(ParquetMetadataConverter.java:816)
	at org.apache.parquet.format.converter.ParquetMetadataConverter.readParquetMetadata(ParquetMetadataConverter.java:793)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:502)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:461)
	at org.apache.parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:437)
	at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:259)
	at org.apache.parquet.hadoop.ParquetFileReader$2.call(ParquetFileReader.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The underlying reason for this seems to that this file was written using `parquet-hadoop` version `1.6.0` while I was reading it with version `1.9.0`.

While this is only a warning, it will be good to upgrade the parquet version being used.

Thanks!

**Comment by ducky427** [comment]
This bug is related to #4732
