### ISSUE TITLE
Tests sometimes fail upon instantiation of TestingPrestoServer

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#7512]
Sometimes something like the following appears in the logs @ Travis

```
2017-03-06T15:22:53.535+0545	INFO	pool-1-thread-2	io.airlift.bootstrap.LifeCycleManager	Life cycle stopped.
Tests run: 85, Failures: 2, Errors: 0, Skipped: 40, Time elapsed: 34.009 sec <<< FAILURE! - in TestSuite
setupServer(com.facebook.presto.jdbc.TestJdbcResultSet)  Time elapsed: 1.749 sec  <<< FAILURE!
javax.validation.ValidationException: error during validation of com.facebook.presto.event.query.QueryMonitorConfig@15d89e07
	at com.facebook.presto.jdbc.TestJdbcResultSet.setupServer(TestJdbcResultSet.java:54)
Caused by: java.lang.NullPointerException
	at com.facebook.presto.jdbc.TestJdbcResultSet.setupServer(TestJdbcResultSet.java:54)
```

I tracked down the source of the `ValidationException` and got this:

```
javax.validation.ValidationException: error during validation of com.facebook.presto.event.query.QueryMonitorConfig@15d89e07
	at org.apache.bval.jsr.ClassValidator.unrecoverableValidationError(ClassValidator.java:594)
	at org.apache.bval.jsr.ClassValidator.validate(ClassValidator.java:144)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:381)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:312)
	at io.airlift.configuration.ConfigurationProvider.get(ConfigurationProvider.java:68)
	at io.airlift.configuration.ConfigurationFactory.validateRegisteredConfigurationProvider(ConfigurationFactory.java:231)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:204)
	at com.facebook.presto.server.testing.TestingPrestoServer.<init>(TestingPrestoServer.java:237)
	at com.facebook.presto.server.testing.TestingPrestoServer.<init>(TestingPrestoServer.java:154)
	at com.facebook.presto.server.testing.TestingPrestoServer.<init>(TestingPrestoServer.java:148)
	at com.facebook.presto.jdbc.TestJdbcResultSet.setupServer(TestJdbcResultSet.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at io.airlift.units.DataSize.compareTo(DataSize.java:147)
	at io.airlift.units.MinDataSizeValidator.isValid(MinDataSizeValidator.java:33)
	at io.airlift.units.MinDataSizeValidator.isValid(MinDataSizeValidator.java:19)
	at org.apache.bval.jsr.ConstraintValidation.validateGroupContext(ConstraintValidation.java:229)
	at org.apache.bval.jsr.ConstraintValidation.validate(ConstraintValidation.java:144)
	at org.apache.bval.util.ValidationHelper.validateProperty(ValidationHelper.java:234)
	at org.apache.bval.jsr.ClassValidator.validateBean(ClassValidator.java:462)
	at org.apache.bval.jsr.ClassValidator.validateBeanNet(ClassValidator.java:409)
	at org.apache.bval.jsr.ClassValidator.validateBeanWithGroups(ClassValidator.java:154)
	at org.apache.bval.jsr.ClassValidator.validate(ClassValidator.java:142)
	... 22 more
```

Looking at the code of `org.apache.bval.jsr.ConstraintValidation`, the class is _terribly not thread safe_ and lazy initializes `validator` field. Hence `MinDataSizeValidator.isValid(MinDataSizeValidator.java:33)` can fail with NPE because `isValid` is called "before" `initialize`.

**Comment by Balandat** [comment]
I believe this happened to my build here: https://travis-ci.org/prestodb/presto/builds/207566031

**Comment by findepi** [comment]
@Balandat, fear not! a fix is on its way!

**Comment by findepi** [comment]
we still need to update airlift in presto. @david, how do we do this?

>

**Comment by petroav** [comment]
@findepi we probably need to (1) release Airlift and then (2) update https://github.com/prestodb/presto/blob/master/pom.xml#L49.
