### ISSUE TITLE
Lost all the workers after cancel a heavy query.

### ISSUE THREAD

**Issue by chengat1314** [prestodb/presto#7523]
As the message in the subject,  our cluster lost all the workers when someone cancelled a heavy query after running about 20 minutes. 
During the down time of the cluster, the CPU usage is low but have a process is keeping doing GC. 

The log message got from one of the worker:
2017-03-06T03:08:50.834Z        ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 19.60s
2017-03-06T03:08:33.192Z        INFO    20170306_030816_00255_p88rz.16.8-0-57   com.amazonaws.latency   ServiceName=[Amazon S3], StatusCode=[206], ServiceEndpoint=[https://grab-helios.s3-ap-southeast-1.amazonaws.com], RequestType=[GetObjectRequest], AWSRequestID=[F33D1C7AB6F7F693], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=1, RequestCount=1, HttpClientPoolLeasedCount=50, ResponseProcessingTime=[1.771], ClientExecuteTime=[16.49], HttpClientSendRequestTime=[0.033], HttpRequestTime=[10.483], RequestSigningTime=[0.068], CredentialsRequestTime=[0.0], HttpClientReceiveResponseTime=[9.203],
2017-03-06T03:09:08.568Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:09:08.672Z        ERROR   Announcer-4     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 17.73s
2017-03-06T03:09:24.732Z        ERROR   exchange-client-17      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.25.135:8889/v1/task/20170306_030713_00253_p88rz.28.17/results/8 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 30000 ms
2017-03-06T03:09:24.757Z        ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.04s
2017-03-06T03:09:41.367Z        ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.60s
2017-03-06T03:09:57.816Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:09:57.816Z        ERROR   Announcer-4     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.45s
2017-03-06T03:10:13.933Z        ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.11s
2017-03-06T03:10:29.027Z        ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 15.09s
2017-03-06T03:10:29.241Z        ERROR   exchange-client-5       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.24.109:8889/v1/task/20170306_030652_00250_p88rz.10.0/results/6 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 30000 ms
2017-03-06T03:10:44.880Z        ERROR   Announcer-4     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 15.85s
2017-03-06T03:10:44.880Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:11:00.946Z        ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.06s
2017-03-06T03:11:15.780Z        ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 14.83s
2017-03-06T03:11:31.185Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:12:37.386Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:15:07.762Z        ERROR   Announcer-4     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 14.83s
2017-03-06T03:15:26.023Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:15:26.023Z        ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 18.26s
2017-03-06T03:15:26.208Z        ERROR   exchange-client-0       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.28.167:8889/v1/task/20170306_030659_00251_p88rz.25.14/results/13 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 30000 ms
2017-03-06T03:15:42.121Z        ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.09s
2017-03-06T03:15:56.844Z        ERROR   Announcer-4     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 14.72s
2017-03-06T03:16:14.838Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:16:14.838Z        ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 17.98s
2017-03-06T03:16:14.844Z        ERROR   exchange-client-9       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.18.62:8889/v1/task/20170306_030631_00249_p88rz.16.0/results/22 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 30000 ms
2017-03-06T03:16:14.852Z        ERROR   exchange-client-15      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.23.35:8889/v1/task/20170306_030711_00252_p88rz.27.1/results/16 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 30000 ms
2017-03-06T03:16:14.880Z        ERROR   exchange-client-9       com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.28.83:8889/v1/task/20170306_030741_00254_p88rz.32.1/results/1 failed java.lang.RuntimeException: java.util.concurrent.TimeoutException: Idle timeout 30000 ms
2017-03-06T03:16:31.043Z        ERROR   Announcer-1     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.18s
2017-03-06T03:16:46.218Z        ERROR   Announcer-4     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 15.17s
2017-03-06T03:17:02.922Z        ERROR   Announcer-2     io.airlift.discovery.client.Announcer   Expected service announcement after 8000.00ms, but announcement was delayed 16.70s
2017-03-06T03:17:02.922Z        INFO    Code-Cache-GC-Trigger   com.facebook.presto.server.CodeCacheGcTrigger   Triggering GC to avoid Code Cache eviction bugs
2017-03-06T03:17:02.929Z        ERROR   exchange-client-13      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.29.245:8889/v1/task/20170306_030631_00249_p88rz.2.3/results/22 failed io.airlift.http.client.RuntimeIOException: Server refused connection: http://172.31.29.245:8889/v1/task/20170306_030631_00249_p88rz.2.3/results/22
2017-03-06T03:17:02.929Z        ERROR   exchange-client-13      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.29.245:8889/v1/task/20170306_030631_00249_p88rz.25.15/results/22 failed io.airlift.http.client.RuntimeIOException: Server refused connection: http://172.31.29.245:8889/v1/task/20170306_030631_00249_p88rz.25.15/results/22
2017-03-06T03:17:02.930Z        ERROR   exchange-client-13      com.facebook.presto.operator.HttpPageBufferClient      ` Request to delete http://172.31.29.245:8889/v1/task/20170306_030631_00249_p88rz.7.3/results/22 failed `io.airlift.http.client.RuntimeIOException: Server refused connection: http://172.31.29.245:8889/v1/task/20170306_030631_00249_p88rz.7.3/results/22
2017-03-06T03:17:02.930Z        ERROR   exchange-client-13      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.28.167:8889/v1/task/20170306_030631_00249_p88rz.2.21/results/22 failed io.airlift.http.client.RuntimeIOException: Server refused connection: http://172.31.28.167:8889/v1/task/20170306_030631_00249_p88rz.2.21/results/22
2017-03-06T03:17:02.930Z        ERROR   exchange-client-13      com.facebook.presto.operator.HttpPageBufferClient       Request to delete http://172.31.28.167:8889/v1/task/20170306_030631_00249_p88rz.7.21/results/22 failed io.airlift.http.client.RuntimeIOException: Server refused connection: http://172.31.28.167:8889/v1/task/20170306_030631_00249_p88rz.7.21/results/22
.....

2017-03-06T03:17:34.223Z        ERROR   async-http-response-45462       org.glassfish.jersey.server.ServerRuntime$Responder     An I/O error has occurred while writing a response message entity to the container output stream.
org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
        at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:92)
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
        at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
        at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder$3.run(ServerRuntime.java:934)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:966)
        at org.glassfish.jersey.server.ServerRuntime$AsyncResponder.resume(ServerRuntime.java:922)
        at io.airlift.http.server.AsyncResponseHandler.lambda$toCompletionCallback$1(AsyncResponseHandler.java:101)
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.EofException
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:199)
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:420)
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:313)
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:140)
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:738)
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:518)
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:724)
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:775)
        at org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor.write(GzipHttpOutputInterceptor.java:108)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:219)
        at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:355)
        at io.airlift.http.server.TimingFilter$TimedServletOutputStream.flush(TimingFilter.java:281)
        at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.flush(ResponseWriter.java:330)
        at org.glassfish.jersey.message.internal.CommittingOutputStream.flush(CommittingOutputStream.java:292)

Our cluster setting: Presto version (0.157.1 on AWS EMR cluster)
the setting is 
http-server.threads.max=500
discovery-server.enabled=true
sink.max-buffer-size=1GB
query.max-memory=300GB
query.max-memory-per-node=16891560140B
query.max-history=300
query.min-expire-age=30m
http-server.http.port=8889
http-server.log.path=/var/log/presto/http-request.log
http-server.log.max-size=67108864B
http-server.log.max-history=5
log.max-size=268435456B
log.max-history=5
task.concurrency = 32
node-scheduler.network-topology = flat
exchange.http-client.request-timeout = 120s

@dain  @nezihyigitbasi @natesammons-nasdaq @ejono 
Please help identify this problem if it's a bug or we can avoid by update the setting. 
Thanks 
Cheng Feng

**Comment by dain** [comment]
Unfortunately, there isn’t enough information in this report to even begin to guess at what is going on.  I suggest you start by verifying you coordinator and workers are using G1 garbage collector:

-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError

And I would enable all of the GC logging:

-XX:+PrintGCApplicationConcurrentTime
-XX:+PrintGCApplicationStoppedTime
-XX:+PrintGCCause
-XX:+PrintGCDateStamps
-XX:+PrintGCTimeStamps
-XX:+PrintGCDetails
-XX:+PrintReferenceGC
-XX:+PrintClassHistogramAfterFullGC
-XX:+PrintClassHistogramBeforeFullGC
-XX:PrintFLSStatistics=2
-XX:+PrintAdaptiveSizePolicy
-XX:+PrintSafepointStatistics
-XX:PrintSafepointStatisticsCount=1

Once you have this information, you should be able to determine of the coordinator or worker is pausing.  At that point I would look at the difference between before and after ClassHistogram in the logs to see what junk is being generated (you’ll likely need a Java dev to dig into this).

Also, to state the obvious, I’d upgrade to the latest release as what ever you are seeing may have been already fixed. 

-dain

**Comment by chengat1314** [comment]
JVM setting: 

-verbose:class
-server
-Xmx54039278518
-Xmn512M
-XX:+UseConcMarkSweepGC
-XX:+ExplicitGCInvokesConcurrent
-XX:+CMSClassUnloadingEnabled
-XX:+AggressiveOpts
-XX:+HeapDumpOnOutOfMemoryError
-XX:OnOutOfMemoryError=kill -9 %p
-XX:ReservedCodeCacheSize=150M
-Xbootclasspath/p:

**Comment by chengat1314** [comment]
Thanks, I will try to update the JVM setting  and test.

**Comment by dain** [comment]
The problem is you are using CMS.  You want to use G1 with Presto.  My guess is the problems will go away with that change alone.

-dain

**Comment by chengat1314** [comment]
OK, thx I will try out.

**Comment by chengat1314** [comment]
OK, thx I will try out.

**Comment by chengat1314** [comment]
After updated the GC type to GC1, the cluster became much more stable now.
thank you very much!

**Comment by sudarsanm94** [comment]
configuration:

#
# WARNING
# ^^^^^^^
# This configuration file is for development only and should NOT be used be
# used in production. For example configuration, see the Presto documentation.
#

-server
-Xmx2G
-XX:+UseG1GC
-XX:+UseGCOverheadLimit
-XX:+ExplicitGCInvokesConcurrent
-XX:+CMSClassUnloadingEnabled
-XX:+AggressiveOpts
-XX:+HeapDumpOnOutOfMemoryError
-XX:+ExitOnOutOfMemoryError
-XX:ReservedCodeCacheSize=150M
-DHADOOP_USER_NAME=hive
-Duser.timezone=UTC
-Xdebug 
-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005

**Comment by sudarsanm94** [comment]
The issue I faced was due to a bug in the test.
