### ISSUE TITLE
Create a user-friendly message for Raptor error when inserting into a table with a lot of columns

### ISSUE THREAD

**Issue by AlekseiS** [prestodb/presto#7612]
Raptor insert query can fail when inserting metadata for created shards because of too many (columns x shards) are inserted in a multi statement transaction.
We'd like to do the following:
1. Have a more user-friendly message for this type of errors that would hint about a potential problem.
2. Log the number of columns and shards updated for a query, so that it's easier to debug later. Ideally, this information should be included in the exception message in point 1.

Full stack trace is the following:
```
PrestoExternalError: com.facebook.presto.spi.PrestoException: Failed to perform metadata operation
	at com.facebook.presto.raptor.util.DatabaseUtil.metadataError(DatabaseUtil.java:68)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.runCommit(DatabaseShardManager.java:333)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.commitShards(DatabaseShardManager.java:293)
	at com.facebook.presto.raptor.RaptorMetadata.finishInsert(RaptorMetadata.java:705)
	at com.facebook.presto.metadata.MetadataManager.finishInsert(MetadataManager.java:544)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$1.finishTable(LocalExecutionPlanner.java:1908)
	at com.facebook.presto.operator.TableFinishOperator.getOutput(TableFinishOperator.java:156)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:378)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:301)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:618)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:529)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:665)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.skife.jdbi.v2.exceptions.CallbackFailedException: org.skife.jdbi.v2.exceptions.TransactionFailedException: Transaction failed do to exception being thrown from within the callback. See cause for the original exception.
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:284)
	at org.skife.jdbi.v2.DBI.useHandle(DBI.java:305)
	at org.skife.jdbi.v2.DBI.useTransaction(DBI.java:341)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.runCommit(DatabaseShardManager.java:321)
	... 13 more
Caused by: org.skife.jdbi.v2.exceptions.TransactionFailedException: Transaction failed do to exception being thrown from within the callback. See cause for the original exception.
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:195)
	at org.skife.jdbi.v2.BasicHandle.useTransaction(BasicHandle.java:333)
	at org.skife.jdbi.v2.DBI$6.useHandle(DBI.java:345)
	at org.skife.jdbi.v2.DBI$4.execute(DBI.java:308)
	at org.skife.jdbi.v2.tweak.VoidHandleCallback.withHandle(VoidHandleCallback.java:35)
	at org.skife.jdbi.v2.tweak.VoidHandleCallback.withHandle(VoidHandleCallback.java:23)
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:281)
	... 16 more
Caused by: java.sql.BatchUpdateException: Multi-statement transaction required more than 'max_binlog_cache_size' bytes of storage; increase this mysqld variable and try again
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1607)
	at com.mysql.jdbc.PreparedStatement.executeBatch(PreparedStatement.java:1272)
	at com.facebook.presto.raptor.metadata.IndexInserter.execute(IndexInserter.java:155)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.insertShardsAndIndex(DatabaseShardManager.java:454)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.lambda$commitShards$3(DatabaseShardManager.java:296)
	at com.facebook.presto.raptor.metadata.DatabaseShardManager.lambda$runCommit$5(DatabaseShardManager.java:324)
	at org.skife.jdbi.v2.BasicHandle$1.execute(BasicHandle.java:336)
	at org.skife.jdbi.v2.VoidTransactionCallback.inTransaction(VoidTransactionCallback.java:33)
	at org.skife.jdbi.v2.VoidTransactionCallback.inTransaction(VoidTransactionCallback.java:21)
	at org.skife.jdbi.v2.tweak.transactions.LocalTransactionHandler.inTransaction(LocalTransactionHandler.java:184)
	... 22 more
Caused by: java.sql.SQLException: Multi-statement transaction required more than 'max_binlog_cache_size' bytes of storage; increase this mysqld variable and try again
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1568)
	... 31 more
```

**Comment by AlekseiS** [comment]
cc @electrum @ggreg
