### ISSUE TITLE
presto failed when meeting database without OwnerType

### ISSUE THREAD

**Issue by ffpeng90** [prestodb/presto#7665]
presto will fail to create tables when meeting hive databases without ownerType property.   

All Functions related is in class [MetastoreUtil.java]. 
If my DataBase did not set OwnerType,  then  **database.getOwnerType()** will return null 
and function **fromMetastoreApiPrincipalType**  will throw an null-pointer Exception. 

so  **PrincipalType ownerType = PrincipalType.ROLE;**  will be nonsense.
Is anybody has this problem? 

Code1:
`
public static Database fromMetastoreApiDatabase(org.apache.hadoop.hive.metastore.api.Database database)
    {
        String ownerName = "PUBLIC";
        PrincipalType ownerType = PrincipalType.ROLE;
        if (database.getOwnerName() != null) {
            ownerName = database.getOwnerName();
            ownerType = fromMetastoreApiPrincipalType(database.getOwnerType());
        }
        Map<String, String> parameters = database.getParameters();
        if (parameters == null) {
            parameters = ImmutableMap.of();
        }
   }
`

Code2: 
`
private static PrincipalType fromMetastoreApiPrincipalType(org.apache.hadoop.hive.metastore.api.PrincipalType principalType)
    {
        switch (principalType) {
            case USER:
                return PrincipalType.USER;
            case ROLE:
                return PrincipalType.ROLE;
            default:
                throw new IllegalArgumentException("Unsupported principal type: " + principalType);
        }
    }
`

**Comment by ffpeng90** [comment]
My presto is 0.166, and my exception below:

java.lang.NullPointerException
	at com.facebook.presto.hive.metastore.MetastoreUtil.fromMetastoreApiPrincipalType(MetastoreUtil.java:348)
	at com.facebook.presto.hive.metastore.MetastoreUtil.fromMetastoreApiDatabase(MetastoreUtil.java:280)
	at java.util.Optional.map(Optional.java:215)
	at com.facebook.presto.hive.metastore.BridgingHiveMetastore.getDatabase(BridgingHiveMetastore.java:61)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadDatabase(CachingHiveMetastore.java:266)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.access$100(CachingHiveMetastore.java:58)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore$2.load(CachingHiveMetastore.java:123)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore$2.load(CachingHiveMetastore.java:118)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:189)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:240)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getDatabase(CachingHiveMetastore.java:260)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadDatabase(CachingHiveMetastore.java:266)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.access$100(CachingHiveMetastore.java:58)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore$2.load(CachingHiveMetastore.java:123)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore$2.load(CachingHiveMetastore.java:118)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:189)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.get(CachingHiveMetastore.java:240)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.getDatabase(CachingHiveMetastore.java:260)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.getDatabase(SemiTransactionalHiveMetastore.java:116)
	at com.facebook.presto.hive.HiveWriteUtils.getDatabase(HiveWriteUtils.java:424)
	at com.facebook.presto.hive.HiveWriteUtils.getTableDefaultLocation(HiveWriteUtils.java:404)
	at com.facebook.presto.hive.HiveLocationService.forNewTable(HiveLocationService.java:48)
	at com.facebook.presto.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:597)
	at com.facebook.presto.hive.HiveMetadata.beginCreateTable(HiveMetadata.java:146)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.beginCreateTable(ClassLoaderSafeConnectorMetadata.java:238)
	at com.facebook.presto.metadata.MetadataManager.beginCreateTable(MetadataManager.java:563)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.createWriterTarget(BeginTableWrite.java:152)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:121)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite$Rewriter.visitTableFinish(BeginTableWrite.java:76)
	at com.facebook.presto.sql.planner.plan.TableFinishNode.accept(TableFinishNode.java:81)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:85)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:33)
	at com.facebook.presto.sql.planner.optimizations.BeginTableWrite.optimize(BeginTableWrite.java:73)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:111)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:297)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:276)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:234)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by amrutagokhale** [comment]
If owner and ownerType both are missing, Presto makes `PUBLIC` role as the owner, and hence `PrincipalType.ROLE` as the ownerType. I don't see anything wrong in this.

I believe in your case, you have `owner` of the database set but not `ownerType`(NullPointerException can only occur in such a case). To me this looks like inconsistency in the underlying database. Though, we can change Presto code to give a more meaningful message about the actual error, rather than throwing NullPointerException.

**Comment by ffpeng90** [comment]
yes, we can offer a more meaningful warning message to remind users.  so they can make up the ownerType properties.
