### ISSUE TITLE
explain is broken

### ISSUE THREAD

**Issue by jefimm** [prestodb/presto#7672]
Presto 0.167

explain with test1 as (....) select *
from test1;

is broken and outputs "index (1) must be less than size (1)"

**Comment by martint** [comment]
Does it happen on 0.170? Can you provide a complete example? I tried a few different things in (...), but I can't reproduce it.

**Comment by jefimm** [comment]
I was able to reduce this to the following :

explain WITH tbl AS (
SELECT date_trunc('hour', date_created) date_created
FROM    source
WHERE   date_created > date_add('hour', -24, now()) AND date_created < date_add('day', 1, current_date)
)
SELECT * FROM tbl;

**Comment by martint** [comment]
And what does "source" look like? If I try to fake it with `source (date_created) as (values current_date)`, it doesn't reproduce:

```sql
explain
WITH
source (date_created) as (values current_date),
tbl AS (
    SELECT date_trunc('hour', date_created) date_created
    FROM source
    WHERE date_created > date_add('hour', -24, now()) AND date_created < date_add('day', 1, current_date)
)
SELECT * FROM tbl;
```

**Comment by jefimm** [comment]
desc source;
           Column            |    Type     | Extra | Comment
-----------------------------+-------------+-------+---------
 date_created                | timestamp   |       |

**Comment by martint** [comment]
Can you try my query above and see if it reproduces for you?

**Comment by jefimm** [comment]
your query works, maybe you can try it with "real" table in, for example, raptor ?

**Comment by martint** [comment]
Also, can you paste the entire stacktrace. You should be able to get it by running the CLI with --debug.

**Comment by jefimm** [comment]
`
Query 20170327_182411_00262_pi3ys failed: index (1) must be less than size (1)
java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
	at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:41)
	at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:67)
	at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:43)
	at com.facebook.presto.sql.planner.PlanPrinter.castToVarchar(PlanPrinter.java:1326)
	at com.facebook.presto.sql.planner.PlanPrinter.access$700(PlanPrinter.java:140)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.lambda$formatDomain$15(PlanPrinter.java:1262)
	at com.facebook.presto.spi.predicate.SortedRangeSet$2.consume(SortedRangeSet.java:220)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.formatDomain(PlanPrinter.java:1238)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.printConstraint(PlanPrinter.java:1224)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.printTableScanInfo(PlanPrinter.java:986)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitScanFilterAndProjectInfo(PlanPrinter.java:953)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitProject(PlanPrinter.java:885)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitProject(PlanPrinter.java:570)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.processChildren(PlanPrinter.java:1197)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitExchange(PlanPrinter.java:1139)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitExchange(PlanPrinter.java:570)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:195)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.processChildren(PlanPrinter.java:1197)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitOutput(PlanPrinter.java:1027)
	at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitOutput(PlanPrinter.java:570)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.PlanPrinter.<init>(PlanPrinter.java:161)
	at com.facebook.presto.sql.planner.PlanPrinter.<init>(PlanPrinter.java:148)
	at com.facebook.presto.sql.planner.PlanPrinter.textLogicalPlan(PlanPrinter.java:185)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:95)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:126)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:104)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:60)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:73)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:57)
	at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:51)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:65)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:296)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:282)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:238)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by martint** [comment]
Hmm. This is probably related to https://github.com/prestodb/presto/issues/3201.

**Comment by martint** [comment]
Actually, it might be a regression introduced by 7c92b1e6ed8438d597fae68f8d8c2a94c5c81c4e

**Comment by jefimm** [comment]
date_created is partition column in our case

**Comment by martint** [comment]
I think what's happening is the following:
- CAST from TIMESTAMP to VARCHAR (which is used by PlanPrinter) takes ConnectorSession as the first argument
- The metadata for that CAST has a "is argument nullable flag" for every regular argument (but not for ConnectorSession, of course)
- The loop in FunctionInvoker is not properly offsetting the lookup into the "is argument nullable" list when skipping the ConnectorSession argument.

It should be a simple fix. @geraint0923, can you take a look?

**Comment by rentaow** [comment]
We're getting similar error exception for EXPLAIN on a table with timestamp column/partition:

presto> EXPLAIN SELECT * FROM default.partition_date;
Query 20170622_204802_00006_ddfst failed: index (1) must be less than size (1)
java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
	at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
