### ISSUE TITLE
InMemory Connector throws error when max-data-per-node is set.

### ISSUE THREAD

**Issue by woland84** [prestodb/presto#7678]
When setting the `memory.max-data-per-node` property in `etc/catalog/memory.properties` in prestodb 0.169 the following exception is thrown:
```
	ERROR	main	com.facebook.presto.server.PrestoServer	Unable to create injector, see the following errors:

1) Configuration property 'memory.max-data-per-node=128MB' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

1 error
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Configuration property 'memory.max-data-per-node=128MB' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.plugin.memory.MemoryConnectorFactory.create(MemoryConnectorFactory.java:59)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:304)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:193)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:185)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:171)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:99)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:77)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:120)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

Am I missing some obvious configuration step or is this a bug?

**Comment by nezihyigitbasi** [comment]
Fixed thru #7694
