### ISSUE TITLE
No factory for connector localfile

### ISSUE THREAD

**Issue by guojun1992** [prestodb/presto#7685]
I test it use localfile but get this error

2017-03-28T10:35:16.627+0000	 INFO	main	com.facebook.presto.server.PluginManager	-- Finished loading plugin /var/presto/data/plugin/tpch --
2017-03-28T10:35:16.627+0000	 INFO	main	com.facebook.presto.metadata.CatalogManager	-- Loading catalog etc/catalog/localfile.properties --
2017-03-28T10:35:16.635+0000	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector localfile
java.lang.IllegalArgumentException: No factory for connector localfile
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-18.0.jar:na]
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:104) ~[presto-main-0.100.jar:0.100]
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:88) ~[presto-main-0.100.jar:0.100]
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:70) ~[presto-main-0.100.jar:0.100]
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:107) [presto-main-0.100.jar:0.100]
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:59) [presto-main-0.100.jar:0.100]
2017-03-28T10:35:16.637+0000	 INFO	Thread-152	io.airlift.bootstrap.LifeCycleManager	Life cycle stopping...

**Comment by losipiuk** [comment]
It look like misconfiguration. Please ask question on https://groups.google.com/forum/#!forum/presto-users sharing your configuration and command you use to run Presto.
