### ISSUE TITLE
Not able to start prestodb as embedded Server in Java Application.

### ISSUE THREAD

**Issue by PallaviSingh1992** [prestodb/presto#7710]
We were trying to start presto as an embedded server in our java application but we are getting the following errors, given below is the stacktrace  ---> 

```
2017-03-31T18:17:22.662+0530	INFO	main	io.airlift.log.Logging	Logging to stderr
2017-03-31T18:17:23.173+0530	INFO	main	Bootstrap	Initializing logging
2017-03-31T18:17:23.626+0530	INFO	main	Bootstrap	PROPERTY          DEFAULT  RUNTIME  DESCRIPTION
2017-03-31T18:17:23.626+0530	INFO	main	Bootstrap	allow-drop-table  false    false    Allow connector to drop tables
2017-03-31T18:17:23.626+0530	INFO	main	Bootstrap	
2017-03-31T18:17:23.626+0530	WARN	main	Bootstrap	UNUSED PROPERTIES
2017-03-31T18:17:23.627+0530	WARN	main	Bootstrap	coordinator=true
2017-03-31T18:17:23.627+0530	WARN	main	Bootstrap	datasources=carbondata
2017-03-31T18:17:23.627+0530	WARN	main	Bootstrap	discovery-server.enabled=true
2017-03-31T18:17:23.627+0530	WARN	main	Bootstrap	discovery.uri=http://localhost:8086
2017-03-31T18:17:23.627+0530	WARN	main	Bootstrap	http-server.http.port=8086
2017-03-31T18:17:23.628+0530	WARN	main	Bootstrap	
2017-03-31T18:17:23.943+0530	INFO	main	stderr	com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and com.facebook.presto.plugin.jdbc.JdbcClient is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
    for parameter 0 at com.facebook.presto.plugin.jdbc.JdbcMetadataFactory.<init>(JdbcMetadataFactory.java:27)
  at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:37)

2) Explicit bindings are required and com.facebook.presto.plugin.jdbc.JdbcClient is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
    for parameter 0 at com.facebook.presto.plugin.jdbc.JdbcRecordSetProvider.<init>(JdbcRecordSetProvider.java:38)
  at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:39)

3) Explicit bindings are required and com.facebook.presto.plugin.jdbc.JdbcClient is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
    for parameter 0 at com.facebook.presto.plugin.jdbc.JdbcRecordSinkProvider.<init>(JdbcRecordSinkProvider.java:35)
  at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:40)

4) Explicit bindings are required and com.facebook.presto.plugin.jdbc.JdbcClient is not explicitly bound.
  while locating com.facebook.presto.plugin.jdbc.JdbcClient
    for parameter 0 at com.facebook.presto.plugin.jdbc.JdbcSplitManager.<init>(JdbcSplitManager.java:34)
  at com.facebook.presto.plugin.jdbc.JdbcModule.configure(JdbcModule.java:38)

5) Configuration property 'coordinator=true' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

6) Configuration property 'datasources=carbondata' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

7) Configuration property 'discovery-server.enabled=true' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

8) Configuration property 'discovery.uri=http://localhost:8086' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

9) Configuration property 'http-server.http.port=8086' was not used
  at io.airlift.bootstrap.Bootstrap.lambda$initialize$2(Bootstrap.java:235)

9 errors
2017-03-31T18:17:23.943+0530	INFO	main	stderr		at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
2017-03-31T18:17:23.944+0530	INFO	main	stderr		at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
2017-03-31T18:17:23.944+0530	INFO	main	stderr		at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
2017-03-31T18:17:23.944+0530	INFO	main	stderr		at com.google.inject.Guice.createInjector(Guice.java:96)
2017-03-31T18:17:23.944+0530	INFO	main	stderr		at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
2017-03-31T18:17:23.944+0530	INFO	main	stderr		at org.apache.carbondata.examples.PrestoDBExample.main(PrestoDBExample.java:47) 
```

Here is our java code that we are using for connecting presto as embedded server 

```
package org.apache.carbondata.examples;

import com.facebook.presto.connector.ConnectorManager;
import com.facebook.presto.jdbc.PrestoDriver;
import com.facebook.presto.metadata.CatalogManager;
import com.facebook.presto.plugin.jdbc.*;
import com.facebook.presto.server.PluginManager;
import io.airlift.bootstrap.Bootstrap;
import com.google.inject.Injector;

import java.lang.reflect.Field;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;

public class PrestoDBExample {
    public static void main(String args[]) {

        BaseJdbcConfig config=new BaseJdbcConfig();
        PrestoDriver driver=new PrestoDriver();
        BaseJdbcClient client =new BaseJdbcClient(new JdbcConnectorId("connectorId"),config,"",driver);
        JdbcModule modules =
                new JdbcModule("connectorId");
        
        String propHttpServerPort = "8086";
        String propDiscoveryUri = "http://localhost:8086";
        String carbondataStoreUrl = "http://localhost:54310/user/hive/warehouse/carbon.store";
        String carbondataProp = "carbondata-store";

        Bootstrap app = new Bootstrap(modules);
        app.setRequiredConfigurationProperty("coordinator", "true");
        app.setRequiredConfigurationProperty("datasources", "carbondata");
        app.setRequiredConfigurationProperty("discovery-server.enabled", "true");
        app.setRequiredConfigurationProperty("http-server.http.port", propHttpServerPort);
        app.setRequiredConfigurationProperty("discovery.uri", propDiscoveryUri);
        //app.setRequiredConfigurationProperty("carbondata-store", "hdfs://localhost:54311/opt/carbonStore");

        Map<String, String> properties = new HashMap();
        properties.put(carbondataProp, carbondataStoreUrl);
        try {
            //app.initialize();
            Injector injector = app.strictConfig().initialize();
            injector.getInstance(PluginManager.class).installPlugin(new JdbcPlugin("carbondata",modules));
            CatalogManager catalogManager = injector.getInstance(CatalogManager.class);
            Field connectorManagerField = CatalogManager.class.getDeclaredField("connectorManager");
            connectorManagerField.setAccessible(true);
            ConnectorManager connectorManager =
                    (ConnectorManager) connectorManagerField.get(catalogManager);
            connectorManager.createConnection("carbondata", "carbondata", properties);
            //  ImmutableMap.builder().put(carbondataProp, carbondataStoreUrl).build());
        } catch (Exception e) {
            e.printStackTrace();
        }


    }
}
```
NOTE: We are trying to use a custom data source for our presto server and we have been successfully able to implement and use our custom connector using presto-jdbc.

**Comment by dain** [comment]
I don’t know what the exact issue is, but take a look at how we do this in the Presto unit tests:

https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/testing/TestingPrestoServer.java
https://github.com/prestodb/presto/blob/master/presto-tests/src/main/java/com/facebook/presto/tests/DistributedQueryRunner.java

-dain

**Comment by PallaviSingh1992** [comment]
Hi @dain ,
We are trying to execute the HiveQueryRunner but it is giving us compilation errors in AstBuilder.java and SqlParser.java.

**Comment by dain** [comment]
I have no idea what your exact issue is, but you will get compile errors from these classes if you did not run the full maven build.

**Comment by PallaviSingh1992** [comment]
Hi @dain ,
Thanks for the help. Could Resolve the issue.
Can you please help in implementing decimal for connector for my data source

**Comment by dain** [comment]
@PallaviSingh1992 please open a new issue with the exact error you are seeing, or if you have a general question please send an email to the mailing list.

If you are just looking for an example, here is how we decode decimal text in the Hive rcfile reader: https://github.com/prestodb/presto/blob/master/presto-rcfile/src/main/java/com/facebook/presto/rcfile/text/DecimalEncoding.java#L72
