### ISSUE TITLE
Memory connector doesn't allow inserting into empty, newly created tables

### ISSUE THREAD

**Issue by sopel39** [prestodb/presto#7733]
```
presto:default> create table memory.default.TCHAR10( RNUM integer );
CREATE TABLE
presto:default> insert into memory.default.tchar10 values ( 0 );

Query 20170403_093522_00014_xs4w3, FAILED, 1 node
Splits: 35 total, 17 done (48,57%)
0:03 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20170403_093522_00014_xs4w3 failed: Failed to find table on a worker.
```
stacktrace:
```
com.facebook.presto.spi.PrestoException: Failed to find table on a worker.
	at com.facebook.presto.plugin.memory.MemoryPagesStore.add(MemoryPagesStore.java:63)
	at com.facebook.presto.plugin.memory.MemoryPageSinkProvider$MemoryPageSink.appendPage(MemoryPageSinkProvider.java:87)
	at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:203)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:309)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
```

FYI: @pnowojski

**Comment by findepi** [comment]
Fixed
