### ISSUE TITLE
"CREATE TABLE ... AS ..." doesn't parse proper query expressions

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7745]
```sql
CREATE TABLE u AS (
   WITH t(x) AS (VALUES 1) 
   SELECT x FROM t);
```

fails with a parsing error:

```
Query 20170405_035149_08220_kmjsc failed: line 1:31: mismatched input 'WITH' expecting {'(', 'SELECT', 'VALUES', 'TABLE'}
com.facebook.presto.sql.parser.ParsingException: line 1:31: mismatched input 'WITH' expecting {'(', 'SELECT', 'VALUES', 'TABLE'}
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:45)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:301)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3450)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3196)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3047)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3439)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3196)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3047)
	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2492)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1461)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:233)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:92)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:65)
	at com.facebook.presto.execution.SqlQueryManager.createQuery(SqlQueryManager.java:338)
	at com.facebook.presto.server.StatementResource$Query.<init>(StatementResource.java:329)
	at com.facebook.presto.server.StatementResource.createQuery(StatementResource.java:173)
```

Per the spec, the `<table contents source>` should be a parenthesized query expression, which can start with a `WITH` clause. Presto currently parses it as a `<query>`, which can resolve to a `<query primary>` that doesn't allow such clause.

```
<table definition> ::=
  CREATE [ <table scope> ] TABLE <table name> <table contents source>
      [ WITH <system versioning clause> ]
      [ ON COMMIT <table commit action> ROWS ]

<table contents source> ::=
    <table element list>
  | <typed table clause>
  | <as subquery clause>

<as subquery clause> ::=
  [ <left paren> <column name list> <right paren> ] AS <table subquery>
      <with or without data>

<table subquery> ::=  <subquery>
<subquery> ::=  <left paren> <query expression> <right paren>

<query expression> ::=
  [ <with clause> ] <query expression body>
      [ <order by clause> ] [ <result offset clause> ] [ <fetch first clause> ]
```

**Comment by ebyhr** [comment]
Following query succeeded. The difference is eliminating only brakets.
```sql
CREATE TABLE u AS 
   WITH t(x) AS (VALUES 1) 
   SELECT x FROM t;
```

Therefore, I changed SqlBase.g4 to like this. Is this approach correct? I confirmed the issue's query succeed. 
```
    | CREATE TABLE (IF NOT EXISTS)? qualifiedName
        (WITH tableProperties)? AS (query | '('query')')
        (WITH (NO)? DATA)?                                             #createTableAsSelect
```

**Comment by martint** [comment]
Yes, that's the way to do it. We're going to have to do some testing to make sure there are no ambiguities or backtracking issues (due to a parenthesis potentially matching the second alternative or the parenthesis in the deep inside the first term (query).
