### ISSUE TITLE
"System distribution does not support source splits"

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7877]
```sql
SELECT suppkey, 1
FROM supplier
UNION ALL
SELECT suppkey, count(*)
FROM supplier
GROUP BY 1
```
Fails with:

```
Query 20170420_233053_00006_69zes failed: System distribution does not support source splits
java.lang.UnsupportedOperationException: System distribution does not support source splits
	at com.facebook.presto.sql.planner.SystemPartitioningHandle.lambda$getNodePartitionMap$0(SystemPartitioningHandle.java:157)
	at com.facebook.presto.sql.planner.NodePartitionMap.getNode(NodePartitionMap.java:59)
	at com.facebook.presto.execution.scheduler.NodeScheduler.selectDistributionNodes(NodeScheduler.java:276)
	at com.facebook.presto.execution.scheduler.SimpleNodeSelector.computeAssignments(SimpleNodeSelector.java:174)
	at com.facebook.presto.execution.scheduler.FixedSourcePartitionedScheduler$FixedSplitPlacementPolicy.computeAssignments(FixedSourcePartitionedScheduler.java:147)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:111)
	at com.facebook.presto.execution.scheduler.FixedSourcePartitionedScheduler.schedule(FixedSourcePartitionedScheduler.java:91)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:354)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is a regression introduced by 7c373d45525e84ce77ddfd05434b7323ba070565

cc @pnowojski

**Comment by martint** [comment]
The plan seems broken:

```
 Fragment 0 [SINGLE]
     Output layout: [suppkey_18, expr_19]
     Output partitioning: SINGLE []
     - Output[suppkey, _col1] => [suppkey_18:bigint, expr_19:bigint]
             suppkey := suppkey_18
             _col1 := expr_19
         - RemoteSource[1] => [suppkey_18:bigint, expr_19:bigint]

 Fragment 1 [HASH]
     Output layout: [suppkey_18, expr_19]
     Output partitioning: SINGLE []
     - LocalExchange[ROUND_ROBIN] () => suppkey_18:bigint, expr_19:bigint
         - ScanProject[table = tpch:tpch:supplier:sf0.01, originalConstraint = true] => [expr_4:bigint, suppkey:bigint]
                 expr_4 := BIGINT '1'
                 suppkey := tpch:suppkey
         - Aggregate(FINAL)[suppkey_5] => [suppkey_5:bigint, count:bigint]
                 count := "count"("count_24")
             - LocalExchange[HASH][$hashvalue] ("suppkey_5") => suppkey_5:bigint, count_24:bigint, $hashvalue:bigint
                 - RemoteSource[2] => [suppkey_5:bigint, count_24:bigint, $hashvalue_25:bigint]

 Fragment 2 [SOURCE]
     Output layout: [suppkey_5, count_24, $hashvalue_26]
     Output partitioning: HASH [suppkey_5][$hashvalue_26]
     - Project[] => [suppkey_5:bigint, count_24:bigint, $hashvalue_26:bigint]
             $hashvalue_26 := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("suppkey_5"), 0))
         - Aggregate(PARTIAL)[suppkey_5] => [suppkey_5:bigint, count_24:bigint]
                 count_24 := "count"(*)
             - TableScan[tpch:tpch:supplier:sf0.01, originalConstraint = true] => [suppkey_5:bigint]
                     suppkey_5 := tpch:suppkey
```

There's a `ScanProject` in fragment 1, which is hash-distributed.
