### ISSUE TITLE
Improve the error message for `transform_keys` and `transform_values`

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#7899]
```
presto> select transform_values(map(array[1], array[2]), x->x);
Query 20170425_234003_68183_cgczr failed: null
com.google.common.base.VerifyException
        at com.google.common.base.Verify.verify(Verify.java:99)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:1094)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:258)
        at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:60)
        at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:277)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:240)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.access$1800(ExpressionAnalyzer.java:155)
        at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.lambda$visitFunctionCall$1(ExpressionAnalyzer.java:804)
        at com.facebook.presto.sql.analyzer.TypeSignatureProvider.getTypeSignature(TypeSignatureProvider.java:60)
        at com.facebook.presto.metadata.SignatureBinder$FunctionSolver.update(SignatureBinder.java:725)
.................
```

It should say something like "expected a lambda function takes two parameters, etc"

**Comment by ebyhr** [comment]
How about this error message?
```
com.facebook.presto.sql.analyzer.SemanticException: expected a lambda function takes 2 parameters (actual: 1)

	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:1097)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:258)
	at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:60)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:277)
...
```

ExpressionAnalyzer$Visitor.visitLambdaExpression
Modified 
```java
            if (types.size() != lambdaArguments.size()) {
                throw new SemanticException(INVALID_PARAMETER_USAGE, node,
                        format("expected a lambda function takes %s parameters (actual: %s)", types.size(), lambdaArguments.size()));
            }
```

Current
```java
verify(types.size() == lambdaArguments.size());
```
```java
  public static void verify(boolean expression) {
    if (!expression) {
      throw new VerifyException();
    }
  }
```

**Comment by wenleix** [comment]
I see. Thank you @ebyhr for the investigation. This looks reasonable for me. @haozhun what do you think? Shall it be considered as a `VerifyException` or `SemanticException`?

**Comment by ebyhr** [comment]
@haozhun Gentle Reminder :)

**Comment by haozhun** [comment]
It should be a `SemanticException`. Thank you for the investigation @ebyhr @wenleix
