### ISSUE TITLE
Planning failure for UNION and GROUP BY

### ISSUE THREAD

**Issue by martint** [prestodb/presto#7928]
The following query:

```
WITH
t1 AS (
  SELECT 1
  FROM tpch.tiny.nation
  GROUP BY 1
),
t2 AS (
  SELECT 1 FROM tpch.tiny.nation
  UNION ALL
  SELECT 1 FROM tpch.tiny.nation
)

SELECT 1
FROM t1
UNION ALL
SELECT 1
FROM t2
```

Fails during planning with:

```
java.lang.IllegalStateException: Cannot set distribution to ROUND_ROBIN. Already set to Optional[HASH]
	at com.google.common.base.Preconditions.checkState(Preconditions.java:721)
	at com.facebook.presto.sql.planner.PlanFragmenter$FragmentProperties.setDistribution(PlanFragmenter.java:259)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:192)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:84)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:195)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:183)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:84)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:195)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.buildSubPlan(PlanFragmenter.java:215)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:198)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitExchange(PlanFragmenter.java:84)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:195)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitOutput(PlanFragmenter.java:135)
	at com.facebook.presto.sql.planner.PlanFragmenter$Fragmenter.visitOutput(PlanFragmenter.java:84)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:32)
	at com.facebook.presto.sql.planner.PlanFragmenter.createSubPlans(PlanFragmenter.java:75)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:314)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:282)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is probably related to the recent changes in https://github.com/prestodb/presto/pull/7239

cc @pnowojski

**Comment by martint** [comment]
It appears to be fixed in master via 69f8b1b21bdf01b9de8373a7adbb0bd50d483bc9. It's not clear why that fixes it, so we need to investigate further.

**Comment by findepi** [comment]
@martint the issue you provided indeed works now in master, but just wrap the query in `select count(*) from ..` to reproduce original failure:

```
WITH
t1 AS (
  SELECT 1
  FROM tpch.tiny.nation
  GROUP BY 1
),
t2 AS (
  SELECT 1 FROM tpch.tiny.nation
  UNION ALL
  SELECT 1 FROM tpch.tiny.nation
)

SELECT count(*) FROM (
    SELECT 1
    FROM t1
    UNION ALL
    SELECT 1
    FROM t2
)
```

```
Query failed: Cannot set distribution to ROUND_ROBIN. Already set to Optional[HASH]
```

**Comment by martint** [comment]
The problem seems to be that it's planning a HASH-based distribution from one side of the union (the one with the aggregation) and a FIXED-ARBITRARY for the other side, which are incompatible (at least as far as PlanFragmenter is concerned). Still investigating...

**Comment by pnowojski** [comment]
I'm looking into this
