### ISSUE TITLE
Flaky test TestHiveStorageFormats#testInsertIntoPartitionedTable

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#8084]
(this is a product test)

**Comment by maciejgrzybek** [comment]
It's not flaky. It fails constantly.

**Comment by findepi** [comment]
Maybe. But even this consistent failure is flaky 😄

**Comment by cawallin** [comment]
This test (when run on dwrf) causes one of the following two errors quite consistently:
```
presto-master_1       | #
presto-master_1       | # A fatal error has been detected by the Java Runtime Environment:
presto-master_1       | #
presto-master_1       | #  SIGSEGV (0xb) at pc=0x00007fa5ea7c8891, pid=5, tid=0x00007fa5d99ff700
presto-master_1       | #
presto-master_1       | # JRE version: OpenJDK Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
presto-master_1       | # Java VM: OpenJDK 64-Bit Server VM (25.121-b13 mixed mode linux-amd64 compressed oops)
presto-master_1       | # Problematic frame:
presto-master_1       | # V  [libjvm.so+0x655891]
presto-master_1       | #
presto-master_1       | # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
presto-master_1       | #
presto-master_1       | # An error report file with more information is saved as:
presto-master_1       | # /var/presto/hs_err_pid5.log
presto-master_1       | 2017-06-13T18:26:21.663Z	INFO	20170613_182618_00152_kt24f.1.0-1-56	com.facebook.presto.hive.HiveEventClient	File created: query: 20170613_182618_00152_kt24f, schema: default, table: storage_formats_test_insert_into_partitioned_dwrf, partition: 'returnflag=A', format: com.facebook.hive.orc.OrcOutputFormat, size: 49322, path: hdfs://hadoop-master:8020/tmp/presto-hdfs/2b7bc72a-6333-47b2-a24b-a2e5bc8f6e0c/returnflag=A/20170613_182618_00152_kt24f_65ac81da-0c11-4ffc-b3d3-d877c49e2cc5
presto-master_1       | 2017-06-13T18:26:21.668Z	INFO	20170613_182618_00152_kt24f.1.0-2-54	com.facebook.presto.hive.HiveEventClient	File created: query: 20170613_182618_00152_kt24f, schema: default, table: storage_formats_test_insert_into_partitioned_dwrf, partition: 'returnflag=R', format: com.facebook.hive.orc.OrcOutputFormat, size: 81358, path: hdfs://hadoop-master:8020/tmp/presto-hdfs/2b7bc72a-6333-47b2-a24b-a2e5bc8f6e0c/returnflag=R/20170613_182618_00152_kt24f_044e60c5-7062-44f0-8877-1180a1863934
presto-master_1       | #
presto-master_1       | # If you would like to submit a bug report, please visit:
presto-master_1       | #   http://bugreport.java.com/bugreport/crash.jsp
presto-master_1       | #
presto-master_1       | /docker/volumes/conf/docker/files/presto-launcher-wrapper.sh: line 23:     5 Aborted                 (core dumped) /docker/volumes/presto-server/bin/launcher -Dnode.id="${HOSTNAME}" -Dcatalog.config-dir="${PRESTO_CONFIG_DIRECTORY}"/catalog --config="${PRESTO_CONFIG_DIRECTORY}/${CONFIG}".properties --jvm-config="${PRESTO_CONFIG_DIRECTORY}"/jvm.config --log-levels-file="${PRESTO_CONFIG_DIRECTORY}"/log.properties --data-dir=/var/presto "$@"
common_presto-master_1 exited with code 134
2017-06-13 18:28:22 INFO: FAILURE     /    com.facebook.presto.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable (Groups: storage_formats) took 2 minutes and 5 seconds
```

and

```
com.teradata.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20170612_201845_00152_ve82c): Error committing write to Hive
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:124)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:85)
	at com.teradata.tempto.query.QueryExecutor.query(QueryExecutor.java:69)
	at com.facebook.presto.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable(TestHiveStorageFormats.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Query failed (#20170612_201845_00152_ve82c): Error committing write to Hive
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1799)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1787)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1756)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.facebook.presto.jdbc.internal.guava.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.facebook.presto.jdbc.internal.guava.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:149)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:233)
	at com.facebook.presto.jdbc.PrestoStatement.executeLargeUpdate(PrestoStatement.java:437)
	at com.facebook.presto.jdbc.PrestoStatement.executeUpdate(PrestoStatement.java:409)
	at com.teradata.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:137)
	at com.teradata.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:117)
	... 16 more
Caused by: com.facebook.presto.spi.PrestoException: Error committing write to Hive
	at com.facebook.presto.hive.RecordFileWriter.commit(RecordFileWriter.java:157)
	at com.facebook.presto.hive.HiveWriter.commit(HiveWriter.java:65)
	at com.facebook.presto.hive.HivePageSink.doFinish(HivePageSink.java:184)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.lambda$executeActionInDoAs$0(UserGroupInformationUtils.java:29)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1678)
	at com.facebook.presto.hive.authentication.UserGroupInformationUtils.executeActionInDoAs(UserGroupInformationUtils.java:27)
	at com.facebook.presto.hive.authentication.ImpersonatingHdfsAuthentication.doAs(ImpersonatingHdfsAuthentication.java:39)
	at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:76)
	at com.facebook.presto.hive.HivePageSink.finish(HivePageSink.java:175)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:57)
	at com.facebook.presto.operator.TableWriterOperator.finish(TableWriterOperator.java:159)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:323)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:541)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	... 3 more
Caused by: org.apache.hadoop.ipc.RemoteException: File /tmp/presto-hdfs/24ca0aa2-e8f7-4908-b714-6dedf390cfb9/returnflag=N/20170612_201845_00152_ve82c_4b01391d-ee94-4f1a-aaff-400118cab2c5 could only be replicated to 0 nodes instead of minReplication (=1).  There are 1 datanode(s) running and no node(s) are excluded in this operation.
	at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:1622)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:3351)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:683)
	at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.addBlock(AuthorizationProviderProxyClientProtocol.java:214)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:495)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2141)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2137)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1714)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2135)

	at org.apache.hadoop.ipc.Client.call(Client.java:1475)
	at org.apache.hadoop.ipc.Client.call(Client.java:1412)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy243.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.addBlock(ClientNamenodeProtocolTranslatorPB.java:418)
	at sun.reflect.GeneratedMethodAccessor593.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy244.addBlock(Unknown Source)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.locateFollowingBlock(DFSOutputStream.java:1455)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1251)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:448)
```

**Comment by cawallin** [comment]
@martint It seems like updating the Java version helped a little in the frequency of the JVM crashes, but the dwrf tests are still failing in ~50% of the builds (mainly because of the Hadoop write error from above -- which I bet is masking a different issue, since all of the other file formats are fine resource wise). We don't have the resources to look into it further right now, what are your thoughts on quarantining that test for now so that we have less noise on Travis?

**Comment by dain** [comment]
Were you able to get a `hs_err_pid*` file?

**Comment by cawallin** [comment]
It doesn't fail locally, we should be able to get that file after this PR is merged: https://github.com/prestodb/presto/pull/8270

**Comment by findepi** [comment]
I retriggered #8270's travis PR job with hope it fails this time. (I run all configurations, not just product tests, in case failure is related to load and load is related to number of running configurations).

**Comment by findepi** [comment]
@cawallin, i also pushed `findepi/save-jvm-error-log-{1,2,3}` to TD/presto (in case PR job doesn't fail or log saving doesn't work for PR jobs).

**Comment by cawallin** [comment]
Thanks! I also realized that we need to update the Java version in the docker images too, I'm in the process of building new ones.

**Comment by cawallin** [comment]
PR to update the docker image version of Java: https://github.com/prestodb/presto/pull/8334

**Comment by fiedukow** [comment]
This test now causes pretty consistent failures when run together with other tests.
I suppose there is some kind of memory leak in DWRF test?

When I run this test with many others (eg. this call):
`./presto-product-tests/bin/run_on_docker.sh singlenode -x quarantine,big_query,profile_specific_tests,tpcds,hive_coercion`
it fails pretty consistently

If I run those test by themselves:
`./presto-product-tests/bin/run_on_docker.sh singlenode -g storage_formats -x quarantine,big_query,profile_specific_tests,tpcds,hive_coercion`
It is consistently successful, but there are too many GC triggers messages for my taste.
This is what I did in TD presto-checks (status tracker):
https://github.com/Teradata/presto-checks/commit/e861c2eb4bf870583a11c5dd992b2bc251cffac8

Disabling DWRF file format in this test (like in commit below) causes those tests to pass consistently, no matter in what context they were started:
https://github.com/Teradata/presto/commit/d54a9b80ec2677776efb7bd42c6cc4158121434a

Currently I only changed the setup of test runs in presto-checks, but this issue will require further investigation, as it seems like real problem.

**Comment by findepi** [comment]
Just to note: this is still a problem. BUMP

**Comment by ilfrin** [comment]
I think this was related to the JVM crash issue I've fixed with https://github.com/prestodb/presto/pull/9472, closing.

**Comment by karteekmurthys** [comment]
[This run failed with](https://github.com/prestodb/presto/actions/runs/6200486314/job/16835268147?pr=20381)

```
2023-09-15 22:42:47 INFO: FAILURE     /    com.facebook.presto.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable (Groups: storage_formats) took 2.2 seconds
2023-09-15 22:42:47 SEVERE: Failure cause:
io.prestodb.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20230915_165746_00250_kkki4): Error committing write to Hive
	at io.prestodb.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:115)
	at io.prestodb.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:83)
	at io.prestodb.tempto.query.QueryExecutor.query(QueryExecutor.java:57)
	at com.facebook.presto.tests.hive.TestHiveStorageFormats.testInsertIntoPartitionedTable(TestHiveStorageFormats.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
```
