### ISSUE TITLE
order by operator "Query exceeded local memory limit"

### ISSUE THREAD

**Issue by onealcenter** [prestodb/presto#8152]
I have a table of 8 million records and it occupies about 800M memory. I execute sql "select * from tablename order by column1 desc", however presto return exception "Query exceeded local memory limit".

this is the completed exception info:
```
com.facebook.presto.ExceededMemoryLimitException: Query exceeded local memory limit of 4.50GB
	at com.facebook.presto.ExceededMemoryLimitException.exceededLocalLimit(ExceededMemoryLimitException.java:34)
	at com.facebook.presto.memory.QueryContext.reserveMemory(QueryContext.java:93)
	at com.facebook.presto.operator.TaskContext.reserveMemory(TaskContext.java:154)
	at com.facebook.presto.operator.PipelineContext.reserveMemory(PipelineContext.java:220)
	at com.facebook.presto.operator.DriverContext.reserveMemory(DriverContext.java:191)
	at com.facebook.presto.operator.OperatorContext.reserveMemory(OperatorContext.java:221)
	at com.facebook.presto.operator.OperatorContext.setMemoryReservation(OperatorContext.java:310)
	at com.facebook.presto.operator.OrderByOperator.addInput(OrderByOperator.java:187)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:309)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:654)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:808)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I think it is abnormal, and I am very hope to learn about the function of "reserveMemory". I deeply doubt that whether or not "reserveMemory" function uses more memory than normal

thanks!!!

**Comment by hellium01** [comment]
Hi, onealcenter, which version are you running. It seems like the page added into orderby operator was not compacted. This should be resolved in latest versions.

**Comment by onealcenter** [comment]
my version is 172. just now,i compare 172 and 177, and i find that version 177 adds [cid:ce3b8f2f-3827-43b7-903d-9b9a74478769]
i will change main module to 177, hope to solve this question

thanks!!!
________________________________
发件人: Yi He <notifications@github.com>
发送时间: 2017年6月1日 12:48:21
收件人: prestodb/presto
抄送: YUE LI; Author
主题: Re: [prestodb/presto] order by operator "Query exceeded local memory limit" (#8152)


Hi, onealcenter, which version are you running. It seems like the page added into orderby operator was not compacted. This should be resolved in latest versions.

―

**Comment by rahul9269** [comment]
Were you able to resolve the issue in 177

**Comment by tooptoop4** [comment]
@onealcenter did u resolve?
