### ISSUE TITLE
com.facebook.presto.spi.PrestoException: HIVE_CURSOR_ERROR | AVRO + Presto 

### ISSUE THREAD

**Issue by shivani147** [prestodb/presto#8154]
I am trying to avro data from hdfs. I have deployed the latest version of presto i.e. 0.177, but while querying the data from hive it is working and the same query is not working for presto. Error is 
2017-05-31T16:17:28.968+0530	ERROR	remote-task-callback-4	com.facebook.presto.execution.StageStateMachine	Stage 20170531_104728_00003_bhypt.1 failed
com.facebook.presto.spi.PrestoException: HIVE_CURSOR_ERROR
	at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:218)
	at com.facebook.presto.hive.HiveRecordCursor.advanceNextPosition(HiveRecordCursor.java:179)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:99)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.hadoop.hive.serde2.avro.BadSchemaException
	at org.apache.hadoop.hive.serde2.avro.AvroSerDe.deserialize(AvroSerDe.java:199)
	at com.facebook.presto.hive.GenericHiveRecordCursor.advanceNextPosition(GenericHiveRecordCursor.java:212)

**Comment by shshnksxn** [comment]
I am also facing same issue. 
started with older version 0.146 and then tried with varied versions till 0.177 release. However, no luck with reading avro data from presto .

Please help !!!

**Comment by raghavsethi** [comment]
@martint do you know somebody with Avro experience who could look at this?

**Comment by nezihyigitbasi** [comment]
There is not much info here to understand what's going on. 

@shivani147 do you have a test case to reproduce this? If you can provide one I can help you with debugging.

Also when I look at the AvroSerde [source](https://github.com/apache/hive/blob/release-1.2.1/serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerDe.java#L175-L176) there should be a warning level log message with more info, do you see that in your logs?

If you are familiar with debugging Java code, you can use a debugger and put a breakpoint at `AvroSerdeUtils ::determineSchemaOrThrowException()` and step through the code to understand what's really going on.

**Comment by dain** [comment]
IIRC Avro supports a bunch of methods for fetching file schema (e.g. stored in each file, stored in separate HDFS file, stored in http server, etc), and each one has different things that make integration difficult.  For someone to look at this this, they will need to know which schema style you are using and how to reproduce the problems.  For example, the Hive commands you used to create the table.

**Comment by shivani147** [comment]
@nezihyigitbasi @dain 
Here are the details, This is how I have created  the hive table
CREATE EXTERNAL TABLE `a_1089`(
  `m1` string COMMENT '', 
  `m2` string COMMENT '', 
  `m3` string COMMENT '', 
  `m4` string COMMENT '', 
  `m5` string COMMENT '')
PARTITIONED BY ( 
  `year` int, 
  `month` int, 
  `day` int, 
  `hour` int)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.avro.AvroSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.avro.AvroContainerOutputFormat'
LOCATION
  'hdfs://xx.xx.xx.xx:8020/path/to/data1/hourly'
TBLPROPERTIES (
  'avro.schema.url'='hdfs:////path/to/data1/schemas/225')

  This is my avro schema
  {"doc": "description", "type": "record", "name": "n225", "fields": [{"default": "null", "type": "string", "name": "m1"}, {"default": "null", "type": "string", "name": "m2"}, {"default": "null", "type": "string", "name": "m3"}, {"default": "null", "type": "string", "name": "m4"}, {"default": "null", "type": "string", "name": "m5"}]}
and the logs which I have pasted above is the server logs of presto.

This schema has only string datatype, but we have cases where we are using other datatype also.

**Comment by subashram** [comment]
one work around is to use avro.schema.literal and embed schema as part of create external table.

**Comment by findepi** [comment]
Closing in favor of https://github.com/prestodb/presto/issues/11548
