### ISSUE TITLE
Planning failure for ORDER BY...LIMIT with similar expressions

### ISSUE THREAD

**Issue by martint** [prestodb/presto#8194]
```SQL
WITH t AS (SELECT 1 x, 1 y) 
SELECT x, y 
FROM t
ORDER BY x, y
LIMIT 1
```

```
Query 20170606_002050_01487_rgj4j failed: Multiple entries with same key: expr=ASC_NULLS_LAST and expr=ASC_NULLS_LAST
java.lang.IllegalArgumentException: Multiple entries with same key: expr=ASC_NULLS_LAST and expr=ASC_NULLS_LAST
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:186)
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:102)
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:88)
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:359)
	at com.facebook.presto.sql.planner.optimizations.SymbolMapper.map(SymbolMapper.java:128)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitTopN(UnaliasSymbolReferences.java:448)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitTopN(UnaliasSymbolReferences.java:117)
	at com.facebook.presto.sql.planner.plan.TopNNode.accept(TopNNode.java:119)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitProject(UnaliasSymbolReferences.java:403)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitProject(UnaliasSymbolReferences.java:117)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitProject(UnaliasSymbolReferences.java:403)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitProject(UnaliasSymbolReferences.java:117)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitProject(UnaliasSymbolReferences.java:403)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitProject(UnaliasSymbolReferences.java:117)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitOutput(UnaliasSymbolReferences.java:410)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences$Rewriter.visitOutput(UnaliasSymbolReferences.java:117)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:27)
	at com.facebook.presto.sql.planner.optimizations.UnaliasSymbolReferences.optimize(UnaliasSymbolReferences.java:114)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:129)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:120)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:312)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kokosing** [comment]
I will give it a shoot.

**Comment by findepi** [comment]
Closing, #8196 is merged.
