### ISSUE TITLE
Planning failure when using GROUPING and legacy_order_by=true

### ISSUE THREAD

**Issue by martint** [prestodb/presto#8207]
```
presto> set session legacy_order_by=true;
SET SESSION

presto> SELECT grouping(a) FROM (VALUES (1) ) AS t (a) GROUP BY a;

Query 20170607_011620_02738_84kx5 failed: GroupingOperation should have been re-written to a FunctionCall before execution
java.lang.IllegalStateException: GroupingOperation should have been re-written to a FunctionCall before execution
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.desugar(DesugaringOptimizer.java:198)
	at com.facebook.presto.sql.planner.plan.Assignments.lambda$rewrite$1(Assignments.java:109)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.Assignments.rewrite(Assignments.java:110)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:125)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:95)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:124)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitProject(DesugaringOptimizer.java:77)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:74)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:38)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:99)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer$Rewriter.visitPlan(DesugaringOptimizer.java:77)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:27)
	at com.facebook.presto.sql.planner.optimizations.DesugaringOptimizer.optimize(DesugaringOptimizer.java:74)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:130)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:121)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:312)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:247)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
cc @petroav
