### ISSUE TITLE
NPE "Value cannot be cast to map(varchar,varchar)"

### ISSUE THREAD

**Issue by dain** [prestodb/presto#8254]
```
Caused by: com.facebook.presto.spi.PrestoException: Value cannot be cast to map(varchar,varchar)
	at com.facebook.presto.operator.scalar.JsonToMapCast.toMap(JsonToMapCast.java:94)
	at com.facebook.presto.$gen.PageFilter_10704.filter(Unknown Source)
	at com.facebook.presto.$gen.PageFilter_10704.filter(Unknown Source)
	at com.facebook.presto.operator.project.DictionaryAwarePageFilter.filter(DictionaryAwarePageFilter.java:85)
	at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:80)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:283)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:541)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: string is null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at io.airlift.slice.Slices.copiedBuffer(Slices.java:289)
	at io.airlift.slice.Slices.utf8Slice(Slices.java:297)
	at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObjectHelper(TypeJsonUtils.java:134)
	at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObjectHelper(TypeJsonUtils.java:109)
	at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObject(TypeJsonUtils.java:74)
	at com.facebook.presto.operator.scalar.JsonToMapCast.toMap(JsonToMapCast.java:80)
	... 16 more

**Comment by wenleix** [comment]
A simple query to reproduce the issue:

This is an existing issue with `TypeJsonUtils`, in https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/type/TypeJsonUtils.java#L134 , `parser.getValueAsString()` will return `null` when the next input to the parser is a JSON Array/Object.

```
presto> SELECT CAST(JSON '{"a":["b"]}' AS MAP<VARCHAR, VARCHAR>);

Query 20170613_172152_41958_7nxjn failed: Value cannot be cast to map(varchar,varchar)
com.facebook.presto.spi.PrestoException: Value cannot be cast to map(varchar,varchar)
        at com.facebook.presto.operator.scalar.JsonToMapCast.toMap(JsonToMapCast.java:94)
        at com.facebook.presto.$gen.PageProjection_345184.project(Unknown Source)
        at com.facebook.presto.$gen.PageProjection_345184.project(Unknown Source)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:179)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:125)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:99)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:51)
        at com.facebook.presto.operator.FilterAndProjectOperator.isFinished(FilterAndProjectOperator.java:71)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: string is null
        at java.util.Objects.requireNonNull(Objects.java:228)
        at io.airlift.slice.Slices.copiedBuffer(Slices.java:289)
        at io.airlift.slice.Slices.utf8Slice(Slices.java:297)
        at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObjectHelper(TypeJsonUtils.java:134)
        at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObjectHelper(TypeJsonUtils.java:109)
        at com.facebook.presto.type.TypeJsonUtils.stackRepresentationToObject(TypeJsonUtils.java:74)
        at com.facebook.presto.operator.scalar.JsonToMapCast.toMap(JsonToMapCast.java:80)
```

**Comment by wenleix** [comment]
The cast is expected to fail when it tries to cast an JSON array/object to VARCHAR. And it is wrapped PrestoException with Error Code INVALID_CAST_ARGUMENT.

Just the stacktrace  is quite vague (Null Pointer Exception ).

We are going to rewrite the legacy JSON -> ARRAY/MAP CAST in https://github.com/prestodb/presto/pull/8217. So hopefully it will produce more useful information :)
