### ISSUE TITLE
Query with lambda function on Group By fails

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#8274]
Query 

```sql
WITH tbl AS (
SELECT ARRAY[regionkey] as arr
FROM nation)

SELECT transform(arr, x->x+1), count(*)
FROM tbl
GROUP BY transform(arr, x->x+1) 
```

fails with the following message:

```
Query 20170615_003438_00022_vy8kz failed: Invalid node. Expression dependencies ([expr_1]) not in source plan output ([transform, $hashvalue, count])
java.lang.IllegalArgumentException: Invalid node. Expression dependencies ([expr_1]) not in source plan output ([transform, $hashvalue, count])
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.checkDependencies(ValidateDependenciesChecker.java:597)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.access$100(ValidateDependenciesChecker.java:79)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:237)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitProject(ValidateDependenciesChecker.java:93)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:449)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitExchange(ValidateDependenciesChecker.java:93)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:196)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:276)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker$Visitor.visitOutput(ValidateDependenciesChecker.java:93)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:90)
	at com.facebook.presto.sql.planner.sanity.ValidateDependenciesChecker.validate(ValidateDependenciesChecker.java:85)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validate$0(PlanSanityChecker.java:45)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validate(PlanSanityChecker.java:45)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:137)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:121)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:312)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:291)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:247)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Group by ordinal columns works:
```sql
WITH tbl AS (
SELECT ARRAY[regionkey] as arr
FROM nation)

SELECT transform(arr, x->x+1), count(*)
FROM tbl
GROUP BY 1
```

**Comment by wenleix** [comment]
Duplicate of https://github.com/prestodb/presto/issues/7140
