### ISSUE TITLE
Add LZOP support to the new Parquet reader

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#8318]
See issue #8290. 

#5107 is the PR that I added the LZO support to Parquet. Since aircompressor already handles LZOP it shouldn't be that difficult to add it in a similar way.

**Comment by dabaitu** [comment]
Quick question as I tried to work on this a bit myself. What was the reason you used the LzoDecompressor from aircompressor but not the LzoCodec?
FYI, I tried to use LzopCodec from aircompressor, but it didn't work. See: [convo with Dain in aircompressor](https://github.com/airlift/aircompressor/commit/4b18723cb19fac56804698a85a450f8d30e8fdf3#commitcomment-22632224).
The optimized reader you guys referred to on the roadmaps meeting a month or two back is this ParquetPageReader, right? Thanks!!

**Comment by nezihyigitbasi** [comment]
When you use `LzoCodec` it uses `HadoopLzoInputStream`, which uses `LzoDecompressor` anyway under the hood. `LzoCodec` is a Hadoop codec and in this case we don't need a Hadoop codec.

Yes, it's the new reader. `ParquetHiveRecordCursor` is the old reader.

**Comment by dabaitu** [comment]
Right, I thought if you used the LzoCodec directly you won't need to write the surrounding code to call LzoDecompressor byte by byte.
So I guess the codecs in aircompressor aren't used at all in Presto.

**Comment by dain** [comment]
@dabaitu can you try https://github.com/airlift/aircompressor/pull/67

**Comment by dabaitu** [comment]
Hi @dain, am on travel. Just tried this. Still getting the same error:
`com.facebook.presto.spi.PrestoException: Error reading dictionary page
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:225)
	at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:204)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error reading dictionary page
	at com.facebook.presto.hive.parquet.reader.ParquetPageReader.readDictionaryPage(ParquetPageReader.java:111)
	at com.facebook.presto.hive.parquet.reader.ParquetColumnReader.setPageReader(ParquetColumnReader.java:122)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:263)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readBlock(ParquetReader.java:317)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:196)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:183)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:201)
	... 12 more
Caused by: java.io.IOException: Not an LZOP file
	at io.airlift.compress.lzo.HadoopLzopInputStream.<init>(HadoopLzopInputStream.java:59)
	at io.airlift.compress.lzo.LzopCodec.createInputStream(LzopCodec.java:84)
	at com.facebook.presto.hive.parquet.ParquetCompressionUtils.decompressLZOP(ParquetCompressionUtils.java:99)
	at com.facebook.presto.hive.parquet.ParquetCompressionUtils.decompress(ParquetCompressionUtils.java:61)
	at com.facebook.presto.hive.parquet.reader.ParquetPageReader.readDictionaryPage(ParquetPageReader.java:106)
	... 18 more`

**Comment by dain** [comment]
I don't know much about Parquet, but you're still getting `Caused by: java.io.IOException: Not an LZOP file`.  This is the first line of the decompressor where we check the stream header to determine if this is LZOP format or not.  My guess is either Paquet is not using LZOP and instead is using LZO with Hadoop framing.

**Comment by nezihyigitbasi** [comment]
@dabaitu Can you decompress your file with the lzop [utility](https://www.lzop.org/)? That will rule out the first possibility.

**Comment by nezihyigitbasi** [comment]
BTW please provide more info about how this file is written (by Presto, or some other engine, etc.)?

**Comment by dabaitu** [comment]
Updates:

I swapped out the airlift LzopCodec with the com.hadoop.compression.lzo.LzopCodec and getting basically the same error, which is complaining about the slice missing the magic lzop header.

Reading the same data with the ParquetRecordReader works fine.

My hunch is maybe the slices aren't split up correctly. Still digging.

**Comment by dabaitu** [comment]
Updates:

Using the com.hadoop.compression.lzo.LzoCodec got the decompression step to work, but failed here:

`com.facebook.presto.spi.PrestoException: length of sub blocks differ: block 0: 77, block 1: 54
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:225)
	at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:204)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: length of sub blocks differ: block 0: 77, block 1: 54
	at com.facebook.presto.spi.block.InterleavedBlock.<init>(InterleavedBlock.java:48)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:210)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:187)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:201)
	... 12 more`

Looks like abstraction of Map object isn't working correctly.

I think somebody told me this earlier that lzop is for compressing entire files, but I just grasped what that meant. So Parquet breaks column rows into groups, and each group is a batch of column rows that's called a page and each page gets compressed by lzo. So in the pageReader, it was decompressing slices or pages which should use lzo decompressor.

Using the LzoCodec from aircompressor still fails in decompression:
`io.airlift.compress.MalformedInputException: Malformed input: offset=22
	at io.airlift.compress.lzo.LzoRawDecompressor.decompress(LzoRawDecompressor.java:264)
	at io.airlift.compress.lzo.LzoDecompressor.decompress(LzoDecompressor.java:36)
	at io.airlift.compress.lzo.HadoopLzoInputStream.read(HadoopLzoInputStream.java:72)
	at com.facebook.presto.hive.parquet.ParquetCompressionUtils.decompressLZOP(ParquetCompressionUtils.java:102)
	at com.facebook.presto.hive.parquet.ParquetCompressionUtils.decompress(ParquetCompressionUtils.java:61)
	at com.facebook.presto.hive.parquet.reader.ParquetPageReader.readPage(ParquetPageReader.java:72)
	at com.facebook.presto.hive.parquet.reader.ParquetColumnReader.readNextPage(ParquetColumnReader.java:250)
	at com.facebook.presto.hive.parquet.reader.ParquetColumnReader.readPrimitive(ParquetColumnReader.java:162)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:269)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readPrimitive(ParquetReader.java:251)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:283)
	at com.facebook.presto.hive.parquet.ParquetPageSource$ParquetBlockLoader.load(ParquetPageSource.java:259)
	at com.facebook.presto.spi.block.LazyBlock.assureLoaded(LazyBlock.java:242)
	at com.facebook.presto.spi.block.LazyBlock.isNull(LazyBlock.java:218)
	at com.facebook.presto.$gen.PageFilter_22.filter(Unknown Source)
	at com.facebook.presto.$gen.PageFilter_22.filter(Unknown Source)
	at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:80)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:283)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:458)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by dabaitu** [comment]
Another update:
Using com.hadoop.compression.lzo.LzoCodec got the recordReader to work with predicate pushdown. The stats filter always worked in predicate pushdown, and this made dictionary filter to work if the dictionary is there.

Looking at 2 issues with debugger:
1. Decompression logic in aircompressor LzoCodec
2. Building map object out of groups of key,val pairs in pageReader

**Comment by dotcomputercraft** [comment]
@dabaitu -  Any updates on this issue? thank you in advance

**Comment by luohao** [comment]
@dain Is LZO compatible with LZOP (e.g, use LzoCodec to decompress the LzopCodec compressed data)? I run into some errors when enable the new parquet optimized reader, but everything works fine with the old record reader.
