### ISSUE TITLE
`TRY(MAP(ARRAY[NULL], ARRAY[x]))` fails

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8323]
The query below fails

    SELECT
      TRY(MAP(ARRAY[NULL], ARRAY[x]))
    FROM
      (VALUES 1, 2) t(x);

with error stack trace

    java.lang.IllegalStateException: Expected current entry to be closed but was opened
            at com.facebook.presto.spi.block.MapBlockBuilder.beginBlockEntry(MapBlockBuilder.java:152)
            at com.facebook.presto.spi.block.MapBlockBuilder.beginBlockEntry(MapBlockBuilder.java:29)
            at com.facebook.presto.operator.scalar.MapConstructor.createMap(MapConstructor.java:105)
            at com.facebook.presto.$gen.PageProjection_90585.try_0(Unknown Source)
            at com.facebook.presto.$gen.PageProjection_90585.project(Unknown Source)
            at com.facebook.presto.$gen.PageProjection_90585.project(Unknown Source)
            at com.facebook.presto.operator.project.DictionaryAwarePageProjection.project(DictionaryAwarePageProjection.java:97)
            at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:179)
            at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:125)
            at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:99)
            at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
            at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
            at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:51)
            at com.facebook.presto.operator.FilterAndProjectOperator.isFinished(FilterAndProjectOperator.java:71)
            at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
            at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
            at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
            at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
            at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
            at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
            at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:748)

This sequence of event explains the root cause:

* Certain functions (mostly functions that return array/map) use a feature in the Presto function framework called `instanceFactory` to avoid repeated allocation of `BlockBuilder`s and to avoid the burden of estimating the size of the allocation.
* When a function fails, it leaves the `BlockBuilder` in a broken state.
* The exception is caught by `TRY`. As a result, the function will be invoked again.
* When the function gets invoked again, it uses the broken `BlockBuilder` and fails.

To fix this:

* Some of the functions uses byte code generated. Working with `try ... catch` in byte code generation is hard. Making things worse, Presto almost exclusively use stack to maintain intermediates during byte code generation. It doesn't use local variables. Stack is completely dropped by JVM before a catch block is executed. In addition, we don't really want to handle this in every function implementation. That is error prone and burdensome for future functions.
* Adding a `try...catch` to projection/filter processor to reset the `instance` a function maintains. Such processors are also generated. And the above mentioned complexity applies. (Resetting the `instance`s also carry a cost.)
* Revamp the way exceptions that can be caught by `TRY` are thrown, so that they don't actually throw a Java exception. (Instead, use a passed-in object to track exceptions.) Further, require that all functions make sure that states are left in a good state.

The last fix is the one we would like.

It is not a straightforward fix. As a result, we would settle for a quick temporary mitigation. This doesn't fix the issue, but would get us a more deterministic behavior.

* Throw an exception using error code GENERIC_INTERNAL_ERROR from functions that uses `BlockBuilder`s as intermediate states so that it can't be caught by `TRY`. Add tests for this (and improve function test framework to enable such tests). We considered using a special error code, but after discussion with @martint, we decide to go with GENERIC_INTERNAL_ERROR for now.

**Comment by haozhun** [comment]
I found another issue that root causes to the thing, but with a different query shape.

When columnar processing is turned on, for `DictionaryBlock`s, evaluation for filtered-out positions could happen. Filtered-out positions could trigger exceptions. This may leave functions in a bad state (for example, `MapConstructor`). cc @dain 

With this new case, the original proposal of throwing an GENERIC_INTERNAL_ERROR won't help. In the TRY case, it's generally possible to avoid this problem to rewrite the query to avoid using TRY. Here, unlike the TRY case, work-around is likely not available.

This significantly changes how I look at the 3 original proposals.

@nezihyigitbasi raised a 4th alternative solution:

* bring the PageBuilder to a healthy state before return/throw in each of these functions.

I think it's better than the 3rd one we mentioned above, and it's easier than the 1st and 2nd. I believe we should do that instead.

**Comment by nezihyigitbasi** [comment]
actually @electrum raised the 4th alternative solution in #8440. I will update the PR shortly to do that.

**Comment by highker** [comment]
This has been resolved right? @nezihyigitbasi @haozhun

**Comment by haozhun** [comment]
Fixed by #8440
