### ISSUE TITLE
MetaException: Column $path doesn't exist in table

### ISSUE THREAD

**Issue by tomerstar** [prestodb/presto#8380]
This issue happens when using hive catalog (CDH 5.11) and selecting from a non partitioned table. (If table is partitioned the select succeeds). also it is doesnt important if table was created using hive of presto, as long as its using the hive metastore, the error happens.
the select fails with this error:

```
Caused by: org.apache.hadoop.hive.metastore.api.MetaException: Column $path doesn't exist in table t_ddat in database dimension_db
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_statistics_req_result$get_table_statistics_req_resultStandardScheme.read(ThriftHiveMetastore.java)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_statistics_req_result$get_table_statistics_req_resultStandardScheme.read(ThriftHiveMetastore.java)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_statistics_req_result.read(ThriftHiveMetastore.java)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_statistics_req(ThriftHiveMetastore.java:2971)
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_statistics_req(ThriftHiveMetastore.java:2958)
        at com.facebook.presto.hive.ThriftHiveMetastoreClient.getTableColumnStatistics(ThriftHiveMetastoreClient.java:146)
        at com.facebook.presto.hive.metastore.ThriftHiveMetastore.lambda$getTableColumnStatistics$6(ThriftHiveMetastore.java:234)
        at com.facebook.presto.hive.metastore.HiveMetastoreApiStats.lambda$wrap$0(HiveMetastoreApiStats.java:42)
        at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:138)
        at com.facebook.presto.hive.metastore.ThriftHiveMetastore.getTableColumnStatistics(ThriftHiveMetastore.java:232)

**Comment by tomerstar** [comment]
one more: the error is on latest version 0.179
I also tested on earlier version 0.171 - work fine without an error

**Comment by dain** [comment]
What query are you running?

**Comment by tomerstar** [comment]
Select * from <table_name>.
Even "show stats for <table_name>" gets the same error

**Comment by tomerstar** [comment]
As I wrote in my comment.
After running the query in 0.179, I downgraded to 0.171 an reran the query and it was fine

**Comment by weikybeidos** [comment]
Envirenment: CDH 5.12 Kerberized (against ADS) /NO SENTRY

Step1 presto171 (success): 
CREATE TABLE test171 (  col1 varchar );

Step 2 presto 171( success)
select * from test171;

step3 presto 181 (success)
CREATE TABLE test181 (  col1 varchar );

Step 4 presto 181( failed)
presto:default> select * from test181;
Query 20170726_141516_00003_m624j failed: Column $path doesn't exist in table test181 in database default


all etc and catalog files are copied so the config is 100% same and the cluster is the same too.

hope that helps

**Comment by electrum** [comment]
Can you show the output of DESCRIBE?

**Comment by alandpost** [comment]
Fixed in master in https://github.com/prestodb/presto/commit/76200966f82f7067655797576ef966921ab64c49
