### ISSUE TITLE
Null pointer exception throw when explain analyze query contains index join

### ISSUE THREAD

**Issue by hellium01** [prestodb/presto#8432]
If the join type is index join, explain analyze fails with NPE even though query will run fine:

```
java.lang.NullPointerException
        at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.getPlanNodeStats(PlanNodeStatsSummarizer.java:151)
        at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.lambda$aggregatePlanNodeStats$0(PlanNodeStatsSummarizer.java:51)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.aggregatePlanNodeStats(PlanNodeStatsSummarizer.java:52)
        at com.facebook.presto.sql.planner.planPrinter.PlanPrinter.textDistributedPlan(PlanPrinter.java:200)
        at com.facebook.presto.operator.ExplainAnalyzeOperator.getOutput(ExplainAnalyzeOperator.java:154)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by kokosing** [comment]
Can you please post a query? What version of presto are you using?

**Comment by hellium01** [comment]
I observed this in version 0.177. But in latest version of AbstractTestIndexedQueries, if I modify one of the test case to use explain analyze instead, the query will fail with same error message.
