### ISSUE TITLE
the official jdbc demo in doc is not success

### ISSUE THREAD

**Issue by TerryShisan** [prestodb/presto#8472]
I am new user for presto. when i used jdbc demo,is wrong.
```sql
// URL parameters
String url = "jdbc:presto://example.net:8080/hive/sales";
Properties properties = new Properties();
properties.setProperty("user", "test");
properties.setProperty("password", "secret");
Connection connection = DriverManager.getConnection(url, properties);
```
the wrong is Authentication using username/password requires SSL to be enabled.
But when  i add `properties.setProperty("SSL", "true");`
it is connect success,but can not execute any sql,the wrong is:
```
Caused by: java.io.UncheckedIOException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at com.facebook.presto.jdbc.internal.client.JsonResponse.execute(JsonResponse.java:148)
	at com.facebook.presto.jdbc.internal.client.StatementClient.<init>(StatementClient.java:118)
	at com.facebook.presto.jdbc.QueryExecutor.startQuery(QueryExecutor.java:45)
	at com.facebook.presto.jdbc.PrestoConnection.startQuery(PrestoConnection.java:606)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:219)
	... 7 more
```
But when I use `./presto --server localhost:8080 --catalog hive --schema default`,
it is ok, i can execute sql.
what can i do next????hope response sincerely....

**Comment by electrum** [comment]
Sorry for the confusion! That example was intended to show the equivalence of properties and URL parameters. We'll fix it so that it works out-of-the-box.

To fix your code, remove the `"password"` property (which isn't used unless you setup SSL and LDAP authentication).

**Comment by TerryShisan** [comment]
in fact,it also wrong when execute sql,the wrong is:
returned an invalid response: JsonResponse{statusCode=405, statusMessage=Method Not Allowed, headers={content-language=[en], content-length=[1067], content-type=[text/html;charset=utf-8], date=[Thu, 13 Jul 2017 11:37:42 GMT], server=[Apache-Coyote/1.1]}, hasValue=false} [Error: <html><head><title>Apache Tomcat/7.0.52 - Error report</title><style></style> </head><body><h1>HTTP Status 405 - HTTP method POST is not supported by this URL</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>HTTP method POST is not supported by this URL</u></p><p><b>description</b> <u>The specified HTTP method is not allowed for the requested resource.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52</h3></body></html>]
	at com.facebook.presto.jdbc.internal.client.StatementClient.requestFailedException(StatementClient.java:362)
	at com.facebook.presto.jdbc.internal.client.StatementClient.<init>(StatementClient.java:120)
	at com.facebook.presto.jdbc.QueryExecutor.startQuery(QueryExecutor.java:45)
	at com.facebook.presto.jdbc.PrestoConnection.startQuery(PrestoConnection.java:606)
	at com.facebook.presto.jdbc.PrestoStatement.execute(PrestoStatement.java:219)
	... 7 more

but i used teradata's presto-jdbc42 ,is everything ok...........................

**Comment by electrum** [comment]
Since you see "Apache Tomcat", this means you are connecting to something other than Presto (we don't use Tomcat). Please verify the host and port in the JDBC URL.
