### ISSUE TITLE
TestAccumuloDistributedQueries::testExplainAnalyze is flaky

### ISSUE THREAD

**Issue by flakycov** [prestodb/presto#8494]
TestAccumuloDistributedQueries::testExplainAnalyze failed for us on commit [87911b1](https://github.com/prestodb/presto/commit/87911b1c2478402b73233f9bdb1b93ec5e281f10) but did not fail in [the corresponding run on Travis](https://travis-ci.org/prestodb/presto/jobs/234144015):

```
testExplainAnalyze(com.facebook.presto.accumulo.TestAccumuloDistributedQueries)  Time elapsed: 9.969 sec  <<< FAILURE!
com.facebook.presto.client.FailureInfo$FailureException: null
	at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.getPlanNodeStats(PlanNodeStatsSummarizer.java:151)
	at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.lambda$aggregatePlanNodeStats$0(PlanNodeStatsSummarizer.java:51)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.aggregatePlanNodeStats(PlanNodeStatsSummarizer.java:52)
	at com.facebook.presto.sql.planner.planPrinter.PlanPrinter.textDistributedPlan(PlanPrinter.java:200)
	at com.facebook.presto.operator.ExplainAnalyzeOperator.getOutput(ExplainAnalyzeOperator.java:154)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Our investigation shows that this test is likely flaky. We set up our build environment to be as close to your Travis environment as possible, using Ubuntu 14.04.5 LTS, Java HotSpot 1.8.0_111-b14 and Maven 3.3.9.

**Comment by ArturGajowy** [comment]
This also happens for `TestRaptorDistributedQueries` :(

```

Tests run: 1668, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,422.247 sec <<< FAILURE! - in TestSuite
testExplainAnalyze(com.facebook.presto.raptor.TestRaptorDistributedQueries)  Time elapsed: 4.247 sec  <<< FAILURE!
com.facebook.presto.client.FailureInfo$FailureException


Results :

Failed tests: 
  TestRaptorDistributedQueries.testExplainAnalyze Â» Failure

Tests run: 1668, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24:00 min
[INFO] Finished at: 2017-07-25T12:01:11Z
[INFO] Final Memory: 69M/255M
[INFO] ------------------------------------------------------------------------
```

**Comment by flakycov** [comment]
We also observed this for `TestHiveDistributedQueries` on commit 47ae3ae, and it did not fail for [the corresponding run on Travis](https://travis-ci.org/prestodb/presto/jobs/257706078):
```
Tests run: 1052, Failures: 1, Errors: 0, Skipped: 47, Time elapsed: 1,612.778 sec <<< FAILURE! - in TestSuite
testExplainAnalyze(com.facebook.presto.hive.TestHiveDistributedQueries)  Time elapsed: 5.157 sec  <<< FAILURE!
com.facebook.presto.client.FailureInfo$FailureException
```

**Comment by adamjshook** [comment]
Ran into this during some new feature development in the Accumulo connector.  Stack trace below -- this is based against version 0.178.

```
testExplainAnalyze
java.lang.NullPointerException
	at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.getPlanNodeStats(PlanNodeStatsSummarizer.java:151)
	at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.lambda$aggregatePlanNodeStats$0(PlanNodeStatsSummarizer.java:51)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.planPrinter.PlanNodeStatsSummarizer.aggregatePlanNodeStats(PlanNodeStatsSummarizer.java:52)
	at com.facebook.presto.sql.planner.planPrinter.PlanPrinter.textDistributedPlan(PlanPrinter.java:200)
	at com.facebook.presto.operator.ExplainAnalyzeOperator.getOutput(ExplainAnalyzeOperator.java:154)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by findepi** [comment]
https://github.com/prestodb/presto/pull/11290 's build failed today on this

**Comment by sopel39** [comment]
Fixed via: https://github.com/prestodb/presto/pull/11211
