### ISSUE TITLE
NPE when selecting maps with complex keys/values from a Cassandra table

### ISSUE THREAD

**Issue by pistolero** [prestodb/presto#8501]
```
2017-07-14T10:11:17.898Z	ERROR	SplitRunner-40-174	com.facebook.presto.execution.executor.TaskExecutor	Error processing Split 20170714_101117_00014_ufct8.1.0-1 {hosts=[/136.243.58.104:9042, /88.99.4.23:9042, /88.99.254.32:9042], schema=sempi, table=project, partitionId=<UNPARTITIONED>} (start = 1.726110616791506E10, wall = 12 ms, cpu = 0 ms, wait = 0 ms, calls = 1)
java.lang.NullPointerException
	at com.datastax.driver.$internal.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken.<init>(TypeToken.java:149)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken.<init>(TypeToken.java:95)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken$SimpleTypeToken.<init>(TypeToken.java:1056)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken.of(TypeToken.java:154)
	at com.datastax.driver.core.AbstractGettableByIndexData.getMap(AbstractGettableByIndexData.java:327)
	at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:26)
	at com.facebook.presto.cassandra.CassandraType.buildMapValue(CassandraType.java:255)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:214)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:165)
	at com.facebook.presto.cassandra.CassandraRecordCursor.getSlice(CassandraRecordCursor.java:121)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:123)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:538)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2017-07-14T10:11:17.914Z	ERROR	remote-task-callback-15	com.facebook.presto.execution.StageStateMachine	Stage 20170714_101117_00014_ufct8.1 failed
java.lang.NullPointerException
	at com.datastax.driver.$internal.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken.<init>(TypeToken.java:149)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken.<init>(TypeToken.java:95)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken$SimpleTypeToken.<init>(TypeToken.java:1056)
	at com.datastax.driver.$internal.com.google.common.reflect.TypeToken.of(TypeToken.java:154)
	at com.datastax.driver.core.AbstractGettableByIndexData.getMap(AbstractGettableByIndexData.java:327)
	at com.datastax.driver.core.AbstractGettableData.getMap(AbstractGettableData.java:26)
	at com.facebook.presto.cassandra.CassandraType.buildMapValue(CassandraType.java:255)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:214)
	at com.facebook.presto.cassandra.CassandraType.getColumnValue(CassandraType.java:165)
	at com.facebook.presto.cassandra.CassandraRecordCursor.getSlice(CassandraRecordCursor.java:121)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:123)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:538)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:463)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by cawallin** [comment]
What data are you selecting? We have testing for basic MAP types, I believe; do you have null values in your data?

**Comment by pistolero** [comment]
@cawallin sorry, missed your question.

it fails for collumn with a following schema:
```
blacklisted map<ascii, frozen<list<text>>>
```

And here is data causing it to fail:
```
{'en': ['test']}
```

**Comment by cawallin** [comment]
@pistolero Yeah, we only test maps with simple types; it does look like the Cassandra connector does not handle maps with complex types as keys/values. Happy to provide pointers if you'd be interested in fixing this yourself!
