### ISSUE TITLE
approx_percentile() with percentages array fails when used as window function

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8559]
```
presto> select approx_percentile(42, array[0.5]) over ();

Query 20170720_165839_00007_qt844 failed: com.facebook.presto.spi.function.WindowIndex.getObject(II)Lcom/facebook/presto/spi/block/Block;
java.lang.NoSuchMethodError: com.facebook.presto.spi.function.WindowIndex.getObject(II)Lcom/facebook/presto/spi/block/Block;
	at com.facebook.presto.$gen.Array_bigint_BigintArray_double_ApproxPercentileAccumulator_70.addInput(Unknown Source)
	at com.facebook.presto.operator.window.AggregateWindowFunction.accumulate(AggregateWindowFunction.java:81)
	at com.facebook.presto.operator.window.AggregateWindowFunction.processRow(AggregateWindowFunction.java:71)
	at com.facebook.presto.operator.window.WindowPartition.processNextRow(WindowPartition.java:108)
	at com.facebook.presto.operator.WindowOperator.extractOutput(WindowOperator.java:439)
	at com.facebook.presto.operator.WindowOperator.getOutput(WindowOperator.java:395)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:300)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:538)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:623)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by electrum** [comment]
@maciejgrzybek This looks related to ea138ba7d0fe5400972f2f3609208a1f993b87e9

**Comment by maciejgrzybek** [comment]
I will look into it right after I finish the investigation of cost calculator for the upcoming Teradata release, unless it's urgent/critical. Is it, @electrum?
