### ISSUE TITLE
Add support for third-party compression codecs like LZO

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#856]
We need a non-hacky way to support Hadoop compression codecs that can't be shipped with Presto (for example, LZO which is GPL). Having a very basic plugin interface (inside the Hive plugin, yay) using `ServiceLoader` that can add the codec to the Hadoop configuration will probably work. The plugins can bundle the native libraries like the Hadoop code already does.

Additionally, it would be good to allow compressed files to be splittable, so we would need to change split creation to use the methods from the `InputFormat`.

See https://groups.google.com/forum/#!topic/presto-users/_Fe9YrZ3gYg

**Comment by wbchn** [comment]
@FlxRobin 
I am using presto 0.86.
It does not work after set jvm.config and copy hadoop-lzo.jar to plugin/hive-hadoop2 (i use hive-hadoop2)

Is there any other solution after version 0.57?

**Comment by yuananf** [comment]
@FlxRobin The hadoop-lzo.jar should be build on https://github.com/klbostee/hadoop-lzo.
Works fine for presto 0.96.

**Comment by wbchn** [comment]
@yuananf 
Thx for your reply.

I try  https://github.com/klbostee/hadoop-lzo , but got same error:
```
2015-03-05T22:13:35.567-0800	DEBUG	query-execution-4	com.facebook.presto.execution.SqlStageExecution	Stage 20150306_061333_00006_y9z6v.1 is FAILED
2015-03-05T22:13:35.570-0800	DEBUG	query-execution-0	com.facebook.presto.execution.SqlStageExecution	Stage 20150306_061333_00006_y9z6v.0 is FAILED
2015-03-05T22:13:35.573-0800	ERROR	hive-hive-3	com.google.common.util.concurrent.Futures$CombinedFuture	input future failed.
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:na]
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:148) ~[presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.HiveSplitSourceProvider$3.process(HiveSplitSourceProvider.java:258) ~[presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.AsyncWalker.doWalk(AsyncWalker.java:95) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.AsyncWalker.access$000(AsyncWalker.java:34) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.AsyncWalker$1.run(AsyncWalker.java:72) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.SuspendingExecutor$1.run(SuspendingExecutor.java:67) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) [presto-hive-0.72.jar:0.72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:145) ~[presto-hive-0.72.jar:0.72]
	... 14 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.hadoop.mapred.DeprecatedLzoTextInputFormat.isSplitable(DeprecatedLzoTextInputFormat.java:101) ~[hadoop-lzo.jar:na]
	... 19 common frames omitted
2015-03-05T22:13:35.573-0800	DEBUG	query-execution-1	com.facebook.presto.execution.QueryStateMachine	Query 20150306_061333_00006_y9z6v is FAILED

～～～～ more  ～～～～

2015-03-05T22:13:35.591-0800	ERROR	hive-hive-12	com.google.common.util.concurrent.Futures$CombinedFuture	input future failed.
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-16.0.1.jar:na]
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:148) ~[presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.HiveSplitSourceProvider$3.process(HiveSplitSourceProvider.java:258) ~[presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.AsyncWalker.doWalk(AsyncWalker.java:95) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.AsyncWalker.access$000(AsyncWalker.java:34) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.AsyncWalker$1.run(AsyncWalker.java:72) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.SuspendingExecutor$1.run(SuspendingExecutor.java:67) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) [presto-hive-0.72.jar:0.72]
	at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) [presto-hive-0.72.jar:0.72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:145) ~[presto-hive-0.72.jar:0.72]
	... 14 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.hadoop.mapred.DeprecatedLzoTextInputFormat.isSplitable(DeprecatedLzoTextInputFormat.java:101) ~[hadoop-lzo.jar:na]
	... 19 common frames omitted
2015-03-05T22:13:35.620-0800	 INFO	query-execution-1	com.facebook.presto.event.query.QueryMonitor	TIMELINE: Query 20150306_061333_00006_y9z6v :: elapsed 1811.00ms :: planning 273.56ms :: scheduling 1537.00ms :: running 0.00ms :: finishing 1537.00ms :: begin 2015-03-05T22:13:33.760-08:00 :: end 2015-03-05T22:13:35.571-08:00
```

It seem like some jar reflect with others after copy hadoop-lzo.jar to plugin. but i have no idea solute this. could u help me?

by the way, i use aws emr enviorment, which using JAVA 7, Hadoop 2.4.0, Hive 0.13.1

**Comment by electrum** [comment]
This will be fixed soon with the new native LZO implementation in https://github.com/airlift/aircompressor

**Comment by yuananf** [comment]
Great! Looking forward to it.

**Comment by mombergm** [comment]
@electrum Do you know in which future release aircompressor would be?

**Comment by xcrossed** [comment]
the lastest version 0.122 
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:250)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.hadoop.mapred.DeprecatedLzoTextInputFormat.isSplitable(DeprecatedLzoTextInputFormat.java:103)
	... 17 more

**Comment by xcrossed** [comment]
Hello @electrum  , have you fixed this problem? Anyone knows how to fix it?


Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:250)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.hadoop.mapred.DeprecatedLzoTextInputFormat.isSplitable(DeprecatedLzoTextInputFormat.java:103)
	... 17 more

**Comment by xcrossed** [comment]
@electrum  Hello, have you fixed this problem? Anyone knows how to fix it?

Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:253)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:233)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:69)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:167)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
	at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$14(ResumableTasks.java:33)
	at com.facebook.presto.hive.util.ResumableTasks$$Lambda$487/1333014523.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.executeOrMerge(BoundedExecutor.java:69)
	at io.airlift.concurrent.BoundedExecutor.access$000(BoundedExecutor.java:28)
	at io.airlift.concurrent.BoundedExecutor$1.run(BoundedExecutor.java:40)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.facebook.presto.hive.HiveUtil.isSplittable(HiveUtil.java:250)
	... 12 more
Caused by: java.lang.NullPointerException
	at com.hadoop.mapred.DeprecatedLzoTextInputFormat.isSplitable(DeprecatedLzoTextInputFormat.java:103)
	... 17 more

**Comment by xcrossed** [comment]
https://groups.google.com/forum/#!topic/presto-users/_Fe9YrZ3gYg can fix it

**Comment by xmly** [comment]
@electrum @mombergm    Have the aircompressor being used in the presto? 

Thanks

**Comment by electrum** [comment]
@xmly Are you interested in text files? I filed a new issue for that: https://github.com/prestodb/presto/issues/7348

Please comment on the new issue with specific use cases, examples of how to create the tables in Hive, etc.

I'm going to close this issue since issue since we now have our own LZO implementation and will use that instead.

**Comment by electrum** [comment]
If you're interested in LZO for SequenceFile, please file a new issue for that, as that's a completely different implementation.
