### ISSUE TITLE
Allow empty password in presto-jdbc

### ISSUE THREAD

**Issue by xerial** [prestodb/presto#8566]
JDBC password should be allowed to be empty:
https://github.com/prestodb/presto/blob/eff7dcc2e2b88d60c23479a5e99c8ae582581f59/presto-jdbc/src/main/java/com/facebook/presto/jdbc/ConnectionProperties.java#L108

But this code wrongly forces password presence check:
https://github.com/prestodb/presto/blob/eff7dcc2e2b88d60c23479a5e99c8ae582581f59/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDriverUri.java#L135

Background:
presto-jdbc before 0.180 has ignored JDBC password property, so we are using username property for authentication (e.g., by embedding some API keys), so we have been using presto-jdbc with SSL + username (api key) + empty password.

**Comment by xerial** [comment]
The code itself seems allowing empty password. I'll check the actual behavior in detail.

**Comment by xerial** [comment]
I confirmed this problem is reproducible: 
{code}
java.sql.SQLException: Connection property 'password' value is empty
	at com.facebook.presto.jdbc.AbstractConnectionProperty.getValue(AbstractConnectionProperty.java:104)
	at com.facebook.presto.jdbc.AbstractConnectionProperty.validate(AbstractConnectionProperty.java:123)
	at com.facebook.presto.jdbc.PrestoDriverUri.validateConnectionProperties(PrestoDriverUri.java:297)
	at com.facebook.presto.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:89)
	at com.facebook.presto.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:79)
	at com.facebook.presto.jdbc.PrestoDriver.connect(PrestoDriver.java:86)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at Sample.main(Sample.java:12)
{code}

The source code is here: https://gist.github.com/xerial/de55b08607df73fcec36867c2408ae09#file-sample-java

**Comment by electrum** [comment]
Thanks, I see the problem here. We don't allow you to specify a property as empty, even if it's optional. For example, you can't say `?SSL=&user=test`, even though `SSL` is optional. But, `password` is special because `DriverManager` sets it automatically. We can probably just skip the special check for empty and allow the normal validation to handle it.
