### ISSUE TITLE
Single node cluster cannot gracefully shutdown

### ISSUE THREAD

**Issue by andrewryder** [prestodb/presto#8636]
When attempting to gracefully shutdown a node (as we wanted to implement this feature in production), I was testing against one of our single-node staging clusters. What resulted was the query being killed before completion.

This seems to be a result of the "No nodes available" exception to be bubbled up into the scheduler loop.

Is this the expected functionality on a single node cluster (Since there are technically no active nodes) or is the expectation that any and all queries currently running should complete first?

This likely isn't a huge problem for any production environment, but might mislead folks attempting to test the functionality of gracefully shutting down like myself.

**Comment by nezihyigitbasi** [comment]
When you try to shutdown the coordinator in a single-node cluster the graceful shutdown logic should throw an exception saying `Cannot shutdown coordinator` (see [this](https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/server/GracefulShutdownHandler.java#L77-L79)), so basically your `PUT` request to `/v1/info` should fail. 

If that's different than what you observe please provide stack traces.

**Comment by andrewryder** [comment]
Sorry, I should clarify;

It is a single *worker* node, separate from the coordinator. This is the stack trace that occurs (I believe this is from 0.164 but testing on the latest gives the same/similar stacktrace):
```
[65541] Query failed (#20170728_202010_00001_tmv6h): No nodes available to run query
           java.lang.RuntimeException: com.facebook.presto.spi.PrestoException: No nodes available to run query
           at com.facebook.presto.execution.scheduler.SimpleNodeSelector.computeAssignments(SimpleNodeSelector.java:123)
           at com.facebook.presto.execution.scheduler.DynamicSplitPlacementPolicy.computeAssignments(DynamicSplitPlacementPolicy.java:41)
           at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:97)
           at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:353)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
           at java.util.concurrent.FutureTask.run(FutureTask.java:266)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
           at java.lang.Thread.run(Thread.java:748)
```

Prior to the query finishing the only worker node is marked as `SHUTTING_DOWN` so no splits can be scheduled on any nodes at this point which kills queries in an ungraceful manner.

**Comment by nezihyigitbasi** [comment]
I guess what's happening is the worker goes to the `shutting down` state and after that point nothing can run as there are no worker nodes available in the cluster, which is expected. What graceful shutdown guarantees is that if there are any running queries on a particular worker then the shutdown handler waits for those queries to finish. If there is nothing running the worker will be put to the shutting down state and will not receive further tasks.

**Comment by nezihyigitbasi** [comment]
@andrewryder please re-open if you have any other issues.
