### ISSUE TITLE
TestResourceGroupIntegration::testMemoryFraction is still flaky

### ISSUE THREAD

**Issue by flakycov** [prestodb/presto#8666]
`TestResourceGroupIntegration::testMemoryFraction` failed for us on commit `ec3ddb7`, but did not fail on the [corresponding run on Travis](https://travis-ci.org/prestodb/presto/jobs/255122621). Issue #6369 previously fixed some flakiness in this test, but it seems that it is now flaky for a different reason: the `Address already in use` error mentioned in #8493.

```
Tests run: 1410, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,566.825 sec <<< FAILURE! - in TestSuite
testMemoryFraction(com.facebook.presto.execution.resourceGroups.TestResourceGroupIntegration)  Time elapsed: 8.604 sec  <<< FAILURE!
com.google.inject.CreationException: 
Unable to create injector, see the following errors:

1) Error notifying InjectionListener io.airlift.bootstrap.LifeCycleModule$1$$Lambda$133/438151297@48ba9324 of io.airlift.http.server.testing.TestingHttpServer.
 Reason: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at io.airlift.http.server.testing.TestingHttpServerModule.configure(TestingHttpServerModule.java:58)
  while locating io.airlift.http.server.testing.TestingHttpServer
  while locating io.airlift.http.server.HttpServer
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.airlift.bootstrap.LifeCycleModule$1.lambda$hear$0(LifeCycleModule.java:64)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:115)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.testing.TestingPrestoServer.<init>(TestingPrestoServer.java:238)
	at com.facebook.presto.tests.DistributedQueryRunner.createTestingPrestoServer(DistributedQueryRunner.java:183)
	at com.facebook.presto.tests.DistributedQueryRunner.<init>(DistributedQueryRunner.java:112)
	at com.facebook.presto.tests.tpch.TpchQueryRunner.createQueryRunnerWithoutCatalogs(TpchQueryRunner.java:68)
	at com.facebook.presto.tests.tpch.TpchQueryRunner.createQueryRunner(TpchQueryRunner.java:47)
	at com.facebook.presto.execution.resourceGroups.TestResourceGroupIntegration.testMemoryFraction(TestResourceGroupIntegration.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor906.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.airlift.bootstrap.LifeCycleManager.startInstance(LifeCycleManager.java:171)
	at io.airlift.bootstrap.LifeCycleManager.addInstance(LifeCycleManager.java:157)
	at io.airlift.bootstrap.LifeCycleModule$1.lambda$hear$0(LifeCycleModule.java:61)
	... 37 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:390)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.airlift.http.server.HttpServer.start(HttpServer.java:383)
	... 43 more
```

**Comment by findepi** [comment]
@flakycov is `TestResourceGroupIntegration::testMemoryFraction` still flaky?

**Comment by flakycov** [comment]
@findepi We haven't seen it flake since this report.
