### ISSUE TITLE
Does Presto support MySQL+SSL?

### ISSUE THREAD

**Issue by grepwood** [prestodb/presto#8687]
Hello,

I have Presto connecting to several databases over SSH tunnels, but would like to switch it all to SSL. Maintaining 20+ SSH tunnels on all nodes is quite painful.

I've tried to run Presto with `-Djavax.net.ssl.trustStore="/path/to/truststore.jks" -Djavax.net.ssl.trustStorePassword="actualpassword"` where we keep an intermediate CA, and a root CA used to sign the certificate for one MySQL database that we've decided to try out first.

First I tried to edit ~/.my.cnf to see if the C CLI client for MySQL will work.
```
MySQL [(none)]> \s
--------------
mysql  Ver 15.1 Distrib 5.5.53-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Connection id:          1525991
Current database:
Current user:           foobar@mysterious_host
SSL:                    Cipher in use is DHE-RSA-AES256-SHA
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MySQL
Server version:         5.6.33-1~dotdeb+7.1 (Debian)
Protocol version:       10
Connection:             important_intranet_host via TCP/IP
Server characterset:    latin1
Db     characterset:    latin1
Client characterset:    utf8
Conn.  characterset:    utf8
```
So it works.

Unfortunately, Presto crashes when it has the following parameters in the database connector file:
```
connector.name=mysql
connection-url=jdbc:mysql://important_intranet_host:3306?useSSL=true&requireSSL=true&verifyServerCertificate=false
connection-user=foobar
connection-password=foobarspassword
```

The crash log:
```
4 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.IllegalStateException: no valid keystore
  at io.airlift.http.client.HttpClientModule.configure(HttpClientModule.java:91) (via modules: io.airlift.discovery.client.DiscoveryModule -> io.airlift.http.client.HttpClientModule)
...
Caused by: java.lang.IllegalStateException: no valid keystore
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48)
...
2) Error in custom provider, java.lang.IllegalStateException: no valid keystore
io.airlift.discovery.client.DiscoveryModule -> io.airlift.http.client.HttpClientModule)
...
Caused by: java.lang.IllegalStateException: no valid keystore
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48)
...
3) Error in custom provider, java.lang.IllegalStateException: no valid keystore
  at io.airlift.http.client.HttpClientModule.configure(HttpClientModule.java:91) (via modules: io.airlift.discovery.client.DiscoveryModule -> io.airlift.http.client.HttpClientModule)
...
Caused by: java.lang.IllegalStateException: no valid keystore
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48)
...
4) Error in custom provider, java.lang.IllegalStateException: no valid keystore
  at io.airlift.http.client.HttpClientModule.configure(HttpClientModule.java:91) (via modules: io.airlift.discovery.client.DiscoveryModule -> io.airlift.http.client.HttpClientModule)
...
Caused by: java.lang.IllegalStateException: no valid keystore
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:48)
```
Funny, 4 errors, all the same. And the keystore file is intact and I can interact with it with keytool just fine. What could have gone wrong?

**Comment by electrum** [comment]
Instead of setting JVM level system properties (which isn't recommended for Presto), try setting as connection properties:

```
&trustCertificateKeyStoreUrl=/path/to/truststore.jks&trustCertificateKeyStorePassword=password
```

https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html

**Comment by grepwood** [comment]
Hello,

Did this, getting
```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: /path/to/truststore.jks does not appear to be a valid URL.
        at sun.reflect.GeneratedConstructorAccessor164.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
        at com.mysql.jdbc.ExportControlled.getSSLSocketFactoryDefaultOrConfigured(ExportControlled.java:299)
        at com.mysql.jdbc.ExportControlled.transformSocketToSSLSocket(ExportControlled.java:85)
        at com.mysql.jdbc.MysqlIO.negotiateSSLConnection(MysqlIO.java:4901)
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1226)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2205)
        at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2056)
        ... 30 more
```

I'm `file`ing the actual path to the truststore, and it comes up as
```
/path/to/truststore.jks: Java KeyStore
```

**Comment by grepwood** [comment]
Alright, for future generations of users, use `trustCertificateKeyStoreUrl=file:///path/to/truststore.jks`
