### ISSUE TITLE
Presto parquet read path fails when map columns have null values.

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [prestodb/presto#8709]
Presto parquet read path fails to read any parquet tables that has null values for the column with map types. This is broken by this change https://github.com/prestodb/presto/pull/7590/files so all releases since the patch has been merged in should be affected. The code reads keyblocks and valueblocks in ParquetReader's readMap method and if the map is null , both keyblock and valueblock will have a null value for that position and the mapisNull array is incorrectly set to an array indicating no map will ever be null. The read fails with 
``` java Caused by: java.lang.IllegalArgumentException: map keys cannot be null
	at com.facebook.presto.spi.block.MapBlockBuilder.buildHashTable(MapBlockBuilder.java:342)
	at com.facebook.presto.spi.block.MapBlock.fromKeyValueBlock(MapBlock.java:202)
	at com.facebook.presto.spi.type.MapType.createBlockFromKeyValue(MapType.java:253)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:215)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:184)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:201)```

**Comment by nezihyigitbasi** [comment]
For other users hitting this issue, you can disable the optimized Parquet reader with the `parquet_optimized_reader_enabled` session parameter to hopefully workaround this issue.

@Parth-Brahmbhatt since you have an understanding of the problem, can you please submit a patch? Otherwise, it would be nice to have a small test file or a test case to repro the issue so that someone can take a look.

**Comment by Parth-Brahmbhatt** [comment]
I am working on the patch, disabling the parquet_optimized_reader_enabled does work.

**Comment by smith-m** [comment]
@Parth-Brahmbhatt  I have observed this issue as well. Do you have a WIP branch or anything I can help with.

**Comment by Parth-Brahmbhatt** [comment]
Here is the PR https://github.com/prestodb/presto/pull/9110
