### ISSUE TITLE
Planning failure with GROUPING and expression that requires implicit coercions

### ISSUE THREAD

**Issue by martint** [prestodb/presto#8738]
```sql
SELECT
    GROUPING(k),
    SUM(v) + 1.0
FROM (VALUES (1,1)) AS t(k,v)
GROUP BY k
```

fails with:

```
com.facebook.presto.sql.analyzer.SemanticException: Column 'k' cannot be resolved
	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
	at com.facebook.presto.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:104)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:371)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:51)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitGroupingOperation(ExpressionAnalyzer.java:1130)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitGroupingOperation(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.GroupingOperation.accept(GroupingOperation.java:49)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1447)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1400)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1366)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1354)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.getExpressionTypes(ExpressionAnalyzer.java:1342)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:118)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:109)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:109)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:109)
	at com.facebook.presto.sql.planner.sanity.TypeValidator$Visitor.visitProject(TypeValidator.java:60)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:26)
	at com.facebook.presto.sql.planner.SimplePlanVisitor.visitPlan(SimplePlanVisitor.java:19)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:49)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.sanity.TypeValidator.validate(TypeValidator.java:57)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.lambda$validateIntermediatePlan$1(PlanSanityChecker.java:59)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.facebook.presto.sql.planner.sanity.PlanSanityChecker.validateIntermediatePlan(PlanSanityChecker.java:59)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:129)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:122)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:358)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

If `1.0` is replaced with `1`, the query succeeds. I believe this is due to some issue with implicit coercions.

**Comment by martint** [comment]
It appears GROUPING(k) is not being rewritten during the initial planning when the `1.0` is in the aggregation expression.
