### ISSUE TITLE
Flaky tests during Maven release on mac

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8769]
Follow-up issue #8788:
```
    Tests run: 749, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 465.517 sec <<< FAILURE! - in TestSuite
    testNonEmptyTable(com.facebook.presto.cassandra.TestCassandraTokenSplitManager)  Time elapsed: 0.309 sec  <<< FAILURE!
    java.lang.AssertionError: expected [10] but found [1]
        at com.facebook.presto.cassandra.TestCassandraTokenSplitManager.testNonEmptyTable(TestCassandraTokenSplitManager.java:69)
```

Line 172 in TestNodeScheduler is not blocking. This looks like casualty caused by other tests:
```
    Tests run: 3345, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 231.095 sec <<< FAILURE! - in TestSuite
    testTopologyAwareScheduling(com.facebook.presto.execution.TestNodeScheduler)  Time elapsed: 6.04 sec  <<< FAILURE!
    org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.TestNodeScheduler.testTopologyAwareScheduling() didn't finish within the time-out 60000
        at com.facebook.presto.execution.TestNodeScheduler.testTopologyAwareScheduling(TestNodeScheduler.java:172)
```

Follow-up issue #8787:
```
    Tests run: 2078, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,069.576 sec <<< FAILURE! - in TestSuite
    testAtTimeZone(com.facebook.presto.tests.TestDistributedSpilledQueries)  Time elapsed: 0.013 sec  <<< FAILURE!
    java.lang.AssertionError: Execution of 'actual' query failed: SELECT TIMESTAMP '2012-10-31 01:00' AT TIME ZONE INTERVAL '07:09' hour to minute
    Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
    Caused by: java.net.SocketException: Bad file descriptor (Write failed)
```

Follow-up issue #8776:
```
java.lang.AssertionError: unknown nulls fraction for t_int expected [false] but found [true]
java.lang.AssertionError: unknown nulls fraction for t_smallint expected [false] but found [true]
```

Fixed #8778:
```
    Tests run: 2078, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,445.64 sec <<< FAILURE! - in TestSuite
    testQueryMemoryLimit(com.facebook.presto.memory.TestMemoryManager)  Time elapsed: 359.957 sec  <<< FAILURE!
    org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.memory.TestMemoryManager.testQueryMemoryLimit() didn't finish within the time-out 240000
        at com.facebook.presto.memory.TestMemoryManager.testQueryMemoryLimit(TestMemoryManager.java:305)
```

Fixed #8777:
```
    Tests run: 2078, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,446.256 sec <<< FAILURE! - in TestSuite
    testInsufficientWorkerNodes(com.facebook.presto.tests.TestMinWorkerRequirement)  Time elapsed: 112.918 sec  <<< FAILURE!
    java.io.UncheckedIOException: java.net.SocketTimeoutException: timeout
        at com.facebook.presto.tests.TestMinWorkerRequirement.testInsufficientWorkerNodes(TestMinWorkerRequirement.java:33)
    Caused by: java.net.SocketTimeoutException: timeout
        at com.facebook.presto.tests.TestMinWorkerRequirement.testInsufficientWorkerNodes(TestMinWorkerRequirement.java:33)
    Caused by: java.net.SocketTimeoutException: Read timed out
        at com.facebook.presto.tests.TestMinWorkerRequirement.testInsufficientWorkerNodes(TestMinWorkerRequirement.java:33)
```

Fixed #8779:
```
Tests run: 2078, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,458.562 sec <<< FAILURE! - in TestSuite
    testAggregationWithLimit(com.facebook.presto.tests.TestTpchDistributedQueries)  Time elapsed: 0.115 sec  <<< FAILURE!
    java.lang.AssertionError: 
    expected row missing: [467, 535205.0]
    All 1000 rows:
        [1, 1428873.6100000003]
        [2, 1156504.9200000002]
        [4, 4134567.3900000006]
        [5, 1084042.7399999998]
        [7, 3922020.98]
        [8, 2311598.7500000005]
        [10, 3865098.1799999997]
        [11, 1233486.5300000003]
        [13, 2292834.57]
        [14, 1787359.08]
        [16, 2170436.43]
        [17, 2016998.76]
        [19, 3686492.93]
        [20, 1230350.63]
        [22, 3130582.1899999995]
        [23, 1673040.1800000002]
        [25, 2845869.53]
        [26, 418511.97]
        [28, 3075314.4600000004]
        [29, 1935593.0900000003]
        [31, 2114517.56]
        [32, 914059.5599999999]
        [34, 3945438.7099999995]
        [35, 2113194.0700000003]
        [37, 2428169.69]
        [38, 1336731.1199999999]
        [40, 2887931.6000000006]
        [41, 1871334.66]
        [43, 3758886.2100000004]
        [44, 1799024.0399999998]
        [46, 2179304.63]
        [47, 518953.38000000006]
        [49, 3415140.2299999986]
        [50, 1693672.0900000003]
        [52, 3307614.6199999996]
        [53, 1790425.06]
        [55, 1998414.2099999997]
        [56, 1967546.44]
        [58, 2258160.75]
        [59, 1454536.43]
        [61, 3497594.0399999996]
        [62, 1730591.94]
        [64, 1517611.9300000002]
        [65, 1863488.8900000001]
        [67, 2620093.9000000004]
        [68, 2318085.52]
        [70, 2186547.8700000006]
        [71, 1580442.3899999997]
        [73, 4638819.21]
        [74, 1364900.85]
        [76, 1255844.09]
        [77, 713381.2799999999]
        [79, 4412540.44]
        [80, 2116340.11]
        [82, 1850376.42]
        [83, 967203.7999999999]
        [85, 2706695.68]
        [86, 1753321.1600000001]
        [88, 3444935.0500000007]
        [89, 975893.56]
        [91, 2603316.4799999995]
        [92, 632422.34]
        [94, 3678708.0900000012]
        [95, 865644.4099999999]
        [97, 2721768.0499999993]
        [98, 1827484.1599999997]
        [100, 2690837.75]
        [101, 2120043.91]
        [103, 3139428.34]
        [104, 1269470.76]
        [106, 1850889.8900000001]
        [107, 1817530.94]
        [109, 3118285.41]
        [110, 1114818.38]
        [112, 3116175.3899999997]
        [113, 1551366.0099999998]
        [115, 2186777.32]
        [116, 1219325.43]
        [118, 1785726.0600000003]
        [119, 460544.22]
        [121, 3801574.769999999]
        [122, 799409.05]
        [124, 1829717.98]
        [125, 1002422.96]
        [127, 2223113.65]
        [128, 2283722.63]
        [130, 2593419.3]
        [131, 863828.64]
        [133, 2270483.1500000004]
        [134, 1665740.58]
        [136, 3279162.63]
        [137, 1292308.5900000003]
        [139, 2900558.3200000003]
        [140, 1632599.52]
        [142, 2325660.16]
        [143, 1080022.83]
        [145, 3002676.11]
        [146, 2016124.03]
        [148, 1771330.96]
        [149, 1860648.57]
    Expected subset 10 rows:
        [892, 2461282.16]
        [1339, 2896845.7399999998]
        [394, 2513568.7600000002]
        [802, 2505998.3299999996]
        [467, 535205.0]
        [1291, 3132551.14]
        [1387, 2753300.1399999997]
        [1156, 3322812.6399999997]
        [34, 3945438.709999999]
        [1013, 2244059.98]
```

**Comment by haozhun** [comment]
Closing this now that release 0.183 is out. A new task will be filed to track pending issues.
