### ISSUE TITLE
Flaky Test in TestDistributedSpilledQueries

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8787]
```
    Tests run: 2078, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,069.576 sec <<< FAILURE! - in TestSuite
    testAtTimeZone(com.facebook.presto.tests.TestDistributedSpilledQueries)  Time elapsed: 0.013 sec  <<< FAILURE!
    java.lang.AssertionError: Execution of 'actual' query failed: SELECT TIMESTAMP '2012-10-31 01:00' AT TIME ZONE INTERVAL '07:09' hour to minute
    Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
    Caused by: java.net.SocketException: Bad file descriptor (Write failed)

**Comment by haozhun** [comment]
@ArturGajowy @losipiuk These tests were introduced recently in 38271f3c98f642c7deca534be1846ba924a67ae5. Can you take a look at this issue? We encountered this failure multiple times during our release process for 0.183. We hope that this can be addressed in a week so that release 0.184 will be easier.

In fact, with #8769 partially fixed, this is now by far the most likely cause for build failures on mac.

**Comment by losipiuk** [comment]
@haozhun  So far I was not able to reproduce that. 
Could you share what exact command you were using for running tests. And on what hardware?

**Comment by raghavsethi** [comment]
We were running mvn release:prepare on a Macbook Pro, and it was not hard to reproduce.

**Comment by raghavsethi** [comment]
@losipiuk @ArturGajowy ping

**Comment by losipiuk** [comment]
Sorry about that. I would love to help here. I just run all the tests many times and I never had any error in `TestDistributedSpilledQueries`.

Is that only happening for `testAtTimeZone` or different tests fail depending on the run?
Could you paste whole stack traces of exceptions (those should be in surefire-log in `presto-test/target/surefire-reports/emailable-report.html`?

I will give it a few more runs but without repro I do not have idea how to tackle that (other than disable the test).
I am running tests on not very recent `MacBook Pro (Retina, 13-inch, Early 2015)` with 16GB of RAM.

**Comment by haozhun** [comment]
@raghavsethi Please post the detailed stack trace when you hit this the next time. I don't think I have them right now.

**Comment by raghavsethi** [comment]
```
testAtTimeZone
java.lang.AssertionError: Execution of 'actual' query failed: SELECT TIMESTAMP '2012-10-31 01:00' AT TIME ZONE INTERVAL '07:09' hour to minute
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:87)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:123)
	at com.facebook.presto.tests.AbstractTestQueries.testAtTimeZone(AbstractTestQueries.java:5788)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:148)
	at com.facebook.presto.client.StatementClient.<init>(StatementClient.java:118)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:82)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:347)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:84)
	... 15 more
Caused by: java.net.SocketException: Bad file descriptor (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
	at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:130)
	... 19 more
... Removed 11 stack frames
```
