### ISSUE TITLE
AccumuloQueryRunner doesn't work on IPv6-only Linux

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8789]
The MiniAccumuloCluster doesn't work on IPv6-only hosts. (The host has IPv4 stack, but only for 127.0.0.1. The host only has IPv6 external facing address.)

Presto runs accumulo 1.6.2, which supposedly have a fix for some similar issue: [ACCUMULO-3340](https://issues.apache.org/jira/browse/ACCUMULO-3340)

Symptom:
* Out-of-box: hangs on attempt to connect: `Opening socket connection to server localhost/127.0.0.1:13061. Will not attempt to authenticate using SASL (unknown error)`
* Removes `::1 localhost` from /etc/hosts: same
* `-Djava.net.preferIPv6Addresses=true`: MiniAccumuloCluster fails initiation sanity check
* `-Djava.net.preferIPv4Stack=true`: works

**Comment by haozhun** [comment]
@adamjshook Do you mind taking a look?

**Comment by electrum** [comment]
For context, this is an actual problem for us since most of our severs including development servers  are IPv6 only: https://code.facebook.com/posts/635645183305089/legacy-support-on-ipv6-only-infra/

**Comment by adamjshook** [comment]
I can start by upgrading Accumulo to the latest line and adding the JVM parameter.  I should have time to look at this on Tuesday.

**Comment by raghavsethi** [comment]
@adamjshook ping

**Comment by electrum** [comment]
I just tried again after merging the 1.7.3 update. The last message *"Failed to open transport ..."* repeats forever with a random port number each time. Note that I replaced the actual hostname of the machine with `dev.example.com`.
```
2017-09-07 22:29:56 INFO Initiating client connection, connectString=localhost:33623 sessionTimeout=30000 watcher=org.apache.accumulo.fate.zookeeper.ZooSession$ZooWatcher@436a4e4b
2017-09-07 22:29:56 INFO Opening socket connection to server localhost/0:0:0:0:0:0:0:1:33623. Will not attempt to authenticate using SASL (unknown error)
2017-09-07 22:29:56 WARNING Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

2017-09-07 22:29:56 INFO Opening socket connection to server localhost/127.0.0.1:33623. Will not attempt to authenticate using SASL (unknown error)
2017-09-07 22:29:56 INFO Socket connection established to localhost/127.0.0.1:33623, initiating session
2017-09-07 22:29:56 INFO Session establishment complete on server localhost/127.0.0.1:33623, sessionid = 0x15e5d3ad9900004, negotiated timeout = 30000
2017-09-07 22:29:56 WARNING Failed to open transport to dev.example.com:34185
2017-09-07 22:29:56 WARNING Failed to open transport to dev.example.com:48979
2017-09-07 22:29:56 WARNING Failed to find an available server in the list of servers: [dev.example.com:48979 (120000), dev.example.com:34185 (120000)]
2017-09-07 22:29:56 WARNING Failed to open transport to dev.example.com:48979
2017-09-07 22:29:56 WARNING Failed to open transport to dev.example.com:34185
2017-09-07 22:29:56 WARNING Failed to open transport to dev.example.com:48979
