### ISSUE TITLE
Planning failure when count(*) over VALUES with aggregation

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#8828]
Queries
```
select count(*) from (values 1) t(a) group by a;
select a, count(*) from (values 1) t(a) group by a;
select count(*) from (values 1) t(a) group by a+1;
```
all fail in `PruneCountAggregationOverScalar` with
```
java.lang.IllegalArgumentException: Expected row to have 2 values, but row has 1 values
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:263)
	at com.facebook.presto.sql.planner.plan.ValuesNode.<init>(ValuesNode.java:46)
	at com.facebook.presto.sql.planner.iterative.rule.PruneCountAggregationOverScalar.apply(PruneCountAggregationOverScalar.java:70)
	at com.facebook.presto.sql.planner.iterative.rule.PruneCountAggregationOverScalar.apply(PruneCountAggregationOverScalar.java:39)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.transform(IterativeOptimizer.java:157)
	at com.facebook.presto.sql.planner.iterative.IterativeOptimizer.exploreNode(IterativeOptimizer.java:130)
```

**Comment by kokosing** [comment]
See: https://github.com/prestodb/presto/pull/8829

**Comment by kokosing** [comment]
Fixed with: https://github.com/prestodb/presto/commit/e759a4afca492521a05054a90923ecbfbe3a3155
