### ISSUE TITLE
Memory Connector. Support create/drop views

### ISSUE THREAD

**Issue by kwent** [prestodb/presto#8834]
Hi,

Any reasons why connector memory does not support CREATE VIEW and DROP VIEW ?

Having this message when attempting to do it.

Input:
```sql
CREATE OR REPLACE VIEW my_view AS
SELECT users.email
FROM users;
```

Output:
```java
com.facebook.presto.spi.PrestoException: This connector does not support creating views
	at com.facebook.presto.spi.connector.ConnectorMetadata.createView(ConnectorMetadata.java:329)
	at com.facebook.presto.metadata.MetadataManager.createView(MetadataManager.java:786)
	at com.facebook.presto.execution.CreateViewTask.execute(CreateViewTask.java:92)
	at com.facebook.presto.execution.CreateViewTask.execute(CreateViewTask.java:44)
	at com.facebook.presto.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:118)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kokosing** [comment]
It is not a design decision.  It is just not yet implemented. We have not needed this so far. Any pull request is welcome.

**Comment by aramesh117** [comment]
I'll try working on this.

**Comment by kwent** [comment]
@aramesh117 Would be amazing. My java is very rusty 🤣

**Comment by kwent** [comment]
Same limitations with a `DELETE` statement

```java
com.facebook.presto.spi.PrestoException: This connector does not support updates or deletes
	at com.facebook.presto.spi.connector.ConnectorMetadata.getUpdateRowIdColumnHandle(ConnectorMetadata.java:303)
	at com.facebook.presto.metadata.MetadataManager.getUpdateRowIdColumnHandle(MetadataManager.java:658)
	at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:201)
	at com.facebook.presto.sql.planner.LogicalPlanner.createDeletePlan(LogicalPlanner.java:344)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:172)
	at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:156)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:127)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:122)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:358)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by aramesh117** [comment]
@kwent DELETE is a much harder feature to support according to @electrum. Can you file a separate PR for DELETE? Thank you!

**Comment by kwent** [comment]
Closing since https://github.com/prestodb/presto/pull/8858 is done ! Thanks
