### ISSUE TITLE
"TextInputFormat" error when select table from external tables in Hive

### ISSUE THREAD

**Issue by Lunatictwo** [prestodb/presto#8840]
Hi everyone,
    I'm using presto-server-0.183, my Hadoop version is hadoop-2.6.4 and Hive version is hive-2.1.
    When I execute query in presto-cli, I got no error with ORC table except external tables. There was the error log:
`   presto:default> select * from sms_123 limit 10;`             
`Query 20170825_104145_00010_8qgyk failed: Unable to create input format org.apache.hadoop.mapred.TextInputFormat`
and table sms_123 was an external table.
Does anyone knows how to fix it?

**Comment by Lunatictwo** [comment]
@cawallin @kokosing Could anyone help?

**Comment by kokosing** [comment]
Do you have any stacktrace from Presto server? It can be accessed through webui. Make sure that jars which provides `TextInputFormat` are in hive lib directory (classpath).

**Comment by Lunatictwo** [comment]
@kokosing see #7804 and we meet the same error. I add all the hadoop*.jar into presto-server/lib, including hadoop-mapreduce-client-core-2.6.4.jar that provides TextInputFormat.

**Comment by kokosing** [comment]
IMO `hadoop-mapreduce-client-core-2.6.4.jar` should be placed in hive plugin (connector) jars directory. All the connector classes are loaded in isolated classloader. Can you please check that?

**Comment by Lunatictwo** [comment]
@kokosing  I add `hadoop-mapreduce-client-core-2.6.4.jar` into /presto-server-0.183/plugin/hive-hadoop2, but I got the same error, then I add it into  /presto-server-0.183/plugin/hive-hadoop2/jar,same error again. Could you please describe clearly : What's the correct path to add the jar files?

**Comment by kokosing** [comment]
If you have in your hive.properties something like: 
```
connector.name=hive-hadoop2
hive.metastore.uri=thrift://localhost:9083
```

Then you need to put all the dependency jars for your hive Presto catalog, into `plugin/hive-hadoop2` file system directory on all the nodes.

**Comment by Lunatictwo** [comment]
@kokosing  I have only one presto node for test, I did it but still errors. Thanks for your patience and I will try it next version.

**Comment by mayundudu** [comment]
@Lunatictwo, Have you solved the problem yet?  I had the same problem.

**Comment by Lunatictwo** [comment]
@mayundudu ,Unfortunately,Not yet. Could you please post your error stackcrace?

**Comment by mayundudu** [comment]
I solved it yesterday,  but I don't know why.  And my presto version is   [0.175.tar.gz]
My presto  cluster has five nodes, node1 is Master Node，The other four nodes is worker.
in every node's etc/catalog  hive.properties    ,  as follows:
connector.name=hive-hadoop2
hive.metastore.uri=thrift://node1:9083
hive.compression-codec=NONE
hive.allow-drop-table=false
hive.allow-rename-table=false
hive.allow-add-column=false
hive.allow-rename-column=false
so, you can try to delete "hive.config.resources=.........".   I can already query  in presto cli ,but I don't why.

**Comment by mayundudu** [comment]
@Lunatictwo , My question is the same as yours, I had solved it,You can also try my way.

**Comment by Lunatictwo** [comment]
@mayundudu ,thank you for your response but when I remove 'hive.config.resources=' ,it looks like presto couldn't find hive metastore and I got the error like this: `Query 20170913_072057_00003_d6pxg failed: java.net.UnknownHostException: masters`
and I only have one presto node for test. 
Could you please post your /etc/config.properties and /etc/node.properties files?

**Comment by mayundudu** [comment]
@Lunatictwo     my presto is following :    
config.properties:
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=9500
query.max-memory=50GB
query.max-memory-per-node=15GB
discovery-server.enabled=true
discovery.uri=http://node1:9500

node.properties:
node.environment=production1
node.id=node1
node.data-dir=/app/presto/data

cat  /etc/hosts
192.168.7.103  node1
./presto-cli-0.175-executable.jar  --server  192.168.7.103:9500 --catalog hive  --schema test
or  
./presto-cli-0.175-executable.jar  --server  node1:9500 --catalog hive  --schema test

so , I guess your hosts file is not configured properly

**Comment by Lunatictwo** [comment]
@mayundudu thanks. I found out where is wrong, my hive/hdfs-site.xml file is an old version and it's not been used anymore, I change it into current configuration and nothing was wrong. Many thanks but I still don't understand why if I remove hive.config.resources  then I could use it. May be when you configure the hive.metastore.uri, presto will find hive configuration file automatically,I can't find out other reason.

**Comment by bwang398** [comment]
@kokosing 

presto:default> select * from redods.ods_mongo_35001_db_prod_30001_brand limit 3;
Query 20170922_024506_00003_rk4mu failed: Unable to create input format com.mongodb.hadoop.mapred.BSONFileInputFormat
com.facebook.presto.spi.PrestoException: Unable to create input format com.mongodb.hadoop.mapred.BSONFileInputFormat
	at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:139)
	at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:117)
	at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:66)
	at com.facebook.presto.split.BufferingSplitSource.isFinished(BufferingSplitSource.java:79)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:78)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:353)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to create input format com.mongodb.hadoop.mapred.BSONFileInputFormat
	at com.facebook.presto.hive.HiveUtil.getInputFormat(HiveUtil.java:215)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:290)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:231)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:86)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:187)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
	at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$1(ResumableTasks.java:33)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	... 3 more
Caused by: java.lang.ClassNotFoundException: Class com.mongodb.hadoop.mapred.BSONFileInputFormat not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
	at com.facebook.presto.hive.HiveUtil.getInputFormatClass(HiveUtil.java:229)
	at com.facebook.presto.hive.HiveUtil.getInputFormat(HiveUtil.java:206)
	... 10 more

**Comment by manna018** [comment]
> @Lunatictwo , My question is the same as yours, I had solved it,You can also try my way.

how did you solve this??

**Comment by jojotaro123** [comment]
i use trino361,and this issue is still here:Unable to create input format org.apache.hadoop.mapred.TextInputFormat error. i dont want to delete hive.config.resources=........,is there any other solution?

**Comment by HatePigNotFat** [comment]
In my case, I connect hive using Presto and I need to manually add hadoop-lzo-xxxx.jar into TRINO_HOME/plugin/hive/ as 'ClassNotFoundException' indicated. So I guess adding corresponding jar files may solve the problem.
