### ISSUE TITLE
All usage of `trimSpacesAndTruncateToLength` are likely wrong

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#8843]
For `CHAR` values, we must do `trim(truncate(val, x))` instead `truncate(trim(val), x)`. The latter can produce values with trailing spaces, which is not valid in-memory representation for `CHAR` values in Presto.

We should have a function `truncateToLengthAndTrimSpace` instead, and move (likely) all current callers to the new function.

Reproduce with ORC SliceDirectStreamReader (#8712 will fix SliceDirectStreamReader, but not this bug in general).

```
presto:default> create table test_hjin_char with (format='orc') as select cast('a c' as char(3)) x;
CREATE TABLE: 1 row

hive> alter table test_hjin_char change x x char(2);

presto:default> select cast(x as varchar) || 'zz' from test_hjin_char;
 _col0
-------
 a zz

presto:default> select upper(x) from test_hjin_char;
Query 20170825_190517_00019_47f4s failed: Slice representing Char should not have trailing spaces
java.lang.IllegalArgumentException: Slice representing Char should not have trailing spaces
        at com.facebook.presto.spi.type.CharType.writeSlice(CharType.java:149)
        at com.facebook.presto.spi.type.CharType.writeSlice(CharType.java:142)
        at com.facebook.presto.$gen.PageProjection_10.project(Unknown Source)
        at com.facebook.presto.$gen.PageProjection_10.project(Unknown Source)
        at com.facebook.presto.operator.project.DictionaryAwarePageProjection.project(DictionaryAwarePageProjection.java:99)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:269)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:177)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:126)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:49)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:286)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by haozhun** [comment]
cc @dain 

I noticed this when reviewing #8712. #8712 will NOT fix this bug. It will only fix ORC SliceDirectStreamReader.

**Comment by haozhun** [comment]
@cawallin @kokosing, I'm glad I had some back and forth with you guys on the release notes for 2342a3b7fb9fdb92b934dfbb05ceac6213657156 recently. Otherwise, I wouldn't have been able to spot this bug.

Are you guys interested in fixing this?

**Comment by kokosing** [comment]
Sure. please leave it to us. How important is it for you (wow long can it wait)? I am asking because I would like to put it somewhere within our scum process.

**Comment by haozhun** [comment]
Sorry. I didn't notice your comment until I see the pull request. It's not urgent.
