### ISSUE TITLE
Failed to rewrite shard file for DELETE FROM

### ISSUE THREAD

**Issue by teejteej** [prestodb/presto#8888]
DELETE queries regularly fail with "Failed to rewrite shard file for ...". It doesn't matter how many times the DELETE is retried for failed ones, they always gives the same error.

Query used:
```
DELETE FROM p8d6d7be8d73d49acae79db82059131b6.users WHERE p8d6d7be8d73d49acae79db82059131b6.users.id IN('59a445f9080a3a04060bebaf','59a44646080a3a09890beca1','59a447fd080a3a09890bed79')
```

Stacktrace:

```
java.util.concurrent.CompletionException: com.facebook.presto.spi.PrestoException: Failed to rewrite shard file: /var/presto/data/var/data/storage/fa/14/fa141441-8785-4e32-ab49-5c4e7c515ba8.orc
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.presto.spi.PrestoException: Failed to rewrite shard file: /var/presto/data/var/data/storage/fa/14/fa141441-8785-4e32-ab49-5c4e7c515ba8.orc
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteFile(OrcStorageManager.java:437)
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteShard(OrcStorageManager.java:402)
	at com.facebook.presto.raptor.storage.OrcStorageManager.lambda$null$0(OrcStorageManager.java:308)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more
Caused by: java.io.EOFException: Read past end of buffer RLE byte from compressed stream Stream for column 18 kind DATA position: 5 length: 5 range: 0 offset: 5830 limit: 5830 range 0 = 0 to 5 uncompressed: 2 to 2
	at org.apache.hadoop.hive.ql.io.orc.RunLengthByteReader.readValues(RunLengthByteReader.java:46)
	at org.apache.hadoop.hive.ql.io.orc.RunLengthByteReader.next(RunLengthByteReader.java:76)
	at org.apache.hadoop.hive.ql.io.orc.BitFieldReader.skip(BitFieldReader.java:110)
	at org.apache.hadoop.hive.ql.io.orc.TreeReaderFactory$BooleanTreeReader.skipRows(TreeReaderFactory.java:227)
	at org.apache.hadoop.hive.ql.io.orc.TreeReaderFactory$StructTreeReader.skipRows(TreeReaderFactory.java:2050)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.advanceToNextRow(RecordReaderImpl.java:1028)
	at org.apache.hadoop.hive.ql.io.orc.RecordReaderImpl.seekToRow(RecordReaderImpl.java:1202)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.rewrite(OrcFileRewriter.java:110)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.rewrite(OrcFileRewriter.java:93)
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteFile(OrcStorageManager.java:434)
	... 6 more
```

Any ideas?

**Comment by electrum** [comment]
Is it always the same file? If so, it's likely the file got corrupted. We added checksums in 0.177 that can detect this.

**Comment by teejteej** [comment]
I was running on latest 0.183, but haven't been able to reproduce the error on the same server. I've lowered a few properties related to concurrency that were probably too high for the small cluster I was testing with, and migrated to MySQL for metadata (was using H20 before). So far no more issues, so I'm closing this one. I'm guessing it's probably related to not using MySQL for metadata.

**Comment by OleksiiDuzhyi** [comment]
Hi, I'm having similar issue but with different exception: 

```
java.util.concurrent.CompletionException: com.facebook.presto.spi.PrestoException: Failed to rewrite shard file: /presto/data/var/data/storage/91/5e/915eb10e-752b-4d73-a2d0-d84485708df8.orc
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.presto.spi.PrestoException: Failed to rewrite shard file: /presto/data/var/data/storage/91/5e/915eb10e-752b-4d73-a2d0-d84485708df8.orc
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteFile(OrcStorageManager.java:437)
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteShard(OrcStorageManager.java:402)
	at com.facebook.presto.raptor.storage.OrcStorageManager.lambda$null$0(OrcStorageManager.java:308)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 3 more
Caused by: java.io.IOException: Unhandled ORC object: org.apache.hadoop.hive.serde2.io.HiveDecimalWritable
	at com.facebook.presto.raptor.storage.OrcFileRewriter.uncompressedSize(OrcFileRewriter.java:180)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.uncompressedSize(OrcFileRewriter.java:146)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.rewrite(OrcFileRewriter.java:127)
	at com.facebook.presto.raptor.storage.OrcFileRewriter.rewrite(OrcFileRewriter.java:93)
	at com.facebook.presto.raptor.storage.OrcStorageManager.rewriteFile(OrcStorageManager.java:434)
	... 6 more
```

And it fails on different files every time, what could be a reason? @electrum

**Comment by electrum** [comment]
@OleksiiDuzhyi Thanks, I was able to reproduce. Please file an issue, should be easy to fix.
