### ISSUE TITLE
java.lang.ClassCastException: com.facebook.presto.spi.block.VariableWidthBlock cannot be cast to com.facebook.presto.spi.block.SingleMapBlock

### ISSUE THREAD

**Issue by wyukawa** [prestodb/presto#8903]
Hi,

I use presto 0.183 + jdk1.8.0_112 + HDP 2.5.3 + hive connector + CentOS 7.2

If I execute the following query, ClassCastException occurs.
```
select
  ...
  parse_agent(json_extract_scalar(log, '$.userAgent'))['os'] as os,
  ...
from
  ...
```
This error doesn't occur in presto 0.182

I guess that ```Improve performance of CAST(json_parse(...) AS ...).``` is related
https://prestodb.io/docs/current/release/release-0.183.html

parse_agent is the my UDF
https://github.com/wyukawa/presto-woothee/blob/master/src/main/java/woothee/ParseAgentFuntion.java

stacktrace
```
Caused by: java.lang.ClassCastException: com.facebook.presto.spi.block.VariableWidthBlock cannot be cast to com.facebook.presto.spi.block.SingleMapBlock
        at com.facebook.presto.operator.scalar.MapSubscriptOperator.subscript(MapSubscriptOperator.java:152)
        at com.facebook.presto.$gen.PageProjection_1931.project(Unknown Source)
        at com.facebook.presto.$gen.PageProjection_1931.project(Unknown Source)
        at com.facebook.presto.operator.project.DictionaryAwarePageProjection.project(DictionaryAwarePageProjection.java:99)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:239)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:159)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:125)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:48)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:288)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:335)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:240)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:612)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by highker** [comment]
You might need to fix function `parse_agent` like the way we did in #8810.
