### ISSUE TITLE
Test failures during 0.184 release

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8906]
```
Tests run: 2078, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 1,258.32 sec <<< FAILURE! - in TestSuite
testAtTimeZone(com.facebook.presto.tests.TestDistributedSpilledQueries)  Time elapsed: 0.018 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT TIMESTAMP '2012-10-31 01:00' AT TIME ZONE INTERVAL '07:09' hour to minute
Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
Caused by: java.net.SocketException: Bad file descriptor (Write failed)

testAverageAll(com.facebook.presto.tests.TestDistributedSpilledQueries)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT AVG(totalprice) FROM ORDERS
Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
Caused by: java.net.SocketException: Bad file descriptor (Write failed)

testBuildFilteredLeftJoin(com.facebook.presto.tests.TestDistributedSpilledQueries)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError: Execution of 'actual' query failed: SELECT * FROM lineitem LEFT JOIN (SELECT * FROM orders WHERE orderkey % 2 = 0) a ON lineitem.orderkey = a.orderkey
Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
Caused by: java.net.SocketException: Bad file descriptor (Write failed)
```

```
Tests run: 2078, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,259.669 sec <<< FAILURE! - in TestSuite
testBasic(com.facebook.presto.execution.resourceGroups.db.TestQueues)  Time elapsed: 68.161 sec  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method com.facebook.presto.execution.resourceGroups.db.TestQueues.testBasic() didn't finish within the time-out 60000
```

```
testAtTimeZone
java.lang.AssertionError: Execution of 'actual' query failed: SELECT TIMESTAMP '2012-10-31 01:00' AT TIME ZONE INTERVAL '07:09' hour to minute
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:87)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:123)
	at com.facebook.presto.tests.AbstractTestQueries.testAtTimeZone(AbstractTestQueries.java:5788)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.UncheckedIOException: java.net.SocketException: Bad file descriptor (Write failed)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:148)
	at com.facebook.presto.client.StatementClient.<init>(StatementClient.java:118)
	at com.facebook.presto.tests.AbstractTestingPrestoClient.execute(AbstractTestingPrestoClient.java:82)
	at com.facebook.presto.tests.DistributedQueryRunner.execute(DistributedQueryRunner.java:347)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:84)
	... 15 more
Caused by: java.net.SocketException: Bad file descriptor (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
	at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:130)
	... 19 more
... Removed 11 stack frames
```

**Comment by electrum** [comment]
Covered by #8787 and #8914
