### ISSUE TITLE
JsonExtract does not handle invalid Unicode

### ISSUE THREAD

**Issue by electrum** [prestodb/presto#8958]
```
java.lang.RuntimeException: java.io.CharConversionException: Invalid UTF-32 character 0x7b227222(above 10ffff)  at char #8, byte #35) 
	at com.google.common.base.Throwables.propagate(Throwables.java:240) 
	at com.facebook.presto.operator.scalar.JsonExtract.extract(JsonExtract.java:143) 
	at com.facebook.presto.operator.scalar.JsonFunctions.varcharJsonExtractScalar(JsonFunctions.java:398) 
	at com.facebook.presto.$gen.PageFilter_20170912_184704_30869_8bak5_2_278_332907.filter(Unknown Source) 
	at com.facebook.presto.$gen.PageFilter_20170912_184704_30869_8bak5_2_278_332907.filter(Unknown Source) 
	at com.facebook.presto.operator.project.PageProcessor.process(PageProcessor.java:85) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.processPageSource(ScanFilterAndProjectOperator.java:281) 
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:229) 
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:337) 
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241) 
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614) 
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235) 
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622) 
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163) 
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23) 
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
	at java.lang.Thread.run(Thread.java:748) 
Caused by: java.io.CharConversionException: Invalid UTF-32 character 0x7b227222(above 10ffff)  at char #8, byte #35) 
	at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:189) 
	at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:150) 
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:241) 
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2346) 
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:644) 
	at com.facebook.presto.operator.scalar.JsonExtract.extract(JsonExtract.java:131) 
	... 17 more

**Comment by prateek1306** [comment]
@electrum Is this issue specifically for 0x7b227222 or for any invalid unicode? Looks similar to #8975
