### ISSUE TITLE
Prevent coordinator serializing plan fragment when sending update to each task

### ISSUE THREAD

**Issue by highker** [prestodb/presto#8964]
`HttpRemoteTask::sendUpdate` triggers expression serializing:

```
at com.facebook.presto.sql.ExpressionFormatter.formatExpression(ExpressionFormatter.java:104)
at com.facebook.presto.sql.Serialization$ExpressionSerializer.serialize(Serialization.java:44)
at com.facebook.presto.sql.Serialization$ExpressionSerializer.serialize(Serialization.java:37)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:695)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:695)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:581)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:695)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
at com.fasterxml.jackson.datatype.jdk8.OptionalSerializer.serialize(OptionalSerializer.java:256)
at com.fasterxml.jackson.datatype.jdk8.OptionalSerializer.serialize(OptionalSerializer.java:22)
at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3672)
at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3072)
at io.airlift.json.JsonCodec.toJsonBytes(JsonCodec.java:211)
at io.airlift.http.client.JsonBodyGenerator.<init>(JsonBodyGenerator.java:31)
at io.airlift.http.client.JsonBodyGenerator.jsonBodyGenerator(JsonBodyGenerator.java:26)
at com.facebook.presto.server.remotetask.HttpRemoteTask.sendUpdate(HttpRemoteTask.java:493)
- locked <0x00007fb661ce3bf8> (a com.facebook.presto.server.remotetask.HttpRemoteTask)
at com.facebook.presto.server.remotetask.HttpRemoteTask$$Lambda$1631/1576814460.run(Unknown Source)
at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
at io.airlift.concurrent.BoundedExecutor$$Lambda$660/1381196687.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```

This triggers a query serialization every time we send an update, which leads to huge coordinator burden. For example, a coordinator without fix #8961 can hang for minutes only formatting strings.

**Comment by BlueStalker** [comment]
Hmm, I think I got the same thing, https://groups.google.com/forum/#!topic/presto-users/JChwt76O5qo

But why it takes so long time like 20 minutes, what is it doing?

**Comment by wenleix** [comment]
This is interesting, because once `SqlTaskExcution` is created, it will set the `needsPlan` fragment in the returned `TaskInfo` to be false, to tell coordinator no longer need to send plan
