### ISSUE TITLE
OrderByOperator can run for hours

### ISSUE THREAD

**Issue by highker** [prestodb/presto#9011]
Let's see if we could make it faster or yield it?

```
2017-09-20T00:54:36.516-0700    WARN    TaskExecutor    com.facebook.presto.execution.executor.TaskExecutor     Split thread 20170920_073314_14168_94jjp.3.0-4 has been running longer than 17.51m
java.lang.Exception: Long running split
        at com.facebook.presto.spi.block.AbstractVariableWidthBlock.checkReadablePosition(AbstractVariableWidthBlock.java:152)
        at com.facebook.presto.spi.block.AbstractVariableWidthBlock.compareTo(AbstractVariableWidthBlock.java:100)
        at com.facebook.presto.spi.type.VarcharType.compareTo(VarcharType.java:131)
        at com.facebook.presto.spi.block.SortOrder.compareBlockValue(SortOrder.java:62)
        at com.facebook.presto.$gen.PagesIndexComparator_6589.compareTo(Unknown Source)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:100)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.sort(PagesIndexOrdering.java:37)
        at com.facebook.presto.operator.PagesIndex.sort(PagesIndex.java:341)
        at com.facebook.presto.operator.PagesIndex.sort(PagesIndex.java:336)
        at com.facebook.presto.operator.OrderByOperator.finish(OrderByOperator.java:164)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:357)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver$$Lambda$656/1508988511.get(Unknown Source)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by yuananf** [comment]
There is a pending PR for distributed merge sort
https://github.com/prestodb/presto/pull/8169

**Comment by martint** [comment]
@yuanaf, this is a little different. It's about the operator not relinquishing control to the engine as it processes. Every operator is expected to do some work and then yield when it gets blocked or when it has spent more than ~1s.

**Comment by yuananf** [comment]
@martint I see, thank you for explaining.

**Comment by aromero-pm** [comment]
@martint  any way for the operator to relinquish control, or is it really not feasible to interrupt the sort operation?

**Comment by highker** [comment]
This happens pretty often
```
2018-01-18T20:14:07.277-0800    WARN    TaskExecutor    com.facebook.presto.execution.executor.TaskExecutor     Split thread 20180119_003859_00961_7sh3e.2.143-7 has been running longer than 17.57m
java.lang.Exception: Long running split
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:100)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:137)
        at com.facebook.presto.operator.PagesIndexOrdering.quickSort(PagesIndexOrdering.java:134)
        at com.facebook.presto.operator.PagesIndexOrdering.sort(PagesIndexOrdering.java:37)
        at com.facebook.presto.operator.PagesIndex.sort(PagesIndex.java:366)
        at com.facebook.presto.operator.WindowOperator.sortPagesIndexIfNecessary(WindowOperator.java:454)
        at com.facebook.presto.operator.WindowOperator.finishPagesIndex(WindowOperator.java:462)
        at com.facebook.presto.operator.WindowOperator.finish(WindowOperator.java:295)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:399)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
        at com.facebook.presto.operator.Driver$$Lambda$1602/1568937788.get(Unknown Source)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:659)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by haozhun** [comment]
@highker If this isn't going to be fixed. Maybe a smaller step is to make it periodically check that whether it should give up the driver thread given the query has failed/cancelled.

**Comment by dain** [comment]
At the very least can we add
```
        if (Thread.interrupted()) {
            throw new InterruptedException();
        }
```
to the sort code, so when the driver thread is interrupted we stop.  (BTW yield would be better)
