### ISSUE TITLE
Error Starting Presto Server on Worker

### ISSUE THREAD

**Issue by FiredrakeRAGE** [prestodb/presto#902]
I have an HDFS/Hive instance set up using MySQL as a metastore.

Running the following version of Hadoop: hadoop-2.2.0
Running the following version of Hive: hive-0.12.0
Running the following version of Presto Server: presto-server-0.54
Running the following version of Discovery Server: discovery-server-1.16 
Using the following Presto CLI: presto-cli-0.54-executable.jar

I have a Presto coordinator setup on a system:

```
[root@viper etc]# cat config.properties
coordinator=true
datasources=jmx
http-server.http.port=8081
presto-metastore.db.type=h2
presto-metastore.db.filename=/hadoop/presto/db
task.max-memory=1GB
discovery-server.enabled=true
discovery.uri=http://viper:8081
```

```
[root@viper etc]# cat node.properties
node.id=c2a9dd40-43f6-4088-9cea-ebd6b9ee923c
node.environment=production
node.data-dir=/hadoop/presto/data
```

```
[root@viper etc]# ping -c 1 viper
PING viper (172.16.100.19) 56(84) bytes of data.
64 bytes from viper (172.16.100.19): icmp_seq=1 ttl=64 time=0.057 ms

--- viper ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.057/0.057/0.057/0.000 ms
```

The server starts fine, and (if there is a datanode configured) runs well.  

I try to start the Presto server on my worker, with the following configuration:

```
[root@defiance etc]# cat config.properties
coordinator=false
datasources=jmx,hive
http-server.http.port=8081
presto-metastore.db.type=h2
presto-metastore.db.filename=/hadoop/presto/db
task.max-memory=1GB
discovery.uri=http://viper:8081
```

```
[root@defiance etc]# cat node.properties
node.id=b948a821-f4e6-49c8-92f2-94dfcd5d407d
node.environment=production
node.data-dir=/hadoop/presto/data
```

```
[root@defiance etc]# ping -c 1 viper
PING viper (172.16.100.19) 56(84) bytes of data.
64 bytes from viper (172.16.100.19): icmp_seq=1 ttl=64 time=0.178 ms

--- viper ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.178/0.178/0.178/0.000 ms
```

I notice the following in the log output:  

```
2013-12-10T15:45:57.509+0000     INFO   main    org.eclipse.jetty.server.AbstractConnector      Started SelectChannelConnector@0.0.0.0:8081
```

I get a bunch of errors (see stack trace below).  It appears that the Presto server is attempting to connect and failing.  Any idea why?

Stack Trace:

```
2013-12-10T15:45:59.563+0000    ERROR   main    com.facebook.presto.server.PrestoServer Guice creation errors:

1) Error in custom provider, org.jboss.netty.channel.ChannelException: Failed to create a selector.
  while locating io.airlift.http.client.AsyncHttpClientModule$SharedNettyIoPoolProvider
  at io.airlift.http.client.AsyncHttpClientModule.configure(AsyncHttpClientModule.java:75)
  while locating io.airlift.http.client.netty.NettyIoPool
  at io.airlift.http.client.AsyncHttpClientModule.configure(AsyncHttpClientModule.java:78)
  at io.airlift.http.client.AsyncHttpClientModule.configure(AsyncHttpClientModule.java:78)
  while locating io.airlift.http.client.AsyncHttpClient annotated with @io.airlift.discovery.client.ForDiscoveryClient()
    for parameter 3 at io.airlift.discovery.client.HttpDiscoveryLookupClient.<init>(HttpDiscoveryLookupClient.java:63)
  while locating io.airlift.discovery.client.HttpDiscoveryLookupClient
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:51)
  while locating io.airlift.discovery.client.DiscoveryLookupClient
    for parameter 0 at io.airlift.discovery.client.CachingServiceSelectorFactory.<init>(CachingServiceSelectorFactory.java:32)
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:65)
  while locating io.airlift.discovery.client.CachingServiceSelectorFactory
  at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:117)
  at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:117)
  while locating io.airlift.discovery.client.MergingServiceSelectorFactory
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:66)
  while locating io.airlift.discovery.client.ServiceSelectorFactory
    for parameter 0 at io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:49)
  at io.airlift.discovery.client.DiscoveryBinder.bindSelector(DiscoveryBinder.java:64)

1 error
com.google.inject.CreationException: Guice creation errors:

1) Error in custom provider, org.jboss.netty.channel.ChannelException: Failed to create a selector.
  while locating io.airlift.http.client.AsyncHttpClientModule$SharedNettyIoPoolProvider
  at io.airlift.http.client.AsyncHttpClientModule.configure(AsyncHttpClientModule.java:75)
  while locating io.airlift.http.client.netty.NettyIoPool
  at io.airlift.http.client.AsyncHttpClientModule.configure(AsyncHttpClientModule.java:78)
  at io.airlift.http.client.AsyncHttpClientModule.configure(AsyncHttpClientModule.java:78)
  while locating io.airlift.http.client.AsyncHttpClient annotated with @io.airlift.discovery.client.ForDiscoveryClient()
    for parameter 3 at io.airlift.discovery.client.HttpDiscoveryLookupClient.<init>(HttpDiscoveryLookupClient.java:63)
  while locating io.airlift.discovery.client.HttpDiscoveryLookupClient
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:51)
  while locating io.airlift.discovery.client.DiscoveryLookupClient
    for parameter 0 at io.airlift.discovery.client.CachingServiceSelectorFactory.<init>(CachingServiceSelectorFactory.java:32)
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:65)
  while locating io.airlift.discovery.client.CachingServiceSelectorFactory
  at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:117)
  at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:117)
  while locating io.airlift.discovery.client.MergingServiceSelectorFactory
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:66)
  while locating io.airlift.discovery.client.ServiceSelectorFactory
    for parameter 0 at io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:49)
  at io.airlift.discovery.client.DiscoveryBinder.bindSelector(DiscoveryBinder.java:64)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:175) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109) ~[guice-3.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:95) ~[guice-3.0.jar:na]
        at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:277) ~[bootstrap-0.84.jar:0.84]
        at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:91) ~[na:na]
        at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:92) ~[presto-main-0.54.jar:0.54]
        at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:79) ~[presto-main-0.54.jar:0.54]
        at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:64) ~[presto-main-0.54.jar:0.54]
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:87) [presto-server-0.54.jar:0.54]
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:47) [presto-server-0.54.jar:0.54]
Caused by: org.jboss.netty.channel.ChannelException: Failed to create a selector.
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:337) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:95) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:51) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:45) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:28) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.newWorker(AbstractNioWorkerPool.java:99) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:69) ~[netty-3.6.2.Final.jar:na]
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39) ~[netty-3.6.2.Final.jar:na]
        at io.airlift.http.client.netty.NettyIoPool.<init>(NettyIoPool.java:65) ~[http-client-0.84.jar:0.84]
        at io.airlift.http.client.AsyncHttpClientModule$NettyIoPoolProvider.get(AsyncHttpClientModule.java:189) ~[http-client-0.84.jar:0.84]
        at io.airlift.http.client.AsyncHttpClientModule$NettyIoPoolProvider.get(AsyncHttpClientModule.java:157) ~[http-client-0.84.jar:0.84]
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:55) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013) ~[guice-3.0.jar:na]
        at io.airlift.http.client.AsyncHttpClientModule$HttpClientProvider.get(AsyncHttpClientModule.java:139) ~[http-client-0.84.jar:0.84]
        at io.airlift.http.client.AsyncHttpClientModule$HttpClientProvider.get(AsyncHttpClientModule.java:97) ~[http-client-0.84.jar:0.84]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254) ~[guice-3.0.jar:na]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974) ~[guice-3.0.jar:na]
        at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:89) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:98) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) ~[guice-3.0.jar:na]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.Scopes$1$1.get(Scopes.java:65) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-3.0.jar:na]
        at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:83) ~[guice-3.0.jar:na]
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110) ~[guice-3.0.jar:na]
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:75) ~[guice-3.0.jar:na]
        at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:73) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024) ~[guice-3.0.jar:na]
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:73) ~[guice-3.0.jar:na]
        at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:147) ~[guice-3.0.jar:na]
        at com.google.inject.internal.Initializer.injectAll(Initializer.java:92) ~[guice-3.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:173) ~[guice-3.0.jar:na]
        ... 9 common frames omitted
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.IOUtil.makePipe(Native Method) ~[na:1.7.0_45]
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:65) ~[na:1.7.0_45]
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36) ~[na:1.7.0_45]
        at java.nio.channels.Selector.open(Selector.java:227) ~[na:1.7.0_45]
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:335) ~[netty-3.6.2.Final.jar:na]
        ... 85 common frames omitted
2013-12-10T15:45:59.565+0000     INFO   Thread-48       io.airlift.bootstrap.LifeCycleManager   Life cycle stopping...
```

**Comment by SivaBu-kore** [comment]
we have file limit set to 66k, still seeing the same issue.
```
[kore@installer-tst ~]$ netstat -lnt |grep 7001
tcp6       0      0 :::7001                 :::*                    LISTEN
[kore@installer-tst ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 119924
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 66000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
[kore@installer-tst ~]$
```
