### ISSUE TITLE
Analysis error for table alias in lambda

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#9023]
```
presto:default> select transform(array[1], x -> x + t.a) from (values 1, 2, 3) t(a);
Query 20170921_015629_01585_tme2n failed: line 1:37: Column 't' cannot be resolved
com.facebook.presto.sql.analyzer.SemanticException: line 1:37: Column 't' cannot be resolved
	at com.facebook.presto.sql.analyzer.SemanticExceptions.missingAttributeException(SemanticExceptions.java:30)
	at com.facebook.presto.sql.analyzer.Scope.lambda$resolveField$0(Scope.java:104)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at com.facebook.presto.sql.analyzer.Scope.resolveField(Scope.java:104)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:371)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitIdentifier(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.Identifier.accept(Identifier.java:70)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:404)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitDereferenceExpression(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.DereferenceExpression.accept(DereferenceExpression.java:54)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.getOperator(ExpressionAnalyzer.java:1145)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:575)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitArithmeticBinary(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.ArithmeticBinaryExpression.accept(ArithmeticBinaryExpression.java:85)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:1080)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitLambdaExpression(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.LambdaExpression.accept(LambdaExpression.java:60)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:264)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.access$1900(ExpressionAnalyzer.java:160)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.lambda$visitFunctionCall$1(ExpressionAnalyzer.java:799)
	at com.facebook.presto.sql.analyzer.TypeSignatureProvider.getTypeSignature(TypeSignatureProvider.java:60)
	at com.facebook.presto.metadata.SignatureBinder$FunctionSolver.update(SignatureBinder.java:725)
	at com.facebook.presto.metadata.SignatureBinder.iterativeSolve(SignatureBinder.java:399)
	at com.facebook.presto.metadata.SignatureBinder.bindVariables(SignatureBinder.java:114)
	at com.facebook.presto.metadata.SignatureBinder.bind(SignatureBinder.java:91)
	at com.facebook.presto.metadata.FunctionRegistry.identifyApplicableFunctions(FunctionRegistry.java:734)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunction(FunctionRegistry.java:703)
	at com.facebook.presto.metadata.FunctionRegistry.matchFunctionExact(FunctionRegistry.java:693)
	at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:648)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.resolveFunction(ExpressionAnalyzer.java:1321)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:808)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:282)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:111)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:301)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:258)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1472)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:1901)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:1713)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.legacyVisitQuerySpecification(StatementAnalyzer.java:968)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:913)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:267)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:648)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:72)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:351)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
select transform(array[1], x -> x + t.a) from (values 1, 2, 3) t(a)

**Comment by findepi** [comment]
This is since 789e4772527037efaed9e3bfbccfdee42697fa4b and this boils down to #7790.

**Comment by findepi** [comment]
Duplicates #7784

**Comment by sopel39** [comment]
waits for release to complete before merging #9099 again
