### ISSUE TITLE
Parquet select failed Column sub_impression_events type LIST not supported

### ISSUE THREAD

**Issue by bwang398** [prestodb/presto#9024]
presto:
select * from reddw.dw_log_events_algo_hourly limit 3;

error:
Query 20170921_130430_00008_6tk5t failed: Error opening Hive split s3://xhs.alpha/dw/dw_log_events_algo_hourly/2017/09/21/10/part-r-00011-e4ad4629-0325-416d-a084-e4455c3a4bec.snappy.parquet (offset=100663296, length=33554432): Column sub_impression_events type LIST not supported

hive is correct;
presto:
select * from reddw.dw_log_events_algo_hourly limit 3;

**Comment by nezihyigitbasi** [comment]
Did you try the optimized Parquet reader? You can enable it with `set session hive.parquet_optimized_reader_enabled=true;`.

**Comment by bramth** [comment]
hi, I experienced similar issue..

Error opening Hive split s3a://.../part-0000-156890-68224581-1068-4633-84ed-7b2268ed70a6.c000.snappy.parquet (offset=0, length=2048235): Column product.depId type LIST not supported

Querying the same table in HIVE has no issue as well

however when I moved that parquet file alone to another bucket then create external table, i have no problem querying it.. any idea?

btw @nezihyigitbasi I tried your approach but it gives me all NULL value for product.depId column which is an array of varchar field

**Comment by nezihyigitbasi** [comment]
@bramth what is the schema of the table and what's the schema of the parquet file (you can use parquet tools to get the file-level schema, see [this](https://community.hortonworks.com/articles/73952/build-and-use-parquet-tools-to-read-parquet-files.html))?

Also can you please post the entire stack trace (start the presto-cli with `--debug`)?

To debug cases like this it always helps to have a small test file that can reproduce the problem.

**Comment by bwang398** [comment]
@nezihyigitbasi @bramth 
1、presto> select * from reddw.dw_log_events_algo_hourly limit 3;

Query 20170929_082054_00009_9x4fj, FAILED, 43 nodes
http://ip-172-31-13-106.cn-north-1.compute.internal:8889/query.html?20170929_082054_00009_9x4fj
Splits: 1,144 total, 180 done (15.73%)
CPU Time: 5.5s total,     0 rows/s,     0B/s, 14% active
Per Node: 0.1 parallelism,     0 rows/s,     0B/s
Parallelism: 4.6
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20170929_082054_00009_9x4fj failed: Error opening Hive split s3://xhs.alpha/dw/dw_log_events_algo_hourly/2017/09/26/21/part-r-00000-cdc06c15-af70-42de-a984-d770bf7dce8c.snappy.parquet (offset=86784728, length=53230296): Column sub_impression_events type LIST not supported
com.facebook.presto.spi.PrestoException: Error opening Hive split s3://xhs.alpha/dw/dw_log_events_algo_hourly/2017/09/26/21/part-r-00000-cdc06c15-af70-42de-a984-d770bf7dce8c.snappy.parquet (offset=86784728, length=53230296): Column sub_impression_events type LIST not supported
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:382)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:156)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createRecordCursor(ParquetRecordCursorProvider.java:92)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:157)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:87)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:253)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:624)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Column sub_impression_events type LIST not supported
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createGroupConverter(ParquetHiveRecordCursor.java:720)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.access$300(ParquetHiveRecordCursor.java:99)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor$PrestoReadSupport.<init>(ParquetHiveRecordCursor.java:434)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:336)
	... 17 more




2、after   set session hive.parquet_optimized_reader_enabled=true;

presto> set session hive.parquet_optimized_reader_enabled=true;
SET SESSION
presto> select * from reddw.dw_log_events_algo_hourly limit 3;

Query 20170929_082328_00011_9x4fj, FAILED, 43 nodes
http://ip-172-31-13-106.cn-north-1.compute.internal:8889/query.html?20170929_082328_00011_9x4fj
Splits: 748 total, 37 done (4.95%)
CPU Time: 1.3s total,     0 rows/s,     0B/s, 11% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.8
0:02 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20170929_082328_00011_9x4fj failed: Index (0) is greater than or equal to list size (0)
com.facebook.presto.spi.PrestoException: Index (0) is greater than or equal to list size (0)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:225)
	at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:204)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:256)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:624)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:776)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
	at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:217)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:209)
	at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:183)
	at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:201)
	... 12 more

**Comment by bramth** [comment]
@nezihyigitbasi sorry for the late reply:

I have tried parquet-tools from link you mentioned and found out that parquet-tools seems to read string datatype in presto as a binary datatype and also bigint as int64, here is the snippet:

`
> java -jar /home/hadoop/parquet/parquet-tools-1.9.0.jar schema part-0000_2017-09-26-13-47-42-260164-b806276b-48b6-4e31-aa26-e52021e10ce1.c000.snappy.parquet

output:
...
optional group product {
    optional group depId (LIST) {
      repeated group list {
        optional binary element (UTF8);
      }
    }
    optional binary id (UTF8);
    optional binary name (UTF8);
    optional int64 price;
  }
...

actual table schema in presto: 
CREATE TABLE hive.iris.ads_click_placeholder (                                                                                                                                                                                       
    ...                                                                                                                                                                                                                   
    product row( ..., name varchar, depid array(varchar), price bigint, id varchar),                                                                             
    date varchar
     ...                                                                                                                                                                                                               
 )                                                                                                                                                                                                                                    
 WITH (                                                                                                                                                                                                                               
    external_location = 's3a://lake/product,                                                                                                                                                            
    format = 'PARQUET',                                                                                                                                                                                                               
    partitioned_by = ARRAY['date']                                                                                                                                                                                               
 )
`
Btw here is the full stack trace after I enable `--debug` in presto

`
presto:lake> select * from product limit 10;

Query 20171003_101519_00561_6xrfv, FAILED, 2 nodes
http://localhost:8889/query.html?20171003_101519_00561_6xrfv
Splits: 98 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 23% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.1
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20171003_101519_00561_6xrfv failed: Error opening Hive split s3a://lake/product/date=2017-09-25/part-0000_2017-09-26-13-47-42-260164-b806276b-48b6-4e31-aa26-e52021e10ce1.c000.snappy.parquet (offset=0, length=30890026): Column product.depId type LIST not supported
com.facebook.presto.spi.PrestoException: Error opening Hive split s3a://lake/product/date=2017-09-25/part-0000_2017-09-26-13-47-42-260164-b806276b-48b6-4e31-aa26-e52021e10ce1.c000.snappy.parquet (offset=0, length=30890026): Column product.depId type LIST not supported
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:386)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:160)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createRecordCursor(ParquetRecordCursorProvider.java:94)
	at com.facebook.presto.hive.HivePageSourceProvider.createHivePageSource(HivePageSourceProvider.java:159)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:87)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:44)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:259)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:335)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:240)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:612)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Column product.depId type LIST not supported
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createGroupConverter(ParquetHiveRecordCursor.java:724)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createConverter(ParquetHiveRecordCursor.java:710)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.access$1100(ParquetHiveRecordCursor.java:102)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor$ParquetStructConverter.<init>(ParquetHiveRecordCursor.java:760)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createGroupConverter(ParquetHiveRecordCursor.java:722)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.access$300(ParquetHiveRecordCursor.java:102)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor$PrestoReadSupport.<init>(ParquetHiveRecordCursor.java:438)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:339)
	... 18 more`

Here is the stack trace after I enabled `hive.parquet_optimized_reader_enabled` to true

`
presto:lake> set session hive.parquet_optimized_reader_enabled=true;
SET SESSION
presto:iris> select * from ads_click_placeholder;
                                                       product                                                                                                  
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {name=Panasonic E27, depid=null, price=7750, id=179164559} 
...

Query 20171003_101057_00559_6xrfv, RUNNING, 2 nodes
http://localhost:8889/query.html?20171003_101057_00559_6xrfv
Splits: 97 total, 0 done (0.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 100% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
0:07 [0 rows, 0B] [0 rows/s, 0B/s]
`

Presto table can be queried but the depId columns which suppose to contain array of string is read as NULL. 

If I read the parquet file in spark or hive, it is working fine.

**Comment by JAlexoid** [comment]
This is now resulting in this error for the old reader and optimized reader is failing silently(returns all nulls)
`java.lang.NullPointerException
	at com.facebook.presto.spi.block.ArrayBlockBuilder.writeObject(ArrayBlockBuilder.java:148)
	at com.facebook.presto.spi.type.ArrayType.writeObject(ArrayType.java:190)
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:121)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:262)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`




`message spark_schema {
  optional binary version (UTF8);
  optional binary id (UTF8);
  optional int32 event_time;
  optional int32 born_time;
  optional group ids (LIST) {
    repeated group list {
      optional binary element (UTF8);
    }
  }
}`

Versus a schema that works without issues(created by insert into hive_schema select * from spark_schema):
`message hive_schema {
  optional binary version (UTF8);
  optional binary id (UTF8);
  optional int32 event_time;
  optional int32 born_time;
  optional group ids (LIST) {
    repeated group bag {
      optional binary array_element (UTF8);
    }
  }
}`
