### ISSUE TITLE
Method code too large in presto 0.171

### ISSUE THREAD

**Issue by tomerstar** [prestodb/presto#9039]
Hi,
While running this insert on Presto 0.171 with hive connector to CDH 5.11.0:

```
insert into stgout_db.t_ftcd_negative_out select cast(f.dk_dat as smallint)as dk_dat,cast(f.dk_tim as INTEGER)as dk_tim,cast(f.dk_tzi as smallint)as dk_tzi,cast(f.cl_grp_id as smallint)as cl_grp_id,cast(f.dk_dir as smallint)as dk_dir,cast(f.dk_bra as INTEGER)as dk_bra,cast(f.dk_pcs as smallint)as dk_pcs,cast(f.dk_org_smp as INTEGER)as dk_org_smp,cast(f.dk_org_snw as INTEGER)as dk_org_snw,cast(f.dk_org_hnw as INTEGER)as dk_org_hnw,cast(f.dk_org_cnp as INTEGER)as dk_org_cnp,cast(f.dk_org_mcp as INTEGER)as dk_org_mcp,cast(f.dk_org_sbo as INTEGER)as dk_org_sbo,cast(f.dk_sbp_ss as INTEGER)as dk_sbp_ss,cast(f.dk_org_fcp as INTEGER)as dk_org_fcp,cast(f.dk_bid_hom as INTEGER)as dk_bid_hom,cast(f.dk_bid_snw as INTEGER)as dk_bid_snw,cast(f.dk_sld as INTEGER)as dk_sld,cast(f.dk_ced as smallint)as dk_ced,cast(f.dk_aft as smallint)as dk_aft,cast(f.dk_afs_taf as smallint)as dk_afs_taf,cast(f.dk_svl as smallint)as dk_svl,cast(f.dk_sbp as INTEGER)as dk_sbp,cast(f.dk_nws as smallint)as dk_nws,cast(f.dk_cab_avl as INTEGER)as dk_cab_avl,cast(f.dk_cab_rcv as INTEGER)as dk_cab_rcv,cast(f.dk_cab_prc as INTEGER)as dk_cab_prc,cast(f.dk_cau as INTEGER)as dk_cau,cast(f.dk_nui as INTEGER)as dk_nui,cast(f.dk_ttb_iot as bigint)as dk_ttb_iot,cast(f.dk_taf as bigint)as dk_taf,cast(f.dk_cur_tlc as smallint)as dk_cur_tlc,cast(f.dk_cur_smc as smallint)as dk_cur_smc,cast(f.dk_cur_pic as smallint)as dk_cur_pic,cast(f.dk_cur_rtc as smallint)as dk_cur_rtc,cast(f.dk_cur_rpc as smallint)as dk_cur_rpc,cast(f.dk_cur_grc as smallint)as dk_cur_grc,cast(f.dk_rpf as bigint)as dk_rpf,cast(f.dk_ecd as INTEGER)as dk_ecd,cast(f.dk_tmo as bigint)as dk_tmo,cast(f.dk_tst as bigint)as dk_tst,cast(f.dk_tzn_loc as bigint)as dk_tzn_loc,cast(f.dk_tzn_dst as bigint)as dk_tzn_dst,cast(f.dk_ttb_rrt as bigint)as dk_ttb_rrt,cast(f.dk_gpi as smallint)as dk_gpi,cast(f.dk_cdt_cnn as smallint)as dk_cdt_cnn,cast(f.dk_cdt_dld as smallint)as dk_cdt_dld,cast(f.dk_dst_dld as smallint)as dk_dst_dld,cast(f.dk_dst_cnn as smallint)as dk_dst_cnn,cast(f.dk_apn as INTEGER)as dk_apn,cast(f.dk_gsn_sgn as bigint)as dk_gsn_sgn,cast(f.dk_gsn as bigint)as dk_gsn,cast(f.dk_clb as INTEGER)as dk_clb,cast(f.dk_cvb as INTEGER)as dk_cvb,cast(f.dk_smi as bigint)as dk_smi,cast(f.dk_sps as smallint)as dk_sps,cast(f.dk_spn as INTEGER)as dk_spn,cast(f.dk_isv as smallint)as dk_isv,cast(f.dk_umi as smallint)as dk_umi,cast(f.dk_dlp as INTEGER)as dk_dlp,cast(f.dk_loi as bigint)as dk_loi,cast(f.dk_msc as bigint)as dk_msc,cast(f.dd_imsi as bigint)as dd_imsi,cast(f.dd_msisdn_min as bigint)as dd_msisdn_min,cast(f.dd_cid as INTEGER)as dd_cid,cast(f.dd_lac as INTEGER)as dd_lac,cast(f.dd_imei as VARCHAR)as dd_imei,cast(f.dd_cllg_no as VARCHAR)as dd_cllg_no,cast(f.dd_clld_no as VARCHAR)as dd_clld_no,cast(f.dd_cml_no as VARCHAR)as dd_cml_no,cast(f.dd_dld_digits as VARCHAR)as dd_dld_digits,cast(f.dd_chg_id as VARCHAR)as dd_chg_id,cast(f.dd_puid as VARCHAR)as dd_puid,cast(f.dd_puid_ncp as VARCHAR)as dd_puid_ncp,cast(f.ld_id as bigint)as ld_id,cast(f.dk_adt as bigint)as dk_adt,cast(f.dk_meq as INTEGER)as dk_meq,cast(f.dk_tri_rrt_dur as bigint)as dk_tri_rrt_dur,cast(f.dk_tri_rrt_vol as bigint)as dk_tri_rrt_vol,cast(f.dk_tri_rrt_evt as bigint)as dk_tri_rrt_evt,cast(f.dk_dat_cre as smallint)as dk_dat_cre,cast(f.dk_dat_ctf as smallint)as dk_dat_ctf,cast(f.dk_dat_fat as smallint)as dk_dat_fat,cast(f.dk_dat_mo_inv as smallint)as dk_dat_mo_inv,cast(f.dk_dat_rcv as smallint)as dk_dat_rcv,cast(f.dk_dat_vld as smallint)as dk_dat_vld,cast(f.dk_tdi as bigint)as dk_tdi,cast(f.dk_taf_ogf as bigint)as dk_taf_ogf,cast(f.dk_rpf_rfl as bigint)as dk_rpf_rfl,cast(f.dk_org_cy_shn as bigint)as dk_org_cy_shn,cast((f.no_cll*-1 ) as smallint)as no_cll,cast((f.no_ced*-1 ) as smallint)as no_ced,cast((f.no_evt*-1 ) as INTEGER)as no_evt,cast((f.no_chgd_evt*-1 ) as INTEGER)as no_chgd_evt,cast((f.vol_out*-1 ) as bigint)as vol_out,cast((f.vol_inc*-1 ) as bigint)as vol_inc,cast((f.chgb_vol*-1 ) as bigint)as chgb_vol,cast((f.chgd_vol*-1 ) as bigint)as chgd_vol,cast((f.chgb_dur*-1 ) as INTEGER)as chgb_dur,cast((f.chgb_dur_air*-1 ) as INTEGER)as chgb_dur_air,cast((f.chgb_dur_tll*-1 ) as INTEGER)as chgb_dur_tll,cast((f.chgb_dur_oct*-1 ) as INTEGER)as chgb_dur_oct,cast((f.chgd_dur*-1 ) as INTEGER)as chgd_dur,cast((f.chgd_dur_air*-1 ) as INTEGER)as chgd_dur_air,cast((f.chgd_dur_tll*-1 ) as INTEGER)as chgd_dur_tll,cast((f.chgd_dur_oct*-1 ) as INTEGER)as chgd_dur_oct,cast((f.sm_nchg*-1 ) as bigint)as sm_nchg,cast((f.sm_nchg_air*-1 ) as bigint)as sm_nchg_air,cast((f.sm_nchg_tll*-1 ) as bigint)as sm_nchg_tll,cast((f.sm_nchg_oct*-1 ) as bigint)as sm_nchg_oct,cast((f.sm_tx*-1 ) as bigint)as sm_tx,cast((f.sm_tx_air*-1 ) as bigint)as sm_tx_air,cast((f.sm_tx_tll*-1 ) as bigint)as sm_tx_tll,cast((f.sm_tx_oct*-1 ) as bigint)as sm_tx_oct,cast((f.sm_tx_sta*-1 ) as bigint)as sm_tx_sta,cast((f.sm_tx_lcl*-1 ) as bigint)as sm_tx_lcl,cast((f.sm_tx_vat*-1 ) as bigint)as sm_tx_vat,cast((f.sm_tx_ntnl*-1 ) as bigint)as sm_tx_ntnl,cast((f.sm_tx_cnty*-1 ) as bigint)as sm_tx_cnty,cast((f.sm_ndsct*-1 ) as bigint)as sm_ndsct,cast((f.sm_nchg_dur*-1 ) as bigint)as sm_nchg_dur,cast((f.sm_tx_dur*-1 ) as bigint)as sm_tx_dur,cast((f.sm_nchg_dur_air*-1 ) as bigint)as sm_nchg_dur_air,cast((f.sm_tx_dur_air*-1 ) as bigint)as sm_tx_dur_air,cast((f.sm_nchg_dur_tll*-1 ) as bigint)as sm_nchg_dur_tll,cast((f.sm_tx_dur_tll*-1 ) as bigint)as sm_tx_dur_tll,cast((f.sm_nchg_dur_oct*-1 ) as bigint)as sm_nchg_dur_oct,cast((f.sm_tx_dur_oct*-1 ) as bigint)as sm_tx_dur_oct,cast((f.sm_nchg_vol*-1 ) as bigint)as sm_nchg_vol,cast((f.sm_tx_vol*-1 ) as bigint)as sm_tx_vol,cast((f.sm_nchg_evt*-1 ) as bigint)as sm_nchg_evt,cast((f.sm_tx_evt*-1 ) as bigint)as sm_tx_evt,cast((f.rr_nchg*-1 ) as bigint)as rr_nchg,cast((f.rr_tx*-1 ) as bigint)as rr_tx,cast((f.rr_ndsct*-1 ) as bigint)as rr_ndsct,cast((f.rr_dur*-1 ) as INTEGER)as rr_dur,cast((f.rr_vol*-1 ) as bigint)as rr_vol,cast((f.rr_no_evt*-1 ) as INTEGER)as rr_no_evt,cast((f.og_nchg*-1 ) as bigint)as og_nchg,cast((f.og_tx*-1 ) as bigint)as og_tx,cast((f.og_ndsct*-1 ) as bigint)as og_ndsct,cast((f.og_dur*-1 ) as INTEGER)as og_dur,cast((f.og_vol*-1 ) as bigint)as og_vol,cast((f.og_no_evt*-1 ) as INTEGER)as og_no_evt,cast((f.rp_nchg*-1 ) as bigint)as rp_nchg,cast((f.rp_tx*-1 ) as bigint)as rp_tx,cast((f.rp_ndsct*-1 ) as bigint)as rp_ndsct,cast((f.noc_nchg*-1 ) as bigint)as noc_nchg,cast((f.noc_tx*-1 ) as bigint)as noc_tx,cast((f.noc_ndsct*-1 ) as bigint)as noc_ndsct,cast((f.noc_dur*-1 ) as INTEGER)as noc_dur,cast((f.noc_vol*-1 ) as bigint)as noc_vol,cast((f.noc_no_evt*-1 ) as INTEGER)as noc_no_evt,cast(f.trf_exr_tlc_2_smc as bigint)as trf_exr_tlc_2_smc,cast(f.trf_exr_pic_2_rtc as bigint)as trf_exr_pic_2_rtc,cast(f.trf_exr_smc_2_rpc as bigint)as trf_exr_smc_2_rpc,cast(f.trf_exr_smc_2_grc as bigint)as trf_exr_smc_2_grc,cast(f.trf_exr_pic_2_rpc as bigint)as trf_exr_pic_2_rpc,cast(f.trf_exr_pic_2_grc as bigint)as trf_exr_pic_2_grc, '0003335-170919104757052-oozie-oozi-W' as wf_id, cast( f.cl_id as INTEGER) as cl_id,cast( f.dk_dat_mo as smallint) as dk_dat_mo,cast( f.ld_group_id as INTEGER) as ld_group_id  from tap_db.t_ftcd f  where cl_id =7 and ((f.dk_dat_mo = 331 AND f.ld_group_id = 162 and ld_id in (3335257962)) OR (f.dk_dat_mo = 331 AND f.ld_group_id = 164 and ld_id in (3334880804)) OR (f.dk_dat_mo = 331 AND f.ld_group_id = 98 and ld_id in (3334917698)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 88 and ld_id in (3335092408)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 190 and ld_id in (3335458750)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 194 and ld_id in (3335476394)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 230 and ld_id in (3335548110)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 198 and ld_id in (3335100358,3335067038,3335075438)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 110 and ld_id in (3335099990,3334902310)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 232 and ld_id in (3335032072,3334674512)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 112 and ld_id in (3334796472)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 114 and ld_id in (3335085434,3335935514)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 236 and ld_id in (3335088076,3334379116)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 116 and ld_id in (3335041756,3335544356,3335145916)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 238 and ld_id in (3335175158)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 90 and ld_id in (3335787370,3335114250)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 92 and ld_id in (3335450532,3334630412,3334977052)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 96 and ld_id in (3335021576)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 10 and ld_id in (3335321930,3335383250)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 98 and ld_id in (3334496858,3334917698)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 12 and ld_id in (3335017852)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 14 and ld_id in (3335050054)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 16 and ld_id in (3335460256)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 18 and ld_id in (3334979498)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 120 and ld_id in (3335044000,3334873200,3335052400,3335707040,3334932840)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 242 and ld_id in (3334728562,3335454602)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 122 and ld_id in (3334751402,3335284242,3335556682)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 244 and ld_id in (3335190284,3335298924)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 124 and ld_id in (3335206404)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 4 and ld_id in (3334488364,3335032964,3334776484)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 246 and ld_id in (3335405326)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 248 and ld_id in (3335143528,3335308168,3334645408,3335002688)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 128 and ld_id in (3334739648)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 8 and ld_id in (3335496648,3335323888,3334814288)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 20 and ld_id in (3334594780)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 22 and ld_id in (3334770342,3335622662)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 26 and ld_id in (3334765306)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 28 and ld_id in (3334321508)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 250 and ld_id in (3335344570)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 130 and ld_id in (3335019370,3334685050)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 252 and ld_id in (3335596852)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 132 and ld_id in (3334633532,3335430972)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 134 and ld_id in (3335299934,3335432094)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 256 and ld_id in (3335295576)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 136 and ld_id in (3335153776,3335362656,3335076496)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 258 and ld_id in (3335511458)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 32 and ld_id in (3335067152,3335501432)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 34 and ld_id in (3334998834,3332927674,3335002474)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 38 and ld_id in (3334264958)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 260 and ld_id in (3335523780,3334367380,3334661100)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 142 and ld_id in (3334695142,3335054102)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 264 and ld_id in (3335101824)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 144 and ld_id in (3335168624)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 266 and ld_id in (3334718226)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 146 and ld_id in (3335389826,3335392906)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 268 and ld_id in (3335458828)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 148 and ld_id in (3334852228,3335315068)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 40 and ld_id in (3335242160,3335240480)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 42 and ld_id in (3334887962,3335089562)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 48 and ld_id in (3334506608,3334721088)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 270 and ld_id in (3335252190)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 150 and ld_id in (3334827590)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 272 and ld_id in (3335186392,3335376232)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 152 and ld_id in (3335194952,3335124392,3334723432,3334952472)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 274 and ld_id in (3334894074)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 154 and ld_id in (3334610314)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 278 and ld_id in (3335114998,3334714598)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 158 and ld_id in (3335017438)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 50 and ld_id in (3334979250)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 54 and ld_id in (3334329654)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 56 and ld_id in (3335935736)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 58 and ld_id in (3335130178,3335769978,3332984818,3335057098)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 160 and ld_id in (3335045440,3335156320)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 162 and ld_id in (3335257962)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 164 and ld_id in (3334880804,3334932324)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 166 and ld_id in (3335130286,3335135886)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 168 and ld_id in (3334614248,3334917488)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 202 and ld_id in (3334101042,3335174842)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 204 and ld_id in (3335340044)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 206 and ld_id in (3335430206)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 60 and ld_id in (3335096580,3334746580,3334963580,3334760580)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 62 and ld_id in (3334729782,3334485062)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 66 and ld_id in (3334828626,3335215306)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 170 and ld_id in (3334999810,3335035090)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 210 and ld_id in (3333385650,3334091250)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 212 and ld_id in (3334674492)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 214 and ld_id in (3335213214)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 216 and ld_id in (3335114936,3335471376,3334521616,3335205096)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 218 and ld_id in (3334822338,3335324938)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 72 and ld_id in (3335066352,3335076992,3335542072)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 74 and ld_id in (3335254794)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 76 and ld_id in (3335560556)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 78 and ld_id in (3334910678,3335488318)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 180 and ld_id in (3335186580)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 186 and ld_id in (3334704146)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 220 and ld_id in (3335207340,3334651260)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 100 and ld_id in (3335274420,3335164100)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 222 and ld_id in (3335233662)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 102 and ld_id in (3334814942,3334845742)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 104 and ld_id in (3334741864)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 106 and ld_id in (3335419186)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 80 and ld_id in (3333436760,3335079240)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 108 and ld_id in (3335223748,3334430228)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 82 and ld_id in (3335143082)) OR (f.dk_dat_mo = 332 AND f.ld_group_id = 84 and ld_id in (3335135524)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 44 and ld_id in (3335915004,3334552524)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 192 and ld_id in (3336192072)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 150 and ld_id in (3335966630)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 272 and ld_id in (3335966752)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 198 and ld_id in (3335963598)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 110 and ld_id in (3336242670)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 112 and ld_id in (3335419752)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 156 and ld_id in (3335760556,3335339996,3335881796)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 278 and ld_id in (3335966758,3336016038)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 114 and ld_id in (3335960154,3336058434)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 236 and ld_id in (3334379116)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 90 and ld_id in (3336023130,3334637970,3335787370)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 238 and ld_id in (3335349038)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 118 and ld_id in (3334989398,3335849838)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 92 and ld_id in (3335904132)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 94 and ld_id in (3334824734,3335112854)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 50 and ld_id in (3336005450)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 10 and ld_id in (3336122170,3335733810)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 54 and ld_id in (3335371814,3334329654,3335882254)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 98 and ld_id in (3335970218)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 56 and ld_id in (3335891776)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 12 and ld_id in (3335360852)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 58 and ld_id in (3335769978,3335029658)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 14 and ld_id in (3335539494)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 16 and ld_id in (3336013536,3335932896)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 120 and ld_id in (3336087560,3335707040)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 164 and ld_id in (3334620404,3335964684,3335896084,3334494684)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 122 and ld_id in (3335883162,3335849842,3335252322)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 166 and ld_id in (3334528566,3336059046)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 2 and ld_id in (3334598962,3335959762,3334719642)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 200 and ld_id in (3335316800)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 168 and ld_id in (3335431568,3335879008)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 246 and ld_id in (3335902886,3335455726,3335823926)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 6 and ld_id in (3335010566)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 204 and ld_id in (3335894724)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 128 and ld_id in (3336163448)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 206 and ld_id in (3336197406,3336120686)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 60 and ld_id in (3335966820)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 64 and ld_id in (3335862664)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 66 and ld_id in (3335670586,3335720426)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 24 and ld_id in (3336056944)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 68 and ld_id in (3335966828)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 26 and ld_id in (3334765306)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 28 and ld_id in (3335883908,3334321508)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 170 and ld_id in (3336005850)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 252 and ld_id in (3335966172,3334684612)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 132 and ld_id in (3335862172)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 210 and ld_id in (3335917970)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 178 and ld_id in (3335917378,3335899458)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 256 and ld_id in (3335966736)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 212 and ld_id in (3336162972,3335972572)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 258 and ld_id in (3336192138)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 214 and ld_id in (3335827254,3335917694)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 216 and ld_id in (3336123776,3336014296)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 218 and ld_id in (3335789178,3335996658,3336248658)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 70 and ld_id in (3335521910)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 72 and ld_id in (3335827672,3335983912)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 30 and ld_id in (3335730750)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 78 and ld_id in (3336105158,3335705318)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 180 and ld_id in (3335756660)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 184 and ld_id in (3335883224)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 140 and ld_id in (3335900260)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 262 and ld_id in (3336017982,3336005102)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 142 and ld_id in (3336064902)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 264 and ld_id in (3335903184)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 144 and ld_id in (3335886544,3336251104)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 100 and ld_id in (3335587460)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 222 and ld_id in (3334970742)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 266 and ld_id in (3334718226)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 268 and ld_id in (3335185268,3334904708)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 148 and ld_id in (3335966348)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 226 and ld_id in (3335080226,3334766066)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 106 and ld_id in (3335178106)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 228 and ld_id in (3335858348,3334999028)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 108 and ld_id in (3334430228)) OR (f.dk_dat_mo = 333 AND f.ld_group_id = 42 and ld_id in (3336191362)))
```

I got  this error:
```
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.facebook.presto.spi.PrestoException: Method code too large!
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:114)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1068)
	... 65 more
Caused by: com.facebook.presto.spi.PrestoException: Method code too large!
	at com.facebook.presto.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:132)
	at com.facebook.presto.sql.gen.ExpressionCompiler.access$300(ExpressionCompiler.java:47)
	at com.facebook.presto.sql.gen.ExpressionCompiler$1.load(ExpressionCompiler.java:58)
	at com.facebook.presto.sql.gen.ExpressionCompiler$1.load(ExpressionCompiler.java:53)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 71 more
Caused by: java.lang.RuntimeException: Method code too large!
	at org.objectweb.asm.MethodWriter.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.toByteArray(Unknown Source)
	at com.facebook.presto.bytecode.CompilerUtils.defineClasses(CompilerUtils.java:110)
	at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:73)
	at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:79)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compileProcessor(ExpressionCompiler.java:162)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compile(ExpressionCompiler.java:129)
	... 78 more
```

Saw that in the past there were some bug on "not in", but they were fixed

Regards,
Tomer

**Comment by electrum** [comment]
This is a limitation of the Presto expression code generator. It means the expression is too large. Try rewriting your query like this:
```sql
WHERE cl_id = 7 AND (f.dk_dat_mo, f.ld_group_id, ld_id) IN  (
  (331, 162, 3335257962),
  (331, 164, 3334880804),
  ...
)
