### ISSUE TITLE
Presto-Pulsar Connector

### ISSUE THREAD

**Issue by Yaliang** [prestodb/presto#9058]
I would like to work on building a connector from Presto to [Apache Pulsar](https://pulsar.incubator.apache.org/)(incubating), a distributed pub-sub messaging system.

Since Pulsar has similar functionality with Kafka, I would start by imitating Presto-Kafka. I guess the key problem I need to resolve is how to split the messaging queue into multiple splits effectively. 

The current official reader impl in Pulsar only supports to read over the non-partitioned queue. I would start with the non-partitioned queue support first.

**Comment by Yaliang** [comment]
+cc @kramasamy @dabaitu

**Comment by kramasamy** [comment]
+mmerli

**Comment by Yaliang** [comment]
@merlimat Do you have any suggestion on how to launch a testing pulsar cluster? I basically got too many dependency conflicts. 🤐

**Comment by merlimat** [comment]
What kind of conflicts are you getting?

Do you mean a distributed cluster or just a standalone? 

For standalone it's very easy you can run it: 
 * Locally http://pulsar.apache.org/docs/latest/getting-started/LocalCluster/ 
 * Within a docker container: http://pulsar.apache.org/docs/latest/getting-started/docker/

A cluster deployment is a bit more involved, though we have instructions for both bare-metal and Kubernetes deployments: http://pulsar.apache.org/docs/latest/deployment/Kubernetes/

**Comment by Yaliang** [comment]
Oh, actually I mean how to launch a testing pulsar cluster for unit tests. Like [this](https://github.com/prestodb/presto/blob/master/presto-kafka/src/test/java/com/facebook/presto/kafka/util/EmbeddedKafka.java) for presto-kafka.

**Comment by merlimat** [comment]
Got it. take a look at https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerTestBase.java 

and example of how we use it in tests: 

https://github.com/apache/incubator-pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SubscriptionSeekTest.java

That will spin up a single node broker, with client instance already created as well, with the ZooKeeper & BookKeeper layers mocked and just implemented in memory.

**Comment by merlimat** [comment]
@Yaliang these classes are in the `org.apache.pulsar:pulsar-broker` artifacts with classifier `test`

**Comment by Yaliang** [comment]
Reading my mind. I was commenting how to refer those classes. Thanks!

**Comment by Yaliang** [comment]
@merlimat It's actually `tests` 🤐  I guess that's why I missed it initially.

**Comment by Yaliang** [comment]
@merlimat I actually discovered the dependency issue is more critical than I thought.

The pulsar client has dependency on `com.google.guava:guava:jar:15.0` but 21.0 was expected by most other presto components and some methods referred by pulsar client was not existing in 21.0 version.

Here is the full story. 
I used the mocked broker you mentioned for testing and initially used a direct dependency to build an testing instance. Then I discovered that the mocked broker is referring some non-existing method in guava. I have initially believed the problem of dependency is only on broker side. So I shaded some related dependencies with `org.apache.pulsar:pulsar-broker:tests` into a side module called `presto-pulsar-testing-server` for building a testing pulsar cluster and make the dependency `pulsar-client` as `provided` (because `presto-pulsar-testing-server` should only be used by `presto-pulsar` module and it includes the `pulsar-client` dependency as a direct dependency).
Unfortunately, I got the following error:
```
[ERROR] testTopicHasData(com.facebook.presto.pulsar.TestMinimalFunctionality)  Time elapsed: 0.068 s  <<< FAILURE!
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at org.apache.pulsar.client.impl.HttpClient.get(HttpClient.java:164)
	at org.apache.pulsar.client.impl.HttpLookupService.getPartitionedTopicMetadata(HttpLookupService.java:84)
	at org.apache.pulsar.client.impl.PulsarClientImpl.getPartitionedTopicMetadata(PulsarClientImpl.java:452)
	at org.apache.pulsar.client.impl.PulsarClientImpl.createProducerAsync(PulsarClientImpl.java:167)
	at org.apache.pulsar.client.impl.PulsarClientImpl.createProducer(PulsarClientImpl.java:115)
	at com.facebook.presto.pulsar.TestingPulsarServer.createProducer(TestingPulsarServer.java:39)
	at com.facebook.presto.pulsar.TestMinimalFunctionality.createMessages(TestMinimalFunctionality.java:85)
	at com.facebook.presto.pulsar.TestMinimalFunctionality.testTopicHasData(TestMinimalFunctionality.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
So, actually the `pulsar-client` is also using some removed methods in guava 21.0. You can see the method `sameThreadExecutor` was remove in 21.0 version:
https://google.github.io/guava/releases/20.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html#sameThreadExecutor--
vs
https://google.github.io/guava/releases/21.0/api/docs/com/google/common/util/concurrent/MoreExecutors.html

Do you have any suggestion for next step? Should we fix it on pulsar side?

My working branch is here -> https://github.com/Yaliang/presto/tree/yaliangw/oss/presto-pulsar

**Comment by findepi** [comment]
> The pulsar client has dependency on com.google.guava:guava:jar:15.0

That's 4 years old already. If pulsar client is a library, this means a big problem to all the pulsar users wanting up-to-date Guava, doesn't it?
Guava had policy for time-limited backwards compatibility and you either keep upgrading or _whooops_. They seem to have changed this policy with Guava 21 _onwards_.
(https://github.com/google/guava/wiki/PhilosophyExplained#non-beta-apis)
