### ISSUE TITLE
Compiler Error for extremely complex field 

### ISSUE THREAD

**Issue by Yaliang** [prestodb/presto#9062]
```
presto:tweetsource> describe unhydrated;
  Column  |                                                                                                                                                                          
----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 event    | row(create_event row(tweet row(id bigint, core_data row(user_id bigint, text varchar, created_via varchar, created_at_secs bigint, .... total 78286 characters
 datehour | varchar                                                                                                                                                                  
(2 rows)

presto:tweetsource> select event.create_event.tweet.id from unhydrated where datehour='2017092700' limit 1

Query 20170928_010923_00026_rryd9, FAILED, 5 nodes
Splits: 110 total, 108 done (98.18%)
0:13 [847 rows, 2.14MB] [67 rows/s, 175KB/s]

Query 20170928_010923_00026_rryd9 failed: Compiler failed and interpreter is disabled

com.facebook.presto.spi.PrestoException: Compiler failed and interpreter is disabled
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1101)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:995)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:576)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:92)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:618)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitOutput(LocalExecutionPlanner.java:576)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:82)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:378)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner.plan(LocalExecutionPlanner.java:310)
	at com.facebook.presto.execution.SqlTaskExecution.<init>(SqlTaskExecution.java:162)
	at com.facebook.presto.execution.SqlTaskExecution.createSqlTaskExecution(SqlTaskExecution.java:121)
	at com.facebook.presto.execution.SqlTaskExecutionFactory.create(SqlTaskExecutionFactory.java:71)
	at com.facebook.presto.execution.SqlTask.updateTask(SqlTask.java:309)
	at com.facebook.presto.execution.SqlTaskManager.updateTask(SqlTaskManager.java:335)
	at com.facebook.presto.server.TaskResource.createOrUpdateTask(TaskResource.java:128)
	at sun.reflect.GeneratedMethodAccessor779.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:395)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1182)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:523)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.presto.spi.PrestoException: COMPILER_ERROR
	at com.facebook.presto.sql.gen.PageFunctionCompiler.compileProjection(PageFunctionCompiler.java:133)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Collections$2.tryAdvance(Collections.java:4717)
	at java.util.Collections$2.forEachRemaining(Collections.java:4725)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.gen.ExpressionCompiler.compilePageProcessor(ExpressionCompiler.java:106)
	at com.facebook.presto.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:1088)
	... 68 more
Caused by: java.lang.IllegalArgumentException: undefined
	at org.objectweb.asm.ByteVector.putUTF8(Unknown Source)
	at org.objectweb.asm.ClassWriter.newUTF8(Unknown Source)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.ClassWriter.newNameType(Unknown Source)
	at org.objectweb.asm.ClassWriter.a(Unknown Source)
	at org.objectweb.asm.MethodWriter.visitInvokeDynamicInsn(Unknown Source)
	at com.facebook.presto.bytecode.instruction.InvokeInstruction$InvokeDynamicInstruction.accept(InvokeInstruction.java:402)
	at com.facebook.presto.bytecode.expression.BytecodeExpression.accept(BytecodeExpression.java:226)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.expression.BytecodeExpression.accept(BytecodeExpression.java:226)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.control.IfStatement.accept(IfStatement.java:125)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.BytecodeBlock.accept(BytecodeBlock.java:938)
	at com.facebook.presto.bytecode.MethodDefinition.visit(MethodDefinition.java:252)
	at com.facebook.presto.bytecode.MethodDefinition.visit(MethodDefinition.java:213)
	at com.facebook.presto.bytecode.ClassDefinition.visit(ClassDefinition.java:167)
	at com.facebook.presto.bytecode.CompilerUtils.defineClasses(CompilerUtils.java:100)
	at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:73)
	at com.facebook.presto.bytecode.CompilerUtils.defineClass(CompilerUtils.java:79)
	at com.facebook.presto.sql.gen.PageFunctionCompiler.compileProjection(PageFunctionCompiler.java:130)
	... 78 more
```

**Comment by mikys-next-insurance** [comment]
I also bumped into this error - 
`SQL Error [65543]: Query failed (#20200706_064520_00021_9swc5): Compiler failed`
because of a very complicated field.
Would appreciate if you can reopen this
