### ISSUE TITLE
PrestoS3FileSystem passing null bucket when actual bucket name contains an underscore

### ISSUE THREAD

**Issue by avirtuos** [prestodb/presto#9085]
When attempting to query data stored in an S3 bucket whose name contains an underscore, the query fails with the below error. After attaching a debugger and tracing the execution it seems that the root cause is the fact that URI uses ‘_’ (among other chars) as a signal character that distinguishes between URIs that are host vs. registry based. Presto’s PrestoS3FileSystem then assumes all S3 URIs are host based resulting in a null being passed to the S3 client when calling operations against buckets containing an ‘_’ in the bucket name. Normally this isn't an issue because you can only create buckets with an '_' when using the aws cli and the us-east-1 region. 

[PrestoS3FileSystem.java:479](https://github.com/prestodb/presto/blob/0707f2f21a96d2fd30953fb3fa9a9a03f03d88bd/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3FileSystem.java#L479) is one example where the URI.getHost() assumption is made. You can also see where URI treats authorities with '_' differently [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/net/URI.java#3119).

```
com.facebook.presto.spi.PrestoException: The bucket name parameter must be specified when listing objects in a bucket
	at com.facebook.presto.hive.HiveSplitSource.propagatePrestoException(HiveSplitSource.java:137)
	at com.facebook.presto.hive.HiveSplitSource.isFinished(HiveSplitSource.java:115)
	at com.facebook.presto.split.ConnectorAwareSplitSource.isFinished(ConnectorAwareSplitSource.java:62)
	at com.facebook.presto.execution.scheduler.SourcePartitionedScheduler.schedule(SourcePartitionedScheduler.java:119)
	at com.facebook.presto.execution.scheduler.SqlQueryScheduler.schedule(SqlQueryScheduler.java:347)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: The bucket name parameter must be specified when listing objects in a bucket
	at com.amazonaws.services.s3.AmazonS3Client.rejectNull(AmazonS3Client.java:3302)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:857)
	at com.facebook.presto.hive.PrestoS3FileSystem.lambda$doListRequestWIthRetry$0(PrestoS3FileSystem.java:565)
	at com.facebook.presto.hive.RetryDriver.run(RetryDriver.java:146)
	at com.facebook.presto.hive.PrestoS3FileSystem.doListRequestWIthRetry(PrestoS3FileSystem.java:565)
	at com.facebook.presto.hive.PrestoS3FileSystem.listPrefix(PrestoS3FileSystem.java:545)
	at com.facebook.presto.hive.PrestoS3FileSystem.access$000(PrestoS3FileSystem.java:108)
	at com.facebook.presto.hive.PrestoS3FileSystem$1.<init>(PrestoS3FileSystem.java:300)
	at com.facebook.presto.hive.PrestoS3FileSystem.listLocatedStatus(PrestoS3FileSystem.java:298)
	at com.facebook.presto.hadoop.HadoopFileSystem.listLocatedStatus(HadoopFileSystem.java:30)
	at com.facebook.presto.hive.HadoopDirectoryLister.list(HadoopDirectoryLister.java:32)
	at com.facebook.presto.hive.util.HiveFileIterator.getLocatedFileStatusRemoteIterator(HiveFileIterator.java:108)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:81)
	at com.facebook.presto.hive.util.HiveFileIterator.computeNext(HiveFileIterator.java:39)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:226)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:77)
	at com.facebook.presto.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:178)
	at com.facebook.presto.hive.util.ResumableTasks.safeProcessTask(ResumableTasks.java:45)
	at com.facebook.presto.hive.util.ResumableTasks.lambda$submit$1(ResumableTasks.java:33)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:77)
	... 3 more
```

**Comment by avirtuos** [comment]
I've submitted a pull request ([PR #9086](https://github.com/prestodb/presto/pull/9086)) with a proposed fix for this issue.

**Comment by nezihyigitbasi** [comment]
Yes, underscores are supported in us-east-1, but I don't think it's recommended (see [docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)). Also I haven't seen this becoming a serious problem for anyone so far.

**Comment by avirtuos** [comment]
Hi Nezih,

Thanks for the quick reply. I agree, it is a relatively narrow use-case. Unfortunately I have seen more than a few people run into this lately and spend hours troubleshooting it before escalting. The [documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)  does say underscores are supported and in my opinion doesn't really discourage it's use. I also find that people using the cli won't necessarily check the documentation for naming conventions, they typically attempt to create a bucket and only check the documentation if they encounter an issue.

From the S3 documentation link you provided:
> The rules for bucket names in the US East (N. Virginia) Region allow bucket names to be as long as 255 characters, and bucket names can contain any combination of uppercase letters, lowercase letters, numbers, periods (.), hyphens (-), and underscores (_).  

Given that the change proposed in PR #9086 is self-contained within a class that already handles nuances of S3 and is unlikely to contribute to unforeseen regressions, do you feel accommodating this case would be problematic? I'm open to alternative solutions if you feel there is a more appropriate route for addressing this edge-case.

**Comment by nezihyigitbasi** [comment]
I got the impression that it's not recommended, because it says in the doc:

>> We recommend that all bucket names comply with DNS naming conventions.

The doc also specifies the rules for DNS-compliant bucket names, and "_" is not listed as DNS-compliant.

It also says

>> While the US East (N. Virginia) Region currently allows non-compliant DNS bucket naming, we are moving to the same DNS-compliant bucket naming convention for the US East (N. Virginia) Region in the coming months.

**Comment by avirtuos** [comment]
I believe that is only a concern if you plan on using [VirtualHosting](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html) for your bucket. I don't believe DNS compliant bucket names matter to customers using the S3 SDK as this complexity is hidden from them. If you plan to make your bucket world readable and access your S3 bucket directly from a browser or cli tool like curl then yes, DNS compliant buckets are a must.

I also think it is not recommended because maintaining us-east-1 as a special case probably doesn't make sense in the long term but I'm not aware of any specific plan to migrating existing, non-compliant, buckets.

**Comment by avirtuos** [comment]
Fix has been merged and will appear in future release. Closing this issue.
