### ISSUE TITLE
NPE when running describe query on cassandra

### ISSUE THREAD

**Issue by trtg** [prestodb/presto#9104]
I'm trying query span data from jaeger which is in cassandra. Doing 
describe traces;
throws this exception:
`
presto:jaeger_v1_datacenter1> describe traces;
Query 20171005_211401_00010_dc4qn failed: null
java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
        at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38)
        at com.google.common.collect.ImmutableList.of(ImmutableList.java:93)
        at com.facebook.presto.cassandra.NativeCassandraSession.buildColumnHandle(NativeCassandraSession.java:315)
        at com.facebook.presto.cassandra.NativeCassandraSession.getTable(NativeCassandraSession.java:232)
        at com.facebook.presto.cassandra.CassandraMetadata.getTableHandle(CassandraMetadata.java:103)
        at com.facebook.presto.cassandra.CassandraMetadata.getTableHandle(CassandraMetadata.java:65)
        at com.facebook.presto.metadata.MetadataManager.getTableHandle(MetadataManager.java:285)
        at com.facebook.presto.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:305)
        at com.facebook.presto.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowColumns(ShowQueriesRewrite.java:150)
        at com.facebook.presto.sql.tree.ShowColumns.accept(ShowColumns.java:54)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:147)
        at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:51)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:69)
        at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:351)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

`

The schema of the traces table is:
`
CREATE TABLE jaeger_v1_datacenter1.traces (
    trace_id blob,
    span_id bigint,
    span_hash bigint,
    duration bigint,
    flags int,
    logs list<frozen<log>>,
    operation_name text,
    parent_id bigint,
    process frozen<process>,
    refs list<frozen<span_ref>>,
    start_time bigint,
    tags list<frozen<keyvalue>>,
    PRIMARY KEY (trace_id, span_id, span_hash)
) WITH CLUSTERING ORDER BY (span_id ASC, span_hash ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'HOURS', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 259200
    AND gc_grace_seconds = 10800
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = 'NONE';

`
and I can query it using cqlsh with no issues.

**Comment by ebyhr** [comment]
You're using user defined type in the table and it causes NPE. 
I guess not only `describe` but also other queries (e.g. `SELECT * FROM traces`) fail in presto. Is it right?
