### ISSUE TITLE
ConcurrentModificationException in BridgingHiveMetastore

### ISSUE THREAD

**Issue by afn** [prestodb/presto#9164]
Trying to drop a column from a Hive table with Presto 0.186 throws a ConcurrentModificationException:

```
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.facebook.presto.hive.metastore.BridgingHiveMetastore.dropColumn(BridgingHiveMetastore.java:214)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropColumn(CachingHiveMetastore.java:495)
        at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropColumn(CachingHiveMetastore.java:495)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$dropColumn$9(SemiTransactionalHiveMetastore.java:357)
        at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:743)
        at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:1522)
        at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:177)
        at com.facebook.presto.transaction.TransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(TransactionManager.java:577)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
        at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
        at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

The table in question looks like this:

```
presto> SHOW CREATE TABLE hive.default.posts;
CREATE TABLE hive.default.posts (
  user_id_dup varchar,
  title varchar,
  body varchar,
  foo integer,
  user_id varchar
)
WITH (
  external_location = 's3a://my-s3-bucket/posts',
  format = 'ORC',
  partitioned_by = ARRAY['user_id']
)
```

And I'm trying to drop the column `foo`. (`ALTER TABLE hive.default.posts DROP COLUMN foo`)

**Comment by electrum** [comment]
This code should be modified as follows:

* Call `deepCopy()` for the `Table` object, as we shouldn't be modifying the original object (there might be other references).
* Use an iterator and call `remove()` on the iterator rather than modifying the list while iterating (which is not safe).

**Comment by ttogola** [comment]
I can do this, let me give it a shot

**Comment by findepi** [comment]
> Trying to drop a column from a Hive table with Presto 0.186 throws a ConcurrentModificationException:

This very problem was fixed in https://github.com/prestodb/presto/pull/9750. Should we close the issue?

**Comment by afn** [comment]
Thanks! Looks like #9750 did indeed address the issue. Closing.
