### ISSUE TITLE
alter table drop column failed with hiveConnector

### ISSUE THREAD

**Issue by cherishDWJ** [prestodb/presto#9177]
I create a table with this code :
`create table hive.dmp.aa(col1 int,col2 int,cole3 int);`
when I alter table to drop column with exception
`Query 20171019_102700_00519_dq8x9 failed: null` for the first time, and I change the column name it will be succeeded
I use the presto with version 0.184,and the hive version is 1.2.1

```
presto:dmp> create table hive.dmp.aa(col1 int,col2 int,cole3 int);
CREATE TABLE
presto:dmp> alter table hive.dmp.aa drop column col1;
Query 20171019_102746_00524_dq8x9 failed: null

presto:dmp> alter table hive.dmp.aa drop column col1;
Query 20171019_104431_00529_dq8x9 failed: null

presto:dmp> alter table hive.dmp.aa drop column col1;
Query 20171019_104433_00530_dq8x9 failed: null

presto:dmp> alter table hive.dmp.aa drop column col1;
Query 20171019_104434_00531_dq8x9 failed: null

presto:dmp> alter table hive.dmp.aa drop column col2;
DROP COLUMN
presto:dmp> alter table hive.dmp.aa drop column col1;
DROP COLUMN
presto:dmp> 
```
The log:

```
java.util.ConcurrentModificationException: undefined
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.facebook.presto.hive.metastore.BridgingHiveMetastore.dropColumn(BridgingHiveMetastore.java:214)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropColumn(CachingHiveMetastore.java:572)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropColumn(CachingHiveMetastore.java:572)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$dropColumn$9(SemiTransactionalHiveMetastore.java:357)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:743)
	at com.facebook.presto.hive.HiveMetadata.commit(HiveMetadata.java:1517)
	at com.facebook.presto.hive.HiveConnector.commit(HiveConnector.java:177)
	at com.facebook.presto.transaction.TransactionManager$TransactionMetadata$ConnectorTransactionMetadata.commit(TransactionManager.java:577)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:111)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:58)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:75)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lvijay** [comment]
can you ask this question on the presto-users group?  it's not a bug or a feature request.

in your case, it looks like the hive metastore isn't updated after you update the schema and hence the issue.  but https://groups.google.com/forum/#!forum/presto-users is the place to ask.

**Comment by cherishDWJ** [comment]
OK. Thank you!
