### ISSUE TITLE
Error reading MapType fields from Parquet files written using legacy Map group annotations

### ISSUE THREAD

**Issue by avirtuos** [prestodb/presto#9192]
# Problem

Customers attempting to query data written in parquet by certain versions of Spark (or any number apps using legacy parquet implementations) may encounter the following error when attempting to read Map fields using Presto 0.172 (I did not confirm exactly when this regressed but it does seem like this changed some time after 0.152)

```json
com.facebook.presto.spi.PrestoException: Index (0) is greater than or equal to list size (0)
                at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:225)
                at com.facebook.presto.hive.HivePageSource.getNextPage(HivePageSource.java:204)
                at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:256)
                at com.facebook.presto.operator.Driver.processInternal(Driver.java:303)
                at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:234)
                at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:537)
                at com.facebook.presto.operator.Driver.processFor(Driver.java:229)
                at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
                at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:654)
                at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:808)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index (0) is greater than or equal to list size (0)
                at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:217)
                at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:220)
                at com.facebook.presto.hive.parquet.reader.ParquetReader.readMap(ParquetReader.java:194)
                at com.facebook.presto.hive.parquet.ParquetPageSource.getNextPage(ParquetPageSource.java:201)
                ... 12 more
```

This is because of a loosely enforced and therefore ambiguous aspect of of how Parquet defines the schema for map group annotations. Pratik found the following documentation for this quirk: https://github.com/apache/parquet-format/blob/master/LogicalTypes.md but the relevant excerpt is below:

### Parquet Map Group Annotation - Legacy Format

It is required that the repeated group of key-value pairs is named `key_value`
and that its fields are named `key` and `value`. However, these names may not
be used in existing data and should not be enforced as errors when reading.

Some existing data incorrectly used `MAP_KEY_VALUE` in place of `MAP`. For
backward-compatibility, a group annotated with `MAP_KEY_VALUE` that is not
contained by a `MAP`-annotated group should be handled as a `MAP`-annotated
group.

Examples that can be interpreted using these rules:

```
// Map<String, Integer> (nullable map, non-null values)
optional group my_map (MAP) {
  repeated group map {
    required binary str (UTF8);
    required int32 num;
  }
}

// Map<String, Integer> (nullable map, nullable values)
optional group my_map (MAP_KEY_VALUE) {
  repeated group map {
    required binary key (UTF8);
    optional int32 value;
  }
}
```

#Steps To Reproduce

##Generating an Impacted Parquet File

Start a cluster with Spark 1.16 and run the following at the spark-shell. I've also attached a sample parquet file generated using the below code and random data.

```scala
	import org.apache.spark.sql.types.{StructType, StructField, MapType, StringType, IntegerType}
	import org.apache.spark.sql.Row
	import org.apache.spark.sql.SaveMode
        val DataFile = sc.textFile("s3a://test-bucket/input/file2.csv")
        val fact_recs = DataFile.map(_.split(","))
        fact_recs.collect().foreach(m => println("one: " + m(0) + "   two: " + m(1)))

	val factSchemaFields = new Array[StructField](3)
	factSchemaFields(0) = new StructField("col0", StringType, false)
	factSchemaFields(1) = new StructField("col1", StringType, false)
	factSchemaFields(2) = new StructField("mcol0", MapType(StringType, StringType, true), false)
	val factSchema = new StructType(factSchemaFields)

        val records = fact_recs.map(p => Row(p(0),p(1),(Map("fname" -> "Al", "lname" -> "Alexander", "col0" -> p(0), "col1" -> p(1)))))
        records.collect().foreach(m => println(m))

        val df = sqlContext.createDataFrame(records, factSchema)
        df.registerTempTable("fact")

	val results = sqlContext.sql("select * from fact")
        results.collect.foreach(m=>println(m.get(2).asInstanceOf[Map[String,String]]("col1")))

        results.coalesce(1).write.mode(SaveMode.Overwrite).parquet("s3a://test-bucket/output/file2.parquet")

	val parquetFileDF = sqlContext.read.parquet("s3a://test-bucket/output/file2.parquet/")

        parquetFileDF.collect().foreach(m => println(m.get(2).asInstanceOf[Map[String,String]]("lname")))
```

**Comment by avirtuos** [comment]
I have a PR ready to submit for review for this issue. I'm just waiting for internal review and testing to complete before I post it. I'll update in the next day or two.
