### ISSUE TITLE
mongodb-we do not need "list databases"

### ISSUE THREAD

**Issue by johnnypenggg** [prestodb/presto#9210]
The catalog configure as below:

mongodb.seeds=locahost:3717
mongodb.credentials=username111:password222@stats

Here we have point out the database is "stats", and the account do not have permission to list databases, and we do not need "list databases"

so the question is how to configure to access database "stats" whithout list all databases???

error as bellow:
com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on admin to execute command { listDatabases: 1 }' on server localhost:3717. The full response is { "ok" : 0.0, "errmsg" : "not authorized on admin to execute command { listDatabases: 1 }", "code" : 13 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:86)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:119)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:260)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:147)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:166)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:157)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:82)
	at com.mongodb.operation.ListDatabasesOperation$1.call(ListDatabasesOperation.java:103)
	at com.mongodb.operation.ListDatabasesOperation$1.call(ListDatabasesOperation.java:100)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:196)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:169)
	at com.mongodb.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:100)
	at com.mongodb.operation.ListDatabasesOperation.execute(ListDatabasesOperation.java:52)
	at com.mongodb.Mongo.execute(Mongo.java:760)
	at com.mongodb.Mongo$2.execute(Mongo.java:747)
	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
	at com.mongodb.ListDatabasesIterableImpl.iterator(ListDatabasesIterableImpl.java:57)
	at com.mongodb.MappingIterable.iterator(MappingIterable.java:36)
	at com.mongodb.MappingIterable.iterator(MappingIterable.java:24)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:229)
	at com.facebook.presto.mongodb.MongoSession.getAllSchemas(MongoSession.java:132)
	at com.facebook.presto.mongodb.MongoMetadata.listSchemaNames(MongoMetadata.java:72)
	at com.facebook.presto.metadata.MetadataManager.listSchemaNames(MetadataManager.java:268)
	at com.facebook.presto.metadata.MetadataListing.listSchemas(MetadataListing.java:57)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildSchemata(InformationSchemaPageSourceProvider.java:254)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:153)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:138)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:96)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:259)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by miniway** [comment]
what query did you execute? Presto might need list of database to run certain types of queries.

**Comment by johnnypenggg** [comment]
like: "show schema from stats;" will cause the error;

"select recordType from stats.stats.ARB limit 5;" will throw error: "Column 'recordtype' cannot be resolved"

**Comment by johnnypenggg** [comment]
@miniway "mongodb.credentials=username111:password222@stats" should have tell the system we want just database  "stats", it's not need list;

**Comment by miniway** [comment]
Presto usually builds whole shape of databases and tables for `show` types of queries even if they only try to access single table. So you need to use other credentials that can use `{listDatabases}`

The word `admin` comes from MongoDB server. I think the error message means `(account username1111 is) not authorized on admin (permission) to execute command { listDatabases: 1 }`

Also I was too busy or lazy to handle the last part of MongoDB case sensitive PR, https://github.com/prestodb/presto/pull/6993 
If you want to use mixed-case identifiers, you should wait or merge the PR on your repo manually.

**Comment by johnnypenggg** [comment]
Thanks:)
