### ISSUE TITLE
Improve error message when failing to cast to decimal

### ISSUE THREAD

**Issue by wenleix** [prestodb/presto#9224]
```
presto> select cast(x AS decimal) from (values '') as t(x);

Query 20171026_174942_55111_ivxzb failed: null
java.lang.NumberFormatException
        at java.math.BigDecimal.<init>(BigDecimal.java:596)
        at java.math.BigDecimal.<init>(BigDecimal.java:383)
        at java.math.BigDecimal.<init>(BigDecimal.java:806)
        at com.facebook.presto.type.DecimalCasts.varcharToLongDecimal(DecimalCasts.java:583)
        at com.facebook.presto.$gen.PageProjectionOutput_20171026_174942_55111_ivxzb_0_95_176415.evaluate(Unknown Source)
        at com.facebook.presto.$gen.PageProjectionOutput_20171026_174942_55111_ivxzb_0_95_176415.compute(Unknown Source)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.processBatch(PageProcessor.java:275)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:180)
        at com.facebook.presto.operator.project.PageProcessor$PositionsPageProcessorIterator.computeNext(PageProcessor.java:126)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
        at com.facebook.presto.operator.project.PageProcessorOutput.hasNext(PageProcessorOutput.java:49)
        at com.facebook.presto.operator.FilterAndProjectOperator.isFinished(FilterAndProjectOperator.java:71)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:334)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by electrum** [comment]
I filed one with more detail: #9225

It's not just a display issue since it prevents `try()` from working (though `try_cast()` works due to how it's implemented).
