### ISSUE TITLE
Is strict config checking really needed?

### ISSUE THREAD

**Issue by richardxin** [prestodb/presto#9254]
A strict config check was added in this commit https://github.com/prestodb/presto/commit/defabcba4e1b89d5df536da51258cfdbfea906cb#diff-fc7374097aa800bd529f476b35716019
Any unrecognized config will throw exception here: 
https://github.com/prestodb/presto/blob/431f8701899145a62ab51a30d0b6ef9fe139dd76/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDriverUri.java#L292

This was causing issue when we trying to integrate presto into Zeppelin 0.7.2

java.sql.SQLException: Unrecognized connection property 'url'
	at com.facebook.presto.jdbc.PrestoDriverUri.validateConnectionProperties(PrestoDriverUri.java:292)
	at com.facebook.presto.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:89)
	at com.facebook.presto.jdbc.PrestoDriverUri.<init>(PrestoDriverUri.java:79)
	at com.facebook.presto.jdbc.PrestoDriver.connect(PrestoDriver.java:86)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.apache.commons.dbcp2.DriverManagerConnectionFactory.createConnection(DriverManagerConnectionFactory.java:79)
	at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:205)
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:836)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:434)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361)
	at org.apache.commons.dbcp2.PoolingDriver.connect(PoolingDriver.java:129)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.getConnectionFromPool(JDBCInterpreter.java:354)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.getConnection(JDBCInterpreter.java:372)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.executeSql(JDBCInterpreter.java:565)
	at org.apache.zeppelin.jdbc.JDBCInterpreter.interpret(JDBCInterpreter.java:692)
	at org.apache.zeppelin.interpreter.LazyOpenInterpreter.interpret(LazyOpenInterpreter.java:97)
	at org.apache.zeppelin.interpreter.remote.RemoteInterpreterServer$InterpretJob.jobRun(RemoteInterpreterServer.java:498)
	at org.apache.zeppelin.scheduler.Job.run(Job.java:175)
	at org.apache.zeppelin.scheduler.ParallelScheduler$JobRunner.run(ParallelScheduler.java:162)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by richardxin** [comment]
The way zeppelin to connect to presto is via generic JDBC interpreter, it would be ideal if presto has a switch to turn on/off strict property checking, and ignore unsupported properties if strict is set to off.

**Comment by richardxin** [comment]
btw, Zeppelin 0.7.2 works well with Presto 0.170, but Presto 0.18x breaks it. "strict config checking" somehow breaks backward compatibility imo.

**Comment by vloup** [comment]
I am the author of the Zeppelin issue on Jira. I do not think that giving the option to disable strict checking is a good idea. As far as I know, Zeppelin is the only tool that got impacted by this change, and it is definitely a bug on their end when they provide extra arguments to all jdbcs. If you do not use recent features used in version 0.180 and later, you can still use an older jdbc right now without any problems from what I recall. I have not tested if the teradata jdbc driver is strict on provided properties, but it is also worth to give it a try. Right now, I just deploy a custom presto-jdbc jar file which is patched to disable strict checking.

I prefer a system that fails and tell you exactly what the problem is than a system that will not behave correctly and let you play the cat and mouse game to find what is wrong. I also *think* that the jdbc spec allows you to be strict.

The example of `SSK=true` seems good, but you'd need to screw up the port number as well, but the idea is totally correct.

I've submitted a workaround a diff on Jira, but I have not made any integration tests.

**Comment by richardxin** [comment]
well, since zeppelin uses generic JDBC interpreter for presto, extra arguments are somehow inevitable, unless zeppelin creates specific interpreter for each jdbc sources.
A "strict config checking" could be "on" by default, people could turn it off to handle compatibility issues like this.
Anyway, if a newer version breaks the older clients that use the service (without easy workaround such as a switch), that sounds a compatibility bug to me.

**Comment by vloup** [comment]
A compatibility issue? Most certainly, but I do not agree with your solution of the problem.

Let us not create a problem that does not exist in the first place: which JDBCs do require extra arguments such as `url` or `driver`? Honestly, if such a library requires you to specify those arguments in the properties, I do have serious doubts of the quality of the underlying code. Concretely, you already use the `driver` argument when loading the JDBC, and `url` when getting a connection object. Both are separate from the properties object:
```
Properties properties = new Properties();
// ...fill up properties with 'user' and 'schema' arguments...

Class.forName("com.facebook.presto.jdbc.PrestoDriver");

Connection connection = DriverManager.getConnection("jdbc:presto://localhost:8080/hive", properties);
```

Back to strict checking, if you need compatibility with buggy softwares, you will soon end up in the infinite loophole of adding workarounds that will gradually rotten your code. It sounds a reasonable idea at first, but it is not a strategy that pays off over the long term. In 5 years, will people ask: "Is this strict checking option *really* used? Who is using this 5 years old version of Zeppelin?".

**Comment by findepi** [comment]
As it has been argued, strict checking was introduced intentionally and is unlikely to be removed.
@richardxin , as a workaround until Zeppelin fixes their JDBC configuration, you can use custom JDBC build that has this check removed.
Hope that helps.

**Comment by srjonemed** [comment]
Hi - could anyone point me to the above mentioned "workaround" ?

**Comment by richardxin** [comment]
I believe what @findepi suggested was that have your own build of presto with removed checking in "presto/presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDriverUri.java".

**Comment by vloup** [comment]
>> I hit some dependency failures during build-tests and I had to -DSkipTest to get the jars built successfully..

It has been quite a while since I wrote this patch but it did not add any dependency back then. I bet it is most likely an issue on your end or on the last code revision. Have you tried to compile the project without applying patches? Pro tip: you can go in the presto-jdbc directory and call mvn there directly.

>> Now the %presto interpreter works from Zeppelin. However on the Presto UI i see "GENERIC_INTERNAL_ERROR (65536)" for all queries (even though on Zeppelin I could see my queries fetching results fine).

We were on top of Hadoop, not MySQL, so our setup was different. Maybe the patch did not apply well and it broke something, I'll need to have a look if I can find the time for it. That error stack is fishy...

Last rebase was *quite* some time ago (I had pushed it on a fork at https://github.com/vloup/presto/tree/presto-jdbc-properties-validation , but stopped to update it after my internship). Maybe building this old version might be worth a shot?

**Comment by gabrielrcouto** [comment]
Thank you @vloup for the patch, I applied on Presto 0.225 and it worked very well with Zeppelin 0.8.1. If someone want to use, I uploaded here: https://github.com/gabrielrcouto/presto/releases
