### ISSUE TITLE
hive struct type  empty ,query NPE

### ISSUE THREAD

**Issue by zhaiyuyong** [prestodb/presto#9262]
```sql
CREATE TABLE `temp_ai.cx_temp_12`(
  `team_id` bigint, 
  `taker_id` bigint, 
  `_c2` struct<>)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.columnar.LazyBinaryColumnarSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.RCFileInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.RCFileOutputFormat'
LOCATION
  '/xxxx/cx_temp_12'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='{\"BASIC_STATS\":\"true\"}', 
  'numFiles'='1', 
  'numRows'='198799', 
  'rawDataSize'='1638268', 
  'totalSize'='1662034', 
  'transient_lastDdlTime'='1509535346');
```
```sql
select * from temp_ai.cx_temp_12
```
```java
java.lang.NullPointerException: type is null
	at com.facebook.presto.spi.ColumnMetadata.<init>(ColumnMetadata.java:46)
	at com.facebook.presto.hive.HiveMetadata.lambda$columnMetadataGetter$15(HiveMetadata.java:1507)
	at com.facebook.presto.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:275)
	at com.facebook.presto.hive.HiveMetadata.getTableMetadata(HiveMetadata.java:262)
	at com.facebook.presto.spi.connector.classloader.ClassLoaderSafeConnectorMetadata.getTableMetadata(ClassLoaderSafeConnectorMetadata.java:128)
	at com.facebook.presto.metadata.MetadataManager.getTableMetadata(MetadataManager.java:338)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:819)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.Table.accept(Table.java:53)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:1762)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:926)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:267)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:655)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:245)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:257)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:231)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:72)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.sql.analyzer.QueryExplainer.analyze(QueryExplainer.java:88)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:136)
	at com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:100)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.getQueryPlan(ExplainRewrite.java:126)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:104)
	at com.facebook.presto.sql.rewrite.ExplainRewrite$Visitor.visitExplain(ExplainRewrite.java:60)
	at com.facebook.presto.sql.tree.Explain.accept(Explain.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at com.facebook.presto.sql.rewrite.ExplainRewrite.rewrite(ExplainRewrite.java:57)
	at com.facebook.presto.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:51)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:69)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:64)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:351)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:337)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Yaliang** [comment]
We have seen the similar error and implemented a hacky solution (https://github.com/twitter-forks/presto/pull/126) which pulls the `UNKNOWN` type in `presto-main` into the `presto-spi` and automatically inserts an `unknown` field in an empty structural field.  

For our use case, we only use the Parquet and LZO-compressed Thrift. It seems safe because the structural field with empty nested fields in Parquet seems always be transformed into `null` in our pipeline and the Thrift reader we implemented would always return `null` for the (missed) `unknown` field. Feel free to check it out and leave a comment if any problem arises.
