### ISSUE TITLE
Get table's column in MongoDB error

### ISSUE THREAD

**Issue by chdw** [prestodb/presto#9307]
Presto server has a mongodb connector,
MongoDB has a collection named "table_type"

My app use Presto JDBC Driver to connect Presto server.

I can execute SQL "select * from table_type" or "desc table_type" , it work fine.

But I can't use conn.getMetaData().getColumns("mongodb", "northwind", "table_type", "%")

to get columns meta

**Comment by chdw** [comment]
Connection conn = DriverManager.getConnection("jdbc:presto://localhost:30105/mongodb/northwind", "test", "");
		ResultSet rs = conn.getMetaData().getColumns("mongodb", "northwind", "abc_def", "%");

Exception in thread "main" java.sql.SQLException: Query failed (#20171115_032644_00023_q7v98): tableName is null
	at com.facebook.presto.jdbc.PrestoResultSet.resultsException(PrestoResultSet.java:1802)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1790)
	at com.facebook.presto.jdbc.PrestoResultSet$ResultsPageIterator.computeNext(PrestoResultSet.java:1756)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
	at com.facebook.presto.jdbc.internal.guava.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
	at com.facebook.presto.jdbc.internal.guava.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
	at com.facebook.presto.jdbc.internal.guava.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.facebook.presto.jdbc.internal.guava.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.facebook.presto.jdbc.PrestoResultSet.next(PrestoResultSet.java:149)

**Comment by chdw** [comment]
Server Exception

java.lang.NullPointerException: tableName is null
        at com.facebook.presto.spi.SchemaUtil.checkNotEmpty(SchemaUtil.java:25)
        at com.facebook.presto.spi.SchemaTableName.<init>(SchemaTableName.java:33)
        at com.facebook.presto.mongodb.MongoMetadata.listTables(MongoMetadata.java:287)
        at com.facebook.presto.mongodb.MongoMetadata.listTableColumns(MongoMetadata.java:127)
        at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:413)
        at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
        at com.facebook.presto.connector.system.jdbc.ColumnJdbcTable.cursor(ColumnJdbcTable.java:126)
        at com.facebook.presto.connector.system.SystemPageSourceProvider$1.cursor(SystemPageSourceProvider.java:125)
        at com.facebook.presto.split.MappedRecordSet.cursor(MappedRecordSet.java:53)
        at com.facebook.presto.spi.RecordPageSource.<init>(RecordPageSource.java:37)
        at com.facebook.presto.connector.system.SystemPageSourceProvider.createPageSource(SystemPageSourceProvider.java:104)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:219)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
