### ISSUE TITLE
Postgres connector tests started from IDE are locale-dependent

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9313]
When I run `TestPostgreSqlIntegrationSmokeTest`, it fails to initialise:
```
Cannot instantiate class com.facebook.presto.plugin.postgresql.TestPostgresSqlTypeMapping
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:40)
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:363)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:275)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:126)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:191)
	at org.testng.TestClass.getInstances(TestClass.java:100)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:86)
	at org.testng.TestClass.init(TestClass.java:78)
	at org.testng.TestClass.<init>(TestClass.java:41)
	at org.testng.TestRunner.initMethods(TestRunner.java:425)
	at org.testng.TestRunner.init(TestRunner.java:252)
	at org.testng.TestRunner.init(TestRunner.java:222)
	at org.testng.TestRunner.<init>(TestRunner.java:163)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:585)
	at org.testng.SuiteRunner.init(SuiteRunner.java:189)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:136)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1375)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1355)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
	... 22 more
Caused by: java.lang.RuntimeException: io.airlift.command.CommandFailedException: [/var/folders/26/5chf3sqx36960p425jczhh680000gp/T/testing-postgresql-server3455928039788787681/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/26/5chf3sqx36960p425jczhh680000gp/T/testing-postgresql-server3455928039788787681/data, -E, UTF-8] exited with 1
The files belonging to this database system will be owned by user "findepi".
This user must also own the server process.

initdb: invalid locale settings; check LANG and LC_* environment variables

	at io.airlift.testing.postgresql.EmbeddedPostgreSql.system(EmbeddedPostgreSql.java:303)
	at io.airlift.testing.postgresql.EmbeddedPostgreSql.initdb(EmbeddedPostgreSql.java:168)
	at io.airlift.testing.postgresql.EmbeddedPostgreSql.<init>(EmbeddedPostgreSql.java:92)
	at io.airlift.testing.postgresql.TestingPostgreSqlServer.<init>(TestingPostgreSqlServer.java:43)
	at com.facebook.presto.plugin.postgresql.TestPostgresSqlTypeMapping.<init>(TestPostgresSqlTypeMapping.java:44)
	... 27 more
Caused by: io.airlift.command.CommandFailedException: [/var/folders/26/5chf3sqx36960p425jczhh680000gp/T/testing-postgresql-server3455928039788787681/bin/initdb, -A, trust, -U, postgres, -D, /var/folders/26/5chf3sqx36960p425jczhh680000gp/T/testing-postgresql-server3455928039788787681/data, -E, UTF-8] exited with 1
The files belonging to this database system will be owned by user "findepi".
This user must also own the server process.

initdb: invalid locale settings; check LANG and LC_* environment variables

	at io.airlift.command.ProcessCallable.call(ProcessCallable.java:64)
	at io.airlift.command.ProcessCallable.call(ProcessCallable.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

For the record, my env (it might be even incorrect, that's not the point):
```
$ env | grep ^L
LC_CTYPE=UTF-8
```

**Comment by findepi** [comment]
My think is that `EmbeddedPostgreSql` could clear environment (or at least remove all `LANG`, `LC_*` variables from it) when initiating and starting postgres server in the background. `io.airlift.command.Command` would need to support that.

cc @losipiuk

**Comment by findepi** [comment]
Might be fixed by https://github.com/airlift/airbase/pull/98

**Comment by electrum** [comment]
Maybe we should simply set `LANG` and `LC_ALL` to `en_US.UTF-8` in `EmbeddedPostgreSql`?

**Comment by findepi** [comment]
So we have these options:
- https://github.com/airlift/airbase/pull/98
- set `LANG` and `LC_ALL` to `en_US.UTF-8` in `EmbeddedPostgreSql`
- run Postgres in docker instead of unpacking to /tmp 

Any of these would do.

**Comment by findepi** [comment]
https://github.com/airlift/airbase/pull/98 was merged.
