### ISSUE TITLE
INTERVAL types not supported in CAST

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9338]
`CAST(null AS INTERVAL YEAR TO MONTH)`
`CAST(null AS INTERVAL DAY TO SECOND)`
`CAST(null AS INTERVAL HOUR TO SECOND)`
etc.

fail with a parsing error:

```
com.facebook.presto.sql.parser.ParsingException: line 1:30: mismatched input 'day' expecting {'(', ')', 'ARRAY'}
	at com.facebook.presto.sql.parser.SqlParser$1.syntaxError(SqlParser.java:48)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:540)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:301)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:124)
	at com.facebook.presto.sql.parser.SqlBaseParser.type(SqlBaseParser.java:9186)
	at com.facebook.presto.sql.parser.SqlBaseParser.primaryExpression(SqlBaseParser.java:8076)
	at com.facebook.presto.sql.parser.SqlBaseParser.valueExpression(SqlBaseParser.java:6867)
	at com.facebook.presto.sql.parser.SqlBaseParser.predicated(SqlBaseParser.java:6132)
	at com.facebook.presto.sql.parser.SqlBaseParser.booleanExpression(SqlBaseParser.java:6023)
	at com.facebook.presto.sql.parser.SqlBaseParser.expression(SqlBaseParser.java:5767)
	at com.facebook.presto.sql.parser.SqlBaseParser.selectItem(SqlBaseParser.java:4809)
	at com.facebook.presto.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:3906)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3674)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3479)
	at com.facebook.presto.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3330)
	at com.facebook.presto.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2759)
	at com.facebook.presto.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1412)
	at com.facebook.presto.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:234)
	at com.facebook.presto.sql.parser.SqlParser.invokeParser(SqlParser.java:95)
	at com.facebook.presto.sql.parser.SqlParser.createStatement(SqlParser.java:68)
```

**Comment by findepi** [comment]
Same for `CREATE TABLE`:
```
USE memory.default;
CREATE TABLE t(a INTERVAL YEAR TO MONTH);
Query 20171115_215014_00008_d4r5i failed: line 1:27: mismatched input 'YEAR' expecting {'(', ')', ',', 'ARRAY', 'COMMENT'}
```
