### ISSUE TITLE
NPE getting table names from Postgresql

### ISSUE THREAD

**Issue by kstenerud** [prestodb/presto#9367]
postgresql.properties:

````
connector.name=postgresql
connection-url=jdbc:posgresql://localhost/postgres
connection-user=testuser
connection-password=testuser
````

Basic postgresql setup (as user postgres):

````sql
create role testuser superuser login password 'testuser';
create database test with owner testuser;
````

As user testuser:
````sql
create schema test;
set search_path to test,public;
create table a (a0 int, a1 int, a2 int, a3 int, a4 int, a5 int, a6 int, a7 int);
````

Use postgresql client to check:

````bash
psql -U testuser -d test
psql (9.5.10)
Type "help" for help.

test=# select * from test.a;
 a0 | a1 | a2 | a3 | a4 | a5 | a6 | a7 
----+----+----+----+----+----+----+----
(0 rows)
````

Use presto client:

````
/opt/presto/bin/prestoclient --catalog postgresql --schema test
presto:test> select * from a;
Query 20171117_104523_00002_dhb3z failed: null
````

Exception:
````
ERROR	remote-task-callback-0	com.facebook.presto.execution.StageStateMachine	Stage 20171117_104521_00001_dhb3z.1 failed
java.lang.NullPointerException
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getTableNames(BaseJdbcClient.java:151)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.listTables(JdbcMetadata.java:104)
	at com.facebook.presto.metadata.MetadataManager.listTables(MetadataManager.java:396)
	at com.facebook.presto.metadata.MetadataListing.listTables(MetadataListing.java:63)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildTables(InformationSchemaPageSourceProvider.java:196)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:147)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:138)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:96)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:224)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by akshatnair** [comment]
Are you able to run `show catalogs`, `show schemas` and `show tables` commands?

**Comment by geetikagupta16** [comment]
I think you are missing the port number for postgres, it should be like:
 `connection-url=jdbc:postgresql://localhost:5432/<db_name>`
