### ISSUE TITLE
enforceTimeLimits error

### ISSUE THREAD

**Issue by zhaiyuyong** [prestodb/presto#9408]
```java
2017-11-24T10:57:19.014+0800	ERROR	ResourceGroupManager	com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager	Exception while processing queued queries for RootInternalResourceGroup{id=analyst_user_high}
java.lang.IllegalArgumentException: value is negative
	at io.airlift.units.Preconditions.checkArgument(Preconditions.java:26)
	at io.airlift.units.Duration.<init>(Duration.java:63)
	at io.airlift.units.Duration.succinctDuration(Duration.java:53)
	at io.airlift.units.Duration.succinctNanos(Duration.java:48)
	at com.facebook.presto.execution.QueryStats.getExecutionTime(QueryStats.java:272)
	at com.facebook.presto.execution.resourceGroups.InternalResourceGroup.enforceTimeLimits(InternalResourceGroup.java:803)
	at com.facebook.presto.execution.resourceGroups.InternalResourceGroup$RootInternalResourceGroup.processQueuedQueries(InternalResourceGroup.java:935)
	at com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager.refreshAndStartQueries(InternalResourceGroupManager.java:232)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nezihyigitbasi** [comment]
This is possible when the queued time for a query is greater than its elapsed time, do you have more details (its stats would be useful) about the query that's triggering this?

**Comment by zhaiyuyong** [comment]
```java
57cf4f6-975f-469d-b41c-46641b3bead6] :: elapsed 1013ms :: planning 437ms :: scheduling 8ms :: running 189ms :: finishing 379ms :: begin 2017-11-28T15:54:00.725+08:00 :: end 2017-11-
28T15:54:01.738+08:00
2017-11-28T15:54:01.802+0800    INFO    query-execution-931     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075400_79418_765pp=FINISHED:: Transaction:[3
ff5e7a4-5939-4658-b4d9-244617d268e8] :: elapsed 1008ms :: planning 441ms :: scheduling 10ms :: running 221ms :: finishing 336ms :: begin 2017-11-28T15:54:00.726+08:00 :: end 2017-11
-28T15:54:01.734+08:00
2017-11-28T15:54:06.210+0800    INFO    query-execution-922     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075406_79422_765pp=FINISHED:: Transaction:[5
3f08e41-132c-4603-8b72-6a83c3f58624] :: elapsed 140ms :: planning 122ms :: scheduling 9ms :: running 6ms :: finishing 3ms :: begin 2017-11-28T15:54:06.068+08:00 :: end 2017-11-28T15
:54:06.208+08:00
2017-11-28T15:54:06.228+0800    INFO    query-execution-922     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075406_79421_765pp=FINISHED:: Transaction:[0
cabfb11-ec9b-4ea5-b29e-e9f5597bc3d5] :: elapsed 156ms :: planning 125ms :: scheduling 17ms :: running 11ms :: finishing 3ms :: begin 2017-11-28T15:54:06.068+08:00 :: end 2017-11-28T
15:54:06.224+08:00
2017-11-28T15:54:06.266+0800    ERROR   ResourceGroupManager    com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager       Exception while processing queued que
ries for RootInternalResourceGroup{id=ema_analyst_user_high}
java.lang.IllegalArgumentException: value is negative
        at io.airlift.units.Preconditions.checkArgument(Preconditions.java:26)
        at io.airlift.units.Duration.<init>(Duration.java:63)
        at io.airlift.units.Duration.succinctDuration(Duration.java:53)
        at io.airlift.units.Duration.succinctNanos(Duration.java:48)
        at com.facebook.presto.execution.QueryStats.getExecutionTime(QueryStats.java:272)
        at com.facebook.presto.execution.resourceGroups.InternalResourceGroup.enforceTimeLimits(InternalResourceGroup.java:803)
        at com.facebook.presto.execution.resourceGroups.InternalResourceGroup$RootInternalResourceGroup.processQueuedQueries(InternalResourceGroup.java:935)
        at com.facebook.presto.execution.resourceGroups.InternalResourceGroupManager.refreshAndStartQueries(InternalResourceGroupManager.java:232)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


2017-11-28T15:54:06.504+0800    INFO    query-execution-924     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075406_79425_765pp=FINISHED:: Transaction:[2d085c4e-8166-426b-b4e3-019282ea7b4d] :: elapsed 180ms :: planning 149ms :: scheduling 9ms :: running 18ms :: finishing 4ms :: begin 2017-11-28T15:54:06.322+08:00 :: end 2017-11-28T15:54:06.502+08:00
2017-11-28T15:54:06.519+0800    INFO    query-execution-924     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075406_79426_765pp=FINISHED:: Transaction:[6e823cf3-1ee3-4051-9135-9265f2b22e29] :: elapsed 192ms :: planning 159ms :: scheduling 24ms :: running 5ms :: finishing 4ms :: begin 2017-11-28T15:54:06.323+08:00 :: end 2017-11-28T15:54:06.515+08:00
2017-11-28T15:54:06.551+0800    INFO    query-execution-922     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075406_79427_765pp=FINISHED:: Transaction:[84433c2c-4596-4e0d-83b5-7f387929b866] :: elapsed 182ms :: planning 169ms :: scheduling 3ms :: running 4ms :: finishing 6ms :: begin 2017-11-28T15:54:06.366+08:00 :: end 2017-11-28T15:54:06.548+08:00
2017-11-28T15:54:06.558+0800    INFO    query-execution-922     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20171128_075406_79431_765pp=FINISHED:: Transaction:[d4b3e430-a137-42e6-ab50-8fbde98d0929] :: elapsed 183ms :: planning 170ms :: scheduling 6ms :: running 5ms :: finishing 2ms :: begin 2017-11-28T15:54:06.372+08:00 :: end 2017-11-28T15:54:06.555+08:00
