### ISSUE TITLE
It's not possible to query JDBC connector information_schema.columns when there is a table with all unsupported data type columns

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9434]
Steps to reproduce:

1. `create table m (m interval);` in Postgres
1. using `postgresql` connector: `select * from postgresql.information_schema.columns;`

```
Query 20171129_143915_00004_exah8 failed: Table has no supported column types: public.m
com.facebook.presto.spi.PrestoException: Table has no supported column types: public.m
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:227)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.getTableMetadata(JdbcMetadata.java:95)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.listTableColumns(JdbcMetadata.java:136)
	at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:419)
	at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:169)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:144)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:138)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:96)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:259)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
	at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I think a better behavior would be to ignore unsupported columns, just like we do for tables where unsupported columns exist together with supported ones.

**Comment by electrum** [comment]
The real problem here is that a table with no columns is invalid. We should have a check in the engine in `MetadataManager.getTableMetadata()` that fails if no columns, and an additional check in the base-jdbc connector with a better error message like "Table has no supported column types"

**Comment by findepi** [comment]
@electrum we already have this kind of check in base-jdbc, but due to how information_schema is handled, it prevents from listing columns for other tables.

I come up with a different solution, please have a look: #9435

**Comment by findepi** [comment]
@electrum the reason why i didn't want check for valid columns when _listing_ tables is that this would incur significant overhead, especially for a database with multiple tables that have multiple columns.
