### ISSUE TITLE
Java 9 instructions

### ISSUE THREAD

**Issue by georgewfraser** [prestodb/presto#9442]
I wasn't able to find any instructions for getting Presto running on Java 9, and I encountered several errors when I tried to do it. The first problem I found was the a JMX agent failed to attach:

```
com.facebook.presto.server.PrestoServer Unable to create injector, see the following errors:
1) Error injecting constructor, java.io.IOException: Can not attach to current VM
  at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:41)
  at io.airlift.jmx.JmxModule.configure(JmxModule.java:55)
  while locating io.airlift.jmx.JmxAgent9
  while locating io.airlift.jmx.JmxAgent
    for parameter 0 at io.airlift.jmx.JmxModule$JmxAnnouncementProvider.setJmxAgent(JmxModule.java:68)
  while locating io.airlift.jmx.JmxModule$JmxAnnouncementProvider
  while locating io.airlift.discovery.client.ServiceAnnouncement annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=323, type=MULTIBINDER, keyType=)
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:68) (via modules: io.airlift.discovery.client.DiscoveryModule -> com.google.inject.multibindings.Multibinder$RealMulti
binder)
  while locating java.util.Set<io.airlift.discovery.client.ServiceAnnouncement>
    for parameter 1 at io.airlift.discovery.client.Announcer.<init>(Announcer.java:68)
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:63)
  while locating io.airlift.discovery.client.Announcer
    for parameter 1 at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:120)
  at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:120)
  at io.airlift.discovery.client.DiscoveryModule.createMergingServiceSelectorFactory(DiscoveryModule.java:120)
  while locating io.airlift.discovery.client.MergingServiceSelectorFactory
  at io.airlift.discovery.client.DiscoveryModule.configure(DiscoveryModule.java:72)
  while locating io.airlift.discovery.client.ServiceSelectorFactory
    for parameter 0 at io.airlift.discovery.client.ServiceSelectorProvider.setServiceSelectorFactory(ServiceSelectorProvider.java:50)
...many more
```
The solution was to add the flag `-Djdk.attach.allowAttachSelf=true` to `${presto-home}/etc/jvm.config`

The second problem was that MysqlPlugin couldn't find the class SqlException:

```
java.util.ServiceConfigurationError: com.facebook.presto.spi.Plugin: Provider com.facebook.presto.plugin.mysql.MySqlPlugin could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
        at java.base/java.util.ServiceLoader.access$100(ServiceLoader.java:390)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:799)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1389)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:270)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:229)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:163)
        at com.facebook.presto.server.PluginManager.loadPlugin(PluginManager.java:154)
        at com.facebook.presto.server.PluginManager.loadPlugins(PluginManager.java:135)
        at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:118)
        at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.NoClassDefFoundError: java/sql/SQLException
        at com.facebook.presto.plugin.mysql.MySqlPlugin.<init>(MySqlPlugin.java:23)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:777)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: java.sql.SQLException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at com.facebook.presto.server.PluginClassLoader.loadClass(PluginClassLoader.java:76)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 15 more
```

I investigated and it looks like PluginClassLoader is using a null classloader as its parent, which means in Java 9 it can only load things from the `java.base` module. I tried deleting the mysql connector but then ran into other similar `NoClassDefFoundError`s. 

Are there instructions anywhere for running Presto on Java 9?

**Comment by martint** [comment]
Presto doesn't currently run on Java 9. I got it working a few months ago on one of the pre-release versions, but some rules changed that broke that. We need to go through the exercise again now that Java 9 is finally out and stable.

**Comment by georgewfraser** [comment]
Did master run on java 9 pre-release or was it a branch?

**Comment by martint** [comment]
It did at some point.

**Comment by electrum** [comment]
#9469 should fix the class loader issue
