### ISSUE TITLE
Getting "Tried to free more revocable memory than is reserved" randomly when using spill

### ISSUE THREAD

**Issue by vivekgarg20** [prestodb/presto#9488]
Presto Version - 0.188
Here is stacktrace for the error.

```
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.facebook.presto.memory.MemoryPool.freeRevocable(MemoryPool.java:196)
        at com.facebook.presto.memory.QueryContext.freeRevocableMemory(QueryContext.java:168)
        at com.facebook.presto.operator.TaskContext.freeRevocableMemory(TaskContext.java:226)
        at com.facebook.presto.operator.PipelineContext.freeRevocableMemory(PipelineContext.java:274)
        at com.facebook.presto.operator.DriverContext.freeRevocableMemory(DriverContext.java:254)
        at com.facebook.presto.operator.OperatorContext.freeRevocableMemory(OperatorContext.java:315)
        at com.facebook.presto.operator.OperatorContext.setRevocableMemoryReservation(OperatorContext.java:307)
        at com.facebook.presto.operator.HashBuilderOperator.lambda$close$11(HashBuilderOperator.java:644)
        at com.google.common.io.Closer.close(Closer.java:216)
        at com.facebook.presto.operator.HashBuilderOperator.close(HashBuilderOperator.java:645)
        at com.facebook.presto.operator.HashBuilderOperator.finish(HashBuilderOperator.java:450)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:357)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
@vivekgarg20 any particular steps to reproduce? In your case, does it happen for every query when spill is enabled?

**Comment by vivekgarg20** [comment]
@findepi  No, It doesn't happen for every query. It happens randomly and frequently.

**Comment by findepi** [comment]
@vivekgarg20 , i did some code static analysis, and I think I know where the problem lies, but a few clarification questions

1. does it happen for particular query/set of queries? What kind of JOIN is it (inner/left/right/full)?
2. is it first exception for a query (cluster-wide)? I.e. can this be related to an abrupt cleanup during error condition?
3. Can you run with https://github.com/prestodb/presto/pull/9493 included? Is this log being printed _on the worker_ where "Tried to free more revocable memory than is reserved" is originally raised?

**Comment by vivekgarg20** [comment]
@findepi  I did not really find any pattern last time. But now in context of your questions, I will try to reproduce and answer. It will take 4-5 days before I come back to you. Thanks for taking time out and do analysis.

**Comment by vivekgarg20** [comment]
@findepi 
Presto version 0.191
We got same error again.
Type of query - insert into select *, with multiple right and left join. It is getting data from two different mysql DB and joining them and storing it on hive with ORC format.

2017-12-16T15:08:59.281Z	ERROR	Task-20171216_145014_00001_wyk8s.12.2-146	com.facebook.presto.operator.Driver	Error closing operator 1 for task 20171216_145014_00001_wyk8s.12.2
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.operator.TaskContext.freeRevocableMemory(TaskContext.java:259)
	at com.facebook.presto.operator.PipelineContext.freeRevocableMemory(PipelineContext.java:279)
	at com.facebook.presto.operator.DriverContext.freeRevocableMemory(DriverContext.java:257)
	at com.facebook.presto.operator.OperatorContext.freeRevocableMemory(OperatorContext.java:328)
	at com.facebook.presto.operator.OperatorContext.setRevocableMemoryReservation(OperatorContext.java:320)
	at com.facebook.presto.operator.HashBuilderOperator.lambda$close$11(HashBuilderOperator.java:637)
	at com.google.common.io.Closer.close(Closer.java:216)
	at com.facebook.presto.operator.HashBuilderOperator.close(HashBuilderOperator.java:638)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:489)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:660)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:630)
	at com.facebook.presto.operator.Driver.close(Driver.java:165)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:1009)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.destroy(PrioritizedSplitRunner.java:115)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.destroy(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor.doRemoveTask(TaskExecutor.java:278)
	at com.facebook.presto.execution.executor.TaskExecutor.removeTask(TaskExecutor.java:255)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1030)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1014)
	at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2017-12-16T15:08:59.281Z	ERROR	Task-20171216_145014_00001_wyk8s.12.2-146	com.facebook.presto.operator.Driver	Driver still has revocable memory reserved after freeing all operator memory. Freeing it.
2017-12-16T15:08:59.281Z	ERROR	Task-20171216_145014_00001_wyk8s.12.2-146	com.facebook.presto.operator.Driver	Error destroying driver for task 20171216_145014_00001_wyk8s.12.2
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.operator.TaskContext.freeRevocableMemory(TaskContext.java:259)
	at com.facebook.presto.operator.PipelineContext.freeRevocableMemory(PipelineContext.java:279)
	at com.facebook.presto.operator.DriverContext.freeRevocableMemory(DriverContext.java:257)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:537)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:660)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:630)
	at com.facebook.presto.operator.Driver.close(Driver.java:165)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:1009)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.destroy(PrioritizedSplitRunner.java:115)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.destroy(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor.doRemoveTask(TaskExecutor.java:278)
	at com.facebook.presto.execution.executor.TaskExecutor.removeTask(TaskExecutor.java:255)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1030)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1014)
	at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2017-12-16T15:08:59.282Z	ERROR	Task-20171216_145014_00001_wyk8s.12.2-146	com.facebook.presto.operator.Driver	Error closing operator 1 for task 20171216_145014_00001_wyk8s.12.2
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.operator.TaskContext.freeRevocableMemory(TaskContext.java:259)
	at com.facebook.presto.operator.PipelineContext.freeRevocableMemory(PipelineContext.java:279)
	at com.facebook.presto.operator.DriverContext.freeRevocableMemory(DriverContext.java:257)
	at com.facebook.presto.operator.OperatorContext.freeRevocableMemory(OperatorContext.java:328)
	at com.facebook.presto.operator.OperatorContext.setRevocableMemoryReservation(OperatorContext.java:320)
	at com.facebook.presto.operator.HashBuilderOperator.lambda$close$11(HashBuilderOperator.java:637)
	at com.google.common.io.Closer.close(Closer.java:216)
	at com.facebook.presto.operator.HashBuilderOperator.close(HashBuilderOperator.java:638)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:489)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:660)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:630)
	at com.facebook.presto.operator.Driver.close(Driver.java:165)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:1009)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.destroy(PrioritizedSplitRunner.java:115)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.destroy(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor.doRemoveTask(TaskExecutor.java:278)
	at com.facebook.presto.execution.executor.TaskExecutor.removeTask(TaskExecutor.java:255)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1030)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1014)
	at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2017-12-16T15:08:59.282Z	ERROR	Task-20171216_145014_00001_wyk8s.12.2-146	com.facebook.presto.operator.Driver	Driver still has revocable memory reserved after freeing all operator memory. Freeing it.
2017-12-16T15:08:59.282Z	ERROR	Task-20171216_145014_00001_wyk8s.12.2-146	com.facebook.presto.operator.Driver	Error destroying driver for task 20171216_145014_00001_wyk8s.12.2
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.operator.TaskContext.freeRevocableMemory(TaskContext.java:259)
	at com.facebook.presto.operator.PipelineContext.freeRevocableMemory(PipelineContext.java:279)
	at com.facebook.presto.operator.DriverContext.freeRevocableMemory(DriverContext.java:257)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:537)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:660)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:630)
	at com.facebook.presto.operator.Driver.close(Driver.java:165)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.close(SqlTaskExecution.java:1009)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.destroy(PrioritizedSplitRunner.java:115)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.destroy(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor.doRemoveTask(TaskExecutor.java:278)
	at com.facebook.presto.execution.executor.TaskExecutor.removeTask(TaskExecutor.java:255)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1030)
	at com.facebook.presto.execution.SqlTaskExecution$RemoveTaskHandleWhenDone.stateChanged(SqlTaskExecution.java:1014)
	at com.facebook.presto.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by findepi** [comment]
@vivekgarg20 I noticed that the new exception is slightly different from the original one.
Originally reported failed within `MemoryPool`:
```
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
        at com.facebook.presto.memory.MemoryPool.freeRevocable(MemoryPool.java:196)
```
and in your last comment there is a failure in `TaskContext`:
```
java.lang.IllegalArgumentException: tried to free more revocable memory than is reserved
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.operator.TaskContext.freeRevocableMemory(TaskContext.java:259)
```

Which probably means that accounting problem can manifest itself in different places, failure in `TaskContext` means it can happen "within" single query, as task is something scoped to query.

While I still could not reproduce the problem locally, I though there may be some overflow involved (just a hypothesis). Of course, it is not possible to have more memory than can be accounted for on a `long`, however memory accounting can still overflow if:
- actual memory reservations are repeatedly not freed
- there is a bogus memory reservation request asking for way more memory
  than actually used, with a value "close" to `Long.MAX_VALUE` 

@vivekgarg20 , please see https://github.com/prestodb/presto/pull/9690. Would you be able to pull that code and verify the above hypothesis?

**Comment by findepi** [comment]
@vivekgarg20 no need for you to try my earlier PR. 
I could repro now  and https://github.com/prestodb/presto/pull/9725 is a new fix. Hopefully (and most probably) it addresses your situation too.
