### ISSUE TITLE
Improve invalid WKT exception handling

### ISSUE THREAD

**Issue by Lewuathe** [prestodb/presto#9511]
I found invalid WKT throw `IllegalArgumentException` and the query failed `GENERIC_INTERNAL_ERROR`. It would be better to show usable error message by catching such type of exception.

```
> select st_polygon('polygon(-1 1, 1 -1)')
```

```
java.lang.IllegalArgumentException: undefined
	at com.esri.core.geometry.WktParser.lineStringStart_(WktParser.java:479)
	at com.esri.core.geometry.WktParser.nextToken(WktParser.java:87)
	at com.esri.core.geometry.OperatorImportFromWktLocal.polygonText(OperatorImportFromWktLocal.java:500)
	at com.esri.core.geometry.OperatorImportFromWktLocal.polygonTaggedText(OperatorImportFromWktLocal.java:179)
	at com.esri.core.geometry.OperatorImportFromWktLocal.importFromWkt(OperatorImportFromWktLocal.java:112)
	at com.esri.core.geometry.OperatorImportFromWktLocal.executeOGC(OperatorImportFromWktLocal.java:76)
	at com.esri.core.geometry.ogc.OGCGeometry.fromText(OGCGeometry.java:470)
```

**Comment by nezihyigitbasi** [comment]
Fixed by #9515
