### ISSUE TITLE
Exception happens when query mongodb collections with certain string type conditions

### ISSUE THREAD

**Issue by visualage** [prestodb/presto#9521]
When querying a mongodb collection using the presto mongodb connector, if a string type condition is not a '=' or an 'IN', it throws the following exception:
```
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class io.airlift.slice.Slice.
        at org.bson.codecs.configuration.CodecCache.getOrThrow(CodecCache.java:46)
        at org.bson.codecs.configuration.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:63)
        at org.bson.codecs.configuration.ChildCodecRegistry.get(ChildCodecRegistry.java:51)
        at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:174)
        at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
        at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
        at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
        at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:172)
        at org.bson.codecs.DocumentCodec.writeIterable(DocumentCodec.java:197)
        at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:170)
        at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:189)
        at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
        at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
        at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:253)
        at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:205)
        at com.mongodb.connection.QueryMessage.encodeMessageBodyWithMetadata(QueryMessage.java:59)
        at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160)
        at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:282)
        at com.mongodb.connection.QueryProtocol.execute(QueryProtocol.java:54)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:260)
        at com.mongodb.connection.DefaultServerConnection.query(DefaultServerConnection.java:183)
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:397)
        at com.mongodb.operation.FindOperation$1.call(FindOperation.java:394)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:196)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:169)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:394)
        at com.mongodb.operation.FindOperation.execute(FindOperation.java:57)
        at com.mongodb.Mongo.execute(Mongo.java:760)
        at com.mongodb.Mongo$2.execute(Mongo.java:747)
        at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
        at com.mongodb.FindIterableImpl.iterator(FindIterableImpl.java:135)
        at com.facebook.presto.mongodb.MongoSession.execute(MongoSession.java:248)
        at com.facebook.presto.mongodb.MongoPageSource.<init>(MongoPageSource.java:78)
        at com.facebook.presto.mongodb.MongoPageSourceProvider.createPageSource(MongoPageSourceProvider.java:51)
        at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
        at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:219)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:337)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
The problem is when building the mongodb query condition from the presto query, string values are not translated from io.airlift.slice.Slice type when the condition value is a range value. This pull request may be a fix to the bug:
https://github.com/prestodb/presto/pull/9520

This bug is reproducible with version 0.190.

**Comment by visualage** [comment]
Resolved already
