### ISSUE TITLE
Hive connector fails to load in Java 9

### ISSUE THREAD

**Issue by martint** [prestodb/presto#9559]
It fails with:

```
	at com.facebook.presto.hive.HiveConnectorFactory.create(HiveConnectorFactory.java:110)
	at com.facebook.presto.connector.ConnectorManager.createConnector(ConnectorManager.java:303)
	at com.facebook.presto.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:191)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:183)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:169)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:96)
	at com.facebook.presto.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:74)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:120)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
Caused by: java.lang.RuntimeException: failed to load Hadoop native library
	at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:58)
	at com.facebook.presto.hive.HdfsEnvironment.<clinit>(HdfsEnvironment.java:37)
	... 39 more
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
	at org.apache.hadoop.io.compress.CompressionCodecFactory.addCodec(CompressionCodecFactory.java:70)
	at org.apache.hadoop.io.compress.CompressionCodecFactory.<init>(CompressionCodecFactory.java:186)
	at com.facebook.presto.hadoop.HadoopNative.loadAllCodecs(HadoopNative.java:65)
	at com.facebook.presto.hadoop.HadoopNative.requireHadoopNative(HadoopNative.java:52)
	... 40 more
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
	at java.base/java.lang.String.substring(String.java:1885)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:52)
	... 45 more
```

It's caused by this line in `Shell.java` (`org.apache.hadoop.util.Shell`):

```java
private static boolean IS_JAVA7_OR_ABOVE = System.getProperty("java.version").substring(0, 3).compareTo("1.7") >= 0;
```

**Comment by electrum** [comment]
This works on the latest Java 9.0.1 because the version string is longer.

**Comment by electrum** [comment]
Fixed upstream in https://issues.apache.org/jira/browse/HADOOP-10775

**Comment by electrum** [comment]
Fixed by https://github.com/prestodb/presto/pull/9563
