### ISSUE TITLE
Error while running queries: Unknown block encoding SLICE_ARRAY

### ISSUE THREAD

**Issue by ashwinhs** [prestodb/presto#9600]
We recently upgraded from presto 0.188 to 0.191. In 0.191, we see this error when running queries - 

```
Query 20171221_155438_00008_6n44p failed: Unknown block encoding SLICE_ARRAY
java.lang.IllegalArgumentException: Unknown block encoding SLICE_ARRAY
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at com.facebook.presto.block.BlockEncodingManager.readBlockEncoding(BlockEncodingManager.java:100)
        at com.facebook.presto.spi.block.DictionaryBlockEncoding$DictionaryBlockEncodingFactory.readEncoding(DictionaryBlockEncoding.java:113)
        at com.facebook.presto.spi.block.DictionaryBlockEncoding$DictionaryBlockEncodingFactory.readEncoding(DictionaryBlockEncoding.java:101)
        at com.facebook.presto.block.BlockEncodingManager.readBlockEncoding(BlockEncodingManager.java:103)
        at com.facebook.presto.block.BlockSerdeUtil.readBlock(BlockSerdeUtil.java:42)
        at com.facebook.presto.execution.buffer.PagesSerdeUtil.readRawPage(PagesSerdeUtil.java:53)
        at com.facebook.presto.execution.buffer.PagesSerde.deserialize(PagesSerde.java:92)
        at com.facebook.presto.operator.ExchangeOperator.getOutput(ExchangeOperator.java:231)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:372)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:269)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:652)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:263)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:990)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

The same query runs and produces results on 0.188. We are running the query on a ORC file ZLIB compressed. Presto is running on AWS EMR (r4.4xlarge machines), in a cluster of 4 machines. Any ideas why this might happen?

**Comment by highker** [comment]
We have removed `SLICE_ARRAY` completely. @ashwinhs  Is it possible that the machines are running with different versions?

**Comment by ashwinhs** [comment]
@highker No, all the nodes are running the same version. 

```
presto:default> select * from system.runtime.nodes;
       node_id       |         http_uri          | node_version | coordinator | state
---------------------+---------------------------+--------------+-------------+--------
 i-0b6c38e67a606f750 | http://<IP>:8081          | 0.191        | false       | active
 i-0dede933fd5d0d1d3 | http://<IP>:8081          | 0.191        | false       | active
 i-0287860ab159220d9 | http://<IP>:8081          | 0.191        | true        | active
 i-00d056b71b83d2149 | http://<IP>:8081          | 0.191        | false       | active
 i-025ab6021045350c4 | http://<IP>:8081          | 0.191        | false       | active
(5 rows)

Query 20171222_133412_00010_9icgj, FINISHED, 2 nodes
http://<IP>.fmrco.com:8081/query.html?20171222_133412_00010_9icgj
Splits: 17 total, 17 done (100.00%)
CPU Time: 0.0s total,   555 rows/s, 30.3KB/s, 10% active
Per Node: 0.1 parallelism,    36 rows/s, 1.96KB/s
Parallelism: 0.1
0:00 [5 rows, 279B] [72 rows/s, 3.93KB/s]

presto:default> select * from <TABLE>;

Query 20171222_133417_00011_9icgj, FAILED, 4 nodes
http://<IP>.fmrco.com:8081/query.html?20171222_133417_00011_9icgj
Splits: 57 total, 13 done (22.81%)
CPU Time: 9.6s total,   743 rows/s, 76.6MB/s, 58% active
Per Node: 0.4 parallelism,   318 rows/s, 32.8MB/s
Parallelism: 1.7
0:06 [7.17K rows, 738MB] [1.27K rows/s, 131MB/s]

Query 20171222_133417_00011_9icgj failed: Unknown block encoding SLICE_ARRAY
java.lang.IllegalArgumentException: Unknown block encoding SLICE_ARRAY
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191)
        at com.facebook.presto.block.BlockEncodingManager.readBlockEncoding(BlockEncodingManager.java:100)
        at com.facebook.presto.spi.block.DictionaryBlockEncoding$DictionaryBlockEncodingFactory.readEncoding(DictionaryBlockEncoding.java:113)
        at com.facebook.presto.spi.block.DictionaryBlockEncoding$DictionaryBlockEncodingFactory.readEncoding(DictionaryBlockEncoding.java:101)
        at com.facebook.presto.block.BlockEncodingManager.readBlockEncoding(BlockEncodingManager.java:103)
        at com.facebook.presto.block.BlockSerdeUtil.readBlock(BlockSerdeUtil.java:42)
        at com.facebook.presto.execution.buffer.PagesSerdeUtil.readRawPage(PagesSerdeUtil.java:53)
        at com.facebook.presto.execution.buffer.PagesSerde.deserialize(PagesSerde.java:92)
        at com.facebook.presto.operator.ExchangeOperator.getOutput(ExchangeOperator.java:231)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:372)
        at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:269)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:652)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:263)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:990)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

*Blanked out IP and Table name.

**Comment by highker** [comment]
@ashwinhs Do you have any fork or wrapper from the open-source Presto? If not, I would suggest either
- fork the latest Presto, build it locally, and deploy it. Any place using `SLICE_ARRAY` will throw compilation error, or
- add breakpoints in the orc reader to check who is producing the block. According to the stacktrace, my hunch is that there is a column in your table contains `varchar` or `varbinary` type (which is also dictionary-encoded). Find out which reader/stream reader is reading that column.
