### ISSUE TITLE
an issue with 'Error opening Hive split...'

### ISSUE THREAD

**Issue by withoutconsciousmind** [prestodb/presto#9610]
I got an error when executing a normal query in 1.9.1: 
Error opening Hive split hdfs://nameservice1/user/hive/warehouse/cs_mobp2p.db/yyd_system_dict/part-m-00002.snappy (offset=0, length=814) using org.apache.hadoop.mapred.TextInputFormat: File does not exist: /user/hive/warehouse/cs_mobp2p.db/yyd_system_dict/part-m-00002.snappy at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:66) at org.apache.hadoop.hdfs.server.namenode.INodeFile.valueOf(INodeFile.java:56) at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsUpdateTimes(FSNamesystem.java:1962) at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocationsInt(FSNamesystem.java:1903) at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1883) at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getBlockLocations(FSNamesystem.java:1855) at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.getBlockLocations(NameNodeRpcServer.java:568) at org.apache.hadoop.hdfs.server.namenode.AuthorizationProviderProxyClientProtocol.getBlockLocations(AuthorizationProviderProxyClientProtocol.java:89) at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.getBlockLocations(ClientNamenodeProtocolServerSideTranslatorPB.java:363) at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java) at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:617) at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1073) at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2086) at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2082) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:422) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1693) at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2080)

initially,I thought the file doesn't eixst,but in Hive, I got the correct result with same query and  the file actually have been existing in hdfs://nameservice1/user/hive/warehouse/cs_mobp2p.db/yyd_system_dict/ as below:
![image](https://user-images.githubusercontent.com/34760772/34293104-53eb076e-e73e-11e7-8ffb-9b5474cbb5be.png)
what's wrong with the metadata of the table?
CREATE TABLE `cs_mobp2p.yyd_system_dict`(
  `id` bigint, 
  `table_name` string, 
  `table_column` string, 
  `nid` int, 
  `value` string, 
  `pid` int, 
  `update_time` string)
COMMENT 'Imported by sqoop on 2017/12/08 00:20:39'
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' 
WITH SERDEPROPERTIES ( 
  'field.delim'='\u0001', 
  'line.delim'='\n', 
  'serialization.format'='\u0001') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  'hdfs://nameservice1/user/hive/warehouse/cs_mobp2p.db/yyd_system_dict'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='true', 
  'numFiles'='4', 
  'numRows'='0', 
  'rawDataSize'='0', 
  'totalSize'='2918', 
  'transient_lastDdlTime'='1513873190')

anyone has an idea about where it went wrong?

**Comment by sqlaide** [comment]
Did you figure this out?

**Comment by MichaelChirico** [comment]
Usually this happens to me when the source table's files are being updated. it would be nice to have a safer fail mode/automatic retries, perhaps. Certainly a more informative error message would go a long way too.

**Comment by haxuanthuyen** [comment]
I get same error when executing a normal query in 0.238. The error happens when quering on large partitions and files:
org.jkiss.dbeaver.model.exec.DBCException: SQL Error [16777219]: Query failed (#20200803_024152_00010_whdse): Error opening Hive split hdfs://nameservice1/user/hive/warehouse/xxx/year=2020/month=07/day=31/hour=12/xxx.avro (offset=0, length=28235) using org.apache.hadoop.hive.ql.io.avro.AvroContainerInputFormat: Filesystem closed
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.nextRow(JDBCResultSetImpl.java:180)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.fetchQueryData(SQLQueryJob.java:669)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:494)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:414)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:406)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:765)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:2848)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:99)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:152)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:97)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$17.run(ResultSetViewer.java:3429)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

- The presto cluster runing on 6 node
- The hive cluster using cdh 6.3 and enabled kerberos
Does anyone know how to fix this problem?
