### ISSUE TITLE
Modeified the presto-mysql compile it all the time errors

### ISSUE THREAD

**Issue by Tank-zhu** [prestodb/presto#9630]
`@Inject
    public MySqlClient(JdbcConnectorId connectorId, BaseJdbcConfig config, MySqlConfig mySqlConfig,JdbcSubTableConfig subTableConfig)
            throws SQLException
    {
        super(connectorId, config, "`", new Driver(),subTableConfig);
        connectionProperties.setProperty("nullCatalogMeansCurrent", "false");
        connectionProperties.setProperty("useUnicode", "true");
        connectionProperties.setProperty("characterEncoding", "utf8");
        connectionProperties.setProperty("tinyInt1isBit", "false");
        if (mySqlConfig.isAutoReconnect()) {
            connectionProperties.setProperty("autoReconnect", String.valueOf(mySqlConfig.isAutoReconnect()));
            connectionProperties.setProperty("maxReconnects", String.valueOf(mySqlConfig.getMaxReconnects()));
        }
        if (mySqlConfig.getConnectionTimeout() != null) {
            connectionProperties.setProperty("connectTimeout", String.valueOf(mySqlConfig.getConnectionTimeout().toMillis()));
        }
        dbType = BaseJdbcClient.TYPE_MYSQL;
    }`

## maven packageing
`root@tank:/usr/local/presto-master/presto/presto-mysql# mvn package -DskipTests 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building presto-mysql 0.187
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) @ presto-mysql ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.206 s
[INFO] Finished at: 2017-12-28T10:11:31+08:00
[INFO] Final Memory: 20M/235M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "Central" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.facebook.presto:presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) on project presto-mysql:
[ERROR] 
[ERROR] Presto plugin dependency org.openjdk.jol:jol-core must have scope 'provided'. It is part of the SPI and will be provided at runtime.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
root@tank:/usr/local/presto-master/presto/presto-mysql# 
`

**Comment by Tank-zhu** [comment]
``` java
@Inject
    public MySqlClient(JdbcConnectorId connectorId, BaseJdbcConfig config, MySqlConfig mySqlConfig,JdbcSubTableConfig subTableConfig)
            throws SQLException
    {
        super(connectorId, config, "`", new Driver(),subTableConfig);
        connectionProperties.setProperty("nullCatalogMeansCurrent", "false");
        connectionProperties.setProperty("useUnicode", "true");
        connectionProperties.setProperty("characterEncoding", "utf8");
        connectionProperties.setProperty("tinyInt1isBit", "false");
        if (mySqlConfig.isAutoReconnect()) {
            connectionProperties.setProperty("autoReconnect", String.valueOf(mySqlConfig.isAutoReconnect()));
            connectionProperties.setProperty("maxReconnects", String.valueOf(mySqlConfig.getMaxReconnects()));
        }
        if (mySqlConfig.getConnectionTimeout() != null) {
            connectionProperties.setProperty("connectTimeout", String.valueOf(mySqlConfig.getConnectionTimeout().toMillis()));
        }
        dbType = BaseJdbcClient.TYPE_MYSQL;
    }

root@tank:/usr/local/presto-master/presto/presto-mysql# mvn package -DskipTests 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building presto-mysql 0.187
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) @ presto-mysql ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.206 s
[INFO] Finished at: 2017-12-28T10:11:31+08:00
[INFO] Final Memory: 20M/235M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "Central" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.facebook.presto:presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) on project presto-mysql:
[ERROR] 
[ERROR] Presto plugin dependency org.openjdk.jol:jol-core must have scope 'provided'. It is part of the SPI and will be provided at runtime.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
root@tank:/usr/local/presto-master/presto/presto-mysql# 
```

**Comment by Tank-zhu** [comment]
``` java
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "Central" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.facebook.presto:presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) on project presto-mysql:
[ERROR] 
[ERROR] Presto plugin dependency io.airlift:units must have scope 'provided'. It is part of the SPI and will be provided at runtime.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.facebook.presto:presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) on project presto-mysql: 

Presto plugin dependency io.airlift:units must have scope 'provided'. It is part of the SPI and will be provided at runtime.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.MojoExecutionException: 

Presto plugin dependency io.airlift:units must have scope 'provided'. It is part of the SPI and will be provided at runtime.
        at com.facebook.presto.maven.SpiDependencyChecker.execute(SpiDependencyChecker.java:74)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 11 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
root@tank:/usr/local/presto-master/presto/presto-mysql# 
```

**Comment by Tank-zhu** [comment]
``` java
INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "Central" could not be activated because it does not exist.
[ERROR] Failed to execute goal com.facebook.presto:presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) on project presto-mysql:
[ERROR] 
[ERROR] Presto plugin dependency org.openjdk.jol:jol-core must have scope 'provided'. It is part of the SPI and will be provided at runtime.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.facebook.presto:presto-maven-plugin:0.3:check-spi-dependencies (default-check-spi-dependencies) on project presto-mysql: 

Presto plugin dependency org.openjdk.jol:jol-core must have scope 'provided'. It is part of the SPI and will be provided at runtime.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.MojoExecutionException: 

Presto plugin dependency org.openjdk.jol:jol-core must have scope 'provided'. It is part of the SPI and will be provided at runtime.
        at com.facebook.presto.maven.SpiDependencyChecker.execute(SpiDependencyChecker.java:74)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 11 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
root@tank:/usr/local/presto-master/presto/presto-mysql# 

```

**Comment by Tank-zhu** [comment]
It's done, You helped. Thank you
