### ISSUE TITLE
Problem displaying geometry with cli

### ISSUE THREAD

**Issue by nezihyigitbasi** [prestodb/presto#9675]
```
presto:sf100> select ST_GeometryFromText('POINT (1.5 2.5)');
java.lang.RuntimeException: Error fetching next at https://[2401:db00:1030:1172:face:0:5:0]:7778/v1/statement/20180104_224028_35178_zviwt/1 returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={content-type=[application/json], date=[Thu, 04 Jan 2018 22:40:28 GMT], vary=[Accept-Encoding, User-Agent], x-content-type-options=[nosniff]}, hasValue=false} [Error: {"id":"20180104_224028_35178_zviwt","infoUri":"https://[2401:db00:1030:1172:face:0:5:0]:7778/query.html?20180104_224028_35178_zviwt","columns":[{"name":"_col0","type":"Geometry","typeSignature":{"rawType":"Geometry","typeArguments":[],"literalArguments":[],"arguments":[]}}],"data":[["POINT (1.5 2.5)"]],"stats":{"state":"FINISHED","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":383,"elapsedTimeMillis":396,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"FINISHED","done":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":100.0}}
]
	at com.facebook.presto.client.StatementClient.requestFailedException(StatementClient.java:390)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:333)
	at com.facebook.presto.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:122)
	at com.facebook.presto.cli.Query.renderQueryOutput(Query.java:134)
	at com.facebook.presto.cli.Query.renderOutput(Query.java:118)
	at com.facebook.presto.cli.Console.process(Console.java:298)
	at com.facebook.presto.cli.Console.runConsole(Console.java:250)
	at com.facebook.presto.cli.Console.run(Console.java:145)
	at com.facebook.presto.cli.Presto.main(Presto.java:32)
Caused by: java.lang.IllegalArgumentException: Unable to create class com.facebook.presto.client.QueryResults from JSON response:
[{"id":"20180104_224028_35178_zviwt","infoUri":"https://[2401:db00:1030:1172:face:0:5:0]:7778/query.html?20180104_224028_35178_zviwt","columns":[{"name":"_col0","type":"Geometry","typeSignature":{"rawType":"Geometry","typeArguments":[],"literalArguments":[],"arguments":[]}}],"data":[["POINT (1.5 2.5)"]],"stats":{"state":"FINISHED","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":383,"elapsedTimeMillis":396,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"FINISHED","done":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":100.0}}
]
	at com.facebook.presto.client.JsonResponse.<init>(JsonResponse.java:69)
	at com.facebook.presto.client.JsonResponse.execute(JsonResponse.java:143)
	at com.facebook.presto.client.StatementClient.advance(StatementClient.java:320)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Invalid JSON string for [simple type, class com.facebook.presto.client.QueryResults]
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:137)
	at com.facebook.presto.client.JsonResponse.<init>(JsonResponse.java:66)
	... 9 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.facebook.presto.client.QueryResults, problem: Illegal base64 character 20
 at [Source: {"id":"20180104_224028_35178_zviwt","infoUri":"https://[2401:db00:1030:1172:face:0:5:0]:7778/query.html?20180104_224028_35178_zviwt","columns":[{"name":"_col0","type":"Geometry","typeSignature":{"rawType":"Geometry","typeArguments":[],"literalArguments":[],"arguments":[]}}],"data":[["POINT (1.5 2.5)"]],"stats":{"state":"FINISHED","queued":false,"scheduled":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":383,"elapsedTimeMillis":396,"processedRows":0,"processedBytes":0,"peakMemoryBytes":0,"rootStage":{"stageId":"0","state":"FINISHED","done":true,"nodes":1,"totalSplits":5,"queuedSplits":0,"runningSplits":0,"completedSplits":5,"userTimeMillis":0,"cpuTimeMillis":0,"wallTimeMillis":0,"processedRows":1,"processedBytes":0,"subStages":[]},"progressPercentage":100.0}}
; line: 1, column: 881]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:268)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1405)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:468)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:487)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:276)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:224)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:135)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1194)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2871)
	at io.airlift.json.JsonCodec.fromJson(JsonCodec.java:134)
	... 10 more
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 20
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at com.facebook.presto.client.QueryResults.fixValue(QueryResults.java:337)
	at com.facebook.presto.client.QueryResults.fixData(QueryResults.java:236)
	at com.facebook.presto.client.QueryResults.<init>(QueryResults.java:96)
	at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:274)
	... 19 more
Query is gone (server restarted?)
```

**Comment by nezihyigitbasi** [comment]
Related to #9353. /cc @mbasmanova

**Comment by nezihyigitbasi** [comment]
My bad, this seems to be working fine after building the latest master.
