### ISSUE TITLE
Lambda cannot be used inside unnest

### ISSUE THREAD

**Issue by haozhun** [prestodb/presto#9709]
```
presto> select * from unnest(transform(sequence(1, 5), x -> x * x));
Query 20180110_011726_00386_hgjdi failed: com.facebook.presto.sql.tree.ArithmeticBinaryExpression cannot be cast to java.lang.Long
java.lang.ClassCastException: com.facebook.presto.sql.tree.ArithmeticBinaryExpression cannot be cast to java.lang.Long
        at com.facebook.presto.$gen.VarArgsToMapAdapter_3751.varArgsToMap(Unknown Source)
        at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:187)
        at com.sun.proxy.$Proxy457.apply(Unknown Source)
        at com.facebook.presto.$gen.ArrayTransform_3752.transform(Unknown Source)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:649)
        at com.facebook.presto.sql.FunctionInvoker.invoke(FunctionInvoker.java:88)
        at com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:971)
        at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:114)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.planner.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:271)
        at com.facebook.presto.sql.planner.ExpressionInterpreter.evaluateConstantExpression(ExpressionInterpreter.java:234)
        at com.facebook.presto.sql.planner.RelationPlanner.visitUnnest(RelationPlanner.java:523)
        at com.facebook.presto.sql.planner.RelationPlanner.visitUnnest(RelationPlanner.java:94)
        at com.facebook.presto.sql.tree.Unnest.accept(Unnest.java:62)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.planner.QueryPlanner.planFrom(QueryPlanner.java:269)
        at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:150)
        at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:467)
        at com.facebook.presto.sql.planner.RelationPlanner.visitQuerySpecification(RelationPlanner.java:94)
        at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:127)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.planner.QueryPlanner.planQueryBody(QueryPlanner.java:258)
        at com.facebook.presto.sql.planner.QueryPlanner.plan(QueryPlanner.java:130)
        at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:460)
        at com.facebook.presto.sql.planner.RelationPlanner.visitQuery(RelationPlanner.java:94)
        at com.facebook.presto.sql.tree.Query.accept(Query.java:94)
        at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:27)
        at com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:376)
        at com.facebook.presto.sql.planner.LogicalPlanner.planStatementWithoutOutput(LogicalPlanner.java:175)
        at com.facebook.presto.sql.planner.LogicalPlanner.planStatement(LogicalPlanner.java:156)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:127)
        at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:122)
        at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:363)
        at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:342)
        at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:274)
        at com.facebook.presto.execution.QueuedExecution.lambda$start$1(QueuedExecution.java:62)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by wenleix** [comment]
inside `unnest` ?
