### ISSUE TITLE
ConcurrentModificationException when alter table drop columns

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#9733]
```
alter table ttd_bi_recommend_created9 drop column edndata2;
```
throw this exception

```
java.util.ConcurrentModificationException: undefined
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.dropColumn(BridgingHiveMetastore.java:217)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropColumn(CachingHiveMetastore.java:495)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.dropColumn(CachingHiveMetastore.java:495)
	at com.facebook.presto.hive.metastore.SemiTransactionalHiveMetastore.lambda$dropColumn$9(SemiTransactionalHiveMetastore.java:357)
```

```
  @Override
    public void dropColumn(String databaseName, String tableName, String columnName)
    {
        verifyCanDropColumn(this, databaseName, tableName, columnName);
        org.apache.hadoop.hive.metastore.api.Table table = delegate.getTable(databaseName, tableName)
                .orElseThrow(() -> new TableNotFoundException(new SchemaTableName(databaseName, tableName)));
        for (FieldSchema fieldSchema : table.getSd().getCols()) {
            if (fieldSchema.getName().equals(columnName)) {
                table.getSd().getCols().remove(fieldSchema);
            }
        }
        alterTable(databaseName, tableName, table);
    }
```

I have changed the code in BridgingHiveMetastore to belows
```
    Iterator<FieldSchema> iters = table.getSd().getCols().iterator();
        while (iters.hasNext()) {
            if (iters.next().getName().equals(columnName)) {
                iters.remove();
            }
        }
```

**Comment by findepi** [comment]
@photogamerun why don't you make a PR with your change?

**Comment by ebyhr** [comment]
@photogamerun 
I reproduced it and confirmed your code works well. Thanks!
Probably, `removeIf` is simple and better?. 

```java
@Override
public void dropColumn(String databaseName, String tableName, String columnName)
{
    verifyCanDropColumn(this, databaseName, tableName, columnName);
    org.apache.hadoop.hive.metastore.api.Table table = delegate.getTable(databaseName, tableName)
            .orElseThrow(() -> new TableNotFoundException(new SchemaTableName(databaseName, tableName)));
    table.getSd().getCols().removeIf(fieldSchema -> fieldSchema.getName().equals(columnName));
    alterTable(databaseName, tableName, table);
}
```
(If you won't send PR, I can send it instead of you)

**Comment by photogamerun** [comment]
yeah, you please send pr.
