### ISSUE TITLE
Nullpointexception happen possible when create table as select statement is running

### ISSUE THREAD

**Issue by photogamerun** [prestodb/presto#9739]
`com.facebook.presto.hive.metastore.thrift.ThriftMetastoreUtil`
```
public static Database fromMetastoreApiDatabase(org.apache.hadoop.hive.metastore.api.Database database)
    {
        String ownerName = "PUBLIC";
        PrincipalType ownerType = PrincipalType.ROLE;
        if (database.getOwnerName() != null) {
            ownerName = database.getOwnerName();
            if (database.getOwnerType() == null) {
                ownerType = fromMetastoreApiPrincipalType(org.apache.hadoop.hive.metastore.api.PrincipalType.ROLE);
            }
            else {
                ownerType = fromMetastoreApiPrincipalType(database.getOwnerType());
            }
        }
```
In this code once `database.getOwnerType()` is null, it will throw null point exception in presto

exception likes 
```
java.lang.NullPointerException: undefined
	at com.facebook.presto.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiPrincipalType(ThriftMetastoreUtil.java:344)
	at com.facebook.presto.hive.metastore.thrift.ThriftMetastoreUtil.fromMetastoreApiDatabase(ThriftMetastoreUtil.java:169)
	at java.util.Optional.map(Optional.java:215)
	at com.facebook.presto.hive.metastore.thrift.BridgingHiveMetastore.getDatabase(BridgingHiveMetastore.java:66)
	at com.facebook.presto.hive.metastore.CachingHiveMetastore.loadDatabase(CachingHiveMetastore.java:239)
	at com.google.common.cache.CacheLoader$FunctionToCacheLoader.load(CacheLoader.java:146)
	at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:182)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
```

**Comment by findepi** [comment]
@photogamerun which version of Presto are you using?

**Comment by photogamerun** [comment]
0.190

**Comment by findepi** [comment]
Please update the quoted code to actually match 0.190
