### ISSUE TITLE
Presto With CDH5 HA

### ISSUE THREAD

**Issue by phoenixhadoop** [prestodb/presto#974]
Hi,facebook team:
    When I executed sql querying with presto-cli ,the console shown below:
    Query 20140120_071822_00005_sihwm failed: java.net.UnknownHostException:   sunrise-cluster
The sunrise-cluster is dfs.nameservices of CDH5 HA
Please help  me.
Thank you.

**Comment by anupash147** [comment]
Can someone help me resolve this issue

java.lang.IllegalArgumentException: java.net.UnknownHostException: nameservice1
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
	at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
	at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
	at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:74)
	at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:61)
	at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:43)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at parquet.hadoop.ParquetFileReader.readFooter(ParquetFileReader.java:384)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:364)
	at com.facebook.presto.hive.parquet.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:203)
	at com.facebook.presto.hive.parquet.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:102)
	at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:128)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:106)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:43)
	at com.facebook.presto.transaction.LegacyConnectorPageSourceProvider.createPageSource(LegacyConnectorPageSourceProvider.java:40)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
	at com.facebook.presto.operator.TableScanOperator.createSourceIfNecessary(TableScanOperator.java:268)
	at com.facebook.presto.operator.TableScanOperator.isFinished(TableScanOperator.java:210)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:377)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:580)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:640)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: nameservice1
	... 30 more


I did all the necessary config changes made and all.. but nothing worked

**Comment by zhangxin0112** [comment]
@anupash147 vi the hive.properties like this     hive.config.resources=etc/hadoop/conf/core-site.xml,/etc/hadoop/hdfs-site.xml
