### ISSUE TITLE
InvalidProtocolBufferException  CDH5 Presto-0.57

### ISSUE THREAD

**Issue by phoenixhadoop** [prestodb/presto#975]
Hi facebook team:
    Now I execute one sql querying of presto from datasource hive on cdh5,but the console prints exception informations as below:
 java.lang.RuntimeException: java.io.IOException: Failed on local exception: com.facebook.presto.hadoop.shaded.com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status; Host Details : local host is: "slave4.sunrise.com/192.168.0.9"; destination host is: "slave4":8020; 
        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[guava-15.0.jar:na]
        at com.facebook.presto.hive.HiveSplitSourceProvider$HiveSplitSource.getNextBatch(HiveSplitSourceProvider.java:481) ~[na:na]
        at com.facebook.presto.execution.SqlStageExecution.scheduleSourcePartitionedNodes(SqlStageExecution.java:637) [presto-main-0.57.jar:0.57]
        at com.facebook.presto.execution.SqlStageExecution.startTasks(SqlStageExecution.java:556) [presto-main-0.57.jar:0.57]
        at com.facebook.presto.execution.SqlStageExecution.access$300(SqlStageExecution.java:95) [presto-main-0.57.jar:0.57]
        at com.facebook.presto.execution.SqlStageExecution$5.run(SqlStageExecution.java:528) [presto-main-0.57.jar:0.57]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_45]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]
Caused by: java.io.IOException: Failed on local exception: com.facebook.presto.hadoop.shaded.com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status; Host Details : local host is: "slave4.sunrise.com/192.168.0.9"; destination host is: "slave4":8020; 
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:763) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at org.apache.hadoop.ipc.Client.call(Client.java:1229) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:202) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at com.sun.proxy.$Proxy157.getListing(Unknown Source) ~[na:na]
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getListing(ClientNamenodeProtocolTranslatorPB.java:441) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_45]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_45]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:164) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:83) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at com.sun.proxy.$Proxy158.getListing(Unknown Source) ~[na:na]
        at org.apache.hadoop.hdfs.DFSClient.listPaths(DFSClient.java:1526) ~[na:na]
        at org.apache.hadoop.hdfs.DistributedFileSystem$1.<init>(DistributedFileSystem.java:466) ~[na:na]
        at org.apache.hadoop.hdfs.DistributedFileSystem.listLocatedStatus(DistributedFileSystem.java:457) ~[na:na]
        at org.apache.hadoop.fs.FileSystem.listLocatedStatus(FileSystem.java:1760) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at com.facebook.presto.hadoop.HadoopFileSystem.listLocatedStatus(HadoopFileSystem.java:30) ~[na:na]
        at com.facebook.presto.hive.util.AsyncRecursiveWalker.doWalk(AsyncRecursiveWalker.java:70) ~[na:na]
        at com.facebook.presto.hive.util.AsyncRecursiveWalker.access$000(AsyncRecursiveWalker.java:31) ~[na:na]
        at com.facebook.presto.hive.util.AsyncRecursiveWalker$1.run(AsyncRecursiveWalker.java:58) ~[na:na]
        at com.facebook.presto.hive.util.SuspendingExecutor$1.run(SuspendingExecutor.java:67) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor.executeOrMerge(BoundedExecutor.java:82) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor.access$000(BoundedExecutor.java:41) ~[na:na]
        at com.facebook.presto.hive.util.BoundedExecutor$1.run(BoundedExecutor.java:53) ~[na:na]
        ... 3 common frames omitted
com.facebook.presto.hadoop.shaded.com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status
        at com.facebook.presto.hadoop.shaded.com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81) ~[na:na]
        at org.apache.hadoop.ipc.protobuf.RpcPayloadHeaderProtos$RpcResponseHeaderProto$Builder.buildParsed(RpcPayloadHeaderProtos.java:1094) ~[na:na]
        at org.apache.hadoop.ipc.protobuf.RpcPayloadHeaderProtos$RpcResponseHeaderProto$Builder.access$1300(RpcPayloadHeaderProtos.java:1028) ~[na:na]
        at org.apache.hadoop.ipc.protobuf.RpcPayloadHeaderProtos$RpcResponseHeaderProto.parseDelimitedFrom(RpcPayloadHeaderProtos.java:986) ~[na:na]
        at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:938) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
        at org.apache.hadoop.ipc.Client$Connection.run(Client.java:836) ~[hadoop-common-2.2.0-cdh5.0.0-beta-1.jar:na]
2014-01-21T10:17:06.952+0800     INFO   query-scheduler-1       com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20140121_021704_00000_vf3qr :: elapsed 1909.00ms :: planning 499.83ms :: scheduling 1409.00ms :: running 0.00ms :: finishing 1409.00ms :: begin 2014-01-21T10:17:04.983+08:00 :: end 2014-01-21T10:17:06.892+08:00
2014-01-21T10:17:06.994+0800    DEBUG   task-notification-0     com.facebook.presto.execution.TaskStateMachine  Task 20140121_021704_00000_vf3qr.0.0 is CANCELED
2014-01-21T10:32:07.093+0800    DEBUG   query-management-1      com.facebook.presto.execution.SqlQueryManager   Remove query 20140121_021704_00000_vf3qr
2014-01-21T10:32:07.281+0800    DEBUG   query-purger-0  com.facebook.presto.server.StatementResource    Removed expired query 20140121_021704_00000_vf3qr

I want to know whether it is caused by incompatible versions of protobuf.
Thanks.

**Comment by versemonger** [comment]
@damiencarol Do you mean adding connector.name=hive-cdh5 in hive.properties? I tried this but I got the error message: com.facebook.presto.server.PrestoServer	No factory for connector hive-cdh5
java.lang.IllegalArgumentException: No factory for connector hive-cdh5
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:147)
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:99)
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:77)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:138)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by electrum** [comment]
Did you build Presto on the command line first? Do this: `mvn clean install -DskipTests`

**Comment by versemonger** [comment]
@electrum Thanks for your timely reply. Yes I did that. In fact I used `mvn clean install` without `-DskipTest`

**Comment by versemonger** [comment]
@electrum 
This is the log of building it successfully.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] presto-root ........................................ SUCCESS [  2.984 s]
[INFO] presto-spi ......................................... SUCCESS [  7.936 s]
[INFO] presto-client ...................................... SUCCESS [  2.322 s]
[INFO] presto-parser ...................................... SUCCESS [  6.019 s]
[INFO] presto-bytecode .................................... SUCCESS [  2.471 s]
[INFO] presto-tpch ........................................ SUCCESS [  1.527 s]
[INFO] presto-main ........................................ SUCCESS [ 29.901 s]
[INFO] presto-tests ....................................... SUCCESS [  7.780 s]
[INFO] presto-atop ........................................ SUCCESS [  4.522 s]
[INFO] presto-jmx ......................................... SUCCESS [  4.519 s]
[INFO] presto-record-decoder .............................. SUCCESS [  2.048 s]
[INFO] presto-kafka ....................................... SUCCESS [  6.111 s]
[INFO] presto-redis ....................................... SUCCESS [  5.097 s]
[INFO] presto-cassandra ................................... SUCCESS [  9.583 s]
[INFO] presto-blackhole ................................... SUCCESS [  3.868 s]
[INFO] presto-orc ......................................... SUCCESS [  6.836 s]
[INFO] presto-benchmark ................................... SUCCESS [  3.014 s]
[INFO] presto-hive ........................................ SUCCESS [  9.036 s]
[INFO] presto-hive-hadoop1 ................................ SUCCESS [  5.326 s]
[INFO] presto-hive-hadoop2 ................................ SUCCESS [  5.767 s]
[INFO] presto-hive-cdh4 ................................... SUCCESS [  5.525 s]
[INFO] presto-hive-cdh5 ................................... SUCCESS [  5.815 s]
[INFO] presto-teradata-functions .......................... SUCCESS [  5.664 s]
[INFO] presto-example-http ................................ SUCCESS [  5.614 s]
[INFO] presto-local-file .................................. SUCCESS [  3.145 s]
[INFO] presto-raptor ...................................... SUCCESS [ 11.894 s]
[INFO] presto-base-jdbc ................................... SUCCESS [  4.112 s]
[INFO] presto-mysql ....................................... SUCCESS [  6.778 s]
[INFO] presto-postgresql .................................. SUCCESS [  4.448 s]
[INFO] presto-mongodb ..................................... SUCCESS [  4.723 s]
[INFO] presto-ml .......................................... SUCCESS [  5.075 s]
[INFO] presto-jdbc ........................................ SUCCESS [  9.051 s]
[INFO] presto-cli ......................................... SUCCESS [  8.015 s]
[INFO] presto-product-tests ............................... SUCCESS [ 11.657 s]
[INFO] presto-benchmark-driver ............................ SUCCESS [  4.105 s]
[INFO] presto-server ...................................... SUCCESS [ 25.734 s]
[INFO] presto-server-rpm .................................. SUCCESS [ 29.378 s]
[INFO] presto-docs ........................................ SUCCESS [ 36.151 s]
[INFO] presto-verifier .................................... SUCCESS [  8.856 s]
[INFO] presto-testing-server-launcher ..................... SUCCESS [  6.541 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:29 min
[INFO] Finished at: 2016-06-27T15:26:09-07:00
[INFO] Final Memory: 454M/2861M
[INFO] ------------------------------------------------------------------------

**Comment by versemonger** [comment]
@electrum When I was poking around, I also found that the factory for connector seems to contains only one version of connector for each kind of platform(for example, hive, jmx, kafka and so on), in which the connector for hive looks hard-coded as hive-cdh4.

**Comment by laoyang945** [comment]
same here. using 0.149 presto
it seems that the only loaded plugin is the hive-cdh4. even if I removed the hive-cdh4 folder from the plugin folder, it still throws error saying no factory for connector hive-cdh5
besides, there is a warning in loading hive-cdh5

2016-06-30T14:30:34.508Z	INFO	main	com.facebook.presto.server.PluginManager	-- Loading plugin /var/presto/data/plugin/hive-cdh5 --
2016-06-30T14:30:34.518Z	WARN	main	com.facebook.presto.server.PluginManager	No service providers of type com.facebook.presto.spi.Plugin
2016-06-30T14:30:34.518Z	INFO	main	com.facebook.presto.server.PluginManager	-- Finished loading plugin /var/presto/data/plugin/hive-cdh5 --
2016-06-30T14:30:34.535Z	INFO	main	com.facebook.presto.metadata.CatalogManager	-- Loading catalog etc/catalog/zhive.properties --
2016-06-30T14:30:34.536Z	ERROR	main	com.facebook.presto.server.PrestoServer	No factory for connector hive-cdh5
java.lang.IllegalArgumentException: No factory for connector hive-cdh5
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.facebook.presto.connector.ConnectorManager.createConnection(ConnectorManager.java:147)
	at com.facebook.presto.metadata.CatalogManager.loadCatalog(CatalogManager.java:99)
	at com.facebook.presto.metadata.CatalogManager.loadCatalogs(CatalogManager.java:77)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:115)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:63)

**Comment by versemonger** [comment]
@laoyang945 Later I found there is an option named plugin.bundles in config.properties Change presto-hive-cdh4/pom.xml into presto-hive-cdh5/pom.xml and this problem should be solved. However now I still have other problems running presto.

**Comment by laoyang945** [comment]
@versemonger but this option is not mentioned in the document right? I compile the 150 version hive-cdh5 and it worked. magic

**Comment by versemonger** [comment]
@laoyang945 Finally I installed a stand-alone hive and hadoop in the same machine as presto server and it worked. I guess presto server working outside a hadoop cluster easily gets this problem when the cluster are installed in VMs according some other discussions I saw.

**Comment by dain** [comment]
Presto ships with the following plugins for Hive:
* hive-cdh4
* hive-cdh5
* hive-hadoop1
* hive-hadoop2
