### ISSUE TITLE
"dictionarySourceIds of data block and hash block do not match"

### ISSUE THREAD

**Issue by ORBAT** [prestodb/presto#9756]
I have a [fairly complex query](https://gist.github.com/ORBAT/135626bf526be349bb42d63b59e177fc) that ran fine with `dictionary_aggregation` enabled on 0.188, but it fails with the following stack trace on 0.192

```
com.google.common.base.VerifyException: dictionarySourceIds of data block and hash block do not match 	at com.google.common.base.Verify.verify(Verify.java:122) 	at com.facebook.presto.operator.MultiChannelGroupByHash.canProcessDictionary(MultiChannelGroupByHash.java:477) 	at com.facebook.presto.operator.MultiChannelGroupByHash.getGroupIds(MultiChannelGroupByHash.java:223) 	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.processPage(InMemoryHashAggregationBuilder.java:164) 	at com.facebook.presto.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:408) 	at com.facebook.presto.operator.Driver.processInternal(Driver.java:385) 	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278) 	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:659) 	at com.facebook.presto.operator.Driver.processFor(Driver.java:272) 	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975) 	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163) 	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 	at java.lang.Thread.run(Thread.java:745)
--
```

Turning `dictionary_aggregation` off mitigated the problem.

How can I help debug this?

**Comment by ORBAT** [comment]
Ran into the same issue with [a simpler query](https://gist.github.com/ORBAT/b19d73ef8b3558a12f402cba460e73f8)

**Comment by fenacoder** [comment]
I've faced with this problem. And when I set `dictionary_aggregation` to false, its solved. 

`set session dictionary_aggregation = false`

**Comment by zorro1992** [comment]
Hey guys ,
We are using Presto 0.194 version and seeing this error again. May I know what made a fix .

The above command is not helping a lot.

**Comment by findepi** [comment]
@zorro1992 you must be altering your session is somehow ineffective way. Once `set session dictionary_aggregation = false` is called, the line of code that is throwing the exception quoted in this issue becomes unreachable.

**Comment by findepi** [comment]
This might be related to Join dictionary processing added in https://github.com/prestodb/presto/pull/8629 (0.190).
Join operator now can produce `DictionaryBlock`s which are problematic for downstream Aggregation operator.

cc @dain @highker @sopel39

**Comment by findepi** [comment]
I didn't reproduce original stacktrace yet, but I got a similar one. Basically in `MultiChannelGroupByHash.canProcessDictionary` there are 2 `verify` statements next to each other. If first can fail (show below), the second can fail as well.

Using single-node Presto
```
presto> use tpch.sf1;
USE
presto:sf1> set session dictionary_aggregation = true;
SET SESSION
presto:sf1> select l.comment from lineitem l join orders o on l.orderkey = o.orderkey where o.orderpriority = '1-URGENT' group by 1 order by comment asc;

Query 20180615_202813_00006_3wjs7, FAILED, 1 node
http://localhost:8080/query.html?20180615_202813_00006_3wjs7
Splits: 89 total, 22 done (24.72%)
CPU Time: 10.4s total,  175K rows/s,  461KB/s, 94% active
Per Node: 3.4 parallelism,  600K rows/s, 1.54MB/s
Parallelism: 3.4
Peak Memory: 9.99MB
0:03 [1.81M rows, 4.66MB] [600K rows/s, 1.54MB/s]

Query 20180615_202813_00006_3wjs7 failed: data channel is dictionary encoded but hash channel is not
com.google.common.base.VerifyException: data channel is dictionary encoded but hash channel is not
	at com.google.common.base.Verify.verify(Verify.java:122)
	at com.facebook.presto.operator.MultiChannelGroupByHash.canProcessDictionary(MultiChannelGroupByHash.java:476)
	at com.facebook.presto.operator.MultiChannelGroupByHash.addPage(MultiChannelGroupByHash.java:216)
	at com.facebook.presto.operator.aggregation.builder.InMemoryHashAggregationBuilder.processPage(InMemoryHashAggregationBuilder.java:162)
	at com.facebook.presto.operator.HashAggregationOperator.addInput(HashAggregationOperator.java:408)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:385)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
