### ISSUE TITLE
VerifyException exception when executing RIGHT OUTER JOIN

### ISSUE THREAD

**Issue by wyukawa** [prestodb/presto#9766]
Hi,

I use presto 0.192 + HDP 2.5.3 + hive connector.

VerifyException occured in the following query.
```
SELECT yyyymmdd FROM test_view WHERE yyyymmdd='20180117' LIMIT 1
```

view ddl
```
create or replace view test_view
as
select
    b.yyyymm
    , b.yyyymmdd
...
    , count(distinct ...) as ... 
from
    ... a
right outer join
    (select distinct yyyymmdd, substr(yyyymmdd,1,6) as yyyymm, ... from ... cross join ...) b
on
    a.yyyymmdd = b.yyyymmdd
    and ...
group by
    b.yyyymm
    , b.yyyymmdd
...
```

stacktrace
```
com.google.common.base.VerifyException: undefined
	at com.google.common.base.Verify.verify(Verify.java:99)
	at com.facebook.presto.operator.PartitionedLookupSource$OuterPositionTracker$Factory.getOuterPositionIterator(PartitionedLookupSource.java:299)
	at com.facebook.presto.operator.PartitionedLookupSource$1.getOuterPositionIterator(PartitionedLookupSource.java:65)
	at com.facebook.presto.operator.PartitionedLookupSourceFactory.getOuterPositionIterator(PartitionedLookupSourceFactory.java:362)
	at com.facebook.presto.operator.LookupJoinOperatorFactory$PerLifespanData.lambda$new$1(LookupJoinOperatorFactory.java:315)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:713)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:655)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:48)
	at com.facebook.presto.operator.ReferenceCount.release(ReferenceCount.java:55)
	at com.google.common.io.Closer.close(Closer.java:216)
	at com.facebook.presto.operator.LookupJoinOperator.close(LookupJoinOperator.java:514)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:496)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:667)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

If I modify view not to use ```right outer join``` in the following, error will be fixed although I'm not sure why
```
create or replace view test_view
as
select
    a.yyyymm
    , a.yyyymmdd
...
    , count(distinct ...) as ... 
from
    (select distinct yyyymmdd, substr(yyyymmdd,1,6) as yyyymm, ... from ... cross join ...) a
left outer join
  ... b
on
    a.yyyymmdd = b.yyyymmdd
    and ...
group by
    a.yyyymm
    , a.yyyymmdd
...
```

Thanks

**Comment by findepi** [comment]
@wyukawa , does the problem persist if you set the following before running your query:
```
set session hive.bucket_execution_enabled = false;
```

**Comment by wyukawa** [comment]
Yes, problem persists.

**Comment by findepi** [comment]
@wyukawa , thanks for checking. 
Are your tables partitioned on `yyyymmdd`?
Could you please try to reproduce the bug using simpler query? E.g. remove `cross join`, remove unnecessary columns, remove aggregations if they do not relate to this bug?

**Comment by wyukawa** [comment]
```yyyymmdd``` is the partitioned column.

I try to reproduce the bug using simpler query, but I can't..

This is the a little simpler query.
```
select
yyyymmdd
from
(
select
     b.yyyymmdd
    , b.test_id
from
    some_partitioned_table a
right outer join
    (select distinct yyyymmdd, test_id from some_non_partitioned_table cross join othere_non_partitioned_table) b
on
    a.yyyymmdd = b.yyyymmdd
    and a.test_id = b.test_id
group by
     b.yyyymmdd
    , b.test_id
)
WHERE yyyymmdd='20180117' LIMIT 1
```

**Comment by ebyhr** [comment]
Reproduced with following DDL on presto-product-tests docker, but it's not stable. Sometimes succeed and sometimes fail.  

```sql
create table default.some_partitioned_table(test_id int) partitioned by (yyyymmdd varchar(8));
create table default.some_non_partitioned_table(yyyymmdd varchar(8));
create table default.othere_non_partitioned_table(test_id int);
```

**Comment by findepi** [comment]
@ebyhr with these DDLs which query were you running to reproduce the issue? The one from @wyukawa's comment https://github.com/prestodb/presto/issues/9766#issuecomment-359654203?

**Comment by ebyhr** [comment]
@findepi  Yes, reproduced the issue with these DDLs and some INSERTs.

Below are entire steps. (I eliminated `cross join`)
```sql
/* Hive CLI */
create table default.some_partitioned_table(test_id int) partitioned by (yyyymmdd varchar(8));
create table default.some_non_partitioned_table(yyyymmdd varchar(8));
```

```sql
/* Presto CLI */
use hive.default;
insert into some_partitioned_table select 1, '20180117'; 
insert into some_non_partitioned_table select '20180117';

select
yyyymmdd
from
(
select
     b.yyyymmdd
from
    some_partitioned_table a
right outer join
    (select distinct yyyymmdd from some_non_partitioned_table) b
on
    a.yyyymmdd = b.yyyymmdd
group by
     b.yyyymmdd
)
WHERE yyyymmdd='20180117' LIMIT 1
;
--  10/10 of select queries were succeeded

insert into some_non_partitioned_table select '20180118';
--  8/10 of select queries were succeeded

insert into some_non_partitioned_table select '20180119';
--  3/10 of select queries were succeeded
```

**Comment by findepi** [comment]
Thanks @haozhun
