### ISSUE TITLE
Planner fails to create correct TopNRowNumber Node with invalid filters on row_number()

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#9779]
When there is a filter on row_number(), we tried to push down the filter and replace the Window operator with TopNRowNumber operator and a Filter operator on top. If the filter has invalid range the query will fail with the above error. 

```
presto:tiny> explain (type distributed) SELECT orderkey, orderdate, rank FROM (
    SELECT orderkey, orderdate, row_number() OVER ( PARTITION BY orderkey ORDER BY orderdate DESC) AS rank FROM orders) WHERE rank=-1;

Query 20180119_211226_00015_vy95y failed: maxRowCountPerPartition must be > 0

java.lang.IllegalArgumentException: maxRowCountPerPartition must be > 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.sql.planner.plan.TopNRowNumberNode.<init>(TopNRowNumberNode.java:60)
	at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.convertToTopNRowNumber(WindowFilterPushDown.java:260)
	at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:169)
	at com.facebook.presto.sql.planner.optimizations.WindowFilterPushDown$Rewriter.visitFilter(WindowFilterPushDown.java:84)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:72)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:84)
	at com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$0(SimplePlanRewriter.java:73)
...
```

This is because we use the range [1..upperbound in filter] as the limit of the TopNRowNumber, and enforce the upperbound must be greater than 0, therefore if the user uses some invalid range like row_number()=-1 the query will fail.

With a valid filter like WHERE row_number() between [99,100], the following plan was created:

```
explain (type distributed) SELECT orderkey, orderdate, rank FROM (SELECT orderkey, orderdate, row_number() OVER ( PARTITION BY orderkey ORDER BY orderdate DESC) AS rank FROM orders) WHERE rank<=10000 and rank >= 9999;
                                                                                          Query Plan
---------------------------------------------------------------------------------------------------- Fragment 0 [SINGLE]
     Output layout: [orderkey, orderdate, row_number_2]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Output[orderkey, orderdate, rank] => [orderkey:bigint, orderdate:date, row_number_2:bigint]
             rank := row_number_2
         - RemoteSource[1] => [orderkey:bigint, orderdate:date, row_number_2:bigint]

 Fragment 1 [tpch:orders:15000]
     Output layout: [orderkey, orderdate, row_number_2]
     Output partitioning: SINGLE []
     Execution Flow: UNGROUPED_EXECUTION
     - Filter[filterPredicate = (("row_number_2" <= BIGINT '10000') AND ("row_number_2" >= BIGINT '9999'))] => [orderkey:bigint, orderdate:date, row_number_2:bigint]
         - Project[] => [orderkey:bigint, orderdate:date, row_number_2:bigint]
             - TopNRowNumber[partition by (orderkey), order by (orderdate DESC_NULLS_LAST) limit 10000][$hashvalue] => [orderkey:bigint, orderdate:date, $hashvalue:bigint, row_number_2:bigint]
                     row_number_2 := row_number()
                 - ScanProject[table = tpch:tpch:orders:sf0.01, originalConstraint = true] => [orderkey:bigint, orderdate:date, $hashvalue:bigint]
                         Cost: {rows: 15000, bytes: ?}/{rows: 15000, bytes: ?}
                         $hashvalue := "combine_hash"(BIGINT '0', COALESCE("$operator$hash_code"("orderkey"), 0))
                         orderkey := tpch:orderkey
                         orderdate := tpch:orderdate
```

One interesting thing to notice is that no matter how narrow the filter range(lb, ub) is we always use TopNRowNumber(1..ub) then apply the filter on top of it. In the above query we have limit 10000 (range [1..10000] for this TopNRowNumber, which is not always helpful.

**Comment by martint** [comment]
Fix merged
