### ISSUE TITLE
HivePageSink causes full GC when flushing huge pages.

### ISSUE THREAD

**Issue by highker** [prestodb/presto#9859]
`HivePageSink` can continuously trigger full GC (even after the query has been killed) when trying to flush a huge page. #9153 exposes stats for this.

Full GC histogram:

```
num     #instances         #bytes  class name
----------------------------------------------
   1:     481767171    75296633088  [B
   2:       4693181    50365274960  [I
   3:     433751102    13880035264  org.apache.hadoop.io.Text
   4:      73335289    11147116744  [Ljava.util.HashMap$Node;
   5:       4554529    10721486784  [J
   6:     221214657    10618303536  java.util.HashMap$Node
   7:      73642027     4713089728  java.util.HashMap
   8:       7930144     3941856176  [Z
   9:      72295238     3470171424  java.util.Collections$UnmodifiableMap
```

stacktrace:
```
2017-10-11T16:09:41.045-0700    WARN    TaskExecutor    com.facebook.presto.execution.executor.TaskExecutor     Split thread 20171011_224756_23576_nimje.1.282-7 has been running longer than 17.56m
java.lang.Exception: Long running split
        at java.util.HashMap$HashIterator.<init>(HashMap.java:1425)
        at java.util.HashMap$EntryIterator.<init>(HashMap.java:1469)
        at java.util.HashMap$EntrySet.iterator(HashMap.java:1013)
        at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$1.<init>(Collections.java:1655)
        at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.iterator(Collections.java:1654)
        at org.apache.hadoop.hive.serde2.lazybinary.LazyBinarySerDe.serialize(LazyBinarySerDe.java:533)
        at org.apache.hadoop.hive.serde2.lazybinary.LazyBinarySerDe.serialize(LazyBinarySerDe.java:499)
        at org.apache.hadoop.hive.serde2.columnar.OptimizedLazyBinaryColumnarSerde.serialize(OptimizedLazyBinaryColumnarSerde.java:69)
        at com.facebook.presto.hive.RecordFileWriter.appendRow(RecordFileWriter.java:143)
        at com.facebook.presto.hive.RecordFileWriter.appendRows(RecordFileWriter.java:126)
        at com.facebook.presto.hive.HiveWriter.append(HiveWriter.java:59)
        at com.facebook.presto.hive.HivePageSink.writePage(HivePageSink.java:293)
        at com.facebook.presto.hive.HivePageSink.doAppend(HivePageSink.java:257)
        at com.facebook.presto.hive.HivePageSink.lambda$appendPage$2(HivePageSink.java:243)
        at com.facebook.presto.hive.HivePageSink$$Lambda$1075/1289405281.run(Unknown Source)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
        at com.facebook.presto.hive.authentication.HdfsAuthentication$$Lambda$1079/1077010884.run(Unknown Source)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:85)
        at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:243)
        at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:49)
        at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:203)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:343)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver$$Lambda$710/168934548.get(Unknown Source)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)



2017-10-11T15:16:51.307-0700    WARN    TaskExecutor    com.facebook.presto.execution.executor.TaskExecutor     Split thread 20171011_214216_22570_nimje.1.282-7 has been running longer than 17.03m
java.lang.Exception: Long running split
        at org.apache.hadoop.hive.common.io.NonSyncByteArrayOutputStream.enLargeBuffer(NonSyncByteArrayOutputStream.java:77)
        at org.apache.hadoop.hive.common.io.NonSyncByteArrayOutputStream.write(NonSyncByteArrayOutputStream.java:95)
        at org.apache.hadoop.hive.serde2.lazybinary.LazyBinaryUtils.writeVLong(LazyBinaryUtils.java:415)
        at org.apache.hadoop.hive.serde2.lazybinary.LazyBinaryUtils.writeVInt(LazyBinaryUtils.java:338)
        at org.apache.hadoop.hive.serde2.lazybinary.LazyBinarySerDe.serialize(LazyBinarySerDe.java:528)
        at org.apache.hadoop.hive.serde2.lazybinary.LazyBinarySerDe.serialize(LazyBinarySerDe.java:499)
        at org.apache.hadoop.hive.serde2.columnar.OptimizedLazyBinaryColumnarSerde.serialize(OptimizedLazyBinaryColumnarSerde.java:69)
        at com.facebook.presto.hive.RecordFileWriter.appendRow(RecordFileWriter.java:143)
        at com.facebook.presto.hive.RecordFileWriter.appendRows(RecordFileWriter.java:126)
        at com.facebook.presto.hive.HiveWriter.append(HiveWriter.java:59)
        at com.facebook.presto.hive.HivePageSink.writePage(HivePageSink.java:293)
        at com.facebook.presto.hive.HivePageSink.doAppend(HivePageSink.java:257)
        at com.facebook.presto.hive.HivePageSink.lambda$appendPage$2(HivePageSink.java:243)
        at com.facebook.presto.hive.HivePageSink$$Lambda$1097/691869595.run(Unknown Source)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:24)
        at com.facebook.presto.hive.authentication.HdfsAuthentication$$Lambda$1099/1262691601.run(Unknown Source)
        at com.facebook.presto.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at com.facebook.presto.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:23)
        at com.facebook.presto.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:85)
        at com.facebook.presto.hive.HivePageSink.appendPage(HivePageSink.java:243)
        at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:49)
        at com.facebook.presto.operator.TableWriterOperator.addInput(TableWriterOperator.java:203)
        at com.facebook.presto.operator.Driver.processInternal(Driver.java:343)
        at com.facebook.presto.operator.Driver.lambda$processFor$6(Driver.java:241)
        at com.facebook.presto.operator.Driver$$Lambda$714/46585330.get(Unknown Source)
        at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:614)
        at com.facebook.presto.operator.Driver.processFor(Driver.java:235)
        at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:622)
        at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
        at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:485)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ashubhumca** [comment]
Do we have any update on this issue?

**Comment by highker** [comment]
This is using old hive writer. Use optimized ORC writer instead.
