### ISSUE TITLE
Presto won't start with LDAP authentication

### ISSUE THREAD

**Issue by chafidz0000000** [prestodb/presto#9873]
Currently I'm trying to build Presto in EMR. with emr-5.11.0 running presto 0.187. I'm trying to use ldap as authenticator. Since I don't wanna use Amazon's simple AD (cause cost), I installed openldap in coordinator node. Everything on openldap side works, and successfully tried using ldapsearch

`ldapsearch -x -H ldaps://ip-x-x-x-x:636 -b ou=People,dc=ip-x-x-x-x`

and my ldap settings on presto are:

```
http-server.authentication.type=LDAP
authentication.ldap.url=ldaps://ip-x-x-x-x:636
authentication.ldap.user-bind-pattern=uid=${USER},ou=People,dc=ip-x-x-x-x

```
but when I start the server, it shows errors in server.log

```
2018-01-31T09:16:12.051Z        ERROR        main        com.facebook.presto.server.PrestoServer        Unable to create injector, see the following errors:

3 errors
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:93)
  while locating com.facebook.presto.server.security.LdapFilter
  at com.facebook.presto.server.security.ServerSecurityModule.lambda$setup$3(ServerSecurityModule.java:53) (via modules: com.facebook.presto.server.security.ServerSecurityModule -> io.airlift.configuration.ConditionalModule -> com.facebook.presto.server.security.ServerSecurityModule$$Lambda$27/90567568)
  while locating javax.servlet.Filter annotated with @com.google.inject.multibindings.Element(setName=@io.airlift.http.server.TheServlet,uniqueId=355, type=MULTIBINDER, keyType=)
  at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:68) (via modules: io.airlift.http.server.HttpServerModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<javax.servlet.Filter> annotated with @io.airlift.http.server.TheServlet()
    for parameter 4 at io.airlift.http.server.HttpServerProvider.<init>(HttpServerProvider.java:74)
  while locating io.airlift.http.server.HttpServerProvider
  at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:64)
  while locating io.airlift.http.server.HttpServer
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.facebook.presto.server.security.LdapFilter$Credentials.<init>(LdapFilter.java:405)
	at com.facebook.presto.server.security.LdapFilter$Credentials.<init>(LdapFilter.java:398)
	at com.facebook.presto.server.security.LdapFilter.checkEnvironment(LdapFilter.java:136)
	at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:130)
	at com.facebook.presto.server.security.LdapFilter$$FastClassByGuice$$83dfbaea.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:375)
	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:258)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:116)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

2) Error injecting constructor, java.lang.NullPointerException
  at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:93)
  while locating com.facebook.presto.server.security.LdapFilter
  at com.facebook.presto.server.security.ServerSecurityModule.lambda$setup$3(ServerSecurityModule.java:53) (via modules: com.facebook.presto.server.security.ServerSecurityModule -> io.airlift.configuration.ConditionalModule -> com.facebook.presto.server.security.ServerSecurityModule$$Lambda$27/90567568)
  while locating javax.servlet.Filter annotated with @com.google.inject.multibindings.Element(setName=@io.airlift.http.server.TheServlet,uniqueId=355, type=MULTIBINDER, keyType=)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.facebook.presto.server.security.LdapFilter$Credentials.<init>(LdapFilter.java:405)
	at com.facebook.presto.server.security.LdapFilter$Credentials.<init>(LdapFilter.java:398)
	at com.facebook.presto.server.security.LdapFilter.checkEnvironment(LdapFilter.java:136)
	at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:130)
	at com.facebook.presto.server.security.LdapFilter$$FastClassByGuice$$83dfbaea.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:116)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

3) Error injecting constructor, java.lang.NullPointerException
  at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:93)
  while locating com.facebook.presto.server.security.LdapFilter
  at com.facebook.presto.server.security.ServerSecurityModule.lambda$setup$3(ServerSecurityModule.java:53) (via modules: com.facebook.presto.server.security.ServerSecurityModule -> io.airlift.configuration.ConditionalModule -> com.facebook.presto.server.security.ServerSecurityModule$$Lambda$27/90567568)
  while locating javax.servlet.Filter annotated with @com.google.inject.multibindings.Element(setName=@io.airlift.http.server.TheServlet,uniqueId=355, type=MULTIBINDER, keyType=)
  at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:68) (via modules: io.airlift.http.server.HttpServerModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
  while locating java.util.Set<javax.servlet.Filter> annotated with @io.airlift.http.server.TheServlet()
    for parameter 4 at io.airlift.http.server.HttpServerProvider.<init>(HttpServerProvider.java:74)
  while locating io.airlift.http.server.HttpServerProvider
  at io.airlift.http.server.HttpServerModule.configure(HttpServerModule.java:64)
  while locating io.airlift.http.server.HttpServer
  at org.weakref.jmx.guice.GuiceMBeanExporter.<init>(GuiceMBeanExporter.java:34)
  at org.weakref.jmx.guice.MBeanModule.configure(MBeanModule.java:38)
  while locating org.weakref.jmx.guice.GuiceMBeanExporter
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.facebook.presto.server.security.LdapFilter$Credentials.<init>(LdapFilter.java:405)
	at com.facebook.presto.server.security.LdapFilter$Credentials.<init>(LdapFilter.java:398)
	at com.facebook.presto.server.security.LdapFilter.checkEnvironment(LdapFilter.java:136)
	at com.facebook.presto.server.security.LdapFilter.<init>(LdapFilter.java:130)
	at com.facebook.presto.server.security.LdapFilter$$FastClassByGuice$$83dfbaea.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:375)
	at com.google.inject.multibindings.Multibinder$RealMultibinder.get(Multibinder.java:258)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1047)
	at org.weakref.jmx.guice.GuiceMBeanExporter.export(GuiceMBeanExporter.java:73)
	at org.weakref.jmx.guice.GuiceMBeanExporter.<init>(GuiceMBeanExporter.java:35)
	at org.weakref.jmx.guice.GuiceMBeanExporter$$FastClassByGuice$$6cc63b28.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:116)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:242)
	at com.facebook.presto.server.PrestoServer.run(PrestoServer.java:116)
	at com.facebook.presto.server.PrestoServer.main(PrestoServer.java:67)
```

What went wrong, is completely puzzled me, please advice.

Thank you

**Comment by andredigenova** [comment]
I had the same issue and worked around it by adding 

internal-communication.authentication.ldap.user=<some valid user>
internal-communication.authentication.ldap.password=<some valid password>

to my config on the master node and that fixed it. Wasn't necessary for the core nodes though for some reason.

**Comment by chafidz0000000** [comment]
So we need a special bind user to for Presto to internally authenticating itself, even when anonymous bind is available?

**Comment by andredigenova** [comment]
Not sure if it is a bug or not, but I couldn't get it to work with anonymous bind. Monitoring traffic to my LDAP server, Presto didn't even hit LDAP before it crashed with the error you copy/pasted above.

**Comment by chafidz0000000** [comment]
Thanks @andredigenova , it works now.
