### ISSUE TITLE
Lambda function couldn't be found in FunctionRegistry if return type is a literal varchar

### ISSUE THREAD

**Issue by yingsu00** [prestodb/presto#9880]
E.g. REGEXP_REPLACE('abbabba', 'abba', x -> 'm') doesn't work
but REGEXP_REPLACE('abbabba', 'abba', x -> VARCHAR 'm') works

The error is like:

com.facebook.presto.sql.analyzer.SemanticException: Unexpected parameters (varchar(7), varchar(4), com.facebook.presto.sql.analyzer.TypeSignatureProvider@6ee660fb) for function regexp_replace. Expected: regexp_replace(varchar(x), Re2JRegExp, varchar(y)) , regexp_replace(varchar, Re2JRegExp, function(array(varchar),varchar)) , regexp_replace(varchar(x), Re2JRegExp) 

	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.resolveFunction(ExpressionAnalyzer.java:1363)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:818)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:288)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:119)
	at com.facebook.presto.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:26)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:309)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:259)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressions(ExpressionAnalyzer.java:1485)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpressionsWithSymbols(ExpressionAnalyzer.java:1438)
	at com.facebook.presto.operator.scalar.FunctionAssertions.createExpression(FunctionAssertions.java:747)
	at com.facebook.presto.operator.scalar.FunctionAssertions.executeProjectionWithAll(FunctionAssertions.java:574)
	at com.facebook.presto.operator.scalar.FunctionAssertions.selectUniqueValue(FunctionAssertions.java:303)
	at com.facebook.presto.operator.scalar.FunctionAssertions.selectSingleValue(FunctionAssertions.java:298)
	at com.facebook.presto.operator.scalar.FunctionAssertions.assertFunction(FunctionAssertions.java:261)
	at com.facebook.presto.operator.scalar.AbstractTestFunctions.assertFunction(AbstractTestFunctions.java:99)
	at com.facebook.presto.operator.scalar.TestRegexpFunctions.testRegexpReplaceLambda(TestRegexpFunctions.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

**Comment by findepi** [comment]
This is probably because `'m'` has type `varchar(1)` (could probably be `char(1)`, but it's not), whereas `VARCHAR 'm'` has type `varchar` (not sure why):
```
presto> select typeof('m'), typeof(varchar 'm');
   _col0    |  _col1
------------+---------
 varchar(1) | varchar
```

**Comment by findepi** [comment]
Of course, this should just work.
