### ISSUE TITLE
Race condition in OuterPositionTracker

### ISSUE THREAD

**Issue by dain** [prestodb/presto#9881]
We saw an error in the OuterPositionTracker, where the outer position iterator is being fetched while there are still reference counts. 

I think this might be caused because the query was tearing down due to a limit.  Here is the stack.
```
com.google.common.base.VerifyException
	at com.google.common.base.Verify.verify(Verify.java:99)
	at com.facebook.presto.operator.PartitionedLookupSource$OuterPositionTracker$Factory.getOuterPositionIterator(PartitionedLookupSource.java:299)
	at com.facebook.presto.operator.PartitionedLookupSource$1.getOuterPositionIterator(PartitionedLookupSource.java:65)
	at com.facebook.presto.operator.PartitionedLookupSourceFactory.getOuterPositionIterator(PartitionedLookupSourceFactory.java:362)
	at com.facebook.presto.operator.LookupJoinOperatorFactory$PerLifespanData.lambda$new$1(LookupJoinOperatorFactory.java:315)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:239)
	at com.google.common.util.concurrent.AbstractTransformFuture$TransformFuture.doTransform(AbstractTransformFuture.java:229)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.setFuture(AbstractFuture.java:713)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:221)
	at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.setResult(AbstractTransformFuture.java:200)
	at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:177)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:902)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:813)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:655)
	at com.google.common.util.concurrent.SettableFuture.set(SettableFuture.java:48)
	at com.facebook.presto.operator.ReferenceCount.release(ReferenceCount.java:55)
	at com.google.common.io.Closer.close(Closer.java:216)
	at com.facebook.presto.operator.LookupJoinOperator.close(LookupJoinOperator.java:514)
	at com.facebook.presto.operator.Driver.destroyIfNecessary(Driver.java:496)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:667)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at com.facebook.presto.execution.executor.LegacyPrioritizedSplitRunner.process(LegacyPrioritizedSplitRunner.java:23)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by findepi** [comment]
@dain this has already been reported as https://github.com/prestodb/presto/issues/9766 and that issue contains some probabilitic repro steps. Closing this one.
