### ISSUE TITLE
Reading from information_schema.columns for MySQL connector may fail when table removed in the mean time

### ISSUE THREAD

**Issue by findepi** [prestodb/presto#9945]
(Observed on Travis: https://travis-ci.org/prestodb/presto/jobs/340517292)

Steps to reproduce
1. Annotate `com.facebook.presto.plugin.mysql.TestMySqlIntegrationSmokeTest#testDropTable` with `@Test(invocationCount = 100)`
1. Annotate `com.facebook.presto.tests.AbstractTestIntegrationSmokeTest#testSelectInformationSchemaColumns` with `@Test(invocationCount = 100)`
1. Run `TestMySqlIntegrationSmokeTest` with test methods in parallel, e.g. using testng suite file:
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="TestAll">
    <test name="a1" parallel="methods">
        <classes>
            <class name="com.facebook.presto.plugin.mysql.TestMySqlIntegrationSmokeTest" />
        </classes>
    </test>
</suite>
```

Observed `testSelectInformationSchemaColumns` fails sometimes with
```
java.lang.AssertionError: Execution of 'actual' query failed: SELECT column_name FROM information_schema.columns WHERE table_catalog = 'something_else'

	at org.testng.Assert.fail(Assert.java:83)
	at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:87)
	at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:120)
	at com.facebook.presto.tests.AbstractTestIntegrationSmokeTest.testSelectInformationSchemaColumns(AbstractTestIntegrationSmokeTest.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.facebook.presto.spi.PrestoException: Table 'tpch.test_drop' doesn't exist
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:218)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.getTableMetadata(JdbcMetadata.java:95)
	at com.facebook.presto.plugin.jdbc.JdbcMetadata.listTableColumns(JdbcMetadata.java:136)
	at com.facebook.presto.metadata.MetadataManager.listTableColumns(MetadataManager.java:433)
	at com.facebook.presto.metadata.MetadataListing.listTableColumns(MetadataListing.java:93)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.buildColumns(InformationSchemaPageSourceProvider.java:150)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInformationSchemaTable(InformationSchemaPageSourceProvider.java:128)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.getInternalTable(InformationSchemaPageSourceProvider.java:122)
	at com.facebook.presto.connector.informationSchema.InformationSchemaPageSourceProvider.createPageSource(InformationSchemaPageSourceProvider.java:80)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
	at com.facebook.presto.operator.ScanFilterAndProjectOperator.getOutput(ScanFilterAndProjectOperator.java:224)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
	at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:278)
	at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:645)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:272)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:975)
	at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:492)
	... 3 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'tpch.test_drop' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2441)
	at com.mysql.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2339)
	at com.mysql.jdbc.IterateBlock.doForAll(IterateBlock.java:50)
	at com.mysql.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2337)
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:527)
	at com.facebook.presto.plugin.jdbc.BaseJdbcClient.getColumns(BaseJdbcClient.java:196)
	... 20 more
```

**Comment by findepi** [comment]
Apparently, despite sharing code base, `postgresql` connector doesn't seem to have this problem.

**Comment by findepi** [comment]
addressed by https://github.com/prestodb/presto/pull/9949

**Comment by electrum** [comment]
This is actually a bug (race condition) in the MySQL driver. Fortunately, they have magic flag to fix it (which is of course off by default).

**Comment by electrum** [comment]
We see this fail constantly in our internal Jenkins.
